### ISSUE TITLE
Cannot restore backup on Xiaomi Poco F2 Pro

### ISSUE THREAD

**Issue by GrandGamer** [signalapp/Signal-Android#10053]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When trying to restore a backup on a new device, the application reaches 12801 messages, jumpts to 12901 messages and crashes every time. I've tried reinstalling the app multiple times and installing the beta version of the app, same issue.

### Steps to reproduce
- Install application from Play Store
- Start application
- Press **Continue**
- Press **Restore Backup**
- Insert backup passphrase

**Actual result:** Application starts restoring messages and crashes once it reaches 12901 crashes. Application storage data also keeps increasing every time I attempt to execute the backup. 
**Expected result:** Application restores the backup and continues to the re-register process.

### Device info
**Device:** Xiaomi Poco F2 Pro
**MIUI version:** 12.0.2(QJKEUXM)
**Android version:** 10 QKQ1.191117.002
**Signal version:** 4.71.5 and 4.72.5

### Debug Log
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
	at java.lang.System.arraycopy(System.java:527)
	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:327)
	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:267)
	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:77)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:201)
	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:193)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

**Comment by GrandGamer** [comment]
After some digging around I decided  to check if the backup file was transferred correctly. I transferred the file through **Syncthing** between the two phones. It appears that the **file was corrupted** during transfer on the new phone. I transferred it through USB and it worked as intended.
