### ISSUE TITLE
Cluttered log file

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#10105]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
There is that one warning that appears over and over again in the logs. I'd usually not complain about something in the debug logs but the message appears 240 in the log and has a pretty long stack trace. All in all, more than 10,000 of  about 12,000 lines are because of it.

Apart from making it hard to find anything it appears also that the log covers no more than the last 20 minutes now. I at least suspect that's related.

The error message:

```
2020-10-20 08:56:57.959 GMT+02:00 W KeyboardAwareLinearLayout: field reflection error when measuring view inset
2020-10-20 08:56:57.959 GMT+02:00 W KeyboardAwareLinearLayout: java.lang.NoSuchFieldException: No field mAttachInfo in class Landroid/view/View; (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes3.dex)
2020-10-20 08:56:57.959 GMT+02:00 W KeyboardAwareLinearLayout: 	at java.lang.Class.getDeclaredField(Native Method)
2020-10-20 08:56:57.959 GMT+02:00 W KeyboardAwareLinearLayout: 	at org.thoughtcrime.securesms.components.KeyboardAwareLinearLayout.getViewInset(KeyboardAwareLinearLayout.java:124)
2020-10-20 08:56:57.959 GMT+02:00 W KeyboardAwareLinearLayout: 	at org.thoughtcrime.securesms.components.KeyboardAwareLinearLayout.updateKeyboardState(KeyboardAwareLinearLayout.java:98)
2020-10-20 08:56:57.959 GMT+02:00 W KeyboardAwareLinearLayout: 	at org.thoughtcrime.securesms.components.KeyboardAwareLinearLayout.onMeasure(KeyboardAwareLinearLayout.java:84)

```

### Steps to reproduce
- n/a

**Actual result:** log goes back about 20 minutes
**Expected result:** log cover reasonable amount of time

### Device info

**Device:** Motorola One
**Android version:** 10
**Signal version:** 4.74.2

### Link to debug log
https://debuglogs.org/0bad86988069397943bfa51e1e7a28756adc525f952f7342215ccb5d5a043505

**Comment by RensOliemans** [comment]
This doesn't seem to happen for everyone. It is also present in my debug log (issue #10110), but #10109 (same Signal version, although their Android version is older) doesn't have these lines in the debug logs.

**Comment by greyson-signal** [comment]
Thanks, this has been mitigated in 4.75
