### ISSUE TITLE
Signal 4.72.5 does not Auto-Update to Signal 4.74.3

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [signalapp/Signal-Android#10124]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I running a long time an very old instance of Signal. I seem that the Signal Web APK had some problems with autoupdates.

### Steps to reproduce
- Download and install Signal 4.72.5 > https://updates.signal.org/android/Signal-website-universal-release-4.72.5.apk
- Start the app and there is no update-promt (to Signal 4.74.3 atm)

**Actual result:** no update-promt with outdatet web-apk-release
**Expected result:** There should be a immediately before a new user starts an init-setup of signal

### Device info 1

**Device:** Sony Xperia E5823
**Android version:** 7.1.2
**Signal version:** 4.72.5

### Device info 2

**Device:** Xiaomi mi 9t
**Android version:** 10
**Signal version:** 4.72.5

### Link to debug log (Sony Xperia E5823)
https://debuglogs.org/ad4552ac74386eb53b15fec2adc89c4f8870f892950fb8c40fb60c0bf0dce6eb

**Comment by cody-signal** [comment]
Did this occur before? And to clarify, this prior to device/account registration and not just having a version and landing on the conversation list screen and not seeing an update banner?

**Comment by sorryusernameisalreadytaken** [comment]
Difficult to answer if this happened before. My dealy phone is the mi-9t and I wait and wait and wait for the release with group-delete messeage feature and was confused why I am not able to do this. So I checked the page and see that there was an update and did it manually. This was today.
So my mi-9t phone stuck on a unknown version.

Now I reproduced it with a non-daily-driver phone and I did not see an update promt within thre first 30 minutes of use fake-use.

Sorry, does this answer your question? :-D

For this is really important, mostly for security reasons. When my singal does not update from web-rls I could have non patched security bug.
And it seems I am not alone:
https://www.reddit.com/r/signal/comments/h9g1q8/no_automatic_update_of_website_apk_installation/

**Comment by eNTi** [comment]
This happens for me too every other release. Not using play store.

**Comment by hiqua** [comment]
I've had the same problem for quite some time, hard to say since when exactly, since I just updated through the website, thinking that it was just slow to notice an update. Now I've read somewhere that it's supposed to check updates every six hours, so it was indeed a bug somewhere.

I've just updated to Signal 4.75.8 via https://signal.org/android/apk/, I'll check within the next two weeks if I get updates once they're one the website (I assume that we're supposed to get the updates at the same time as they are on the website).

Is there any way to get meaningful logs reliably for the update mechanism? Since it cannot be triggered manually, we would have to periodically check the logs to find the corresponding logs, but that's quite a hassle.

**Comment by hiqua** [comment]
It just worked for me from 4.75.8 to 4.76.3.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> It just worked for me from 4.75.8 to 4.76.3.

Uh thx for this infroamtion.

Can you tell me your:
- Android Version
- If you run a custom-rom, wich one
- Did you use MicroG | Gapps or stock-Rom with Google or stock-Rom with Huawei-Store

**Comment by eNTi** [comment]
I've recently reinstalled Signal-APK and since the last two versions the updater works for me.

Running rooted, LineageOS 7.1.2, No MicroG, no Gapps.

**Comment by hiqua** [comment]
Well it doesn't seem to be working now from 76.3 to 4.78.5, not sure why, but I have a log:
https://debuglogs.org/e2b47e52a1e594840edc1835e75258879137fc5c4155dd535feff6d9820d482d

In particular:
```
[4.76.3] 2020-12-02 10:25:54.772 GMT+01:00 I UpdateApkJob: Got descriptor: [7460, 4.78.5, https://updates.signal.org/android/Signal-website-prod-universal-release-4.78.5.apk]
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: null
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: java.io.FileNotFoundException: No filename found.
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at android.app.DownloadManager.openDownloadedFile(DownloadManager.java:1149)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.getDigestForDownloadId(UpdateApkJob.java:186)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.getDownloadStatus(UpdateApkJob.java:136)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.onRun(UpdateApkJob.java:88)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
[4.76.3] 2020-12-02 10:25:55.049 GMT+01:00 W UpdateApkJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
[4.76.3] 2020-12-02 10:25:55.068 GMT+01:00 I UpdateApkJob: Download status: PENDING
[4.76.3] 2020-12-02 10:25:55.069 GMT+01:00 I JobRunner: [JOB::044cec07-71e1-42e3-ac5d-6c6e8b1c209f][UpdateApkJob][3] Job finished with result SUCCESS in 651 ms. (Time Since Submission: 93860 ms, Lifespan: Immortal, Run Attempt: 1/2)
```

I'm not getting any notification regarding a possible update, and I don't think Signal downloads the APK before asking, does it? Then it shouldn't expect the .apk to exist, right?

**Comment by eNTi** [comment]
Nope... doesn't look like it.

**Comment by hiqua** [comment]
Still nothing:

https://debuglogs.org/15679461ae6d01456003b201b98b35d056b426b6b7ff28c76cd5c351153e6b2d

@sorryusernameisalreadytaken could you open this issue again? Otherwise I'll create a new one.

In the meantime I'll install the new apk directly from https://signal.org/android/apk/ to check whether I get the same behavior, meaning updating from a manually installed apk works once but stop working afterwards which is my current situation:

* 4.75.8 to 4.76.3 auto update worked after I installed 4.75.8 manually
* 4.76.3 to 4.78.5 is not happening

**Comment by hiqua** [comment]
Just got the update, I guess it was just because of the digest issue (https://github.com/signalapp/Signal-Android/issues/10255). I guess we can close for now, I'll comment if I get the issue again.
