### ISSUE TITLE
crash saving audio files

### ISSUE THREAD

**Issue by tsonntig** [signalapp/Signal-Android#10159]
Signal crash if i try following:

1. Open signal 
2. Settings
3. Storage
4. Select all audio files
5. Save

https://debuglogs.org/71bb604fbef289795ca6cff4b2e2c2cc9fee8f10f12b9b0748c4a7fa618aa119

![Screenshot_20201102-073825](https://user-images.githubusercontent.com/6700569/97837954-82a3f500-1cdf-11eb-8175-fa6e00d97aa3.png)
![Screenshot_20201102-073919](https://user-images.githubusercontent.com/6700569/97837997-98b1b580-1cdf-11eb-9488-80329fb3810a.png)
![Screenshot_20201102-073946](https://user-images.githubusercontent.com/6700569/97838005-9c453c80-1cdf-11eb-8f36-63ccae87b181.png)

**Comment by greyson-signal** [comment]
Crash for reference:

```java
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: java.lang.RuntimeException: An error occurred while executing doInBackground()
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:761)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Parcel.readException(Parcel.java:1697)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.content.ContentResolver.insert(ContentResolver.java:1325)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.createOutputUri(SaveAttachmentTask.java:185)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:97)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:75)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:32)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2020-11-02 07:18:17.161 MEZ E SignalUncaughtExceptionHandler: 	... 3 more
```

**Comment by 0xnor0** [comment]
Same behavoir with saving photos:
https://debuglogs.org/daa5b8b9a42a2e47f67ef6116938d7b30817cab7c1f07ddf3e72598337e5fcac

**Comment by decimo1** [comment]
Android 6.0.1 Signal 4.76.3
I have the same problem for saving audio files where the app crashes when trying. 
File size doesn't matter. With photos it shows "Error with saving attachments to storage!" and doesn't crash.

Workaround for the photos is to create a "Pictures" folder on Internal Storage manually because Signal fails to create it.

If someone knows where Audio files are normally saved we could try this workaround for that too.

**Comment by decimo1** [comment]
Still the same problem on 4.77.3

**Comment by liayn** [comment]
suspects https://github.com/signalapp/Signal-Android/commit/dc64a186d55a84444b294b0d9981cf2fe7be63c9 or https://github.com/signalapp/Signal-Android/commit/a264d10685620d7f3fe00350adafd2ed972f088e

**Comment by Frivolous2** [comment]
Happens to me when I try to play some voice notes as well.

**Comment by unhammer** [comment]
What folder do I have to create to save videos then?

**Comment by decimo1** [comment]
Does anyone who sees this thread know where Videos and Voice Notes get saved to normally? Pictures get saved in Pictures in Internal Storage. For Videos it does not work with Videos or Pictures/Videos.

**Comment by liayn** [comment]
> Does anyone who sees this thread know where Videos and Voice Notes get saved to normally? Pictures get saved in Pictures in Internal Storage. For Videos it does not work with Videos or Pictures/Videos.

Goes into the `video` folder on my android 8

**Comment by unhammer** [comment]
Wow. I had `Movies` and `Videos`, but I had to make the directory `video` and then it managed to save the file.

**This seems like it should be easy to fix?**

**Comment by liayn** [comment]
@unhammer IMO you at the wrong issue with your request. This is about saving audio files, which does not work, whereas saving video files does work.

**Comment by decimo1** [comment]
> @unhammer IMO you at the wrong issue with your request. This is about saving audio files, which does not work, whereas saving video files does work.

Yep, apparently these are different issues. Pictures and videos kann only be saved by making a "Pictures" and "video" folder manually. But for audio Signal crashes, whereas for Pictures and videos it shows an Error (if you don't have the folders) and doesn't crash.

**Comment by DirkPitt1** [comment]
Can confirm that saving audio files works in 5.0.3.

However the second part of my closed and linked here issue #10249 still remains a problem.

Saving videos still ends with 'Error while saving attachment to storage!' and exception

> SaveAttachmentTask: java.io.FileNotFoundException: No such file or directory

https://debuglogs.org/f117a74078106d138b02632a1524e71a211e5c221dbe0c4aa2f80982373ab87d

And another issue with saving pdf on other device with similar exception

> SaveAttachmentTask: java.io.FileNotFoundException: /storage/emulated/0/Download/[Redacted].pdf (No such file or directory)

https://debuglogs.org/29937774339ef85c32856e8deba7befb9a6331d201615de31cbd60eaf214ce4f

**Comment by decimo1** [comment]
@DirkPitt1 You can try creating the folders "Pictures" and "video" manually for a quick fix.

I'll have to try out version 5.0.3 for the audio files as well.

**Comment by decimo1** [comment]
5.0.8 fixed the issue for me, too. I think this can be closed. 
The fact that Signal cannot create the folders "Pictures" "video" and the one for audio files is a different issue which should get it's own Issue here. 
Thank you to the team and fumiakiy who apparently fixed this! :)

**Comment by decimo1** [comment]
* The folder for Audio files is "Music" on my phone. If you are having the "Error while saving attachment to storage!" problem, then creating that folder will fix it.

**Comment by liayn** [comment]
Confirmed. Seems to work again with v5.0.5
