### ISSUE TITLE
Sharing a picture from system gallery resulted in empty message

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [signalapp/Signal-Android#10160]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I shared a photo out of the gallery with "share" button, as usual and it resulted in an empty message

### Steps to reproduce
- taken a photo
- clicked in the corner to enter gallery
- clicked "share" button 
- clicked send
I wasn't able to repeat it. It happened once.

**Actual result:** A picture sent to the recipient
**Expected result:** An empty message.

### Screenshots
![signal-2020-11-02-121649](https://user-images.githubusercontent.com/11697819/97863197-e392f380-1d06-11eb-8d00-2d2aee6d4f1c.jpeg)

### Device info
**Device:** Xiaomi Redmi Note 9 Pro
**Android version:** 10 QP1A.190711.020
**Signal version:** 4.75.7

### Link to debug log
https://debuglogs.org/be52d75964aadc974bcd77727b4f7ee797c0904bfd06b4887e96a6ca7f01a00b

**Comment by Nisc3d** [comment]
This looks like the issue #10072 I reported, but instead of an image description the message is empty, because the sender didn't write any text to the image.

**Comment by Nisc3d** [comment]
This happened again to a friend. She sent 3 pictures in a row quickly, but 2 messages were deleted. One resulted in an empty message and a weird glitch on the right side. She sent them directly from signal, not over the gallery.

![grafik](https://user-images.githubusercontent.com/7361310/101288967-a9cb7600-37f9-11eb-943f-70bf2bd87925.png)

Debug Log:
https://debuglogs.org/d38c53e08a5d5f86ff61c812dc54d17672b2d8993431f054c82cebbb7ad09819

I think these are the relevant lines:

> 2020-12-06 19:11:12.087 MEZ D AttachmentUploadJob: Using attachments V3
2020-12-06 19:11:12.109 MEZ D MarkReadHelper: Marking 0 messages as read.
2020-12-06 19:11:12.213 MEZ W BaseJob: [JOB::90e19856-6fe3-4cc5-ab06-8fb7df0917e7][AttachmentUploadJob] Encountered a failing exception. (Time Since Submission: 1535 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
2020-12-06 19:11:12.213 MEZ W BaseJob: org.thoughtcrime.securesms.jobs.AttachmentUploadJob$InvalidAttachmentException: Cannot find the specified attachment.
2020-12-06 19:11:12.213 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:110)
2020-12-06 19:11:12.213 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
2020-12-06 19:11:12.213 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
2020-12-06 19:11:12.213 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
2020-12-06 19:11:12.219 MEZ I AttachmentDatabase: [deleteAttachmentOnDisk] No other strong uses of this attachment. Safe to delete. /data/user/0/org.thoughtcrime.securesms/app_parts/part1767027542577214213.mms AttachmentId::(9196, 1607278270445)
2020-12-06 19:11:12.220 MEZ I AttachmentDatabase: [deleteAttachmentOnDisk] Deleted attachment file. /data/user/0/org.thoughtcrime.securesms/app_parts/part1767027542577214213.mms AttachmentId::(9196, 1607278270445)
2020-12-06 19:11:12.221 MEZ W JobRunner: [JOB::90e19856-6fe3-4cc5-ab06-8fb7df0917e7][AttachmentUploadJob][3] Job failed. (Time Since Submission: 1542 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
2020-12-06 19:11:12.741 MEZ I ConversationActivity: Deleted 1 abandoned attachments.

and 

> 2020-12-06 19:11:17.523 MEZ D AttachmentUploadJob: Using attachments V3
2020-12-06 19:11:17.528 MEZ I UnidentifiedAccessUtil: Unidentified: 2, Other: 0. Types: {UUID_AND_E164=2}
2020-12-06 19:11:17.624 MEZ I AttachmentDatabase: [deleteAttachmentOnDisk] No other strong uses of this attachment. Safe to delete. /data/user/0/org.thoughtcrime.securesms/app_parts/part6137539107251406947.mms AttachmentId::(9196, 1607278274166)
2020-12-06 19:11:17.634 MEZ I AttachmentDatabase: [deleteAttachmentOnDisk] Deleted attachment file. /data/user/0/org.thoughtcrime.securesms/app_parts/part6137539107251406947.mms AttachmentId::(9196, 1607278274166)
2020-12-06 19:11:17.636 MEZ W BaseJob: [JOB::e61e8ea3-ec6a-4685-9cd8-714fc13e2441][AttachmentUploadJob] Encountered a failing exception. (Time Since Submission: 3379 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
2020-12-06 19:11:17.636 MEZ W BaseJob: org.thoughtcrime.securesms.jobs.AttachmentUploadJob$InvalidAttachmentException: Cannot find the specified attachment.
2020-12-06 19:11:17.636 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:110)
2020-12-06 19:11:17.636 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
2020-12-06 19:11:17.636 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
2020-12-06 19:11:17.636 MEZ W BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
2020-12-06 19:11:17.650 MEZ W JobRunner: [JOB::e61e8ea3-ec6a-4685-9cd8-714fc13e2441][AttachmentUploadJob][3] Job failed. (Time Since Submission: 3390 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
2020-12-06 19:11:18.138 MEZ I ConversationActivity: Deleted 1 abandoned attachments.

Then thing got weirder. As a test she sent all images again quickly in a row and only one made it through.
Now there are 6 deleted abandoned attachments in the new debug log: https://debuglogs.org/438f78a3d00e5cbba5f6316527d278b1f64fa56bf3342e77adf2ac8290828dbe

![grafik](https://user-images.githubusercontent.com/7361310/101289315-fadc6980-37fb-11eb-853d-a996789c9a11.png)


Also some empty messages disappeared:

![grafik](https://user-images.githubusercontent.com/7361310/101289355-2fe8bc00-37fc-11eb-83fe-4673d19ad3a3.png)


Device: Nokia 6
Android version: 9
Signal version: 4.73.4

I know the signal Version is old, but I hope this can still help.
