### ISSUE TITLE
App crashes when sending feedback

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#10212]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app crashes when trying to send feedback from within the app when no mail app is installed.

This had been fixed [once](https://github.com/signalapp/Signal-Android/commit/79fc33630b0f56c2a909a4ed6f0e2c50cdb28b97), but the fix was [lost/removed](https://github.com/signalapp/Signal-Android/commit/acbfff89d35247c71359fe536f4cb7306f390242#diff-dd701a837ac54da3fa240868b170fbae88f7ad07299cddcc8041b813541bba0e). The string `HelpFragment__no_email_app_found` is still present in xml, but unused in code.

### Steps to reproduce
- Try to send feedback

**Actual result:** Crash
**Expected result:** Explain that a mail app is required

### Device info

**Device:** Fairphone 3
**Android version:** 10
**Signal version:** 4.46

### Stack trace

````
2020-11-19 18:37:03.283 18100-18100/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 18100
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SENDTO dat=mailto: (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
        at android.app.Activity.startActivityForResult(Activity.java:5227)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:5185)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at android.app.Activity.startActivity(Activity.java:5556)
        at android.app.Activity.startActivity(Activity.java:5524)
        at org.thoughtcrime.securesms.util.CommunicationActions.openEmail(CommunicationActions.java:158)
        at org.thoughtcrime.securesms.help.HelpFragment.submitFormWithDebugLog(HelpFragment.java:147)
        at org.thoughtcrime.securesms.help.HelpFragment.lambda$submitForm$8(HelpFragment.java:132)
        at org.thoughtcrime.securesms.help.HelpFragment.lambda$submitForm$8$HelpFragment(Unknown Source:0)
        at org.thoughtcrime.securesms.help.-$$Lambda$HelpFragment$oOCQtnHJjJAD7S1VdZIsemxrgq8.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
````

**Comment by ali-khannakhjavani** [comment]
I could reproduce, and capture a bug report on emulator by disabling the Gmail app. This happens because no mailing app can be found to complete the sending request. The solution is to confirm with PackageManger if there is an Activity/App to resolve the SENDTO action before starting the Activity. I Will work on a fix.
