### ISSUE TITLE
Video did not send, exception on thumbnail creation

### ISSUE THREAD

**Issue by Wasseranomalie** [signalapp/Signal-Android#10225]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
One video-thumbnail never appeared in the chat history and the video also was not sent (although both checks visible. At least it never arrived visibily at any other group-member). Unfortunately I forgot to post this issue for one week, therefore I sadly can't provide additional information beside the debug log of the sender phone.

### Steps to reproduce
---

**Actual result:** No video thumbnail and video never sent
**Expected result:** Video thumbnail is shown and video successfully sent

### Screenshots

![Missing_Thumbnail](https://user-images.githubusercontent.com/6809794/100393527-39269b80-303a-11eb-8f5e-157053b24084.png)
The video thumbnail should be visible inside the message block with the two checkmarks.

### Device info

**Device:** Xiaomi Mi A1
**Android version:** 9
**Signal version:** 4.77.3

### Link to debug log

https://debuglogs.org/0cfb5a04a8dcb8a6b012154d8a7708e2afcc552b3fc12ff37bfc272c62453ef7

(Most likely) relevant part:
```
[4.77.3] 2020-11-20 08:56:26.796 MEZ I VideoThumbnailsExtracto: video: 1920x1080 0
[4.77.3] 2020-11-20 08:56:26.801 MEZ I VideoThumbnailsExtracto: output: 213x120
[4.77.3] 2020-11-20 08:56:26.892 MEZ I VideoThumbnailsExtracto: doExtract started
[4.77.3] 2020-11-20 08:56:26.910 MEZ I VideoThumbnailsExtracto: seek to 21395833, actual 25066666
[4.77.3] 2020-11-20 08:56:26.927 MEZ I VideoThumbnailsExtracto: seek to 42791666, actual 41733333
[4.77.3] 2020-11-20 08:56:26.946 MEZ I VideoThumbnailsExtracto: seek to 64187499, actual 66733333
[4.77.3] 2020-11-20 08:56:26.965 MEZ I VideoThumbnailsExtracto: seek to 85583333, actual 83400000
[4.77.3] 2020-11-20 08:56:26.993 MEZ I VideoThumbnailsExtracto: seek to 106979166, actual 108400000
[4.77.3] 2020-11-20 08:56:27.025 MEZ I VideoThumbnailsExtracto: seek to 128374999, actual 128800000
[4.77.3] 2020-11-20 08:56:27.037 MEZ D BaseActivity: [ConversationActivity] onStop()
[4.77.3] 2020-11-20 08:56:27.038 MEZ D LoggingFragment: [ConversationFragment] onStop()
[4.77.3] 2020-11-20 08:56:27.039 MEZ D LoggingFragment: [MentionsPickerFragment] onStop()
[4.77.3] 2020-11-20 08:56:27.040 MEZ D BaseActivity: [ShareActivity] onStop()
[4.77.3] 2020-11-20 08:56:27.040 MEZ D LoggingFragment: [ContactSelectionListFra] onStop()
[4.77.3] 2020-11-20 08:56:27.041 MEZ D BaseActivity: [ShareActivity] onDestroy()
[4.77.3] 2020-11-20 08:56:27.043 MEZ I VideoThumbnailsExtracto: seek to 149770832, actual 146033333
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: null
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: org.thoughtcrime.securesms.video.videoconverter.TranscodingException: Surface frame wait timed out
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at org.thoughtcrime.securesms.video.videoconverter.OutputSurface.awaitNewImage(OutputSurface.java:251)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsExtractor.doExtract(VideoThumbnailsExtractor.java:168)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsExtractor.extractThumbnails(VideoThumbnailsExtractor.java:98)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsView$ThumbnailsTask.doInBackground(VideoThumbnailsView.java:185)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at org.thoughtcrime.securesms.video.videoconverter.VideoThumbnailsView$ThumbnailsTask.doInBackground(VideoThumbnailsView.java:165)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[4.77.3] 2020-11-20 08:56:27.833 MEZ W VideoThumbnailsExtracto: 	at java.lang.Thread.run(Thread.java:764)
[4.77.3] 2020-11-20 08:56:27.837 MEZ W VideoThumbnailsView: Thumbnail extraction failed
```

**Comment by Wasseranomalie** [comment]
It happened again, but this time there was no ```TranscodingException```:
https://debuglogs.org/38b16c9d7b914a0323bccb1df159368dc0ad9f51e186cefb044efdd4f9400859

Starts at [4.78.5] 2020-11-27 08:39:11.774

At a receiver this message seems to be just an empty message:
2020-11-27T07:40:25.438Z handleDataMessage: Dropping empty message
https://debuglogs.org/f488c0ee1e0fdb90d73c86ab3042714bb6e8e746ce902cb597db8e3c6230aa4f (Signal Desktop)
