### ISSUE TITLE
MMS fails to send/receive Verizon oneplus 7 pro

### ISSUE THREAD

**Issue by Whitak3r** [signalapp/Signal-Android#10244]
All non signal users can't receive my mms. Also can't receive from them.

https://debuglogs.org/09af52ab6a70c3331514b422f376156f5b5afd634b29d25389198aab957a2975

Most recent debug log after a couple messages failed to send and receive. 

I remember this happening about a year ago, and it was fixed. Something with Verizon I guess.

**Comment by greyson-signal** [comment]
Failure for reference:

```java
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: null
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: org.thoughtcrime.securesms.transport.UndeliverableMessageException: java.util.concurrent.TimeoutException: timeout when waiting for MMS
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLollipopMmsConnection.send(OutgoingLollipopMmsConnection.java:108)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:35)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:139)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:35)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: Caused by: java.util.concurrent.TimeoutException: timeout when waiting for MMS
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLollipopMmsConnection.send(OutgoingLollipopMmsConnection.java:97)
[4.79.0] 2020-12-02 12:52:27.833 MST W CompatMmsConnection: 	... 6 more
[4.79.0] 2020-12-02 12:52:27.841 MST I CompatMmsConnection: Falling back to legacy connection...
[4.79.0] 2020-12-02 12:52:27.842 MST I CompatMmsConnection: Sending via legacy connection
[4.79.0] 2020-12-02 12:52:27.853 MST I TelephonyUtil: Choosing MCC+MNC info from TelephonyManager.getSimOperator()
[4.79.0] 2020-12-02 12:52:27.855 MST D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
[4.79.0] 2020-12-02 12:52:27.860 MST D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
[4.79.0] 2020-12-02 12:52:27.863 MST I OutgoingLegacyMmsConnection: Sending MMS with radio change and proxy...
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: null
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:90)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:90)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:46)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:139)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:35)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: Caused by: java.lang.reflect.InvocationTargetException
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at java.lang.reflect.Method.invoke(Native Method)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:84)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	... 7 more
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: Caused by: java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at android.net.ConnectivityManager.unsupportedStartingFrom(ConnectivityManager.java:3834)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at android.net.ConnectivityManager.checkLegacyRoutingApiAccess(ConnectivityManager.java:3851)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	at android.net.ConnectivityManager.startUsingNetworkFeature(ConnectivityManager.java:1322)
[4.79.0] 2020-12-02 12:52:27.868 MST W OutgoingLegacyMmsConnection: 	... 9 more
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: null
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: org.thoughtcrime.securesms.transport.UndeliverableMessageException: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:113)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:46)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:139)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:35)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: Caused by: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:90)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:90)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	... 6 more
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: Caused by: java.lang.reflect.InvocationTargetException
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at java.lang.reflect.Method.invoke(Native Method)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:84)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	... 7 more
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: Caused by: java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at android.net.ConnectivityManager.unsupportedStartingFrom(ConnectivityManager.java:3834)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at android.net.ConnectivityManager.checkLegacyRoutingApiAccess(ConnectivityManager.java:3851)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	at android.net.ConnectivityManager.startUsingNetworkFeature(ConnectivityManager.java:1322)
[4.79.0] 2020-12-02 12:52:27.872 MST W CompatMmsConnection: 	... 9 more
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: null
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: org.thoughtcrime.securesms.transport.UndeliverableMessageException: Both lollipop and legacy connections failed...
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:63)
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:139)
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:35)
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
[4.79.0] 2020-12-02 12:52:27.878 MST W MmsSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
```
