### ISSUE TITLE
Preventing request because client is deprecated

### ISSUE THREAD

**Issue by swadexi** [signalapp/Signal-Android#10254]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I tried to build signal from master without anything, Just Compile and run on my android Device. But When i try to registration the Service not connected, in Logcat said : " 

`DeprecatedClientPrevent: Preventing request because client is deprecated.
PushChallengeRequest: Error getting push challenge
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1431)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1393)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1378)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1320)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1296)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestPushChallenge(PushServiceSocket.java:361)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestPushChallenge(SignalServiceAccountManager.java:198)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest$Request.requestAndReceiveChallengeBlocking(PushChallengeRequest.java:94)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest$Request.access$100(PushChallengeRequest.java:66)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest.getPushChallengeBlocking(PushChallengeRequest.java:50)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:50)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:39)
2020-12-06 05:18:25.349 6972-7494/org.thoughtcrime.securesms W/DeprecatedClientPrevent: Preventing request because client is deprecated.
2020-12-06 05:18:25.350 6972-7494/org.thoughtcrime.securesms W/RegistrationCodeRequest: Error during account registration
    org.whispersystems.signalservice.api.push.exceptions.DeprecatedVersionException
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1431)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1393)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1378)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1320)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1308)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestSmsVerificationCode(PushServiceSocket.java:259)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestSmsVerificationCode(SignalServiceAccountManager.java:211)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:55)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:39)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

`

**Actual result:** Registration can not connect to service
**Expected result:** Registration connect to service

### Device info

**Device:** SAMSUNG M21
**Android version:** 10.0.0
**Signal version:** 5.0.0

**Comment by swadexi** [comment]
The fastest solution that i used is force return false in this function in MiscellaneousValues.java

public boolean isClientDeprecated() {
    //return getBoolean(CLIENT_DEPRECATED, false);
    return false;
  }
