### ISSUE TITLE
Verifier rejected class org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserver

### ISSUE THREAD

**Issue by swadexi** [signalapp/Signal-Android#10262]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just compile Signal and when i create new message, the messenger Closed and in the logcat shows : 

`java.lang.VerifyError: Verifier rejected class org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserver: void org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserver.<init>(org.thoughtcrime.securesms.conversation.ConversationFragment, androidx.recyclerview.widget.RecyclerView, org.thoughtcrime.securesms.util.SnapToTopDataObserver$ScrollRequestValidator) failed to verify: void org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserver.<init>(org.thoughtcrime.securesms.conversation.ConversationFragment, androidx.recyclerview.widget.RecyclerView, org.thoughtcrime.securesms.util.SnapToTopDataObserver$ScrollRequestValidator): [0x4] register v0 has type Uninitialized This Reference: org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserverAllocation PC: 0 but expected Precise Reference: org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserver (declaration of 'org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationSnapToTopDataObserver' appears in /data/app/org.thoughtcrime.securesms-hAJkqjDk46xukrbQOBoolQ==/base.apk:classes2.dex)
        at org.thoughtcrime.securesms.conversation.ConversationFragment.onCreateView(ConversationFragment.java:229)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at org.thoughtcrime.securesms.BaseActivity.onStart(BaseActivity.java:47)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
        at android.app.Activity.performStart(Activity.java:6992)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Actual result:** The messenger Close
**Expected result:** The Messenger not close

### Device info

**Device:** All
**Android version:** 10.0.0
**Signal version:** 5.0.0

**Comment by greyson-signal** [comment]
I'm not able to reproduce this. Did you run a Can you try running a `./gradlew clean` before building?

**Comment by swadexi** [comment]
> 
> 
> I'm not able to reproduce this. Did you run a Can you try running a `./gradlew clean` before building?
This happen when i Compile The Signal
- Remove distributionSha256Sum=c9910513d0eed63cd8f5c7fec4cb4a05731144770104a0871234a4edc3ba3cef
- Change MiscellaneousValues.java
```
public boolean isClientDeprecated() {
//    return getBoolean(CLIENT_DEPRECATED, false);
    return false;
  }
```


I tried to clean gradle-> same error
Clean + Invalidate Cache & Restart -> Same Error
Dowload new signal master and compile -> same error

**Comment by jonahbeckford** [comment]
I've seen VerifyError when I accidentally executed Gradle with JDK 11 just once. The command line `gradlew` and Android Studio have to be set to use the same JDK. I didn't realize that at first, so I had accidentally started a persistent JDK 11 Gradle daemon. Even though subsequent invocations I used JDK 8, my `clean` was not stopping the VerifyError.

If you haven't already done the following, try from the command line:

```bash
gradlew -Dorg.gradle.java.home=SOME_JDK8_HOME_DIR --stop
gradlew -Dorg.gradle.java.home=SOME_JDK8_HOME_DIR clean
gradlew -Dorg.gradle.java.home=SOME_JDK8_HOME_DIR qa
```
The `--stop` was to shut down all existing Gradle daemons, and then `clean` to get rid of the JDK 11 compiled classes. `qa` should be sufficient to catch the VerifyError without installing on a device.

After that, make sure you build from Android Studio with the same JDK HOME (and the same JDK 8 version).

Hope that works for you. YMMV.

**Comment by greyson-signal** [comment]
@jonahbeckford That sounds like a likely cause. Regardless, my recommendation for almost all build-related issues is to look at our steps for [Reproducible Builds](https://github.com/signalapp/Signal-Android/tree/master/reproducible-builds). You can use the exact same docker image we use to build the app for release.
