### ISSUE TITLE
Crash when trying to choose a backup from storage

### ISSUE THREAD

**Issue by BlizzardWizzard** [signalapp/Signal-Android#10312]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes when trying to select a location to backup to or when trying to select a backup in the install screen.
This could be because of [android 11's storage framework changes](https://developer.android.com/about/versions/11/privacy/storage#file-directory-restrictions).

### Steps to reproduce
- open freshly installed app
- tap "Restore backup"
- tap "choose backup"

**Actual result:** App exits
**Expected result:** File manager opens to select file

### Device info
**Device:** Samsung Galaxy S20+ SM-G985F/DS
**Android version:** 11
**Signal version:** 5.0.5

### Link to debug log

12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=application/octet-stream (has extras) }
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2080)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.app.Activity.startActivityForResult(Activity.java:5374)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:796)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.ChooseBackupFragment.onChooseBackupSelected(ChooseBackupFragment.java:78)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.ChooseBackupFragment.lambda$odnMbt6sUJFF_Fld0tKgDevRqTU(Unknown Source:0)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.-$$Lambda$ChooseBackupFragment$odnMbt6sUJFF_Fld0tKgDevRqTU.onClick(Unknown Source:2)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.view.View.performClick(View.java:8178)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.widget.TextView.performClick(TextView.java:16104)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.view.View.performClickInternal(View.java:8147)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.view.View.access$3700(View.java:888)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.view.View$PerformClick.run(View.java:30233)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.os.Handler.handleCallback(Handler.java:938)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.os.Looper.loop(Looper.java:246)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at android.app.ActivityThread.main(ActivityThread.java:8414)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at java.lang.reflect.Method.invoke(Native Method)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
12-17 16:11:58.544 32500 32500 E SignalUncaughtExceptionHandler:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by alex-signal** [comment]
Hi! Thanks for reporting this bug. Hoping this will be resolved in 5.1. As far as I can tell Samsung's "MyFiles" app doesn't support the OPEN_DOCUMENT action at all. (I could be wrong but that's what my investigation indicated)

I have a couple possible workarounds while you're sitting tight for 5.1:

1) Download the "Files by Google" app from the play store. This is the Files app that comes preinstalled on Pixel devices, and it has support for the previously mentioned intent.

2) Alternatively, you may be able to enable "Manage all files" in the Permissions settings for the Signal app (in system settings) and the app may pick up on that and utilize the legacy method (pre scoped storage). You can disable this again after you've selected a backup.

**Comment by BlizzardWizzard** [comment]
Thank you for your Ideas; sadly they didn't work.
I wasn't using Samsung's MyFiles in the first place, but I've now also tried that and that also does not work, just like "Files by Google".
I was also not able to enable "Manage all files" in permissions, because the samsung settings don't let me do that.
