### ISSUE TITLE
Can't send picture in non secure MMS group chat

### ISSUE THREAD

**Issue by jaredsburrows** [signalapp/Signal-Android#10313]
**Repro information:**
 - Pixel 4
 - Android Version 11
 - Setup group with 1 other Signal user(secure) and 1 non-Signal user(non-secure) - insecure MMS group chat
 - Taking pictures while in the app and sending it works
 - Sending pictures not taken in the app such a screenshots of the home screen doesnt work

**Top level exceptions and errors:**
  - `org.thoughtcrime.securesms.transport.UndeliverableMessageException: Null response.`
  - `org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException`
  - `Caused by: java.lang.reflect.InvocationTargetException`
  - `Caused by: java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above`
  - org.thoughtcrime.securesms.transport.UndeliverableMessageException: `org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException`
  - `Caused by: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException`
  - `Caused by: java.lang.reflect.InvocationTargetException`
  - `Caused by: java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above`
  - `org.thoughtcrime.securesms.transport.UndeliverableMessageException: Both lollipop and legacy connections failed...`

**ADB logcat:**
```
12-17 13:26:50.055 26430 26430 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.058 26430 26430 I chatty  : uid=10238(org.thoughtcrime.securesms) identical 2 lines
12-17 13:26:50.059 26430 26430 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.061 26430 26430 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.sms.MessageSender$MessageSentEvent
12-17 13:26:50.061 26430 26430 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
12-17 13:26:50.070 26430 26471 D OpenGLRenderer: endAllActiveAnimators on 0xb400007200523090 (RippleDrawable) with handle 0xb4000071200ead10
12-17 13:26:50.087 26430 26464 I Job     : [JOB::eb06f735-2215-48a2-be78-f6dc5be63095][AttachmentCompressionJob] onSubmit() (Time Since Submission: 27 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
12-17 13:26:50.087 26430 26464 I Job     : [JOB::e758841c-18e4-4bd1-b646-134ec6e454c7][MmsSendJob] onSubmit() (Time Since Submission: 27 ms, Lifespan: Immortal, Run Attempt: 1/15)
12-17 13:26:50.088 26430 26464 V Cursor  : Filling cursor window with start position:0 required position:0

12-17 13:26:50.146 26430 26464 I chatty  : uid=10238(org.thoughtcrime.securesms) signal-JobManag identical 6 lines
12-17 13:26:50.146 26430 26464 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.152 26430 27505 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.153 26430 27505 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.153 26430 26468 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.153 26430 27505 D ConversationDataSource: size() for thread 272: 1 ms
12-17 13:26:50.154 26430 26468 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.155 26430 26468 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.158 26430 26490 I JobRunner: [JOB::eb06f735-2215-48a2-be78-f6dc5be63095][AttachmentCompressionJob][1] Running job. (Time Since Submission: 96 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
12-17 13:26:50.161 26430 26468 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.161 26430 26490 D AttachmentCompressionJo: Running for: AttachmentId::(2428, 1608228941791)
12-17 13:26:50.161 26430 26509 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.212 26430 26490 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.213 26430 26490 I AttachmentCompressionJo: Skipping at the direction of the TransformProperties.
12-17 13:26:50.214 26430 26490 I JobRunner: [JOB::eb06f735-2215-48a2-be78-f6dc5be63095][AttachmentCompressionJob][1] Job finished with result SUCCESS in 57 ms. (Time Since Submission: 153 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
12-17 13:26:50.223 26430 26490 I JobRunner: [JOB::e758841c-18e4-4bd1-b646-134ec6e454c7][MmsSendJob][1] Running job. (Time Since Submission: 162 ms, Lifespan: Immortal, Run Attempt: 1/15)
12-17 13:26:50.224 26430 26509 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.224 26430 26509 D ConversationDataSource: [load(0, 100), thread 272] messages: 68  mentions: 1  conversion: 0  total: 69
12-17 13:26:50.226 26430 26490 I SendJob : Starting message send attempt
12-17 13:26:50.226 26430 26490 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.228 26430 26490 I chatty  : uid=10238(org.thoughtcrime.securesms) signal-JobRunne identical 3 lines
12-17 13:26:50.228 26430 26490 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.228 26430 26490 I MmsSendJob: Sending message: 11142
12-17 13:26:50.237 26430 26430 I ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/xxx/xxx
12-17 13:26:50.240 26430 26490 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.244 26430 26490 V Cursor  : Filling cursor window with start position:0 required position:0
12-17 13:26:50.266 26430 26490 I CompatMmsConnection: Sending via Lollipop API
12-17 13:26:50.268 26430 26490 I MmsBodyProvider: openFile(content://org.thoughtcrime.securesms.mms/mms/xxx, w)
12-17 13:26:50.268 26430 26490 I MmsBodyProvider: Fetching message body for a single row...
12-17 13:26:50.268 26430 26490 I MmsBodyProvider: returning file /data/user/0/org.thoughtcrime.securesms/cache/xxx.mmsbody
12-17 13:26:50.271  1519  3388 D MmsServiceBroker: sendMessage() by org.thoughtcrime.securesms
12-17 13:26:50.274  2394  2937 D MmsService: sendMessage messageId: 0
12-17 13:26:50.281  2394  2937 D MmsService: Current running=0, current subId=-1, pending=0
12-17 13:26:50.281  2394  2937 D MmsService: Add request to running queue for subId 2
12-17 13:26:50.281  2394 19902 I MmsService: [SendRequest@3f15a84 messageId: 0] Executing...
12-17 13:26:50.281  2394 19902 I MmsService: mms config for sub 2: Bundle[{httpSocketTimeout=60000, aliasMinChars=2, smsToMmsTextThreshold=7, enableSMSDeliveryReports=true, maxMessageTextSize=-1, supportMmsContentDisposition=true, enabledTransID=true, aliasEnabled=true, supportHttpCharsetHeader=false, allowAttachAudio=false, smsToMmsTextLengthThreshold=-1, recipientLimit=20, uaProfTagName=Profile, aliasMaxChars=48, maxImageHeight=1944, enableMMSDeliveryReports=false, userAgent=, mmsCloseConnection=true, config_cellBroadcastAppLinks=true, maxSubjectLength=80, httpParams=x-up-calling-line-id: 1##LINE1NOCOUNTRYCODE##|X-VzW-MDN: 1##LINE1NOCOUNTRYCODE##, enableGroupMms=true, emailGatewayNumber=6245, maxMessageSize=1258291, naiSuffix=, enableMMSReadReports=false, maxImageWidth=2592, uaProfUrl=, enabledMMS=true, enabledNotifyWapMMSC=true, sendMultipartSmsAsSeparateMessages=false, enableMultipartSMS=true}]
12-17 13:26:50.285 26430 26446 I MmsBodyProvider: openFile(content://org.thoughtcrime.securesms.mms/mms/xxx, r)
12-17 13:26:50.285 26430 26446 I MmsBodyProvider: Fetching message body for a single row...
12-17 13:26:50.285 26430 26446 I MmsBodyProvider: returning file /data/user/0/org.thoughtcrime.securesms/cache/xxx.mmsbody
12-17 13:26:50.287  2394 19902 E MmsService: PDU read is too large
12-17 13:26:50.287  2394 19902 E MmsService: [SendRequest@3f15a84 messageId: 0] Failed to prepare for request
12-17 13:26:50.293  2394 19902 I MmsService: [SendRequest@3f15a84 messageId: 0] processResult: 5, httpStatusCode: success (0)
12-17 13:26:50.294  2394 19902 D MmsService: Schedule requests pending on SIM
12-17 13:26:50.299 26430 26430 I LollipopMmsConnection: onReceive()
12-17 13:26:50.299 26430 26430 I OutgoingLollipopMmsConnection: HTTP status: -1
12-17 13:26:50.300 26430 26490 I OutgoingLollipopMmsConnection: MMS broadcast received and processed.
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: null
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: org.thoughtcrime.securesms.transport.UndeliverableMessageException: Null response.
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLollipopMmsConnection.send(OutgoingLollipopMmsConnection.java:104)
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:36)
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:140)
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:34)
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
12-17 13:26:50.301 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
12-17 13:26:50.301 26430 26490 I CompatMmsConnection: Falling back to legacy connection...
12-17 13:26:50.301 26430 26490 I CompatMmsConnection: Sending via legacy connection
12-17 13:26:50.301 26430 26490 I TelephonyUtil: Choosing MCC+MNC info from TelephonyManager.getSimOperator()
12-17 13:26:50.302 26430 26490 D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
12-17 13:26:50.303 26430 26490 D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
12-17 13:26:50.304 26430 26490 I TelephonyUtil: Choosing MCC+MNC info from TelephonyManager.getSimOperator()
12-17 13:26:50.304 26430 26490 I OutgoingLegacyMmsConnection: Sending MMS with radio change and proxy...
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: null
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:90)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:91)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:47)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:140)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:34)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: Caused by: java.lang.reflect.InvocationTargetException
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at java.lang.reflect.Method.invoke(Native Method)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:84)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	... 7 more
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: Caused by: java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at android.net.ConnectivityManager.unsupportedStartingFrom(ConnectivityManager.java:4587)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at android.net.ConnectivityManager.checkLegacyRoutingApiAccess(ConnectivityManager.java:4599)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	at android.net.ConnectivityManager.startUsingNetworkFeature(ConnectivityManager.java:1442)
12-17 13:26:50.304 26430 26490 W OutgoingLegacyMmsConnection: 	... 9 more
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: null
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: org.thoughtcrime.securesms.transport.UndeliverableMessageException: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:114)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:47)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:140)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:34)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: Caused by: org.thoughtcrime.securesms.mms.MmsRadioException: java.lang.reflect.InvocationTargetException
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:90)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.send(OutgoingLegacyMmsConnection.java:91)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	... 6 more
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: Caused by: java.lang.reflect.InvocationTargetException
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at java.lang.reflect.Method.invoke(Native Method)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at org.thoughtcrime.securesms.mms.MmsRadio.connect(MmsRadio.java:84)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	... 7 more
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: Caused by: java.lang.UnsupportedOperationException: This method is not supported in target SDK version 23 and above
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at android.net.ConnectivityManager.unsupportedStartingFrom(ConnectivityManager.java:4587)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at android.net.ConnectivityManager.checkLegacyRoutingApiAccess(ConnectivityManager.java:4599)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	at android.net.ConnectivityManager.startUsingNetworkFeature(ConnectivityManager.java:1442)
12-17 13:26:50.304 26430 26490 W CompatMmsConnection: 	... 9 more
12-17 13:26:50.304 26430 26490 W MmsSendJob: null
12-17 13:26:50.304 26430 26490 W MmsSendJob: org.thoughtcrime.securesms.transport.UndeliverableMessageException: Both lollipop and legacy connections failed...
12-17 13:26:50.304 26430 26490 W MmsSendJob: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.send(CompatMmsConnection.java:64)
12-17 13:26:50.304 26430 26490 W MmsSendJob: 	at org.thoughtcrime.securesms.jobs.MmsSendJob.onSend(MmsSendJob.java:140)
12-17 13:26:50.304 26430 26490 W MmsSendJob: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:34)
12-17 13:26:50.304 26430 26490 W MmsSendJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
12-17 13:26:50.304 26430 26490 W MmsSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
12-17 13:26:50.304 26430 26490 W MmsSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by mtschoen-unity** [comment]
I'm seeing the same behavior, though I don't see these exceptions in the log. I just can't send pictures from outside of the app. The gallery show up as black and so does the image, then the app just hangs when I try to send it.
