### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#10536]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Yesterday, after the upgrade to 5.1.6, Signal was really slow to open again. In fact, so slow that I closed it (by swiping it away) and tried again after seeing a black screen for a minute.

Based on time, this warning (any many more that are identical) is likely related:

```
[5.1.6] [main] 2021-01-12 00:42:12.125 GMT+01:00 W LiveRecipient: [Resolve][MAIN] RecipientId::20
[5.1.6] [main] 2021-01-12 00:42:12.125 GMT+01:00 W LiveRecipient: java.lang.Throwable
[5.1.6] [main] 2021-01-12 00:42:12.125 GMT+01:00 W LiveRecipient: 	at org.thoughtcrime.securesms.recipients.LiveRecipient.resolve(LiveRecipient.java:129)
[5.1.6] [main] 2021-01-12 00:42:12.125 GMT+01:00 W LiveRecipient: 	at org.thoughtcrime.securesms.recipients.Recipient.resolve(Recipient.java:844)
[5.1.6] [main] 2021-01-12 00:42:12.125 GMT+01:00 W LiveRecipient: 	at org.thoughtcrime.securesms.recipients.Recipient.isGroup(Recipient.java:667)
[5.1.6] [main] 2021-01-12 00:42:12.125 GMT+01:00 W LiveRecipient: 	at org.thoughtcrime.securesms.contacts.ContactSelectionListItem.setText(ContactSelectionListItem.java:118)
```

Code issuing the warning at [LiveRecipient.java#129](https://github.com/signalapp/Signal-Android/blob/v5.1.6/app/src/main/java/org/thoughtcrime/securesms/recipients/LiveRecipient.java#L129):

```
    if (Util.isMainThread()) {
      Log.w(TAG, "[Resolve][MAIN] " + getId(), new Throwable());
    }
```

Guess that's there because it can block the main thread.

**Actual result:** Delay during start
**Expected result:** No delay

### Device info

**Device:** Motorola One Vision
**Android version:** 10
**Signal version:** 5.1.6

### Link to debug log

[debug log](https://debuglogs.org/e8f10965e9133a688446085f3327eb7e4f2f9a5ce5d356c5a08d5d6c5d3f52f1)

**Comment by pgerber** [comment]
Issue has not occurred in some time.
