### ISSUE TITLE
Crash when registering phone number (right after installing for first time)

### ISSUE THREAD

**Issue by Zylann** [signalapp/Signal-Android#10829]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
I just installed Signal for the first time, but it crashes during onboarding.
It crashes after pressing `Next` (in French "Suivant" on my phone) at the phone number registration phase. I then receive an SMS with a code in it but the app closed at this point. If I relaunch it, it restarts from the beginning of the onboarding. Because of this I am unable to use the app at all.

### Steps to reproduce
- Install app from Google Play
- Launch app
- Press the button to start on the welcome screen
- Press "next" on the phone number registration (I'm french so the button says "Suivant" for me)
- After some loading, the app crashes: "Signal has stopped".
Reproduces every time.

**Actual result:** 
The app stops.

**Expected result:**
The app successfully registering my number and not crashing.

### Screenshots
I don't know how to do it, not sure if it's relevant here

### Device info
**Device:** Wiko Birdy
**Android version:** 4.4.2
**Signal version:** 5.2.3

### Link to debug log
I cannot use Signal's advanced settings to get a log, because Signal can't even get past the onboarding screens, which have no other menus than the two buttons mentionned in the repro steps.
However I found accidentally that if I tap the first screen randomly, it prepares a debug log, so I uploaded it here https://debuglogs.org/889dae9323d8fc7ea0b3777ab2ab22a44070e0838c14a1fb4251b8602a90b613

```
E/AndroidRuntime(16774): FATAL EXCEPTION: main
E/AndroidRuntime(16774): Process: org.thoughtcrime.securesms, PID: 16774
E/AndroidRuntime(16774): android.view.InflateException: Binary XML file line #114: Error inflating class ImageView
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(16774): 	at org.thoughtcrime.securesms.registration.fragments.EnterCodeFragment.onCreateView(EnterCodeFragment.java:61)
E/AndroidRuntime(16774): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
E/AndroidRuntime(16774): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
E/AndroidRuntime(16774): 	at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
E/AndroidRuntime(16774): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
E/AndroidRuntime(16774): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
E/AndroidRuntime(16774): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
E/AndroidRuntime(16774): 	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
E/AndroidRuntime(16774): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(16774): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(16774): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(16774): 	at android.app.ActivityThread.main(ActivityThread.java:5315)
E/AndroidRuntime(16774): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16774): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(16774): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(16774): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(16774): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(16774): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_error_outline_14_ultramarine.xml from drawable resource ID #0x7f080140
E/AndroidRuntime(16774): 	at android.content.res.Resources.loadDrawable(Resources.java:2152)
E/AndroidRuntime(16774): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
E/AndroidRuntime(16774): 	at android.view.View.<init>(View.java:3579)
E/AndroidRuntime(16774): 	at android.widget.ImageView.<init>(ImageView.java:123)
E/AndroidRuntime(16774): 	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:74)
E/AndroidRuntime(16774): 	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
E/AndroidRuntime(16774): 	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:199)
E/AndroidRuntime(16774): 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:119)
E/AndroidRuntime(16774): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
E/AndroidRuntime(16774): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
E/AndroidRuntime(16774): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/AndroidRuntime(16774): 	... 23 more
E/AndroidRuntime(16774): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
E/AndroidRuntime(16774): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/AndroidRuntime(16774): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime(16774): 	at android.content.res.Resources.loadDrawable(Resources.java:2148)
E/AndroidRuntime(16774): 	... 34 more
```

**Comment by fredzv** [comment]
I have the same issue on my LG G2 and Android 4.4.2. Crashes as soon as I get the SMS.

**Comment by Zylann** [comment]
I got a new phone since, the problem is not happening on it, likely due to a more recent OS version. I was never able to make Signal work on the phone on which I reported this issue.
