### ISSUE TITLE
Can't handle video file

### ISSUE THREAD

**Issue by vandenheuvel** [signalapp/Signal-Android#10860]
Signal crashes when trying to send a video.

### Steps to Reproduce

1.  Create a video from a number of png's using ffmpeg, command `ffmpeg -framerate 25 -i /dir/frame_%05d.png -vcodec libx264 -crf 22 video.mp4`. You can find the video file [here](https://user-images.githubusercontent.com/20440137/106349598-62c8a100-62cf-11eb-8638-d56f2be16583.mp4).
2.  Send it to a contact.

When I initially sent that video using Signal Desktop, my contact could view the video (iOS) and had no issues. I could also view it in Signal Desktop. When I try to play the sent video on my phone, the video view opens but nothings plays (but doesn't work via the standard built-in app either). When I save it (from the Signal Android app to my usual storage) and send it to another contact, Signal Android crashes. The same behavior when I try to forward the message I sent earlier.

When that crash happens, Signal Android returns to the list of all chats the first time. The second time I try the OS tells me that the app keeps crashing and any ongoing call at that point stops.

### Device info

**Device:** Xiaomi Mi 9T Pro
**Android version:** 11
**Signal version:** 5.2.3

[Debug Log](https://debuglogs.org/5d9e8a6c1b8a7755ee2bc67202bb7106d55d0138aebfcf0ad1ef116a36ace31c)

**Comment by Masqueey** [comment]
When I try to play the video file it says the video file is corrupted. The problem might be the video, not the app.

**Comment by vandenheuvel** [comment]
I don't expect Signal to play the video (my browser can't either) but I do expect the app not to crash just by sending it. Shouldn't you be able to send and forward any file?

**Comment by vandenheuvel** [comment]
It is still relevant and easily reproducible by saving the provided sample to an Android phone and sending it to a contact.

**Comment by cody-signal** [comment]
I can't reproduce this using the provided video on the latest signal and Android 11. Could you try to reproduce and post an updated debuglog with the latest version of Signal.

**Comment by UserX404** [comment]
Same happend to me on 5.39.6
https://debuglogs.org/dec54a9dea54a5abf58642776cbd9e2fdad94e0c3c884194997ef8787549f54e

**Comment by alex-signal** [comment]
```
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException java.lang.RuntimeException: An error occurred while executing doInBackground()
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.lang.Thread.run(Thread.java:923)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException Caused by: java.lang.IllegalArgumentException: MIME type application/octet-stream cannot be inserted into content://media/external/video/media; expected MIME type under video/*
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.content.ContentResolver.insert(ContentResolver.java:2149)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.content.ContentResolver.insert(ContentResolver.java:2111)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.createOutputUri(SaveAttachmentTask.java:293)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:114)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:89)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:44)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5.30.6] [5613 ] 2022-02-07 23:05:56.733 GMT+01:00 E SignalUncaughtException 	... 3 more
```

It appears that Desktop is misinterpreting the video with the wrong mime type meaning Android then gets confused. This should be brought up as a bug on Desktop at this point.

**Comment by UserX404** [comment]
At this time no desktop client was running. Did you get in touch with the desktop team or should i open a ticket?

**Comment by UserX404** [comment]
It was an old chat from an unlinked user.
That contact had changed it's account to another telephone number but this was the case a few days before 'change number'+feature was enabled. It was the classic way - new account and changed nr. within my android contacts.

The 'floating' chat still exist with a unknown number.
Saving it to disk crashed the app.

**Comment by vandenheuvel** [comment]
bump
