### ISSUE TITLE
Messages not delivered when app is in background

### ISSUE THREAD

**Issue by zskamljic** [signalapp/Signal-Android#10947]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On Huawei P30 messages do not seem to be received unless the screen is unlocked and notifications are not shown. On sender device for the most part only one checkmark appears (sent, but not delivered), other times both appear, but the device still does not receive messages. All messages arrive if phone screen is unlocked or if the app is open.

Note that notifications from other apps (including a sample app that uses firebase notifications I made) work fine.

I have followed the troubleshooting on these links:
https://support.signal.org/hc/en-us/articles/360027913252-Troubleshoot-receiving-messages#android
https://support.signal.org/hc/en-us/articles/360028198711#huawei - only the first one exists, the remaining points don't seem to be present on the device
https://support.signal.org/hc/en-us/articles/360027919052

Manual management is enabled for Signal, and it's allowed to Auto-launch and Run in background

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots
In Settings > Battery > App launch
![image](https://user-images.githubusercontent.com/14160663/107500820-ec615400-6b96-11eb-853c-2752c1ab17da.png)

### Device info
**Device:** Huawei P30
**Android version:** 10.0
**Signal version:** 5.3.12

### Link to debug log

https://debuglogs.org/f4c00c1cdffc8e91f01fe64f5aecc23d63b2f6e7a93daa2f5528f5f4e3856254

**Comment by Parstion** [comment]
Have you tried disable battery optimization?
it is in Settings -> Apps -> Apps -> 3 dots -> Special access -> Battery optimization -> Select All apps and search for Signal -> Select ( Don't allow )
by the way these on EMUI 10, don't know about the others

**Comment by zskamljic** [comment]
Changed this setting as well, but it seems to be the same

**Comment by Nisc3d** [comment]
First: You posted your issue at the right place and it should still stay here.
I'm just informing on another way you could help solve issues around missing notifications.
Right now a Signal Developer asked on the forum to send additional debug information directly to him via a direct Message on the Signal Forum. This includes a Android Bug report, which contain more information, that could help.
If you are comfortable sharing that information you can register at the forum.
Here are the detailed steps what to send and some more information what is included in an Android Bug report (read carefully):
https://community.signalusers.org/t/help-needed-share-an-android-bug-report-to-help-debug-notifications/27739

**Comment by AsamK** [comment]
Looking at the logs, it seems the Signal app receives the firebase notifications without much delay. But fails to connect to the signal servers to get the actual message.
Is there maybe some background data saver active on the device, that limits network access when the screen is locked?

```
[5.3.12] [20036] 2021-02-10 11:37:47.733 CET I FcmReceiveService: onMessageReceived() ID: 0:1612953467240888%e3016397f9fd7ecd, Delay: 494, Original Priority: 1
[5.3.12] [main ] 2021-02-10 11:37:47.740 CET I FcmFetchService: Incrementing active count to 1
[5.3.12] [20032] 2021-02-10 11:37:47.746 CET W BackgroundMessageRetrie: We may be operating in a constrained environment. Doze: false Network: false
[5.3.12] [20032] 2021-02-10 11:37:47.747 CET I BackgroundMessageRetrie: Performing normal message fetch.
[5.3.12] [20032] 2021-02-10 11:37:47.747 CET I BackgroundMessageRetrie: Attempting strategy: RestStrategy (1 ms elapsed)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: Failed to retrieve messages. Resetting the SignalServiceMessageReceiver.
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.ConnectException: Failed to connect to textsecure-service.whispersystems.org/13.248.212.111:443
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1486)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1411)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:422)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:272)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.thoughtcrime.securesms.messages.RestStrategy.enqueuePushDecryptJobs(RestStrategy.java:85)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.thoughtcrime.securesms.messages.RestStrategy.execute(RestStrategy.java:39)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.executeBackgroundRetrieval(BackgroundMessageRetriever.java:87)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.retrieveMessages(BackgroundMessageRetriever.java:67)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmFetchService.retrieveMessages(FcmFetchService.java:85)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmFetchService.fetch(FcmFetchService.java:75)
...
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: Caused by: java.net.ConnectException: Failed to connect to textsecure-service.whispersystems.org/13.248.212.111:443
...
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: Caused by: java.net.ConnectException: failed to connect to textsecure-service.whispersystems.org/13.248.212.111 (port 443) from /100.81.155.134 (port 59464) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
...
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
[5.3.12] [20032] 2021-02-10 11:37:49.843 CET W RestStrategy: 	... 54 more
```

**Comment by zskamljic** [comment]
No data savers there, everything that I could find that was related to either data saving or power saving has been disabled, with no changes. Perhaps noteworthy, other apps seem to be getting notifications correctly.

**Comment by Vrumfondel** [comment]
Hi there!
Got the same issue on my Unihertz Titan with Android 10. No messages are received if Signal is in Background. All the "normal" countermeasures regarding batterysafe and backgrounddata are allready set as they should be - but no success ...

**Comment by theo2354** [comment]
Hello,

Same problem with a Ulefone Armor 5, no battery nor network limiter, notifications only arrive if the app is opened.

**Comment by Vrumfondel** [comment]
Hello again,

the main issue seems to be that correlated settings are somehow spread within Android10 in several locations - which are not even obviously named.
I wonder why Apps line WhatsApp are able to set these correctly on installation, but Signal can't.
Can you check if your phone has a setting like the following (My Phone is German, so please be aware that my translation might not be 100% percise):
Settings -> intelligent help -> app limitations -> Signal -> all switches must be set to OFF .

**Comment by anwfr** [comment]
Same problem here with Unihertz Titan on Android 10.
There is no "intelligent help" or "app limitations" in my settings menu.

**Comment by Vrumfondel** [comment]
OK, maybe this is a translation issue. On the Titan, if you go to the settings, the 4th option from top - beeing a yellow hand - is called "intelligente Hilfe" in the German version. Under this, the 5th item from top is "App-Beschränkungen".
Changing this made Signal finally work as expected for me.

**Comment by mkauzlar** [comment]
Same thing on Ulefone Armor 7 (Android 9). After a while the notifications stop and they resume only if the app is started in the foreground.
This problem is all over the web, reported by many people.

**Comment by Tsjippy** [comment]
I have te same problem on a Infinix phone.
All settings I could find are set correctly.
But messages are only shown if I open the signal app.

**Comment by mkauzlar** [comment]
#8597

**Comment by anwfr** [comment]
@Vrumfondel Excellent, thank you so much!
Found it under: Settings > Smart Assistant > App blocker > Signal > uncheck all restrictions

**Comment by zskamljic** [comment]
Issue seems to have gotten worse with the latest Huawei update, now it appears that the app needs to be open to actually get the message. I'm aware that this is a Huawei issue, but it's probably forcing a lot of people to abandon the app, myself included.

**Comment by jedie** [comment]
There is also a forum threads about this Problem.

**Comment by ZiOLONwe** [comment]
I have the same problem, I try very solution. No work.

**Comment by evilSwanson** [comment]
> I'm aware that this is a Huawei issue
It's not. 50% of my contacts don't receive my messages because of this. I always have to write them via Whatsapp that they should open Signal and most of them don't have Huawei phones...

**Comment by janvlug** [comment]
I have one particular contact with a Huawei pro 30 who is experiencing severe issues with receiving notifications as well.

**Comment by KonstantMan** [comment]
I have the same problem with signal on Android 8, I have heavily degoogled my phone and I use netguard to disable any internet access. So I have noticed that signal notifications work only when I enable Google services, is there any way to install signal from a different source other than Aurora in order to receive notifications without the Google services?

**Comment by suamor** [comment]
I have this problem with multiple apps. Apps like signal, whatsapp, telegram. Some of them are working fine, others do not work at all, some notifications are working, others do not work at all. Sometimes notifications do not come. As if the app is suspended even though no battery optimization is happening. I have a Samsung A41. This problem is also present in older Android versions. Though in Android 11 it is occuring much more often.

1. Voice/Video call: No notification when phone is locked. Sometimes call notification when phone is unlocked. No missed call notification from such apps.
2. Messages: Sometimes notifications when phone is locked. When phone is unlocked notification work when app has been running recently. But they stop coming in all situations when app has not run for a longer time.

I think that some internal changes on Android 11 notification system has especially worsened situations with call notifications. As there is no solution in sight I will stop using Android 11 (buying new phone with Android 10, downgrading or something else) until this is solved.

**Comment by UserX404** [comment]
@suamor
Without a log nobody can help you.
Please try 'DontKillMyApp' from playstore for analysis. It's likely your device/os is killing the needed backgroundtasks.

**Comment by kpeace** [comment]
This helped me:

Apps & Notifications -> All Apps -> Signal -> Notifications -> Lock Status - > Make sure it's on "Alerting"

**Comment by zuluqq** [comment]
Got it to at least vibrate/ring once by long-pressing the "missed called" top bar notification, ensuring that's set to "default" or whatever and not "silent", then clicking "Manage" below and playing with those settings (specifically the individual App ones and picking Signal and just maxxing it all out, whatever looked like it would help). Running Android 12 on a Pixel 5. I also know of other phones that have this same issue; haven't yet applied this fix to them though, having just discovered it.

Wading through the permissions and privacy settings was a nightmare though. Took me a whole afternoon, between hacking on the phone and reading fora. First you have the phone settings, then you have the in-app settings, then these weird settings that are only somewhat accessible through a long-press on a missed call notification, and even then like three menus deep.

I'm sure there will be a day when Signal will ring just like a regular call, displaying as such on the lockscreen and inside the unlocked device, no matter if the app has been killed or is running in the background or what (currently notifications work well when you're actively in the app, running it in the foreground). I really look forward to that day.
