### ISSUE TITLE
Review storage immediately crashes after opening

### ISSUE THREAD

**Issue by dkm** [signalapp/Signal-Android#10983]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When opening the storage manager, it first display the correct window (the and immediately crash.

### Steps to reproduce
- setting
- data and storage
- manage storage
- review storage

The tabbed view (with media, ... all) is correctly opened but is empty. Then after 1 or 2 s, the system pops up 'the app has crashed...' 

The logcat gives this : 
```
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler:
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:761)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: Caused by: org.thoughtcrime.securesms.recipients.RecipientId$InvalidLongRecipientIdError
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:36)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.database.MediaDatabase$MediaRecord.from(MediaDatabase.java:220)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.database.loaders.GroupedThreadMediaLoader.loadInBackground(GroupedThreadMediaLoader.java:76)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.database.loaders.GroupedThreadMediaLoader.loadInBackground(GroupedThreadMediaLoader.java:23)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-16 20:32:56.985 12766 12992 E SignalUncaughtExceptionHandler: 	... 3 more
02-16 20:32:57.002 12766 12992 I JobManager: Successfully flushed.
02-16 20:32:57.002 12766 12992 E AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #2
02-16 20:32:57.002 12766 12992 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12766
02-16 20:32:57.002 12766 12992 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: Caused by: org.thoughtcrime.securesms.recipients.RecipientId$InvalidLongRecipientIdError
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:36)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MediaDatabase$MediaRecord.from(MediaDatabase.java:220)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.loaders.GroupedThreadMediaLoader.loadInBackground(GroupedThreadMediaLoader.java:76)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.loaders.GroupedThreadMediaLoader.loadInBackground(GroupedThreadMediaLoader.java:23)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-16 20:32:57.002 12766 12992 E AndroidRuntime: 	... 3 more
02-16 20:32:57.005  2656  7861 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.mediaoverview.MediaOverviewActivity
02-16 20:32:57.012  2656  7861 D ActivityTrigger: ActivityTrigger activityPauseTrigger
02-16 20:32:57.014  2656  4598 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{48be464 org.thoughtcrime.securesms} is now in focus and seems to be in full-screen mode
02-16 20:32:57.014  2656  4598 E ActivityTrigger: activityResumeTrigger: not whiteListedorg.thoughtcrime.securesms/org.thoughtcrime.securesms.ApplicationPreferencesActivity/78500
02-16 20:32:57.044 12766 12766 D BaseActivity: [ApplicationPreferencesA] onStart()
02-16 20:32:57.046 12766 12804 V Cursor  : Filling cursor window with start position:0 required position:0
```

### Device info

**Device:** Fairphone 2, no Google App installed
**Android version:** 7.1.2
**Signal version:** 5.3.12 (direct apk install)

### Link to debug log
https://debuglogs.org/b5307c274bee4421f643ff00e2d06842280c26112dfd059408e8969565e8ff1c

**Comment by Dhanurjan** [comment]
Try beta 5.4.4

**Comment by dkm** [comment]
> Try beta 5.4.4

Is it possible without the play store? Can't find any link for the beta apk...

**Comment by Dhanurjan** [comment]
Click this link and follow - [Get the latest Android releases even faster with Firebase App Delivery](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-firebase-app-delivery/17538)

**Comment by dkm** [comment]
Thanks for the info. Unfortunately, this method needs a google account and the firebase application. I'll wait:D

**Comment by Dhanurjan** [comment]
Then try this link and direct download the apk - [Signal](https://www.apkmirror.com/uploads/?q=signal-foundation)

**Comment by dkm** [comment]
Ok thanks for the help ! I've installed the beta 5.4.5 and have the exact same behavior...

**Comment by infinitewaveparticle** [comment]
I also have had this crash for quite a while. I use the Review Storage function a lot so this is very upsetting. I reported this bug to support@signal.org at least a month ago, possibly two. I also use the apk version from the website so perhaps that's a clue...? Whatever the case this needs fixed. It seems as though the newer the versions the more problems and crashes are introduced which take forever to be fixed... And convenient options are replaced with useless functions. It's getting to be a bit infuriating honestly.

**Comment by dkm** [comment]
I gave up and reinstalled the app. The issue can be closed.

**Comment by infinitewaveparticle** [comment]
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
It seems to work fine now

Sent from ProtonMail mobile

-------- Original Message --------
