### ISSUE TITLE
Crash on multi-forwarding a voice note / audio message

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#11000]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crash on multi-forward audio message.
Forwarding it to a single contact works without problems.
It seems there a problems with rendering the spectrum image (?)

### Steps to reproduce
- sending a audio file from desktop to a participant and append some text to it.
- on Android select the message and forward it.
- select some contacts and klick on send.

**Actual result:** 
Nothing happens, app crashes at the second try.
**Expected result:**
Audio message should be sent to the selected contacts.

### Screenshots

N/A

### Device info

**Device:** Sony XZ2 compact (H8324)
**Android version:** 10 (052001A003004902006556692, 52.1.A.3.49)
**Signal version:** 5.3.12

### Link to debug log

https://debuglogs.org/6fed5b0d735b1b8b9937c1e8966175af40b163eff15317c1c531e2e05e46a83a

Crash:
```
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: java.lang.UnsupportedOperationException: Can only render images and videos. Found mimetype: 'audio/mpeg'
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.MediaSendFragmentPagerAdapter.getItem(MediaSendFragmentPagerAdapter.java:53)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:178)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.MediaSendFragmentPagerAdapter.instantiateItem(MediaSendFragmentPagerAdapter.java:65)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.View.measure(View.java:24564)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3012)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1839)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2128)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1727)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7612)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.Choreographer.doCallbacks(Choreographer.java:852)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.Choreographer.doFrame(Choreographer.java:787)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:883)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:100)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:359)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7418)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[5.3.12] [main ] 2021-02-20 07:34:34.798 MEZ E SignalUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
[5.3.12] [main ] 2021-02-20 07:34:34.802 MEZ I JobManager: Successfully flushed.
```

**Comment by Sgn-32** [comment]
The function getItem(int i) cannot handle audio files with text messages.

```
  @Override
  public Fragment getItem(int i) {
    Media mediaItem = media.get(i);

    if (MediaUtil.isGif(mediaItem.getMimeType())) {
      return MediaSendGifFragment.newInstance(mediaItem.getUri());
    } else if (MediaUtil.isImageType(mediaItem.getMimeType())) {
      return ImageEditorFragment.newInstance(mediaItem.getUri());
    } else if (MediaUtil.isVideoType(mediaItem.getMimeType())) {
      return MediaSendVideoFragment.newInstance(mediaItem.getUri(),
                                                mediaConstraints.getCompressedVideoMaxSize(ApplicationDependencies.getApplication()),
                                                mediaConstraints.getVideoMaxSize(ApplicationDependencies.getApplication()));
    } else {
      throw new UnsupportedOperationException("Can only render images and videos. Found mimetype: '" + mediaItem.getMimeType() + "'");
    }
  }
```
