### ISSUE TITLE
Saving media files from Manage Storage does not save the files to internal storage

### ISSUE THREAD

**Issue by broersma** [signalapp/Signal-Android#11050]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When saving media from Signal Storage to the device (either through Manage Storage or from a conversation) the media does not get saved.

### Steps to reproduce
- Go to Manage Storage
- Select one or more media items
- Press the Save button

**Actual result:** A pop-up shows up really quickly, then disappears. No files are saved to the internal storage.
**Expected result:** A pop-up shows up to warn you that other apps have access to the media after you save them. After pressing OK the files will get saved and will show up in a folder (e.g. Pictures/Movies) on the internal storage.

### Device info

**Device:** Samsung Galaxy J5
**Android version:** 6.0.1
**Signal version:** 4.5.7

### Link to debug log

https://debuglogs.org/7220e5282df2880e64834a005413dbdd34954fcbb6356beb2a5594dc0f3d3dea

**Comment by broersma** [comment]
### Work-around
The thread for #10159 mentions manually creating Movies and Pictures folders as a work-around. And this did allow me to save the media files.

### Speculation

I think this might be related to this fix 2cca6a5afb7138aa1eee1d30aea811529dd0091d to #10159, based on:
- me having an old phone running Android 6.0.1 (API 23) and some if-s relating to Build.VERSION.SDK_INT got changed in the commit, and
- on the stack trace from my debug log showing
```[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: null
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: java.io.FileNotFoundException: No such file or directory
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1009)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:751)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:118)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:81)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:38)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
[5.4.7] [5565 ] 2021-03-03 12:27:08.435 GMT+01:00 W SaveAttachmentTask: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by keponk** [comment]
Can confirm this issue with Samsung galaxy A3 running Android 7. And also with a Samsung galaxy A7 running Android 8.
Manually creating the "Movies" folder fixed the issue. Curiously the "Pictures" folder was already there, probably thanks to the camera/Gallery apps

**Comment by FRvanderVeen** [comment]
Can confirm this issue on a Samsung Galaxy S6 with Android 7.0 and Signal 5.13.18.

Manually creating the 'Pictures' folder on the SD card is a working workaround.

Digged a bit further into the code:
I found there is a StorageUtils class (which is called to get the appropriate Uri according to the mimetype of the attachment. Probably a similar method is needed to ensure the directory exists before calling 'openOutputStream' in 'saveAttachment' in 'SaveAttachmentTask.java'. I would think just before opening the inputstream.

**Comment by broersma** [comment]
I upgraded my phone in the meantime, so I am unable to check.

However, it seems (solely based on :eyes: the code) that 555e65d3eef9d58f497f552e8a43ac25272af1e7 which fixed #11505 also fixed this issue (because `ensureExternalPath` creates the missing paths if needed).
