### ISSUE TITLE
Signal Crashing with index out of bounds during backup restoration

### ISSUE THREAD

**Issue by Fuzion24** [signalapp/Signal-Android#11076]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I have a backup of Signal from a previous device.  When I attempt to restore the backup on my new device Signal crashes.

### Steps to reproduce
Create a Signal backup
Restore the Signal backup

**Actual result:** Signal Crashes during backup restoration
**Expected result:** Signal does not crash during backup restoration

This backup restore fails consistently in the same way. The backup was not corrupted, AFAICT.

### Device info

**Device:** Pixel device
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log
```
03-07 22:02:57.791 22459 22492 W FullBackupImporter: Bad MAC for attachment <REDACTED>! Can't restore it.
03-07 22:02:57.791 22459 22492 W FullBackupImporter: org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:322)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:149)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:86)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:249)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:240)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-07 22:02:57.791 22459 22492 W FullBackupImporter: 	at java.lang.Thread.run(Thread.java:923)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: Bad MAC for attachment <REDACTED>! Can't restore it.
03-07 22:02:57.849 22459 22492 W FullBackupImporter: org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:322)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:149)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:86)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:249)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:240)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-07 22:02:57.849 22459 22492 W FullBackupImporter: 	at java.lang.Thread.run(Thread.java:923)
--------- beginning of crash
03-07 22:02:58.000 22459 22492 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
03-07 22:02:58.000 22459 22492 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 22459
03-07 22:02:58.000 22459 22492 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.lang.System.arraycopy(System.java:524)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:338)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:278)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:80)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:249)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:240)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-07 22:02:58.000 22459 22492 E AndroidRuntime: 	... 4 more
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:923)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.lang.System.arraycopy(System.java:524)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:338)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:278)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:80)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:249)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:240)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-07 22:02:58.000 22459 22492 E SignalUncaughtExceptionHandler: 	... 4 more
03-07 22:02:58.009 22459 22492 I JobManager: Successfully flushed.
```

**Comment by deleted** [comment]
@Fuzion24 Sometimes, for whatever reason, message attachments serialize out in such a way that MAC authentication fails on import.

There's a lengthy thread about this category of problems in #8355

I hope someday this bug will get fixed, but if you're struggling to import one of your backups, I recommend trying this tool. It helped me:
https://github.com/bepaald/signalbackup-tools

**Comment by ckujau** [comment]
Trying to debug a failing backup restore here too. The backup file (2.8 GB) is from Signal 5.10.8 (taken on a fully patched Google Pixel 4 phone) and is supposed to be restored on a Google Pixel 5 (running Signal 5.10.8). The restore process started, it's counting messages, and then Signal just vanishes and maybe crashes.

With [no way to debug the Pixel 5](https://community.signalusers.org/t/backup-restore-another-bedtime-story/32776/5 "Backup & Restore: Another bedtime story") I tried to import the same backup file on a OnePlus One phone running LineageOS 18.1 (Android 11) with Signal 5.10.8 installed. This time I got a nice `org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException` and I was able to capture the logs while the restore was running. I also installed Signal Beta here (5.12.2) but got the same exception:

* Debug log with Signal [5.10.8](https://paste.ubuntu.com/p/YwSM3djF3S/)
* Debug log with Signal [5.12.2](https://paste.ubuntu.com/p/CzDyKGJmYZ/)

Excerpt from the latter:
```
05-21 11:44:21.642  9056  9093 W FullBackupImporter: Bad MAC for attachment 1601133505315! Can't restore it.
05-21 11:44:21.642  9056  9093 W FullBackupImporter: org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:373)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:170)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:103)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:75)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:248)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-21 11:44:21.642  9056  9093 W FullBackupImporter: 	at java.lang.Thread.run(Thread.java:923)
--------- beginning of crash
05-21 11:44:21.673  9056  9093 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-21 11:44:21.673  9056  9093 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9056
05-21 11:44:21.673  9056  9093 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.lang.System.arraycopy(System.java:524)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:389)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:329)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:96)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:75)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:248)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-21 11:44:21.673  9056  9093 E AndroidRuntime: 	... 4 more
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:923)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.lang.System.arraycopy(System.java:524)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:389)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:329)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:96)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:75)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:248)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-21 11:44:21.674  9056  9093 E SignalUncaughtException: 	... 4 more
05-21 11:44:21.686  9056  9093 I JobManager: Successfully flushed.
05-21 11:44:21.728   748 10045 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-21 11:44:21.748   748  3941 W ActivityTaskManager:   Force finishing activity org.thoughtcrime.securesms/.registration.RegistrationNavigationActivity
```
