### ISSUE TITLE
Crash on forward Media to chat which is temporary switched to SMS

### ISSUE THREAD

**Issue by UserX404** [signalapp/Signal-Android#11099]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
As already reported at [5.4 beta feedback thread](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-4-release/27904/430?u=userx404) Signal crashes if a media message is forwarded to  a signal user if the chat is switched to sms.

### Steps to reproduce
- select a media message from a chat (with text) and click on forward
- select some (3) signal members
- signal crashes

**Actual result:** see description above
**Expected result:** Ask for 'switch-back' to signal channel or at least send out via MMS

### Screenshots
Not necessary.

### Device info

**Device:** Sony Xperia XZ2 compact (H8324)
**Android version:** 10.0
**Signal version:** 5.4.12

### Link to debug log

https://debuglogs.org/6931d5ce47413ac7d7e6e4d984b3ee50fc2263aac1bf33ed5ad506b9a4e9ef9d

problematic part:
```
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: java.lang.IllegalStateException: Provided recipients to send to, but this is SMS!
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.MediaSendViewModel.onSendClicked(MediaSendViewModel.java:459)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.MediaSendActivity.onSend(MediaSendActivity.java:601)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.MediaSendActivity.onCameraContactsSendClicked(MediaSendActivity.java:578)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.-$$Lambda$T1NBgodExHvmqQCpzP_gHhk8W4c.run(Unknown Source:4)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.concurrent.SimpleTask.lambda$null$0(SimpleTask.java:33)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.concurrent.-$$Lambda$SimpleTask$LQGURywcMtNw-Jv626_pY2YfHUw.run(Unknown Source:6)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:883)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:100)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:359)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7418)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[5.4.12] [main ] 2021-03-11 20:24:04.017 MEZ E SignalUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by UserX404** [comment]
Close because works without crash on 5.9.6
