### ISSUE TITLE
Hard crash when get 'application/octet-stream' image

### ISSUE THREAD

**Issue by im7mortal** [signalapp/Signal-Android#11204]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I download image from the browser. [cat's nose](https://karimoku-cat.jp/wp/wp-content/uploads/2020/06/cat_smell_cover.jpeg)
I could see the image very well in the gallery.
I opened chat and click on "+"
I saw this image in the preview. 
I picked the image
The signal immediately crashed

### Steps to reproduce
Upload the image from link  [cat's nose](https://karimoku-cat.jp/wp/wp-content/uploads/2020/06/cat_smell_cover.jpeg) or any your which can cause  'application/octet-stream' crash to the Android phone
I open  chat and click on "+"
Pick the image
The signal immediately crashed

**Actual result:** it crashes
**Expected result:** at least it should tell something like "Image is not supported"; ideally if it would support it but it's other story

### Screenshots

![Screenshot_20210413-160927_Signal](https://user-images.githubusercontent.com/5336231/114632145-e78e4e80-9c72-11eb-9705-61451947c6e0.jpg)

### Device info

**Device:** `SM-G965U`  Samsung Galaxy s9+
**Android version:** 10
**Signal version:** first 5.5.5 then updated to (just now) 5.6.4 

### Link to debug log
https://debuglogs.org/5adf350a580f7c027b53ab48903b945924ab417307560d1805a1133ba52bae8c
*starts at* 
> [5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: java.lang.UnsupportedOperationException: Can only render images and videos. Found mimetype: 'application/octet-stream'

```
...
[5.6.4] [main ] 2021-04-13 15:36:00.929 PDT D LoggingFragment: [MentionsPickerFragment] onStart()
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: java.lang.UnsupportedOperationException: Can only render images and videos. Found mimetype: 'application/octet-stream'
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.mediasend.MediaSendFragmentPagerAdapter.getItem(MediaSendFragmentPagerAdapter.java:53)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at androidx.fragment.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:179)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.mediasend.MediaSendFragmentPagerAdapter.instantiateItem(MediaSendFragmentPagerAdapter.java:65)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1050)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.View.measure(View.java:26411)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3638)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2373)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2665)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.Choreographer.doFrame(Choreographer.java:732)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.os.Handler.handleCallback(Handler.java:883)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:100)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.os.Looper.loop(Looper.java:237)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[5.6.4] [main ] 2021-04-13 15:36:00.943 PDT E SignalUncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
[5.6.4] [main ] 2021-04-13 15:36:00.950 PDT I JobManager: Successfully flushed.
...
```

**Comment by mage1k99** [comment]
Hey, had the same issue today, have you checked the image extension ? by manually checking whether it has .jpg, or .png extension ??

**Comment by mage1k99** [comment]
just add .png or .jpg to the extension of the image and issue solved :)

**Comment by im7mortal** [comment]
@mage1k99  Mustn't it just reject this image with an error message?
The app goes to the wide variety third users who mustn't experience the hard crash

**Comment by mage1k99** [comment]
Yes, they could have warned, but application is crashing, lets hope they see this issue can fix it.

**Comment by mage1k99** [comment]
Is it the case for any image with an invalid extension, or is it for a specific image? @im7mortal

**Comment by mage1k99** [comment]
no, issue got fixed
