### ISSUE TITLE
Signal crashes after moving back to conversations menu

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#11218]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal randomly crashes after moving back to conversation menu

### Steps to reproduce
- When you're inside a conversation
- Press back 
- To get back to the conversation menu
- See Signal crash

### Device info

**Signal version:** 5.8.7

### Link to debug log
https://debuglogs.org/72f95752e064db56df9698e0ec1299e5d2602b3c59530d1a935d3a1c3f8e39fe

**Comment by cody-signal** [comment]
Hi @Xashyar, unfortunately there's no crash data in your logs ☹️ . I see where a call ended and then the app starts up again so guessing that's when the crash occurred but we just don't have logs for it. Most likely means it was a native crash. If it's reproducible, logging via adb and trying to pull the crash from that would be helpful.

**Comment by Xashyar** [comment]
Hi, @cody-signal, I think this crash is unrelated to calls, as I experienced it again without any call ongoing at that moment:

https://debuglogs.org/15c4226f672fd9083a6f1b3d8dccccf58874d2e3f52ba1c06898bbda5183a224

I'm updating the issue henceforth.

**Comment by cody-signal** [comment]
Thanks for the update, are you able to catch logs via adb and if there's any crashes in there? It seems like something with Android 6 and how we try to log crashes isn't working well anymore.

**Comment by Xashyar** [comment]
Hi @cody-signal, I don't see this crash anymore, probably fixed by this commit https://github.com/signalapp/Signal-Android/commit/14565b08644e3c6c2ba177187a26e6ce6c308cda

Closing.

**Comment by Xashyar** [comment]
This is still reproducible as of [5.33.6](https://github.com/signalapp/Signal-Android/releases/tag/v5.33.6), reopening.

**Comment by Xashyar** [comment]
This is observable in the Android bug report, when the crash occurs:

```
04-25 16:03:45.094  3042  3053 V WindowManager: Skipping AppWindowToken{98a0ef7 token=Token{e2b4af6 ActivityRecord{1220b91 u0 org.thoughtcrime.securesms/.conversation.ConversationActivity t240}}} -- going to hide
04-25 16:03:45.155  3042  3987 V WindowManager: Skipping AppWindowToken{98a0ef7 token=Token{e2b4af6 ActivityRecord{1220b91 u0 org.thoughtcrime.securesms/.conversation.ConversationActivity t240}}} -- going to hide
04-25 16:03:45.166  3042  4352 I HwMtmBroadcastResourceManager: removeReceiver mtm Broadcast
04-25 16:03:45.167  3042  4353 I HwMtmBroadcastResourceManager: removeReceiver mtm Broadcast
04-25 16:03:45.216  3042  3737 I ActivityManager: retrieveServiceLocked, callerApp: ProcessRecord{339aa54 4140:org.thoughtcrime.securesms/u0a120}, flags: 400
04-25 16:03:45.216  3042  3737 I ActivityManager: bindServiceLocked, r: ServiceRecord{fa451eb u0 euid: 0 org.thoughtcrime.securesms/.components.voice.VoiceNotePlaybackService}, euid: 0
04-25 16:03:45.285  3042  3052 V WindowManager: Skipping AppWindowToken{98a0ef7 token=Token{e2b4af6 ActivityRecord{1220b91 u0 org.thoughtcrime.securesms/.conversation.ConversationActivity t240}}} -- going to hide
04-25 16:03:45.416  4140  4140 F libc    : invalid address or address of corrupt block 0x55a51fa3c0 passed to try_realloc_chunk
04-25 16:03:45.416  4140  4140 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 4140 (crime.securesms)
04-25 16:03:45.485  2495  2495 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-25 16:03:45.486  2495  2495 F DEBUG   : Build fingerprint: 'Huawei/ALE-L21/hwALE-H:6.0/HuaweiALE-L21/C185B572:user/release-keys'
04-25 16:03:45.486  2495  2495 F DEBUG   : Revision: '0'
04-25 16:03:45.486  2495  2495 F DEBUG   : ABI: 'arm64'
04-25 16:03:45.486  2495  2495 F DEBUG   : pid: 4140, tid: 4140, name: crime.securesms  >>> org.thoughtcrime.securesms <<<
04-25 16:03:45.486  2495  2495 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
04-25 16:03:45.571  2495  2495 F DEBUG   : Abort message: 'invalid address or address of corrupt block 0x55a51fa3c0 passed to try_realloc_chunk'
04-25 16:03:45.572  2495  2495 F DEBUG   :     x0   0000000000000000  x1   0000007fa2685808  x2   0000000000000001  x3   635f636f6c6c6165
04-25 16:03:45.572  2495  2495 F DEBUG   :     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000028
04-25 16:03:45.572  2495  2495 F DEBUG   :     x8   7f7f7f7f7f7f7f7f  x9   fefefeff6a6d7467  x10  00000000deadbaad  x11  0101010101010101
04-25 16:03:45.572  2495  2495 F DEBUG   :     x12  0000007fa2685800  x13  20652086315b54a7  x14  20652086315b54a7  x15  0006345c0d839d36
04-25 16:03:45.572  2495  2495 F DEBUG   :     x16  0000007fa267f9e8  x17  0000000000000000  x18  00000000ffffffd8  x19  0000000000000000
04-25 16:03:45.572  2495  2495 F DEBUG   :     x20  00000055a51fa3c0  x21  0000007fa2686000  x22  00000055a51fa3c0  x23  0000000000000004
04-25 16:03:45.572  2495  2495 F DEBUG   :     x24  0000000000000003  x25  0000000000000019  x26  0000000000000001  x27  0000000000000000
04-25 16:03:45.572  2495  2495 F DEBUG   :     x28  0000000000000000  x29  0000007fd5567320  x30  0000007fa25e922c
04-25 16:03:45.572  2495  2495 F DEBUG   :     sp   0000007fd5567320  pc   0000007fa25e9238  pstate 0000000060000000
04-25 16:03:45.588  2495  2495 F DEBUG   : 
04-25 16:03:45.588  2495  2495 F DEBUG   : backtrace:
04-25 16:03:45.588  2495  2495 F DEBUG   :     #00 pc 0000000000046238  /system/lib64/libc.so (try_realloc_chunk.constprop.6+644)
04-25 16:03:45.588  2495  2495 F DEBUG   :     #01 pc 0000000000048a08  /system/lib64/libc.so (dlrealloc+88)
04-25 16:03:45.588  2495  2495 F DEBUG   :     #02 pc 0000000000019d10  /system/lib64/libc.so (realloc+20)
04-25 16:03:45.588  2495  2495 F DEBUG   :     #03 pc 00000000002a2ce4  /system/lib64/libskia.so (_Z16sk_realloc_throwPvm+16)
04-25 16:03:45.588  2495  2495 F DEBUG   :     #04 pc 00000000001a32b8  /system/lib64/libskia.so (_ZN9SkPathRef11growForVerbEif+124)
04-25 16:03:45.588  2495  2495 F DEBUG   :     #05 pc 000000000019bf28  /system/lib64/libskia.so (_ZN6SkPath7cubicToEffffff+92)
04-25 16:03:45.588  2495  2495 F DEBUG   :     #06 pc 00000000740b1a50  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x23e5000)
04-25 16:03:45.745  3042  3970 I HwActivityManagerService: PackageName for pid 22184 is ch.protonvpn.android
04-25 16:03:45.749  3042  3351 I HwActivityManagerService: PackageName for pid 22184 is ch.protonvpn.android
04-25 16:03:46.767  3042  3737 I HwActivityManagerService: PackageName for pid 22184 is ch.protonvpn.android
04-25 16:03:46.770  3042  4353 I HwActivityManagerService: PackageName for pid 22184 is ch.protonvpn.android
04-25 16:03:46.944  2495  2495 F DEBUG   : 
04-25 16:03:46.944  2495  2495 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_09
04-25 16:03:46.957  3042  6783 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
04-25 16:03:46.957  3042  3139 I BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
04-25 16:03:46.963  3042  3139 W DropBoxManagerService: Dropping: SYSTEM_TOMBSTONE (10 > 0 bytes)
04-25 16:03:46.993  3042  6783 V HwWindowManagerService: moveTaskToTop mTaskChanged:true
04-25 16:03:46.998  3042  6784 W DropBoxManagerService: Dropping: data_app_native_crash (2007 > 0 bytes)
04-25 16:03:46.998  3042  6783 V HwWindowManagerService: setFocusedApp update app ops, mTaskChanged set to:false
04-25 16:03:47.140  3042  3970 I WindowState: WIN DEATH: Window{32f9783 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}
04-25 16:03:47.142  3042  3405 D WifiService: Client connection lost with reason: 4
04-25 16:03:47.146  3042  3053 I WindowState: WIN DEATH: Window{5c37620 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}
04-25 16:03:47.300  3042  6783 I WindowManager: Screenshot max retries 4 of Token{8d9656b ActivityRecord{ea8e2ba u0 org.thoughtcrime.securesms/.RoutingActivity t240 f}} appWin=Window{5c37620 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity EXITING} drawState=1
04-25 16:03:47.311  3042  6783 W ActivityManager: Exception thrown during pause
04-25 16:03:47.311  3042  6783 W ActivityManager: android.os.DeadObjectException
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:505)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1094)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3688)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3512)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:3332)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12856)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:12751)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:13458)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12960)
04-25 16:03:47.311  3042  6783 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
04-25 16:03:47.318  3042  3737 D SmartHeartBeat: setAlarmsAdjust...
04-25 16:03:47.324  3042  3042 I ActivityManager: collectReceiverComponents for intent: Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) }, receivers: [ResolveInfo{aeab48 com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver m=0x108000 euid=0}, ResolveInfo{43f0de1 com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver m=0x108000 euid=0}]
04-25 16:03:47.327  3042  3042 I ActivityManager: collectReceiverComponents for intent: Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) }, receivers: [ResolveInfo{219a706 com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver m=0x108000 euid=0}, ResolveInfo{a7421c7 com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver m=0x108000 euid=0}]
04-25 16:03:47.327  3042  3511 I ActivityManager: Process org.thoughtcrime.securesms (pid 4140) has died
04-25 16:03:47.328  3042  3511 D ActivityManager: cleanUpApplicationRecord -- 4140
04-25 16:03:47.328  3042  3511 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{18a4a7a u0 euid: 0 org.thoughtcrime.securesms/.jobmanager.KeepAliveService}
04-25 16:03:47.329  3042  3511 I ActivityManager: cleanUpApplicationRecordLocked, reset pid: 4140, euid: 0
04-25 16:03:47.355  3042  3985 I ActivityManager: retrieveServiceLocked, callerApp: ProcessRecord{6fa3b90 20874:com.google.android.gms.persistent/u0a7}, flags: 400
04-25 16:03:47.359  3042  3985 I ActivityManager: bindServiceLocked, r: ServiceRecord{ca733f4 u0 euid: 0 com.google.android.gms/.stats.service.DropBoxEntryAddedService}, euid: 0
04-25 16:03:47.369  3042  3135 W ActivityManager: Skipping native crash dialog of ProcessRecord{339aa54 0:org.thoughtcrime.securesms/u0a120}
04-25 16:03:47.370  3042  3052 I ActivityManager: retrieveServiceLocked, callerApp: ProcessRecord{6fa3b90 20874:com.google.android.gms.persistent/u0a7}, flags: 400
04-25 16:03:47.371  3042  3052 I ActivityManager: bindServiceLocked, r: ServiceRecord{7bda71d u0 euid: 0 com.google.android.gms/.chimera.GmsIntentOperationService}, euid: 0
```

**Comment by Xashyar** [comment]
Still reproducible.

**Comment by Xashyar** [comment]
Not been able to reproduce it lately, but keeping it open a little while longer, just in case.
