### ISSUE TITLE
AssertionError in AvatarUtil.java:133

### ISSUE THREAD

**Issue by hiqua** [signalapp/Signal-Android#11234]
- [X] I have searched open and closed issues for duplicates
- ~~I am submitting a bug report for existing functionality that does not work as intended~~ not really, no visible bug AFAICT
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Assertion error in log. No visible impact, but since it literally says "this call should not fail", I thought I'd report it anyway.

### Steps to reproduce

Unknown.

```
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: java.lang.AssertionError: This call should not fail.
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.AvatarUtil.getIconForShortcut(AvatarUtil.java:113)
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.ConversationUtil.buildShortcutInfo(ConversationUtil.java:212)
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.ConversationUtil.setActiveShortcuts(ConversationUtil.java:168)
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.ConversationShortcutUpdateJob.onRun(ConversationShortcutUpdateJob.java:85)
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[5.7.6] [1958 ] 2021-04-22 21:21:04.300 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

### Device info

**Android version:** 11
**Signal version:** 5.7.6

### Link to debug log
https://debuglogs.org/c885d6c5bfaecf3b28704b9c84fc31b124ec103132d459f2d8f986d2739eb9ce

**Comment by alex-signal** [comment]
Thanks for your report! I've made a change to pass through the exception in a future release (currently slated for 5.10) so that if this happens in the future, we at least know what happened.

**Comment by hiqua** [comment]
Ok great, I'll keep looking then!
