### ISSUE TITLE
Singal crashes a few seconds after launching

### ISSUE THREAD

**Issue by 1nikolas** [signalapp/Signal-Android#11248]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Started happening after updating to 5.10.1. The app opens, and after a few seconds it crashes. UI loads, just fine but then it crashes. Also Android 11 bubbles make the app crash

### Steps to reproduce
- Open the app

**Actual result:** crash
**Expected result:** not crash

### Screenshots

none

### Device info

**Device:** OnePlus 7T
**Android version:** 11.0
**Signal version:** 5.10.1

### Link to debug log

Can't access debug logs, here is the crash log
```
java.lang.NullPointerException: Attempt to get length of null array
at org.whispersystems.util.Base64.encodeBytes(Base64.java:723)
at org.thoughtcrime.securesms.util.Base64.encodeBytes(Base64.java:17)
at org.thoughtcrime.securesms.storage.StorageSyncHelper.lambda$findIdDifference$3(StorageSyncHelper.java:74)
at org.thoughtcrime.securesms.storage.-$$Lambda$StorageSyncHelper$BYmkyDpyxGuiCon_XA8FRfwEku4.apply(Unknown Source:2)
at com.annimon.stream.Collectors$8.accept(Collectors.java:163)
at com.annimon.stream.Collectors$8.accept(Collectors.java:160)
at com.annimon.stream.Stream.collect(Stream.java:1579)
at org.thoughtcrime.securesms.storage.StorageSyncHelper.findIdDifference(StorageSyncHelper.java:74)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:229)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:181)
at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by cody-signal** [comment]
Thanks, we're already on it and a fix is in 5.10.2 which will go out soon.

**Comment by tsikmartin** [comment]
I am having similar issue when muting Group messages from users who do not have signal, signal crashes upon opening (BETA TESTER).

It has made my default sms app useless right now.

**Comment by tsikmartin** [comment]
is there an ETA on when the update will be released so we are able to resume using signal? @cody-signal

**Comment by cody-signal** [comment]
Should be out now in .2 or .3 in the beta channels.

**Comment by 1nikolas** [comment]
Yeah problem is solved thanks :)
