### ISSUE TITLE
Crash when making a backup

### ISSUE THREAD

**Issue by Nisc3d** [signalapp/Signal-Android#11277]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Crashes when at the end of taking a Backup. No Backup File is created.

### Steps to reproduce
- Create a Backup

**Actual result:** Signal crashes
**Expected result:** Backup File should be created

### Device info
**Device:** Motorola Moto G Pro
**Android version:** 11
**Signal version:** 5.9.7

### Link to debug log
https://debuglogs.org/d69de3cd3ee5e48f3b4d6750e1e9d11a3a1bb580d0e94a3a71c6d46ff162463c

Relevant Part I think:

```
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:923)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: Caused by: java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Pictures/image.png bucket_display_name=Pictures volume_name=external_primary date_modified=null date_expires=null _display_name=image.png mime_type=image/png _data=/storage/emulated/0/Pictures/image.png _size=null is_trashed=0 is_pending=0 bucket_id=-1617409521 relative_path=Pictures/
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.os.Parcel.createException(Parcel.java:2357)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.os.Parcel.readException(Parcel.java:2340)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.content.ContentProviderProxy.update(ContentProviderNative.java:649)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.content.ContentResolver.update(ContentResolver.java:2356)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.content.ContentResolver.update(ContentResolver.java:2318)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:132)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:81)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:38)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5.9.7] [263444] 2021-05-10 12:17:14.621 GMT+02:00 E SignalUncaughtException: 	... 3 more
```

**Comment by Nisc3d** [comment]
Correction: After a second try it worked. I am still leaving this issue open, maybe it has some relevance.

**Comment by douglasg14b** [comment]
This was happening to me as well, except that my phone would crash, not just signal.

And re-opening signal after the phone restarted will prompt for the unlock, and then freeze, and crash my phone. After a few retries signal actually opened and no backup has been made, if I try and backup again it gets to ~4500 and then crashes again.

Rinse and repeat.

**Comment by Nisc3d** [comment]
@douglasg14b do you have a debug log?

**Comment by douglasg14b** [comment]
Debug log: https://debuglogs.org/9ca2cef8c5e2d4e2d36e18da2efd653d2ed02915c031c30fa9485f4b882801d6

**Comment by douglasg14b** [comment]
> Is this still relevant?

Seems so, did my partners phone the other week, just as unstable.

>  If so, what is blocking it?

... response times/maintainer bandwidth?

**Comment by douglasg14b** [comment]
Playing the bumping game?
