### ISSUE TITLE
I get this error when sending a message as a video

### ISSUE THREAD

**Issue by khanhduy1407** [signalapp/Signal-Android#11309]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.ninetalk.talk, PID: 13060
    java.lang.UnsatisfiedLinkError: No implementation found for int org.thoughtcrime.securesms.util.FileUtils.createMemoryFileDescriptor(java.lang.String) (tried Java_org_thoughtcrime_securesms_util_FileUtils_createMemoryFileDescriptor and Java_org_thoughtcrime_securesms_util_FileUtils_createMemoryFileDescriptor__Ljava_lang_String_2)
        at org.ninetalk.talk.util.FileUtils.createMemoryFileDescriptor(Native Method)
        at org.ninetalk.talk.util.MemoryFileDescriptor.supported(MemoryFileDescriptor.java:36)
        at org.ninetalk.talk.mms.MediaConstraints.isVideoTranscodeAvailable(MediaConstraints.java:92)
        at org.ninetalk.talk.mms.PushMediaConstraints.getUncompressedVideoMaxSize(PushMediaConstraints.java:58)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.lambda$getFilteredMedia$10(MediaSendViewModel.java:580)
        at org.ninetalk.talk.mediasend.-$$Lambda$MediaSendViewModel$nLhKmxxdhc69F0udsJg-sz2Jdas.test(Unknown Source:6)
        at com.annimon.stream.operator.ObjFilter.nextIteration(ObjFilter.java:43)
        at com.annimon.stream.operator.ObjFilter.hasNext(ObjFilter.java:22)
        at com.annimon.stream.Stream.toList(Stream.java:1538)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.getFilteredMedia(MediaSendViewModel.java:581)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.lambda$onSelectedMediaChanged$1(MediaSendViewModel.java:149)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.lambda$onSelectedMediaChanged$1$MediaSendViewModel(Unknown Source:0)
        at org.ninetalk.talk.mediasend.-$$Lambda$MediaSendViewModel$xDi8R0vPoOkASk5bOqEjobFrSw0.run(Unknown Source:10)
        at org.signal.core.util.ThreadUtil.runOnMain(ThreadUtil.java:51)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.lambda$onSelectedMediaChanged$2(MediaSendViewModel.java:148)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.lambda$onSelectedMediaChanged$2$MediaSendViewModel(Unknown Source:0)
        at org.ninetalk.talk.mediasend.-$$Lambda$MediaSendViewModel$ySCxWUMItboicsZ5XEMtoqKm_Zw.onComplete(Unknown Source:10)
        at org.ninetalk.talk.mediasend.MediaRepository.getPopulatedMedia(MediaRepository.java:79)
        at org.ninetalk.talk.mediasend.MediaSendViewModel.onSelectedMediaChanged(MediaSendViewModel.java:147)
        at org.ninetalk.talk.mediasend.MediaSendActivity.onCreate(MediaSendActivity.java:279)
        at org.ninetalk.talk.PassphraseRequiredActivity.onCreate(PassphraseRequiredActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:7146)
        at android.app.Activity.performCreate(Activity.java:7137)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2876)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3001)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6750)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

**Comment by hiqua** [comment]
Can you also add a debug log?

**Comment by Masqueey** [comment]
Once you encounter this bug again, you should go to setting, help, debug log, send. Then copy the link and paste it here. Otherwise developers can't fix your issue.
