### ISSUE TITLE
I have some errors that I need your help with

### ISSUE THREAD

**Issue by khanhduy1407** [signalapp/Signal-Android#11301]
When I run the project, after creating the PIN or disabling the PIN I get this error 

E/AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
    Process: org.thoughtcrime.securesms, PID: 11443
    java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.read(Quote.java:105)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.readZero(Quote.java:111)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.<init>(Quote.java:62)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.validateAndBuildRemoteAttestation(RemoteAttestationUtil.java:121)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.getAndVerifyMultiRemoteAttestation(RemoteAttestationUtil.java:70)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:381)
        at org.thoughtcrime.securesms.contacts.sync.ContactDiscoveryV2.getDirectoryResult(ContactDiscoveryV2.java:69)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:231)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:102)
        at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:74)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
E/SignalUncaughtException: java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.read(Quote.java:105)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.readZero(Quote.java:111)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.<init>(Quote.java:62)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.validateAndBuildRemoteAttestation(RemoteAttestationUtil.java:121)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.getAndVerifyMultiRemoteAttestation(RemoteAttestationUtil.java:70)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:381)
        at org.thoughtcrime.securesms.contacts.sync.ContactDiscoveryV2.getDirectoryResult(ContactDiscoveryV2.java:69)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:231)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:102)
        at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:74)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)

**Comment by hiqua** [comment]
> When I run the project

How do you run it?

If you compile your own version, please ask on https://community.signalusers.org/c/development/android-development/22 instead.

**Comment by Sgn-32** [comment]
Hi,
i had the same problem with self-build Signal. It's the used JDK version. Android Studio had automatically updated to Java 13.
I had changed it to openJDK 1.8 (Java 8). Now it works without this issue.
