### ISSUE TITLE
Crash when tried to send image which has invalid or no extension

### ISSUE THREAD

**Issue by mage1k99** [signalapp/Signal-Android#11308]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal app crashes when image selected for sending has no extension or weird extension (not png or jpg). 

note : the image can be viewed by other image viewer or can be sent through other platforms like telegram.

### Steps to reproduce
- opens signal chat, clicks '+' icon to send image
- selects image with different format
- signal crashes

**Actual result:** Signal crashes

**Expected result:** Signal would have displayed a warning message, that the 'extension of image is invalid' or just send the image without crashing

### Screenshots
N/A

### Device info
**Device:** Redmi K20 Pro ( Raphael)
**Android version:** 10.0
**Signal version:** 5.11.3

### Link to debug log

**Check the crash log by clicking [https://del.dog/signalCrashImage.txt](https://del.dog/signalCrashImage.txt)**

or check this

### Issues with same problem.
 I have searched for the issues of same problem found 2 of them.

Issue #11204 and Issue #10980

```
time: 1621229128471
msg: java.lang.UnsupportedOperationException: Can only render images and videos. Found mimetype: 'application/octet-stream'
stacktrace: java.lang.UnsupportedOperationException: Can only render images and videos. Found mimetype: 'application/octet-stream'
	at org.thoughtcrime.securesms.mediasend.MediaSendFragmentPagerAdapter.getItem(MediaSendFragmentPagerAdapter.java:53)
	at androidx.fragment.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:179)
	at org.thoughtcrime.securesms.mediasend.MediaSendFragmentPagerAdapter.instantiateItem(MediaSendFragmentPagerAdapter.java:65)
	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25097)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```

**Comment by hiqua** [comment]
Is it the case for any image with an invalid extension, or is it for a specific image?

Are you able to share an image that creates triggers this bug on your phone? Obviously don't share it if it contains faces etc.

**Comment by mage1k99** [comment]
For me images downloaded from reddit, Check Issue #11204, they have type different image causing crash.

But these images can be sent through other applications like telegram

Here is the [image](https://yeemail.fossfreaks.com/cloud/index.php/s/F38bw2fxfsNBsmF) used.

----

### Steps of done for producing the bugs

- When I download the image from reddit (Official android client), It gets downloaded without the dot

![image from reddit](https://user-images.githubusercontent.com/46259860/118635186-ecee3400-b7f0-11eb-8f11-2b807ef95b70.jpeg)

> eg: image.jpg gets downloaded as imagejpg

- But the image  can be viewed by any application, can be sent as mime type image/jpg (as image with compression applied) on other platforms

- When rename it by adding dot (eg: imagejpg to image.jpg) it can be sent in signal without crashes

![Renaming Image](https://user-images.githubusercontent.com/46259860/118635788-9cc3a180-b7f1-11eb-8797-e8b6543fbbba.jpeg)

![Able to send the image](https://user-images.githubusercontent.com/46259860/118635989-d2688a80-b7f1-11eb-91cb-511fb7bf7d21.jpeg)

-----

### When I tried While re-producing the bug
- **To re-produce** the bug 
- I tried to re-produce the bug by renaming the image by removing the extension (removing the dot).

![image from reddit](https://user-images.githubusercontent.com/46259860/118635186-ecee3400-b7f0-11eb-8f11-2b807ef95b70.jpeg)

- But it does not up show in image picker.

![But it does not up show in image picker.](https://user-images.githubusercontent.com/46259860/118636184-093ea080-b7f2-11eb-97e9-b56126da5953.jpeg)

**Comment by mage1k99** [comment]
Yes, it appears on gallery I mean when downloaded from the reddit client it appears but when I perform modification like adding extension and removing it to check if its visible on gallery, it does not show up. 

It can be sent on other application like telegram.


so you could add try catch for selecting image, and display warning if its unsupported like that instead of crashing the whole application.

**Comment by mage1k99** [comment]
In recent beta release of signal I couldn't reproduce the bug. seems like might be fixed ? I can't download the reddit image too. as it comes with proper extension.

So this issue is not anymore a problem. 


closing it, If not fixed reopen the issue.

:)
