### ISSUE TITLE
Audio not working in video calls due to an issue with microphone permissions

### ISSUE THREAD

**Issue by ljpp** [signalapp/Signal-Android#11378]
### Bug description

Signal seems to lose the permission to use the microfone in video/audio calls, thus audio is not delivered

### Steps to reproduce

This has now happened twice during this week. I simply made a video call, which connected but my voice was not heard at the other end. Tested this by calling in between my two phones as well, and was able to reproduce.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Audio missing from the call.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Video calls with audio

### Device info

**Device:** Xiaomi Mi A3
**Android version:** Android One, up-to-date with Android 11 and May security patches.
**Signal version:** 5.13.8

Note: The device is managed by Google Family Link. Signal app has unlimited screen time.

### Workaround

By going to Android app settings and disabling and re-enabling microphone permission fixes the issue, but it came back after a few days.

**Comment by UESCTerm** [comment]
Moved from lineage 17.1 android 10 to lineage 18.1 android 11 and transfer went OK, but audio does not work. Video works, no audio. Disable re-enable does not work.  Voice memo crashes app.

**Comment by UserX404** [comment]
Hello @UESCTerm 
Append a debug log.
I'm also running on LOS 18.1 without problems.

**Comment by UESCTerm** [comment]
https://debuglogs.org/99c703bd7200edba4a8a7b7abd28fec82ccbf5a8669f7da815e4220f10f53920

On August 13, 2021 4:54:05 PM EDT, UserX ***@***.***> wrote:
>Hello @UESCTerm 
>Append a debug log.
>I'm also running on LOS 18.1 without problems.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/Signal-Android/issues/11378#issuecomment-898715101

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UserX404** [comment]
Hi
You are using the website release without google service, what shouldn't matter.
As far as i've checked LOS page your device isn't supported officially. Are you using [this](https://forum.xda-developers.com/t/rom-11-unofficial-laurel_sprout-oss-lineageos-18-1.4240953/) unofficial release?
Maybe you could contact the LOS dev.

What i can see there are several exceptions due too invalid audio buffer size which certainly leads to your issue.
Some reference for the devs:
```
[5.20.4] [main ] 2021-08-13 16:09:53.216 EDT I AudioRecorder: startRecording()
[5.20.4] [994  ] 2021-08-13 16:09:53.217 EDT I AudioRecorder: Running startRecording() + 994
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: java.lang.IllegalArgumentException: Invalid audio buffer size -20 (frame size 2)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at android.media.AudioRecord.audioBuffSizeCheck(AudioRecord.java:875)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at android.media.AudioRecord.<init>(AudioRecord.java:397)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at android.media.AudioRecord.<init>(AudioRecord.java:301)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.audio.AudioCodec.createAudioRecord(AudioCodec.java:188)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.audio.AudioCodec.<init>(AudioCodec.java:40)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.audio.AudioRecorder.lambda$startRecording$2(AudioRecorder.java:55)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.audio.AudioRecorder.lambda$startRecording$2$AudioRecorder(Unknown Source:0)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at org.thoughtcrime.securesms.audio.-$$Lambda$AudioRecorder$5-RbVKUXLjLZsgJVURvLvR-3XFQ.run(Unknown Source:2)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:923)
[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException: 
```

**Comment by UESCTerm** [comment]
It is supported and images provided.

https://wiki.lineageos.org/devices/apollon

M2007J3SG


On August 15, 2021 7:20:41 AM EDT, UserX ***@***.***> wrote:
>Hi
>You are using the website release without google service, what
>shouldn't matter.
>As far as i've checked LOS page your device isn't supported officially.
>Are you using
>[this](https://forum.xda-developers.com/t/rom-11-unofficial-laurel_sprout-oss-lineageos-18-1.4240953/)
>unofficial release?
>Maybe you could contact the LOS dev.
>
>What i can see there are several exceptions due too invalid audio
>buffer size which certainly leads to your issue.
>Some reference for the devs:
>```
>[5.20.4] [main ] 2021-08-13 16:09:53.216 EDT I AudioRecorder:
>startRecording()
>[5.20.4] [994  ] 2021-08-13 16:09:53.217 EDT I AudioRecorder: Running
>startRecording() + 994
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>java.lang.IllegalArgumentException: Invalid audio buffer size -20
>(frame size 2)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at android.media.AudioRecord.audioBuffSizeCheck(AudioRecord.java:875)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at android.media.AudioRecord.<init>(AudioRecord.java:397)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at android.media.AudioRecord.<init>(AudioRecord.java:301)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>org.thoughtcrime.securesms.audio.AudioCodec.createAudioRecord(AudioCodec.java:188)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>org.thoughtcrime.securesms.audio.AudioCodec.<init>(AudioCodec.java:40)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>org.thoughtcrime.securesms.audio.AudioRecorder.lambda$startRecording$2(AudioRecorder.java:55)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>org.thoughtcrime.securesms.audio.AudioRecorder.lambda$startRecording$2$AudioRecorder(Unknown
>Source:0)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>org.thoughtcrime.securesms.audio.-$$Lambda$AudioRecorder$5-RbVKUXLjLZsgJVURvLvR-3XFQ.run(Unknown
>Source:2)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at
>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>	at java.lang.Thread.run(Thread.java:923)
>[5.20.4] [994  ] 2021-08-13 16:09:53.225 EDT E SignalUncaughtException:
>
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/signalapp/Signal-Android/issues/11378#issuecomment-899035242

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UserX404** [comment]
> It is supported and images provided. https://wiki.lineageos.org/devices/apollon M2007J3SG

Sorry, i messed it up with the OP issue template which deals with Mi A3.
