### ISSUE TITLE
Error updating to 5.15.6 on LineageOS 17.1

### ISSUE THREAD

**Issue by greasy-crow** [signalapp/Signal-Android#11446]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I try to update Signal to the latest version using the Aurora Store on my device, the update process fails and gives me an error that says "open failed ENOENT (No such file or directory)." I have never had issues updating or installing Signal before, and I am not familiar with this error.

### Steps to reproduce
- find the page for Signal in whatever version of the play store you are using (in my case it is Aurora Store)
- click the "Update" prompt and wait for the update to download
- the installation stops halfway through and gives am error message

### Device info

**Device:** Oneplus 6T
**Android version:** LineageOS 17.1
**Signal version:** Current version: 5.6.4 Desired version: 5.15.6

The error it gives is as follows
`java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
	at androidx.core.content.FileProvider.openFile(:2)
	at android.content.ContentProvider.openAssetFile(ContentProvider.java:1712)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1894)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1961)
	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:511)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
	at e.b.a.q.g.h.a(:9)
	at e.b.a.a.a.g.h.a(:1)
	at e0.a.a.l0$a.a(:1)
	at e0.a.a.y$a.run(:2)
	at e0.a.a.p0.l.run(Unknown Source:9)
	at java.lang.Thread.run(Thread.java:919)`

**Comment by Nihal247** [comment]
Hi @greasy-crow and thank you for your patience.

I am unaware of this problem, but if you want to update the Signal, you can use APKPure to update it.

Thank you in advance.

**Comment by jonbenfri** [comment]
I had the same issue. I installed 5.18.4 beta via APK Mirror and the upgrade succeeded.

Potentially related commit: https://github.com/signalapp/Signal-Android/commit/7ccba5b1c844bed7a72d4e3ca4488d7650f725b5
