### ISSUE TITLE
yes-E164 certificate required to connect to server

### ISSUE THREAD

**Issue by MikaMaracuja** [signalapp/Signal-Android#11472]
This is not a duplicate: 
https://github.com/signalapp/Signal-Android/issues/5100

### Bug description
On Win10 with Kaspersky, the self-signed certificate of whispersystems is not allowed and thus a successful connection cannot be established.

### Steps to reproduce
- Start Signal. Try to connect.

**Actual result:** No Server Connection
**Expected result:** Client should connect and authenticate successfully to the server, even with high SSL policies enabled.

### Screenshots
![grafik](https://user-images.githubusercontent.com/15981220/125929984-5a5808ba-ebc2-4a0c-9107-ac8063febede.png)

### Device info
Win10
**Device:** Dell Latitude 7490
**Android version:** 0.0.0
**Signal version:** Signal Desktop 5.8.0

### Link to debug log
(unable to upload detailed logs to the signalapp servers)
ERROR 2021-07-16T09:47:36.332Z GET https://textsecure-service.whispersystems.org/v1/config 0 Error
ERROR 2021-07-16T09:47:36.338Z Top-level unhandled promise rejection: HTTPError: promiseAjax catch; code: -1
    at makeHTTPError ([REDACTED]\resources\app.asar\preload.bundle.js:2:5597728)
    at [REDACTED]\resources\app.asar\preload.bundle.js:2:5597366
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Original stack:
FetchError: request to https://textsecure-service.whispersystems.org/v1/config failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> ([REDACTED]\resources\app.asar\node_modules\node-fetch\lib\index.js:1464:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Initial stack:
Error
    at _outerAjax ([REDACTED]\resources\app.asar\preload.bundle.js:2:5597629)
    at _ajax ([REDACTED]\resources\app.asar\preload.bundle.js:2:5619775)
    at Object.getConfig ([REDACTED]\resources\app.asar\preload.bundle.js:2:5602405)
    at Object.q.refreshRemoteConfig ([REDACTED]\resources\app.asar\preload.bundle.js:2:3713675)
    at invokeFunc ([REDACTED]\resources\app.asar\preload.bundle.js:2:2095637)
    at leadingEdge ([REDACTED]\resources\app.asar\preload.bundle.js:2:2095710)
    at Object.debounced [as maybeRefreshRemoteConfig] ([REDACTED]\resources\app.asar\preload.bundle.js:2:2096132)
    at Object.q.initRemoteConfig ([REDACTED]\resources\app.asar\preload.bundle.js:2:3713402)
    at [REDACTED]\resources\app.asar\preload.bundle.js:2:3761361
ERROR 2021-07-16T09:47:36.345Z GET https://textsecure-service.whispersystems.org/v1/config 0 Error
ERROR 2021-07-16T09:47:36.345Z connect: Error refreshing remote config: HTTPError: promiseAjax catch; code: -1
    at makeHTTPError ([REDACTED]\resources\app.asar\preload.bundle.js:2:5597728)
    at [REDACTED]\resources\app.asar\preload.bundle.js:2:5597366
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Original stack:
FetchError: request to https://textsecure-service.whispersystems.org/v1/config failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> ([REDACTED]\resources\app.asar\node_modules\node-fetch\lib\index.js:1464:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Initial stack:
Error

...

WARN  2021-07-16T09:47:43.019Z Sender certificate service could not fetch a yes-E164 certificate. Returning undefined HTTPError: promiseAjax catch; code: -1
    at makeHTTPError ([REDACTED]\resources\app.asar\preload.bundle.js:2:5597728)
    at [REDACTED]\resources\app.asar\preload.bundle.js:2:5597366
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Original stack:
FetchError: request to https://textsecure-service.whispersystems.org/v1/certificate/delivery failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> ([REDACTED]\resources\app.asar\node_modules\node-fetch\lib\index.js:1464:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Initial stack:
Error
    at _outerAjax ([REDACTED]\resources\app.asar\preload.bundle.js:2:5597629)
    at _ajax ([REDACTED]\resources\app.asar\preload.bundle.js:2:5619775)
    at Object.getSenderCertificate ([REDACTED]\resources\app.asar\preload.bundle.js:2:5606553)
    at Qe.requestSenderCertificate ([REDACTED]\resources\app.asar\preload.bundle.js:2:5180846)
    at Qe.fetchAndSaveCertificate ([REDACTED]\resources\app.asar\preload.bundle.js:2:5179943)
    at async [REDACTED]\resources\app.asar\preload.bundle.js:2:5179241
INFO  2021-07-16T09:47:43.020Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]8a9/[REDACTED]f31 (unauth)
INFO  2021-07-16T09:47:43.021Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]089/[REDACTED]376 (unauth)
INFO  2021-07-16T09:47:43.027Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]b63/[REDACTED]3a3 (unauth)
INFO  2021-07-16T09:47:43.029Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]e96/[REDACTED]07a (unauth)
INFO  2021-07-16T09:47:43.031Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]d90/[REDACTED]380 (unauth)
ERROR 2021-07-16T09:47:43.403Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]b63/[REDACTED]3a3 0 Error
ERROR 2021-07-16T09:47:43.414Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]d90/[REDACTED]380 0 Error
ERROR 2021-07-16T09:47:43.417Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]8a9/[REDACTED]f31 0 Error
ERROR 2021-07-16T09:47:43.418Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]089/[REDACTED]376 0 Error
ERROR 2021-07-16T09:47:43.419Z GET https://textsecure-service.whispersystems.org/v1/profile/[REDACTED]e96/[REDACTED]07a 0 Error

**Comment by Genis-Sage** [comment]
hey @MikaMaracuja 
you are describing an issue with the Desktop Client, but you are in the Android repo
please close the issue here, and open it here: https://github.com/signalapp/Signal-Desktop/issues
(after checking, if there is there is not already somewhere a ticket about it)
