### ISSUE TITLE
Crashes at startup

### ISSUE THREAD

**Issue by Fregf** [signalapp/Signal-Android#11474]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since updating Signal beta to 5.17.0, Signal immediately crashes at startup.

Logcat:
```
07-16 16:48:37.704 18539 18539 D AndroidRuntime: Shutting down VM
07-16 16:48:37.705 18539 18539 E AndroidRuntime: FATAL EXCEPTION: main
07-16 16:48:37.705 18539 18539 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18539
07-16 16:48:37.705 18539 18539 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.NullPointerException: Attempt to get length of null array
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.signal.aesgcmprovider.AesGcmCipher.engineInit(AesGcmCipher.java:119)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2980)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1288)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1223)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:72)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:37)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:22)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:250)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$0(ApplicationContext.java:127)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$0$ApplicationContext(Unknown Source:0)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.-$$Lambda$ApplicationContext$FUG4OX_0WYia1ROK536avz_A-eY.run(Unknown Source:2)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.AppStartup.execute(AppStartup.java:142)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:177)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
07-16 16:48:37.705 18539 18539 E AndroidRuntime: 	... 8 more
07-16 16:48:37.710  2547 18574 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-16 16:48:37.711  2547  3250 W ActivityTaskManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
07-16 16:48:37.715  2547 18574 W DropBoxManagerService: Dropping: data_app_crash (2554 > 0 bytes)
07-16 16:48:37.740  2547  2690 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
07-16 16:48:37.740  2547  2690 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
07-16 16:48:37.777 18539 18539 I Process : Sending signal. PID: 18539 SIG: 9
```

### Steps to reproduce
- Start Singal

**Actual result:** Singal does not start, I get the message that Signal stops immediately, with the option to show App Info, close the app, or send feedback.
**Expected result:** The Signal window appears on the screen

### Device info
**Device:** OnePlus 3
**Android version:** 10.0 (LineageOS)
**Signal version:** 5.17.0

**Comment by Fregf** [comment]
Rebooting my phone fixed this issue. Weird.

**Comment by greyson-signal** [comment]
Just some context: it appears we crashed because we were unable to open the system key store (this is a special OS thing that lets us store cryptographic keys in a safe spot). I'm guessing something was up with that system component and restarting fixed it. :shrug:
