### ISSUE TITLE
IllegalStateException crash when capturing a debug log on the setup screen

### ISSUE THREAD

**Issue by strugee** [signalapp/Signal-Android#11491]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Trying to capture a debug log by tapping repeatedly in the upper-right corner of the setup screen crashes Signal.

### Steps to reproduce

1. Install Signal
2. Open Signal
3. Tap repeatedly on the upper-right corner of the setup screen
4. Continue tapping when you see the "You are x steps away from submitting a debug log" toasts

**Actual result:** Signal crashes
**Expected result:** a debug log is captured

### Screenshots

N/A

### Device info

**Device:** Google Pixel 3a XL
**Android version:** LineageOS July 24, 2021, based on Android 11
**Signal version:** 5.18.3 beta

### Link to debug log

This is a manually-snipped `adb logcat` capture. It contains the exception stack trace and a few minutes before and after.
[signal-setup-crash-snipped.log](https://github.com/signalapp/Signal-Android/files/6881742/signal-setup-crash-snipped.log)

Here's the actual stack trace (putting this here mostly for search keywords):

```
07-26 16:39:16.391  3366 10100 E AndroidRuntime: FATAL EXCEPTION: signal-serial-0
07-26 16:39:16.391  3366 10100 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3366
07-26 16:39:16.391  3366 10100 E AndroidRuntime: java.lang.IllegalStateException: Tried to call getSelf() before local data was set!
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getSelf(LiveRecipientCache.java:158)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.recipients.Recipient.self(Recipient.java:322)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.logsubmit.LogSectionKeyPreferences.getContent(LogSectionKeyPreferences.java:32)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.getLinesForSection(SubmitDebugLogRepository.java:277)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.getPrefixLogLinesInternal(SubmitDebugLogRepository.java:247)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.lambda$getPrefixLogLines$0(SubmitDebugLogRepository.java:101)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.lambda$getPrefixLogLines$0$SubmitDebugLogRepository(Unknown Source:0)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at org.thoughtcrime.securesms.logsubmit.-$$Lambda$SubmitDebugLogRepository$paG8G49QHIH5SW00EvbfHfNzIxU.run(Unknown Source:4)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-26 16:39:16.391  3366 10100 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException: java.lang.IllegalStateException: Tried to call getSelf() before local data was set!
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getSelf(LiveRecipientCache.java:158)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.recipients.Recipient.self(Recipient.java:322)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.logsubmit.LogSectionKeyPreferences.getContent(LogSectionKeyPreferences.java:32)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.getLinesForSection(SubmitDebugLogRepository.java:277)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.getPrefixLogLinesInternal(SubmitDebugLogRepository.java:247)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.lambda$getPrefixLogLines$0(SubmitDebugLogRepository.java:101)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.logsubmit.SubmitDebugLogRepository.lambda$getPrefixLogLines$0$SubmitDebugLogRepository(Unknown Source:0)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at org.thoughtcrime.securesms.logsubmit.-$$Lambda$SubmitDebugLogRepository$paG8G49QHIH5SW00EvbfHfNzIxU.run(Unknown Source:4)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-26 16:39:16.391  3366 10100 E SignalUncaughtException:       at java.lang.Thread.run(Thread.java:923)
07-26 16:39:16.392  3366 10100 I JobManager: Successfully flushed.
```

**Comment by strugee** [comment]
I cloned Signal to a work profile (with Shelter) so I didn't have to backup and restore my app. Seems to be fixed, unless there's something different about the work profile environment.

**Comment by strugee** [comment]
I'm gonna assume this is fixed; if you want me to try on a main profile though let me know.
