### ISSUE TITLE
Save attachment - Content is insert in MediaColumns even saving isn't possible

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#11505]
- [ ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When checking the issue #10792, it became apparent that the file metadata is being insert in the MediaColumns even though the file is not saved.

Also related to #10792 is #11050 , #11400 

### Steps to reproduce
- try several times to save a video without having the folder "Movies"

### Device info

**Android version:** 7.1.1
**Signal version:** 5.19.2

### Link to debug log

Additional logs starts with "Test"

```
2021-07-31 16:28:36.884 14383-14674/org.thoughtcrime.securesms W/StorageUtil: Test getVideoUri file:///storage/emulated/0/Movies
2021-07-31 16:28:36.886 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test outputUri video/mp4 /external/video/media
2021-07-31 16:28:36.906 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test getExternalPathToFileForType /storage/emulated/0/Movies
2021-07-31 16:28:36.926 14383-14674/org.thoughtcrime.securesms D/SaveAttachmentTask: The content exists. Rename and check again. /external/video/media /storage/emulated/0/Movies/signal-2021-03-31-201510.mp4
2021-07-31 16:28:36.931 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test getExternalPathToFileForType /storage/emulated/0/Movies
2021-07-31 16:28:36.944 14383-14674/org.thoughtcrime.securesms D/SaveAttachmentTask: The content exists. Rename and check again. /external/video/media /storage/emulated/0/Movies/signal-2021-03-31-201510-1.mp4
2021-07-31 16:28:36.948 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test getExternalPathToFileForType /storage/emulated/0/Movies
2021-07-31 16:28:36.959 14383-14674/org.thoughtcrime.securesms D/SaveAttachmentTask: The content exists. Rename and check again. /external/video/media /storage/emulated/0/Movies/signal-2021-03-31-201510-2.mp4
2021-07-31 16:28:36.962 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test getExternalPathToFileForType /storage/emulated/0/Movies
2021-07-31 16:28:36.971 14383-14674/org.thoughtcrime.securesms D/SaveAttachmentTask: The content exists. Rename and check again. /external/video/media /storage/emulated/0/Movies/signal-2021-03-31-201510-3.mp4
2021-07-31 16:28:36.981 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test getExternalPathToFileForType /storage/emulated/0/Movies
2021-07-31 16:28:36.991 14383-14674/org.thoughtcrime.securesms D/SaveAttachmentTask: The content exists. Rename and check again. /external/video/media /storage/emulated/0/Movies/signal-2021-03-31-201510-4.mp4
2021-07-31 16:28:36.996 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test getExternalPathToFileForType /storage/emulated/0/Movies
2021-07-31 16:28:37.033 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: Test mediaUri signal-2021-03-31-201510.mp4 /external/video/media/10436
2021-07-31 16:28:37.063 14383-14674/org.thoughtcrime.securesms W/SaveAttachmentTask: null
    java.io.FileNotFoundException: No such file or directory
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1002)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:744)
        at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:127)
        at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:81)
        at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:38)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)


```

---------------------------

After creating the missing folder "Movies" the gallery shows this:

![signal-2021-07-31-172107_002](https://user-images.githubusercontent.com/49990901/127744627-e6ad46f3-48f7-4482-a80a-a0fe2922e34a.png) ![signal-2021-07-31-172107_001](https://user-images.githubusercontent.com/49990901/127744629-a798f652-55c8-4353-845c-45eba9068bb5.png)

------------------------------

The contentValue is insert here with returning the ouputUri/mediaUri

https://github.com/signalapp/Signal-Android/blob/c427dbad086a98b70ccf66f41354f6a2ec6420b0/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L231

Failing here with `java.io.FileNotFoundException: No such file or directory` when opening the outputUri/mediaUri

https://github.com/signalapp/Signal-Android/blob/c427dbad086a98b70ccf66f41354f6a2ec6420b0/app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java#L123

**Comment by Sgn-32** [comment]
@fumiakiy 
Have seen that checking and renaming the file name was a commit from you.
https://github.com/signalapp/Signal-Android/commit/2cca6a5afb7138aa1eee1d30aea811529dd0091d
