### ISSUE TITLE
No virtual method position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by sagarzala123** [signalapp/Signal-Android#11525]
After successful register app getting crashed. Below are logcat.   

```
 java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.read(Quote.java:105)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.readZero(Quote.java:111)
        at org.whispersystems.signalservice.internal.contacts.crypto.Quote.<init>(Quote.java:62)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.validateAndBuildRemoteAttestation(RemoteAttestationUtil.java:121)
        at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.getAndVerifyMultiRemoteAttestation(RemoteAttestationUtil.java:70)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:381)
        at org.thoughtcrime.securesms.contacts.sync.ContactDiscoveryV2.getDirectoryResult(ContactDiscoveryV2.java:69)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:233)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:104)
        at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:74)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by cody-signal** [comment]
This happens when building from source with a JDK other than JDK 8. Please use the forum for further development/building related questions.

https://community.signalusers.org/c/development/android-development/22
