### ISSUE TITLE
Beta5.22.3 Crash - in StorageSyncModels.localToRemoteContact

### ISSUE THREAD

**Issue by benys** [signalapp/Signal-Android#11572]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I run aplication - after few seconds it crashes

### Steps to reproduce
- run my instance
- wait

**Actual result:** 
Application crashes

**Expected result:** 
Application shoud run

### Device info
**Device:** Xaoimi Mi 11
**Android version:** 11
**Signal version:** 5.22.3

### Link to debug log
```
08-28 10:03:33.461  3230  3304 E BaseJob : Encountered a fatal exception. Crash imminent.
08-28 10:03:33.461  3230  3304 E BaseJob : java.lang.NullPointerException
08-28 10:03:33.461  3230  3304 E BaseJob : 	at java.util.Objects.requireNonNull(Objects.java:220)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.whispersystems.libsignal.util.guava.Preconditions.checkNotNull(Preconditions.java:189)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:34)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:47)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:94)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:33)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.lambda$getMatching$0(ContactRecordProcessor.java:79)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.lambda$getMatching$0$ContactRecordProcessor(Unknown Source:0)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.-$$Lambda$ContactRecordProcessor$IyB35V1drtcGDkwsTatLZiTmGOQ.apply(Unknown Source:6)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.whispersystems.libsignal.util.guava.Present.transform(Present.java:67)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.getMatching(ContactRecordProcessor.java:73)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.getMatching(ContactRecordProcessor.java:23)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:51)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:23)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:279)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:175)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
08-28 10:03:33.461  3230  3304 E BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
08-28 10:03:33.462  3230  3304 E JobRunner: [JOB::861e92ba-c0db-4d20-8425-7a2ae2765246][StorageSyncJob][1] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 4389 ms, Lifespan: 86400000 ms, Run Attempt: 1/3)
08-28 10:03:33.462  3230  3325 D ConversationListDataSou: [size(), UnarchivedConversationListDataSource] 1 ms
08-28 10:03:33.463  3230  3304 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
08-28 10:03:33.463  3230  3304 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3230
08-28 10:03:33.463  3230  3304 E AndroidRuntime: java.lang.NullPointerException
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:220)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.whispersystems.libsignal.util.guava.Preconditions.checkNotNull(Preconditions.java:189)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:34)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:47)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:94)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:33)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.lambda$getMatching$0(ContactRecordProcessor.java:79)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.lambda$getMatching$0$ContactRecordProcessor(Unknown Source:0)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.-$$Lambda$ContactRecordProcessor$IyB35V1drtcGDkwsTatLZiTmGOQ.apply(Unknown Source:6)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.whispersystems.libsignal.util.guava.Present.transform(Present.java:67)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.getMatching(ContactRecordProcessor.java:73)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.getMatching(ContactRecordProcessor.java:23)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:51)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:23)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:279)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:175)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
08-28 10:03:33.463  3230  3304 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: java.lang.NullPointerException
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at java.util.Objects.requireNonNull(Objects.java:220)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.whispersystems.libsignal.util.guava.Preconditions.checkNotNull(Preconditions.java:189)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:34)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:47)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteContact(StorageSyncModels.java:94)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:33)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.lambda$getMatching$0(ContactRecordProcessor.java:79)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.lambda$getMatching$0$ContactRecordProcessor(Unknown Source:0)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.-$$Lambda$ContactRecordProcessor$IyB35V1drtcGDkwsTatLZiTmGOQ.apply(Unknown Source:6)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.whispersystems.libsignal.util.guava.Present.transform(Present.java:67)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.getMatching(ContactRecordProcessor.java:73)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.getMatching(ContactRecordProcessor.java:23)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:51)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:23)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:279)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:175)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
08-28 10:03:33.465  3230  3304 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
08-28 10:03:33.470  3230  3304 I JobManager: Successfully flushed.
08-28 10:03:33.471  1743  3458 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-28 10:03:33.472  1743  4168 W ActivityTaskManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
```

**Comment by benys** [comment]
```
  private static @NonNull SignalContactRecord localToRemoteContact(@NonNull RecipientSettings recipient, byte[] rawStorageId) {
    if (recipient.getUuid() == null && recipient.getE164() == null) {
      throw new AssertionError("Must have either a UUID or a phone number!");
    }

    return new SignalContactRecord.Builder(rawStorageId, new SignalServiceAddress(recipient.getUuid(), recipient.getE164()))
```

I discovered that my recipient has NULL in getUuid(). Creating SignalServiceAddress causes this exception.

**Comment by markusd112** [comment]
I have the same problem since today (5.22.5) on a Samsung Galaxy A51 with android 11: directly after starting signal it crashes instantly, it doesn't work any longer
The days before sometimes a message is displayed "I/O error" when using signal... maybe there is relation to the crashes....
@edit2: after activating offline mode (airplane mode) signal doesn't crash any longer. When activating network it crashes again...
