### ISSUE TITLE
Crash in converstion list after quitting a group

### ISSUE THREAD

**Issue by AsamK** [signalapp/Signal-Android#11611]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When quitting a group, Signal updates the snippet type in the ThreadDatabase, but doesn't update the snippet body.
Then the conversation list tries to base64 decode the snippet body because the type is a GROUP_UPDATE.
The converstion list code tries to catch IOExceptions, but it doesn't catch the IllegalArgumentException.
```
java.lang.IllegalArgumentException: Base64-encoded string must have at least four characters, but length specified was 1
        at org.whispersystems.util.Base64.decode(Base64.java:1181)
        at org.whispersystems.util.Base64.decode(Base64.java:1289)
        at org.whispersystems.util.Base64.decode(Base64.java:1246)
        at org.thoughtcrime.securesms.util.Base64.decode(Base64.java:13)
        at org.thoughtcrime.securesms.database.model.MessageRecord.getGv2ChangeDescription(MessageRecord.java:242)
        at org.thoughtcrime.securesms.conversationlist.ConversationListItem.getThreadDisplayBody(ConversationListItem.java:439)
        at org.thoughtcrime.securesms.conversationlist.ConversationListItem.bind(ConversationListItem.java:183)
        at org.thoughtcrime.securesms.conversationlist.ConversationListItem.bind(ConversationListItem.java:148)
        at org.thoughtcrime.securesms.conversationlist.ConversationListAdapter.onBindViewHolder(ConversationListAdapter.java:136)
        at org.thoughtcrime.securesms.conversationlist.ConversationListAdapter.onBindViewHolder(ConversationListAdapter.java:114)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
```

-> Either the converstion list should also catch IllegalArgumentException or the Base64 decode method should always throw IOExceptions
-> When updating the thread snippet type the snippet body should probably also be updated to match the type

### Steps to reproduce
- Send a short message in a group (1 to 3 chars), e.g. `V`
- Check in the conversation list that the message preview text is shown
- Quit the group
- Go back to the conversation list
-> Signal crashes

**Actual result:** After leaving the group and scrolling to it in the conversation list, signal crashes
**Expected result:** shouldn't crash

### Device info
**Device:** OnePlus 8T
**Android version:** 11
**Signal version:** v5.23.6

### Link to debug log
https://debuglogs.org/6f6ae201b46a54244b9ca613ea3dbfffcdfa1cab3cd41c5df646eeb84592acb8

**Comment by AsamK** [comment]
Crash had more been fixed with
8df86962e9236d289d38d7f657c1b8d3b699ebc1
