### ISSUE TITLE
Unable to restore from a backup

### ISSUE THREAD

**Issue by modernNeo** [signalapp/Signal-Android#11678]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I have a signal backup I made on 2020 Sept 7 and I am trying to restore from it but I am having some problems doing so where it thinks the passphrase is wrong. All incidents I came across on this repo and github that seemed close to my situation indicate that its because the user used Titanium Backup but I did not.

### Steps to reproduce
 - Create a backup using whatever Signal version was the latest on 2020 Sept 7th
 - try to restore that backup with Signal version 5.24.14

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

When I enter the passphrase, it gets as far as telling me this
![Screenshot_20210808-010256](https://user-images.githubusercontent.com/14242088/136881827-327cbc91-cc28-4f8f-8dd4-781f66a0fb1f.png)

Before it decided to give up and instead says

![Screenshot_20210808-010301](https://user-images.githubusercontent.com/14242088/136881866-8b1c832b-9db3-47b3-a1b7-a9154fdb472f.png)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

To be able to import the messages

### Device info

**Device:** Google Pixel 1
**Android version:** 10
**Signal version:** 5.24.14

### Link to debug log

I used `adb` to get the logs with `logcat`

```
10-11 19:27:54.125   910  2517 W VibratorService: Failed to perform effect (2)
10-11 19:27:56.120 13920 14009 W PlayCommon: [1117] anjt.m(1): No account for auth token provided
10-11 19:27:56.124 13920 14009 I PlayCommon: [1117] anjt.k(167): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
10-11 19:27:56.206 13920 14009 I PlayCommon: [1117] anjt.k(199): Successfully uploaded logs.
10-11 19:27:56.694   684   684 E VibratorService: Setting amplitude  to: 1856
10-11 19:27:56.799  1869  1869 I GoogleInputMethodService: GoogleInputMethodService.onFinishInputView():2356 
10-11 19:27:56.803   626   626 I netd    : firewallSetUidRule(2, 10075, 2) <4.58ms>
10-11 19:27:56.804   910  1267 D ConnectivityService: Blocked status changed to true for 10075(20) on netId 100
10-11 19:27:56.805   910  1267 D ConnectivityService: Blocked status changed to true for 10075(21) on netId 100
10-11 19:27:58.935 14189 14264 I RestoreBackupFragment: Starting backup restore.
10-11 19:27:58.936   656  2558 I ACDB-LOADER: ACDB AFE returned = -19
10-11 19:27:58.936   656  2558 D hardware_info: hw_info_append_hw_type : device_name = speaker
10-11 19:27:58.936   656  2558 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
10-11 19:27:58.936   656  2558 D audio_route: Apply path: speaker
10-11 19:27:58.936   656  2558 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
10-11 19:27:58.936   656  2558 D audio_route: Apply path: low-latency-playback speaker
10-11 19:27:58.939  2036  2063 E ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
10-11 19:27:58.939  2036  2063 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
10-11 19:27:58.943 14189 14264 W KeyStore: KeyStore exception
10-11 19:27:58.943 14189 14264 W KeyStore: android.os.ServiceSpecificException:  (code 7)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.os.Parcel.createException(Parcel.java:2085)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:2039)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:1987)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:978)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:236)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:225)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:147)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:82)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:51)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.backup.BackupPassphrase.set(BackupPassphrase.java:47)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:261)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:253)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-11 19:27:58.943 14189 14264 W KeyStore: 	at java.lang.Thread.run(Thread.java:919)
10-11 19:27:58.945 14189 14264 W KeyStore: KeyStore exception
10-11 19:27:58.945 14189 14264 W KeyStore: android.os.ServiceSpecificException:  (code 7)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.os.Parcel.createException(Parcel.java:2085)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:2039)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:1987)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:978)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:236)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:225)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:165)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:147)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:82)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:51)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.backup.BackupPassphrase.set(BackupPassphrase.java:47)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:261)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:253)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-11 19:27:58.945 14189 14264 W KeyStore: 	at java.lang.Thread.run(Thread.java:919)
10-11 19:27:58.950 14189 14244 D OpenGLRenderer: endAllActiveAnimators on 0x74abf39300 (RippleDrawable) with handle 0x74c04bc4a0
10-11 19:27:58.955   910  2303 E InputDispatcher: Window handle Window{a9b0cb2 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity} has no registered input channel
10-11 19:27:58.962  1869  1869 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3410 
10-11 19:27:58.962  1869  1869 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1994 
10-11 19:27:58.963  1869  1869 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():31 Notify device unlocked.
10-11 19:27:58.964   502   502 W /vendor/bin/hw/android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
10-11 19:27:58.964   502   502 W /vendor/bin/hw/android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
10-11 19:27:58.966   656  2558 D audio_hw_primary: out_write: retry previous failed cal level set
10-11 19:27:58.973   910  2517 E InputDispatcher: Window handle Window{a9b0cb2 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity} has no registered input channel
10-11 19:27:59.271   910  2517 D WificondControl: Scan result ready event
10-11 19:28:00.190 14189 14264 I FullBackupImporter: Ignoring import for statement: CREATE TABLE sqlite_sequence(name,seq)
10-11 19:28:02.152   656   676 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
10-11 19:28:02.155   656   676 D hardware_info: hw_info_append_hw_type : device_name = speaker
10-11 19:28:02.155   656   676 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
10-11 19:28:02.942 14189 14201 I crime.securesm: Background concurrent copying GC freed 59677(27MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 11MB/23MB, paused 75us total 101.621ms
10-11 19:28:02.947 14189 14203 W System  : A resource failed to call close. 
10-11 19:28:04.738 14189 14201 I crime.securesm: Background concurrent copying GC freed 14422(20MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 12MB/24MB, paused 118us total 112.234ms
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: null
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: java.io.IOException: File ended early!
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:343)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:171)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:104)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:76)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:262)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:253)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at java.lang.Thread.run(Thread.java:919)
10-11 19:28:09.588   910  2517 W NotificationService: Toast already killed. pkg=org.thoughtcrime.securesms callback=android.app.ITransientNotification$Stub$Proxy@4da4e2b
10-11 19:28:12.156   667   667 I /vendor/bin/hw/android.hardware.health@2.0-service.marlin: SRAM data: 2812000
10-11 19:28:12.172  1474  1952 D PowerUI : can't show warning due to - plugged: true status unknown: false
```

**Comment by tbvdm** [comment]
From your logcat:

```
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: java.io.IOException: File ended early!
10-11 19:28:06.040 14189 14264 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:343)
```

This suggests that your backup file is too short. Did you copy the backup file to your phone? In that case, check if it has been copied correctly (in particular, compare file sizes).

**Comment by modernNeo** [comment]
actually before I close this issue, is there a way to verify that the daily backups my signal is making are valid backups? 

cause I can't think of anything that I myself did wrong to corrupt the backup I made last year, I feel like it has to either be a signal issue or the backup did not copy over correctly but I didn't do anything fancy with that to corrupt it, I just literally copied it with the Files app on my debian.

**Comment by kaimast** [comment]
I just tried to restore from a backup. I pick the file, but instead of asking me for the passphrase, Signal asks me for my phone number and then I end up on with empty account. 

I checked the file with the sigbak tool but it does not report any errors. What should I do now?  It's a file with 6 years of messages, so I'd hate to lose it.

**Comment by tbvdm** [comment]
> I just tried to restore from a backup. I pick the file, but instead of asking me for the passphrase, Signal asks me for my phone number and then I end up on with empty account. 
> 
> I checked the file with the sigbak tool but it does not report any errors. What should I do now?  It's a file with 6 years of messages, so I'd hate to lose it. 

@kaimast I received your comment by mail, but I can't see it on the GitHub issue page. Very odd. Anyway, I think you should report this in a new issue. Adding screenshots and a debug log would probably also be helpful.

**Comment by kaimast** [comment]
Oh I deleted it. It runs our Signal doesn't like when the file is opened from Dropbox. Copying to local storage and then restoring it fixed the problem.

I'll try to open a new bug once I have time...
