### ISSUE TITLE
Unable to Transfer from old Android device to new android device

### ISSUE THREAD

**Issue by graingert** [signalapp/Signal-Android#11799]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm attempted to transfer my account between two phones

### Steps to reproduce
- start the transfer from both devices

**Actual result:** - I get "error connecting" on the new device
**Expected result:** the account is transferred to the new phone

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 12 (Pixel 6 Pro) update November 5th 2021
**Signal version:** 5.27.5

### Link to debug log
https://debuglogs.org/0b7a86eb40983500bb4a4af75159ebf94e01b1201625c9b9075d8ebf38b756a6

**Comment by graingert** [comment]
```
[5.27.5] [186  ] 2021-11-30 17:56:33.504 GMT W WifiDirect: add local service failure_reason: 2
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: org.signal.devicetransfer.WifiDirectUnavailableException
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at org.signal.devicetransfer.WifiDirect.startDiscoveryService(WifiDirect.java:188)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at org.signal.devicetransfer.DeviceTransferServer.startWifiDirect(DeviceTransferServer.java:178)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at org.signal.devicetransfer.DeviceTransferServer.handleMessage(DeviceTransferServer.java:146)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at android.os.Looper.loopOnce(Looper.java:201)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at android.os.Looper.loop(Looper.java:288)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 	at android.os.HandlerThread.run(HandlerThread.java:67)
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT E DeviceTransferServer: 
[5.27.5] [184  ] 2021-11-30 17:56:33.505 GMT I DeviceTransferServer: Shutting down ServerThread
[5.27.5] [185  ] 2021-11-30 17:56:33.506 GMT I NetworkServerThread: Server shutting down...
[5.27.5] [185  ] 2021-11-30 17:56:33.506 GMT I NetworkServerThread: Server exiting
[5.27.5] [184  ] 2021-11-30 17:56:33.506 GMT I DeviceTransferServer: Shutting down WiFi Direct
[5.27.5] [184  ] 2021-11-30 17:56:33.506 GMT D WifiDirect: Shutting down
[5.27.5] [186  ] 2021-11-30 17:56:33.517 GMT W WifiDirect: discover peers failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:33.532 GMT W WifiDirect: clear service requests failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:34.611 GMT W WifiDirect: clear service requests failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:35.636 GMT W WifiDirect: clear service requests failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:36.661 GMT W WifiDirect: stop peer discovery failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:37.677 GMT W WifiDirect: stop peer discovery failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:38.693 GMT W WifiDirect: stop peer discovery failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:39.718 GMT W WifiDirect: clear local services failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:40.739 GMT W WifiDirect: clear local services failure_reason: 2
[5.27.5] [186  ] 2021-11-30 17:56:41.763 GMT W WifiDirect: clear local services failure_reason: 2
[5.27.5] [184  ] 2021-11-30 17:56:42.764 GMT I DeviceTransferServer: Shutting down command and control
[5.27.5] [184  ] 2021-11-30 17:56:42.765 GMT I DeviceToDeviceTransferS: Shutdown
[5.27.5] [184  ] 2021-11-30 17:56:42.765 GMT D DeviceTransferServer: transferStatus: FAILED
[5.27.5] [main ] 2021-11-30 17:56:42.771 GMT I DeviceTransferSetupView: Handling transferStatus: FAILED
[5.27.5] [main ] 2021-11-30 17:56:42.771 GMT D DeviceToDeviceTransferS: Intentionally no notification text for: FAILED
[5.27.5] [main ] 2021-11-30 17:56:42.772 GMT V DeviceToDeviceTransferS: onDestroy
[5.27.5] [main ] 2021-11-30 17:56:42.773 GMT I DeviceTransferSetupFrag: Handling step: ERROR
[5.27.5] [main ] 2021-11-30 17:56:42.829 GMT V DeviceToDeviceTransferS: onCreate
[5.27.5] [main ] 2021-11-30 17:56:42.831 GMT D DeviceToDeviceTransferS: Action: stop
[5.27.5] [main ] 2021-11-30 17:56:42.831 GMT I DeviceToDeviceTransferS: Shutdown
[5.27.5] [main ] 2021-11-30 17:56:42.840 GMT V DeviceToDeviceTransferS: onDestroy
[5.27.5] [main ] 2021-11-30 17:56:44.585 GMT D DeviceTransferSetupView: Check for permissions
[5.27.5] [main ] 2021-11-30 17:56:44.599 GMT I DeviceTransferSetupFrag: Handling step: PERMISSIONS_CHECK
[5.27.5] [main ] 2021-11-30 17:56:44.600 GMT D DeviceTransferSetupView: Permissions granted
[5.27.5] [main ] 2021-11-30 17:56:44.606 GMT I DeviceTransferSetupFrag: Handling step: LOCATION_CHECK
[5.27.5] [main ] 2021-11-30 17:56:44.607 GMT D DeviceTransferSetupView: Location enabled
[5.27.5] [main ] 2021-11-30 17:56:44.608 GMT I DeviceTransferSetupFrag: Handling step: WIFI_CHECK
[5.27.5] [main ] 2021-11-30 17:56:44.609 GMT D DeviceTransferSetupView: Wifi enabled
[5.27.5] [main ] 2021-11-30 17:56:44.609 GMT I DeviceTransferSetupFrag: Handling step: WIFI_DIRECT_CHECK
[5.27.5] [main ] 2021-11-30 17:56:44.610 GMT D DeviceTransferSetupView: Wifi direct available
```

**Comment by cody-signal** [comment]
Hey there, Error 2 indicates that the wifi direct system is busy and unavailable for use by us. Can you make sure you have no other WiFi DIrect/P2P connections setup while attempting to transfer? You can also go into the system WiFi direct settings (under Wifi->Advanced usually) and see if any devices are connected there. If they are it's best to disable/disconnect/forget them.

**Comment by graingert** [comment]
@cody-signal 
This is the WiFi direct settings pane:
![Screenshot_20211203-085551](https://user-images.githubusercontent.com/413772/144574317-20067fd0-ad44-41cc-b295-4c70cde67c4d.png)

**Comment by cody-signal** [comment]
@graingert Can you remove that device and try again? Should be able to long press and remove/forget.

**Comment by graingert** [comment]
> @graingert Can you remove that device and try again? Should be able to long press and remove/forget.

There's no device there @cody-signal

**Comment by cody-signal** [comment]
Oh my bad, the UX/UI varies from platform to platform, and didn't realize that was the name of your device.

One thing Android 12 added was some permissions around discovery. Can you check in the System settings for the app and see if anything like Nearby Devices is there and disabled, and manually enable it.

**Comment by graingert** [comment]
![Screenshot_20211217-013709](https://user-images.githubusercontent.com/413772/146474375-3e7f2219-d43b-48a9-aac9-ea56f1522d7e.png)
These are the permissions

**Comment by graingert** [comment]
It seems 5.28.4 fixes it for me
