### ISSUE TITLE
NetworkOnMainThreadException when pressing Add funds button in payments

### ISSUE THREAD

**Issue by ndgunebo** [signalapp/Signal-Android#11813]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Crash when pressing Add funds button in payments due to network on main thread

### Steps to reproduce
- Open the Add funds button. This crash doesn't happen everytime.

**Actual result:** Add funds opens and I can see my public address
**Expected result:** The app crashes

### Device info

**Device:** Google Pixel 3
**Android version:** 12
**Signal version:** 5.27.10

### Link to debug log

```
12-04 13:38:14.080 26849 26849 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-04 13:38:14.082 26849 26849 E AndroidRuntime: FATAL EXCEPTION: main
12-04 13:38:14.082 26849 26849 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 26849
12-04 13:38:14.082 26849 26849 E AndroidRuntime: android.os.NetworkOnMainThreadException
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1668)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:802)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.conscrypt.ConscryptFileDescriptorSocket.shutdownAndFreeSslNative(ConscryptFileDescriptorSocket.java:1018)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.conscrypt.ConscryptFileDescriptorSocket.close(ConscryptFileDescriptorSocket.java:1013)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.Util.closeQuietly(Util.java:157)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.streamFailed(StreamAllocation.java:465)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:145)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.net.DeviceTransferBlockingInterceptor.intercept(DeviceTransferBlockingInterceptor.java:38)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.net.DeprecatedClientPreventionInterceptor.intercept(DeprecatedClientPreventionInterceptor.java:36)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.net.RemoteDeprecationDetectorInterceptor.intercept(RemoteDeprecationDetectorInterceptor.java:22)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.net.UserAgentInterceptor.intercept(UserAgentInterceptor.java:20)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at okhttp3.RealCall.execute(RealCall.java:93)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1746)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1658)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1646)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1635)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1571)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1553)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getAuthCredentials(PushServiceSocket.java:980)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPaymentsAuthorization(PushServiceSocket.java:998)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getPaymentsAuthorization(SignalServiceAccountManager.java:842)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.MobileCoinMainNetConfig.getAuth(MobileCoinMainNetConfig.java:57)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.Wallet.reauthorizeClient(Wallet.java:392)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.Wallet.<init>(Wallet.java:73)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.Payments.getWallet(Payments.java:37)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyRepository.getWalletAddress(PaymentsAddMoneyRepository.java:21)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyViewModel.<init>(PaymentsAddMoneyViewModel.java:25)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyViewModel$Factory.create(PaymentsAddMoneyViewModel.java:62)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyFragment.onViewCreated(PaymentsAddMoneyFragment.java:31)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7840)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-04 13:38:14.082 26849 26849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: android.os.NetworkOnMainThreadException
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1668)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:802)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.conscrypt.ConscryptFileDescriptorSocket.shutdownAndFreeSslNative(ConscryptFileDescriptorSocket.java:1018)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.conscrypt.ConscryptFileDescriptorSocket.close(ConscryptFileDescriptorSocket.java:1013)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.Util.closeQuietly(Util.java:157)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.connection.StreamAllocation.streamFailed(StreamAllocation.java:465)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:145)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.net.DeviceTransferBlockingInterceptor.intercept(DeviceTransferBlockingInterceptor.java:38)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.net.DeprecatedClientPreventionInterceptor.intercept(DeprecatedClientPreventionInterceptor.java:36)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.net.RemoteDeprecationDetectorInterceptor.intercept(RemoteDeprecationDetectorInterceptor.java:22)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.net.UserAgentInterceptor.intercept(UserAgentInterceptor.java:20)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at okhttp3.RealCall.execute(RealCall.java:93)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1746)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1658)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1646)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1635)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1571)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1553)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getAuthCredentials(PushServiceSocket.java:980)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPaymentsAuthorization(PushServiceSocket.java:998)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getPaymentsAuthorization(SignalServiceAccountManager.java:842)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.MobileCoinMainNetConfig.getAuth(MobileCoinMainNetConfig.java:57)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.Wallet.reauthorizeClient(Wallet.java:392)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.Wallet.<init>(Wallet.java:73)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.Payments.getWallet(Payments.java:37)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyRepository.getWalletAddress(PaymentsAddMoneyRepository.java:21)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyViewModel.<init>(PaymentsAddMoneyViewModel.java:25)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyViewModel$Factory.create(PaymentsAddMoneyViewModel.java:62)
12-04 13:38:14.083 26849 26849 E SignalUncaughtException: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at org.thoughtcrime.securesms.payments.preferences.addmoney.PaymentsAddMoneyFragment.onViewCreated(PaymentsAddMoneyFragment.java:31)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at android.os.Handler.handleCallback(Handler.java:938)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at android.os.Looper.loopOnce(Looper.java:201)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at android.os.Looper.loop(Looper.java:288)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:7840)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-04 13:38:14.084 26849 26849 E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
12-04 13:38:14.084 26849 26849 I JobManager: Successfully flushed.
12-04 13:38:14.085 26849 26849 E AndroidRuntime: Error reporting crash
12-04 13:38:14.085 26849 26849 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:571)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5294)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.SignalUncaughtExceptionHandler.uncaughtException(SignalUncaughtExceptionHandler.java:31)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
12-04 13:38:14.085 26849 26849 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
12-04 13:38:14.085 26849 26849 I Process : Sending signal. PID: 26849 SIG: 9
```

**Comment by ndgunebo** [comment]
If I exit the app or force close the app and then go into settings -> payments -> add funds, the screen freezes when pressing the Add funds button before it shows the QR code and address, so it looks like it is doing network calls on main thread.
