### ISSUE TITLE
App crashes after attempting registration lock too many times

### ISSUE THREAD

**Issue by ndgunebo** [signalapp/Signal-Android#11834]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes after attempting registration lock too many times

### Steps to reproduce
- Register a number w registration lock enabled
- Run out of attempts
**Actual result:** App crashes after the last attempt fails
**Expected result:** No crash

### Device info

**Signal version:** 5.28.3

### Link to debug log

```
I KbsRepository: restoreMasterKey()
I KbsRepository: Preparing to restore from fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe
D InputMethodManager: showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{9b61e07 VFED..CL. .F....ID 251,689-829,813 #7f0a05e5 app:id/kbs_lock_pin_input aid=1073741831} flags=0 reason=SHOW_SOFT_INPUT
D InsetsController: show(ime(), fromIme=true)
I KbsRepository: Restoring pin from KBS
I KeyBackupService: Restore TOKEN_MISMATCH
I KeyBackupService: Restore TOKEN_MISMATCH
I KeyBackupService: Token MISMATCH 2 1
W KbsRepository: Failed to restore key
W KbsRepository: org.whispersystems.signalservice.internal.contacts.crypto.UnauthenticatedResponseException: Token mismatch, expended all automatic retries
W KbsRepository: 	at org.whispersystems.signalservice.api.KeyBackupService$Session.restorePin(KeyBackupService.java:153)
W KbsRepository: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKeyFromEnclave(KbsRepository.java:124)
W KbsRepository: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKey(KbsRepository.java:108)
W KbsRepository: 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$verifyAccountWithPin$1.call(VerifyAccountRepository.kt:87)
W KbsRepository: 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$verifyAccountWithPin$1.call(VerifyAccountRepository.kt:29)
W KbsRepository: 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
W KbsRepository: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
W KbsRepository: 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
W KbsRepository: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
W KbsRepository: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
W KbsRepository: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W KbsRepository: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W KbsRepository: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W KbsRepository: 	at java.lang.Thread.run(Thread.java:920)
E SignalUncaughtException: java.io.IOException: org.whispersystems.signalservice.internal.contacts.crypto.UnauthenticatedResponseException: Token mismatch, expended all automatic retries
E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.BaseRegistrationLockFragment.handlePinEntry(BaseRegistrationLockFragment.java:178)
E SignalUncaughtException: 	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
E SignalUncaughtException: 	at [[ ↓↓ Original trace ↓↓ ]].(:0)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKeyFromEnclave(KbsRepository.java:135)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKey(KbsRepository.java:108)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$verifyAccountWithPin$1.call(VerifyAccountRepository.kt:87)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$verifyAccountWithPin$1.call(VerifyAccountRepository.kt:29)
E SignalUncaughtException: 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
E SignalUncaughtException: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
E SignalUncaughtException: 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
E SignalUncaughtException: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
E SignalUncaughtException: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:920)
E SignalUncaughtException: Caused by: org.whispersystems.signalservice.internal.contacts.crypto.UnauthenticatedResponseException: Token mismatch, expended all automatic retries
E SignalUncaughtException: 	at org.whispersystems.signalservice.api.KeyBackupService$Session.restorePin(KeyBackupService.java:153)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKeyFromEnclave(KbsRepository.java:124)
E SignalUncaughtException: 	... 12 more
I JobManager: Successfully flushed.
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 13682
E AndroidRuntime: java.io.IOException: org.whispersystems.signalservice.internal.contacts.crypto.UnauthenticatedResponseException: Token mismatch, expended all automatic retries
E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.BaseRegistrationLockFragment.handlePinEntry(BaseRegistrationLockFragment.java:178)
E AndroidRuntime: 	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
E AndroidRuntime: 	at [[ ↓↓ Original trace ↓↓ ]].(:0)
E AndroidRuntime: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKeyFromEnclave(KbsRepository.java:135)
E AndroidRuntime: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKey(KbsRepository.java:108)
E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$verifyAccountWithPin$1.call(VerifyAccountRepository.kt:87)
E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.VerifyAccountRepository$verifyAccountWithPin$1.call(VerifyAccountRepository.kt:29)
E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
E AndroidRuntime: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
E AndroidRuntime: 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
E AndroidRuntime: Caused by: org.whispersystems.signalservice.internal.contacts.crypto.UnauthenticatedResponseException: Token mismatch, expended all automatic retries
E AndroidRuntime: 	at org.whispersystems.signalservice.api.KeyBackupService$Session.restorePin(KeyBackupService.java:153)
E AndroidRuntime: 	at org.thoughtcrime.securesms.pin.KbsRepository.restoreMasterKeyFromEnclave(KbsRepository.java:124)
E AndroidRuntime: 	... 12 more
I Process : Sending signal. PID: 13682 SIG: 9

```

**Comment by cody-signal** [comment]
Addressed in upcoming 5.29
