### ISSUE TITLE
Signal app seems to crash on start after update

### ISSUE THREAD

**Issue by claell** [signalapp/Signal-Android#11874]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I used Signal before on an Android device. Now I wanted to transfer data to the device I am currently using. For that, I updated the Signal app on the old device (that I didn't use for about a year). I checked the app before the update and it worked (just some message about a new version and need for re-verification or something like that). After the update, a white screen is displayed when launching the app. The Android notification icons are still displayed. Sometimes, the screen is also black. Also, sometimes (for example when pressing "launch" on the Google Play Store App page recently), the whole screen turns black, so no more Android icons on the top.

### Steps to reproduce
- Have an old version of Signal running
- Update it
- Try to launch it

**Actual result:** See description
**Expected result:** App should launch normally

### Screenshots
Can be added if considered helpful

### Device info

**Device:** Motorola Moto G5
**Android version:** 8.1.0
**Signal version:** most current in Google Play Store

### Link to debug log
Cannot be created, as I cannot access the app. I am willing to provide ADB logs, if this issue can be solved.

Overall, this looks similar to #9627. Might also be a duplicate of #10035 or #9332.

Also, I found a Reddit post describing a similar problem: https://www.reddit.com/r/signal/comments/n6utyn/for_a_few_days_now_signal_only_starts_a_blank/

**Comment by claell** [comment]
Things I have already tried: Reboot the phone, force stop the app, clear cache.

**Comment by claell** [comment]
Also, do you know whether it is save to install an older version of the app again without losing data? Possibly older versions will set the app in a working state again.

**Comment by greyson-signal** [comment]
Hi there, ADB logs would be very helpful in diagnosing the issue. Also, installing an old version of the app *will* wipe all app data -- this is an Android thing, not a Signal thing.

**Comment by claell** [comment]
Alright, thanks. Then I won't try installing an older Signal version.

I'll try to get you the logs, soon.

**Comment by claell** [comment]
@greyson-signal There you go (`adb logcat`, should be the relevant part when launching Signal):

```
01-03 17:33:56.266  1788  9279 D WificondControl: Scan result ready event
01-03 17:33:56.403   770   770 D MotoSensors: ALS 27
01-03 17:33:58.544   770   770 D MotoSensors: ALS 22
01-03 17:33:59.655  1788  9279 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[282,1197][540,1558]} from uid 10123
01-03 17:33:59.656   795   856 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
01-03 17:33:59.677  1788  9279 I ActivityManager: Start proc 19847:org.thoughtcrime.securesms/u0a201 for activity org.thoughtcrime.securesms/.RoutingActivity
01-03 17:33:59.774 19847 19847 I MultiDex: VM with version 2.1.0 has multidex support
01-03 17:33:59.775 19847 19847 I MultiDex: Installing application
01-03 17:33:59.775 19847 19847 I MultiDex: VM has multidex support, MultiDex support library is disabled.
01-03 17:33:59.797 19847 19847 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
01-03 17:33:59.815 19847 19847 I FirebaseInitProvider: FirebaseApp initialization successful
01-03 17:33:59.831 19847 19847 I BlobContentProvider: onCreate()
01-03 17:33:59.831 19847 19847 I PartProvider: onCreate()
01-03 17:33:59.867 19847 19847 I ApplicationContext: Installed AesGcmProvider: 1
01-03 17:33:59.970   770   770 D MotoSensors: ALS 33
01-03 17:34:00.063 19847 19847 V NativeCrypto: Registering org/conscrypt/NativeCrypto's 284 native methods...
01-03 17:34:00.074 19847 19847 I ApplicationContext: Installed Conscrypt provider: 2
01-03 17:34:00.104   809   809 I SFPerfTracer:      triggers: (rate: 27:2341) (compose: 0:0) (post: 0:6) (render: 0:8) (20:66379 frames) (21:70762)
01-03 17:34:00.104   809   809 D SFPerfTracer:        layers: (4:8) (StatusBar#0 (0xb1c62000): 3:2273) (com.android.systemui.ImageWallpaper#0 (0xb1c60000): 0:64) (DimLayerController/Stack=0#0 (0xb1bbd000): 0:1102)* (Sprite#0 (0xb1bd7000): 0:10)* (animation background stackId=1#0 (0xb1bc9000): 0:22)* (com.android.systemui/com.android.systemui.recents.RecentsActivity#0 (0xb1bb0000): 0:81)- (com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher#0 (0xb1bc6000): 1:73) (Splash Screen org.thoughtcrime.securesms#0 (0xb1bb0000): 21:23)
01-03 17:34:00.117   809   898 I SFPerfTracer:      triggers: (rate: 0:0) (1116 sw vsyncs) (0 skipped) (1:66108 vsyncs) (3:74272)
01-03 17:34:00.236 19847 19847 I ApplicationContext: onCreate()
01-03 17:34:00.257 19847 19847 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.257 19847 19869 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.271 19847 19847 I KeyValueDatabase: onCreate()
01-03 17:34:00.274 19847 19847 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.281 19847 19847 I SignalDatabase: Upgrading database: 35, 123
01-03 17:34:00.311 19847 19869 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.367 19847 19870 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.372 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.390 19847 19870 I chatty  : uid=10201(org.thoughtcrime.securesms) signal-unbounde identical 4 lines
01-03 17:34:00.391 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.392 19847 19847 E SQLiteLog: (11) database corruption at line 71281 of [10e20c0b43]
01-03 17:34:00.392 19847 19847 E SQLiteLog: (11) database corruption at line 71431 of [10e20c0b43]
01-03 17:34:00.392 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.394 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.395 19847 19847 D AndroidRuntime: Shutting down VM
01-03 17:34:00.395 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.396 19847 19847 E AndroidRuntime: FATAL EXCEPTION: main
01-03 17:34:00.396 19847 19847 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 19847
01-03 17:34:00.396 19847 19847 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.IllegalStateException: getDatabase called recursively
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6626)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
01-03 17:34:00.396 19847 19847 E AndroidRuntime: Caused by: java.lang.IllegalStateException: getDatabase called recursively
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:313)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:297)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.KeyValueDatabase.getDataSet(KeyValueDatabase.java:105)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.KeyValueStore.initializeIfNecessary(KeyValueStore.java:153)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.KeyValueStore.containsKey(KeyValueStore.java:88)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.AccountValues.<init>(AccountValues.kt:36)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.SignalStore.<init>(SignalStore.java:61)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.SignalStore.getInstance(SignalStore.java:51)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.SignalStore.account(SignalStore.java:150)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:796)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:149)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:395)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:297)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:167)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:254)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(Unknown Source:2)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.KeyValueDatabase.onCreate(KeyValueDatabase.java:75)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:390)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:297)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.database.KeyValueDatabase.getDataSet(KeyValueDatabase.java:105)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.KeyValueStore.initializeIfNecessary(KeyValueStore.java:153)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.KeyValueStore.containsKey(KeyValueStore.java:88)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.AccountValues.<init>(AccountValues.kt:36)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.SignalStore.<init>(SignalStore.java:61)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.SignalStore.getInstance(SignalStore.java:51)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.keyvalue.SignalStore.settings(SignalStore.java:194)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.notifications.NotificationChannels.onCreate(NotificationChannels.java:601)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.notifications.NotificationChannels.create(NotificationChannels.java:93)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$3(ApplicationContext.java:150)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.$r8$lambda$hmtE-gWKgtJqnegkmcKGyW9S4lE(Unknown Source:0)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext$$ExternalSyntheticLambda28.run(Unknown Source:2)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.util.AppStartup.execute(AppStartup.java:144)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:193)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1141)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5854)
01-03 17:34:00.396 19847 19847 E AndroidRuntime:        ... 8 more
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:
01-03 17:34:00.396 19847 19847 E SignalUncaughtException: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.IllegalStateException: getDatabase called recursively
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5857)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.app.ActivityThread.-wrap1(Unknown Source:0)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.os.Handler.dispatchMessage(Handler.java:106)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.os.Looper.loop(Looper.java:164)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.app.ActivityThread.main(ActivityThread.java:6626)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at java.lang.reflect.Method.invoke(Native Method)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException: Caused by: java.lang.IllegalStateException: getDatabase called recursively
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:313)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:297)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.KeyValueDatabase.getDataSet(KeyValueDatabase.java:105)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.KeyValueStore.initializeIfNecessary(KeyValueStore.java:153)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.KeyValueStore.containsKey(KeyValueStore.java:88)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.AccountValues.<init>(AccountValues.kt:36)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.SignalStore.<init>(SignalStore.java:61)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.SignalStore.getInstance(SignalStore.java:51)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.SignalStore.account(SignalStore.java:150)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:796)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:149)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:395)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:297)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:167)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:254)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(Unknown Source:2)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.KeyValueDatabase.onCreate(KeyValueDatabase.java:75)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:390)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:297)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.KeyValueDatabase.getDataSet(KeyValueDatabase.java:105)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.KeyValueStore.initializeIfNecessary(KeyValueStore.java:153)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.KeyValueStore.containsKey(KeyValueStore.java:88)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.AccountValues.<init>(AccountValues.kt:36)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.SignalStore.<init>(SignalStore.java:61)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.SignalStore.getInstance(SignalStore.java:51)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.keyvalue.SignalStore.settings(SignalStore.java:194)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.notifications.NotificationChannels.onCreate(NotificationChannels.java:601)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.notifications.NotificationChannels.create(NotificationChannels.java:93)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$3(ApplicationContext.java:150)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.ApplicationContext.$r8$lambda$hmtE-gWKgtJqnegkmcKGyW9S4lE(Unknown Source:0)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.ApplicationContext$$ExternalSyntheticLambda28.run(Unknown Source:2)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.util.AppStartup.execute(AppStartup.java:144)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:193)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1141)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5854)
01-03 17:34:00.396 19847 19847 E SignalUncaughtException:       ... 8 more
01-03 17:34:00.396 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.398 19847 19847 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.398 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.400 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.400 19847 19847 I KeyValueDatabase: onCreate()
01-03 17:34:00.401 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.403 19847 19847 I SQLiteConnection: Database keying operation returned:0
01-03 17:34:00.403 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.408 19847 19870 I chatty  : uid=10201(org.thoughtcrime.securesms) signal-unbounde identical 3 lines
01-03 17:34:00.409 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.410 19847 19847 I SignalDatabase: Upgrading database: 35, 123
01-03 17:34:00.411 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.424 19847 19870 I chatty  : uid=10201(org.thoughtcrime.securesms) signal-unbounde identical 8 lines
01-03 17:34:00.425 19847 19870 I SQLiteCursor: Set CursorWindow allocation size to 8389120
01-03 17:34:00.440 19847 19870 D LogDatabase: [trim] keepers-size: 36  binary-search: 41  delete: 14  total: 91
01-03 17:34:00.507 19847 19847 E SQLiteLog: (11) database corruption at line 71281 of [10e20c0b43]
01-03 17:34:00.507 19847 19847 E SQLiteLog: (11) database corruption at line 71431 of [10e20c0b43]
01-03 17:34:01.167   770   770 D MotoSensors: ALS 296
01-03 17:34:02.485   770   770 D MotoSensors: ALS 48
01-03 17:34:03.810  2639  2639 D HeadsetPhoneState: Enter onSignalStrengthsChanged
01-03 17:34:03.810  2639  2639 D HeadsetPhoneState: Exit onSignalStrengthsChanged
01-03 17:34:03.827   809   898 I SFPerfTracer:      triggers: (rate: 0:0) (1116 sw vsyncs) (0 skipped) (22:66219 vsyncs) (24:74387)
01-03 17:34:04.535   770   770 D MotoSensors: ALS 40
01-03 17:34:05.449   770  1941 I MotoSensors: Sensorhub hal setDelay: 1 - 20
01-03 17:34:05.449   770  1941 I MotoSensors: Sensorhub hal setdelay: 1 - 20
01-03 17:34:05.449   770  1941 I MotoSensors: Sensorhub hal enable: 1 - 1
01-03 17:34:05.449   770  1941 I MotoSensors: HubSensors::updateAccelRate 20
01-03 17:34:07.094  1788  1963 I PowerManagerService: Going to sleep due to power button (uid 1000)...
```

Looks like some database problem?

**Comment by greyson-signal** [comment]
Ah, I think I see what's happening. I put a potential fix in 5.28.9 (will go to beta later today). Let me know if that works for you, thanks!

**Comment by claell** [comment]
Nice, thank you very much!

Can you give some more details? Is some data corrupted on my device or another issue?

Also, is it safe for me to test the beta?

**Comment by claell** [comment]
Also, I don't see any commit here, is the Beta developed on a non-public branch?

**Comment by UserX404** [comment]
@claell 
You will see the commits when 5.28.9 is ready and is pushed to the public repo.
You likely get more information in the [community forum](https://community.signalusers.org) (pls use forums search function) and/or the actual [beta-feedback-thread](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-28-release/39659).

**Comment by claell** [comment]
Alright! So I guess I'll just join the Beta on Google Play and wait for it to update. Fingers crossed that it won't make things worse...

**Comment by claell** [comment]
Probably need to use Firebase as written on the forum (https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-28-release/39659/319)

**Comment by claell** [comment]
@greyson-signal I can confirm that the Beta fixed my problem. Many thanks for helping me out so fast!

**Comment by r00t-** [comment]
i'm still seeing a similar issue in the current release (5.34.5).

i upgraded from a very old version (that i had not used for a long time, and that had become unsupported),
which most likely was 5721_4.50.6.
after the upgrade, signal always crashed on startup.
clearing application data and trying to restore a backup made before the upgrade leads to the same crash.
i cannot work around by going back to the old version, because it won't import the backup before registering with the server, which does not work anymore. thus my backup is unreadable now. (lest i extract the code to decrypt it from the app.)

[telegram_crash.txt](https://github.com/signalapp/Signal-Android/files/8412052/telegram_crash.txt)
