### ISSUE TITLE
Crash when clicking on a message with text and sticker

### ISSUE THREAD

**Issue by AsamK** [signalapp/Signal-Android#11883]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Third party clients can send messages to Signal-Android, that contain a message text and a sticker.
That message is displayed with only the text (no sticker image) and without a bubble background, which is probably fine as this isn't supported by official Signal clients.

But when clicking on the message, Signal-Android crashes, which shouldn't happen:
```
2022-01-03 11:38:15.332 14717-14717/? E/SignalUncaughtException: java.lang.IllegalStateException: Found a situation where we have something other than a thumbnail or a document.
        at org.thoughtcrime.securesms.conversation.ConversationItem.getMultiselectPartForLatestTouch(ConversationItem.java:567)
        at org.thoughtcrime.securesms.conversation.ConversationAdapter.lambda$onCreateViewHolder$0(ConversationAdapter.java:208)
        at org.thoughtcrime.securesms.conversation.ConversationAdapter.$r8$lambda$q34l8SqOcgcVZywQXV36PHUH4HY(Unknown Source:0)
        at org.thoughtcrime.securesms.conversation.ConversationAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at org.thoughtcrime.securesms.conversation.ConversationItem$ClickListener.onClick(ConversationItem.java:1988)
        at android.view.View.performClick(View.java:7520)
        at org.thoughtcrime.securesms.conversation.ConversationItem$PassthroughClickListener.onClick(ConversationItem.java:1975)
        at android.view.View.performClick(View.java:7520)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Steps to reproduce
- adapt Signal-Android code to send a message with text and sticker
- click on the message

### Screenshots
![image](https://user-images.githubusercontent.com/2340865/147922593-6afb32a2-37d8-4a83-be21-becb1dd2de34.png)

**Comment by greyson-signal** [comment]
Given that we don't support text with stickers, I don't anticipate spending time on fixing this, apologies!
