### ISSUE TITLE
Updating app from a pre-2018 version to a 2022 version causes Signal to crash upon first entering main Activity

### ISSUE THREAD

**Issue by JamesCropcho** [signalapp/Signal-Android#11906]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes upon first entering main Activity (upon "starting the app"). Most of the time it happens immediately or within 1s. 10% of the time there is a "loading screen" displaying something like (*) "Signal is updating…" which can be displayed for up to tens of minutes, but which does eventually result in same crash behavior.

The app does not start.

Possibly related to bug reports https://github.com/signalapp/Signal-Android/issues/11160, https://github.com/signalapp/Signal-Android/issues/10868.

_\* I cannot capture screenshots due to app permissions_

#### Important note: only seeking to create backup

Though it is perhaps outside the scope of this report I nonetheless want to mention that my sole personal goal for my Signal installation on this device is to create a backup prior to factory reset. Although the behavior I am describing is indeed a bug and I hope this report is broadly helpful to many, I am not personally interested in using the continued use of Signal on this device, only the preservation of my correspondences.

Regardless, I am very interested in helping to diagnose this errant behavior, so request freely from me any additional details or tests to perform and expect rapid turn-around from me!

### Steps to reproduce
- Update the app directly from a version circa August 6, 2017, to a version circa January 16, 2021
- Tap the app icon to enter main Activity
- Sometimes see app-originated fullscreen loading display with text like "Signal is updating…"
- Confirm seeing OS-originated modal dialog like "Signal has crashed. What would you like to do?"
- Tap option like "Try to re-open"
- Confirm seeing OS-originated modal dialog like "Signal keeps crashing"

### Device info
**Device:** LG Nexus 5X
**Android version:** 8.1.0, patchlevel June 5, 2018
**Signal version:** 5.28.10; 5.29.2 beta
**Funding status:** Signal Sustainer 1
**Rooted status:** non-rooted
**Storage usage by app:** 200MB (approx.) (as reported by Settings)

### Logs

```ada
{cmp=org.thoughtcrime.securesms/.migrations.ApplicationMigrationActivity (has extras)} from uid 10096
--------- beginning of crash
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: FATAL EXCEPTION: MessageRetrievalService
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5551
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: java.lang.NullPointerException
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:203)
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.connect(WebSocketConnection.java:115)
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalWebSocket.getWebSocket(SignalWebSocket.java:147)
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalWebSocket.connect(SignalWebSocket.java:78)
01-17 18:54:22.067 10096  5551  5607 E AndroidRuntime: 	at org.thoughtcrime.securesms.messages.IncomingMessageObserver$MessageRetrievalThread.run(IncomingMessageObserver.java:216)
```

```ada
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: FATAL EXCEPTION: signal-bounded-2
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5551
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: org.thoughtcrime.securesms.recipients.RecipientId$InvalidLongRecipientIdError
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:38)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.ThreadDatabase$StaticReader.getCurrent(ThreadDatabase.java:1564)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.ThreadDatabase$StaticReader.getNext(ThreadDatabase.java:1560)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.lambda$warmUp$3(LiveRecipientCache.java:193)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.$r8$lambda$ymJZipcpDoaCAg5dEDDzJ1eGghQ(Unknown Source:0)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache$$ExternalSyntheticLambda2.run(Unknown Source:4)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at org.signal.core.util.concurrent.TracingExecutorService$execute$1.run(TracingExecutorService.kt:25)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-17 18:55:22.173 10096  5551  5602 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

```ada
01-17 18:56:50.946  1000   722  2964 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.thoughtcrime.securesms/.MainActivity (has extras)} from uid 10096
01-17 18:56:50.991  1000   722  2990 E ActivityManager: applyOptionsLocked: Unknown animationType=0
01-17 18:56:51.037  1000   722  2990 I ActivityManager: Start proc 6308:org.thoughtcrime.securesms/u0a96 for activity org.thoughtcrime.securesms/.MainActivity
01-17 18:56:51.095  1000   722   777 W Looper  : Dispatch took 109ms on android.ui, h=Handler (com.android.server.am.ActivityManagerService$UiHandler) {dc480cc} cb=null msg=53
01-17 18:56:51.138  1000   722   872 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
01-17 18:56:51.267  1000   722  1435 W ActivityManager: Slow operation: 70ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
01-17 18:56:54.505  1000   722  2990 I ActivityManager: START u0 {cmp=org.thoughtcrime.securesms/.migrations.ApplicationMigrationActivity (has extras)} from uid 10096

01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: FATAL EXCEPTION: MessageRetrievalService
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6308
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: java.lang.NullPointerException
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:203)
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.connect(WebSocketConnection.java:115)
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalWebSocket.getWebSocket(SignalWebSocket.java:147)
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalWebSocket.connect(SignalWebSocket.java:78)
01-17 18:56:55.034 10096  6308  6354 E AndroidRuntime: 	at org.thoughtcrime.securesms.messages.IncomingMessageObserver$MessageRetrievalThread.run(IncomingMessageObserver.java:216)

01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: FATAL EXCEPTION: signal-logger
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6308
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: net.zetetic.database.sqlcipher.SQLiteDatabaseLockedException: database is locked (code 5)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecute(Native Method)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.execute(SQLiteConnection.java:588)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:327)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.beginTransaction(SQLiteSession.java:302)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:556)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:427)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.LogDatabase.insert(LogDatabase.kt:123)
01-17 18:57:01.132 10096  6308  6341 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger$WriteThread.run(PersistentLogger.kt:113)
01-17 18:57:04.730  1000   722  2990 I ActivityManager: Start proc 6397:com.google.android.tts/u0a69 for broadcast com.google.android.tts/androidx.work.impl.background.systemalarm.RescheduleReceiver
01-17 18:57:04.732  1000   722  2990 I ActivityManager: Killing 3397:com.google.android.apps.photos/u0a79 (adj 906): empty #17
01-17 18:57:05.284  1000   722  3324 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=14, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ], android.os.BinderProxy@32c6bd2)
01-17 18:57:05.294  1000   722  1229 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=14, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] (release request)

01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: FATAL EXCEPTION: signal-bounded-0
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6308
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: org.thoughtcrime.securesms.recipients.RecipientId$InvalidLongRecipientIdError
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientId.from(RecipientId.java:38)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.ThreadDatabase$StaticReader.getCurrent(ThreadDatabase.java:1564)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.ThreadDatabase$StaticReader.getNext(ThreadDatabase.java:1560)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.lambda$warmUp$3(LiveRecipientCache.java:193)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.$r8$lambda$ymJZipcpDoaCAg5dEDDzJ1eGghQ(Unknown Source:0)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipientCache$$ExternalSyntheticLambda2.run(Unknown Source:4)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at org.signal.core.util.concurrent.TracingExecutorService$execute$1.run(TracingExecutorService.kt:25)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-17 18:57:12.372 10096  6308  6344 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
01-17 18:57:12.721  1000   722   779 E KernelUidCpuFreqTimeReader: Failed to read /proc/uid_time_in_state: java.io.FileNotFoundException: /proc/uid_time_in_state (No such file or directory)
01-17 18:57:12.722  1000   722   779 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu4/cpufreq/stats/time_in_state (No such file or directory)
01-17 18:57:12.829  1000   722   776 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu4/cpufreq/stats/time_in_state (No such file or directory)
```

**Comment by JamesCropcho** [comment]
Hello, all:

In case anyone else in a similar boat comes here looking for a solution, here is what I was told over email by Signal's support team:

> We reviewed this with the developers and unfortunately given the jump in versions from 2017 to 2022, the crash behavior is expected and a fix timeline for something like this is unknown. Unfortunately our best recommendation at this time is to re-install Signal, which would erase your conversations that have not been backed up. In the future we recommend setting up automatic updates for Signal to stay up to date on the versions as they are released as long as your device remains powered on and connected to wifi or mobile data.

Unfortunately I'm out of luck! But hey, at least I know that now.

―James
