### ISSUE TITLE
App get crashed in Home Screen

### ISSUE THREAD

**Issue by sagarzala123** [signalapp/Signal-Android#12018]
E/BaseJob: Encountered a fatal exception. Crash imminent.
    java.lang.SecurityException: uid 10728 cannot explicitly add accounts of type: org.thoughtcrime.securesms
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:1209)
        at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:889)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.createAccount(DirectoryHelper.java:451)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.getOrCreateSystemAccount(DirectoryHelper.java:435)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:310)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:277)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:105)
        at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:74)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accounts.AccountManagerService.addAccountExplicitlyWithVisibility(AccountManagerService.java:473)
        at com.android.server.accounts.AccountManagerService.addAccountExplicitly(AccountManagerService.java:1620)
        at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:215)
        at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1075)
        at android.os.Binder.execTransact(Binder.java:735)
E/JobRunner: [JOB::e7711328-82fd-4a91-bf60-ab840d211578][DirectoryRefreshJob][2] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 23258 ms, Lifespan: Immortal, Run Attempt: 1/10, Queue: StorageSyncingJobs)
E/AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
    Process: org.thoughtcrime.securesms, PID: 21956
    java.lang.SecurityException: uid 10728 cannot explicitly add accounts of type: org.thoughtcrime.securesms
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:1209)
        at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:889)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.createAccount(DirectoryHelper.java:451)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.getOrCreateSystemAccount(DirectoryHelper.java:435)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:310)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:277)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:105)
        at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:74)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accounts.AccountManagerService.addAccountExplicitlyWithVisibility(AccountManagerService.java:473)
        at com.android.server.accounts.AccountManagerService.addAccountExplicitly(AccountManagerService.java:1620)
        at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:215)
        at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1075)
        at android.os.Binder.execTransact(Binder.java:735)
E/SignalUncaughtException: java.lang.SecurityException: uid 10728 cannot explicitly add accounts of type: org.thoughtcrime.securesms
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:1209)
        at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:889)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.createAccount(DirectoryHelper.java:451)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.getOrCreateSystemAccount(DirectoryHelper.java:435)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:310)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshNumbers(DirectoryHelper.java:277)
        at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:105)
        at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:74)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
        at [[ ↑↑ Original Trace ↑↑ ]].(:0)
        at [[ ↓↓ Inferred Trace ↓↓ ]].(:0)
        at org.signal.core.util.concurrent.TracingExecutor.execute(TracingExecutor.kt:11)
        at org.thoughtcrime.securesms.jobmanager.JobManager.runOnExecutor(JobManager.java:405)
        at org.thoughtcrime.securesms.jobmanager.JobManager.enqueueChain(JobManager.java:384)
        at org.thoughtcrime.securesms.jobmanager.JobManager.access$200(JobManager.java:40)
        at org.thoughtcrime.securesms.jobmanager.JobManager$Chain.enqueue(JobManager.java:470)
        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:204)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accounts.AccountManagerService.addAccountExplicitlyWithVisibility(AccountManagerService.java:473)
        at com.android.server.accounts.AccountManagerService.addAccountExplicitly(AccountManagerService.java:1620)
        at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:215)
        at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1075)
        at android.os.Binder.execTransact(Binder.java:735)
I/ExoPlayerImpl: Init 45363e1 [ExoPlayerLib/2.15.0] [whyred, Redmi Note 5 Pro, Xiaomi, 28]

**Comment by cody-signal** [comment]
Please follow the template and provide a full debuglog or at least also the top SYS INFO section.
