### ISSUE TITLE
Android app immediate crashes on reboot and on open

### ISSUE THREAD

**Issue by sanjay** [signalapp/Signal-Android#12129]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a Samsung S10+ running Android 12 (March 1, 2022 Google Play system update), Signal has been crashing on app launch lately. We've fixed this by doing a complete uninstall and restore from backup and everything is fine for some time.  But then the app launch instant crash (sometimes you can see the message list screen, sometimes not) returns. Just now I rebooted the phone and without opening Signal, there was an Android popup saying that "Signal keeps stopping".

This device was fine up until a few weeks to two months ago.  We thought it might be space related but we've cleared away a ton of space. There is a group in this account between two individuals - one also a Signal user and the other one is not (Apple user in case it matters). We think it might be related to that group but really no evidence other than our other three devices don't have a group like that and have had no issues on those devices (they're also Samsung S20 Ultras in case that matters).

### Steps to reproduce
- Open Signal Android
- See crash
- Be very sad

**Actual result:** Instant crashing once it starts this behavior - no apparent way to make it stop.
**Expected result:** No insta-crashing.

### Device info
**Device:** Samsung Galaxy S10+
**Android version:** 12
**Signal version:** 5.34.5

### Link to debug log
Can't get to this menu because the app crashes every single time I try to open it.

**Comment by cody-signal** [comment]
Hey there, sorry this is happening. I feel your repro steps. Can you try using adb to capture the crash?

https://developer.android.com/studio/command-line/logcat

**Comment by jmoerschbach** [comment]
Same here. App crashes at startup after it got updated over night. Now version is 5.34.10 on Samsung Galaxy A3 (2017), Android 8.0.
Even the app name changed to "org.thoughtcrime.securesms" in both launcher and home with standard android app icon instead of signals original blue icon.

logcat output when trying to start the app (it looks like missing resources... how can that happen^^):
`2022-04-08 17:23:40.772 4837-11080/? I/ActivityManager: START u0 {act=android.intent.action.MAIN typ=null flg=0x10200000 cmp=ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} from uid 10062
2022-04-08 17:23:40.810 4837-5869/? D/ActivityManagerPerformance: Received MSG_CFMS_HINT_AMS_SWITCH pkgName: org.thoughtcrime.securesms
2022-04-08 17:23:40.840 4837-4920/? W/WindowManager: Token{ad7d337 ActivityRecord{7407836 u0 org.thoughtcrime.securesms/.RoutingActivity t46948}} failed creating starting window
    android.content.res.Resources$NotFoundException: Resource ID #0x112003d
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
        at android.content.res.Resources.getBoolean(Resources.java:1071)
        at android.view.Window.getDefaultFeatures(Window.java:1664)
        at android.view.Window.<init>(Window.java:675)
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:345)
        at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:3505)
        at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:98)
        at com.android.server.wm.AppWindowContainerController.lambda$-com_android_server_wm_AppWindowContainerController_5383(AppWindowContainerController.java:164)
        at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.$m$0(Unknown Source:4)
        at com.android.server.wm.-$Lambda$yD_PJl7HJqiWmREGaMLSh2Wy11U$2.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
2022-04-08 17:23:40.841 4837-11080/? D/ActivityManager: applyOptionsLocked, ANIM_CUSTOM_SCALE_UP, task.getRootActivity() : ActivityRecord{7407836 u0 org.thoughtcrime.securesms/.RoutingActivity t46948}, task.getTaskToReturnTo() : 1
2022-04-08 17:23:40.848 4837-5097/? D/GameManagerService: handleForegroundChange(). pkgName: org.thoughtcrime.securesms, clsName: org.thoughtcrime.securesms.MainActivity,FgActivityName:org.thoughtcrime.securesms/.MainActivity
2022-04-08 17:23:40.848 4837-11080/? D/MARsPolicyManager: onPackageResumedFG pkgName = org.thoughtcrime.securesms, userId = 0
2022-04-08 17:23:40.848 4837-5097/? D/GameManagerService: handleForegroundChange(). pkgName: org.thoughtcrime.securesms, clsName: org.thoughtcrime.securesms.MainActivity,FgActivityName:org.thoughtcrime.securesms/.MainActivity
2022-04-08 17:23:40.848 4837-5097/? D/GameManagerService: notifyResumePause(). pkg: org.thoughtcrime.securesms, type: 4, isMinimized: false, isTunableApp: false
2022-04-08 17:23:40.857 4837-7704/? D/GamePkgDataHelper: getGamePkgDataIncServer(). org.thoughtcrime.securesms
2022-04-08 17:23:40.857 4837-7704/? D/GameManagerService: identifyGamePackage. org.thoughtcrime.securesms
2022-04-08 17:23:40.857 4837-7704/? D/GamePkgDataHelper: getGamePkgData(). org.thoughtcrime.securesms
2022-04-08 17:23:40.858 4837-7704/? D/GameManagerService: identifyGamePackage. org.thoughtcrime.securesms
2022-04-08 17:23:40.858 4837-7704/? D/GamePkgDataHelper: getGamePkgData(). org.thoughtcrime.securesms
2022-04-08 17:23:40.860 4837-7704/? D/GameManagerService: identifyGamePackage. org.thoughtcrime.securesms
2022-04-08 17:23:40.860 4837-7704/? D/GamePkgDataHelper: getGamePkgData(). org.thoughtcrime.securesms
2022-04-08 17:23:40.863 4837-7704/? D/GameManagerService: identifyGamePackage. org.thoughtcrime.securesms
2022-04-08 17:23:40.864 4837-7704/? D/GamePkgDataHelper: getGamePkgData(). org.thoughtcrime.securesms
2022-04-08 17:23:40.932 4130-4130/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms, PID: 4130
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f1309d9
        at android.app.ActivityThread.installProvider(ActivityThread.java:6581)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f1309d9
        at android.content.res.ResourcesImpl.getResourcePackageName(ResourcesImpl.java:262)
        at android.content.res.Resources.getResourcePackageName(Resources.java:1963)
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(com.google.android.gms:play-services-basement@@17.5.0:5)
        at com.google.firebase.FirebaseOptions.fromResource(FirebaseOptions.java:156)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:243)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
2022-04-08 17:23:40.937 4837-11080/? W/ActivityManager: crash : org.thoughtcrime.securesms,0
2022-04-08 17:23:40.938 4837-11080/? W/ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
2022-04-08 17:23:40.939 4837-11080/? W/MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{9166310d0 #46948 A=org.thoughtcrime.securesms U=0 StackId=1 sz=1}, rootActivity=null
2022-04-08 17:23:40.960 4837-4854/? W/PackageManager: Failure retrieving text 0x7f13099d in package org.thoughtcrime.securesms
    android.content.res.Resources$NotFoundException: String resource ID #0x7f13099d
        at android.content.res.Resources.getText(Resources.java:353)
        at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:2165)
        at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo.java:173)
        at android.app.ApplicationPackageManager.getApplicationLabel(ApplicationPackageManager.java:2209)
        at com.android.server.am.AppErrorDialog.<init>(AppErrorDialog.java:80)
        at com.android.server.am.AppErrors.handleShowAppErrorUi(AppErrors.java:974)
        at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:2224)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
        at com.android.server.UiThread.run(UiThread.java:42)
2022-04-08 17:23:40.961 4837-4854/? I/ActivityManager: Showing crash dialog for package org.thoughtcrime.securesms u0
2022-04-08 17:23:41.010 4837-4854/? V/WindowManager: Relayout Window{37f0b91 u0 Application Error: org.thoughtcrime.securesms}: viewVisibility=0 req=676x425 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x110 fmt=-3 wanim=0x10302ec surfaceInsets=Rect(4, 4 - 4, 4) needsMenuKey=2 colorMode=0 naviIconColor=0}
2022-04-08 17:23:41.013 2637-2637/? I/SurfaceFlinger: id=1017 createSurf (684x433),1 flag=4, Application Error: org.thoughtcrime.securesms#0
2022-04-08 17:23:41.029 2585-2596/? W/PkgUtils: p: org.thoughtcrime.securesms, u:0
2022-04-08 17:23:41.037 4837-4854/? V/WindowManager: finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING Window{37f0b91 u0 Application Error: org.thoughtcrime.securesms} in Surface(name=Application Error: org.thoughtcrime.securesms)
2022-04-08 17:23:41.076 2637-2637/? D/SurfaceFlinger:   Display[0] configurations (* current):
        * 0: 720x1280, xdpi=309.966003, ydpi=309.638000, refresh=16949152
      numHwLayers=5, flags=00000000
        type   |  handle  | hint | flag | tr | blnd |   format    |     source crop (l,t,r,b)      |          frame         | name 
    -----------+----------+------+------+----+------+-------------+--------------------------------+------------------------+------
           HWC | ef3e6240 | 0000 | 0020 | 00 | 0100 | RGBx_8888   |   36.0,   64.0,  756.0, 1344.0 |    0,    0,  720, 1280 | com.android.systemui.ImageWallpaper#0
          GLES | eef03cc0 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity#0
          GLES | eef033c0 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  684.0,  433.0 |   45,  464,  674,  862 | Application Error: org.thoughtcrime.securesms#0
           HWC | ef3e60c0 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720
2022-04-08 17:23:41.078 5242-5645/? W/PackageManager: Failure retrieving text 0x7f13099d in package org.thoughtcrime.securesms
    android.content.res.Resources$NotFoundException: String resource ID #0x7f13099d
        at android.content.res.Resources.getText(Resources.java:353)
        at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:2165)
        at android.content.pm.ComponentInfo.loadLabel(ComponentInfo.java:149)
        at com.android.systemui.recents.misc.SystemServicesProxy.getBadgedActivityLabel(SystemServicesProxy.java:1117)
        at com.android.systemui.recents.model.RecentsTaskLoader.getAndUpdateActivityTitle(RecentsTaskLoader.java:505)
        at com.android.systemui.recents.model.RecentsTaskLoadPlan.preloadPlan(RecentsTaskLoadPlan.java:243)
        at com.android.systemui.recents.model.RecentsTaskLoader.preloadTasks(RecentsTaskLoader.java:381)
        at com.android.systemui.recents.RecentsImpl$TaskStackListenerImpl.onTaskStackChangedBackground(RecentsImpl.java:207)
        at com.android.systemui.recents.misc.SystemServicesProxy$2.onTaskStackChanged(SystemServicesProxy.java:308)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:49)
        at android.os.Binder.execTransact(Binder.java:682)
2022-04-08 17:23:41.084 5242-5645/? W/PackageManager: Failure retrieving resources for org.thoughtcrime.securesms: Resource ID #0x7f0f0000
2022-04-08 17:23:41.084 4837-6344/? D/PackageManager: getComponentMetadataForIconTray : org.thoughtcrime.securesms.MainActivity does not exist in mServices
2022-04-08 17:23:41.084 4837-6344/? D/PackageManager: getComponentMetadataForIconTray : org.thoughtcrime.securesms.MainActivity does not exist in mProviders
2022-04-08 17:23:41.084 4837-6344/? D/PackageManager: getComponentMetadataForIconTray : org.thoughtcrime.securesms.MainActivity does not exist in mReceivers
2022-04-08 17:23:41.085 5242-5645/? D/ApplicationPackageManager: updateItemMetaDataForFixedIconScale: package: org.thoughtcrime.securesms
2022-04-08 17:23:41.085 4837-6344/? D/PackageManager: getSelectedMetaData : packageName(org.thoughtcrime.securesms) or Metadata strings {[Ljava.lang.String;@14f3dda}
2022-04-08 17:23:41.085 5242-5645/? I/ApplicationPackageManager: return adaptive icon for org.thoughtcrime.securesms
2022-04-08 17:23:41.092 2637-2637/? D/SurfaceFlinger:  460,  681,  867 | Application Error: org.thoughtcrime.securesms#0
           HWC | ef3e60c0 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0,   48.0 |    0,    0,  720,   48 | StatusBar#0
     FB TARGET | ef3e6600 | 0000 | 0000 | 00 | 0105 | RGBA_8888   |    0.0,    0.0,  720.0, 1280.0 |    0,    0,  720, 1280 | HWC_FRAMEBUFFER_TARGET
2022-04-08 17:23:41.440 4837-4853/? W/ActivityManager: Activity pause timeout for ActivityRecord{7407836 u0 org.thoughtcrime.securesms/.RoutingActivity t46948 f}
2022-04-08 17:23:43.812 4837-5869/? D/ActivityManagerPerformance: Received MSG_DISABLE_APP_SWITCH, r: ActivityRecord{7407836 u0 org.thoughtcrime.securesms/.RoutingActivity t46948 f}
2022-04-08 17:23:51.450 4837-4853/? W/ActivityManager: Activity destroy timeout for ActivityRecord{7407836 u0 org.thoughtcrime.securesms/.RoutingActivity t46948 f}
2022-04-08 17:24:11.100 4837-11080/? I/ActivityManager: Killing 4130:org.thoughtcrime.securesms/u0a218 (adj 900): crash
2022-04-08 17:24:11.112 4837-4854/? D/InputEventReceiver: channel '37f0b91 Application Error: org.thoughtcrime.securesms (client)' ~ Disposing input event receiver.
2022-04-08 17:24:11.112 4837-4854/? D/InputEventReceiver: channel '37f0b91 Application Error: org.thoughtcrime.securesms (client)' ~NativeInputEventReceiver.
2022-04-08 17:24:11.113 4837-4854/? I/WindowManager: Destroying surface Surface(name=Application Error: org.thoughtcrime.securesms) called by com.android.server.wm.WindowStateAnimator.destroySurface:2501 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:985 com.android.server.wm.WindowState.removeImmediately:2407 com.android.server.wm.WindowState.removeIfPossible:2615 com.android.server.wm.WindowState.removeIfPossible:2445 com.android.server.wm.WindowManagerService.removeWindow:2028 com.android.server.wm.Session.remove:237 android.view.ViewRootImpl.dispatchDetachedFromWindow:4106 
2022-04-08 17:24:11.113 2637-3748/? I/SurfaceFlinger: id=1017 Removed Application Error: org.thoughtcrime.securesms#0 (4/6)
2022-04-08 17:24:11.114 2637-2637/? I/Layer: id=1017 onRemoved Application Error: org.thoughtcrime.securesms#0 
`

**Comment by cody-signal** [comment]
@jmoerschbach huh...this log has a crash around string resources but it's all in the system level. I don't know of anything we've changed recently that would impact this.

**Comment by jmoerschbach** [comment]
ok, so I could fix my issue by joining the beta program and thus forcing another update (v5.35.0). Now everything works again. I suspect that something went wrong while automatically updating because of storage issues (my device is quite full). I freed some space and updated successfully to 5.35.0 and all is good :)

**Comment by sanjay** [comment]
@cody-signal Thanks for the response.  We ended up uninstalling and restoring so it's working fine now but given recent history, this is going to happen again soon.  The minute it does I'll try to capture the crash (just installed adb on my laptop). This is my spouse's phone so I'll just have to wait until she tells me it's acting up again.

**Comment by sanjay** [comment]
@cody-signal Okay - I think we've figured out what the steps are to cause this crash.  It's a group with two other members (three people total).  Two members have Signal and the third is an iPhone user (no Signal).  My spouse forwarded a message from "Note to Self" to the group chat.  This caused Signal to crash and then go into a loop where the app would no longer open.  My spouse then uninstalled Signal and reinstalled it and restored it from backup and it's fine again (although she likely lost some stuff since last night's backup - a feature request would be to let the user set the frequency of backups).  Before you ask, I didn't get a crash dump because she did this before I could ask to get the phone to get the log.  If it happens again, I'll get the crash log but I figured some info on the path to the crash would at least be somewhat helpful.

**Comment by colzin** [comment]
I just had this problem yesterday. I forwarded from a signal user to an MMS group, and the app now is in a crash loop.
This is on a Note 9 Android phone. I have taken adb logs when trying to open signal, and a video (that is too big to upload here).
[signalLog1_airplaneMode.txt](https://github.com/signalapp/Signal-Android/files/8505772/signalLog1_airplaneMode.txt)
[signalLog2_online.txt](https://github.com/signalapp/Signal-Android/files/8505773/signalLog2_online.txt)

I guess I'll try uninstalling and reinstalling, and hope that I don't lose many messages...

**Comment by grandchild** [comment]
Same thing happened here yesterday after upgrade:
```
[ 09-11 14:50:28.116   657:0x2a7 W/PackageManager ]
Failure retrieving text 0x7f130a65 in package org.thoughtcrime.securesms
android.content.res.Resources$NotFoundException: String resource ID #0x7f130a65
    at android.content.res.Resources.getText(Resources.java:254)
    at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:994)
    at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo.java:115)
    at android.app.ApplicationPackageManager.getApplicationLabel(ApplicationPackageManager.java:1038)
    at com.android.server.am.AppErrorDialog.<init>(AppErrorDialog.java:69)
    at com.android.server.am.ActivityManagerService$2.handleMessage(ActivityManagerService.java:1207)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at com.android.server.am.ActivityManagerService$AThread.run(ActivityManagerService.java:2049)
```

Plus, the App icon is gone and replaced by a generic Android icon. When I try and install the APK from `/data/app/` it says "App not installed" (I guess, as in "wasn't installed" not "you don't have it").

So it does seem like an upgrade issue (faulty download?). Will see if forcing an upgrade through joining the Beta fixes things. A "force redownload" button in the PlayStore would be handy for debugging.

My phone's system is a rather ancient Android 4.4.
