### ISSUE TITLE
crash on startup after upgrade ("Upgrading database: 23, 135", "database corruption at line", "getDatabase called recursively")

### ISSUE THREAD

**Issue by r00t-** [signalapp/Signal-Android#12147]
### Bug description
i'm seeing a crash similar to the one reported and fixed in https://github.com/signalapp/Signal-Android/issues/11874 in the current release (5.34.5).

i upgraded from a very old version (that i had not used for a long time, and that had become unsupported),
which most likely was 4.50.6.
after the upgrade, signal always crashed on startup.
clearing application data and trying to restore a backup made before the upgrade leads to the same crash.

**i cannot work around by going back to the old version, because it won't import the backup before registering with the server, which does not work anymore. thus my backup is unreadable/useless now.** (lest i extract the code to decrypt it from the app.)

```
04-01 19:25:51.711 29113 29145 I SignalDatabase: Upgrading database: 23, 135
[...]
04-01 19:25:52.155 29113 29145 E SQLiteLog: (11) database corruption at line 71281 of [10e20c0b43]
04-01 19:25:52.155 29113 29145 E SQLiteLog: (11) database corruption at line 71431 of [10e20c0b43]
04-01 19:25:52.162 29113 29158 I RefreshPreKeysJob: Scheduling a prekey refresh. Time since last schedule: 1648833952162 ms
04-01 19:25:52.162 29113 29147 I SQLiteConnection: Database keying operation returned:0
04-01 19:25:52.164 29113 29145 E SignalUncaughtException:
04-01 19:25:52.164 29113 29145 E SignalUncaughtException: java.lang.IllegalStateException: getDatabase called recursively
04-01 19:25:52.164 29113 29145 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:313)
04-01 19:25:52.164 29113 29145 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:273)
04-01 19:25:52.164 29113 29145 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.getRawWritableDatabase(SignalDatabase.kt:176)
04-01 19:25:52.164 29113 29145 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase$Companion.inTransaction(SignalDatabase.kt:227)
04-01 19:25:52.164 29113 29145 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.inTransaction(SignalDatabase.kt)

```

[signal_crash.txt](https://github.com/signalapp/Signal-Android/files/8460008/signal_crash.txt)

### Steps to reproduce
upgrade from very old version or try to import backup from such a version.

**Actual result:** crash
**Expected result:** no crash

### Device info
**Android version:** android 7 (MIUI)
**Signal version:** 5.34.5

### Link to debug log
see catlog log above.

**Comment by r00t-** [comment]
great this is addressed so quickly!
