### ISSUE TITLE
Notification of failed message when sending group text to non-Signal users

### ISSUE THREAD

**Issue by allieaggie** [signalapp/Signal-Android#12155]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I send a group text via Signal (my default app) to a group with all non-Signal Users, I get a notifficaton of "Send Failed" and message "Message could not be sent. Check your connection and try again."

I'm definitely connected, since I can text an individual non-Signal User and texts to individual Signal users and group texts to Signal Users work just fine.  It seems to consistently fail when texting to a GROUP of all non-Signal Users.  I just started to experience this today (4/12/2022) - and worked just fine yesterday. 

I also tried to create a new group with 3 non-Signal Users, and when I send a group text, I get the "Send Failed" notification.

I'm sending a brief text with no pictures.

I saw that there was a similar issue posted, but then was closed due to no activity -  https://github.com/signalapp/Signal-Android/issues/11541  

### Steps to reproduce
- Open Signal app
- look for the group with non-signal users
- start typing a brief message 
- hit send

**Actual result:** It spins for a few seconds, then I get the notification of "Send"
**Expected result:** The message should send with no issues. 

### Device info

**Device:** Samsung Galaxy S21 5G
**Android version:** 12
**Signal version:** 5.34.10

### Link to debug log

https://debuglogs.org/android/5.34.10/e2d0564b4303bb987091f594363ec20899d154befdccd4010d249874067e29bd

**Comment by jmcclelland** [comment]
I reviewed the log file and see a back trace repeated. The error seems to be:

`CompatMmsConnection: org.thoughtcrime.securesms.mms.MmsException: java.util.concurrent.TimeoutException: timeout when waiting for MMS`

Here is the full chunk:

```
04-12 10:32:59.868  6072  6440 I Job     : [JOB::dfb1e7ba-6b1c-46a5-9a41-79c39a0f38e5][MmsDownloadJob] onSubmit() (Time Since Submission: 2 ms, Lifespan: Immortal, Run Attempt: 1/25, Queue: mms-operation)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn: null
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn: java.util.concurrent.TimeoutException: timeout when waiting for MMS
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:118)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:77)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:146)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
04-12 10:33:00.071  6072  6496 W IncomingLollipopMmsConn:       at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection: null
04-12 10:33:00.071  6072  6496 W CompatMmsConnection: org.thoughtcrime.securesms.mms.MmsException: java.util.concurrent.TimeoutException: timeout when waiting for MMS
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:144)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:77)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:146)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection: Caused by: java.util.concurrent.TimeoutException: timeout when waiting for MMS
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:118)
04-12 10:33:00.071  6072  6496 W CompatMmsConnection:   ... 5 more
04-12 10:33:00.071  6072  6496 I CompatMmsConnection: Falling back to receiving via legacy connection
04-12 10:33:00.071  6072  6496 W MmsDownloadJob: null
04-12 10:33:00.071  6072  6496 W MmsDownloadJob: java.io.IOException: Both lollipop and fallback APIs failed...
04-12 10:33:00.071  6072  6496 W MmsDownloadJob:        at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:99)
04-12 10:33:00.071  6072  6496 W MmsDownloadJob:        at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:146)
04-12 10:33:00.071  6072  6496 W MmsDownloadJob:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
04-12 10:33:00.071  6072  6496 W MmsDownloadJob:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
04-12 10:33:00.071  6072  6496 W MmsDownloadJob:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
04-12 10:33:00.075  6072  4708 W FixedSizePagingController: Invalidated! Just before individual change was loaded for position 1
```

**Comment by allieaggie** [comment]
I was able to finally make it work by clearing the cache of the Signal App and restarting the phone.
To clear the cache:
- Go to Home screen
- Swipe from top downward and click the Settings icon ("gear wheel")
- click on Apps
- click on Signal app
- click on Storage
- click "Clear Cache"
- Restart the phone

It now works like a charm!

**Comment by greyson-signal** [comment]
Hmm, I'd be surprised if we had anything in the cache causing this bug. More likely this is some weird state your system was in, since the calls that were failing were system calls. But sounds like things are resolved now, good to hear :)
