### ISSUE TITLE
Signal create damaged backup on SD card trimmed to 4GiB

### ISSUE THREAD

**Issue by ikino** [signalapp/Signal-Android#12282]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal backup created on SDcard and greater than 4GiB are trimmed and damaged.

### Steps to reproduce
- backup to sd card greater than 4GiB
- signal say backup OK

**Actual result:** Backup is unusable, trimmed and damaged, when importing that, signal silently crash. I lost 3 months of data.

### Device info

**Device:** Motorola G20
**Android version:** 11
**Signal version:** 5.40.4

when importing:
```
2022-06-04 11:12:59.287 12230-12264/org.thoughtcrime.securesms W/FullBackupImporter: Bad MAC for attachment 1650737789852! Can't restore it.
    org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:403)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:184)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:117)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:89)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-06-04 11:12:59.297 12230-12264/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.thoughtcrime.securesms, PID: 12230
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
        at java.lang.System.arraycopy(System.java:524)
        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:419)
        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:359)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:110)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:89)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-06-04 11:12:59.303 12230-12264/org.thoughtcrime.securesms E/SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
        at java.lang.System.arraycopy(System.java:524)
        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:419)
        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:359)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:110)
        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:89)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:291)
        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

```

**Comment by ikino** [comment]
Problem is so backup was created on SD card with FAT32. Signal create backup trimmed to 4GiB, but WITHOUT ERROR !!!

**Comment by clauz9** [comment]
Is your SD card formatted as `Fat32` for some reason ? 🤔 

if you don't know, you can install [Disk info](https://play.google.com/store/apps/details?id=com.drhowdydoo.diskinfo&hl=en_US&gl=US) and find out. 

let me know what shows up for you, in the red square
![image](https://user-images.githubusercontent.com/77681918/172024014-89b54845-3fc4-40eb-9b10-d6c81f541dc5.png)

**Comment by ikino** [comment]
@clauz9 Yes, It's fat32. It's formated as FAT32 default from shop. I know, of course, that maximum file size of fat32 is 4GiB. But it's weird that the signal didn't throw an error. If he threw an error, I would know there was a problem and I could back it up to internal memory.

**Comment by clauz9** [comment]
> But it's weird that the signal didn't throw an error.

well....you're not wrong, Signal should either warn you, or make split back-ups.

**Comment by johanw666** [comment]
Reformat the card as ExFAT or ext4 is a quick wortkaround.

**Comment by ikino** [comment]
Reformat is not a solution. Most people use FAT32.

**Comment by johanw666** [comment]
Then they will have a problem with such large bckups. FAT32 file size limit is 4GB. But most large SD cards I get these days are exFAT formatted. The last one I got with FAT32 were some old 2GB cards where this is no issue anyway.

**Comment by ikino** [comment]
@johanw666 I know, but Signal silently say so backup is OK, but backup file IS NOT OK. And that is wrong.

**Comment by Smojo** [comment]
> Reformat the card as ExFAT or ext4 is a quick wortkaround.

**@johanw666 do you have a reference guide how to do this?** Last time I tried with a Fairphone 2 and it is not accepted by Android (asks for re-formating after boot). Detials you can read [here](https://forum.fairphone.com/t/use-a-different-format-for-sd-card-as-portable-storage-ext3-ext4-extfat/71197/9) or o this thread in general.

**Comment by Diapolo** [comment]
> Reformat the card as ExFAT or ext4 is a quick wortkaround.

This is not an option for some Android versions / configurations, for me it doesn't work and I can just use FAT32 👎 .

**Comment by Diapolo** [comment]
> > Reformat the card as ExFAT or ext4 is a quick wortkaround.
> 
> **@johanw666 do you have a reference guide how to do this?** Last time I tried with a Fairphone 2 and it is not accepted by Android (asks for re-formating after boot). Detials you can read [here](https://forum.fairphone.com/t/use-a-different-format-for-sd-card-as-portable-storage-ext3-ext4-extfat/71197/9) or o this thread in general.

Same phone, same observation.

**Comment by johanw666** [comment]
I have no experience with Fairphones, I format my card (265GB) as exFAT and that works in my device. I didn't try ext4 because that gives compatibility issues when I want to sync the card contants with my PC.

**Comment by Smojo** [comment]
What does "marked as stale" and the "wontfix" label here and for the PR mean? 

The newer the device and/or the more internal space (and/or the possibility to format the external SD to a filesystem, which supports files bigger than 4G -> which is nothing for an average user) the less critical this problem is. 

Still I think it is a good enhancement, so I hope this "marked as stale" will not lead to that the PR is dropped completely.
