### ISSUE TITLE
Backup fails on Android because a .mms file is missing in Signal data store

### ISSUE THREAD

**Issue by MatejKafka** [signalapp/Signal-Android#12387]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Creating a chat backup on my Android 11 phone fails a few seconds after I start the backup – the backup seems to be running correctly for a bit, and then it fails after encountering a missing file. The debug log shows the following exception:
```
[5.46.1] [392  ] 2022-08-12 12:07:40.198 GMT+02:00 W LocalBackupJobApi29: Error during backup!
[5.46.1] [392  ] 2022-08-12 12:07:40.198 GMT+02:00 W LocalBackupJobApi29: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part8819524030910873446.mms: open failed: ENOENT (No such file or directory)
```

### Steps to reproduce
Sorry, I don't have a reproduction from a clean state. The issue started occurring today, and a restart doesn't help.

### Device info

**Device:** Unihertz Jelly2
**Android version:** 11
**Signal version:** 5.46.1

### Debug log
If necessary, I can provide the full debug log, but I hope this snippet should contain all logs relevant to the backup attempt.
```
[5.46.1] [2408 ] 2022-08-12 11:54:47.017 GMT+02:00 I LocalBackupJobApi29: Executing backup job...
[5.46.1] [2408 ] 2022-08-12 11:54:47.018 GMT+02:00 D NotificationCancellatio: cancelLegacy() called with: notificationId = [31321]
[5.46.1] [2408 ] 2022-08-12 11:54:47.022 GMT+02:00 I GenericForegroundServic: Starting foreground service (Creating Signal backup…) id=3
[5.46.1] [main ] 2022-08-12 11:54:47.138 GMT+02:00 I GenericForegroundServic: handleStart() ChannelId: backups_v2  Id: 3 Progress: 0/0 determinate
[5.46.1] [main ] 2022-08-12 11:54:47.150 GMT+02:00 I NotificationController: Service connected ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.service.GenericForegroundService}
[5.46.1] [main ] 2022-08-12 11:54:47.151 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 0/0 indeterminate
[5.46.1] [2408 ] 2022-08-12 11:54:48.955 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 0/100 determinate
[5.46.1] [2408 ] 2022-08-12 11:55:00.765 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 1/100 determinate
[5.46.1] [2408 ] 2022-08-12 11:55:05.894 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 2/100 determinate
[5.46.1] [2408 ] 2022-08-12 11:55:10.782 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 3/100 determinate
[5.46.1] [2408 ] 2022-08-12 11:55:18.417 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 4/100 determinate
[5.46.1] [2408 ] 2022-08-12 11:55:30.457 GMT+02:00 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 3 Progress: 5/100 determinate
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: Error during backup!
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part8819524030910873446.mms: open failed: ENOENT (No such file or directory)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at libcore.io.IoBridge.open(IoBridge.java:492)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:28)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.openAttachmentStream(FullBackupExporter.java:428)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.calculateVeryOldStreamLength(FullBackupExporter.java:414)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportAttachment(FullBackupExporter.java:373)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.lambda$internalExport$5(FullBackupExporter.java:174)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.$r8$lambda$AM__6NnZmduQ5oDS8tZY51D7UmE(Unknown Source:0)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter$$ExternalSyntheticLambda6.postProcess(Unknown Source:8)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportTable(FullBackupExporter.java:345)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.internalExport(FullBackupExporter.java:174)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.export(FullBackupExporter.java:122)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:118)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at libcore.io.Linux.open(Native Method)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7584)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	at libcore.io.IoBridge.open(IoBridge.java:478)
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 	... 15 more
[5.46.1] [2408 ] 2022-08-12 11:55:36.722 GMT+02:00 W LocalBackupJobApi29: 
[5.46.1] [2408 ] 2022-08-12 11:55:37.174 GMT+02:00 W LocalBackupJobApi29: Backup failed. Deleted temp file
[5.46.1] [2408 ] 2022-08-12 11:55:37.177 GMT+02:00 I GenericForegroundServic: Stopping foreground service id=3
[5.46.1] [main ] 2022-08-12 11:55:37.178 GMT+02:00 I GenericForegroundServic: handleStop()
[5.46.1] [main ] 2022-08-12 11:55:37.179 GMT+02:00 I GenericForegroundServic: Last request. Ending foreground service.
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: [JOB::a3684082-1f9a-4716-a5a7-c2c0b9f5ab20][LocalBackupJobApi29] Encountered a failing exception. (Time Since Submission: 67874942 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part8819524030910873446.mms: open failed: ENOENT (No such file or directory)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at libcore.io.IoBridge.open(IoBridge.java:492)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:28)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.openAttachmentStream(FullBackupExporter.java:428)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.calculateVeryOldStreamLength(FullBackupExporter.java:414)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportAttachment(FullBackupExporter.java:373)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.lambda$internalExport$5(FullBackupExporter.java:174)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.$r8$lambda$AM__6NnZmduQ5oDS8tZY51D7UmE(Unknown Source:0)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter$$ExternalSyntheticLambda6.postProcess(Unknown Source:8)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportTable(FullBackupExporter.java:345)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.internalExport(FullBackupExporter.java:174)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.export(FullBackupExporter.java:122)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:118)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at libcore.io.Linux.open(Native Method)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7584)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	at libcore.io.IoBridge.open(IoBridge.java:478)
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 	... 15 more
[5.46.1] [2408 ] 2022-08-12 11:55:37.179 GMT+02:00 W BaseJob: 
[5.46.1] [2408 ] 2022-08-12 11:55:37.180 GMT+02:00 W JobRunner: [JOB::a3684082-1f9a-4716-a5a7-c2c0b9f5ab20][LocalBackupJobApi29][1] Job failed. (Time Since Submission: 67874943 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
```

**Comment by cody-signal** [comment]
Hey there, we are tracking this in our current beta thread, and will have a fix in .3 coming out later today.

**Comment by nsartor** [comment]
This is now working for me on 5.46.3, was previously failing.

Thanks!

**Comment by MatejKafka** [comment]
Can confirm that backups now also work for me. :+1:
