### ISSUE TITLE
Signal keeps stopping

### ISSUE THREAD

**Issue by vbatts** [signalapp/Signal-Android#12392]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Opening a new issue, as it seems unfix by the similar issues of #12370 and #12375 

### Bug description
The Signal app (when in the background or launched) closes and the Android message of "Signal keeps stopping".

From #12375 I found that the app can stay launched while the phone is in airplane-mode (no mobile nor wifi). Enabling any data connection will immediately crash the app.

This happened last week for me. In troubleshooting it, I even wiped my device. Did not record the versions of Signal being used at that time. Sorry.
When re-setting up my phone the Signal backup did not work, so this week I was starting from a fresh start and have not had any crashes all week until today.

### Steps to reproduce
- Launch app
- almost immediately the app closes

**Actual result:** Normal application usage
**Expected result:** Android will drop you back to the home screen, possibly with the message box

### Screenshots

![Screenshot_20220813-080617](https://user-images.githubusercontent.com/67049/184510350-f0da3395-d57b-45c7-a235-ad969a332fc3.png)

### Device info

**Device:** Moto g stylus (XT2043-4)
**Android version:** 11; RPRS31.Q1-56-9-15; 4.14.180-perf+#1 Sun Mar 27 09:24:05 EDT 2022
**Signal version:** either the 5.46.3 beta or 5.45.6 regular

### Link to debug log

[signal-log-1660422302024.zip](https://github.com/signalapp/Signal-Android/files/9332140/signal-log-1660422302024.zip)

**Comment by vbatts** [comment]
maybe the relevant portion of the attached log?
```
[5.45.6] [7376 ] 2022-08-13 16:23:48.512 EDT D StoryDistributionListRe: Attempting to get matching record...
[5.45.6] [7376 ] 2022-08-13 16:23:48.514 EDT E StoryDistributionListRe: Cannot find matching database record for My Story.
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob: Encountered a fatal exception. Crash imminent.
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob: org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor$MyStoryDoesNotExistException
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.getMatching(StoryDistributionListRecordProcessor.java:76)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.getMatching(StoryDistributionListRecordProcessor.java:24)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:51)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.process(StoryDistributionListRecordProcessor.java:24)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:403)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:283)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:195)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:         at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[5.45.6] [7376 ] 2022-08-13 16:23:48.515 EDT E BaseJob:
[5.45.6] [7376 ] 2022-08-13 16:23:48.517 EDT E JobRunner: [JOB::e00b5807-6824-4c98-9ca8-d21f237a3dac][StorageSyncJob][3] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 417 ms, Lifespan: 86400000 ms, Run Attempt: 1/3, Queue: StorageSyncingJobs)
[5.45.6] [7359 ] 2022-08-13 16:23:48.520 EDT D PinRestoreRepository: [PinSubmission] MasterKey: 3239  AccountRestore: 511  ContactRestore: 421  total: 4171
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException: org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor$MyStoryDoesNotExistException
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.getMatching(StoryDistributionListRecordProcessor.java:76)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.getMatching(StoryDistributionListRecordProcessor.java:24)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:51)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.process(StoryDistributionListRecordProcessor.java:24)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:403)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:283)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:195)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at [[ ↑↑ Original Trace ↑↑ ]].(:0)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at [[ ↓↓ Inferred Trace ↓↓ ]].(:0)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.signal.core.util.concurrent.TracingExecutor.execute(TracingExecutor.kt:11)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getLive(LiveRecipientCache.java:82)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.recipients.Recipient.live(Recipient.java:150)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.recipients.Recipient.resolved(Recipient.java:179)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.crypto.storage.SignalBaseIdentityKeyStore.getIdentityRecord(SignalBaseIdentityKeyStore.java:156)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.crypto.storage.SignalIdentityKeyStore.getIdentityRecord(SignalIdentityKeyStore.java:73)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.database.RecipientDatabase.applyStorageSyncContactUpdate(RecipientDatabase.kt:934)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.ContactRecordProcessor.updateLocal(ContactRecordProcessor.java:165)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.storage.ContactRecordProcessor.process(ContactRecordProcessor.java:25)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:396)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:283)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:195)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[5.45.6] [7376 ] 2022-08-13 16:23:48.521 EDT E SignalUncaughtException:         at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by vbatts** [comment]
I just installed the 5.46.5 beta and restored from backup. No crashes yet.

**Comment by greyson-signal** [comment]
I think you just had some bad data from an old backup, and I put in some additional safe guards. For the history on the crash, you can read my comment [here](https://github.com/signalapp/Signal-Android/issues/12370#issuecomment-1207253491). Thanks!

**Comment by vbatts** [comment]
Thanks @greyson-signal

**Comment by MikeSofaer** [comment]
Is there an accepted way to mitigate this? I am having repeated crashing after moving messages to my new phone, and I'd like to know how to get it working, ideally without losing all the messages.

**Comment by greyson-signal** [comment]
@MikeSofaer Can you get a debuglog and follow up in #12552?

To get a debuglog during registration, tap any header text 8 times. Thanks!
