### ISSUE TITLE
After Upgrading from 5.26.0.0(-JW) to 5.47.0.0(-JW) Signal crashes on startup

### ISSUE THREAD

**Issue by derMart** [signalapp/Signal-Android#12410]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Although this is happening on JW fork, it seems to be a problem upstream. See https://github.com/johanw666/Signal-Android/issues/56 for details

### Steps to reproduce
see https://github.com/johanw666/Signal-Android/issues/56 for details

### Link to debug log
see https://github.com/johanw666/Signal-Android/issues/56 for details
EDIT: for convenience here is also the log:
```
08-21 15:31:01.628  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
08-21 15:31:01.628  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
08-21 15:31:01.628  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
08-21 15:31:01.628  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
08-21 15:31:01.631  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
08-21 15:31:01.632  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
08-21 15:31:01.635  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
08-21 15:31:01.636  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
08-21 15:31:01.636  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
08-21 15:31:01.636  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
08-21 15:31:01.636  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
08-21 15:31:01.636  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
08-21 15:31:01.636  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
08-21 15:31:01.637  1569  1569 W crime.securesm: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
08-21 15:31:01.656  1569  1569 I ApplicationContext: Installed AesGcmProvider: 1
08-21 15:31:01.830  1569  1569 V NativeCrypto: Registering org/conscrypt/NativeCrypto's 284 native methods...
08-21 15:31:01.834  1569  1569 W crime.securesm: Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
08-21 15:31:01.834  1569  1569 W crime.securesm: Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
08-21 15:31:01.835  1569  1569 W crime.securesm: Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
08-21 15:31:01.835  1569  1569 W crime.securesm: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
08-21 15:31:01.835  1569  1569 W crime.securesm: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
08-21 15:31:01.835  1569  1569 W crime.securesm: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, linking, allowed)
08-21 15:31:01.837  1569  1569 W crime.securesm: Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
08-21 15:31:01.841  1569  1569 I ApplicationContext: Installed Conscrypt provider: 2
08-21 15:31:02.152  1569  1569 I SQLiteConnection: Database keying operation returned:0
08-21 15:31:02.158  1569  1569 I SQLiteConnection: Database keying operation returned:0
08-21 15:31:02.160  1569  1569 I SignalDatabase: Upgrading database: 120, 153
08-21 15:31:02.504  1569  1569 D AndroidRuntime: Shutting down VM
08-21 15:31:02.505  1569  1569 E AndroidRuntime: FATAL EXCEPTION: main
08-21 15:31:02.505  1569  1569 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 1569
08-21 15:31:02.505  1569  1569 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.IllegalStateException: getDatabase called recursively
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: Caused by: java.lang.IllegalStateException: getDatabase called recursively
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:313)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:273)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.getSignalWritableDatabase(SignalDatabase.kt:186)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.triggerDatabaseAccess(SignalDatabase.kt:281)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.triggerDatabaseAccess(Unknown Source:2)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.getInstance(KeyValueDatabase.java:57)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.getLocalAci(SignalDatabaseMigrations.kt:2731)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:2286)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:159)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:395)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:273)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.getSignalWritableDatabase(SignalDatabase.kt:186)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.triggerDatabaseAccess(SignalDatabase.kt:281)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.LogDatabase$Companion.getInstance(LogDatabase.kt:89)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.kt:41)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:293)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$1$org-thoughtcrime-securesms-ApplicationContext(ApplicationContext.java:149)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext$$ExternalSyntheticLambda14.run(Unknown Source:2)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.AppStartup.execute(AppStartup.java:145)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:207)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
08-21 15:31:02.505  1569  1569 E AndroidRuntime: 	... 8 more
```

This seems to be similar to https://github.com/signalapp/Signal-Android/issues/12147

**Comment by johanw666** [comment]
This is a duplicate from https://github.com/signalapp/Signal-Android/issues/12409

**Comment by johanw666** [comment]
Considering the error it has most probably nothing to do with any changes I made, except for the fact that my fork's apk's don't expire so running such an old version is possible. But updating a forgotten phone with an old installation of the official client would probably also trigger it.
