### ISSUE TITLE
Changing phone number failed

### ISSUE THREAD

**Issue by kaovilai** [signalapp/Signal-Android#12420]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Changing phone number failed on device 2 after having been transferred from device 1 which might've been using number B already.

After transferring to device 2 I put in number A but changed my mind to using number B.

Device 1 may have previously used number B.

So 1B -> 2A -> 2B

### Steps to reproduce
- Transfer from device 1 (Google pixel 6) to device 2 (Samsung Galaxy z flip 4)
- enter phone number A
- change account phone number from A to B
- enter 2FA code sent to number B
- crash

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![Screenshot_20220827_170541_Signal.jpg](https://user-images.githubusercontent.com/11228024/187048014-bbf38cf3-4896-4cb5-b424-4b202e7859b1.jpg)

### Device info

**Device:** Samsung SM-F721U
**Android version:** 12
**Signal version:** 5.47.3

### Link to debug log

https://debuglogs.org/android/5.47.3/6e981682463f9cdf90fd88a0ecbd1e59fea47481479fffb4a6c9f105bc89feb9

**Comment by kaovilai** [comment]
There's retry or leave.. there should at least be revert when SQLite fails during operations like these

**Comment by kaovilai** [comment]
I'm assuming the app will remain unusable until an update arrives where I will try the retry button again. Else I can delete data and start new.

**Comment by fobo66** [comment]
I'm facing the same issue. I receive the code and entered it correctly multiple times, but app always shows the error "Cannot connect to service" or something like that.

[Here](https://debuglogs.org/android/5.48.3/ac68fe82fed6c49046b92a4ef9cdf5bb8b7fb4c138391bb4c56bea802d88da6b) is the debug log that I get. There is one noticeable crash, but not sure if it is related to the phone number change

**Comment by fobo66** [comment]
Seems that the exception above wasn't the root cause. Found something else:

```
09-01 11:50:13.061 31899 32214 I ChangeNumberViewModel: Local and remote numbers match, we can unlock.
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: post verify: 
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:662)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2177)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedSyncPniChangeNumberMessage(SignalServiceMessageSender.java:629)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository.createChangeNumberRequest(ChangeNumberRepository.kt:241)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository.changeNumber$lambda-2(ChangeNumberRepository.kt:64)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository.$r8$lambda$GA2Vzi4QR7-vEt7RIaLlva-7vdQ(Unknown Source:0)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository$$ExternalSyntheticLambda1.call(Unknown Source:6)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.lang.Thread.run(Thread.java:920)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: Caused by: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1734)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1709)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1691)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1680)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1616)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1610)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:633)
09-01 11:50:13.063 31899 31899 W BaseEnterSmsCodeFragmen: 	... 15 more
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: Unable to verify code
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: org.whispersystems.signalservice.api.push.exceptions.UnregisteredUserException: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:662)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2177)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedSyncPniChangeNumberMessage(SignalServiceMessageSender.java:629)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository.createChangeNumberRequest(ChangeNumberRepository.kt:241)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository.changeNumber$lambda-2(ChangeNumberRepository.kt:64)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository.$r8$lambda$GA2Vzi4QR7-vEt7RIaLlva-7vdQ(Unknown Source:0)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.thoughtcrime.securesms.components.settings.app.changenumber.ChangeNumberRepository$$ExternalSyntheticLambda1.call(Unknown Source:6)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at java.lang.Thread.run(Thread.java:920)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: Caused by: org.whispersystems.signalservice.api.push.exceptions.NotFoundException: [404] Not found
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1734)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1709)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1691)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1680)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1616)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1610)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:633)
09-01 11:50:13.064 31899 31899 W BaseEnterSmsCodeFragmen: 	... 15 more
```

I'm pretty sure that my old number that I enter was registered

**Comment by hohwille** [comment]
Here are my submitted logs: https://debuglogs.org/android/5.48.3/ba653d2c9301b2195d802af1ddcc6f45eff0156080a9b6aeea4bd9e23204c93b

**Comment by winkelnp** [comment]
I have the same issue, migrating from a UK number to a German one (same phone)

**Comment by cody-signal** [comment]
Hi folks, looks like there are two different issues being reported in here around change number. 

One that results in a "Error connecting to service"/404 which we should have a fix for in 5.50 and has a workaround: Go to your linked devices and remove any old devices that you no longer use. If you do have devices you still use in that list, make sure they are active and updated. Then try change number again.

The second is the OP post of getting stuck with a SQL constraint. Looking into that now.

**Comment by cody-signal** [comment]
@kaovilai your issue should be fixed in 5.49.x which should start prod rollout today.

**Comment by kaovilai** [comment]
Sounds good thanks!

**Comment by winkelnp** [comment]
> workaround: Go to your linked devices and remove any old devices that you no longer use. If you do have devices you still use in that list, make sure they are active and updated. Then try change number again.

Sorry we must have misunderstood the original post... This workaround did work for me, thanks :)

**Comment by kaovilai** [comment]
Confirm closed by reopening the updated app.

**Comment by hohwille** [comment]
Thanks mates for fixing this. You are real heros. My Signal is working again like a charm and I did not loose any data. 👍

**Comment by lm2lm2** [comment]
Hi,

had same issue

i had a big advantage : automatics backup were setup.
So when this issue occured, i had a j0 plus a j-7 backups
i use rarely signal

i tried tons of things :
-different pin unlock attempts, but no one said "right pin" nor "wrong pin"
-upgrade to the latest version of signal

then i had the idea to take another ungoogled android device : i installed latest version of signal, and "tested" backups. The recent one did not worked. The older one (one week older) worked. just had to do same on the original device.

Then i completely wiped data of my signal app
i opened it again, took "restore" choice, and used my old backup
and then validated my number by sms

everything worked, but it's a real bad signal from a such app..
