### ISSUE TITLE
ForegroundServiceDidNotStartInTimeException logcat/crash after sending videos and swiping away

### ISSUE THREAD

**Issue by rugk** [signalapp/Signal-Android#12422]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I was sending a video and swiping away I got a crash.

### Steps to reproduce
- send three videos to one contact
- immediately swipe away to another app afterwards

**Actual result:** crash
**Expected result:** not crash
### Screenshots

N/A

### Device info

**Device:** Pixel 4 (flame)  
**Android version:** 12, CalyxOS 3.6.0  
**Signal version:** 5.47.3

### Link to debug log

```
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 23990
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{abad951 u0 org.thoughtcrime.securesms/.service.GenericForegroundService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
	at android.app.ActivityThread.access$2700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Full debug log can be shared privately upon request

**Comment by alex-signal** [comment]
Hi! Please feel free to share the debug log with me privately. You can mail it to me at alex at signal dot org, or I can set up a Signal number you can send it to.
