### ISSUE TITLE
Error while starting app: MissingAddressError: Missing address for 1

### ISSUE THREAD

**Issue by Wowol** [signalapp/Signal-Android#12453]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Few seconds after startup, application crashes with error: `MissingAddressError: Missing address for 1`. Full stacktrace:

```
org.thoughtcrime.securesms.recipients.Recipient$MissingAddressError: Missing address for 1
    at org.thoughtcrime.securesms.recipients.Recipient.requireE164(Recipient.java:726)
    at org.thoughtcrime.securesms.crypto.storage.SignalBaseIdentityKeyStore.isTrustedIdentity(SignalBaseIdentityKeyStore.java:132)
    at org.thoughtcrime.securesms.crypto.storage.SignalIdentityKeyStore.isTrustedIdentity(SignalIdentityKeyStore.java:64)
    at org.thoughtcrime.securesms.crypto.storage.SignalServiceAccountDataStoreImpl.isTrustedIdentity(SignalServiceAccountDataStoreImpl.java:71)
    at org.signal.libsignal.internal.Native.SessionBuilder_ProcessPreKeyBundle(Native Method)
    at org.signal.libsignal.protocol.SessionBuilder.process(SessionBuilder.java:93)
    at org.whispersystems.signalservice.api.crypto.SignalSessionBuilder.process(SignalSessionBuilder.java:24)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:2183)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:2158)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1777)
    at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:224)
    at org.thoughtcrime.securesms.jobs.SendReadReceiptJob.onRun(SendReadReceiptJob.java:184)
    at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
    at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
    at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
    at [[ ↑↑ Original Trace ↑↑ ]].(:0)
    at [[ ↓↓ Exception Message ↓↓ ]].(:0)
    at Missing address for 1.(:0)
```

### Steps to reproduce
- Change the number (from one country to another), along with the sim card
- Open the app

**Actual result:** Signal crashes while after starting, preventing even from entering settings - I can't view my data nor copy them to new device.
**Expected result:** Signal don't crash

### Device info
**Device:** Xiaomi Redmi Note 8 Pro
**Android version:** 10
**Signal version:** 5.48.3

### Link to debug log
I can't, since signal crashes 2 seconds after startup and won't allow me to do any action.

**Comment by greyson-signal** [comment]
5.49.3 is currently rolling out to prod and may help. Let me know what happens after you update. thanks!

**Comment by Wowol** [comment]
Hi @greyson-signal,
I've update signal to 5.49.3 - now I don't get this issue right after entering the app - I get this after I click 'settings' (exception is the same, but stacktrace is different):

```
org.thoughtcrime.securesms.recipients.Recipient$MissingAddressError: Missing address for 1
	at org.thoughtcrime.securesms.recipients.Recipient.requireE164(Recipient.java:726)
	at org.thoughtcrime.securesms.components.settings.app.AppSettingsFragment$BioPreferenceViewHolder.bind(AppSettingsFragment.kt:236)
	at org.thoughtcrime.securesms.components.settings.app.AppSettingsFragment$BioPreferenceViewHolder.bind(AppSettingsFragment.kt:224)
	at org.thoughtcrime.securesms.util.adapter.mapping.MappingAdapter.onBindViewHolder(MappingAdapter.java:112)
	at org.thoughtcrime.securesms.util.adapter.mapping.MappingAdapter.onBindViewHolder(MappingAdapter.java:106)
	at org.thoughtcrime.securesms.util.adapter.mapping.MappingAdapter.onBindViewHolder(MappingAdapter.java:45)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:812)
	at android.view.View.layout(View.java:22237)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3300)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2796)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1869)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8024)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
	at android.view.Choreographer.doCallbacks(Choreographer.java:793)
	at android.view.Choreographer.doFrame(Choreographer.java:728)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
	at [[ ↑↑ Original Trace ↑↑ ]].🙂
```

I think this **might** be related to the fact, that signal says that 'device no longer registered' (correct me if I'm wrong) - unfortunately, after I try to register and verify my number, **nothing happens**. I've created a seperate issue with that, here: #12456
