### ISSUE TITLE
Images are not loaded when previously sent from Signal-Desktop while Android app was offline

### ISSUE THREAD

**Issue by fschwa** [signalapp/Signal-Android#12502]
### Bug description
When I send an image or video to someone from the Signal-Desktop app while my phone (with the Android app) is in Airplane mode (meaning: offline), those image or videos are not loaded properly once I exit Airplane mode on the phone bringing Signal online again..

### Steps to reproduce
For me this is reproducible every time on both mobile data and wifi.

- Put your phone in Airplane mode
- Send an image or video to a contact from Signal-Desktop (here on Linux but not sure if that makes a difference)
- Exit Airplane mode

#### Actual result:
- Signal tries to download the image or video into the conversation but does not finish (not even after a day ).
- Sometimes (but not always) messages _from_ that contact do not arrive anymore (other contacts do work)
- Sometimes (but not always) messages _to_ that contact are sent and received but the "received" markers (second check mark) are not shown (other contacts do work)
- If "sometimes" is the case, need to "Delete message for me" to make the conversation with that contact work again.

#### Expected result:
media files should be downloaded properly after client was offline

### Screenshots
Taken hours after exiting Airplane mode.

![signal-loading-image](https://user-images.githubusercontent.com/70687497/194698914-1bd33d69-a887-44b2-87ad-aacf7a30fd26.jpeg)

### Device info
Device: Fairphone 4
Android version: iode 3.1 (20220726-FP4) based on Android 12 / LineageOS 19.1
Signal version: 5.48.3

### App state
Signal messages and calls registered, SMS disabled, passphrase enabled

### Link to debug log
https://debuglogs.org/android/5.48.3/e49611dd401af93c0fddf6ea374cf150c328ef1971a14a25e47cb9a71ccf2d71

**Comment by greyson-signal** [comment]
Hmm, looks like we're hitting weird socket timeouts:

```java
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 Caused by: java.net.SocketTimeoutException: failed to connect to cdn.signal.org/2600:9000:2182:9400:1d:4f32:50c0:93a1 (port 443) from /fd00:1:fd00:1:fd00:1:fd00:1 (port 38470) after 10000ms
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at libcore.io.IoBridge.connect(IoBridge.java:180)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
[5.48.3] [54    ] 2022-10-08 09:58:09.905 GMT+02:00 I BaseJob                 	at java.net.Socket.connect(Socket.java:621)
```

I see you're using a VPN. Does this still happen if you disable the VPN?

**Comment by fschwa** [comment]
I did not consciously run a VPN but I am using TrackerControl, which apparently works by creating a VPN. So I configured it to not watch the Signal app and then the images were loaded immediately. :)

Thanks for the hint in the right direction. :)

(the issue is closed automatically here so if you think the socket timeouts could be handled more gracefully, feel free to reopen)
