### ISSUE TITLE
[ERROR] App doesn't run after restoring backup

### ISSUE THREAD

**Issue by turlyyy** [signalapp/Signal-Android#12552]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x]This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
After restoring backup on new phone signal just crashing when I open app.

### Steps to reproduce
- Create backup
- Restore
- Run app

**Actual result:** crash
**Expected result:** normal work

### Device info

**Android version:** 13
**Signal version:** 5.52.2

### Link to debug log

```
type: crash

org.thoughtcrime.securesms.storage.StorageSyncValidations$UnknownInsertError
	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validateManifestAndInserts(StorageSyncValidations.java:141)
	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validate(StorageSyncValidations.java:35)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:355)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Inferred Trace ↓↓ ]].(:0)
	at org.signal.core.util.concurrent.TracingExecutorService.execute(TracingExecutorService.kt:14)
	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getLive(LiveRecipientCache.java:82)
	at org.thoughtcrime.securesms.recipients.Recipient.live(Recipient.java:148)
	at org.thoughtcrime.securesms.recipients.Recipient.resolved(Recipient.java:177)
	at org.thoughtcrime.securesms.recipients.Recipient.externalGroupExact(Recipient.java:326)
	at org.thoughtcrime.securesms.database.RecipientDatabase.getContactStorageSyncIdsMap(RecipientDatabase.kt:1308)
	at org.thoughtcrime.securesms.database.RecipientDatabase.getContactStorageSyncIds(RecipientDatabase.kt:1269)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.getAllLocalStorageIds(StorageSyncJob.java:421)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:334)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at null.(:0)

```

**Comment by greyson-signal** [comment]
Are you able to share the full debug log?

**Comment by themsay** [comment]
Experiencing same crash trying to restore backup
Android version: 12
Signal version: 5.53.8

**Comment by themsay** [comment]
I was able to restored my backup successful by disabling `Google Play Service` entirely before proceedings to verification.

**Comment by einalex** [comment]
I encountered this error as well:

### Bug description
Signal crashes on each start **after** having successfully moved an account from another phone and number.
So not after restoring a backup and with no play services available.

### Steps to reproduce
- start Signal

**Actual result:** Crashes immediately
**Expected result:** Starts fine
### Device info
**Device:** Google Pixel 7
**Android version:** latest Grapheneos version based on Androind 13
**Signal version:** 6.5.6 from https://signal.org/android/apk/

### debug log
```
type: crash
osVersion: google/panther/panther:13/TQ1A.221205.011/2022121400:user/release-keys
package: org.thoughtcrime.securesms:118100
process: org.thoughtcrime.securesms
processUptime: 1106 + 289 ms

org.thoughtcrime.securesms.storage.StorageSyncValidations$UnknownInsertError
	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validateManifestAndInserts(StorageSyncValidations.java:141)
	at org.thoughtcrime.securesms.storage.StorageSyncValidations.validate(StorageSyncValidations.java:35)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:355)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Inferred Trace ↓↓ ]].(:0)
	at org.signal.core.util.concurrent.TracingExecutor.execute(TracingExecutor.kt:11)
	at org.thoughtcrime.securesms.recipients.LiveRecipientCache.getLive(LiveRecipientCache.java:86)
	at org.thoughtcrime.securesms.recipients.Recipient.live(Recipient.java:147)
	at org.thoughtcrime.securesms.recipients.Recipient.resolved(Recipient.java:176)
	at org.thoughtcrime.securesms.database.GroupTable$GroupRecord$$ExternalSyntheticLambda0.apply(Unknown Source:2)
	at j$.util.stream.R1.accept(SourceFile:0)
	at j$.util.Iterator$-CC.$default$forEachRemaining(SourceFile:0)
	at j$.util.a0.forEachRemaining(SourceFile:0)
	at j$.util.stream.c.A0(SourceFile:0)
	at j$.util.stream.c.S0(SourceFile:0)
	at j$.util.stream.u1.c(Unknown Source:4)
	at j$.util.stream.c.V0(SourceFile:0)
	at j$.util.stream.X1.collect(SourceFile:0)
	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteStoryDistributionList(StorageSyncModels.java:222)
	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:62)
	at org.thoughtcrime.securesms.storage.StorageSyncModels.localToRemoteRecord(StorageSyncModels.java:46)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.buildLocalStorageRecords(StorageSyncJob.java:462)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:336)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at null.(:0)

```

**Comment by greyson-signal** [comment]
@einalex Can you get a full debuglog? I think you'll find that if you put the device in airplane mode that it won't crash, and then you can hit the three-dot menu on the debuglogs screen to save the log as a file. If the crash happens during registration, you can tap the header 8 times to get to the registration screen. Thanks!

**Comment by einalex** [comment]
Yes, airplane mode worked. I think 'submitting' it also worked before the APP crashed. Anyway I attached the log.

**Comment by einalex** [comment]
[signal-log-1671482577524.zip](https://github.com/signalapp/Signal-Android/files/10267554/signal-log-1671482577524.zip)
ah, upload works on the desktop.

@greyson-signal here is the debug log

**Comment by greyson-signal** [comment]
Ah, thank you!

**Comment by Penguin-Guru** [comment]
I just transferred (Signal transfer) from a Pixel 5 to Pixel 7, both running Graphene. When the process finished, the old phone thought it had succeeded and Signal had minimised/crashed on the new phone. Killing the app, clearing the app cache, and restarting the phone did not help. Airplane also did not help, even repeating the aforementioned process with it enabled. I'm going to try restoring from a backup file and will follow up here if the result is different.

**Comment by nicholas-signal** [comment]
> I just transferred (Signal transfer) from a Pixel 5 to Pixel 7, both running Graphene. When the process finished, the old phone thought it had succeeded and Signal had minimised/crashed on the new phone. Killing the app, clearing the app cache, and restarting the phone did not help. Airplane also did not help, even repeating the aforementioned process with it enabled. I'm going to try restoring from a backup file and will follow up here if the result is different.
> 
> I cleared the app storage data, enabled aeroplane mode, then imported from the backup file. This worked. I disabled aeroplane mode once the app asked to confirm my phone number.

Are you able to get a debuglog? Either through the normal channels, or at least use ADB to copy the logcat output.

**Comment by Penguin-Guru** [comment]
@nicholas-signal 

Sorry, I'm not sure why I didn't get an email notification for your comment but I just restored from the backup file and it worked as expected. Is there any data left that you want? I'm not very familiar with Android.

**Comment by nicholas-signal** [comment]
> I just restored from the backup file and it worked as expected.

Glad to hear everything worked! I'll close this issue then.

**Comment by gadicc** [comment]
Just adding a note here in case it helps others.  In my case, I transferred the backup but registered with the wrong phone number afterwards.  Had the same problem with crash on startup, could use the app in aeroplane mode.  Deleted all data, did the transfer again, using the correct phone number for registration, and all working great :tada:
