### ISSUE TITLE
SMS export failed, when retrying - same issue

### ISSUE THREAD

**Issue by PatrykMis** [signalapp/Signal-Android#12561]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
While exporting messages (total something between 16000-16999) near approx. 80% of exporting progress the Signal is crashing. Each time I try again the crash is happening instantly.

**Actual result:** The app crashed with provided stack trace:

```
type: crash
osVersion: google/flame/flame:13/TP1A.221005.002/2022102600:user/release-keys
package: org.thoughtcrime.securesms:114200
process: org.thoughtcrime.securesms

java.lang.NullPointerException
	at org.thoughtcrime.securesms.exporter.SignalSmsExportReader$ExportableMessageIterator.readExportableSmsMessageFromRecord(SignalSmsExportReader.kt:181)
	at org.thoughtcrime.securesms.exporter.SignalSmsExportReader$ExportableMessageIterator.next(SignalSmsExportReader.kt:121)
	at org.thoughtcrime.securesms.exporter.SignalSmsExportReader$ExportableMessageIterator.next(SignalSmsExportReader.kt:83)
	at org.signal.smsexporter.SmsExportService.startExport$lambda-1(SmsExportService.kt:1851)
	at org.signal.smsexporter.SmsExportService.$r8$lambda$tEit1M1A4QqGu66EdUkWT5XDUyI(Unknown Source:0)
	at org.signal.smsexporter.SmsExportService$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at null.(:0)

```

**Expected result:** App should finish exporting and export all messages correctly.

### Device info
**Device:** Google Pixel 4 (flame)
**Android version:** 13.0
**Signal version:** 5.52.5

### Link to debug log
https://debuglogs.org/android/5.52.5/ba6953d057911d98ba1cf6742bea1141cbedc3447f1c6fcf56a3303a8711fd4b)

**Comment by MoralCode** [comment]
Have you looked at #12521?

**Comment by PatrykMis** [comment]
Thanks @MoralCode. Closing as a duplicate of #12526.
