### ISSUE TITLE
Exception when adding a new member to a group

### ISSUE THREAD

**Issue by fr33tux** [signalapp/Signal-Android#12580]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When adding a contact to an existing GV2 (a legacy GV1 that was converted to GV2), two members of that group get an error: "_One member couldn't be added to the group. Do you want to add it now?_". That new person can already see the content of the group, send or receive messages. Only two of thee group members get the issue with that pop-up looping and failing.

The debug log show an exception with that dialog `GroupsV1MigrationSuggestionsDialog`:

```
[6.0.6] [31831] 2022-11-03 13:28:05.337 EDT I Job: [JOB::9926ef74-b7f2-4553-9441-92f2a396555f][MultiDeviceReadUpdateJob] onSubmit() (Time Since Submission: 5 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: null)
[6.0.6] [31831] 2022-11-03 13:28:05.351 EDT I Job: [JOB::9d1c0e32-0542-4b0b-a769-2a8c4a1631a7][SendReadReceiptJob] onSubmit() (Time Since Submission: 12 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: RecipientId::190)
[6.0.6] [31845] 2022-11-03 13:28:05.354 EDT I JobRunner: [JOB::9926ef74-b7f2-4553-9441-92f2a396555f][MultiDeviceReadUpdateJob][3] Running job. (Time Since Submission: 21 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: null)
[6.0.6] [31844] 2022-11-03 13:28:05.359 EDT I JobRunner: [JOB::9d1c0e32-0542-4b0b-a769-2a8c4a1631a7][SendReadReceiptJob][2] Running job. (Time Since Submission: 20 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: RecipientId::190)
[6.0.6] [main ] 2022-11-03 13:28:05.363 EDT D ConversationItemAnimato: Finished running animations.
[6.0.6] [31844] 2022-11-03 13:28:05.370 EDT I UnidentifiedAccessUtil: Unidentified: 1, Other: 0. Types: {UUID_AND_E164=1}
[6.0.6] [31860] 2022-11-03 13:28:05.431 EDT D NotificationFactory: showing summary notification
[6.0.6] [31860] 2022-11-03 13:28:05.446 EDT I DefaultMessageNotifier: threads: 1 messages: 1
[6.0.6] [31845] 2022-11-03 13:28:05.486 EDT I JobRunner: [JOB::9926ef74-b7f2-4553-9441-92f2a396555f][MultiDeviceReadUpdateJob][3] Job finished with result SUCCESS in 132 ms. (Time Since Submission: 153 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: null)
[6.0.6] [31844] 2022-11-03 13:28:05.518 EDT I JobRunner: [JOB::9d1c0e32-0542-4b0b-a769-2a8c4a1631a7][SendReadReceiptJob][2] Job finished with result SUCCESS in 159 ms. (Time Since Submission: 179 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: RecipientId::190)
[6.0.6] [31945] 2022-11-03 13:28:05.598 EDT I ProfileUtil: Updating profile key credential on recipient RecipientId::190, fetching
[6.0.6] [31945] 2022-11-03 13:28:05.679 EDT I ProfileUtil: Got new profile key credential for recipient RecipientId::190
[6.0.6] [main ] 2022-11-03 13:28:05.746 EDT I SimpleProgressDialog: Taking some time. Showing a progress dialog.
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: Permanent failure! Removing these dropped members from the list.
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: org.thoughtcrime.securesms.groups.GroupChangeFailedException: org.whispersystems.signalservice.internal.push.exceptions.GroupPatchNotAcceptedException: StatusCode: 400
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:656)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:639)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:633)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.addMembers(GroupManagerV2.java:353)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManager.addMembers(GroupManager.java:409)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.ui.migration.GroupsV1MigrationSuggestionsDialog.lambda$onAddClicked$3(GroupsV1MigrationSuggestionsDialog.java:78)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.ui.migration.GroupsV1MigrationSuggestionsDialog.$r8$lambda$4tOym9D4E_wW36Eowv_ZiuttLsk(Unknown Source:0)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.ui.migration.GroupsV1MigrationSuggestionsDialog$$ExternalSyntheticLambda4.run(Unknown Source:2)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.SimpleTask.lambda$run$3(SimpleTask.java:87)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.SimpleTask.$r8$lambda$jvZ0-8nsHlQ_qvU-Rex9q6uvOXs(Unknown Source:0)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.SimpleTask$$ExternalSyntheticLambda0.run(Unknown Source:4)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.TracingExecutorService.execute$lambda-0(TracingExecutorService.kt:25)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.TracingExecutorService.$r8$lambda$JWXxcO1P3GzWBfvZk9N5USCLsAo(Unknown Source:0)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.signal.core.util.concurrent.TracingExecutorService$$ExternalSyntheticLambda0.run(Unknown Source:4)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at java.lang.Thread.run(Thread.java:764)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: Caused by: org.whispersystems.signalservice.internal.push.exceptions.GroupPatchNotAcceptedException: StatusCode: 400
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.lambda$static$12(PushServiceSocket.java:2334)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.$r8$lambda$8TP1YqRAKaZu38lRooQqjPTRm-0(Unknown Source:0)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket$$ExternalSyntheticLambda10.handle(Unknown Source:0)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket$ResponseCodeHandler$-CC.$default$handle(PushServiceSocket.java:2298)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket$$ExternalSyntheticLambda10.handle(Unknown Source:0)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeStorageRequest(PushServiceSocket.java:1951)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.patchGroupsV2Group(PushServiceSocket.java:2400)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.whispersystems.signalservice.api.groupsv2.GroupsV2Api.patchGroup(GroupsV2Api.java:168)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitToServer(GroupManagerV2.java:769)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChange(GroupManagerV2.java:745)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	at org.thoughtcrime.securesms.groups.GroupManagerV2$GroupEditor.commitChangeWithConflictResolution(GroupManagerV2.java:650)
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 	... 16 more
[6.0.6] [31945] 2022-11-03 13:28:05.831 EDT W GroupsV1MigrationSugges: 
[6.0.6] [main ] 2022-11-03 13:28:05.846 EDT I ConversationParentFragm: onModified(RecipientId::33) REGISTERED
[6.0.6] [main ] 2022-11-03 13:28:05.850 EDT I ConversationParentFragm: updateDefaultSubscriptionId(null)
[6.0.6] [main ] 2022-11-03 13:28:05.917 EDT D ConversationParentFragm: [presentMessageRequestState] No message request necessary.
[6.0.6] [31836] 2022-11-03 13:28:06.864 EDT I IncomingMessageObserver: Retrieved envelope! 1667496486804
[6.0.6] [31836] 2022-11-03 13:28:06.886 EDT I Job: [JOB::9a96f256-4d52-4211-85bb-d1f3e7b130d0][PushDecryptMessageJob] onSubmit() (Time Since Submission: 20 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited, Queue: __PUSH_DECRYPT_JOB__)
[6.0.6] [31836] 2022-11-03 13:28:06.897 EDT D IncomingMessageObserver: Network: true, Foreground: true, FCM: true, Stay open requests: [], Censored: false, Registered: true, Proxy: false, Force websocket: false
[6.0.6] [31837] 2022-11-03 13:28:06.897 EDT I JobSchedulerScheduler: JobScheduler enqueue of  (0)
[6.0.6] [31836] 2022-11-03 13:28:06.897 EDT D IncomingMessageObserver: Reading message...
```

### Steps to reproduce

Not sure of the actual steps. Just open the group, see that banner, click on it and see it failing/looping.

**Expected result:** The new contact added to the group is seen added to the group from all members.

### Screenshots

![issue_001](https://user-images.githubusercontent.com/5955898/200065418-e6c141ad-40ce-4152-8e05-5bd016106e4a.jpeg)

![issue_002](https://user-images.githubusercontent.com/5955898/200065435-7f506feb-d415-4dcb-ad43-8a68656afb87.jpeg)

### Device info
```
Manufacturer  : LGE
Model         : LG-H870
Product       : lucye_global_com
Screen        : 1440x2672, xxxhdpi (640), 60.00 hz
Font Scale    : 1.0
Android       : 9, API 28 (1930916292597, PKQ1.190522.001)
ABIs          : arm64-v8a, armeabi-v7a, armeabi
```

**Signal version:** 6.0.6

### Link to debug log
https://debuglogs.app/android/6.0.6/0402f0c593e90a35b8f29337c5dbe969ffb258e4fbcad4819eb29918c428896b

**Comment by fr33tux** [comment]
Related to https://github.com/signalapp/Signal-Android/issues/12554

**Comment by fr33tux** [comment]
https://github.com/signalapp/Signal-Android/commit/99a516f8e5575b66db07fd4bdf9496024c8a90cf
