### ISSUE TITLE
Cannot change number

### ISSUE THREAD

**Issue by mhmdanas** [signalapp/Signal-Android#12591]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am unable to change my Signal account's phone number.

### Steps to reproduce
- Go the settings page, then press on "Account" then on "Change phone number"
- Follow the steps to change your phone number

**Actual result:** The app crashes with the following stack trace:
```
FATAL EXCEPTION: GoogleApiHandler
Process: org.thoughtcrime.securesms, PID: 29588
java.lang.IllegalArgumentException: org.thoughtcrime.securesms: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
	at com.google.android.gms.common.api.GoogleApiActivity.zaa(com.google.android.gms:play-services-base@@17.5.0:4)
	at com.google.android.gms.common.GoogleApiAvailability.zaa(com.google.android.gms:play-services-base@@17.5.0:116)
	at com.google.android.gms.common.api.internal.GoogleApiManager.zaa(com.google.android.gms:play-services-base@@17.5.0:252)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.5.0:109)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.5.0:75)
	at com.google.android.gms.common.internal.zai.onConnectionFailed(com.google.android.gms:play-services-base@@17.5.0:2)
	at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(com.google.android.gms:play-services-basement@@17.5.0:6)
	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.5.0:21)
	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(com.google.android.gms:play-services-basement@@17.5.0:11)
	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(com.google.android.gms:play-services-basement@@17.5.0:49)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```
**Expected result:** The app should not crash, and I should be able to change my phone number just fine.

### Device info

**Device:** Galaxy A51
**Android version:** 12
**Signal version:** 6.0.6

### Link to debug log

The app crashes and then restarts, so I don't think there's anything related to the crash in the debug log (though I can provide it if needed).

**Comment by cody-signal** [comment]
Can you provide a full debuglog link please? You can send it to me directly (cody@signal.org) if you do not wish to include it in the GH issue.

**Comment by mhmdanas** [comment]
@cody-signal I shot an e-mail to your side, though again, I think it wouldn't contain anything useful (but I'm not a Signal developer, so I'll stop nagging you about it).

**Comment by greyson-signal** [comment]
We think this is because our Play Services is out of date, fix coming in 6.2, thanks!

**Comment by mhmdanas** [comment]
Can confirm the issue has been fixed, thank you!
