### ISSUE TITLE
Signal crush when randomly input something to "Enter Custom Amount" box on the donate page

### ISSUE THREAD

**Issue by Terrible-Tornado** [signalapp/Signal-Android#12647]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Randomly input something such as word "detail" to "Enter Custom Amount" box on the donate page, and then Signal crush.

### Steps to reproduce
1. Open Signal
2. Enter Settings
3. Click "Donate to Signal"
4. Click "Donate to Signal" button in the middle
5. Set text such as word "detail" to the text box

**Actual result:** Signal crush and fall back to the home page
**Expected result:** Nothing is inputted or prompt that the input is illegal

### Screenshots
<img width="643" alt="image" src="https://user-images.githubusercontent.com/119578731/205249796-38fdbd6d-d462-4cb6-bc80-e12558bf233a.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/119578731/205249862-ec000a8e-60d8-4a4e-adf4-5022d9a05a9a.png">

### Device info
**Device:** Emulator Google Pixel 2
**Android version:** 9.0
**Signal version:** 6.3.3

### Link to debug log
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 28091
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
... 1 more
Caused by: java.text.ParseException: Unparseable number: "detail"
at java.text.NumberFormat.parse(NumberFormat.java:375)
at org.thoughtcrime.securesms.components.settings.app.subscription.donate.DonateToSignalViewModel.setCustomAmount(DonateToSignalViewModel.kt:152)
at org.thoughtcrime.securesms.components.settings.app.subscription.donate.DonateToSignalFragment$displayOneTimeSelection$3.invoke(DonateToSignalFragment.kt:338)
at org.thoughtcrime.securesms.components.settings.app.subscription.donate.DonateToSignalFragment$displayOneTimeSelection$3.invoke(DonateToSignalFragment.kt:326)
at org.thoughtcrime.securesms.components.settings.app.subscription.boost.Boost$SelectionViewHolder$bind$2.invoke(Boost.kt:175)
at org.thoughtcrime.securesms.components.settings.app.subscription.boost.Boost$SelectionViewHolder$bind$2.invoke(Boost.kt:174)
at org.thoughtcrime.securesms.components.settings.app.subscription.boost.Boost$MoneyFilter.afterTextChanged(Boost.kt:318)
at android.widget.TextView.sendAfterTextChanged(TextView.java:9770)
at android.widget.TextView.setText(TextView.java:5739)
at android.widget.TextView.setText(TextView.java:5571)
at android.widget.EditText.setText(EditText.java:122)
at android.widget.TextView.setText(TextView.java:5528)
at android.widget.TextView.performAccessibilityActionInternal(TextView.java:11110)
at android.view.View.performAccessibilityAction(View.java:12053)
at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:711)
at android.view.AccessibilityInteractionController.access$500(AccessibilityInteractionController.java:67)
at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1327)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
... 3 more

**Comment by cody-signal** [comment]
How were you able to put text in there? The keyboard is pretty restrictive to entering anything bug numbers. I can't reproduce this

**Comment by Terrible-Tornado** [comment]
By [https://github.com/xiaocong/uiautomator](url). I often use my apps on computer and I am interested in writing scripts.
