### ISSUE TITLE
Registration after restoring local backup fails

### ISSUE THREAD

**Issue by ByteHamster** [signalapp/Signal-Android#12669]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When transferring my installation to a new phone, I cannot use the "from local file" restore method. The phone number verification after restoring the backup fails with 404 (see logs below).

### Steps to reproduce
- Export backup to file on old device
- Select to import backup on new device
- Enter password and let it import the backup (successfully)
- See phone number verification page
- It automatically types in the code
- Shows error message "Error connecting to the service"
  - Note that I get a different error message when typing a wrong verification code. So the code check itself does work
- To me, it looks like Signal, in addition to restoring the local backup, tries to restore a remote backup (and fails).

### Device info

**Device:** OnePlus 7T
**Android version:** 12L (LineageOS)
**Signal version:** 6.4.2

### Debug log
```
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen: post verify: 
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [404] Response: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.backup.signal.org/v1/token/[redacted]}
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1936)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.getKeyBackupServiceToken(PushServiceSocket.java:1172)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.whispersystems.signalservice.api.KeyBackupService.getToken(KeyBackupService.java:80)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository.getTokenSync(KbsRepository.java:70)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository.lambda$getToken$1(KbsRepository.java:55)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository.$r8$lambda$gQW53DCOOUBv_pjpMCKg0jUs3xk(Unknown Source:0)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository$$ExternalSyntheticLambda1.call(Unknown Source:4)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-10 17:37:30.863 27839 27839 W BaseEnterSmsCodeFragmen:       at java.lang.Thread.run(Thread.java:920)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen: Unable to verify code
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [404] Response: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.backup.signal.org/v1/token/[redacted]}
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:1936)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.whispersystems.signalservice.internal.push.PushServiceSocket.getKeyBackupServiceToken(PushServiceSocket.java:1172)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.whispersystems.signalservice.api.KeyBackupService.getToken(KeyBackupService.java:80)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository.getTokenSync(KbsRepository.java:70)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository.lambda$getToken$1(KbsRepository.java:55)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository.$r8$lambda$gQW53DCOOUBv_pjpMCKg0jUs3xk(Unknown Source:0)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at org.thoughtcrime.securesms.pin.KbsRepository$$ExternalSyntheticLambda1.call(Unknown Source:4)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-10 17:37:30.864 27839 27839 W BaseEnterSmsCodeFragmen:       at java.lang.Thread.run(Thread.java:920)
```

**Comment by cody-signal** [comment]
This has been fixed in 6.5.x which is currently in beta. If you switch to the beta channel and update this would resolve. You can then switch out of the beta and the next prod version will take you back to the main release channel.
