### ISSUE TITLE
Restore Backup crashing

### ISSUE THREAD

**Issue by ScR4tCh** [signalapp/Signal-Android#12671]
### Bug description
I currently was not able start signal after a system update and decided to reinstall and restore. However restoring crashes signal (also tried opting-out beta and restoring) with:

### Device info
**Device:** Fairphone FP3
**Android version:** 12 (Linage 19.1)
**Signal version:** 6.5.2

### Link to debug log
```12-11 08:47:52.720 13781 13924 I RestoreBackupFragment: Starting backup restore.
12-11 08:47:52.723 13781 13795 I OpenGLRenderer: Davey! duration=9223370599914ms; Flags=0, FrameTimelineVsyncId=79022, IntendedVsync=1436924788307, Vsync=1436924788307, InputEventId=0, HandleInputStart=1436934792472, AnimationStart=1436934794503, PerformTraversalsStart=1436935007003, DrawStart=1436935117420, FrameDeadline=1436958121639, FrameInterval=1436934789347, FrameStartTime=16666666, SyncQueued=1436935370909, SyncStart=1436950759399, IssueDrawCommandsStart=1436950868409, SwapBuffers=1436952178878, FrameCompleted=9223372036854775807, DequeueBufferDuration=29844, QueueBufferDuration=519531, GpuCompleted=9223372036854775807, SwapBuffersCompleted=1436953323982, DisplayPresentTime=72057630528635673, 
12-11 08:47:52.730     0     0 I aw8898_mute: mute state=0
12-11 08:47:52.730     0     0 I         : aw8898_smartpa_cfg, flag = 1
12-11 08:47:52.738 13781 13822 D OpenGLRenderer: endAllActiveAnimators on 0x716c111330 (RippleDrawable) with handle 0x707c15cab0
12-11 08:47:52.739  1393  1730 W InputManager-JNI: Input channel object '6fff37 org.thoughtcrime.securesms/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity (client)' was disposed without first being removed with the input manager!
12-11 08:47:52.756  1393  1588 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
12-11 08:47:52.763   701  2753 D audio_hw_primary: start_output_stream: exit
12-11 08:47:52.784  3613  3613 I HK/LatinKbdBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{17a7e97 V.ED..... ......I. 0,0-1080,740 #7f080004 app:id/LatinkeyboardBaseView}
12-11 08:47:52.792  3078 12555 I MediaProvider: Open with lower FS for /storage/emulated/0/Signal/Backups/signal-2022-12-09-03-23-48.backup. Uid: 10030
12-11 08:47:53.540 13781 13924 I libsignal: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
12-11 08:47:53.549 13781 13924 I FullBackupImporter: Dropping table: part
12-11 08:47:53.550 13781 13924 I FullBackupImporter: Dropping table: identities
12-11 08:47:53.552 13781 13924 I FullBackupImporter: Dropping table: drafts
12-11 08:47:53.553 13781 13924 I FullBackupImporter: Dropping table: push
12-11 08:47:53.554 13781 13924 I FullBackupImporter: Dropping table: groups
12-11 08:47:53.555 13781 13924 I FullBackupImporter: Dropping table: recipient
12-11 08:47:53.557 13781 13924 E SQLiteLog: (1) no such table: main.msl_message in "DROP TABLE IF EXISTS recipient"
12-11 08:47:53.560 13781 13924 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-11 08:47:53.560 13781 13924 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 13781
12-11 08:47:53.560 13781 13924 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
12-11 08:47:53.560 13781 13924 E AndroidRuntime: Caused by: net.zetetic.database.sqlcipher.SQLiteException: no such table: main.msl_message (code 1): , while compiling: DROP TABLE IF EXISTS recipient
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:922)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.prepare(SQLiteConnection.java:533)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteSession.prepare(SQLiteSession.java:592)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteProgram.<init>(SQLiteProgram.java:64)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteStatement.<init>(SQLiteStatement.java:37)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1992)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1901)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.dropAllTables(FullBackupImporter.java:282)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:90)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:73)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-11 08:47:53.560 13781 13924 E AndroidRuntime:        ... 4 more
12-11 08:47:53.560 13781 13924 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at android.os.AsyncTask$4.done(AsyncTask.java:415)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.lang.Thread.run(Thread.java:920)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException: Caused by: net.zetetic.database.sqlcipher.SQLiteException: no such table: main.msl_message (code 1): , while compiling: DROP TABLE IF EXISTS recipient
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:922)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteConnection.prepare(SQLiteConnection.java:533)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteSession.prepare(SQLiteSession.java:592)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteProgram.<init>(SQLiteProgram.java:64)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteStatement.<init>(SQLiteStatement.java:37)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1992)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1901)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.dropAllTables(FullBackupImporter.java:282)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:90)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:73)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-11 08:47:53.560 13781 13924 E SignalUncaughtException:       ... 4 more```

**Comment by ScR4tCh** [comment]
Addition: going back to 6.4.2-117400 works (restoring, app also starts and seems to function as expected)
```

```
