### ISSUE TITLE
Attachments often fail to send

### ISSUE THREAD

**Issue by hmenke** [signalapp/Signal-Android#12695]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

When sharing multiple items from the gallery, the entire batch often fails at an unknown point.

<details>

<summary><code>adb logcat</code></summary>

```
12-26 11:57:40.267 23243 23302 W AttachmentTable: null
12-26 11:57:40.267 23243 23302 W AttachmentTable: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part2978291222329552006.mms: open failed: ENOENT (No such file or directory)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at libcore.io.IoBridge.open(IoBridge.java:574)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:28)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.database.AttachmentTable.getDataStream(AttachmentTable.java:1060)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachmentStream(AttachmentTable.java:212)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:74)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.getAttachmentFor(AttachmentUploadJob.java:192)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:145)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
12-26 11:57:40.267 23243 23302 W AttachmentTable: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at libcore.io.Linux.open(Native Method)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7764)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	at libcore.io.IoBridge.open(IoBridge.java:560)
12-26 11:57:40.267 23243 23302 W AttachmentTable: 	... 10 more
12-26 11:57:40.268 23243 23302 W BaseJob : [JOB::b194f969-761a-4160-a4ec-dd9e36889c24][AttachmentUploadJob] Encountered a failing exception. (Time Since Submission: 866 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: null)
12-26 11:57:40.268 23243 23302 W BaseJob : org.thoughtcrime.securesms.jobs.AttachmentUploadJob$InvalidAttachmentException: java.io.IOException: No stream for: AttachmentId::(12310, 1672051155940)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.getAttachmentFor(AttachmentUploadJob.java:221)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:145)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
12-26 11:57:40.268 23243 23302 W BaseJob : Caused by: java.io.IOException: No stream for: AttachmentId::(12310, 1672051155940)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachmentStream(AttachmentTable.java:214)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:74)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.getAttachmentFor(AttachmentUploadJob.java:192)
12-26 11:57:40.268 23243 23302 W BaseJob : 	... 4 more
12-26 11:57:40.268 23243 23302 W BaseJob : Caused by: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part2978291222329552006.mms: open failed: ENOENT (No such file or directory)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at libcore.io.IoBridge.open(IoBridge.java:574)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:28)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.database.AttachmentTable.getDataStream(AttachmentTable.java:1060)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachmentStream(AttachmentTable.java:212)
12-26 11:57:40.268 23243 23302 W BaseJob : 	... 6 more
12-26 11:57:40.268 23243 23302 W BaseJob : Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at libcore.io.Linux.open(Native Method)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7764)
12-26 11:57:40.268 23243 23302 W BaseJob : 	at libcore.io.IoBridge.open(IoBridge.java:560)
12-26 11:57:40.268 23243 23302 W BaseJob : 	... 10 more
```

</details>

### Steps to reproduce
- Press (+) next to the message field
- Select Gallery
- Select multiple items and press send

**Actual result:** All items are sent without problems.
**Expected result:** "Send failed" and a red exclamation mark appears. The items are not sent.

### Device info

**Device:** Google Pixel 4a
**Android version:** 13 (TQ1A.221205.011.2022122000)
**Signal version:** 6.6.3

**Comment by greyson-signal** [comment]
Would you be able to provide a full debuglog? It'll let us see what's happening from the time you press the send button, which can help us figure out what's happening with the attachment.

**Comment by hmenke** [comment]
I haven't sent a large batch of media recently. As soon as it happens again I'll provide a debug log.

**Comment by hmenke** [comment]
So far I was not able to reproduce this. Maybe it was fixed in the meantime, so I'm closing this for now. Should this happen again, I might reopen this with an accompanying debug log.

**Comment by hmenke** [comment]
It happened again: https://debuglogs.org/android/6.7.6/dd9c90a04acb1a77ea8df803e88f214702676b7be0fb771a41f6d01ef82039da

**Comment by hmenke** [comment]
Is anyone ever going to fix this will attachments just remain permanently broken in Signal?
