### ISSUE TITLE
Unable to receive/send messages on mobile using VPN

### ISSUE THREAD

**Issue by p43b1** [signalapp/Signal-Android#12709]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is unable to receive/send messages on mobile Network using VPN. It works perfectly on WiFi using VPN.

### Steps to reproduce
- Use Signal under a Wifi network using a VPN
- Deactivate WiFi
- Let the VPN automatically reconnect under the mobile network
- Try send/receive messages, they will be stuck
- Reactivate WiFi
- Let the VPN reconnect to the WiFi network
- Sending receiving messages will work again

**Actual result:** Unable to receive or send messages on mobile network unless I deactivate the VPN.

[6.6.3] [33586] 2023-01-03 16:39:18.035 GMT+01:00 W BackgroundMessageRetrie: Strategy failed: RestStrategy (20406 ms elapsed)
[6.6.3] [33586] 2023-01-03 16:39:18.035 GMT+01:00 I BackgroundMessageRetrie: Attempting strategy: RestStrategy (20406 ms elapsed)
[6.6.3] [33467] 2023-01-03 16:39:20.810 GMT+01:00 I InAppScheduler: Triggering a job retry.
[6.6.3] [33483] 2023-01-03 16:39:20.821 GMT+01:00 I JobRunner: [JOB::48606d2e-c7a4-4631-ad33-b4ac1f92d417][DirectoryRefreshJob][1] Running job. (Time Since Submission: 726533 ms, Lifespan: Immortal, Run Attempt: 9/10, Queue: StorageSyncingJobs)
[6.6.3] [33483] 2023-01-03 16:39:20.828 GMT+01:00 I DirectoryRefreshJob: DirectoryRefreshJob.onRun()
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: Failed to retrieve messages. Resetting the SignalServiceMessageReceiver.
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: **org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: SSL handshake timed out**
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1790)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1701)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:567)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:202)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.messages.RestStrategy.enqueuePushDecryptJobs(RestStrategy.java:87)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.messages.RestStrategy.execute(RestStrategy.java:41)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.executeBackgroundRetrieval(BackgroundMessageRetriever.java:112)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.retrieveMessages(BackgroundMessageRetriever.java:83)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.messages.BackgroundMessageRetriever.retrieveMessages(BackgroundMessageRetriever.java:46)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmJobService.lambda$onStartJob$0(FcmJobService.java:52)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmJobService.$r8$lambda$nKXBLHXoN18pQ3mKXDouufEcxFU(Unknown Source:0)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.gcm.FcmJobService$$ExternalSyntheticLambda0.run(Unknown Source:4)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.signal.core.util.concurrent.TracingExecutorService.execute$lambda$0(TracingExecutorService.kt:25)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.signal.core.util.concurrent.TracingExecutorService.$r8$lambda$Z2aONVyEhhkvutd9DlyQ6a4W4zM(Unknown Source:0)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.signal.core.util.concurrent.TracingExecutorService$$ExternalSyntheticLambda0.run(Unknown Source:4)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at java.lang.Thread.run(Thread.java:919)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: Caused by: java.net.SocketTimeoutException: SSL handshake timed out
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:385)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:225)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.net.DeviceTransferBlockingInterceptor.intercept(DeviceTransferBlockingInterceptor.java:38)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.net.DeprecatedClientPreventionInterceptor.intercept(DeprecatedClientPreventionInterceptor.java:36)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.net.RemoteDeprecationDetectorInterceptor.intercept(RemoteDeprecationDetectorInterceptor.java:22)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.thoughtcrime.securesms.net.UserAgentInterceptor.intercept(UserAgentInterceptor.java:20)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at okhttp3.RealCall.execute(RealCall.java:93)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:1783)
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 	... 17 more
[6.6.3] [33586] 2023-01-03 16:39:38.355 GMT+01:00 W RestStrategy: 

**Expected result:** Receive or send messages on mobile network using the VPN without deactivating it.
### Device info
Manufacturer   : Xiaomi
Model          : Redmi Note 7
Product        : lavender_eea
Screen         : 1080x2131, xxhdpi (440), 60.00 hz
Font Scale     : 1.0
Animation Scale: 1.0
Android        : 10, API 29 (V12.5.1.0.QFGEUXM, QKQ1.190910.002 V12.5.1.0.QFGEUXM)
ABIs           : arm64-v8a, armeabi-v7a, armeabi
Memory         : 47M (5.79% free, 512M max)
Memclass       : 256
MemInfo        : availMem: 1378 mb, totalMem: 3736 mb, threshold: 216 mb, lowMemory: false
OS Host        : c4-miui-ota-bd172.bj
RecipientId    : RecipientId::5
ACI            : ********-****-****-****-**********2c
Device ID      : 1
Censored       : false
Network Status : [isOnVpn: true, isMetered: true]
Data Saver     : DISABLED
Play Services  : true
FCM            : true
BkgRestricted  : false
Locale         : en_US
Linked Devices : true
First Version  : 546
Days Installed : 1280
Build Variant  : playProdRelease
Emoji Version  : 7 (xhdpi)
RenderBigEmoji : false
Telecom        : false
User-Agent     : Signal-Android/6.6.3 Android/29
App            : Signal 6.6.3 (1185, 118502) (cb0e7ade141f) 
Package        : org.thoughtcrime.securesms (doDiFGKPO1r)

### Link to debug log
[https://debuglogs.org/android/6.6.3/ddf410718a3dc0cff6c7c42bd52d106e5302fdd9fb0543b71ce75300beb9c508](https://debuglogs.org/android/6.6.3/ddf410718a3dc0cff6c7c42bd52d106e5302fdd9fb0543b71ce75300beb9c508)

**Comment by nicholas-signal** [comment]
Hello, based on your debuglog, it appears that the VPN is timing out when Signal is attempting to establish an SSL handshake. This is typically caused by unusual network conditions. Glad to hear it works off-VPN, and I would suggest seeing if it reproduces with other VPN providers.

**Comment by EphDoering** [comment]
I tried and failed to reproduce this issue with OpenVPN on Android. Messages sent without any issues during all three test phases. (on vpn over WiFi, still on VPN over LTE, still on VPN over WiFi)

**Comment by nicholas-signal** [comment]
It sounds like the issue lies with that first VPN's configuration. I would suggest following up with them. Nevertheless, thank you for your thorough bug report!
