### ISSUE TITLE
Signal does not start, failing migration after a long time of device being powered off

### ISSUE THREAD

**Issue by liori** [signalapp/Signal-Android#12730]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't start. This is on a device that I haven't been using for more than half a year.

### Steps to reproduce
- Try launching the application.

**Actual result:** I'm getting the «Signal keeps stopping» popup.
**Expected result:** Signal starts.

### Device info

**Device:** Moto G7 Play
**Android version:** Android 11 (LineageOS, a custom build)
**Signal version:** Signal-Android-website-prod-universal-release-6.7.6.apk

### Link to debug log

Log captured by `adb logcat`:
```
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: org.thoughtcrime.securesms.migrations.MigrationJob$FailedMigrationError: java.lang.IllegalArgumentException: Cannot bind argument at index 2 because the index is out of range.  The statement has 1 parameters.
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.migrations.MigrationJob.run(MigrationJob.java:46)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.migrations.ProfileSharingUpdateMigrationJob.run(ProfileSharingUpdateMigrationJob.java:13)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: Caused by: java.lang.IllegalArgumentException: Cannot bind argument at index 2 because the index is out of range.  The statement has 1 parameters.
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteProgram.bind(SQLiteProgram.java:234)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteProgram.bindString(SQLiteProgram.java:172)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:206)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:51)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1611)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1530)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$rawQuery$5(SQLiteDatabase.java:350)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$ZL2y7ZoQKy_coM3aTsqtfCMjGSA(Unknown Source:0)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda14.run(Unknown Source:6)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:95)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:350)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.RecipientTable.markPreMessageRequestRecipientsAsProfileSharingEnabled(RecipientTable.kt:3314)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.migrations.ProfileSharingUpdateMigrationJob.performMigration(ProfileSharingUpdateMigrationJob.java:38)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	at org.thoughtcrime.securesms.migrations.MigrationJob.run(MigrationJob.java:42)
01-15 16:29:15.117 14034 14083 E SignalUncaughtException: 	... 3 more
```

**Comment by greyson-signal** [comment]
Ah, look like an old migration broke. This will be resolved in 6.9. Apologies!
