### ISSUE TITLE
Restore from backup fails with "Incorrect backup passphrase"

### ISSUE THREAD

**Issue by jeromio** [signalapp/Signal-Android#12743]
- [X ] I have searched open and closed issues for duplicates
- [X ] I am submitting a bug report for existing functionality that does not work as intended
- [X ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Attempts to restore chat backup fail with "Incorrect Passphrase" error yet correct (verified) passphrase was used. 
This has now happened to me 3 times over the span of 2 years. Same reproduction steps each time. I have never been able to restore a backup 🙁.

### Steps to reproduce
 - Created a backup on "old" phone. 
 - Copied the 30 digit passphrase. 
 - Used the "verify passphrase" functionality and got an affirmative response from the app. 
 - Copied the backup file to a PC and then to the "new" phone. 
 - On 1st start up of Signal app, chose the Restore function.
 - Selected backup file.
 - Entered correct, verified, 30 digit passphrase.
 - Received "Incorrect passphrase" error. (Repeated the last 2 steps 20 or so times out of desparation)

**Actual result:** No restore happens: all saved messages lost forever
**Expected result:** Successfully restored all messages contained in the backup

### Device info
**Device:** Google Pixel 3, Samsung Flip3, Samsung Flip4
**Android versions:** 11,12,12.1
**Signal version:** 6.8.3

### Link to debug log
Not possible to get debug log from restore process since it can only be accessed *before* the actual app is launched for the 1st time.

**Comment by cody-signal** [comment]
Hi there, sorry you are encountering this. You can get a debuglog in the restore flow by tapping on the title of the screen 8 times.

When entering the passphrase are you typing it manually or pasting it?

**Comment by AJolly** [comment]
@cody-signal Is that debuglog saved anywhere if Signal crashes? I've got a backup that's failing to import for me.  I made it before resetting my phone, the password is correct, but import fails/crashes signal about 5200 messages in.  Trying to find whatever logs I can so I can file a bug report.

**Comment by cody-signal** [comment]
Yes, the logs are persisted through a crash. So you can do the same and tap on the title of the screen eight times after starting the app after the crash.

**Comment by gotgot1995** [comment]
Thank goodness, I'm not the only one going through the same issue.  :pray: 

I proceeded exactly as @jeromio did and got the same result. For the record, I have entered the passphrase manually, not copied/pasted (try a bunch of times desperately too with no luck).

**Comment by cody-signal** [comment]
@gotgot1995 Can you tap on the title of any of the registration screens eight times after starting the app to get debuglogs and submit that here?

**Comment by gotgot1995** [comment]
But of course @cody-signal. Here you go.

[signal-log-1682021126912.zip](https://github.com/signalapp/Signal-Android/files/11290191/signal-log-1682021126912.zip)

**Comment by le-dawg** [comment]
Exactly the same happens to me when transferring from OnePlus 6 to OnePlus Nord 2. Both phones not rooted. The import step doesn't even start. I entered the passphrase both possible ways: reading it either row by row and left to right or column by column and left to right. 

Neither works. 

This is , eh , ridiculous. This is not a cryptography problem i think.

**Comment by le-dawg** [comment]
FWIW: I am trying to import a backup from version 6.30.4 into version 6.6.3

**Comment by le-dawg** [comment]
FYI:

I was able to resolve this issue by:

- updating the OLD phone Signal app to the newest available
- deleting and reinstalling the signal app on the NEW phone
- following the instructions

It appears that there was a backward compatibility issue.

**Comment by imyxh** [comment]
I have the same issue, and I too have verified in-app that the passphrase is correct.

I'm now in this weird limbo where I don't want to set up Signal again, because then I won't be able to import my old messages later, but I still need to use Signal to talk to my contacts.

Nothing in the log seems particularly relevant but here it is anyway: [signal-log-1700633612372.zip](https://github.com/signalapp/Signal-Android/files/13434355/signal-log-1700633612372.zip)

Could we get this issue re-opened and unmarked as wontfix?

**Comment by studiok87** [comment]
Same problem here, updated the firmware of Asus Zenfone with a factory reset and can't open my last 3 backups (which are all I have). When I switch to home after "Incorrect passphrase" popup, open Signal again and skip restore, enter my phone number etc and then try verifying the backup code in Settings -> Chat -> Backup, it verifies correctly.
It's the same passphrase I used for such a long time and that worked every 6 moths or so when I reset to factory and update the phone.

Signal Version 6.41.3, Android 13 

Might there be any problems that Signal Desktop is still installed on a Linux Mint partition (not booted from that since I have the restoring problem)? Signal Debug log says "Linked Devices: false"

![Screenshot](https://github.com/signalapp/Signal-Android/assets/155073743/d0d2b1e5-d3fc-45a4-bdb7-bd805d87024f)

**Comment by kocherjj** [comment]
I have this same issue. My phone service provider told me I had to factory reset my phone as a troubleshooting step when we could not resolve a calling issue.
I backed up Signal, verified the passphrase, factory reset my phone, and now it rejects the passphrase, which I saved to my password manager before verifying so I know it is is exact. I have tried both manually typing it in and copy/pasting. In both cases I get the 'Incorrect Passphrase' message. Does this mean 5 years of message history is gone forever?

**Comment by greyson-signal** [comment]
@imyxh 
> I have the same issue, and I too have verified in-app that the passphrase is correct.

Really strange, we supposedly log the exception we hit, but it's not in your normal logs. I see this in your logcat at the same time:

```
11-22 01:12:47.396  5866  5936 W KeyStore: android.os.ServiceSpecificException:  (code 7)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.os.Parcel.createException(Parcel.java:2357)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:2340)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:2282)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:988)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:233)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:222)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:165)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:147)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:82)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:51)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at org.thoughtcrime.securesms.backup.BackupPassphrase.set(BackupPassphrase.java:47)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:290)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:281)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-22 01:12:47.396  5866  5936 W KeyStore: 	at java.lang.Thread.run(Thread.java:923)
```

But this is made by the system, not us, and reports online indicate this particular error is usually something that the KeyStore will log but not throw. I can't tell just by looking at the logs. If this _is_ the issue, there's not much we do besides provide a better error message. We need the KeyStore for many app operations.

Regardless, ya'll are likely hitting some error that is _not_ an incorrect passphrase and we're just rendering a bad error message, but there is some other problem with the backup here that we'll need to find out, but that can only be debugged with logs.

@kocherjj @studiok87 Please share logs.

**Comment by studiok87** [comment]
Sorry for answering that late, too busy at the moment, but I'll send you debug and logcat via mail. Or anything else I can provide (non-rooted phone)? Seems like many more users have this problem -> #13333

**Comment by giammin** [comment]
having the same problem...
this issue is not resolved and should be reopened

**Comment by pabloscloud** [comment]
I have the same issue. I lost my backup for the thousand time now. Remove file backups if it won't work...

**Comment by DDPF02** [comment]
I have the same issue....

![signal-log-1717428673731.zip](https://github.com/user-attachments/files/15536300/signal-log-1717428673731.zip)

**Comment by studiok87** [comment]
Dear Signal-devs, two months ago I've sent you logs twice and all I got was two e-mails with this:
"Hi there, I’d like to help you. Did you see our previous email? Did you start using [Signal](https://signal.org/install)?"
Is that a joke? If it's a serious question, my answer is: yes, I started using Signal since it was published and I regret it!

**Comment by PeteSapai** [comment]
This seems to have happened to me as well. I have a screenshot from 2021-06-06 with the passphrase, I'm 99% certain it should still be the same one (I have no idea why it wouldn't be). I reinstalled the OS yesterday, installed Signal just now and tried to restore the backup; I'm 100% certain I entered the correct 30 numbers, but I get "incorrect backup passphrase" thrice.

**Comment by oversanne** [comment]
Hello, I have the same issue here too! I hope to find a solution quickly as... currently I don't know if I should wait for a solution or start from scratch. Thanks for your help :)

**Comment by kocherjj** [comment]
I would recommend moving on. No one seems to be seriously interested in resolving this. I lost years of history and do not intend to trust signal with my data any longer unless/until they give their users back control of our own data by allowing local unencrypted backups.

**Comment by mark8819** [comment]
> I would recommend moving on. No one seems to be seriously interested in resolving this. I lost years of history and do not intend to trust signal with my data any longer unless/until they give their users back control of our own data by allowing local unencrypted backups.

This is exactly why I stopped using Signal and so did my friends. If they implemented local unencrypted backups, it would be the best messaging app.

Without it, I risk losing all my chats with friends and family, which is unacceptable

**Comment by studiok87** [comment]
> This is exactly why I stopped using Signal and so did my friends. If they added the option of local unencrypted backups, it would be the best messaging app overall
> 
> Without it, I risk losing all my chats with friends and family, which is unacceptable

Yes, beside the automated answer I quoted from some months ago ("Did you start using Signal?") I never got an answer after sending my logs, also not for other stuff like the captcha problems with Signal Desktop. 
Talking about security: as long as I can't choose the install folder on Windows and have to trust BitLocker, every "it's more secure bla bla" is just a joke. As long as Signal is installed in Windows-System-partition, nobody needs encrypted backups...

**Comment by 00Martin** [comment]
I also lost my conversations. I couldn't verify the passphrase on the old app since I have reset the phone it was on, but I know for a fact that it was the correct passphrase, I took a screenshot of it...

**Comment by kcorbridge** [comment]
I have this issue as well.   Screen captured the passphrase and entered it manually a dozen times, I don't think I entered it incorrectly that many times....  I had to do a factory reset on the phone and now cannot restore critical messages. I have them on my laptop so have stopped using signal on my phone since I cannot afford to lose the information in those messages.

**Comment by Mitsu13Ion** [comment]
Same issue here on a 1yo backup

**Comment by Superslub** [comment]
Same issue here on a "backup" done 12h ago ...

**Comment by AnanazFrutti** [comment]
Same issue here

**Comment by erdnuesse** [comment]
Same. The restore function is absolute hot garbage. It just never works on reinstallations, phone transfers, or after setting it up with restoring after primary setup. Idk how a messaging application can be this user unfriendly. In my line I live by 'backups are non-existent if the restore doesn't work / has never been tested' 
And no one can sell me by the fact that a few media files and json, would be hard to encrypt and decrypt by passphrase alone, no, somehow device binding is necessary. 
I riddle you this: what good is a backup function, if it drives ppl to other apps? Just remove the goddarn feature, because now I now have 1.5 GB of trashed data I always thought were safe, that I can never restore. 
Good job.

**Comment by AdnanHodzic** [comment]
Same issue ... altough I have Signal app installed on Linux laptop which is linked to backup I'm trying to restore.

**Comment by francoisao** [comment]
Hello,

I have 1 phone, I had some free time and wanted to do a full factory reset. After some Googling, I found some articles ([like this](https://blog.afeld.me/migrating-signal-history-between-android-devices-fc2d5a40769a)) explaining how to proceed with Signal and backup in such a case.

I copy-pasted the passphrase to my computer to be sure to not fail the registration. The passphrase is said to be incorrect by the app, with the latest Signal version on the store (7.47.2). (See the log : [signal-log-1752521726405.zip](https://github.com/user-attachments/files/21221612/signal-log-1752521726405.zip))

I tried to install an old APK (the oldest I could find was 7.21.4), there is no message at all about failure to import the backup, but it fails too. [signal-log-1752521967507.zip](https://github.com/user-attachments/files/21221628/signal-log-1752521967507.zip)

Because the message is different this time, I guess somewhere in there is some explanation to the issue.

But I'm not really a dev…

Unfortunately I don't know which version I had on my previous installation, since the phone has been reset completely. Maybe, a quick workaround for the upcoming versions of Signal, would be to write inside the backup, in a format readable by humans, the version of signal used. This way, we could reinstall the same and work from there, probably? And not loose everything :s

**Comment by imyxh** [comment]
this feature really should just be removed for now, or a warning message added

**Comment by CapitaineToinon** [comment]
In my case, my backup was corrupted. I wish it gave a different error message when that's the case. I copied the backup I had on my drive directly through USB instead to my phone and it worked.

**Comment by geoffroy-noel-ddh** [comment]
Similar problem here. Installed signal, chose to restore a backup from file, enter the passphrase, then it progressively reads messages from it, until it reaches around 11000 messages and stop abruptly with a temporary message saying the passphrase is incorrect.

**If the passphrase is incorrect how can Signal read 11000 messages?**

**If it is incorrect how can signalbackup-tools read the exact same file (using the exact same passphrase) to the end on my pc, without error and export all my messages on a sqlite file?**

The error message from the Signal doesn't make sense. It looks like a very poor experience. When you develop a secure messaging app and invite people to record years of important conversations on it, the least you can do as developer for your users is to test your restore process and provide more robust and bug-free experience. The app doesn't provide a useful or meaningful message allowing me to understand the problem.

**Comment by kroche98** [comment]
I had the same problem. Despite retyping the passphrase nearly a dozen times (and being absolutely certain it was the correct passphrase), I kept getting "Incorrect backup passphrase." Eventually I just threw up my hands, paid for a 1 month subscription to the "premium" backup service, backed up the old phone, restored on the new phone from that backup, and then cancelled the subscription 10 minutes later.

**Comment by PeteSapai** [comment]
Oh, FFS! I decided to test my backupphrase (because I'm about to mess around with Magisk), so I copy-pasted the key to signal from the key that was created in August. I still have the screenshot and it is 100% the correct one. Result: "passphrase was not correct." If something had happened to my phone I would've lost the Signal history because this backup passphrase check is just broken.

Can you please, _please_ give us an option to disable this security feature and just have us create a local backup without passphrase until this is properly fixed? (If someone can get to my backup, which is on the SD card, they can get to my Signal messages too, so that security is useless to me anyway.)

And while you're at it: I would like an option to copy the passphrase from Signal when turning on the backup feature. Why would you make us copy it manually, increasing chances of copying the wrong code?

**Comment by 1Eyed** [comment]
Same here as of 31 March 2026, v8.4.1.
Tried copy-paste and manual and got the same error.
Deleted the backup and created a new one. Same error.

**Comment by Chandre21** [comment]
Same here. I have now done 5 different backups with 3 different new keys. When i create the key it verifies and says it's ok. Seconds later on the new device it's not ok anymore. Please solve this or at least give us the option to do a non-passphrase backup. This has been an issue for 3 years as it seems. Please do something. It is an essential feature.

**Comment by greyson-signal** [comment]
Unfortunately, the user-facing error of the passphrase not being correct is likely a red herring. I think an exception was being thrown that was being misinterpreted as an incorrect passphrase at the UI level. It's likely that you're hitting some other problem while restoring the backup.

@Chandre21 Are you using the new directory style backup format? This was released in the last month or so, and should be a lot better. If you're using now-legacy single-file format with a purely numeric key, you should be able to upgrade to the new format that uses a 64-character alphanumeric key and exports many files in a directory. Regardless, sharing a log would be helpful.

**Comment by Chandre21** [comment]
I have now gotten it to work. I got the prompt to switch to the new 64 character key before trying to restore, so yes @greyson-signal , I was using it. I dont know if the issue was me pointing to Signal Backups folder instead of the folder where Signal Backups is stored or if it was related to nextcloud, as i backup directly to a nextcloud folder to keep the files safe in my nas.
I should say nextcloud backups complete successfully and they appeared on the restore process correctly. I could even see the older backups in the selection dialog.
I would guess it's not the folder issue but if it was it should be made clearer on where to point because the backups appeared on both occasions.

**Comment by greyson-signal** [comment]
We should theoretically allow you to point at either folder, and we should just sort of work regardless. If you're restoring from Nextcloud, I wonder if we just hit some sort of general IO error and misreported it in the UI. Did you pick a Nextcloud location directly when choosing where to save your backup, or did you choose a local folder that is synced to Nextcloud via some background process?

**Comment by Chandre21** [comment]
I picked the nextcloud folder directly on the location dialog

**Comment by jan-paulus** [comment]
Any update on this? Did anyone find a workaround?

**Comment by studiok87** [comment]
> Same here. I have now done 5 different backups with 3 different new keys. When i create the key it verifies and says it's ok. Seconds later on the new device it's not ok anymore. Please solve this or at least give us the option to do a non-passphrase backup. This has been an issue for 3 years as it seems. Please do something. It is an essential feature.

☝️ THIS!
After losing all my messages of five years or more in 2023, I just migrated everything from my dad to his new phone and voila...incorrect passphrase. Old phone stuck in a bootloop. So now he's loosing also all messages. Three godamn years later. I regret every donation I made... Dear Signal devs, this sucks that much and paying for a full cloud backup does not solve this!

**Comment by mtang-signal** [comment]
Hi, for this issue, could you get us a debuglog by tapping on the title of the screen 8 times? That'd help us with investigating this.

**Comment by studiok87** [comment]
No, he was just visiting and I had to finish his phone so he can use it normal. So it's too late now, I configured Signal then without any backup, so everything is gone. I tried recovering with signalbackuptools, but same errors I had with mine in 2023, no chance to recover.

**Comment by kocherjj** [comment]
As someone who works in, plays with, and passionately supports data sovereignty and open source software that returns control of individuals data to those individuals, it's impossible to take seriously any continued pretense that the developers of Signal are actually interested in resolving this issue.

The real problem here is that Signal will not allow a user to save an unencrypted local export of their own personal message history for use as they see fit.

The numerous and repeated disasters of folks like me losing years of data forever due to this refusal demonstrate the need for this, but for true data sovereignty this fundamental requirement exists even in the absence of all these permanent data loss events.

The continued focus on the symptom and asking for logs and 'details' shows that there is no interest at all in solving the underlying issue, which is that Signal does NOT allow users of this software control or ownership of their own personal data.

I have moved on from Signal with regret for the years of communication with loved ones that are now lost to me forever, and the donations I made to support its development when I was still ignorant of this massive flaw. I have stopped recommending it to anyone and apologized to those I once convinced to get onboard when I believed in it.

I realize this is free software and the developers technically owe me and all their other current or former users nothing at all, but many will come to this software because it is advertised as a way to take back control of their digital life from mega corporations, and it isn't, it takes it AWAY from those corps, but it doesn't take it BACK, and that is not honestly explained anywhere in the documentation.

**Comment by greyson-signal** [comment]
@kcorbridge 

> The real problem here is that Signal will not allow a user to save an unencrypted local export of their own personal message history for use as they see fit.

If it helps, we do, in fact, allow you to save an unencrypted local export. Settings > Chats > Export chat history (although we have plans to move it to a different settings screen in the near future).

The old backup format was very brittle and prone to failure. It was one of the reasons we developed the new local backup format, which should be much more reliable (in addition to being faster and using much less space). This ticket has a long history with other duplicate bugs filed along the way, and our ticket hygiene isn't the best, so it wasn't always communicated here what changes or improvements we made. But we indeed did fix plenty of bugs related to this over the years, including extra validation steps on export that drastically reduced the number of reported issues.

And then around the start of this year, we started working on that new format, and we had to choose how to spend our limited resources: fixing bugs with the old format, or focusing on the new one. We chose to focus on the new one, which left this ticket unresponsive for a bit.

I do think that the number of issues with this format has gone way down, but we haven't been very aggressive about converting people to it (it requires user interaction because the password has to change). But we may choose to get more aggressive soon to kick people off of the old one.

We absolutely care about backups, and I'm sorry you had a bad experience. We'll continue to improve in this area.

**Comment by ThreeSixes** [comment]
Same issue as everyone else. Phone broke, but I created a backup on the desktop version since I was still able to use it. I copied and pasted the recovery key into a password manager, double and triple checked the copy/paste of 64 characters. All looks good. Copy the backup to the replacement device. Manually type the passphrase 5 times. I got the invalid passphrase error every time. Copy and pasted it from the password manager. Same error. I deleted the backup from the new device and copied it from the desktop again directly. Same problem typing the code and copy/pasting it from the password manager. I can't use the desktop app now because I have to link it to the new device that I can't set up because I'm not able to restore my backup.  I can't restore later if I reset my message history. This is an extremely awful experience. What are the next steps?

Edit: Re-installing the app and repeating the process didn't work. Debug logs were generated, but show a generic passphrase couldn't restore the backup error in the log section with no other exceptions or notable data around then.

**Comment by greyson-signal** [comment]
@ThreeSixes Everyone else was using an old backup format. If you created the backup on desktop, you'd be using the new format. Can you share the debuglog link? Otherwise I can't do much.
