### ISSUE TITLE
Building 6.11.0 playProdDebug fails

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#12777]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Building 6.11.0 playProdDebug fails.
Building is successful at least to this commit: Store & submit spam reporting token from server. 
Included the next commit "[Introduce Wire for proto codegen.](https://github.com/signalapp/Signal-Android/commit/a91a13cead03078025651c666b8aee10356084c4)" building fails. 

```
Task :Signal-Android:dexBuilderPlayProdDebug
AGPBI: {"kind":"error","text":"Type org.thoughtcrime.securesms.emoji.protos.JumbomojiItem is defined multiple times:
/home/1234/StudioProjects/Signal-Android/app/build/tmp/kotlin-classes/playProdDebug/org/thoughtcrime/securesms/emoji/protos/JumbomojiItem.class,
/home/1234/StudioProjects/Signal-Android/app/build/intermediates/javac/playProdDebug/classes/org/thoughtcrime/securesms/emoji/protos/JumbomojiItem.class",
"sources":[{"file":"/home/1234/StudioProjects/Signal-Android/app/build/tmp/kotlin-classes/playProdDebug/org/thoughtcrime/securesms/emoji/protos/JumbomojiItem.class"}],"tool":"D8"}

AGPBI: {"kind":"error","text":"Type org.thoughtcrime.securesms.emoji.protos.JumbomojiItem$Builder is defined multiple times:
/home/1234/StudioProjects/Signal-Android/app/build/tmp/kotlin-classes/playProdDebug/org/thoughtcrime/securesms/emoji/protos/JumbomojiItem$Builder.class,
/home/1234/StudioProjects/Signal-Android/app/build/intermediates/javac/playProdDebug/classes/org/thoughtcrime/securesms/emoji/protos/JumbomojiItem$Builder.class",
"sources":[{"file":"/home/1234/StudioProjects/Signal-Android/app/build/tmp/kotlin-classes/playProdDebug/org/thoughtcrime/securesms/emoji/protos/JumbomojiItem$Builder.class"}],"tool":"D8"}

org.gradle.workers.WorkerExecutionException: There were multiple failures while executing work items
	at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:269)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:249)
	at com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate.doProcess(DexArchiveBuilderTaskDelegate.kt:227)
	at com.android.build.gradle.internal.tasks.DexArchiveBuilderTask.doTaskAction(DexArchiveBuilderTask.kt:255)
	at com.android.build.gradle.internal.tasks.NewIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:69)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.internal.tasks.NewIncrementalTask.taskAction(NewIncrementalTask.kt:46)
	at jdk.internal.reflect.GeneratedMethodAccessor3020.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	[...]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Cause 1: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:339)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.lambda$waitForItemsAndGatherFailures$2(DefaultAsyncWorkTracker.java:130)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:321)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:304)
	[...]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
        ......
```

**Comment by bme13** [comment]
Think I run into the same multiple defined error. Running a build clean fixed it.

**Comment by alex-signal** [comment]
We've started switching proto generation over to Wire (https://github.com/square/wire) and some old files can end up hanging around. Cleaning your build is the right path forward.
