### ISSUE TITLE
Automatic Chat Backup Not Working

### ISSUE THREAD

**Issue by kgSignal** [signalapp/Signal-Android#12794]
Signal stopped automatically producing a chat backup over a week ago. My last backup I initiated myself on Tuesday. 

Pixel 7Pro
Android 13 on February Security Patch
Signal Version 6.11.7

https://debuglogs.org/android/6.11.7/44b6a6dfade4e0791c07e681407e4087df55160fed376fc58a366eb230a55459

**Comment by AlertSubject** [comment]
Is fixed in the latest beta
Will just be a matter of a few days maybe until it'll work for you again

If it doesn't work then I suggest posting a debug log here

**Comment by itandy** [comment]
> Is fixed in the latest beta Will just be a matter of a few days maybe until it'll work for you again
> 
> If it doesn't work then I suggest posting a debug log here

I'm using Android 12 and Signal version is also 6.11.7. I found the daily backup is missing intermittently. Do you think it's the same issue which has already been fixed in latest beta?

**Comment by AlertSubject** [comment]
> > Is fixed in the latest beta Will just be a matter of a few days maybe until it'll work for you again
> > 
> > If it doesn't work then I suggest posting a debug log here
> 
> I'm using Android 12 and Signal version is also 6.11.7. I found the daily backup is missing intermittently. Do you think it's the same issue which has already been fixed in latest beta?

I believe this was fixed in 6.12

**Comment by HigH-HawK** [comment]
I am having the same issue.

Samsung Galaxy S22 Ultra
Android 13 February 2023 security patch
Signal version 6.12.5

https://debuglogs.org/android/6.12.5/2088046c3af6194e820f9f69e34e26c2867ac84ea940696326ec54b724e39aa5

**Comment by Mrshiat** [comment]
Same issue here.

After the recent update the backup worked one time.

**Comment by cody-signal** [comment]
Thanks all, we're looking into it.

**Comment by itandy** [comment]
Now using 6.12.5 but still automatic backup didn't work last night. It looks like my issue is related to whether my phone is plugged in to AC or not. Every time it's plugged in, backup fails.

**Comment by nicholas-signal** [comment]
> It looks like my issue is related to whether my phone is plugged in to AC or not. Every time it's plugged in, backup fails.

Since 2020, Signal automatic backups [only run when charging](https://github.com/signalapp/Signal-Android/blame/89b0167fd2d8b69a7b293e911743963608ec1040/app/src/main/java/org/thoughtcrime/securesms/jobs/LocalBackupJob.java#L62). Would you mind submitting a debuglog so we can diagnose the specific issue?

**Comment by Herohtar** [comment]
> Signal automatic backups only run when charging

I don't know if it was a bug, but that hasn't been true on my phone more recently (past few months or so).

Although, backups haven't run at all since the 19th due to this bug.

**Comment by nicholas-signal** [comment]
> I don't know if it was a bug, but that hasn't been true on my phone more recently (past few months or so).

Backup jobs do behave differently for Android 10+ vs. Android 9 and below; the code path I quoted for you is from Android 9 and below devices.

If you are able to submit a debug log, we can help solve this bug: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by itandy** [comment]
> > It looks like my issue is related to whether my phone is plugged in to AC or not. Every time it's plugged in, backup fails.
> 
> Since 2020, Signal automatic backups [only run when charging](https://github.com/signalapp/Signal-Android/blame/89b0167fd2d8b69a7b293e911743963608ec1040/app/src/main/java/org/thoughtcrime/securesms/jobs/LocalBackupJob.java#L62). Would you mind submitting a debuglog so we can diagnose the specific issue?

Last night my phone was plugged in for charging and no backup file was generated again. Here is the debug log. Thanks!

https://debuglogs.org/android/6.13.3/85977f74792b46a1e204fba0089207ec5541be90d05d7d6068f2d7b55567d544

**Comment by HigH-HawK** [comment]
It looks like the `ChargingConstraint` is not working as intended. Looking at the logs it looks like this:

```
========== CONSTRAINTS ==========
CellServiceConstraint         : true
NetworkConstraint             : true
NetworkOrCellServiceConstraint: true
ChargingConstraint            : false
WebsocketDrainedConstraint    : true
NotInCallConstraint           : true
AutoDownloadEmojiConstraint   : true
SqlCipherMigrationConstraint  : true
```

So if I'm not misunderstanding, the `ChargingConstraint` stays `false` regardless of the phone being on charge or not.

**Comment by Mrshiat** [comment]
My signal backups aren't working still, but if i check charging constraint it shows as true when it's plugged in

**Comment by itandy** [comment]
> > I don't know if it was a bug, but that hasn't been true on my phone more recently (past few months or so).
> 
> Backup jobs do behave differently for Android 10+ vs. Android 9 and below; the code path I quoted for you is from Android 9 and below devices.
> 
> If you are able to submit a debug log, we can help solve this bug: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

FYI, last night my phone was NOT plugged in and this morning a successful backup was found.

https://debuglogs.org/android/6.13.3/f7dcbe3cf3546666a9da605bcb87868dab5c37d40af1cb3a2c4c3fe0e1f30ce1

**Comment by Mrshiat** [comment]
My phone was plugged in last night, no backup. Tried setting it for a time this morning when it's not plugged in, and it did run a backup.

**Comment by kgSignal** [comment]
Interesting with the charging constant! I left my phone off the wireless charger (Pixel Stand 2) last night and it created a backup.

**Comment by kgSignal** [comment]
Sorry! First time really continuing here and the interface (on mobile at least) made it seem like I had to close as resolved or understood in order to post a comment...

As with others I left my phone off my wireless charger (Pixel Stand 2) and it created a backup as well.

**Comment by LeicesterTriangle** [comment]
I see the following in Signal 6.12.6: no backups as scheduled. 
- changing the backup time causes Signal to back up immediately, and this completes successfully. I'd assume this means all attachments are readable and OK, and that the backup location is writable, etc. 
- I have now twice found a successful backup, as scheduled, when the phone was charging and the Signal app was closed.
- I have *not* found a backup when the phone was charging, and the Signal app was open.

**Comment by Herohtar** [comment]
So apparently the backup eventually ran at least once; Signal shows that the last backup was Thursday (March 2nd). However, that also means it hasn't run since then.

I tried "changing" the backup time by opening the dialog and hitting Ok without actually changing the time and Signal immediately started taking a backup. Not sure what that means, but that seems like incorrect behavior. Definitely not expected.

https://debuglogs.org/android/6.12.6/0e99ca1bcec3fcdaad9fe815cfd51ef0260240acc99a2693f2bac4aaab2cbdb5

**Comment by LeicesterTriangle** [comment]
I can confirm the following in Signal, now 6.13.6: backups as scheduled fail if the app is open. 
- app closed at the time the backup is scheduled: successful backup.
- app open at the time of the successful backup:  *no* backup.  Changing the backup time starts an immediate backup; this is successful.

**Comment by LeicesterTriangle** [comment]
Signal 6.13.6, and the above is consitently reproducible. The message "Already at the max instance count. " for the backup log seems to be common to all failures...

>03-13 02:00:05.087   418   586 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 0 Progress: 81/100 determinate
>03-13 02:00:05.106   418   586 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 0 Progress: 82/100 determinate
>03-13 02:00:05.125   418   586 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 0 Progress: 83/100 determinate
>03-13 02:00:05.261   418   433 I crime.securesms: Background concurrent copying GC freed 624201(26MB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 121us,61us total 110.470ms
>03-13 02:00:05.345   418   586 I GenericForegroundServic: handleReplace() ChannelId: backups_v2  Id: 0 Progress: 84/100 determinate
>03-13 02:00:05.356   418   418 I PersistentAlarmManagerL: [LocalBackupListener] onReceive(null)
>03-13 02:00:05.358   418   418 I PersistentAlarmManagerL: [LocalBackupListener] onAlarm(): scheduled: 1678669200000 actual: 1678669205357
>03-13 02:00:05.360   418   570 W JobController: [JOB::41287f8b-e54f-4bb4-837c-d4cb0e51b122][LocalBackupJobApi29] Canceling while running. (Time Since Submission: 5058 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
>03-13 02:00:05.361   418   570 W JobController: [JOB::9b1836a6-d5fd-4097-acbf-8f1ea3630b0a][LocalBackupJobApi29] Already at the max instance count. Factory limit: 1, Queue limit: -1. Skipping. (Time Since Submission: 3 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
>03-13 02:00:05.384   418   418 I PersistentAlarmManagerL: [LocalBackupListener] scheduling exact alarm for: 1678755600000 hasManagerPermission: true
>03-13 02:00:05.393   418   586 W LocalBackupJobApi29: Backup cancelled
>03-13 02:00:05.601   418   586 W LocalBackupJobApi29: Backup failed. Deleted temp file
>03-13 02:00:05.628   418   586 I GenericForegroundServic: Stopping foreground service id=0
>03-13 02:00:05.640   418   418 I GenericForegroundServic: handleStop()
>03-13 02:00:05.641   418   418 I GenericForegroundServic: Last request. Ending foreground service.
>03-13 02:00:05.641   418   586 W BaseJob : [JOB::41287f8b-e54f-4bb4-837c-d4cb0e51b122][LocalBackupJobApi29] Encountered a failing exception. (Time Since Submission: 5335 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
>03-13 02:00:05.641   418   586 W BaseJob : org.thoughtcrime.securesms.backup.FullBackupExporter$BackupCanceledException
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.backup.FullBackupExporter.throwIfCanceled(FullBackupExporter.java:276)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportTable(FullBackupExporter.java:403)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.backup.FullBackupExporter.internalExport(FullBackupExporter.java:191)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.backup.FullBackupExporter.export(FullBackupExporter.java:141)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:143)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:32)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
>03-13 02:00:05.641   418   586 W BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
>03-13 02:00:05.642   418   586 W JobRunner: [JOB::41287f8b-e54f-4bb4-837c-d4cb0e51b122][LocalBackupJobApi29][3] Failing because the job was canceled. (Time Since Submission: 5340 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)
>03-13 02:00:05.643   418   586 W JobRunner: [JOB::41287f8b-e54f-4bb4-837c-d4cb0e51b122][LocalBackupJobApi29][3] Job failed. (Time Since Submission: 5341 ms, Lifespan: Immortal, Run Attempt: 1/3, Queue: __LOCAL_BACKUP__)

**Comment by LeicesterTriangle** [comment]
6.13.7 doesn't fix this. 
The backup was scheduled for 03-15 02:00, started, aborted soon after. 
Changing the time of the backup triggers an immediate backup; this is successful, and verifies successfully. 
Log of the aborted backup:
<https://debuglogs.org/android/6.13.7/c454f52e12d630334d3519cd367ade6f8c8264094021e3864bc99deb7e0e4848>

**Comment by LeicesterTriangle** [comment]
Seems fixed in 6.14.4! 
Signal updated to 6.14.4 only yesterday (though beta-tester, and apparently skipping 6.14.3). I left the app open and phone on the charger: These are circumstances under which it would fail reliably previously -- and it worked! Scheduled backup created...
