### ISSUE TITLE
Can't (re)register: "You've made too many attempts to register this number"

### ISSUE THREAD

**Issue by mrzapp** [signalapp/Signal-Android#12834]
- [x] I have searched open and closed issues for duplicates (there are some, but their solutions are not applicable)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The registration flow fails, telling me I have made too many attempts to register the number.

I have no fake app store, FCM shim or mock services installed. I have tried switching off my VPN, using a LineageOS version with Google Play Services and using Molly/Molly FOSS, but the issue persists.

### Steps to reproduce
- Flash a fresh LineageOS ROM to Waydroid (with or without GAPPS, doesn't seem to matter)
- Install Signal using the APK on the [Signal website](https://signal.org/android/apk/)
- Try to register the device
- Confirm that the entered number is correct
- Confirm that you are not using Google Play Services
- Confirm that you're a human by clicking on images generated by AI :roll_eyes: 
- Confirm that the entered number is correct *AGAIN*
- Confirm that you are not using Google Play Services *AGAIN*

**Actual result:**  
I get an error message saying "You've made too many attempts to register this number. Please try again in (number that gets bigger every time registration fails)"

**Expected result:**  
I receive an SMS to my phone and I can type in the code

### Screenshots
![image](https://user-images.githubusercontent.com/2747428/224296987-ae997a7e-cec1-42c4-80a7-8cee838bc3c4.png)

### Device info
**Device:** Waydroid 1.4.0
**Android version:** 11
**Signal version:** 6.13.6

### Link to debug log
As Signal won't even let me past the first screen, I can only provide the relevant `logcat`:

```
03-10 10:39:14.501  2480  2480 I EnterPhoneNumberFragmen: Unable to collect necessary data to enter skip flow, returning to normal
03-10 10:39:14.501  2480  2480 I EnterPhoneNumberFragmen: FCM is not supported, using no SMS listener
03-10 10:39:14.503  2480  2480 I AccountValues: Setting push registered: false
03-10 10:39:14.503  2480  2480 I AccountValues: java.lang.Throwable
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.keyvalue.AccountValues.setRegistered(AccountValues.kt:303)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.lambda$requestVerificationCode$10(EnterPhoneNumberFragment.java:280)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.$r8$lambda$WGT27_vWweIdZZJAosa47SPLeug(Unknown Source:0)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment$$ExternalSyntheticLambda17.accept(Unknown Source:2)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSubscribe(SingleDoOnSubscribe.java:60)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSubscribe(SingleDoOnSuccess.java:48)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.onSubscribe(SingleObserveOn.java:57)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:68)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:68)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSubscribe(SingleFlatMap.java:68)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSubscribe(SingleMap.java:51)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:29)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:35)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:37)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4799)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4768)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.requestVerificationCode(EnterPhoneNumberFragment.java:282)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.handleRequestVerification(EnterPhoneNumberFragment.java:258)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.lambda$onE164EnteredSuccessfully$6(EnterPhoneNumberFragment.java:217)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.$r8$lambda$0JvqUiI-DRWYCXZYAhY_VkWOBL4(Unknown Source:0)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment$$ExternalSyntheticLambda20.accept(Unknown Source:8)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at rxdogtag2.DogTagSingleObserver.lambda$onSuccess$3(DogTagSingleObserver.java:63)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at rxdogtag2.DogTagSingleObserver.$r8$lambda$XHPr6lQHRHXcw_CKIYStMAqfnNo(Unknown Source:0)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at rxdogtag2.DogTagSingleObserver$$ExternalSyntheticLambda1.run(Unknown Source:4)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at rxdogtag2.RxDogTag.guardedDelegateCall(RxDogTag.java:219)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at rxdogtag2.DogTagSingleObserver.onSuccess(DogTagSingleObserver.java:62)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onSuccess(SingleOnErrorReturn.java:82)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at android.os.Handler.handleCallback(Handler.java:938)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at android.os.Looper.loop(Looper.java:223)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at android.app.ActivityThread.main(ActivityThread.java:7665)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-10 10:39:14.503  2480  2480 I AccountValues: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-10 10:39:14.503  2480  2518 D IncomingMessageObserver: Network: true, Foreground: true, FCM: true, Stay open requests: [], Censored: false, Registered: false, Proxy: false, Force websocket: false
03-10 10:39:14.994  2480  2480 I EnterPhoneNumberFragmen: Unable to request sms code due to rate limit
```

**Comment by albirs** [comment]
exact same problem here:
Device: OnePlus 6
Android version: LineageOS 20.0-20230307
Signal version: 6.13.6

i dont know its the same error like #12830 and descibed her https://github.com/signalapp/Signal-Android/issues/12506#issuecomment-1279991793

in the Community there are the same problem on this version in tests: https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-6-13-release/51700/108

Is there any way to remove own phone number from the "waiting-list"?

**Comment by Tsi-Napah** [comment]
Same issue, lineageos 19 without gapps on sony xperia xa2

**Comment by cody-signal** [comment]
Please try on 6.14.2 when it's available to you. Just went to beta.

**Comment by Tsi-Napah** [comment]
OK will do, thanks

**Comment by mrzapp** [comment]
Fabulous! It works for me now.

@Tsi-Napah and @albirs, how about you? You can download the APK from APKMirror, if you are not using the Play Store.

**Comment by Tsi-Napah** [comment]
Unfortunately not yet, the error message changed to "connect connect to the service" and the phone number is now blocked for another 4:30 hours. I will re-try in a zone with better 4G coverage...

**Comment by Jab2870** [comment]
Just wanted to add I am having the same issue. Android 13 but no play services.

**Comment by albirs** [comment]
> Fabulous! It works for me now.
thanks @mrzapp ... !  the APKMirror version 6.14.2 works for me too!!

**Comment by Tsi-Napah** [comment]
Finally it worked with better coverage.

Thank you very much Signal dev team!

**Comment by mrzapp** [comment]
Latest version seems to have solved the issue, so closing it for now

**Comment by ploum** [comment]
I’m affected by this bug and, on three different times, I’ve managed to actually receive an SMS. The bad part is that it was not enough: the SMS code was not recognized and registration failed.

**Comment by mrzapp** [comment]
> I’m affected by this bug and, on three different times, I’ve managed to actually receive an SMS. The bad part is that it was not enough: the SMS code was not recognized and registration failed.

That's probably best reported as a new issue with the exact error response you're getting as the title

**Comment by Bourjois** [comment]
> Please try on 6.14.2 when it's available to you. Just went to beta.

This fixed the issue for me. Thank you!
