### ISSUE TITLE
Crash when trying to register

### ISSUE THREAD

**Issue by J0nnyMak0** [signalapp/Signal-Android#12844]
When trying to register a new account on Signal app on Android, it asks me for my phone number. When I enter the phone number and proceed to receive sms, I get a crash:
```
type: crash
osVersion: google/bluejay/bluejay:13/T2B3.230109.009/2023031500:user/release-keys
package: org.thoughtcrime.securesms:122607
process: org.thoughtcrime.securesms
processUptime: 14762 + 209 ms

java.util.NoSuchElementException: No value present
 at org.thoughtcrime.securesms.registration.fragments.EnterPhoneNumberFragment.requestVerificationCode(EnterPhoneNumberFragment.java:282)
 at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
 at [[ ↓↓ Original trace ↓↓ ]].(:0)
 at j$.util.Optional.get(Unknown Source:9)
 at org.thoughtcrime.securesms.registration.RegistrationSessionProcessor.pushChallengeTimedOut(RegistrationSessionProcessor.kt:43)
 at org.thoughtcrime.securesms.registration.viewmodel.BaseRegistrationViewModel.lambda$getValidSession$3(BaseRegistrationViewModel.java:289)
 at org.thoughtcrime.securesms.registration.viewmodel.BaseRegistrationViewModel.$r8$lambda$BqkeWausZ7-0k4qoIQGfzOcBPHA(Unknown Source:0)
 at org.thoughtcrime.securesms.registration.viewmodel.BaseRegistrationViewModel$$ExternalSyntheticLambda6.accept(Unknown Source:4)
 at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:54)
 at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:65)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:55)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
 at [[ ↑↑ Original Trace ↑↑ ]].(:0)
 at [[ ↓↓ Exception Message ↓↓ ]].(:0)
 at No value present.(:0)
```
`

**Comment by cody-signal** [comment]
Not sure which app version you are on, but if you update to 6.13.8 or 6.14.3 it should fix the issue.

**Comment by J0nnyMak0** [comment]
> Not sure which app version you are on, but if you update to 6.13.8 or 6.14.3 it should fix the issue.

Thianks! I was on 6.13.7.
