### ISSUE TITLE
Forwarding a Signal sticker to a story - Send failed

### ISSUE THREAD

**Issue by Sgn-32** [signalapp/Signal-Android#12887]
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Forwarding a Signal sticker to a story ends up with "Send failed"

### Steps to reproduce
- Forward a sticker to a story

**Actual result:** "Send failed"
**Expected result:**
a) The sending does not fail, or
b) do not allow forwarding of stickers to stories

### Screenshot

![Screenshot_1681049732](https://user-images.githubusercontent.com/49990901/230777962-859ed0cc-3a47-4b84-82fd-d979e034d34f.png)

### Device info

**Signal version:** 6.17.1

```
PushDistributionListSen org.thoughtcrime.securesms           W  [JOB::e98f9889-fd16-4db4-b98f-210bcdc983df][PushDistributionListSendJob] 1681048901623 (Time Since Submission: 476 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited, Queue: RecipientId::1::MEDIA)
                                                                                                    org.thoughtcrime.securesms.transport.UndeliverableMessageException: No attachment on non-text story.
                                                                                                    	at org.thoughtcrime.securesms.jobs.PushDistributionListSendJob.deliver(PushDistributionListSendJob.java:216)
                                                                                                    	at org.thoughtcrime.securesms.jobs.PushDistributionListSendJob.onPushSend(PushDistributionListSendJob.java:181)
                                                                                                    	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:110)
                                                                                                    	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:42)
                                                                                                    	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
                                                                                                    	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
                                                                                                    	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
ThreadTable             org.thoughtcrime.securesms           W  Unable to find snippet message for thread 6
```

**Comment by alex-signal** [comment]
We don't support sending stickers to stories, just adding stickers to an image. Thanks for the report!

**Comment by Sgn-32** [comment]
Forwarding stickers to stories disabled with https://github.com/signalapp/Signal-Android/commit/93228f4be789a17655a7d1224e0a34c64921a981  in 6.19 beta
