### ISSUE TITLE
java.io.IOException: Backup stream does not start with header!

### ISSUE THREAD

**Issue by threeeye** [signalapp/Signal-Android#12929]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A few weeks ago my backup started failing with "Bad attachment id", I found the bad files and deleted them (although I don't know why files from 2 years ago are suddenly starting to fail in backups...).
After deleting the files, the backup fails with a new error "Backup stream does not start with header!"
Here is some of the log (let me know if you need the full log):

```
[6.18.4] [127  ] 2023-05-03 12:15:27.090 EDT D FullBackupExporter: Exporting table: payments
[6.18.4] [127  ] 2023-05-03 12:15:27.091 EDT D FullBackupExporter: Exporting table: pending_pni_signature_message
[6.18.4] [127  ] 2023-05-03 12:15:27.092 EDT D FullBackupExporter: Exporting table: push
[6.18.4] [127  ] 2023-05-03 12:15:27.092 EDT D FullBackupExporter: Exporting table: reaction
[6.18.4] [127  ] 2023-05-03 12:15:27.144 EDT D FullBackupExporter: Exporting table: remapped_recipients
[6.18.4] [127  ] 2023-05-03 12:15:27.145 EDT D FullBackupExporter: Exporting table: remapped_threads
[6.18.4] [127  ] 2023-05-03 12:15:27.146 EDT D FullBackupExporter: Exporting table: remote_megaphone
[6.18.4] [127  ] 2023-05-03 12:15:27.152 EDT D FullBackupExporter: Exporting table: sticker
[6.18.4] [127  ] 2023-05-03 12:15:28.225 EDT D FullBackupExporter: Exporting table: storage_key
[6.18.4] [127  ] 2023-05-03 12:15:28.227 EDT D FullBackupExporter: Exporting table: story_sends
[6.18.4] [127  ] 2023-05-03 12:15:28.686 EDT D FullBackupExporter: [Backup] table::avatar_picker: 0  table::call_link: 0  table::recipient: 87  table::thread: 8  table::message: 1740  table::call: 2  table::cds: 48  table::chat_colors: 0  table::distribution_list: 0  table::distribution_list_member: 0  table::donation_receipt: 1  table::drafts: 2  table::emoji_search: 0  table::group_membership: 4  table::group_receipts: 81  table::groups: 1  table::identities: 28  table::mention: 0  table::message_fts: 0  table::msl_payload: 112  table::msl_message: 114  table::msl_recipient: 83  table::notification_profile: 0  table::notification_profile_allowed_members: 0  table::notification_profile_schedule: 1  table::one_time_prekeys: 0  table::part: 139685  table::payments: 1  table::pending_pni_signature_message: 1  table::pending_retry_receipts: 0  table::push: 0  table::reaction: 52  table::remapped_recipients: 1  table::remapped_threads: 1  table::remote_megaphone: 6  table::sender_key_shared: 0  table::sender_keys: 0  table::sessions: 0  table::signed_prekeys: 0  table::sticker: 1072  table::storage_key: 3  table::story_sends: 2  prefs: 7  key_values: 12  avatars: 438  total: 143593
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: Unable to verify backup
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: java.io.IOException: Backup stream does not start with header!
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.<init>(BackupRecordInputStream.java:53)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.BackupVerifier.verifyFile(BackupVerifier.kt:23)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.verifyBackup(LocalBackupJobApi29.java:200)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:150)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[6.18.4] [127  ] 2023-05-03 12:15:28.812 EDT W LocalBackupJobApi29: 
[6.18.4] [127  ] 2023-05-03 12:15:28.814 EDT D LocalBackupJobApi29: [backup-export] backup-create: 144138  backup-verify: 125  total: 144263
[6.18.4] [main ] 2023-05-03 12:15:29.514 EDT W FrameRateTracker: Bad frame! Took 466 ms (27 dropped frames, or 2.14 FPS)
[6.18.4] [127  ] 2023-05-03 12:15:29.601 EDT W LocalBackupJobApi29: Backup failed. Deleted temp file
[6.18.4] [127  ] 2023-05-03 12:15:29.602 EDT I BackupUtil: Deleting older backups
```

### Device info

**Device:** T-Mobile REVVL 6 pro
**Android version:** 12
**Signal version:** 6.18.4

### Link to debug log

https://debuglogs.org/android/6.18.4/c8b39b33259eea28fbf16c3c9be0a1d99351cd10920d8d4622bbfc28b5087d87

**Comment by cody-signal** [comment]
Hi there, do you know if you the storage you are trying to save your backup to is formatted as fat32? It's likely you're maxing out the file size supported by fat32 which is 4gb.

**Comment by cody-signal** [comment]
Interesting. Let us know how it goes!

**Comment by threeeye** [comment]
Update:
It was in fact the SD Card.
Backing up to internal and/or to new SD Card worked with no issues.
