### ISSUE TITLE
App crashes immediately upon launch

### ISSUE THREAD

**Issue by cgranade** [signalapp/Signal-Android#12955]
After the May 17, 2023 beta Channel update, the Signal app on my Samsung S22 Ultra crashes immediately after each launch, with no error message shown. The behavior persists through a reboot of the phone.

I recognize this is not a lot of information to go on, but I'm not sure how to collect better logs given that no error message is displayed. Please let me know what other information would be helpful to provide, thank you!

**Comment by cgranade** [comment]
Much obliged! I'm away from my desktop for a while, so I'll collect that ASAP when i get back, then.

**Comment by aggym** [comment]
I have the same issue. Galaxy S22 Ultra.

**Comment by cgranade** [comment]
Output of `adb logcat` after capturing a crash (everything except the crash itself elided):

```
5-18 12:12:15.381 19759 19805 E AndroidRuntime: FATAL EXCEPTION: signal-bounded-1
05-18 12:12:15.381 19759 19805 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 19759
05-18 12:12:15.381 19759 19805 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: call_tmp.call_id, call_tmp.peer | ExtraMessage: null
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1993)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.migration.V193_BackCallLinksWithRecipient.migrate(V193_BackCallLinksWithRecipient.kt:63)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:243)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:170)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:302)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:195)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:305)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(Unknown Source:2)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.lambda$onOpen$0(KeyValueDatabase.java:99)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.$r8$lambda$jefACyoHK4h3lvPI5zn7iBuWxuI(Unknown Source:0)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase$$ExternalSyntheticLambda0.run(Unknown Source:0)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
05-18 12:12:15.381 19759 19805 E AndroidRuntime: 	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: call_tmp.call_id, call_tmp.peer | ExtraMessage: null
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1993)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.helpers.migration.V193_BackCallLinksWithRecipient.migrate(V193_BackCallLinksWithRecipient.kt:63)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:243)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:170)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:302)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:195)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:305)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(Unknown Source:2)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.lambda$onOpen$0(KeyValueDatabase.java:99)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.$r8$lambda$jefACyoHK4h3lvPI5zn7iBuWxuI(Unknown Source:0)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.KeyValueDatabase$$ExternalSyntheticLambda0.run(Unknown Source:0)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:1012)
05-18 12:12:15.381 19759 19805 E SignalUncaughtException: 	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
```

**Comment by clark-signal** [comment]
Hey sorry about that, we should have a fix going out in 6.21.1

**Comment by cgranade** [comment]
No worries, I'm on the beta channel after all! Mostly wanted to raise in case it wasn't known. Thanks for the update! ♥

**Comment by pappasadrian** [comment]
Same issue on Nokia Xr20. Waiting for the update ❤️

**Comment by eladyarom** [comment]
I'm having the same issue on 6.21.1 :(

05-19 06:48:30.646 20429 20462 E AndroidRuntime: FATAL EXCEPTION: signal-bounded-2
05-19 06:48:30.646 20429 20462 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 20429
05-19 06:48:30.646 20429 20462 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: call_tmp.call_id, call_tmp.peer | ExtraMessage: null
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1993)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.migration.V196_BackCallLinksWithRecipientV2.migrate(V196_BackCallLinksWithRecipientV2.kt:67)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:256)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:169)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:302)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:194)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:310)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(Unknown Source:2)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.lambda$onOpen$0(KeyValueDatabase.java:99)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.$r8$lambda$jefACyoHK4h3lvPI5zn7iBuWxuI(Unknown Source:0)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase$$ExternalSyntheticLambda0.run(Unknown Source:0)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
05-19 06:48:30.646 20429 20462 E AndroidRuntime: 	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
05-19 06:48:30.646 20429 20462 E SignalUncaughtException: android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: call_tmp.call_id, call_tmp.peer | ExtraMessage: null

**Comment by carbonpenguin** [comment]
Same issue on Pixel 5a. When will 6.21.1 be available in the Google Play store to see if that fixes it?

**Comment by GentlyD** [comment]
same here on Samsung S10+ going back to 6.20.5 was a temporary quick fix for me https://signal.org/android/apk/

**Comment by gmrodgers** [comment]
Same issue on Pixel 6

**Comment by GentlyD** [comment]
@eladyarom when you get "app not installed as package appears to be invalid"...is it possible that you did not uninstall any other Signal version first?

**Comment by strugee** [comment]
Please note that the reason you need to uninstall Signal first is because Android apps don't support downgrading. Therefore the workaround of installing the stable version implies **wiping all of your Signal data and starting from an old, probably incomplete backup**. Just want to make sure folks are clear about what's being discussed.

**Comment by eladyarom** [comment]
I didn't uninstall the current app no, I don't want to loose my messages/photos/verified connections.

**Comment by GentlyD** [comment]
@eladyarom okay, sure. In case you configured Signal to automatically create daily backups you can use your latest backup also for version 6.20.5 -> this process worked fine for me.

**Comment by strugee** [comment]
FYI for folks here 77ccbdd32217fb256bcf1cbeed38d4d0da94326f just landed which I'm _guessing_ will fix this (but I'm not sure and I can't test because it's so new 6.21.2 hasn't even hit Firebase distribution yet).

**Comment by strugee** [comment]
Confirmed fixed by 6.21.2 (at least for me).

**Comment by eladyarom** [comment]
Confirmed fixed by 6.21.2  for me as well. Thank you Signal team for all your hard work :tada: :heart:

**Comment by GentlyD** [comment]
Same here, confirmed fixed by 6.21.2 - Thanks to the Signal team!!!

**Comment by cgranade** [comment]
Works for me as well, thank you so much! ♥
