### ISSUE TITLE
App crashes on new device soon after Account Transfer is complete

### ISSUE THREAD

**Issue by gnuanu** [signalapp/Signal-Android#12954]
**Metadata**
Platform: Android
Source: Google Play Store
Version: 6.20.5

Activity: Account Transfer
Old Device: OnePlus 7T
New Device: Pixel 7a

**Description**
Application on new device crashes soon after the transfer is complete. The completion of data transfer is confirmed on the old device. Whilst relaunching the application on new device, it takes to the register screen again

**Reproducible**
3 out of 3

**Steps to reproduce**
Precondition: App signed in on old device; Installed freshly on new device
1. Go through the account transfer steps.
2. Wait for the transfer to complete
3. Soon after the completion, App on new device crashes

**ADB Logcat**
```
05-18 14:46:05.469  9898  9984 I SignalDatabase: Upgrading database: 188, -1
05-18 14:46:05.471  9898  9984 E SQLiteLog: (1) foreign key mismatch - "call_tmp" referencing "call_link" in "INSERT INTO call_tmp
05-18 14:46:05.471  9898  9984 E SQLiteLog: SELECT
05-18 14:46:05.471  9898  9984 E SQLiteLog:   _id,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   call_id,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   message_id,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   peer,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   NULL as call_link,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   type,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   direction,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   event,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   timestamp,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   ringer,
05-18 14:46:05.471  9898  9984 E SQLiteLog:   del
05-18 14:46:05.473  9898  9983 D DeviceTransferServer: Handle message: 1004
05-18 14:46:05.473  9898  9983 D DeviceTransferServer: transferStatus: NETWORK_CONNECTED
05-18 14:46:05.473  9898  9984 E AndroidRuntime: FATAL EXCEPTION: Thread-2
05-18 14:46:05.473  9898  9984 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9898
05-18 14:46:05.473  9898  9984 E AndroidRuntime: android.database.sqlite.SQLiteException: FullCode: 1 | ErrorCode: 1 | ExtendedErrorCode: 0 | Message: foreign key mismatch - "call_tmp" referencing "call_link" | ExtraMessage: , while compiling: INSERT INTO call_tmp
05-18 14:46:05.473  9898  9984 E AndroidRuntime: SELECT
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   _id,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   call_id,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   message_id,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   peer,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   NULL as call_link,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   type,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   direction,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   event,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   timestamp,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   ringer,
05-18 14:46:05.473  9898  9984 E AndroidRuntime:   deletion_timestamp
05-18 14:46:05.473  9898  9984 E AndroidRuntime: FROM call
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteConnection.prepare(SQLiteConnection.java:536)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteSession.prepare(SQLiteSession.java:592)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteProgram.<init>(SQLiteProgram.java:64)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteStatement.<init>(SQLiteStatement.java:38)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1991)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.helpers.migration.V189_CreateCallLinkTableColumnsAndRebuildFKReference.migrate(V189_CreateCallLinkTableColumnsAndRebuildFKReference.kt:53)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:223)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:167)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase$Companion$runPostBackupRestoreTasks$1$1.invoke(SignalDatabase.kt:282)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase$Companion$runPostBackupRestoreTasks$1$1.invoke(SignalDatabase.kt:281)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase$Companion.runPostBackupRestoreTasks(SignalDatabase.kt:281)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.SignalDatabase.runPostBackupRestoreTasks(Unknown Source:2)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.thoughtcrime.securesms.devicetransfer.newdevice.NewDeviceServerTask.run(NewDeviceServerTask.java:52)
05-18 14:46:05.473  9898  9984 E AndroidRuntime:        at org.signal.devicetransfer.NetworkServerThread.run(NetworkServerThread.java:97)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException: android.database.sqlite.SQLiteException: FullCode: 1 | ErrorCode: 1 | ExtendedErrorCode: 0 | Message: foreign key mismatch - "call_tmp" referencing "call_link" | ExtraMessage: , while compiling: INSERT INTO call_tmp
05-18 14:46:05.474  9898  9984 E SignalUncaughtException: SELECT
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   _id,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   call_id,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   message_id,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   peer,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   NULL as call_link,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   type,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   direction,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   event,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   timestamp,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   ringer,
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:   deletion_timestamp
05-18 14:46:05.474  9898  9984 E SignalUncaughtException: FROM call
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteConnection.prepare(SQLiteConnection.java:536)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteSession.prepare(SQLiteSession.java:592)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteProgram.<init>(SQLiteProgram.java:64)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteStatement.<init>(SQLiteStatement.java:38)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1991)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.helpers.migration.V189_CreateCallLinkTableColumnsAndRebuildFKReference.migrate(V189_CreateCallLinkTableColumnsAndRebuildFKReference.kt:53)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:223)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:167)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase$Companion$runPostBackupRestoreTasks$1$1.invoke(SignalDatabase.kt:282)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase$Companion$runPostBackupRestoreTasks$1$1.invoke(SignalDatabase.kt:281)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase$Companion.runPostBackupRestoreTasks(SignalDatabase.kt:281)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.database.SignalDatabase.runPostBackupRestoreTasks(Unknown Source:2)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.thoughtcrime.securesms.devicetransfer.newdevice.NewDeviceServerTask.run(NewDeviceServerTask.java:52)
05-18 14:46:05.474  9898  9984 E SignalUncaughtException:       at org.signal.devicetransfer.NetworkServerThread.run(NetworkServerThread.java:97)
05-18 14:46:05.482  9898  9984 I JobManager: Successfully flushed.
05-18 14:46:05.485  9898  9898 D DeviceToDeviceTransferS: Action: stop
05-18 14:46:05.485  9898  9898 I DeviceToDeviceTransferS: Shutdown
05-18 14:46:05.488  1740 10056 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-18 14:46:05.489  1740  3059 W ActivityTaskManager:   Force finishing activity org.thoughtcrime.securesms/.registration.RegistrationNavigationActivity
05-18 14:46:05.489  9898  9898 D LoggingFragment: [NewDeviceTransferSetupF] onDestroy()
05-18 14:46:05.490  9898  9898 D LoggingFragment: [NewDeviceTransferFragme] onStop()
05-18 14:46:05.490  9898  9898 D LoggingFragment: [NewDeviceTransferInstru] onDestroy()
05-18 14:46:05.490  9898  9898 D LoggingFragment: [TransferOrRestoreFragme] onDestroy()
05-18 14:46:05.490  9898  9898 D LoggingFragment: [NewDeviceTransferComple] onCreate()
05-18 14:46:05.500  9898  9898 D LoggingFragment: [NewDeviceTransferComple] onStart()
05-18 14:46:05.502  9898  9898 D DeviceToDeviceTransferS: Action: stop
05-18 14:46:05.502  9898  9898 I DeviceToDeviceTransferS: Shutdown
05-18 14:46:05.506  1740  1779 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-18 14:46:05.506  1740  1779 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-18 14:46:05.508  9898  9984 I Process : Sending signal. PID: 9898 SIG: 9
05-18 14:46:05.575  1740  3059 I ActivityManager: Process org.thoughtcrime.securesms (pid 9898) has died: fg  TOP 
05-18 14:46:05.575  1740 11635 I WindowManager: WIN DEATH: Window{1caca92 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity}
05-18 14:46:05.575  1740  2041 D WifiP2pService: Client:org.thoughtcrime.securesms is removed
```

**Comment by benschop-it** [comment]
So is there any way I can get my data back? I was in the middle of a transfer that crashed on the target. Then I updated the source application so it was also on the latest version to see if that solved the issue, and now the source also crashes! So now neither apps work and all my data is gone!

**Comment by clark-signal** [comment]
> So is there any way I can get my data back? I was in the middle of a transfer that crashed on the target. Then I updated the source application so it was also on the latest version to see if that solved the issue, and now the source also crashes! So now neither apps work and all my data is gone!

You'll need to update both the new device and old device, and then you should be able to transfer. Your data shouldn't be gone. If that doesn't work we'll likely need logs to take a look at what's going wrong.

**Comment by depaperis** [comment]
Same issue here: 
- on a new android phone fresh install from google play store, v. 6.21.3. App starts correctly.
- the account transfer completes and is apparently successful, but then the app won't start anymore.
- (uninstalled and repeated multiple times, including powering off and on the phone: no luck).
- and finally, after a *successful* update of the app on the old phone, the app crashes when opening.

I'll try to get the logs, but in the meantime...

is there a way to restore a previous version? I remember there were old apks available for download but I can't find them anymore.

**Comment by MikeTango** [comment]
Same problem, please reopen.
