### ISSUE TITLE
Error while attempting to transfer my account between two phones

### ISSUE THREAD

**Issue by inexxt** [signalapp/Signal-Android#13003]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm attempting to transfer my account between two phones.

### Steps to reproduce
 - start the transfer from both devices
 - click "accept" when asked to confirm the connection on the new phone

**Actual result**: After about 30 seconds idle, I get "Error Connecting\n An unexpected error occured while attempting to connect to your new Android device." on the old device
**Expected result**: the account is transferred to the new phone

### Device info

**Device:** Pixel 3a
**Android version:** 12, API 32 (8782922, SP2A.220505.008)
**Signal version:** 6.22.8

### Link to debug log

https://debuglogs.org/android/6.22.8/71426e53a2e032bb77c94fd49727f6cbbde0eb5bfc83baf48ead375acd4ed33a

**Comment by cody-signal** [comment]
Your logs show that WiFi Direct is unavailable. We use that to connect peer-to-peer to the other device.

Do you have a VPN on or anything else that may be interfering with WiFi Direct?

**Comment by inexxt** [comment]
Oh, thanks, that has helped - it was the VPN's fault, after disabling the problem went away. I should have thought about that, sorry. 

Although I think that WiFi Direct error is not what was responsible.

For posteriority - initially Signal didn't even get to the point of discovering the second device, it just errored (with the same message of "Error Connecting\n An unexpected error occured while attempting to connect to your new Android device"). I looked through the logs, saw the "WifiDirect: discover services failure_reason: 2" error in there, and assumed that this was because I had a hotspot enabled on the old device. 

After disabling the hotspot, the device discovery had completed successfully, but it was breaking afterwards. I looked through the (new) logs again, and couldn't find a solution.

Specifically, I have disabled hotspot at 20:36, and @cody-signal you can see that from this point onwards, there are no failure_reason 2 in the log - it says:
```
[6.22.8] [282  ] 2023-06-14 20:36:45.501 GMT+01:00 I WifiDirect: Successfully connected to service.
```

And then the error that is actually happening is:

```
[6.22.8] [289  ] 2023-06-14 20:36:52.230 GMT+01:00 I NetworkClientThread: Client thread running
[6.22.8] [289  ] 2023-06-14 20:36:52.231 GMT+01:00 I NetworkClientThread: Attempting to connect to server... tries: 3
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: Error connecting to server
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: java.net.SocketTimeoutException: failed to connect to /...ipv4... (port 44547) from /...ipv4... (port 47349) after 10000ms
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at libcore.io.IoBridge.connect(IoBridge.java:179)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at java.net.Socket.connect(Socket.java:646)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:155)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 	at org.signal.devicetransfer.NetworkClientThread.run(NetworkClientThread.java:77)
[6.22.8] [289  ] 2023-06-14 20:37:02.242 GMT+01:00 W NetworkClientThread: 
[6.22.8] [282  ] 2023-06-14 20:37:02.243 GMT+01:00 D DeviceTransferClient: Handle message: 1002
[6.22.8] [282  ] 2023-06-14 20:37:02.243 GMT+01:00 D DeviceTransferClient: transferStatus: NETWORK_CONNECTED
[6.22.8] [main ] 2023-06-14 20:37:02.244 GMT+01:00 I DeviceTransferSetupView: Handling transferStatus: NETWORK_CONNECTED
[6.22.8] [main ] 2023-06-14 20:37:02.244 GMT+01:00 D DeviceTransferSetupView: Ignore event: NETWORK_CONNECTED
[6.22.8] [289  ] 2023-06-14 20:37:05.243 GMT+01:00 I NetworkClientThread: Attempting to connect to server... tries: 2
[6.22.8] [289  ] 2023-06-14 20:37:15.255 GMT+01:00 W NetworkClientThread: Error connecting to server
```

Anyway, feel free to close the issue.
