### ISSUE TITLE
Creating backup and getting error Plz help 

### ISSUE THREAD

**Issue by trao90** [signalapp/Signal-Android#13038]
- [ ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
HELLO, I'm trying to create a backup but everytime its ginving an error with "Your recent backup could not be created and verified please create a new one", I have deleted large files from groups and grant acces to a folder where it should writes the backup data also done enable disabled chats to see if it works but no luck

### Screenshots

![Screenshot_20230630_024445_Firefox](https://github.com/signalapp/Signal-Android/assets/138168024/846ade88-1583-4c76-a918-b38c01a52e99)

### Device info

**Device:** Samsung S21 Ultra SM-G9980
**Android version:** 13
**Signal version:** 6.23.5

### Link to debug log

https://debuglogs.org/android/6.23.5/4b9cee93c9cd5abf8840ac423888f29b320cdbaf4a860929cbbf5614c42388d3

**Comment by derMart** [comment]
(for disclaimer I am not part of the Signal team, but was interested in your case)
This is the relevant log portion:
```
[6.23.5] [123148] 2023-06-28 02:15:35.433 GMT+05:00 D FullBackupExporter: Exporting table: payments
[6.23.5] [123148] 2023-06-28 02:15:35.433 GMT+05:00 D FullBackupExporter: Exporting table: pending_pni_signature_message
[6.23.5] [123148] 2023-06-28 02:15:35.433 GMT+05:00 D FullBackupExporter: Exporting table: push
[6.23.5] [123148] 2023-06-28 02:15:35.433 GMT+05:00 D FullBackupExporter: Exporting table: reaction
[6.23.5] [123148] 2023-06-28 02:15:35.507 GMT+05:00 D FullBackupExporter: Exporting table: remapped_recipients
[6.23.5] [123148] 2023-06-28 02:15:35.509 GMT+05:00 D FullBackupExporter: Exporting table: remapped_threads
[6.23.5] [123148] 2023-06-28 02:15:35.509 GMT+05:00 D FullBackupExporter: Exporting table: remote_megaphone
[6.23.5] [123148] 2023-06-28 02:15:35.510 GMT+05:00 D FullBackupExporter: Exporting table: sticker
[6.23.5] [123148] 2023-06-28 02:15:36.201 GMT+05:00 D FullBackupExporter: Exporting table: storage_key
[6.23.5] [123148] 2023-06-28 02:15:36.203 GMT+05:00 D FullBackupExporter: Exporting table: story_sends
[6.23.5] [123148] 2023-06-28 02:15:36.344 GMT+05:00 D FullBackupExporter: [Backup] table::avatar_picker: 0  table::recipient: 568  table::thread: 15  table::message: 3702  table::call: 16  table::call_link: 2  table::cds: 96  table::chat_colors: 0  table::distribution_list: 1  table::distribution_list_member: 1  table::donation_receipt: 1  table::drafts: 0  table::emoji_search: 0  table::group_membership: 5  table::group_receipts: 689  table::groups: 1  table::identities: 17  table::kyber_prekey: 105  table::mention: 6  table::message_fts: 0  table::msl_payload: 674  table::msl_message: 821  table::msl_recipient: 621  table::notification_profile: 0  table::notification_profile_allowed_members: 2  table::notification_profile_schedule: 0  table::one_time_prekeys: 0  table::part: 116842  table::payments: 0  table::pending_pni_signature_message: 0  table::pending_retry_receipts: 0  table::push: 0  table::reaction: 74  table::remapped_recipients: 2  table::remapped_threads: 0  table::remote_megaphone: 1  table::sender_key_shared: 0  table::sender_keys: 0  table::sessions: 0  table::signed_prekeys: 0  table::sticker: 691  table::storage_key: 2  table::story_sends: 19  prefs: 2  key_values: 5  avatars: 115  total: 125096
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: Unable to find backup file, attempt: 1/5
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/1000004014
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.os.Parcel.createException(Parcel.java:3007)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.os.Parcel.readException(Parcel.java:2990)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.verifyBackup(LocalBackupJobApi29.java:198)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:150)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[6.23.5] [123148] 2023-06-28 02:15:36.397 GMT+05:00 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```
Backup process goes like this: File with temporary name (timestamp + some random string) is created, then `FullBackupExporter` is writing backup to that file, then `LocalBackupJobApi29` via `BackupVerifier` is verifying the backup (tries to read it once with the password), then temp file is renamed to the final signal-.....backup file. Now in your case it is written to the temp file supposedly according to log. But verifier is not able to read the file because of missing permissions. That is strange indeed. You could try to disable an enable backups and try again or set the backup directory again in the settings, you could also try to set a different backup directory. You could also have a look at the backup directory and see if you can spot the temporary file. If you have a second device, you could rename that file to .backup and try to import it on a second device. This way you know that it is ok.

**Comment by MartinX3** [comment]
In my case I needed to
1. deactivate and activate the backup function
2. remove every backup file

Now it finally works again

**Comment by MartinX3** [comment]
Backup stopped working again

See #12915

**Comment by clauz9** [comment]
@trao90 Did you fix this issue ? 

If not, and since it seems you might be having a  storage permissions iasue... can you take a look at this cooment and see if it helps..



https://github.com/signalapp/Signal-Android/issues/12915#issuecomment-1624078250
