### ISSUE TITLE
Save all media gives error and does not work

### ISSUE THREAD

**Issue by janvlug** [signalapp/Signal-Android#13061]
### Bug description
I tried to save all media, but only a very small fraction of the files was saved.
See error log for details, but I guess this is the relevant part:

```
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part4252733374678444408.mms: open failed: ENOENT (No such file or directory)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at libcore.io.IoBridge.open(IoBridge.java:492)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:30)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.database.AttachmentTable.getDataStream(AttachmentTable.java:1074)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachmentStream(AttachmentTable.java:216)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:74)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:129)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:91)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:46)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at java.lang.Thread.run(Thread.java:923)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at libcore.io.Linux.open(Native Method)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7583)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	at libcore.io.IoBridge.open(IoBridge.java:478)
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 	... 13 more
[6.25.5] [2956 ] 2023-07-14 12:13:20.997 GMT+02:00 W AttachmentTable: 
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: java.io.IOException: No stream for: AttachmentId::(4212, 1675179634524)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachmentStream(AttachmentTable.java:218)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:74)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.saveAttachment(SaveAttachmentTask.java:129)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:91)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.util.SaveAttachmentTask.doInBackground(SaveAttachmentTask.java:46)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at java.lang.Thread.run(Thread.java:923)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: Caused by: java.io.FileNotFoundException: /data/user/0/org.thoughtcrime.securesms/app_parts/part4252733374678444408.mms: open failed: ENOENT (No such file or directory)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at libcore.io.IoBridge.open(IoBridge.java:492)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:30)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.database.AttachmentTable.getDataStream(AttachmentTable.java:1074)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachmentStream(AttachmentTable.java:216)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	... 9 more
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at libcore.io.Linux.open(Native Method)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7583)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	at libcore.io.IoBridge.open(IoBridge.java:478)
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 	... 13 more
[6.25.5] [2956 ] 2023-07-14 12:13:20.998 GMT+02:00 W SaveAttachmentTask: 
```

### Steps to reproduce
- go to Settings
- go to Data and storage
- go to Manage storage
- go to REVIEW STORAGE
- select Media
-  long press the first medium and choose Select all
-  choose Save
-  I see Saving 4108 attachments and the spinner
- After a while I saw very shortly a message: Error while saving.... (could not read it fully)

Side note: this error message should not disappear, but be very dominant  and wait for the user to indicate that it has been read. But this issue is about that there is an error in itself. I missed this error message all times, but only saw it when creating the steps above.

**Actual result:** Error message
**Expected result:** All media should be saved

### Device info
Manufacturer      : HMD Global
Model             : Nokia 4.2
Product           : Panther_00EEA
Screen            : 720x1370, xhdpi (300), 60.00 hz
Font Scale        : 1.0
Animation Scale   : 1.0
Android           : 11, API 30 (00EEA_3_24B, 00EEA_3_240_SP02)
ABIs              : arm64-v8a, armeabi-v7a, armeabi
Memory            : 62M (21.36% free, 512M max)
Memclass          : 192
MemInfo           : availMem: 1153 mb, totalMem: 2850 mb, threshold: 216 mb, lowMemory: false
OS Host           : Hoki_192-168-67-127_15525_docker
User-Agent        : Signal-Android/6.25.5 Android/30
App               : Signal 6.25.5

### Link to debug log
https://debuglogs.org/android/6.25.5/0c205ecb70ca6b7ee4ad1bab792f0e545ecd886397ae714f52dd05c6ed12ba1f

**Comment by olafolafsson** [comment]
Same issue here

https://debuglogs.org/android/6.27.10/3bea860fe15e473d1e989987ad523d4c65bb73b56dadad58c0426ffc4bc06fa3

**Comment by janvlug** [comment]
I tested today again, and this issue is still there. Can it be reopened please?
