### ISSUE TITLE
Crash upon trying to create a Story

### ISSUE THREAD

**Issue by Wojtaz0w** [signalapp/Signal-Android#13063]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when creating a story. 

### Steps to reproduce
- try to create a Story

**Actual result:** crash 💀
**Expected result:** no crash

### Screenshots
https://github.com/signalapp/Signal-Android/assets/104674625/9c26bfaa-27d9-406c-ab23-150f2ffa1e9b

### Device info
**Device:** Redmi 9
**Android version:** 13
**Signal version:** 6.26.2

### Link to debug log
https://debuglogs.org/android/6.26.2/0ad683c2e67f5be5f154f060de791a049de0a7748b8a0b289414d0c56d0b24da

Captured by custom ROM( **https://paste.crdroid.net/Rs6MV1**) :
time: 1689439218982
```
msg: java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{cc87ab2 V.E...... R.....I. 0,0-0,0} not attached to window manager
stacktrace: java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{cc87ab2 V.E...... R.....I. 0,0-0,0} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:571)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:448)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:155)
	at android.widget.PopupWindow.update(PopupWindow.java:2227)
	at android.widget.PopupWindow.update(PopupWindow.java:2348)
	at android.widget.PopupWindow.alignToAnchor(PopupWindow.java:2518)
	at android.widget.PopupWindow.-$$Nest$malignToAnchor(Unknown Source:0)
	at android.widget.PopupWindow$1.onViewAttachedToWindow(PopupWindow.java:243)
	at android.view.View.dispatchAttachedToWindow(View.java:21308)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2326)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9092)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at View=android.widget.PopupWindow$PopupDecorView{cc87ab2 V.E...... R.....I. 0,0-0,0} not attached to window manager.(:0)
```

**Comment by Wojtaz0w** [comment]
Fixed as of 6.28.2
