### ISSUE TITLE
Crash when receiving message from matrix bridge/always when opening chat

### ISSUE THREAD

**Issue by rugk** [signalapp/Signal-Android#13099]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- I got a message (related or not I was using signal bubbles and my system ui crashed because of that), anyway every time when opening the message it crashes, later I found out I think the sender used the signal-matrix bridge and had not used the app for a while/[app required a captcha on their site](https://signald.org/articles/captcha/)
- it says "unknown - receiving problem", and always when opening this chat it crashes again

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots

![IMG_20230810_103243](https://github.com/signalapp/Signal-Android/assets/11966684/db24dc9c-e698-489c-8c7e-85b890463c1c)

### Device info

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.11.3. 
source: F-Droid (CalyxOS repo)  
version: v. Version 6.27.10
Build-ID: `TQ3A.230705.001.23411030` 

### Link to debug log

https://debuglogs.org/android/6.27.10/5c3d21df83c2eb84ba52555e39adffc9172c6a75b7525e1bacb754e77f2ab61d

Logcat:
```
java.lang.IllegalStateException: Condition must be true!
	at org.thoughtcrime.securesms.conversation.v2.ConversationViewModel.<init>(ConversationViewModel.kt:157)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at org.whispersystems.signalservice.api.util.Preconditions.checkState(Preconditions.java:26)
	at org.whispersystems.signalservice.api.util.Preconditions.checkState(Preconditions.java:21)
	at org.thoughtcrime.securesms.recipients.Recipient.getParticipantAcis(Recipient.java:910)
	at org.thoughtcrime.securesms.conversation.ConversationRepository.getConversationData(ConversationRepository.java:116)
	at org.thoughtcrime.securesms.conversation.v2.ConversationRepository.getConversationThreadState$lambda$0(ConversationRepository.kt:137)
	at org.thoughtcrime.securesms.conversation.v2.ConversationRepository.$r8$lambda$SEmY6z8BVO3vpDRoIUBmm8tqjes(ConversationRepository.kt:0)
	at org.thoughtcrime.securesms.conversation.v2.ConversationRepository$$ExternalSyntheticLambda7.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
FATAL EXCEPTION: signal-io-bounded-3
Process: org.thoughtcrime.securesms, PID: 17440
java.lang.IllegalStateException: Condition must be true!
	at org.thoughtcrime.securesms.conversation.v2.ConversationViewModel.<init>(ConversationViewModel.kt:157)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at org.whispersystems.signalservice.api.util.Preconditions.checkState(Preconditions.java:26)
	at org.whispersystems.signalservice.api.util.Preconditions.checkState(Preconditions.java:21)
	at org.thoughtcrime.securesms.recipients.Recipient.getParticipantAcis(Recipient.java:910)
	at org.thoughtcrime.securesms.conversation.ConversationRepository.getConversationData(ConversationRepository.java:116)
	at org.thoughtcrime.securesms.conversation.v2.ConversationRepository.getConversationThreadState$lambda$0(ConversationRepository.kt:137)
	at org.thoughtcrime.securesms.conversation.v2.ConversationRepository.$r8$lambda$SEmY6z8BVO3vpDRoIUBmm8tqjes(ConversationRepository.kt:0)
	at org.thoughtcrime.securesms.conversation.v2.ConversationRepository$$ExternalSyntheticLambda7.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at Condition must be true!.(:0)
```

**Comment by simono43** [comment]
Here the error message from the server

`[2023-08-10 08:25:39,465] [ERROR@mau.portal.s9v/…] Failed to handle Matrix message … …
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 320, in handle_matrix_message
    await self._handle_matrix_message(sender, message, event_id)
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 491, in _handle_matrix_message
    retry_count = await self._signal_send_with_retries(
  File "/usr/lib/python3.10/site-packages/mautrix_signal/portal.py", line 558, in _signal_send_with_retries
    await send_fn(sender, event_id, req_id=req_id, **send_args)
  File "/opt/mautrix-signal/mausignald/signald.py", line 315, in send
    raise Exception("\n".join(errors))
Exception: Network failure occurred while sending message to …`

**Comment by greyson-signal** [comment]
It appears that your contact using a matrix bridge is messaging you via a groupId that does not exist. And they're also otherwise sending you badly-encrypted messages. Unfortunately the matrix bridge is made by a third party and not supported by us.

**Comment by rugk** [comment]
But uhm I cannot decide what my contact does and if it crashes *my* messenger that should not happen?
