### ISSUE TITLE
Signal crashes when opening backup file for restore

### ISSUE THREAD

**Issue by TheGorf** [signalapp/Signal-Android#13127]
I have a pixel 7 pro that I purposely reset. I had taken a backup of signal only just a few minutes before. After the phone was done resetting, I installed signal and opened my backup file to restore all of my data. Signal crashes the moment I enter my backup passphrase and try to start. There appear to be several different bugs filed related to this kind of topic, but they are all in a closed state and none of them seem to have any fixes that work for me.

### Device info

**Device:** Google Pixel 7 Pro
**Android version:** 13
**Signal version:** 0.0.0

### Link to debug log
Because the app crashes, the best I can do is provide this just as I start:

https://debuglogs.org/android/6.28.6/28e738b2a48a4e1e6c7791abb8c22d263bc6b2bfcafb0aa20d64c7d212231933

**Comment by jd-solanki** [comment]
Thanks you opened this before me 😅

I formatted my mobile and wanted to get back the chat but signal crashes just like him 🤦🏻‍♂️

**Comment by lizsugar** [comment]
This is still happening, over month later. How is this not a priority 1 issue?? I just encountered this today, ALL of my backup files yield an instant crash upon entering the backup code, whether it's the right code or an invalid one. The largest backup was only 1.1GB in size 

Here's my debug log from after such a crash. 

https://debuglogs.org/android/6.33.2/4fc9e16130fd6c82d8f50e38486cbcb098285ec34cb94d2594987acd596696a2

**Comment by ErikOlufson** [comment]
I also have to report that behavior. I tried to restore a 2.3Gb Backup.

`
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:1012)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1040734064 byte allocation with 25242024 free bytes and 503MB until OOM, target footprint 33656032, growth limit 536870912
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-29 22:54:56.565 25360 25697 E SignalUncaughtException: 	... 4 more
`
