### ISSUE TITLE
Signal crashes after opening a conversation

### ISSUE THREAD

**Issue by iforapsy** [signalapp/Signal-Android#13167]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I open any Signal conversation (whether it's a group chat or one-on-one conversation), Signal crashes after it displays the chat history.

Exception stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at androidx.core.util.ObjectsCompat.requireNonNull(ObjectsCompat.java:134)
	at androidx.core.graphics.drawable.IconCompat.createWithBitmap(IconCompat.java:278)
	at org.thoughtcrime.securesms.util.AvatarUtil.getIconCompatForShortcut(AvatarUtil.java:122)
	at org.thoughtcrime.securesms.util.ConversationUtil.buildShortcutInfo(ConversationUtil.java:229)
	at org.thoughtcrime.securesms.util.ConversationUtil.setActiveShortcuts(ConversationUtil.java:180)
	at org.thoughtcrime.securesms.jobs.ConversationShortcutUpdateJob.onRun(ConversationShortcutUpdateJob.java:79)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

### Steps to reproduce
- Open Signal
- Go to the main conversation list
- Open a conversation
- Wait a second.

**Actual result:** Signal crashes. Android says "Unfortunately, Signal has stopped." If I'm quick, I can read the read the message history. It's too quick for me to be able to write replies and send messages.
**Expected result:** Signal does not crash, thereby allowing me to send messages in my chats.

### Screenshots
N/A

### Device info

**Device:** LG V20
**Android version:** 8.0.0 (Orea)
**Signal version:** 6.32.2 (beta)

### Link to debug log
https://debuglogs.org/android/6.32.2/3652165942ea4d5963089f95820cbf1f63be193a64ac6bd581a242d53da523f4

**Comment by DeathDragonAW** [comment]
Happened today for me, too. Signal also seems to not be able to create a new backup, it ran multiple times today but no new file got stored. Additionally Signal is also showing a push notification with "~checking for messages ..." and another with "~you may have new messages".
![image](https://github.com/signalapp/Signal-Android/assets/52355057/e0e35de5-9135-43cf-9f7d-480a0b0f1398)

When I try to access the debug log it is not loading. Installed the latest available update but that did not help.

Device: Redmi Note 8 Pro
Android version: 10
Signal Version: 6.32.4

If more information is needed or anything I'll try to provide it/help. Absolutely don't want to loose my history.
