### ISSUE TITLE
Upgrading to 6.32.4 crashed the UI till a force stop

### ISSUE THREAD

**Issue by not-my-profile** [signalapp/Signal-Android#13172]
I have Signal installed via the APK. Upgrading to 6.32.4 crashed the UI so that none of the chats were visible (and clicking on "Calls" or "Stories" didn't do anything). Force stopping the app solved the problem.

### Screenshots
<details><summary>Screenshot</summary>

![Screenshot_20230914-174626_Signal](https://github.com/signalapp/Signal-Android/assets/73739153/6fdd122a-85d6-4b77-bdfc-1ea636ce6f44)
</details>

### Device info

**Device:** Google Pixel 3a
**Android version:** Android 12
**Signal version:** 6.32.4

### Link to debug log

I don't feel comfortable posting the whole log, however the relevant part appears to be:

```
--------- beginning of crash
09-14 17:45:48.456 25558 25593 E AndroidRuntime: FATAL EXCEPTION: signal-JobManager
09-14 17:45:48.456 25558 25593 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 25558
09-14 17:45:48.456 25558 25593 E AndroidRuntime: java.lang.IllegalArgumentException: column 'last_run_attempt_time' does not exist. Available columns: [_id, job_spec_id, factory_key, queue_key, create_time, next_run_attempt_time, run_attempt, max_attempts, lifespan, serialized_data, serialized_input_data, is_running]
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:358)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.signal.core.util.CursorUtil.requireLong(CursorUtil.java:29)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.signal.core.util.CursorExtensionsKt.requireLong(CursorExtensions.kt:33)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.database.JobDatabase.jobSpecFromCursor(JobDatabase.kt:359)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.kt:184)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.kt:19)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:77)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobManager.$r8$lambda$XT2SMZJxrQFMSviwHBjZhWrZ8u4(JobManager.java:0)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobManager$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
09-14 17:45:48.456 25558 25593 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.impl.DefaultExecutorFactory$1.run(DefaultExecutorFactory.java:19)
```

which appears to be related to the recent change a911a007d279d84d69abff624ca3224915f706b9.

**Comment by clark-signal** [comment]
Hi there, thanks so much for the report. Would you feel comfortable sending the log directly to support? You can e-mail the log link to support@signal.org and mention this github issue.

Logs would help us immensely in figuring out why this is happening

**Comment by not-my-profile** [comment]
Yes I have sent you the log :)

**Comment by not-my-profile** [comment]
Thanks for the quick fix!
