### ISSUE TITLE
App crashes constantly after group upgrade (which was left)

### ISSUE THREAD

**Issue by FiV0** [signalapp/Signal-Android#13193]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The App gets opened and crashes after a couple of seconds. I can click on a conversation which opens up the thread but after 2 seconds I am back to the conversation list screen and then 2 seconds later it crashes. The App does not crash when in Airplane mode. 

I am seeing the same error message as @chromosapiens in #13183. As it was mentioned that his issue is a different one then the original problem I opened up an explicit issue for it.

### Steps to reproduce

This is more my suspicion of what is happening than concrete evidence. 

This started happening yesterday. Signal was showing "Checking for message...." for a couple of hours on my phone. I also have the App linked to a Linux Client. I think this is very likely related to a group I am in/was in (no longer sure as the different clients say different things). That group was upgraded yesterday (seeing that on the Linux client). The new updates don't show on Signal-Android (as there I apparently left the group). I am getting the new messages in the group on the Linux client.
I am getting updates to other conversations but not to that group on the Android App.

The logs also say something about a group migration from V1 to V2 just before the crash.

### Device info
**Device:** : Googel Pixel 4a
**Android version:** 13, API 33 (10316531, TQ3A.230805.001)
**Signal version:** Signal-Android/6.33.3 Android/33

### Link to debug log
I can't upload the debug log as I am only able to look at it in Airplane mode. So I attached it as file
[signal-log-1695796948095.zip](https://github.com/signalapp/Signal-Android/files/12735460/signal-log-1695796948095.zip)

I think the important bit is 
```
[6.33.3] [86   ] 2023-09-27 08:39:40.572 GMT+02:00 E JobRunner: [JOB::3a69cbdb-511f-47cd-b69a-30ad8e9ac725][StorageSyncJob][1] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 2162 ms, Lifespan: 86400000 ms, Run Attempt: 1/3, Queue: StorageSyncingJobs)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: android.database.sqlite.SQLiteConstraintException: FullCode: 787 | ErrorCode: 19 | ExtendedErrorCode: 3 | Message: FOREIGN KEY constraint failed | ExtraMessage: null
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1871)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$updateWithOnConflict$16(SQLiteDatabase.java:401)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$thWq-xMSB79IwmaAnXhLQP0hKPM(SQLiteDatabase.java:0)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda11.run(R8$$SyntheticClass:0)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:401)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.update(SQLiteDatabase.java:256)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.signal.core.util.UpdateBuilderPart3.run(SQLiteDatabaseExtensions.kt:289)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.signal.core.util.UpdateBuilderPart3.run$default(SQLiteDatabaseExtensions.kt:288)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.GroupTable$migrateToV2$1.invoke(GroupTable.kt:868)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.GroupTable$migrateToV2$1.invoke(GroupTable.kt:849)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.GroupTable.migrateToV2(GroupTable.kt:849)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.groups.GroupsV1MigrationUtil.performLocalMigration(GroupsV1MigrationUtil.java:177)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.groups.GroupsV1MigrationUtil.performLocalMigration(GroupsV1MigrationUtil.java:149)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.GroupV2RecordProcessor.insertLocal(GroupV2RecordProcessor.java:117)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.GroupV2RecordProcessor.insertLocal(GroupV2RecordProcessor.java:24)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:73)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.GroupV2RecordProcessor.process(GroupV2RecordProcessor.java:24)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:412)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[6.33.3] [86   ] 2023-09-27 08:39:40.576 GMT+02:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
```

**Comment by chromosapiens** [comment]
Sounds indeed similar to my issue.
Same SQLite method but different query error (SQL logic error vs your foreign key constraint error) and the airplane trick does not work for me unfortunately. So causes may be different.

**Comment by cody-signal** [comment]
Indeed, the crashes are similar but not the same. Thanks for making a new ticket and providing so much background. We'll look into it.

**Comment by guiweber** [comment]
I've also started experiencing this issue a few days ago, and it also points to an issue with groups as @FiV0 surmised.

Signal android started crashing after I accepted an invite to a group through the windows desktop app. It's a group I had been part of in the past, but had left and had not been part of for two years. I'm getting messages for the new group on the desktop app while on android it says that I've left the group. I'm still getting other messages on android and don't get crashes when airplane mode is active.

My debug log shows the same exception and trace. My experience differs slightly in two ways: First the app didn't show "Checking for message...." for a long time before the issue started happening. Second, the app crashes much faster for me, usually in less than a second. Third, I'm sometimes getting messages that the app has crashed in the background (I didn't try to open the app).

Device: : LG V20
Android version: 7.0
Signal version: Signal-Android 6.34.5

**Comment by kerhac** [comment]
I am also seeing the same behavior as described above. Also on a Pixel 4a but with GrapheneOS and also with a Linux desktop client attached. Creating a backup and recovering it solved the issue for me.

<details>
  <summary>details and stack trace</summary>

## Android:
```
Android Version: 13
Build number: TQ3A.230805.001.2023100300
```
## App:
```
Version 6.36.1

org.thoughtcrime.securesms
versionCode 134302

targetSdk 33
minSdk 21

Installed: 21 May 2022; 15:32
Updated: 7 Oct 2023; 03:32
```  
## Stack Trace
```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001/2023100300:user/release-keys
package: org.thoughtcrime.securesms:134302
process: org.thoughtcrime.securesms
processUptime: 5765 + 339 ms
installer: com.android.vending

android.database.sqlite.SQLiteConstraintException: FullCode: 787 | ErrorCode: 19 | ExtendedErrorCode: 3 | Message: FOREIGN KEY constraint failed | ExtraMessage: null
at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
at net.zetetic.database.sqlcipher.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1871)
at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$updateWithOnConflict$16(SQLiteDatabase.java:401)
at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$thWq-xMSB79IwmaAnXhLQP0hKPM(SQLiteDatabase.java:0)
at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda11.run(R8$$SyntheticClass:0)
at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
at org.thoughtcrime.securesms.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:401)
at org.thoughtcrime.securesms.database.SQLiteDatabase.update(SQLiteDatabase.java:256)
at org.signal.core.util.UpdateBuilderPart3.run(SQLiteDatabaseExtensions.kt:289)
at org.signal.core.util.UpdateBuilderPart3.run$default(SQLiteDatabaseExtensions.kt:288)
at org.thoughtcrime.securesms.database.GroupTable$migrateToV2$1.invoke(GroupTable.kt:868)
at org.thoughtcrime.securesms.database.GroupTable$migrateToV2$1.invoke(GroupTable.kt:849)
at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
at org.thoughtcrime.securesms.database.GroupTable.migrateToV2(GroupTable.kt:849)
at org.thoughtcrime.securesms.groups.GroupsV1MigrationUtil.performLocalMigration(GroupsV1MigrationUtil.java:177)
at org.thoughtcrime.securesms.groups.GroupsV1MigrationUtil.performLocalMigration(GroupsV1MigrationUtil.java:149)
at org.thoughtcrime.securesms.storage.GroupV2RecordProcessor.insertLocal(GroupV2RecordProcessor.java:117)
at org.thoughtcrime.securesms.storage.GroupV2RecordProcessor.insertLocal(GroupV2RecordProcessor.java:24)
at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:73)
at org.thoughtcrime.securesms.storage.GroupV2RecordProcessor.process(GroupV2RecordProcessor.java:24)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:412)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
at [[ ↑↑ Original Trace ↑↑ ]].(:0)
at [[ ↓↓ Exception Message ↓↓ ]].(:0)
at FullCode: 787 | ErrorCode: 19 | ExtendedErrorCode: 3 | Message: FOREIGN KEY constraint failed | ExtraMessage: null.(:0)

```
## Linux Client
```bash
$ pacman -Qi signal-desktop
Name            : signal-desktop
Version         : 6.32.0-1
Description     : Signal Private Messenger for Linux
Architecture    : x86_64
URL             : https://signal.org
Licenses        : AGPL-3.0-only
Groups          : None
Provides        : None
Depends On      : alsa-lib  gtk3  hicolor-icon-theme  libvips  libxss  openjpeg2
Optional Deps   : xdg-desktop-portal: Screensharing with Wayland [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 387.90 MiB
Packager        : kpcyrd <kpcyrd@archlinux.org>
Build Date      : Fri 29 Sep 2023 10:44:20 AM CEST
Install Date    : Mon 02 Oct 2023 12:35:28 PM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
</details>

**Comment by benni-as** [comment]
I experience the same issues. I open signal and after 1 second the app crashes. Sadly, the workaround (backup, uninstall, install, restore) didn't help. So I can't use signal right now. (Which is a serious issue :scream: )

Device: : Googel Pixel 6a
Android version: 14 (Kernel: 5.10.157-android13-4-...)
Signal version: 6.37.2

**Comment by guiweber** [comment]
Still an issue...

**Comment by greyson-signal** [comment]
@guiweber Are you on 6.41.2+?

**Comment by guiweber** [comment]
@greyson-signal it seems my app hadn't been updated for some reason. I can't reproduce the issue after forcing the update :)
