### ISSUE TITLE
Signal v6.34.0-6.34.5 crashes on opening when connected to network - StoryDistributionListRecordProcessor UNIQUE constraint failed

### ISSUE THREAD

**Issue by bertille-ddp** [signalapp/Signal-Android#13198]
- [x] I have searched open and closed issues for duplicates _-> Some issues seemed functionally the same but the error message was different_
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on opening. Note: this doesn’t happen in airplane mode

### Steps to reproduce
- open Signal
- wait 0.5 to 5 seconds
Notes:
- the crash happens whether I stay on the main menu or if I open a conversation or a menu
- if I turn the network back on while using Signal, it crashes as well
- the notifications work, I can read messages and answer them
- if I compose a message in airplane mode, change window and turn the network back on, the message will get sent

**Actual result:** Signal can’t stay open, triggering a pop-up from Android after a few times
**Expected result:** Signal should stay open, allowing me to receive and send messages or change some config options

### Screenshots
Not relevant

### Device info

**Device:** Fairphone 3
**Android version:** /e/OS 1.15 (problem started when I was in 1.14)
**Signal version:** 6.34.5 (problem started just after an update on September 22, I believe it was 6.34.0 but I’m not sure)

### Debug log
I couldn’t capture logs via the app so here is the adb log:
```
10-01 20:22:54.002   901   948 E ANDR-PERF-OPTSHANDLER: Perflock resource /proc/sys/kernel/sched_spill_nr_run not supported
10-01 20:22:54.002   901   948 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [3, 11]
10-01 20:22:54.002   901   948 E ANDR-PERF-OPTSHANDLER: Perflock resource /proc/sys/kernel/sched_restrict_cluster_spill not supported
10-01 20:22:54.002   901   948 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [3, 13]
10-01 20:22:55.059   560   956 E HWComposer: getSupportedContentTypes: getSupportedContentTypes failed for display 0: Unsupported (8)
10-01 20:22:57.212  6981  7023 E BaseJob : Encountered a fatal exception. Crash imminent.
10-01 20:22:57.212  6981  7023 E BaseJob : android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: distribution_list.name | ExtraMessage: null
10-01 20:22:57.212  6981  7023 E BaseJob : 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at net.zetetic.database.sqlcipher.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1871)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at net.zetetic.database.sqlcipher.SQLiteDatabase.update(SQLiteDatabase.java:1817)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$update$15(SQLiteDatabase.java:396)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$7et4tsAJDomDbG3nqETNrQR4y2U(SQLiteDatabase.java:0)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.SQLiteDatabase.update(SQLiteDatabase.java:396)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.DistributionListTables$applyStorageSyncStoryDistributionListUpdate$1.invoke(DistributionListTables.kt:657)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.DistributionListTables$applyStorageSyncStoryDistributionListUpdate$1.invoke(DistributionListTables.kt:649)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.database.DistributionListTables.applyStorageSyncStoryDistributionListUpdate(DistributionListTables.kt:649)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.updateLocal(StoryDistributionListRecordProcessor.java:142)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.process(StoryDistributionListRecordProcessor.java:24)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:416)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
10-01 20:22:57.212  6981  7023 E BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
10-01 20:22:57.216  6981  7023 E JobRunner: [JOB::bacb2d6a-99e1-4c04-8874-1b7151157ef1][StorageSyncJob][1] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 2711 ms, Lifespan: 86400000 ms, Run Attempt: 1/3, Queue: StorageSyncingJobs)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
10-01 20:22:57.234  6981  7023 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: distribution_list.name | ExtraMessage: null
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1871)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.update(SQLiteDatabase.java:1817)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$update$15(SQLiteDatabase.java:396)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$7et4tsAJDomDbG3nqETNrQR4y2U(SQLiteDatabase.java:0)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.update(SQLiteDatabase.java:396)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DistributionListTables$applyStorageSyncStoryDistributionListUpdate$1.invoke(DistributionListTables.kt:657)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DistributionListTables$applyStorageSyncStoryDistributionListUpdate$1.invoke(DistributionListTables.kt:649)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DistributionListTables.applyStorageSyncStoryDistributionListUpdate(DistributionListTables.kt:649)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.updateLocal(StoryDistributionListRecordProcessor.java:142)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.process(StoryDistributionListRecordProcessor.java:24)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:416)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
10-01 20:22:57.234  6981  7023 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: android.database.sqlite.SQLiteConstraintException: FullCode: 2067 | ErrorCode: 19 | ExtendedErrorCode: 8 | Message: UNIQUE constraint failed: distribution_list.name | ExtraMessage: null
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:758)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1871)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.update(SQLiteDatabase.java:1817)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$update$15(SQLiteDatabase.java:396)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$7et4tsAJDomDbG3nqETNrQR4y2U(SQLiteDatabase.java:0)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.SQLiteDatabase.update(SQLiteDatabase.java:396)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.DistributionListTables$applyStorageSyncStoryDistributionListUpdate$1.invoke(DistributionListTables.kt:657)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.DistributionListTables$applyStorageSyncStoryDistributionListUpdate$1.invoke(DistributionListTables.kt:649)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:20)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.DistributionListTables.applyStorageSyncStoryDistributionListUpdate(DistributionListTables.kt:649)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.updateLocal(StoryDistributionListRecordProcessor.java:142)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.process(StoryDistributionListRecordProcessor.java:24)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:416)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
10-01 20:22:57.234  6981  7023 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
10-01 20:22:57.452   560   560 E ClientCache: failed to get buffer, invalid process token
10-01 20:22:57.520   560   560 E BpTransactionCompletedListener: Failed to transact (-32)
```

Thank you for your insights :)

**Comment by TRoc81** [comment]
Same behavior on my phone. I am using a Samsung  s21 fe 5g android 13 security patchlevel 1st of August. If this information helps in any way.

**Comment by bertille-ddp** [comment]
> Update: After creating a backup in airplane mode, reinstalling the app and restoring the backup everything seems to work again.

I tried to do this as well but for me it didn't solve the problem sadly :(

**Comment by bertille-ddp** [comment]
Update: upgrading to 6.35.3 didn't solve my problem

**Comment by bertille-ddp** [comment]
Just so you know: I'm still having the same behaviour, with the same error messages, on 6.38.2. Good luck for the rest of the dev process!

**Comment by cody-signal** [comment]
Hi @bertille-ddp sorry this took so long, but we know the cause and will have a fix out shortly,

**Comment by sebastianha** [comment]
Hi,

I just ran into this problem, too.

I can remember that I:
1. Had an existing story list (name: "test")
2. Created a new one with the name "test2"
3. Deleted the first one ("test")
4. Renamed the second one to the exact name of the first one ("test2" -> "test")

**Comment by sebastianha** [comment]
@cody-signal Will the fix repair the database? (Is it worth waiting for the fix or do I have do delete all my data anyway because restoring the backup will not help)

**Comment by clark-signal** [comment]
I believe the fix should repair the DB, so I wouldn't delete your data. The fix is in 6.42. Currently 6.41.2 is going to production, but 6.42 will likely be in beta (firebase app delivery) tomorrow.

**Comment by bertille-ddp** [comment]
Signal v6.42 just dropped for my phone and the fix works indeed!! No more crashes on startup

Thank you so much for this fix 🙏🙏🙏 As far as I'm concerned, this issue can be closed

**Comment by sebastianha** [comment]
> Signal v6.42 just dropped for my phone and the fix works indeed!! No more crashes on startup

On which channel did you receive the update? PlayStore and APK on website ist still on 6.41.3.

**Comment by adrien-github** [comment]
We got the same symptoms as describe in this bug (signal works without internet only)   but the version 6.42.3 doesn't solve the problems.
The bug occurs on 2 differents smartphone (Samsung and Huawei), here is the log journals on the 2 smartphones.

Kind regards

[signal-log-1703703929606.zip](https://github.com/signalapp/Signal-Android/files/13780708/signal-log-1703703929606.zip)
[signal-log-1703703934148.zip](https://github.com/signalapp/Signal-Android/files/13780710/signal-log-1703703934148.zip)

**Comment by bertille-ddp** [comment]
> > Signal v6.42 just dropped for my phone and the fix works indeed!! No more crashes on startup
> 
> On which channel did you receive the update? PlayStore and APK on website ist still on 6.41.3.

It was on /e/OS AppStore, which is just a proxy to Google's PlayStore. Did you get the update now?

**Comment by bertille-ddp** [comment]
Hi :)

> We got the same symptoms as describe in this bug (signal works without internet only) but the version 6.42.3 doesn't solve the problems. The bug occurs on 2 differents smartphone (Samsung and Huawei), here is the log journals on the 2 smartphones.
> 
> Kind regards

You may have the same behaviour but the error messages that show up in your logs are not the same as the ones that were in mine. I encourage you to open your own issue so that another fix can be found

**Comment by adrien-github** [comment]
Hi, 
thanks for our answer , I will open a new bug.

**Comment by sebastianha** [comment]
I can report back that 6.42.3 fixed the issure for me and also "repaired" my backup. I did a fresh install with a known broken backup and know everything is running fine. Thank you very much!
