### ISSUE TITLE
Signal force closes

### ISSUE THREAD

**Issue by sywir** [signalapp/Signal-Android#13203]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In 2021 i put my Pixel 5 to charge and after that my Signal application began to force close. Initially, I was able to view my messages briefly before the application would close. Now, however, I'm presented with a black screen preceding the closure. Despite updating to the latest version in the subsequent years, the problem persists. The only relevant information I've retrieved from the stack trace is "org.thoughtcrime.securesms.database.SqlCipherErrorHandler$DatabaseCorruptedError". I have shared this concern on the Signal Users community forum at [this link](https://community.signalusers.org/t/signal-started-force-closing-and-i-lack-a-backup-would-like-to-save-the-installation/37295). It was recommended there that I raise this issue on Github. It is important to me to access the messages as I have lost access to my backup.

### Steps to reproduce
- Start Signal

**Actual result:** Signal force closes
**Expected result:** Signal should open up and let me read and send messages

### Device info

**Device:** Google Pixel 5
**Android version:** Stock Android 12
**Signal version:** 6.35.3

**Comment by nicholas-signal** [comment]
Hello, a corrupted database can have many causes. Are you able to get any further information from the stack trace? The more context, the better, as the log lines preceding the exception can help us trace which codepath it follows and what the state of the application is before the exception.

**Comment by sywir** [comment]
Thank you for getting back to me. I've made corrections to the initial report. Specifically, the version of Signal I am using is 6.35.3, not 6.35.2, and my Android version is 12, not 13. I've also successfully retrieved a stack trace using Scoop. Below is the stack trace:

```FATAL EXCEPTION: signal-bounded-0
Process: org.thoughtcrime.securesms, PID: 16603
org.thoughtcrime.securesms.database.SqlCipherErrorHandler$DatabaseCorruptedError_BothChecksPass
at org.thoughtcrime.securesms.database.SqlCipherErrorHandler.onCorruption(SqlCipherErrorHandler.kt:40)
at net.zetetic.database.sqlcipher.SQLiteDatabase.onCorruption(SQLiteDatabase.java:348)
at net.zetetic.database.sqlcipher.SQLiteProgram.onCorruption(SQLiteProgram.java:117)
at net.zetetic.database.sqlcipher.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:74)
at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1993)
at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1900)
at org.thoughtcrime.securesms.database.helpers.migration.V149_LegacyMigrations.migrate(V149_LegacyMigrations.kt:2173)
at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:80)
at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:168)
at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:302)
at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:193)
at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:309)
at org.thoughtcrime.securesms.database.JobDatabase.dropTableIfPresent(JobDatabase.kt:408)
at org.thoughtcrime.securesms.database.JobDatabase.onOpen$lambda$0(JobDatabase.kt:158)
at org.thoughtcrime.securesms.database.JobDatabase.$r8$lambda$ou_p531IVGikC2LNueT6qnVrWyc(JobDatabase.kt:0)
at org.thoughtcrime.securesms.database.JobDatabase$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)
at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
at [[ ↑↑ Original Trace ↑↑ ]].(:0)
at [[ ↓↓ Inferred Trace ↓↓ ]].(:0)
at Database 'signal.db' corrupted!.(:0)
at [sqlite] FullCode: 267 | ErrorCode: 11 | ExtendedErrorCode: 1 | Message: database disk image is malformed | ExtraMessage: null.(:0)
at Diagnostics results:.(:0)
at ===== PRAGMA integrity_check (same-connection) =====.(:0)
at ok.(:0)
at .(:0)
at ===== PRAGMA cipher_integrity_check (same-connection) =====.(:0)
at .(:0)```

**Comment by nicholas-signal** [comment]
Unfortunately it would appear that the database image itself is irreversibly corrupted. There exist unofficial tools that you may be able to use to extract some of the contents of the damaged image.

With a fresh install of Signal 6.35, are you able to register and send messages?
