### ISSUE TITLE
Signal crashes when opening settings menu.

### ISSUE THREAD

**Issue by tati1454** [signalapp/Signal-Android#13227]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I was trying to build Signal from source, and when I tried to open Signal settings it crashed,
at first I thought it was related to the dev build, so I just removed it and installed again the app from
the play store, I cleared cache and data, did the registration process again, but the settings crash was
still there.

### Steps to reproduce
- Click the three dots in the right corner.
- Click settings.

**Actual result:** Signal crashes.
**Expected result:** Get settings to open.

### Device info

**Device:** Samsung Galaxy A32s SM-A325M
**Android version:** 13
**Signal version:** 6.35.5

### Link to debug log

I can't access Signal's settings :p

**Comment by alex-signal** [comment]
Given you sound like you've got ADB available, are you able to check it for a stacktrace?

**Comment by cody-signal** [comment]
@tati1454 this is wild, it's pretty much saying it can't find you, but we do this much earlier in the app lifecycle so how it wouldn't work here but does earlier makes no sense.

**Comment by tati1454** [comment]
Maybe it's a bug in the server? Because when trying to compile signal and install it in my smartphone, for some reason I lost my account so I had to create a new one and couldn't recover it.

**Comment by tati1454** [comment]
I just want to inform that I'm still having this issue.

**Comment by ay7n** [comment]
Same issue on S23 Android - March 2025 - all updates applied. **Clicking on Settings crashes the app. No direct workaround.** 
Indirect workaround: I'm able to access settings from my PC.

**Comment by iferca** [comment]
Same issue with Pixel 7 on GrapheneOS. 
I reinstalled the app and while it was retrieving the groups I was briefly able to access settings. Once it finished the issue went back. 
Here are some logs: 

```
type: crash
osVersion: google/panther/panther:15/AP4A.250205.002/2025030300:user/release-keys
package: org.thoughtcrime.securesms:151900, targetSdk 34
process: org.thoughtcrime.securesms
processUptime: 1746 + 258 ms
installer: com.android.vending

org.thoughtcrime.securesms.recipients.Recipient$MissingAddressError: Missing address for 2
	at org.thoughtcrime.securesms.recipients.Recipient.requireE164(Recipient.kt:406)
	at org.thoughtcrime.securesms.components.settings.app.BioRecipientState.<init>(BioRecipientState.kt:24)
	at org.thoughtcrime.securesms.components.settings.app.AppSettingsViewModel.self$lambda$0(AppSettingsViewModel.kt:36)
	at org.thoughtcrime.securesms.components.settings.app.AppSettingsViewModel.$r8$lambda$zkCJqTr5Dhv8kUtmFtxNXOq47xU(AppSettingsViewModel.kt:0)
	at org.thoughtcrime.securesms.components.settings.app.AppSettingsViewModel$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
	at androidx.lifecycle.Transformations$map$1.invoke(Transformations.kt:57)
	at androidx.lifecycle.Transformations$map$1.invoke(Transformations.kt:57)
	at androidx.lifecycle.Transformations$sam$androidx_lifecycle_Observer$0.onChanged(Transformations.kt:0)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:171)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at org.thoughtcrime.securesms.util.livedata.LiveDataUtil$CombineLiveData.lambda$new$2(LiveDataUtil.java:298)
	at org.thoughtcrime.securesms.util.livedata.LiveDataUtil$CombineLiveData.$r8$lambda$OicKrnolYD4HL2SlmVDLZ9LEI0A(LiveDataUtil.java:0)
	at org.thoughtcrime.securesms.util.livedata.LiveDataUtil$CombineLiveData$$ExternalSyntheticLambda2.onChanged(R8$$SyntheticClass:0)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:171)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
	at androidx.lifecycle.LiveData.observeForever(LiveData.java:234)
	at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:160)
	at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:137)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:405)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:481)
	at androidx.lifecycle.LiveData.observeForever(LiveData.java:234)
	at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:160)
	at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:137)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:405)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:481)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.jvm.kt:257)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.jvm.kt:293)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:205)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1707)
	at android.view.View.dispatchAttachedToWindow(View.java:22895)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3506)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3513)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3515)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2977)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10429)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1424)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1024)
	at android.view.Choreographer.doFrame(Choreographer.java:953)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1398)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at Missing address for 2.(:0)
```
