### ISSUE TITLE
Signal crashes when trying to send a message to an unregistered group member

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#13390]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In a group, someone who has been unregistered from Signal is still listed as a member. When I try to send a message to her from the group member list, Signal crashes.

I think this is the relevant crash from the debug log:
```
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:923)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: Caused by: org.thoughtcrime.securesms.recipients.Recipient$MissingAddressError: Missing address for 1943
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.recipients.Recipient.requireE164(Recipient.java:723)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.lambda$getUpdateDisplayBody$15(MessageRecord.java:255)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.$r8$lambda$dyMKv0oyxuP2TB01A-PNsMLNa4A(MessageRecord.java:0)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord$$ExternalSyntheticLambda7.apply(R8$$SyntheticClass:0)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.lambda$fromRecipient$20(MessageRecord.java:377)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.$r8$lambda$rbqyp_8YOLKiNqJpt8xoLU4cPkI(MessageRecord.java:0)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord$$ExternalSyntheticLambda0.create(R8$$SyntheticClass:0)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.UpdateDescription.getSpannable(UpdateDescription.java:126)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.getDisplayBody(MessageRecord.java:171)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.getDisplayBody(MessageRecord.java:163)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MmsMessageRecord.getDisplayBody(MmsMessageRecord.java:222)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.PlaintextBackupExporter.exportPlaintext(PlaintextBackupExporter.java:63)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.PlaintextBackupExporter.exportPlaintextToSd(PlaintextBackupExporter.java:24)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.ImportExportFragment$ExportPlaintextTask.doInBackground(ImportExportFragment.java:316)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.ImportExportFragment$ExportPlaintextTask.doInBackground(ImportExportFragment.java:301)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[6.45.1.0-JW] [5933 ] 2024-01-27 16:08:12.030 GMT+01:00 E SignalUncaughtException: 	... 3 more
```

### Steps to reproduce
- I don't know how to willingly keep someone a group member after unregistering.

### Device info
**Device:** Samsug A50
**Android version:** 11
**Signal version:** 6.45.1

### Link to debug log
https://debuglogs.org/android/6.45.1-JW/ee04d150a03d0916ad5012ce55128a0e5e4c3fa9580905fb7e136ec4a4d03564

I can provide the recipient record for user 1943 if that would help. unregistered_timestamp is set.

**Comment by johanw666** [comment]
BTW, when I try the same from Signal desktop I just get a message that the user is unregistered without a crash. I did exchange messages with this user in the past.

**Comment by johanw666** [comment]
Another thing I noticed: I have had a xonversation with this user in the past, when I open it on desktop it just ahows it, when I open it on Android I get the same crash.

**Comment by johanw666** [comment]
6.45.2 didn't fix the crash. I removed the conversation with this contct but now I get the same crash on another contact:
```
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.lang.Thread.run(Thread.java:923)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: Caused by: org.thoughtcrime.securesms.recipients.Recipient$MissingAddressError: Missing address for 4620
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.recipients.Recipient.requireE164(Recipient.java:723)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.lambda$getUpdateDisplayBody$15(MessageRecord.java:255)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.$r8$lambda$dyMKv0oyxuP2TB01A-PNsMLNa4A(MessageRecord.java:0)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord$$ExternalSyntheticLambda7.apply(R8$$SyntheticClass:0)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.lambda$fromRecipient$20(MessageRecord.java:377)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.$r8$lambda$rbqyp_8YOLKiNqJpt8xoLU4cPkI(MessageRecord.java:0)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord$$ExternalSyntheticLambda0.create(R8$$SyntheticClass:0)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.UpdateDescription.getSpannable(UpdateDescription.java:126)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.getDisplayBody(MessageRecord.java:171)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MessageRecord.getDisplayBody(MessageRecord.java:163)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.model.MmsMessageRecord.getDisplayBody(MmsMessageRecord.java:222)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.PlaintextBackupExporter.exportPlaintext(PlaintextBackupExporter.java:63)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.database.PlaintextBackupExporter.exportPlaintextToSd(PlaintextBackupExporter.java:24)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.ImportExportFragment$ExportPlaintextTask.doInBackground(ImportExportFragment.java:316)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.ImportExportFragment$ExportPlaintextTask.doInBackground(ImportExportFragment.java:301)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[6.45.2.0-JW] [23083] 2024-02-01 09:18:40.144 GMT+01:00 E SignalUncaughtException: 	... 3 more
```
Debug log: https://debuglogs.org/android/6.45.2-JW/1933964984975023b54690b26800d9128f7ea535c4fdc0e924d75a97deec5b6c

**Comment by johanw666** [comment]
I'm pleased that 6.46.0 solves the issue.
