### ISSUE TITLE
Unable to sync pre keys, fails with 422 Unprocessable

### ISSUE THREAD

**Issue by jethrogb** [signalapp/Signal-Android#13434]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm not able to send any messages. The outbound messages show as "pending" indefinitely. I was able to send messages fine before today. Receiving messages still works fine. I haven't made any changes to my phone OS, last Signal app update was Feb 8.

I'm seeing a lot of these errors in the debug log:
```
org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [422] Bad response: 422 Unprocessable Entity
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2131)
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2069)
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2006)
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2000)
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.registerPreKeys(PushServiceSocket.java:782)
```

### Device info
```
============ SYSINFO ============
Time              : 1708346764202
Manufacturer      : asus
Model             : ASUS_AI2302
Product           : WW_AI2302
Screen            : 1080x2181, xxhdpi (440), 60.00 hz
Font Scale        : 1.0
Animation Scale   : 0.0
Android           : 14, API 34 (34.1004.0204.88, UKQ1.230917.001.34.1004.0204.88 release-keys)
ABIs              : arm64-v8a, armeabi-v7a, armeabi
Memory            : 137M (60.51% free, 768M max)
Memclass          : 256
MemInfo           : availMem: 1626 mb, totalMem: 7215 mb, threshold: 300 mb, lowMemory: false
OS Host           : builder2021-RS720-E9-RS8-G
RecipientId       : RecipientId::1
ACI               : ********-****-****-****-*********4c8
Device ID         : 1
Censored          : false
Network Status    : [isOnVpn: false, isMetered: false]
Data Saver        : DISABLED
Play Services     : true
FCM               : false
BkgRestricted     : false
Locale            : en_NL
Linked Devices    : false
First Version     : 1380
Days Installed    : 14
Build Variant     : playProdRelease
Emoji Version     : 8 (xhdpi)
RenderBigEmoji    : true
DontKeepActivities: false
Server Time Offset: -11 ms (last updated: 1708346748989)
Telecom           : false
User-Agent        : Signal-Android/6.46.7 Android/34
SlowNotifications : false
PotentiallyBattery: true
App               : Signal 6.46.7 (1388, 138802) (ca3d239ce29b) 
Package           : org.thoughtcrime.securesms (doDiFGKPO1r)
```

### Link to debug log
```
[6.46.7] [74   ] 2024-02-19 13:45:35.600 GMT+01:00 I JobRunner: [JOB::f3b0c43b-1341-44ff-958c-ea83c7bc68ca][ServiceOutageDetectionJob][3] Running job. (Time Since Submission: 2 ms, Lifespan: Immortal, Run Attempt: 1/5, Queue: ServiceOutageDetectionJob)
[6.46.7] [74   ] 2024-02-19 13:45:35.604 GMT+01:00 I ServiceOutageDetectionJ: onRun()
[6.46.7] [74   ] 2024-02-19 13:45:35.617 GMT+01:00 I ServiceOutageDetectionJ: Received outage check address: ...ipv4...
[6.46.7] [74   ] 2024-02-19 13:45:35.617 GMT+01:00 I ServiceOutageDetectionJ: Service is available.
[6.46.7] [74   ] 2024-02-19 13:45:35.618 GMT+01:00 I JobRunner: [JOB::f3b0c43b-1341-44ff-958c-ea83c7bc68ca][ServiceOutageDetectionJob][3] Job finished with result SUCCESS in 18 ms. (Time Since Submission: 20 ms, Lifespan: Immortal, Run Attempt: 1/5, Queue: ServiceOutageDetectionJob)

[...]

[6.46.7] [74   ] 2024-02-19 13:45:46.581 GMT+01:00 I JobRunner: [JOB::79999238-e284-47c1-b06f-0dca7332447c][IndividualSendJob][3] Running job. (Time Since Submission: 8742982 ms, Lifespan: 86400000 ms, Run Attempt: 108/Unlimited, Queue: RecipientId::15)
[6.46.7] [74   ] 2024-02-19 13:45:46.583 GMT+01:00 I SendJob: Starting message send attempt
[6.46.7] [74   ] 2024-02-19 13:45:46.583 GMT+01:00 W PushSendJob: [JOB::79999238-e284-47c1-b06f-0dca7332447c][IndividualSendJob] It's been too long since rotating our signed prekeys (ACI: 128217922 ms, PNI: 1249821215 ms)! Attempting to rotate now. (Time Since Submission: 8742984 ms, Lifespan: 86400000 ms, Run Attempt: 108/Unlimited, Queue: RecipientId::15)
[6.46.7] [74   ] 2024-02-19 13:45:46.584 GMT+01:00 I Job: [JOB::611e6ba4-f24f-4003-ad69-d08df2396c62][PreKeysSyncJob] onSubmit() (Time Since Submission: 1 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[6.46.7] [73   ] 2024-02-19 13:45:46.588 GMT+01:00 I JobRunner: [JOB::611e6ba4-f24f-4003-ad69-d08df2396c62][PreKeysSyncJob][2] Running job. (Time Since Submission: 4 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[6.46.7] [main ] 2024-02-19 13:45:46.663 GMT+01:00 I JobSchedulerScheduler: Waking due to job: -1733499378
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeysSyncJob: [ACI] No need to rotate signed prekey. TimeSinceLastRotation: 128218031 ms (1.4840049884259259 days)
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeysSyncJob: [ACI] There are 60 one-time EC prekeys available, which is enough.
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeysSyncJob: [ACI] No need to rotate last-resort kyber prekey. TimeSinceLastRotation: 128218031 ms (1.4840049884259259 days)
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeysSyncJob: [ACI] There are 60 one-time kyber prekeys available, which is enough.
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeysSyncJob: [ACI] No prekeys to upload.
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeysSyncJob: [ACI] Cleaning prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.692 GMT+01:00 I PreKeyUtil: Cleaning signed prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.693 GMT+01:00 I PreKeyUtil: Cleaning kyber prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.697 GMT+01:00 I OneTimePreKeyTable: Deleted 0 stale one-time EC prekeys.
[6.46.7] [73   ] 2024-02-19 13:45:46.701 GMT+01:00 I KyberPreKeyTable: Deleted 0 stale one-time EC prekeys.
[6.46.7] [73   ] 2024-02-19 13:45:46.814 GMT+01:00 I PreKeysSyncJob: [PNI] Rotating signed prekey. SignedPreKeyRegistered: true, TimeSinceLastRotation: 1249821446 ms (14.46552599537037 days)
[6.46.7] [73   ] 2024-02-19 13:45:46.814 GMT+01:00 I PreKeyUtil: Generating signed prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.815 GMT+01:00 I PreKeyUtil: Storing signed prekey...
[6.46.7] [73   ] 2024-02-19 13:45:46.816 GMT+01:00 I PreKeysSyncJob: [PNI] There are 0 one-time EC prekeys available, which is less than our threshold. Need more.
[6.46.7] [73   ] 2024-02-19 13:45:46.816 GMT+01:00 I PreKeyUtil: Generating one-time EC prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.832 GMT+01:00 I PreKeyUtil: Storing one-time EC prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.840 GMT+01:00 I PreKeysSyncJob: [PNI] Rotating last-resort kyber prekey. TimeSinceLastRotation: 1249821470 ms (14.465526273148148 days)
[6.46.7] [73   ] 2024-02-19 13:45:46.840 GMT+01:00 I PreKeyUtil: Storing kyber prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:46.840 GMT+01:00 I PreKeysSyncJob: [PNI] There are 0 one-time kyber prekeys available, which is less than our threshold. Need more.
[6.46.7] [73   ] 2024-02-19 13:45:46.840 GMT+01:00 I PreKeyUtil: Generating one-time kyber prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:47.049 GMT+01:00 I PreKeyUtil: Storing one-time kyber prekeys...
[6.46.7] [73   ] 2024-02-19 13:45:47.103 GMT+01:00 I PreKeysSyncJob: [PNI] Something to upload. SignedPreKey: true, OneTimeEcPreKeys: true, LastResortKyberPreKey: true, OneTimeKyberPreKeys: true
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob: [JOB::611e6ba4-f24f-4003-ad69-d08df2396c62][PreKeysSyncJob] Encountered a failing exception. (Time Since Submission: 780 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: [422] Bad response: 422 Unprocessable Entity
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:2131)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2069)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2006)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2000)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.whispersystems.signalservice.internal.push.PushServiceSocket.registerPreKeys(PushServiceSocket.java:782)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.whispersystems.signalservice.api.SignalServiceAccountManager.setPreKeys(SignalServiceAccountManager.java:342)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.syncPreKeys(PreKeysSyncJob.kt:146)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.thoughtcrime.securesms.jobs.PreKeysSyncJob.onRun(PreKeysSyncJob.kt:111)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob:   at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W BaseJob: 
[6.46.7] [73   ] 2024-02-19 13:45:47.363 GMT+01:00 W JobRunner: [JOB::611e6ba4-f24f-4003-ad69-d08df2396c62][PreKeysSyncJob][2] Job failed. (Time Since Submission: 780 ms, Lifespan: 2592000000 ms, Run Attempt: 1/Unlimited, Queue: PreKeysSyncJob)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob: [JOB::79999238-e284-47c1-b06f-0dca7332447c][IndividualSendJob] Encountered a retryable exception. (Time Since Submission: 8743765 ms, Lifespan: 86400000 ms, Run Attempt: 108/Unlimited, Queue: RecipientId::15)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob: org.thoughtcrime.securesms.transport.RetryLaterException: org.thoughtcrime.securesms.TextSecureExpiredException: Failed to refresh prekeys! State: FAILURE
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob:   at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:122)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob:   at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:42)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob:   at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob:   at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob:   at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob: Caused by: org.thoughtcrime.securesms.TextSecureExpiredException: Failed to refresh prekeys! State: FAILURE
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob:   ... 5 more
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I BaseJob: 
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I JobRunner: [JOB::79999238-e284-47c1-b06f-0dca7332447c][IndividualSendJob][3] Job finished with result RETRY in 783 ms. (Time Since Submission: 8743765 ms, Lifespan: 86400000 ms, Run Attempt: 108/Unlimited, Queue: RecipientId::15)
[6.46.7] [74   ] 2024-02-19 13:45:47.364 GMT+01:00 I JobController: [JOB::79999238-e284-47c1-b06f-0dca7332447c][IndividualSendJob] Scheduling a retry in 63249 ms. (Time Since Submission: 8743765 ms, Lifespan: 86400000 ms, Run Attempt: 108/Unlimited, Queue: RecipientId::15)
```

**Comment by jethrogb** [comment]
Resolved after I transferred to another device and back again
