### ISSUE TITLE
Secure Value Recovery (SVR2) returns 404 upon PIN entry

### ISSUE THREAD

**Issue by miles992** [signalapp/Signal-Android#13458]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The SVR2 is returning a 404 if the user tries to enter their PIN during switch of mobile devices. 

It is impossible to move the account to a new device, but due to the started process the old device is already de-registered. This is a blocker for customer operation.

There is a very similar issue reported November 23, which is marked as fixed here:
https://github.com/signalapp/Signal-Android/issues/13275

### Steps to reproduce
- try to register an existing account with set PIN on a new device

**Actual result:** A "Error connecting to service" error is displayed if the correct PIN is entered. Logs show a 404 error.
**Expected result:** Account is loaded and operable on the new device

### Device info
**Device:** Google Pixel
**Android version:** Android 14, latest offical
**Signal version:** latest from website (downloaded today)

### Link to debug log
logcat:
```
03-03 09:29:39.309  5461  5589 I SvrRepository: [restoreMasterKeyPreRegistration] Network error. SVR2::6ee1042f9e20f880326686dd4ba50c25359f01e9f733eeba4382bca001d45094
03-03 09:29:39.309  5461  5589 I SvrRepository: java.io.IOException: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
03-03 09:29:39.309  5461  5589 I SvrRepository: at org.whispersystems.signalservice.api.svr.Svr2Socket$SvrWebSocketListener.onFailure(Svr2Socket.kt:163)
03-03 09:29:39.309  5461  5589 I SvrRepository: at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
03-03 09:29:39.309  5461  5589 I SvrRepository: at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
03-03 09:29:39.309  5461  5589 I SvrRepository: at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
03-03 09:29:39.309  5461  5589 I SvrRepository: at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-03 09:29:39.309  5461  5589 I SvrRepository: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-03 09:29:39.309  5461  5589 I SvrRepository: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-03 09:29:39.309  5461  5589 I SvrRepository: at java.lang.Thread.run(Thread.java:1012)
03-03 09:29:39.309  5461  5589 I SvrRepository: Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
03-03 09:29:39.309  5461  5589 I SvrRepository: at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
03-03 09:29:39.309  5461  5589 I SvrRepository: at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
03-03 09:29:39.309  5461  5589 I SvrRepository: ... 5 more
03-03 09:29:39.309  5461  6466 W Svr2Socket: [onFailure] response? true
03-03 09:29:39.309  5461  6466 W Svr2Socket: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
03-03 09:29:39.309  5461  6466 W Svr2Socket: at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
03-03 09:29:39.309  5461  6466 W Svr2Socket: at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
03-03 09:29:39.309  5461  6466 W Svr2Socket: at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
03-03 09:29:39.309  5461  6466 W Svr2Socket: at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-03 09:29:39.309  5461  6466 W Svr2Socket: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-03 09:29:39.309  5461  6466 W Svr2Socket: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-03 09:29:39.309  5461  6466 W Svr2Socket: at java.lang.Thread.run(Thread.java:1012)
03-03 09:29:39.309  5461  6466 W Svr2Socket:
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: Unable to verify code with registration lock
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: java.io.IOException: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at org.whispersystems.signalservice.api.svr.Svr2Socket$SvrWebSocketListener.onFailure(Svr2Socket.kt:163)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at java.lang.Thread.run(Thread.java:1012)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
03-03 09:29:39.312  5461  5461 W BaseRegistrationLockFra: ... 5 more
```

**Comment by SudoJuergens** [comment]
I have a very similar problem, in my case I got de-registered on my old device when trying to activate the new one, but entered the wrong PIN there. Now a week later I try to register my old device again and have the same error message as above. What is a bit concerning now is that although Signal claims I need to enter my PIN to do anything, after the first try I do receive messages on my account again and can even answer them (by clicking on the notifications and answering there instead of in the app), but I am still locked out of the app. In the log file I added both the failing call and that I receive/send messages should be visible. 
[signal-log-1709567745463.zip](https://github.com/signalapp/Signal-Android/files/14484184/signal-log-1709567745463.zip)

**Comment by nicholas-signal** [comment]
This issue is fixed in 7.1

**Comment by miles992** [comment]
> This issue is fixed in 7.1

How to get 7.1? The APK download is still 6.47.5, see here:
https://signal.org/android/apk/

**Comment by alex-signal** [comment]
Hello! 7.1 should be going to beta tomorrow afternoon.

**Comment by miles992** [comment]
Until the beta is released, my account is unusable? I am pretty sure I am not the only person using PIN.

**Comment by Ole-Harald** [comment]
I have the same problem.

**Comment by ichthyosaurus** [comment]
Is there any confirmation that this is actually fixed before it gets auto-closed? Molly closed their issue https://github.com/mollyim/mollyim-android/issues/293...

**Comment by greyson-signal** [comment]
Hi there, according to earlier comments, yes, it was fixed.
