### ISSUE TITLE
Crash on startup (input currency code is not 3-letter alphabetic code)

### ISSUE THREAD

**Issue by vaardan** [signalapp/Signal-Android#13600]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The application crashes after the launch. It does that only with the internet connection. Seems to be related to some kind of currency check.

### Steps to reproduce
Can't really tell. It crashes right after the launch.

**Actual result:** Application crashes a couple of seconds after the launch.
**Expected result:** Application doesn't crash.

### Device info

**Device:** Google Pixel 7
**Android version:** 14 (Graphene OS)
**Signal version:** 7.8.1

### Crash log
```
type: crash
osVersion: google/panther/panther:14/AP2A.240605.024/2024062000:user/release-keys
package: org.thoughtcrime.securesms:142102
process: org.thoughtcrime.securesms
processUptime: 3477 + 255 ms
installer: com.android.vending

java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
	at android.icu.util.Currency.getInstance(Currency.java:289)
	at java.util.Currency.getInstance(Currency.java:278)
	at org.thoughtcrime.securesms.keyvalue.DonationsValues.setSubscriber(DonationsValues.kt:248)
	at org.thoughtcrime.securesms.storage.StorageSyncHelper.applyAccountStorageSyncUpdates(StorageSyncHelper.java:230)
	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.updateLocal(AccountRecordProcessor.java:183)
	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.process(AccountRecordProcessor.java:28)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:413)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at The input currency code is not 3-letter alphabetic code..(:0)
```

### Link to debug log
Adding log as a file. I can't export it so it can be a link because that requires internet connection & that leads to a crash.
[log.txt](https://github.com/user-attachments/files/15936608/log.txt)

**Comment by petre2dor** [comment]
Same issue here.
LineageOS 21 with Google Apps, Oneplus 8T.

**Comment by tkeitzl** [comment]
Same issue here.
Device: Fairphone 3
Android version: 13
Signal version: 7.8.1

**Comment by betrieb** [comment]
Same issue here with LineageOS 19, Android 12, Oneplus 5T

**Comment by vaardan** [comment]
@tkeitzl the v7.9.6 works for me as well

**Comment by santiago-mooser** [comment]
Same issue here. 

Device: Pixel 8
OS: CalyxOS 5.8.0 (Android 14, June 5 security update)
Signal version: 7.8.1
Extra info: The OS uses MicroG instead of google play services, but I don't think that's related to the issue.

Updating to v7.9.6 worked for me too. The app is no longer crashing, but it seems like the error is still there. The error seems to be related to being a subscriber since it's in the `org.thoughtcrime.securesms.keyvalue.DonationsValues.setSubscriber` method. 

Just as extra info: I donate monthly and I pay through the website in Hong Kong Dollar (HKD $29 every month).

```log
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: Setting subscriber for currency 
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: java.lang.Exception
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.keyvalue.DonationsValues.setSubscriber(DonationsValues.kt:241)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.storage.StorageSyncHelper.applyAccountStorageSyncUpdates(StorageSyncHelper.java:230)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.updateLocal(AccountRecordProcessor.java:183)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.process(AccountRecordProcessor.java:28)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:413)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[7.8.1] [4209 ] 2024-06-24 09:19:02.626 GMT+08:00 I DonationsValues: 
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: Encountered a fatal exception. Crash imminent.
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at android.icu.util.Currency.getInstance(Currency.java:289)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at java.util.Currency.getInstance(Currency.java:278)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.keyvalue.DonationsValues.setSubscriber(DonationsValues.kt:248)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.storage.StorageSyncHelper.applyAccountStorageSyncUpdates(StorageSyncHelper.java:230)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.updateLocal(AccountRecordProcessor.java:183)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.process(AccountRecordProcessor.java:28)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:413)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[7.8.1] [4209 ] 2024-06-24 09:19:02.630 GMT+08:00 E BaseJob: 
[7.8.1] [4209 ] 2024-06-24 09:19:02.635 GMT+08:00 E JobRunner: [JOB::56af8707-9cb6-4c07-8315-8da28d515dce][StorageSyncJob][2] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 4122 ms, Lifespan: 86400000 ms, Run Attempt: 1/3, Queue: StorageSyncingJobs)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at android.icu.util.Currency.getInstance(Currency.java:289)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at java.util.Currency.getInstance(Currency.java:278)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.keyvalue.DonationsValues.setSubscriber(DonationsValues.kt:248)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.StorageSyncHelper.applyAccountStorageSyncUpdates(StorageSyncHelper.java:230)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.updateLocal(AccountRecordProcessor.java:183)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:68)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.storage.AccountRecordProcessor.process(AccountRecordProcessor.java:28)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:413)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
[7.8.1] [4209 ] 2024-06-24 09:19:02.639 GMT+08:00 E SignalUncaughtException: 
```

You can find my logs here:
https://debuglogs.org/android/7.9.6/97b55a7c1b1f49edd3509f980f2c6c7aeb6df06977b2094330ecacb4f9ce1382


@vaardan @petre2dor @tkeitzl @betrieb @vaardan do you guys donate as well?

**Comment by vaardan** [comment]
@santiago-mooser yep, I do donate as well

**Comment by betrieb** [comment]
@santiago-mooser I've never donated

**Comment by schoeda** [comment]
Same problem here with a Pixel 8 and i do a donation too.

**Comment by vaardan** [comment]
For the quick fix, if you don't want/know how to manually compile v7.9.6, you can temporarily get the apk from [apk mirror](https://www.apkmirror.com/apk/signal-foundation/signal-private-messenger/signal-private-messenger-7-9-6-release/).

The apk seems fine & it's signed by Signal (Whisper Systems) itself.

**Comment by alex-signal** [comment]
Hi everyone! I've just updated the rollout for 7.9.6 to 100% on production so the build should be available to all without having to go through apk mirror. Sorry for the crash!
