### ISSUE TITLE
Backup chats failing at 0.6%

### ISSUE THREAD

**Issue by smeyerhuky** [signalapp/Signal-Android#13627]
I'm trying to transfer my account to another device and the backup keeps failing. Transfer doesn't work either, no matter what I do it stops after 0.6% with no reason/message provided. 

- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended
- [ x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Backup is failing after 0.6%, the device has over 80gb available and the signal backup is no larger than 8 or 9 GB.

### Steps to reproduce
- enable backup
- start backup
- it fails 

Or
- start Android to Android transfer
- device fails transfer after connecting and starting when it reaches about 0.6%
- retry doesn't work

**Actual Results:**
Backup fails with no error message. 

**Expected result:** 
Backup should succeed

### Screenshots
N/A

### Device info

**Device:** Samsung A32 5G
**Android version:** 13
**Signal version:** 7.12.1 (also tried on lower version pre-beta with same failure)

Debug logs:
https://debuglogs.org/android/7.12.1/f3194a106c0abcdcc1abd04c9ea8cc0069e4b959a020007d88d07e644553a918

I've tried so many different things. I'm trying to transfer the signal account from one device to another. When using the transfer it also fails at about 0.6% with no explanation and won't restart after clicking retry. 

The following error is reported via adb logcat:

07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: Error during backup!
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: java.io.IOException: read failed: EIO (I/O error)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.IoBridge.read(IoBridge.java:614)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at java.io.FileInputStream.read(FileInputStream.java:328)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at java.io.FileInputStream.read(FileInputStream.java:297)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:123)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:225)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.BackupFrameOutputStream.writeStream(BackupFrameOutputStream.java:178)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.BackupFrameOutputStream.write(BackupFrameOutputStream.java:131)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportAttachment(FullBackupExporter.java:470)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.lambda$internalExport$6(FullBackupExporter.java:174)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.$r8$lambda$8F0Ep7yNWnc1QKmxS2FNaMnP_kg(FullBackupExporter.java:0)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter$$ExternalSyntheticLambda5.postProcess(R8$$SyntheticClass:0)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportTable(FullBackupExporter.java:435)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.internalExport(FullBackupExporter.java:174)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.export(FullBackupExporter.java:124)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.LocalBackupJobApi29.onRun(LocalBackupJobApi29.java:142)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.Linux.readBytes(Native Method)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.Linux.read(Linux.java:190)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:325)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	at libcore.io.IoBridge.read(IoBridge.java:604)
07-21 22:35:12.709 18720 18784 W LocalBackupJobApi29: 	... 18 more

**Comment by martinUB** [comment]
Would be interested in a solution as well. Having the same issue. Neither backup nor transfer from android to android will get over 1%. Fails with the above mentioned error codes. Tried different folders for backup and so on. Deleted some big files -> the percentage, which are transferred increase / decrease for some 0.x%, but still the transfer/backup will fail. Did restarts, delete cache and so on. Always the same result. 
Old phone is running android 13.

**Comment by ralf-z** [comment]
I also have the same issue with the latest version 7.17.6 running Android 13 on a Samsung A52s 5G with a similar exception. According to the stack trace it seems the issue is when exporting an attachment. Maybe its possible to handle issues while exporting attachments more gracefully by continuing the backup without the attachment that couldn't be exported instead of completely aborting the backup? I'd rather have an incomplete backup instead of no backup at all.

**Comment by nakato** [comment]
I helped someone running into this issue today, crashing on attachments as above.

They were trying to switch phones, and the phone-to-phone transfer would fail, I could not find any logs on the cause of the failure.  Eventually I tried creating a standard file backup and was able to find the backtrace listed in the opening issue message.

I went through all the attachments in the "Data & Storage" section, and looked for image thumbnails that failed to load, only showing the "blurred image placeholder" (See BlurHash for an example of what that looks like), and deleted those attachments.  Once that was done, I was able to create a backup successfully.  After rebooting both phones I was able to perform the phone-to-phone transfer.

**Comment by smeyerhuky** [comment]
Still no fix. I've run through and cleaned to the few attachments that had thumbnails blurred out and still nothing..

Any help?

**Comment by vglaeser** [comment]
Is there any progress on this? I am facing  the same issue with v7.37.3
