### ISSUE TITLE
Crash on startup: couldn't find "libsqlcipher.so"

### ISSUE THREAD

**Issue by DEVoytas** [signalapp/Signal-Android#13634]
- [x] I have searched open and closed issues for duplicates (only issue mentioning libsqlcipher is #13524)
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After installing Signal version `7.12.2` Signal crashes immediately after opening.

### Steps to reproduce
- Tap on signal icon in launcher

**Actual result:**
"Unfortunately, Signal has stopped."  pop-up message comes up. The application does not start.

**Expected result:**
Application starts and does not crash.

### Screenshots
N/A

### Device info

**Device:** Samsung Galaxy S5, model DM-G900F (it's very old, I know :( )
**Android version:** 6.0.1 (same here)
**Signal version:** 7.12.2

### Log captured from the device with Logcat Reader
```
[08-01 16:40:13.857 25234:25234 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 25234
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.thoughtcrime.securesms-1/base.apk"],nativeLibraryDirectories=[/data/app/org.thoughtcrime.securesms-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.thoughtcrime.securesms.database.SqlCipherLibraryLoader.load(SqlCipherLibraryLoader.kt:17)
	at org.thoughtcrime.securesms.ApplicationContext.lambda$onCreate$0(ApplicationContext.java:151)
	at org.thoughtcrime.securesms.ApplicationContext.$r8$lambda$vv6743ogNBAaQNcivpzBaI7HMLg(ApplicationContext.java:0)
	at org.thoughtcrime.securesms.ApplicationContext$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at org.thoughtcrime.securesms.util.AppStartup.execute(AppStartup.java:145)
	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:224)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
	at android.app.ActivityThread.access$1800(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

I presume the rootcause is that my Android it too old and does not have the `libsqlcipher.so` required by new Signal version so I tried to downgrade to older version (which was was saying that I need to upgrade in X days) that would at least allowed me to backup my messages, but that was not possible (probably for security reasons which makes sense).
Is there any way I can migrate migrate to oter device without loosing the history?

**Comment by alex-signal** [comment]
libsqlcipher is a library that should be shipped with signal. It's possible something is wrong in our abi config. I'll bring this up with the team, thanks for your report!

**Comment by DEVoytas** [comment]
I wouldn't  like to come across as impatient, but is there any update on this?
I am stil not able to start the app and I would like to know whether this may be the upstream issue or something wrong with my device.

**Comment by cody-signal** [comment]
@DEVoytas we don't know anything new about what is happening. You can try updating to a new version. If you use the website apk to install Signal, can also try redownloading it from the web and installing again (DO NOT UNINSTALL FIRST, just install the apk again like an update.

I found an old S5 in my stash, but it's not stock anymore, but is on Android 5, so who knows 🤷🏼

**Comment by cody-signal** [comment]
I'm able to run the app on my S5 running Android 5 with a custom ROM. Knowing how you install and update could be helpful.

**Comment by DEVoytas** [comment]
Thank you very much for quick reply and testing on your own phone @cody-signal!
What is the website apk you recommend to use?
So far I've been using Aurora Store to get Signal, since I don't use Google Play Store (which is what Android download from https://signal.org/download/ redirects to).
Is there any other way of installing Signal (website apk you mentioned) if I don't have Google account (other than building from sources)?

**Comment by cody-signal** [comment]
Interesting the Aurora store intercepts our website routing you to Play Store. Didn't know it hijacked urls like that.

I would recommend installing from https://signal.org/android/apk/ directly. It will also auto-update directly from us going forward.

**Comment by DEVoytas** [comment]
Version from https://signal.org/android/apk/ works fine!
Thank you for your help!
