### ISSUE TITLE
Crash on startup in 7.14.2 in VoiceNotePlaybackService

### ISSUE THREAD

**Issue by gordonxy** [signalapp/Signal-Android#13673]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Hello, the app crashes on start up. Clearing cache, restarting the device and similar things have not helped.

### Steps to reproduce
- not sure what got me into the situation, logs make me believe it might be listening to a voice note?
- start Signal

**Actual result:** the app crashes
**Expected result:** the app does not crash

### Screenshots
-/-

### Device info

**Device:** Motorola G84
**Android version:** 14
**Signal version:** 7.14.2

### Link to debug log

```--------- beginning of crash
--------- beginning of system
--------- beginning of main
2024-08-26 00:18:30.495 29711-29913 OpenGLRenderer
org.thoughtcrime.securesms           E  Unable to match the desired swap
behavior.
2024-08-26 00:18:30.732 29711-29711 VoiceNotePlaybackServic
org.thoughtcrime.securesms           E  Unable to create media session
at all, stopping service to avoid crash.
2024-08-26 00:18:30.780 29711-29711 SignalUncaughtException
org.thoughtcrime.securesms           E
java.util.concurrent.ExecutionException: java.lang.SecurityException:
Session rejected the connection request.
      at
org.thoughtcrime.securesms.components.voice.VoiceNoteMediaController.createMediaControllerAsync(VoiceNoteMediaController.kt:144)
      at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
      at [[ ↓↓ Original trace ↓↓ ]].(:0)
      at
com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
      at
com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:571)
      at
io.reactivex.rxjava3.internal.operators.observable.ObservableFromFuture.subscribeActual(ObservableFromFuture.java:41)
      at
io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13131)
      at
io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
      at
io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
      at
io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
      at java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
      at java.lang.Thread.run(Thread.java:1012)
      at
org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
Caused by: java.lang.SecurityException: Session rejected the connection
request.
      at
androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
      at
androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
      at
androidx.media3.session.MediaController.release(MediaController.java:547)
      at
androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda7.run(R8$$SyntheticClass:0)
      at androidx.media3.common.util.Util.postOrRun(Util.java:824)
      at
androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1957)
      at
androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:105)
      at
androidx.media3.session.MediaControllerStub.$r8$lambda$f7Ccr-KPKS3G9Op4LiHF2cfRqV8(MediaControllerStub.java:0)
      at
androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
      at
androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:349)
      at
androidx.media3.session.MediaControllerStub.$r8$lambda$1mqEmhpt-kfk4BRdU-3KyMUq3ro(MediaControllerStub.java:0)
      at
androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda13.run(R8$$SyntheticClass:0)
      at androidx.media3.common.util.Util.postOrRun(Util.java:824)
      at
androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:341)
      at
androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:103)
      at
androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0(MediaSessionService.java:729)
      at
androidx.media3.session.MediaSessionService$MediaSessionServiceStub.$r8$lambda$WimxQSmf3WLVYVBjoloYH8aR1Jc(MediaSessionService.java:0)
      at
androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
      at android.os.Handler.handleCallback(Handler.java:1000)
      at android.os.Handler.dispatchMessage(Handler.java:104)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-08-26 00:18:31.104 29711-29711 AndroidRuntime
org.thoughtcrime.securesms           E  FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 29711
java.util.concurrent.ExecutionException: java.lang.SecurityException:
Session rejected the connection request.
      at
org.thoughtcrime.securesms.components.voice.VoiceNoteMediaController.createMediaControllerAsync(VoiceNoteMediaController.kt:144)
      at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
      at [[ ↓↓ Original trace ↓↓ ]].(:0)
      at
com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
      at
com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:571)
      at
io.reactivex.rxjava3.internal.operators.observable.ObservableFromFuture.subscribeActual(ObservableFromFuture.java:41)
      at
io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13131)
      at
io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
      at
io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
      at
io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
      at java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
      at java.lang.Thread.run(Thread.java:1012)
      at
org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
      at [[ ↑↑ Original Trace ↑↑ ]].(:0)
      at [[ ↓↓ Exception Message ↓↓ ]].(:0)
      at java.lang.SecurityException: Session rejected the connection
request..(:0)
Caused by: java.lang.SecurityException: Session rejected the connection
request.
      at
androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
      at
androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
      at
androidx.media3.session.MediaController.release(MediaController.java:547)
      at
androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda7.run(R8$$SyntheticClass:0)
      at androidx.media3.common.util.Util.postOrRun(Util.java:824)
      at
androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1957)
      at
androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:105)
      at
androidx.media3.session.MediaControllerStub.$r8$lambda$f7Ccr-KPKS3G9Op4LiHF2cfRqV8(MediaControllerStub.java:0)
      at
androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
      at
androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:349)
      at
androidx.media3.session.MediaControllerStub.$r8$lambda$1mqEmhpt-kfk4BRdU-3KyMUq3ro(MediaControllerStub.java:0)
      at
androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda13.run(R8$$SyntheticClass:0)
      at androidx.media3.common.util.Util.postOrRun(Util.java:824)
      at
androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:341)
      at
androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:103)
      at
androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0(MediaSessionService.java:729)
      at
androidx.media3.session.MediaSessionService$MediaSessionServiceStub.$r8$lambda$WimxQSmf3WLVYVBjoloYH8aR1Jc(MediaSessionService.java:0)
      at
androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
      at android.os.Handler.handleCallback(Handler.java:1000)
      at android.os.Handler.dispatchMessage(Handler.java:104)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024-08-26 00:18:31.104 29711-29711 AndroidRuntime
org.thoughtcrime.securesms           E      at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)```

**Comment by sf-thr** [comment]
Hello, is there any information on when issues in github will be looked at? At the moment the app is completely unusable to me sadly.

**Comment by gordonxy** [comment]
Hello, is there any information on when issues in github will be looked at? At the moment the app is completely unusable to me sadly.

**Comment by nicholas-signal** [comment]
Signal v7.15.4 is now available on Google Play as well as [our website](https://signal.org/android/apk/). Please let us know if the crash is resolved.

**Comment by sf-thr** [comment]
Hello, @nicholas-signal thanks for responding. The crash is unfortunately not resolved.

**Comment by gordonxy** [comment]
Hello, @nicholas-signal thanks for responding. The crash is unfortunately not resolved.

**Comment by gordonxy** [comment]
Maybe catching the ExecutionException from the ListenableFuture in VoiceNoteMediaController:144 could be a start to get the app usable again until a real fix can be found for it. I would greatly appreciate that.

**Comment by nicholas-signal** [comment]
@gordonxy would you mind submitting a new adb log? 532441db24185cc0f0b62a857a98cbee1aff3c95 should have caught the error you first reported, you may be hitting a different one now.

**Comment by gordonxy** [comment]
@nicholas-signal Hello, sorry for the wait, I did not manage the time to get on the computer. I have a new log now though:

<details><summary>Details</summary>
<p>
2024-09-05 16:35:33.138 31891-31936 OpenGLRenderer
org.thoughtcrime.securesms           E  Unable to match the desired swap
behavior.
2024-09-05 16:35:33.613 31891-31891 VoiceNotePlaybackServic
org.thoughtcrime.securesms           E  Unable to create media session
at all, stopping service to avoid crash.
2024-09-05 16:35:33.681 31891-31891 AndroidRuntime
org.thoughtcrime.securesms           E  FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 31891
java.lang.RuntimeException: Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@4c078b0:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
androidx.media3.session.MediaSession.release()' on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void androidx.media3.session.MediaSession.release()' on a null
object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:107)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-09-05 16:35:33.681 31891-31891 SignalUncaughtException
org.thoughtcrime.securesms           E  java.lang.RuntimeException:
Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@4c078b0:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
androidx.media3.session.MediaSession.release()' on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void androidx.media3.session.MediaSession.release()' on a null
object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:107)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

</p>
</details>

**Comment by gordonxy** [comment]
Hello, seems like there is "just" a NPE now, could you maybe catch that one as well, so I can atleast use Signal without the voice media stuff? Would be greatly appreciated, thank you!

**Comment by gordonxy** [comment]
@cody-signal Hey Cody, thanks for the quick reply. Unfortunately this seems to not have caught everything or caused another NPE down the line, I will add another log from 7.16.4:

```
2024-09-12 18:44:21.265 20889-20889 AndroidRuntime
org.thoughtcrime.securesms           E  FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 20889
java.lang.RuntimeException: Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@8926f61:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:117)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-09-12 18:44:21.265 20889-20889 SignalUncaughtException
org.thoughtcrime.securesms           E  java.lang.RuntimeException:
Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@8926f61:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:117)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-09-12 18:44:31.945 21017-21121 OpenGLRenderer
org.thoughtcrime.securesms           E  Unable to match the desired swap
behavior.
2024-09-12 18:44:32.348 21017-21017 VoiceNotePlaybackServic
org.thoughtcrime.securesms           E  Unable to create media session
at all, stopping service to avoid crash.
2024-09-12 18:44:32.378 21017-21017 AndroidRuntime
org.thoughtcrime.securesms           E  FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 21017
java.lang.RuntimeException: Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@4e3e4a7:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:117)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-09-12 18:44:32.379 21017-21017 SignalUncaughtException
org.thoughtcrime.securesms           E  java.lang.RuntimeException:
Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@4e3e4a7:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:117)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-09-12 18:44:52.641 21249-21285 OpenGLRenderer
org.thoughtcrime.securesms           E  Unable to match the desired swap
behavior.
2024-09-12 18:44:52.967 21249-21249 VoiceNotePlaybackServic
org.thoughtcrime.securesms           E  Unable to create media session
at all, stopping service to avoid crash.
2024-09-12 18:44:53.008 21249-21249 AndroidRuntime
org.thoughtcrime.securesms           E  FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 21249
java.lang.RuntimeException: Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@64dfcba:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:117)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
2024-09-12 18:44:53.009 21249-21249 SignalUncaughtException
org.thoughtcrime.securesms           E  java.lang.RuntimeException:
Unable to stop service
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService@64dfcba:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4995)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService$KeyClearedReceiver.unregister()'
on a null object reference
      at
org.thoughtcrime.securesms.components.voice.VoiceNotePlaybackService.onDestroy(VoiceNotePlaybackService.java:117)
      at
android.app.ActivityThread.handleStopService(ActivityThread.java:4975)
      at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown
Source:0)
      at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
      at android.os.Handler.dispatchMessage(Handler.java:111)
      at android.os.Looper.loopOnce(Looper.java:242)
      at android.os.Looper.loop(Looper.java:362)
      at android.app.ActivityThread.main(ActivityThread.java:8407)
      at java.lang.reflect.Method.invoke(Native Method)
      at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
```

**Comment by gordonxy** [comment]
@cody-signal This seems to have worked, thank you very much! I leave the closing to you, since you might want to investigate the root of the original crash. If I can be of help there with any logs, let me know.

Have a great weekend!
