### ISSUE TITLE
Notifications not being delivered without "Contacts" permission

### ISSUE THREAD

**Issue by lgfa29** [signalapp/Signal-Android#13671]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After updating the Android OS (to version 15 build number `AP41.240726.009`) and the Signal app (to version 7.15.1), I stopped receiving notifications for any activity (new message, incoming call etc.), but only for the Signal app (all other apps worked fine).

Looking through the debug logs I found this runtime exception stack trace:

```
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: java.lang.SecurityException: UID 10303 does not have permission to content://com.android.contacts/contacts/lookup/680i1849e7050f301d0d.2399r307-422A4C5A403A2A3652503A324C4C325C.3789r372-422A4C5A403A2A3652503A324C4C325C/2374 [user 0]
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.os.Parcel.createException(Parcel.java:3226)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.os.Parcel.readException(Parcel.java:3209)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.os.Parcel.readException(Parcel.java:3151)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3240)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:755)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at android.app.NotificationManager.notify(NotificationManager.java:705)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:290)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:271)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.ActiveCallManager.update(ActiveCallManager.kt:189)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.ActiveCallManager$Companion.update(ActiveCallManager.kt:80)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.ActiveCallManager.update(ActiveCallManager.kt:0)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.WebRtcCallService.update(WebRtcCallService.java:96)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.WebRtcInteractor.setCallInProgressNotification(WebRtcInteractor.java:98)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.IncomingCallActionProcessor.handleLocalRinging(IncomingCallActionProcessor.java:211)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$onCallEvent$52(SignalCallManager.java:610)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$nm0MtD3jFLYyqfYhLQZTfdS0ReU(SignalCallManager.java:0)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda7.process(R8$$SyntheticClass:0)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$process$0(SignalCallManager.java:210)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$s7jZ5qAaqdaNwJjDQSUaDVOqJks(SignalCallManager.java:0)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda26.run(R8$$SyntheticClass:0)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at java.lang.Thread.run(Thread.java:1012)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: Caused by: android.os.RemoteException: Remote stack trace:
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1359)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1432)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at com.android.server.uri.UriGrantsManagerService.-$$Nest$mcheckGrantUriPermissionUnlocked(UriGrantsManagerService.java:0)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermission(UriGrantsManagerService.java:1640)
[7.15.1] [192  ] 2024-08-23 12:52:21.266 EDT I ActiveCallManager: 	at com.android.server.notification.NotificationRecord.visitGrantableUri(NotificationRecord.java:1502)
```

After granting the `Contacts` permission to the Signal app notifications started working again, and removing it causes them to start failing again.

I'm part of the Android and Signal app beta programs, and updated both at the same time, so I'm not sure which updated started causing the problem.

### Steps to reproduce
- Update to latest Android 15 beta.
- Update Signal app to the latest beta version.
- Remove the `Contacts` permission from the Signal app.
- Close the app and receive a message.

**Actual result:** No notification.
**Expected result:** A notification for the new message is received.

### Screenshots

N/A

### Device info

**Device:** Pixel 7 Pro
**Android version:** 15 (`AP41.240726.009`)
**Signal version:** 7.15.1

### Link to debug log
https://debuglogs.org/android/7.15.1/1931f80b714c33e10f852758966513d81a522d36a33217b0dd206ac057d0420d

**Comment by lgfa29** [comment]
Thank you for the fix @cody-signal! I just confirmed that notifications are working again without Contacts permission when using Signal v7.16.2 and Android 15 🙂
