### ISSUE TITLE
Immediate crash after latest Play Store update 

### ISSUE THREAD

**Issue by EmilVogt** [signalapp/Signal-Android#13711]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I just received the automatic update via Google's Play Store to version 7.17.6. Now, upon opening the app, Signal immediately crashes, even before I can unlock the app. Putting the device into flight mode does not help.

### Steps to reproduce
- open app from homescreen
- app immediately closes/crashes

**Actual result:** App crashes
**Expected result:** I can unlock the app

### Screenshots

There's nothing to screenshot 

### Device info

**Device:** Samsung Galaxy A52s 5G
**Android version:** 14
**Signal version:** 7.17.6

### Link to debug log

Unfortunately not possible.

**Comment by tnixeu** [comment]
I think I have the same problem on my Samsung device, Samsung S7 with Android 8. On this phone the Signal is not locked, moments after the app is started I can see a few chats but then it crashes.

**Comment by EmilVogt** [comment]
I took a debug log with `adb logcat` and got a lot of crashes of the same type:
```
--------- beginning of crash
09-25 00:57:47.275 19462 19657 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-4
09-25 00:57:47.275 19462 19657 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 19462
09-25 00:57:47.275 19462 19657 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=32 dstPos=0 length=32
09-25 00:57:47.275 19462 19657 E AndroidRuntime: 	at java.lang.System.arraycopy(Native Method)
09-25 00:57:47.275 19462 19657 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.util.Util.split(Util.java:53)
09-25 00:57:47.275 19462 19657 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.<init>(AttachmentCipherOutputStream.java:39)
09-25 00:57:47.275 19462 19657 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BackfillDigestJob.run(BackfillDigestJob.kt:82)
09-25 00:57:47.275 19462 19657 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
09-25 00:57:47.275 19462 19657 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
09-25 00:57:47.351 19462 19656 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
09-25 00:57:47.351 19462 19656 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 19462
09-25 00:57:47.351 19462 19656 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=32 dstPos=0 length=32
09-25 00:57:47.351 19462 19656 E AndroidRuntime: 	at java.lang.System.arraycopy(Native Method)
09-25 00:57:47.351 19462 19656 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.util.Util.split(Util.java:53)
09-25 00:57:47.351 19462 19656 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.<init>(AttachmentCipherOutputStream.java:39)
09-25 00:57:47.351 19462 19656 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BackfillDigestJob.run(BackfillDigestJob.kt:82)
09-25 00:57:47.351 19462 19656 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
09-25 00:57:47.351 19462 19656 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
[...]
09-25 18:15:19.890 12961 13145 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
09-25 18:15:19.890 12961 13145 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12961
09-25 18:15:19.890 12961 13145 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=32 dstPos=0 length=32
09-25 18:15:19.890 12961 13145 E AndroidRuntime: 	at java.lang.System.arraycopy(Native Method)
09-25 18:15:19.890 12961 13145 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.util.Util.split(Util.java:53)
09-25 18:15:19.890 12961 13145 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.<init>(AttachmentCipherOutputStream.java:39)
09-25 18:15:19.890 12961 13145 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BackfillDigestJob.run(BackfillDigestJob.kt:82)
09-25 18:15:19.890 12961 13145 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
09-25 18:15:19.890 12961 13145 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
09-25 18:16:37.645 14294 14409 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
09-25 18:16:37.645 14294 14409 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 14294
09-25 18:16:37.645 14294 14409 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=0 dst.length=32 dstPos=0 length=32
09-25 18:16:37.645 14294 14409 E AndroidRuntime: 	at java.lang.System.arraycopy(Native Method)
09-25 18:16:37.645 14294 14409 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.util.Util.split(Util.java:53)
09-25 18:16:37.645 14294 14409 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.<init>(AttachmentCipherOutputStream.java:39)
09-25 18:16:37.645 14294 14409 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BackfillDigestJob.run(BackfillDigestJob.kt:82)
09-25 18:16:37.645 14294 14409 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
09-25 18:16:37.645 14294 14409 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
--------- beginning of system
```

This now looks to me the same as reported in  #13697. I also have very old chat history (> 10 years), if this is relevant. Could you please have a look, as Signal is currently unusable for me? Thanks a lot!

**Comment by EmilVogt** [comment]
Closing as duplicate of #13697
