### ISSUE TITLE
Deadlock on startup with corrupt wallpaper file (WallpaperStorageMigrationJob)

### ISSUE THREAD

**Issue by cpfeiffer** [signalapp/Signal-Android#13769]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

I had a 0-bytes-sized wallpaper file for unknown reason, causing Signal to hang indefinitely on startup:

-rw-------  1 u0_a34 u0_a34       0 2022-09-21 23:29 wallpaper7777480446804193503.webp

```
I WallpaperStorageMigrati: There are 9 wallpapers to migrate.
W MigrationJob: [JOB::4bc2167d-e87d-481b-abd7-c9b6644b6dbc][WallpaperStorageMigrationJob] Encountered a retryable exception. (Time Since Submission: 1481960144 ms, Lifespan: Immortal, Run Attempt: 6581/Unlimited, Queue: MIGRATION)
W MigrationJob: java.io.IOException: Prematurely reached end of stream!
W MigrationJob:  at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.readFully(ModernDecryptingPartInputStream.java:80)
W MigrationJob:  at org.thoughtcrime.securesms.crypto.ModernDecryptingPartInputStream.createFor(ModernDecryptingPartInputStream.java:39)
W MigrationJob:  at org.thoughtcrime.securesms.util.storage.FileStorage.getInputStream(FileStorage.java:102)
W MigrationJob:  at org.thoughtcrime.securesms.util.storage.FileStorage.read(FileStorage.java:56)
W MigrationJob:  at org.thoughtcrime.securesms.migrations.WallpaperStorageMigrationJob.performMigration(WallpaperStorageMigrationJob.kt:53)
W MigrationJob:  at org.thoughtcrime.securesms.migrations.MigrationJob.run(MigrationJob.java:42)
W MigrationJob:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
W MigrationJob:  at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
```

Most likely introduced with https://github.com/signalapp/Signal-Android/commit/a7bdfb6d7692602f6f893461659ad7641f84ba6b

### Device

MotoX4

### Android version

13

### Signal version

7.22.2

**Comment by cpfeiffer** [comment]
I manually deleted the offending file in `/data/data/org.thoughtcrime.securesms/app_wallpapers/` making the migration successful and allowing Signal to work again.

**Comment by cpfeiffer** [comment]
Thanks a lot! :heart:
