### ISSUE TITLE
HtcLinkifier?

### ISSUE THREAD

**Issue by moxie0** [signalapp/Signal-Android#2452]
From the play store crash browser.

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.htc.HtcLinkifyDispatcher/com.htc.HtcLinkifyDispatcher.HtcLinkifyDispatcherActivity}; have you declared this activity in your AndroidManifest.xml?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1634)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1510)
at android.app.Activity.startActivityForResult(Activity.java:3251)
at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
at android.app.Activity.startActivity(Activity.java:3358)
at android.text.style.LinkifyURLSpan.onClick(LinkifyURLSpan.java:73)
at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:212)
at android.widget.TextView.onTouchEvent(TextView.java:8835)
at android.view.View.dispatchTouchEvent(View.java:5579)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1982)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1441)
at android.app.Dialog.dispatchTouchEvent(Dialog.java:769)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1930)
at android.view.View.dispatchPointerEvent(View.java:5759)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2970)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2529)
at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:869)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2538)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:4945)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mcginty** [comment]
That looks like an HTC bug

**Comment by mcginty** [comment]
is this common?

**Comment by moxie0** [comment]
It's not the top crash or anything, but it's happening.  I know that these bugs are problems with HTC or LGE or whoever not doing things correctly, but unfortunately it's ultimately our responsibility to deal with it.

**Comment by rhodey** [comment]
relevant reading material:

http://commonsware.com/blog/2012/07/24/linkify-problem-detection-mitigation.html
http://stackoverflow.com/questions/13691241/autolink-not-working-on-htc-htclinkifydispatcher

looks like there is a fix but pretty ugly

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
