### ISSUE TITLE
Missed message/Bad encrypted message (with debug log)

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#2514]
I was going from wifi to 3g and missed a message. After a few minutes I got a bad encrypted message, which I believe is the message I missed. Here is the debug log: https://gist.github.com/anonymous/b66acc3c95c4c33aa680

**Comment by rhodey** [comment]
relevant bit

```
W/GcmBroadcastReceiver(24562): GCM message...
W/TextSecureEnvelope(24562): Our MAC: 45 41 11 71 58 72 49 c0 3e 2a 
W/TextSecureEnvelope(24562): Thr MAC: 45 41 11 71 58 72 49 c0 3e 2a 
W/GcmBroadcastReceiver(24562): GCM message...
W/DeliveryReceiptJob(24562): Sending delivery receipt...
W/TextSecureEnvelope(24562): Our MAC: 55 9d 30 b0 a5 6b b2 96 df 5a 
W/TextSecureEnvelope(24562): Thr MAC: 55 9d 30 b0 a5 6b b2 96 df 5a 
W/DeliveryReceiptJob(24562): Sending delivery receipt...
W/PushDecryptJob(24562): org.whispersystems.libaxolotl.InvalidMessageException: No valid sessions.
W/PushDecryptJob(24562): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:290)
W/PushDecryptJob(24562): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:249)
W/PushDecryptJob(24562): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:217)
W/PushDecryptJob(24562): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:71)
W/PushDecryptJob(24562): 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:98)
W/PushDecryptJob(24562): 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:76)
W/PushDecryptJob(24562): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushDecryptJob(24562): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/PushDecryptJob(24562): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/PushDecryptJob(24562): Caused by: org.whispersystems.libaxolotl.InvalidMessageException: Bad Mac!
W/PushDecryptJob(24562): 	at org.whispersystems.libaxolotl.protocol.WhisperMessage.verifyMac(WhisperMessage.java:132)
W/PushDecryptJob(24562): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:314)
W/PushDecryptJob(24562): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:268)
W/PushDecryptJob(24562): 	... 8 more
```

**Comment by kramimus** [comment]
I think I also just ran into this issue. Was in the middle of a chat with a iOS signal user in an area with somewhat flaky wifi and now the 7 most recent messages from the other user are bad encrypted messages.

https://gist.github.com/anonymous/bc65500ae0a211d0903e

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
