### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by agrajaghh** [signalapp/Signal-Android#2824]
I uninstalled and reinstalled ts several times on a test devices (resulting in a new key) which lead to multiple new identity messages on my main device. After accepting some of them I kept getting this crash on TS startup (had to clear data):

```
    986-1026/org.thoughtcrime.securesms E/AndroidRuntime﹕ FATAL EXCEPTION: JobConsumer-0
    Process: org.thoughtcrime.securesms, PID: 986
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
            at org.whispersystems.libaxolotl.protocol.PreKeyWhisperMessage.<init>(PreKeyWhisperMessage.java:48)
            at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:109)
            at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:106)
            at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:87)
            at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
            at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
            at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Sorry, I don't know exactly which steps lead to this, but both devices were running 2.9.2

**Comment by rhodey** [comment]
@moxie0 looks like the crash occurred in `libaxolotl-java` and I'm not hopeful that we can reproduce this. wanna move it over to the [library repo](https://github.com/WhisperSystems/libaxolotl-java) or what? leaving this to you.

**Comment by moxie0** [comment]
it's fine here thanks

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
