### ISSUE TITLE
Textsecure crashed (too many files open)

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3025]
Sometimes it happens that when I'm texting really fast with someone (over push) textsecure crashes. I don't know what it is, but here's the debug log: https://gist.github.com/27f53a8819cc76f8ccc3

**Comment by rhodey** [comment]
There are three distinct exceptions in this log file, summaries provided in the order that they occur.

## android.database.sqlite.SQLiteCantOpenDatabaseException
```
E/SQLiteLog(30177): (14) cannot open file at line 30241 of [00bb9c9ce4]
E/SQLiteLog(30177): (14) os_unix.c:30241: (24) open(/data/data/org.thoughtcrime.securesms/databases/whisper_directory.db-journal) - 
E/SQLiteLog(30177): (14) cannot open file at line 30241 of [00bb9c9ce4]
E/SQLiteLog(30177): (14) os_unix.c:30241: (24) open(/data/data/org.thoughtcrime.securesms/databases/whisper_directory.db-journal) - 
E/SQLiteLog(30177): (14) statement aborts at 16: [SELECT registered FROM directory WHERE number = ?] unable to open database file
E/SQLiteQuery(30177): exception: unable to open database file (code 14); query: SELECT registered FROM directory WHERE number = ?
W/MessageRetrievalService(30177): android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:969)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
W/MessageRetrievalService(30177): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
W/MessageRetrievalService(30177): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.database.TextSecureDirectory.isActiveNumber(TextSecureDirectory.java:98)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.isActiveNumber(PushReceivedJob.java:59)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handle(PushReceivedJob.java:24)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.service.MessageRetrievalService$1.onMessage(MessageRetrievalService.java:89)
W/MessageRetrievalService(30177): 	at org.whispersystems.textsecure.api.TextSecureMessagePipe.read(TextSecureMessagePipe.java:80)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.service.MessageRetrievalService.run(MessageRetrievalService.java:82)
W/MessageRetrievalService(30177): 	at java.lang.Thread.run(Thread.java:856)
W/MessageRetrievalService(30177): Shutting down pipe...
```

## android.database.CursorWindowAllocationException
```
E/CursorWindow(30177): Could not allocate CursorWindow '/data/data/org.thoughtcrime.securesms/databases/whisper_directory.db' of size 2097152 due to error -24.
W/MessageRetrievalService(30177): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=2 (# cursors opened by this proc=2)
W/MessageRetrievalService(30177): 	at android.database.CursorWindow.<init>(CursorWindow.java:108)
W/MessageRetrievalService(30177): 	at android.database.CursorWindow.<init>(CursorWindow.java:100)
W/MessageRetrievalService(30177): 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:289)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
W/MessageRetrievalService(30177): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
W/MessageRetrievalService(30177): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
W/MessageRetrievalService(30177): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.database.TextSecureDirectory.isActiveNumber(TextSecureDirectory.java:98)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.isActiveNumber(PushReceivedJob.java:59)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.jobs.PushReceivedJob.handle(PushReceivedJob.java:24)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.service.MessageRetrievalService$1.onMessage(MessageRetrievalService.java:89)
W/MessageRetrievalService(30177): 	at org.whispersystems.textsecure.api.TextSecureMessagePipe.read(TextSecureMessagePipe.java:80)
W/MessageRetrievalService(30177): 	at org.thoughtcrime.securesms.service.MessageRetrievalService.run(MessageRetrievalService.java:82)
W/MessageRetrievalService(30177): 	at java.lang.Thread.run(Thread.java:856)
```

## java.net.SocketException
```
W/OkHttpClientWrapper(30177): java.net.SocketException: socket failed: EMFILE (Too many open files)
W/OkHttpClientWrapper(30177): 	at libcore.io.IoBridge.socket(IoBridge.java:583)
W/OkHttpClientWrapper(30177): 	at java.net.PlainSocketImpl.create(PlainSocketImpl.java:201)
W/OkHttpClientWrapper(30177): 	at java.net.Socket.checkOpenAndCreate(Socket.java:663)
W/OkHttpClientWrapper(30177): 	at java.net.Socket.setSoTimeout(Socket.java:518)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.Connection.connect(Connection.java:154)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.Call.getResponse(Call.java:262)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.OkHttpClient$1.callGetResponse(OkHttpClient.java:129)
W/OkHttpClientWrapper(30177): 	at com.squareup.okhttp.internal.ws.WebSocket.connect(WebSocket.java:160)
W/OkHttpClientWrapper(30177): 	at org.whispersystems.textsecure.internal.websocket.OkHttpClientWrapper$1.run(OkHttpClientWrapper.java:59)
W/OkHttpClientWrapper(30177): Caused by: libcore.io.ErrnoException: socket failed: EMFILE (Too many open files)
W/OkHttpClientWrapper(30177): 	at libcore.io.Posix.socket(Native Method)
W/OkHttpClientWrapper(30177): 	at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:181)
W/OkHttpClientWrapper(30177): 	at libcore.io.IoBridge.socket(IoBridge.java:568)
W/OkHttpClientWrapper(30177): 	... 13 more
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
