### ISSUE TITLE
OpenGL OutOfResourcesException

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3058]
I swear I was just chatting...
https://gist.github.com/500bd3a3cdeeef632253

**Comment by mcginty** [comment]
```
E/ViewRootImpl( 2852): OutOfResourcesException initializing HW surface
E/ViewRootImpl( 2852): android.view.Surface$OutOfResourcesException: eglMakeCurrent failed EGL_BAD_ALLOC
E/ViewRootImpl( 2852): 	at android.view.HardwareRenderer$GlRenderer.createEglSurface(HardwareRenderer.java:920)
E/ViewRootImpl( 2852): 	at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:748)
E/ViewRootImpl( 2852): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1627)
E/ViewRootImpl( 2852): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1113)
E/ViewRootImpl( 2852): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4481)
E/ViewRootImpl( 2852): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
E/ViewRootImpl( 2852): 	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
E/ViewRootImpl( 2852): 	at android.view.Choreographer.doFrame(Choreographer.java:525)
E/ViewRootImpl( 2852): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
E/ViewRootImpl( 2852): 	at android.os.Handler.handleCallback(Handler.java:615)
E/ViewRootImpl( 2852): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/ViewRootImpl( 2852): 	at android.os.Looper.loop(Looper.java:137)
E/ViewRootImpl( 2852): 	at android.app.ActivityThread.main(ActivityThread.java:4867)
E/ViewRootImpl( 2852): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ViewRootImpl( 2852): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/ViewRootImpl( 2852): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
E/ViewRootImpl( 2852): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
E/ViewRootImpl( 2852): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mcginty** [comment]
We don't use any GLSurfaceViews, which is typically when you see this error. This confuses me.

**Comment by volcano99** [comment]
I don't know how to help. I was chatting really fast with two contacts and it crashed while switching from one conversation to the other

**Comment by McLoo** [comment]
`W/ThreadDatabase( 2852): Cursor count is greater than length!` ??

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
