### ISSUE TITLE
crash - sqlite error, code 14

### ISSUE THREAD

**Issue by ghost** [signalapp/Signal-Android#3060]
I hope I'm not bugging anyone with all my crash reports, feel free to edit the title
https://gist.github.com/anonymous/40b24138db15e9beb7e0

**Comment by agrajaghh** [comment]
````
E/AndroidRuntime(10874): FATAL EXCEPTION: ModernAsyncTask #1
E/AndroidRuntime(10874): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(10874): 	at android.support.v4.a.q$3.done(ModernAsyncTask.java:137)
E/AndroidRuntime(10874): 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(10874): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(10874): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(10874): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(10874): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime(10874): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime(10874): 	at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime(10874): Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
E/AndroidRuntime(10874): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
E/AndroidRuntime(10874): 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:969)
E/AndroidRuntime(10874): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
E/AndroidRuntime(10874): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
E/AndroidRuntime(10874): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
E/AndroidRuntime(10874): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
E/AndroidRuntime(10874): 	at org.thoughtcrime.securesms.util.AbstractCursorLoader.loadInBackground(AbstractCursorLoader.java:72)
E/AndroidRuntime(10874): 	at org.thoughtcrime.securesms.util.AbstractCursorLoader.loadInBackground(AbstractCursorLoader.java:11)
E/AndroidRuntime(10874): 	at android.support.v4.a.a.onLoadInBackground(AsyncTaskLoader.java:242)
E/AndroidRuntime(10874): 	at android.support.v4.a.b.a(AsyncTaskLoader.java:51)
E/AndroidRuntime(10874): 	at android.support.v4.a.b.a(AsyncTaskLoader.java:40)
E/AndroidRuntime(10874): 	at android.support.v4.a.q$2.call(ModernAsyncTask.java:123)
E/AndroidRuntime(10874): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime(10874): 	... 4 more
````

**Comment by rhodey** [comment]
seems related to other crash reported by @volcano99 here #3025. thanks for submitting all these :) crash bugs are the worst.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
