### ISSUE TITLE
crash bug on avatar update (file not found)

### ISSUE THREAD

**Issue by rhodey** [signalapp/Signal-Android#3085]
I was trying to reproduce #3084 when I ran into another crash bug related to images synced with google drive, similar to #3042.

1) create a group
2) update the group avatar with a picture synced to google drive
3) crash

using images synced to google drive, @mcginty was unable to reproduce the behavior I experienced in #3042, the stack traces showed that it was a FileNotFoundException so we concluded it was not a problem with google drive images specifically but poor handing file not found situations which arose from some google drive sync weirdness. I expect that this is again the case here, ie root cause is some file not found situation.

log from 2.12.0 play store release, (presumably) from 28232fc2a5f8ac8ba11283ca9992f1052467d28b: https://gist.github.com/anonymous/4e420a8581fe3a13ac3c

logs from my own debug build, built from d0008b57b5f4b825561a0c4eab14151ab6771f3e with the `build.gradle` from #3072: https://gist.github.com/anonymous/8badb51fb3df0e253c33
https://gist.github.com/anonymous/b87da4d69c3b8a96d74a

**Comment by rhodey** [comment]
yup, `java.io.FileNotFoundException` again :open_file_folder: :see_no_evil: 

```
D/AndroidRuntime( 8705): Shutting down VM
--------- beginning of crash
E/AndroidRuntime( 8705): FATAL EXCEPTION: main
E/AndroidRuntime( 8705): Process: org.thoughtcrime.securesms, PID: 8705
E/AndroidRuntime( 8705): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/com.soundcloud.android.crop.CropImageActivity}: java.lang.IllegalArgumentException: Unknown column requested: _data
E/AndroidRuntime( 8705): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 8705): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 8705): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 8705): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 8705): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8705): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8705): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 8705): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8705): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8705): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 8705): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 8705): Caused by: java.lang.IllegalArgumentException: Unknown column requested: _data
E/AndroidRuntime( 8705): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
E/AndroidRuntime( 8705): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
E/AndroidRuntime( 8705): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
E/AndroidRuntime( 8705): 	at android.content.ContentResolver.query(ContentResolver.java:478)
E/AndroidRuntime( 8705): 	at android.content.ContentResolver.query(ContentResolver.java:422)
E/AndroidRuntime( 8705): 	at com.soundcloud.android.crop.c.a(CropUtil.java:95)
E/AndroidRuntime( 8705): 	at com.soundcloud.android.crop.CropImageActivity.c(CropImageActivity.java:126)
E/AndroidRuntime( 8705): 	at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
E/AndroidRuntime( 8705): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 8705): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 8705): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 8705): 	... 10 more
I/Process ( 8705): Sending signal. PID: 8705 SIG: 9
W/PartProvider(17253): onCreate()
W/PassphraseRequiredActionBarActivity(17253): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(17253): initializeClearKeyReceiver()
E/BitmapFactory(17253): Unable to decode stream: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
W/BitmapDrawable(17253): BitmapDrawable cannot decode
```

**Comment by 2-4601** [comment]
Tried this with a deleted image (#3053) and got the same file not found exception but TS did not crash.
https://gist.github.com/anonymous/7bdd0f40ad431124d7a5
```
E/android-crop( 4658): Error reading image: No such file or directory
E/android-crop( 4658): java.io.FileNotFoundException: No such file or directory
E/android-crop( 4658): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
E/android-crop( 4658): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
E/android-crop( 4658): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
E/android-crop( 4658): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
E/android-crop( 4658): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
E/android-crop( 4658): 	at com.soundcloud.android.crop.CropImageActivity.a(CropImageActivity.java:152)
E/android-crop( 4658): 	at com.soundcloud.android.crop.CropImageActivity.c(CropImageActivity.java:130)
E/android-crop( 4658): 	at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
E/android-crop( 4658): 	at android.app.Activity.performCreate(Activity.java:5990)
E/android-crop( 4658): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/android-crop( 4658): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/android-crop( 4658): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/android-crop( 4658): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/android-crop( 4658): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/android-crop( 4658): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/android-crop( 4658): 	at android.os.Looper.loop(Looper.java:135)
E/android-crop( 4658): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/android-crop( 4658): 	at java.lang.reflect.Method.invoke(Native Method)
E/android-crop( 4658): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/android-crop( 4658): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/android-crop( 4658): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

There's also a `java.io.IOException: Invalid encoding` in the log.
Perhaps because I did not type anything in the name field?

**Comment by rhodey** [comment]
@moxie0 are you seeing any of these kinda traces from the developer console? eg: `java.lang.IllegalArgumentException: Unknown column requested: _data`

**Comment by rhodey** [comment]
I updated our `com.soundcloud.android:android-crop` dependency to 1.0.0 and was unable to reproduce this crash using all the google drive synced images on my device, so looks like they have fixed it. unfortunately they also bumped their minimum API level up to 14 so there is that. also the syntax changed a bit so now:

`new Crop(data.getData()).output(outputFile).asSquare().start(this);`
becomes
`Crop.of(data.getData(), outputFile).asSquare().start(this);`

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
