### ISSUE TITLE
Text message not delivered for certain phone number (unsecured SMS)

### ISSUE THREAD

**Issue by brenns10** [signalapp/Signal-Android#3096]
For one particular contact, I attempt to send an unsecured SMS and immediately the app displays it with a red exclamation mark, saying "Not delivered" and "Tap for details".  I can send unsecured SMS to other contacts just fine, but this one reliably fails.  I plugged my phone into ADB and reproduced the issue while running logcat.  The wall of text below is what looks to be the relevant section from logcat (I expunged the phone number):

```
W/MmsSmsDatabase( 6309): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 15) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 15) ORDER BY date_received DESC) LIMIT 1
I/LatinIME:LogUtils( 1405): Dictionary info: dictionary = ContextualDictionary.en_US ; version = 1430519766 ; date = ?
D/BubblePopupHelper( 1405): BubblePopupHelper has no instance. Hence we cannot call setShowingBubblePopup : false
D/KeyguardUpdateMonitor( 1210): received broadcast com.lge.softkeypad.intent.SHOW
D/NotificationService(  967): updateLightListLocked :r=NotificationRecord(0x43856d78: pkg=android user=UserHandle{-1} id=17040546 tag=null score=0: Notification(pri=0 contentView=android/0x1090064 vibrate=null sound=null defaults=0x0 flags=0x2 kind=[android.system.imeswitcher])), action=2
D/KeyguardUpdateMonitor( 1210): IME visibility change, visible = true
D/LgeQuickCoverNLService( 1210): onNotificationPosted
D/LgeQuickCoverNLService( 1210): onNotificationPosted isNotClearable
D/LgeQuickCoverNLService( 1210): onNotificationPosted isOngoing
D/KeyguardModel( 1210): mReceiver, received action: com.lge.intent.action.NLDataPosted, sendingUserId:0
D/KeyguardModel( 1210): [native noti] MSG_NOTIFICATION_UPDATED received
D/KeyguardModel( 1210): [native noti] handleFolioNotificationPosted(true)
D/QuickCircle( 1210): onRefreshFolioNotificationInfoUpdated(true)
D/LgeQuickCoverNotificationData( 1210): post do NOT update Ongoing, NoClear or low score job
D/LgeQuickCoverNotificationData( 1210): showAll0
D/NotificationService(  967): notification=Notification(pri=0 contentView=android/0x1090064 vibrate=null sound=null defaults=0x0 flags=0x2 kind=[android.system.imeswitcher])
E/AmanattoDataUpdaterHelper( 1405): Failed to get contextual suggestions.
E/AmanattoDataUpdaterHelper( 1405): package name: org.thoughtcrime.securesms
I/dalvikvm( 1495): Jit: resizing JitTable from 4096 to 8192
W/MmsSmsDatabase( 6309): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 15) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 15) ORDER BY date_received ASC)
W/PhoneNumberFormatter( 6309): Got local CC: US
W/PhoneNumberFormatter( 6309): Got local CC: US
W/MessageDatabase( 6309): Updating ID: 1255 to base type: 22
W/MmsSmsDatabase( 6309): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 15) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 15) ORDER BY date_received DESC) LIMIT 1
I/[SystemUI]StatusBar.NetworkController( 1210): onSignalStrengthsChanged signalStrength=SignalStrength: 99 0 -75 -70 -120 -1 -1 20 -103 -10 118 2147483647 2147483647 cdma 14 level=3
D/BubblePopupHelper( 1210): isShowingBubblePopup : false
D/PhoneInterfaceManager( 1440): [PhoneIntfMgr] sigLevel = 3
I/[SystemUI]LGPhoneStatusBarPolicy( 1210): onReceive = android.intent.action.SIG_STR
W/MmsSmsDatabase( 6309): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 15) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 15) ORDER BY date_received ASC)
W/SmsSendJob( 6309): Sending message: 1255
D/[SMS_LD]( 1440): setSmsPriority(), smsPriority = 0
W/SmsSendJob( 6309): java.lang.NullPointerException
W/SmsSendJob( 6309):    at android.os.Parcel.readException(Parcel.java:1478)
W/SmsSendJob( 6309):    at android.os.Parcel.readException(Parcel.java:1426)
W/SmsSendJob( 6309):    at com.android.internal.telephony.ISms$Stub$Proxy.sendText(ISms.java:909)
W/SmsSendJob( 6309):    at android.telephony.SmsManager.sendTextMessage(SmsManager.java:194)
W/SmsSendJob( 6309):    at android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:399)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:99)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.onSend(SmsSendJob.java:55)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/SmsSendJob( 6309):    at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/SmsSendJob( 6309):    at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/SmsSendJob( 6309): Recipient: (***) ***-****
W/SmsSendJob( 6309): Message Parts: 1
D/[SMS_LD]( 1440): setSmsPriority(), smsPriority = 0
W/SmsSendJob( 6309): java.lang.NullPointerException
W/SmsSendJob( 6309):    at android.os.Parcel.readException(Parcel.java:1478)
W/SmsSendJob( 6309):    at android.os.Parcel.readException(Parcel.java:1426)
W/SmsSendJob( 6309):    at com.android.internal.telephony.ISms$Stub$Proxy.sendText(ISms.java:909)
W/SmsSendJob( 6309):    at android.telephony.SmsManager.sendTextMessage(SmsManager.java:194)
W/SmsSendJob( 6309):    at android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:399)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:99)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.onSend(SmsSendJob.java:55)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/SmsSendJob( 6309):    at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/SmsSendJob( 6309):    at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/SmsSendJob( 6309): org.thoughtcrime.securesms.transport.UndeliverableMessageException: java.lang.NullPointerException
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:113)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.onSend(SmsSendJob.java:55)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/SmsSendJob( 6309):    at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/SmsSendJob( 6309):    at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/SmsSendJob( 6309): Caused by: java.lang.NullPointerException
W/SmsSendJob( 6309):    at android.os.Parcel.readException(Parcel.java:1478)
W/SmsSendJob( 6309):    at android.os.Parcel.readException(Parcel.java:1426)
W/SmsSendJob( 6309):    at com.android.internal.telephony.ISms$Stub$Proxy.sendText(ISms.java:909)
W/SmsSendJob( 6309):    at android.telephony.SmsManager.sendTextMessage(SmsManager.java:194)
W/SmsSendJob( 6309):    at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:107)
W/SmsSendJob( 6309):    ... 5 more
W/MessageDatabase( 6309): Updating ID: 1255 to base type: 24
W/MmsSmsDatabase( 6309): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 15) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 15) ORDER BY date_received DESC) LIMIT 1
```
- Phone: LG G2 (Verizon)
- Android: 4.4.2
- TextSecure: 2.12.0

Looking through the code, on [this line](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/jobs/SmsSendJob.java#L94) there's a note about what looks like exactly this error.  I checked for corresponding GitHub issues-- this looks roughly similar to #418, (different file, but it's likely the same one, just refactored into a new place).  In that issue, there was something to do with multipart messages, but I've reproduced this with messages that are as small as a single letter.  Let me know if you need more info.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
