### ISSUE TITLE
Crash while in background

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#3785]
I have got a couple of these recently (reported).
While I'm using some other apps or switching to other apps TS crashes in the background.
https://gist.github.com/anonymous/1afef9541cd27e8bf111

```
E/AndroidRuntime(21016): FATAL EXCEPTION: FinalizerWatchdogDaemon
E/AndroidRuntime(21016): Process: org.thoughtcrime.securesms, PID: 21016
E/AndroidRuntime(21016): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
E/AndroidRuntime(21016):    at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
E/AndroidRuntime(21016):    at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:412)
E/AndroidRuntime(21016):    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
E/AndroidRuntime(21016):    at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
E/AndroidRuntime(21016):    at java.lang.Thread.run(Thread.java:818)
```

Nexus 4, stock 5.1.1, TS 2.23.2, perhaps also 2.22.x versions (and could've been even in 2.21.x) not that frequent to really bother daily usage.

**Comment by moxie0** [comment]
...related to those ANRs?

**Comment by mcginty** [comment]
https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin

doesn't seem like anyone really knows what's going on. some people suspect a google play services issue

**Comment by 2-4601** [comment]
After a long while got another one of these:
https://gist.github.com/anonymous/28bdb0ad6b090801126f
```
E/AndroidRuntime(14859): FATAL EXCEPTION: FinalizerWatchdogDaemon
E/AndroidRuntime(14859): Process: org.thoughtcrime.securesms, PID: 14859
E/AndroidRuntime(14859): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
E/AndroidRuntime(14859): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
E/AndroidRuntime(14859): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:412)
E/AndroidRuntime(14859): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
E/AndroidRuntime(14859): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
E/AndroidRuntime(14859): 	at java.lang.Thread.run(Thread.java:818)
I/Process (14859): Sending signal. PID: 14859 SIG: 9
```
Nexus 4, stock 5.1.1, Signal 3.15.2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
