### ISSUE TITLE
TextSecure crashes when passphrase locked and something is shared to it

### ISSUE THREAD

**Issue by paride** [signalapp/Signal-Android#3990]
This is easy to reproduce:
1. Configure TextSecure so it's locked with a (non cached) passphrase;
2. Share something to it with the Android "Share to" function, for example an image from the Photos app;
3. TextSecure opens and asks for the passphrase. Enter it.
4. Press Unlock. TextSecure crashes.

Debug log:

https://gist.github.com/anonymous/32aae2e2352b96d4bf40

```
E/AndroidRuntime( 5665): FATAL EXCEPTION: main
E/AndroidRuntime( 5665): Process: org.thoughtcrime.securesms, PID: 5665
E/AndroidRuntime( 5665): java.lang.SecurityException: Uid 10099 does not have permission to uri 0 @ content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F3651/ACTUAL/1707585164
E/AndroidRuntime( 5665):    at android.os.Parcel.readException(Parcel.java:1546)
E/AndroidRuntime( 5665):    at android.os.Parcel.readException(Parcel.java:1499)
E/AndroidRuntime( 5665):    at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2430)
E/AndroidRuntime( 5665):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
E/AndroidRuntime( 5665):    at android.app.Activity.startActivityForResult(Activity.java:3745)
E/AndroidRuntime( 5665):    at android.app.Activity.startActivityForResult(Activity.java:3706)
E/AndroidRuntime( 5665):    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
E/AndroidRuntime( 5665):    at android.app.Activity.startActivity(Activity.java:4016)
E/AndroidRuntime( 5665):    at android.app.Activity.startActivity(Activity.java:3984)
E/AndroidRuntime( 5665):    at org.thoughtcrime.securesms.PassphraseActivity$1.onServiceConnected(PassphraseActivity.java:60)
E/AndroidRuntime( 5665):    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
E/AndroidRuntime( 5665):    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
E/AndroidRuntime( 5665):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 5665):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5665):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5665):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 5665):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5665):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5665):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5665):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by 2-4601** [comment]
I can reproduce this only when I share with the (Google) Photos app. Other apps work fine.
Nexus 4, stock 5.1.1, TS 2.25.3, Photos app 1.3.0.101074912

Related: #3307, #3989.

**Comment by Dyras** [comment]
This is still happening for me. This should totally be fixed before a Signal release IMO.

https://gist.github.com/anonymous/12b077d3555c0082beb1

**Comment by bartz1** [comment]
Agreed. But there are so many top priority bugs at the moment... if they had waited to fix all the bugs before releasing Signal then they would've never released it. Better release a broken product than no product at all.
Poe's law applies

**Comment by Dyras** [comment]
I'm not so sure about that. This isn't even something unique to a single type of phone. This affects everybody. The last thing they want is to piss people off the moment they try to share a link.

**Comment by bartz1** [comment]
"Poe's law applies" = "I was being sarcastic" :)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
