### ISSUE TITLE
Crash when registering

### ISSUE THREAD

**Issue by yingchain** [signalapp/Signal-Android#4047]
I have seen this crash on my Samsung S6 - any idea how to fix it? It doesn't let me finish registration. It is reproducible and blocking.  

```
E/AndroidRuntime(22145): Process: org.thoughtcrime.securesms, PID: 22145
E/AndroidRuntime(22145): android.database.sqlite.SQLiteException: null
E/AndroidRuntime(22145):    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
E/AndroidRuntime(22145):    at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
E/AndroidRuntime(22145):    at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:520)
E/AndroidRuntime(22145):    at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:402)
E/AndroidRuntime(22145):    at android.content.ContentResolver.applyBatch(ContentResolver.java:1297)
E/AndroidRuntime(22145):    at org.thoughtcrime.securesms.contacts.ContactsDatabase.setRegisteredUsers(ContactsDatabase.java:113)
E/AndroidRuntime(22145):    at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:67)
E/AndroidRuntime(22145):    at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:250)
E/AndroidRuntime(22145):    at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:204)
E/AndroidRuntime(22145):    at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:59)
E/AndroidRuntime(22145):    at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:91)
E/AndroidRuntime(22145):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(22145):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(22145):    at java.lang.Thread.run(Thread.java:818)
```

**Comment by yingchain** [comment]
Hello... any update on this? Any ideas? It is Android 5.1 if it is important.

**Comment by pmb-msft** [comment]
I am seeing this issue as well. Any clues?

**Comment by moxie0** [comment]
Crash appears to be happening inside Android's code.  You guys running stock or a custom ROM?

**Comment by mcginty** [comment]
@moxie0 shall we take this out of 3.1.0 since it doesn't seem actionable?

**Comment by pmb-msft** [comment]
This seems to be the same issue, and there is a suggested workaround:
http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=285044&listLines=15&startId=zzzzz~

**Comment by barisunver** [comment]
I'm also having this issue, and the canned email response from Signal didn't help at all.

@pmb-msft, I think Samsung deleted that thread. Do you remember the workaround?

**Comment by francwalter** [comment]
Same crash on SGS4 with Stock 5.0.1
Not possible to register, last step crashes.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
