### ISSUE TITLE
fatal exception

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#4202]
https://gist.github.com/538c5f23aa1bf1abee22

This is from yesterday. Picked up phone, TS had crashed.

Android 4.4.4 stock rooted

**Comment by dcherian** [comment]
````
--------- beginning of /dev/log/system
E/AndroidRuntime( 7718): FATAL EXCEPTION: main
E/AndroidRuntime( 7718): Process: org.thoughtcrime.securesms, PID: 7718
E/AndroidRuntime( 7718): java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{429b7460 V.E..... R......D 0,0-684,324} not attached to window manager
E/AndroidRuntime( 7718): 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:370)
E/AndroidRuntime( 7718): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:299)
E/AndroidRuntime( 7718): 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
E/AndroidRuntime( 7718): 	at android.app.Dialog.dismissDialog(Dialog.java:329)
E/AndroidRuntime( 7718): 	at android.app.Dialog.dismiss(Dialog.java:312)
E/AndroidRuntime( 7718): 	at org.thoughtcrime.securesms.ExportFragment$ExportPlaintextTask.onPostExecute(ExportFragment.java:120)
E/AndroidRuntime( 7718): 	at org.thoughtcrime.securesms.ExportFragment$ExportPlaintextTask.onPostExecute(ExportFragment.java:90)
E/AndroidRuntime( 7718): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime( 7718): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime( 7718): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime( 7718): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7718): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7718): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
E/AndroidRuntime( 7718): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7718): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7718): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 7718): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 7718): 	at dalvik.system.NativeStart.main(Native Method)
````

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
