### ISSUE TITLE
Playing audio fails on fast switching between play and pause 

### ISSUE THREAD

**Issue by McLoo** [signalapp/Signal-Android#4636]
As reported in #4625 - not a voice message issue but audio player issue 

Rappid toggling play/pause of an audio (length doesn't matter) seems to start the server multiple times? According to the ports and timeouts?!

Can be a single audio or switching between different audio messages. 

From the second time play is pressed, the toast "Error playing audio" appears and stays as long as you toggle play/pause.

And that "error playing audio" persists until force stopping Signal - even for sane single tapping the play button
Or maybe I have to wait longer... 

```
11-20 07:53:13.119 30147-30147/org.thoughtcrime.securesms W/AudioView: playbutton onClick
11-20 07:53:13.122 30147-30147/org.thoughtcrime.securesms E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
11-20 07:53:13.124 30147-30147/org.thoughtcrime.securesms D/MediaPlayer: Couldn't open file on client side, trying server side
11-20 07:53:13.129 30147-30861/org.thoughtcrime.securesms D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:13.131 30147-30162/org.thoughtcrime.securesms D/MediaHTTPConnection: proxy null port 0
11-20 07:53:13.147 30147-20630/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:13.147 30147-20630/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: accept-encoding : gzip
11-20 07:53:13.147 30147-20630/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: host : 127.0.0.1:60931
11-20 07:53:13.147 30147-20630/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: connection : Keep-Alive
11-20 07:53:13.167 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Should have subtitle controller already set
11-20 07:53:13.167 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: onPrepared
11-20 07:53:13.197 30147-30162/org.thoughtcrime.securesms E/MediaPlayer: error (1, -19)
11-20 07:53:13.205 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Error (1,-19)
11-20 07:53:13.205 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: MediaPlayer Error: 1 , -19
11-20 07:53:13.317 30147-30147/org.thoughtcrime.securesms W/AudioView: pausebutton onClick
11-20 07:53:13.317 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: Stop called!
11-20 07:53:13.537 30147-30147/org.thoughtcrime.securesms W/AudioView: playbutton onClick
11-20 07:53:13.540 30147-30147/org.thoughtcrime.securesms E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
11-20 07:53:13.543 30147-30147/org.thoughtcrime.securesms D/MediaPlayer: Couldn't open file on client side, trying server side
11-20 07:53:13.558 30147-30162/org.thoughtcrime.securesms D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:13.559 30147-30161/org.thoughtcrime.securesms D/MediaHTTPConnection: proxy null port 0
11-20 07:53:13.564 30147-20648/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:13.564 30147-20648/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: accept-encoding : gzip
11-20 07:53:13.564 30147-20648/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: host : 127.0.0.1:51622
11-20 07:53:13.564 30147-20648/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: connection : Keep-Alive
11-20 07:53:13.589 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Should have subtitle controller already set
11-20 07:53:13.589 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: onPrepared
11-20 07:53:13.633 30147-30161/org.thoughtcrime.securesms E/MediaPlayer: error (1, -19)
11-20 07:53:13.637 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Error (1,-19)
11-20 07:53:13.637 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: MediaPlayer Error: 1 , -19
11-20 07:53:13.801 30147-30147/org.thoughtcrime.securesms W/AudioView: pausebutton onClick
11-20 07:53:13.801 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: Stop called!
11-20 07:53:13.989 30147-30147/org.thoughtcrime.securesms W/AudioView: playbutton onClick
11-20 07:53:13.991 30147-30147/org.thoughtcrime.securesms E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
11-20 07:53:13.993 30147-30147/org.thoughtcrime.securesms D/MediaPlayer: Couldn't open file on client side, trying server side
11-20 07:53:14.025 30147-30161/org.thoughtcrime.securesms D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:14.026 30147-30162/org.thoughtcrime.securesms D/MediaHTTPConnection: proxy null port 0
11-20 07:53:14.030 30147-20661/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:14.030 30147-20661/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: accept-encoding : gzip
11-20 07:53:14.030 30147-20661/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: host : 127.0.0.1:36610
11-20 07:53:14.030 30147-20661/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: connection : Keep-Alive
11-20 07:53:14.056 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Should have subtitle controller already set
11-20 07:53:14.056 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: onPrepared
11-20 07:53:14.082 30147-30861/org.thoughtcrime.securesms E/MediaPlayer: error (1, -19)
11-20 07:53:14.101 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Error (1,-19)
11-20 07:53:14.101 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: MediaPlayer Error: 1 , -19
11-20 07:53:14.223 30147-30147/org.thoughtcrime.securesms W/AudioView: pausebutton onClick
11-20 07:53:14.223 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: Stop called!
11-20 07:53:14.456 30147-30147/org.thoughtcrime.securesms W/AudioView: playbutton onClick
11-20 07:53:14.458 30147-30147/org.thoughtcrime.securesms E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
11-20 07:53:14.461 30147-30147/org.thoughtcrime.securesms D/MediaPlayer: Couldn't open file on client side, trying server side
11-20 07:53:14.469 30147-30162/org.thoughtcrime.securesms D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:14.469 30147-30861/org.thoughtcrime.securesms D/MediaHTTPConnection: proxy null port 0
11-20 07:53:14.477 30147-20674/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:14.477 30147-20674/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: accept-encoding : gzip
11-20 07:53:14.477 30147-20674/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: host : 127.0.0.1:47029
11-20 07:53:14.477 30147-20674/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: connection : Keep-Alive
11-20 07:53:14.507 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Should have subtitle controller already set
11-20 07:53:14.507 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: onPrepared
11-20 07:53:14.535 30147-30861/org.thoughtcrime.securesms E/MediaPlayer: error (1, -19)
11-20 07:53:14.543 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Error (1,-19)
11-20 07:53:14.543 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: MediaPlayer Error: 1 , -19
11-20 07:53:14.705 30147-30147/org.thoughtcrime.securesms W/AudioView: pausebutton onClick
11-20 07:53:14.705 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: Stop called!
11-20 07:53:14.892 30147-30147/org.thoughtcrime.securesms W/AudioView: playbutton onClick
11-20 07:53:14.894 30147-30147/org.thoughtcrime.securesms E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
11-20 07:53:14.895 30147-30147/org.thoughtcrime.securesms D/MediaPlayer: Couldn't open file on client side, trying server side
11-20 07:53:14.916 30147-30162/org.thoughtcrime.securesms D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:14.917 30147-30161/org.thoughtcrime.securesms D/MediaHTTPConnection: proxy null port 0
11-20 07:53:14.923 30147-20691/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: user-agent : stagefright/1.2 (Linux;Android 5.1.1)
11-20 07:53:14.923 30147-20691/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: accept-encoding : gzip
11-20 07:53:14.923 30147-20691/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: host : 127.0.0.1:40410
11-20 07:53:14.923 30147-20691/org.thoughtcrime.securesms I/AudioAttachmentServer: Header: connection : Keep-Alive
11-20 07:53:14.941 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Should have subtitle controller already set
11-20 07:53:14.941 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: onPrepared
11-20 07:53:14.976 30147-30861/org.thoughtcrime.securesms E/MediaPlayer: error (1, -19)
11-20 07:53:14.994 30147-30147/org.thoughtcrime.securesms E/MediaPlayer: Error (1,-19)
11-20 07:53:14.994 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: MediaPlayer Error: 1 , -19
11-20 07:53:15.125 30147-30147/org.thoughtcrime.securesms W/AudioView: pausebutton onClick
11-20 07:53:15.126 30147-30147/org.thoughtcrime.securesms W/AudioSlidePlayer: Stop called!
11-20 07:53:18.150 30147-20630/org.thoughtcrime.securesms W/AudioAttachmentServer: java.net.SocketTimeoutException
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
                                                                                       at libcore.io.Posix.accept(Native Method)
                                                                                       at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216) 
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140) 
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85) 
                                                                                       at java.lang.Thread.run(Thread.java:818) 
11-20 07:53:18.150 30147-20630/org.thoughtcrime.securesms D/AudioAttachmentServer: Proxy interrupted. Shutting down.
11-20 07:53:18.570 30147-20648/org.thoughtcrime.securesms W/AudioAttachmentServer: java.net.SocketTimeoutException
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
                                                                                       at libcore.io.Posix.accept(Native Method)
                                                                                       at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216) 
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140) 
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85) 
                                                                                       at java.lang.Thread.run(Thread.java:818) 
11-20 07:53:18.570 30147-20648/org.thoughtcrime.securesms D/AudioAttachmentServer: Proxy interrupted. Shutting down.
11-20 07:53:19.030 30147-20661/org.thoughtcrime.securesms W/AudioAttachmentServer: java.net.SocketTimeoutException
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
                                                                                       at libcore.io.Posix.accept(Native Method)
                                                                                       at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216) 
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140) 
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85) 
                                                                                       at java.lang.Thread.run(Thread.java:818) 
11-20 07:53:19.030 30147-20661/org.thoughtcrime.securesms D/AudioAttachmentServer: Proxy interrupted. Shutting down.
11-20 07:53:19.480 30147-20674/org.thoughtcrime.securesms W/AudioAttachmentServer: java.net.SocketTimeoutException
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
                                                                                       at libcore.io.Posix.accept(Native Method)
                                                                                       at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216) 
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140) 
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85) 
                                                                                       at java.lang.Thread.run(Thread.java:818) 
11-20 07:53:19.480 30147-20674/org.thoughtcrime.securesms D/AudioAttachmentServer: Proxy interrupted. Shutting down.
11-20 07:53:19.930 30147-20691/org.thoughtcrime.securesms W/AudioAttachmentServer: java.net.SocketTimeoutException
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216)
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140)
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85)
                                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                                    Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
                                                                                       at libcore.io.Posix.accept(Native Method)
                                                                                       at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
                                                                                       at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
                                                                                       at java.net.ServerSocket.implAccept(ServerSocket.java:216) 
                                                                                       at java.net.ServerSocket.accept(ServerSocket.java:140) 
                                                                                       at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85) 
                                                                                       at java.lang.Thread.run(Thread.java:818) 
11-20 07:53:19.930 30147-20691/org.thoughtcrime.securesms D/AudioAttachmentServer: Proxy interrupted. Shutting down.
```

**Comment by McLoo** [comment]
Takes some tape to reproduce in my Z1 compact 5.1.1 could be the system  resources?!
