### ISSUE TITLE
Issues using in China

### ISSUE THREAD

**Issue by piecam** [signalapp/Signal-Android#4946]
HI,

I just had a friend installed this app and got registered successfully with SMS code. However, he was not able to send out secure message to me. 

Are we aware of any blocking the use of Signal in China? or Is this protocol blockable? Any other suggestions?

It seems that even with private vpn access to other places, it's still not working.

Any ideas?

thanks

**Comment by 2-4601** [comment]
Debug log from your friend after he tries to send a Signal message could be helpful
settings -> advanced -> submit debug log
and paste the link here

**Comment by piecam** [comment]
https://gist.github.com/9120fe9b68ffb0c9c191

**Comment by piecam** [comment]
the above is log without out using VPN service bypassing China's firewall.

**Comment by piecam** [comment]
https://gist.github.com/25fa19ba65cfa0372d02
this is with VPN service bypassing CHINA's firewall

**Comment by McLoo** [comment]
If there wasn't a crash in the second log, I'd ask you to take this issue over to the support http://support.whispersystems.org/

From the second (VPN) log:

```logcat
ConversationActivity(14870): org.whispersystems.libaxolotl.InvalidMessageException: 信息为空！
W/ConversationActivity(14870): 	at org.thoughtcrime.securesms.ConversationActivity.getMessage(ConversationActivity.java:1172)
W/ConversationActivity(14870): 	at org.thoughtcrime.securesms.ConversationActivity.sendTextMessage(ConversationActivity.java:1291)
W/ConversationActivity(14870): 	at org.thoughtcrime.securesms.ConversationActivity.sendMessage(ConversationActivity.java:1228)
W/ConversationActivity(14870): 	at org.thoughtcrime.securesms.ConversationActivity.access$3300(ConversationActivity.java:154)
W/ConversationActivity(14870): 	at org.thoughtcrime.securesms.ConversationActivity$SendButtonListener.onClick(ConversationActivity.java:1452)
W/ConversationActivity(14870): 	at android.view.View.performClick(View.java:4446)
W/ConversationActivity(14870): 	at org.thoughtcrime.securesms.ConversationActivity$SendButtonListener.onEditorAction(ConversationActivity.java:1458)
W/ConversationActivity(14870): 	at android.widget.TextView.onEditorAction(TextView.java:4320)
W/ConversationActivity(14870): 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
W/ConversationActivity(14870): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:315)
W/ConversationActivity(14870): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:87)
W/ConversationActivity(14870): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/ConversationActivity(14870): 	at android.os.Looper.loop(Looper.java:136)
W/ConversationActivity(14870): 	at android.app.ActivityThread.main(ActivityThread.java:5315)
W/ConversationActivity(14870): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/ConversationActivity(14870): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/ConversationActivity(14870): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
W/ConversationActivity(14870): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
W/ConversationActivity(14870): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
