### ISSUE TITLE
Background crash on message receipt

### ISSUE THREAD

**Issue by wickedshimmy** [signalapp/Signal-Android#4984]
I don't think I was doing anything particular at the time; the app was backgrounded, and on receipt of a new message I noticed that I needed to re-unlock. Sorry I can't pin it down any more than that :/

https://gist.github.com/anonymous/8d9af351e55e9162b7a3

```
Device  : motorola XT1053 (ghost_retail)
Android : 5.1 (4, LPA23.12-15.5)
Memory  : 16M (0.08% used, 96M max)
Memclass: 96
OS Host : ilclbld99
App     : Signal 3.8.1

--------- beginning of crash
E/AndroidRuntime(26026): FATAL EXCEPTION: main
E/AndroidRuntime(26026): Process: org.thoughtcrime.securesms, PID: 26026
E/AndroidRuntime(26026): java.lang.NullPointerException: Attempt to invoke virtual method 'org.thoughtcrime.securesms.TransportOption org.thoughtcrime.securesms.components.SendButton.getSelectedTransport()' on a null object reference
E/AndroidRuntime(26026):    at org.thoughtcrime.securesms.ConversationActivity.onConfigurationChanged(ConversationActivity.java:300)
E/AndroidRuntime(26026):    at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4129)
E/AndroidRuntime(26026):    at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:4227)
E/AndroidRuntime(26026):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1447)
E/AndroidRuntime(26026):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26026):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(26026):    at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(26026):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26026):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26026):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(26026):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
--------- beginning of main
W/PartProvider(12715): onCreate()
W/MessageRetrievalService(12715): Waiting for websocket state change....
W/MessageRetrievalService(12715): Network requirement: true, active activities: 0, push pending: 0
W/SMSListener(12715): Got SMS broadcast...
W/art     (12715): Suspending all threads took: 13.642ms
W/RecipientPreferenceDatabase(12715): Muted until: 0
W/RecipientPreferenceDatabase(12715): Muted until: 0
W/PublicKey(12715): Serializing public key point: 05 fa c6 2a 25 66 a9 28 50 49 cb 25 9b 7b b1 1e 7a d2 ef 69 8f 49 20 5e f5 56 30 4e d2 db 69 83 73 
--------- beginning of system
W/ResourcesManager(12715): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/MmsSmsDatabase(12715): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 6) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 6) ORDER BY date_received DESC LIMIT 1)
W/MmsSmsDatabase(12715): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/art     (12715): Suspending all threads took: 9.705ms
W/NotificationState(12715): Added thread: 6
W/NotificationState(12715): Pending array off intent length: 1
W/TAG     (12715): threadIds length: 1
W/MarkReadReceiver(12715): Marking as read: 6
W/MmsSmsDatabase(12715): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/PassphraseRequiredActionBarActivity(12715): onCreate(Bundle[mParcelledData.dataSize=2628])
W/ExperienceUpgradeActivity(12715): getExperienceUpgrade(157)
W/PassphraseRequiredActionBarActivity(12715): routeApplicationState(), state: 2
D/OpenGLRenderer(12715): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   (12715): Validating map...
I/Adreno-EGL(12715): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020_msm8960_LA.AF.1.1_RB1__release_AU ()
I/Adreno-EGL(12715): OpenGL ES Shader Compiler Version: E031.25.03.06
I/Adreno-EGL(12715): Build Date: 03/30/15 Mon
I/Adreno-EGL(12715): Local Branch: mybranch8688311
I/Adreno-EGL(12715): Remote Branch: quic/LA.AF.1.1_rb1.16
I/Adreno-EGL(12715): Local Patches: NONE
I/Adreno-EGL(12715): Reconstruct Branch: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.02.006.020 + 9b2699f + 2215637 + 60aa592 + f2362e6 + 5c64f59 + 82411a1 + 1f36e07 +  NOTHING
I/OpenGLRenderer(12715): Initialized EGL, version 1.4
D/OpenGLRenderer(12715): Enabling debug mode 0
W/PassphraseRequiredActionBarActivity(12715): onDestroy()
W/art     (12715): Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
W/InputEventReceiver(12715): Attempted to finish an input event but the input event receiver has already been disposed.
```

**Comment by nkokkalis** [comment]
Same case here:
https://gist.github.com/anonymous/369d6643b406d998f127

**Comment by moxie0** [comment]
@nkokkalis that looks like a different stack trace, would you mind opening a new issue for that?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
