### ISSUE TITLE
Signal crashes during registration (last step)

### ISSUE THREAD

**Issue by gtom** [signalapp/Signal-Android#5281]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Bug description

Try to install Signal through Playstore, download/install works, we can start registration process, the verify-SMS reaches Signal but then we see a small windows with (german) message "Signal angehalten" (Signal stopped) with no more info.
I did a logcat during registration process and found an fatal exception. This happens only on our  Samsung (Samsung Note4, OS 5.1.1, Kernel-Version 3.10.40-5932639, all Samsung-updates applied).  We do use other mobiles with stock google and and some with cyanogenmod, there is no problem at all in using Signal.
### Steps to reproduce
- start install from Playstore
- start registration, verify phone number
- sms arrives, registration crashes, Signal stops. No possibility to bypass sms-receive, because Signal crashes.
### Device info

Samsung Note4, OS 5.1.1, Kernel-Version 3.10.40-5932639, all Samsung-updates applied

 **Android version:**  5.1.1

 **Signal version:** 
cannot read version because of crash, but should be actual version provided in Playstore
### Link to debug log

see attached logcat (phonenumbers edited with <delete>)
[logcat3.txt](https://github.com/WhisperSystems/Signal-Android/files/142194/logcat3.txt)

**Comment by moxie0** [comment]
```
E/AndroidRuntime(13365): android.database.sqlite.SQLiteException: null
E/AndroidRuntime(13365): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
E/AndroidRuntime(13365): 	at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
E/AndroidRuntime(13365): 	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:520)
E/AndroidRuntime(13365): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:402)
E/AndroidRuntime(13365): 	at android.content.ContentResolver.applyBatch(ContentResolver.java:1297)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.contacts.ContactsDatabase.setRegisteredUsers(ContactsDatabase.java:125)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.util.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:203)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:101)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:254)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:208)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:63)
E/AndroidRuntime(13365): 	at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:95)
E/AndroidRuntime(13365): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(13365): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(13365): 	at java.lang.Thread.run(Thread.java:818)
```

Looks like an NPE in Samsung's code.

**Comment by haffenloher** [comment]
This:
```
E/DatabaseUtils(19422): android.database.sqlite.SQLiteDoneException
E/DatabaseUtils(19422): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
E/DatabaseUtils(19422): 	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:768)
E/DatabaseUtils(19422): 	at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
E/DatabaseUtils(19422): 	at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.aggregation.ContactAggregator.updateMatchScoresBasedOnNameMatches(ContactAggregator.java:1867)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.aggregation.ContactAggregator.updateMatchScoresBasedOnDataMatches(ContactAggregator.java:1747)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.aggregation.ContactAggregator.pickBestMatchBasedOnData(ContactAggregator.java:1654)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.aggregation.ContactAggregator.aggregateContact(ContactAggregator.java:852)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.aggregation.ContactAggregator.aggregateContact(ContactAggregator.java:771)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.ContactsProvider2.updateAggregationException(ContactsProvider2.java:10087)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.ContactsProvider2.updateInTransaction(ContactsProvider2.java:8239)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.AbstractContactsProvider.update(AbstractContactsProvider.java:169)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.ContactsProvider2.update(ContactsProvider2.java:3309)
E/DatabaseUtils(19422): 	at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:256)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.AbstractContactsProvider.applyBatch(AbstractContactsProvider.java:240)
E/DatabaseUtils(19422): 	at com.android.providers.contacts.ContactsProvider2.applyBatch(ContactsProvider2.java:3528)
E/DatabaseUtils(19422): 	at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:301)
E/DatabaseUtils(19422): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:192)
E/DatabaseUtils(19422): 	at android.os.Binder.execTransact(Binder.java:446)
```

...looks very similar to http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=285044&listLines=15&startId=zzzzz~

**Comment by cascheberg** [comment]
#4047 :)

**Comment by gtom** [comment]
So in my point of view this seems to be a bug in Samsung-code known at least since last year according to links above. It seems that Samsung is not really interested in fixing a bug in an already sold phone. The workaround (resetting contacts.db) seems to be not really comfortable in the long run. 

Is there any chance of catching this event an Signal-side during registration to avoid the workaround? Right now we have two different Samsungs suffering this problem (but only this problem, other messengers do work as expected). I don't think these are the only ones in the world. Do you count suddenly cancelled registrations at Whisper-Systems-Server by Android-Version? Is there any difference in percentage of interrupted registration between Stock-Androids and Samsung-Android?
Thanks in advance
gtom

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
