### ISSUE TITLE
ActivityNotFoundException after enabling/disabling Signal as default SMS app

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [signalapp/Signal-Android#5373]
_Edit: Restructured based on the sharp-eyed research by_ @haffenloher

---
### Bug description

`android.provider.Settings.ACTION_WIRELESS_SETTINGS` does not have matching activity in Android FlymeOs and Signal crashes.
According to [Android docs](https://developer.android.com/reference/android/provider/Settings.html#ACTION_WIRELESS_SETTINGS) the app developer should take it into account that not all Android flavours have this activity:

>  In some cases, a matching Activity may not exist, so ensure you safeguard against this.
### Steps to reproduce
1. Signal is your default SMS app
2. you go to _Settings > SMS and MMS_
3. you touch _SMS Enabled - Touch to change your default SMS app_
4. the system dialog (called _Wireless & networks_ in 5.1 emulator) that Signal [tries to open](https://github.com/WhisperSystems/Signal-Android/blob/84fa2d1a34c7d74efc3eab1599e03c036ab50b2f/src/org/thoughtcrime/securesms/preferences/SmsMmsPreferenceFragment.java#L56) somehow does not exist
### Device info

**Device:** Meizu m2 note,
**Android:** Flyme OS 4.5.4.2I, Android 5.1
**Signal:** 3.14.2
### Link to debug log

https://gist.github.com/dff65ac6cc0972b854c2

```
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 24169
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.WIRELESS_SETTINGS }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1800)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
    at android.app.Activity.startActivityForResult(Activity.java:3852)
[...]
```

**Comment by cascheberg** [comment]
You linked the same debug log here as in #5308. I was thinking that following the above steps would result in a different debug log that's worth posting.

**Comment by KarolTrzeszczkowski** [comment]
Man, I'm just user. I'm trying to help.

**Comment by 2-4601** [comment]
@KarolTrzeszczkowski thank you for your help, it seems there was just a small misunderstanding and this is after all the same bug as #5308, sorry :)

**Comment by cascheberg** [comment]
Yep, thanks and sorry, I was not actually complaining.

**Comment by KarolTrzeszczkowski** [comment]
:) It's ok. Thank you also. It was misunderstanding.

**Comment by haffenloher** [comment]
Wait, is this tracked somewhere?

```
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 24169
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.WIRELESS_SETTINGS }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1800)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
	at android.app.Activity.startActivityForResult(Activity.java:3852)
[...]
```

I don't think this has anything to do with #5308.
[Android docs](https://developer.android.com/reference/android/provider/Settings.html#ACTION_WIRELESS_SETTINGS) for `android.provider.Settings.ACTION_WIRELESS_SETTINGS` say:
>  In some cases, a matching Activity may not exist, so ensure you safeguard against this.

So we should probably do something about the crash.

**Comment by 2-4601** [comment]
So is this because of the work around for some operators that can't send MMS unless Wi-Fi is turned off? And when you enable/disable/use Signal as your SMS/MMS app that setting is triggered and sometimes crashes if there's no activity for it?

**Comment by haffenloher** [comment]
@2-4601 No, sorry, that wasn't very clear :stuck_out_tongue:
the crash happens when

1. you're on Android 4.4 or later
1. Signal is your default SMS app
1. you go to *Settings > SMS and MMS*
1. you touch *SMS Enabled - Touch to change your default SMS app*
1. the system dialog (called *Wireless & networks* in my 5.1 emulator) that Signal [tries to open](https://github.com/WhisperSystems/Signal-Android/blob/84fa2d1a34c7d74efc3eab1599e03c036ab50b2f/src/org/thoughtcrime/securesms/preferences/SmsMmsPreferenceFragment.java#L56) somehow does not exist

**Comment by 2-4601** [comment]
I couldn't reproduce this on stock 5.1.1, Nexus 4, Signal 3.15.0 (also nothing in the logs) but maybe it's best to open a new issue for this. This has too much unrelated stuff so it's hard to figure out the actual cause :D

**Comment by KarolTrzeszczkowski** [comment]
I think it is the case it of Meizu and it's modification of Android flyme os.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
