### ISSUE TITLE
Signal crashes on certain messages (Android bug)

### ISSUE THREAD

**Issue by cascheberg** [signalapp/Signal-Android#5394]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

A friend of mine reported this crash.

```
java.lang.ArrayIndexOutOfBoundsException: length=244; index=374
    at android.text.MeasuredText.addStyleRun(MeasuredText.java:168)
    at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
    at android.text.StaticLayout.generate(StaticLayout.java:281)
    at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
    at android.text.DynamicLayout.<init>(DynamicLayout.java:170)
    at android.widget.TextView.makeSingleLayout(TextView.java:5863)
    at android.widget.TextView.makeNewLayout(TextView.java:5761)
    at android.widget.TextView.onMeasure(TextView.java:6118)
    at org.thoughtcrime.securesms.components.emoji.EmojiTextView.onMeasure(EmojiTextView.java:71)
    at android.view.View.measure(View.java:15264)
...
```

I found this: http://stackoverflow.com/questions/12849676/i-cant-figure-the-issue-with-a-stacktrace-error
According to that the crash happens because of a bug in the stock Android 4.1.1 code. It's triggered by some certain texts. It also proposes one quite complex and one rather simple workaround.

Note that, according to my friend, using system emojis apparently does not crash.
### Device info

**Device:** Acer V360
**Android version:** 4.1.1
**Signal version:** 3.14.2
### Link to debug log

https://gist.github.com/anonymous/d29e6932a84b5a1820a2

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
