### ISSUE TITLE
com.google.protobuf.UninitializedMessageException: Message missing required fields

### ISSUE THREAD

**Issue by john-difool** [signalapp/Signal-Android#5435]
```
04-12 11:17:29.947 8149-8190/org.thoughtcrime.securesms W/JobConsumer: com.google.protobuf.UninitializedMessageException: Message missing required fields: 
                                                                           at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
                                                                           at org.whispersystems.libsignal.state.StorageProtos$SignedPreKeyRecordStructure$Builder.build(StorageProtos.java:7521)
                                                                           at org.whispersystems.libsignal.state.SignedPreKeyRecord.<init>(SignedPreKeyRecord.java:28)
                                                                           at org.thoughtcrime.securesms.crypto.PreKeyUtil.generateSignedPreKey(PreKeyUtil.java:76)
                                                                           at org.thoughtcrime.securesms.jobs.CreateSignedPreKeyJob.onRun(CreateSignedPreKeyJob.java:51)
                                                                           at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
                                                                           at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
                                                                           at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
04-12 11:17:29.947 8149-8190/org.thoughtcrime.securesms E/AndroidRuntime: FATAL EXCEPTION: JobConsumer-4
                                                                          Process: org.thoughtcrime.securesms, PID: 8149
                                                                          com.google.protobuf.UninitializedMessageException: Message missing required fields: 
                                                                              at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770)
                                                                              at org.whispersystems.libsignal.state.StorageProtos$SignedPreKeyRecordStructure$Builder.build(StorageProtos.java:7521)
                                                                              at org.whispersystems.libsignal.state.SignedPreKeyRecord.<init>(SignedPreKeyRecord.java:28)
                                                                              at org.thoughtcrime.securesms.crypto.PreKeyUtil.generateSignedPreKey(PreKeyUtil.java:76)
                                                                              at org.thoughtcrime.securesms.jobs.CreateSignedPreKeyJob.onRun(CreateSignedPreKeyJob.java:51)
                                                                              at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
                                                                              at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
                                                                              at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

**Comment by moxie0** [comment]
@john-difool Please use the issue template when posting issues. It's hard to do anything with this in its current form.

**Comment by esellin** [comment]
I get the same error by running this single line of code:

`
KeyHelper.generatePreKeys(1, 100);
`

It looks like the generated protobuf message isn't initialized somehow, and a UninitializedMessageException is thrown.

Is there some global init() method that we need to call first?

This is with org.whispersystems:signal-protocol-android:2.2.0

Many thanks,
Eric

**Comment by esellin** [comment]
The exception above only occurs when running in the emulator, Genymotion in my case. It runs fine on the physical device.

It may have something to do with loading the JNI library for the Curve25519 code, but I couldn't see any errors being logged to the console apart from the exception above.

**Comment by esellin** [comment]
The exception doesn't happen when running in the standard Android emulator with an ARM system image. It's super slow but it works!

I thought the Curve25519 library was supposed to fall back to a straight Java implementation if it fails to load the JNI library, so not sure why it's not working with an Intel image (which is what Genymotion is using).

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
