### ISSUE TITLE
Problems resetting connection from any device (was: "from desktop")

### ISSUE THREAD

**Issue by keraba** [signalapp/Signal-Android#5438]
I have:
- [x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

The following occurred on the Signal desktop extension.

A friend reset his key or connection (whatever was required to join the desktop beta), because on my end it had appended a bubble saying, "Connection reset" or something like that. I clicked on it to verify him, but then the bubble changed to, "Error handling incoming message." Clicking on the little red ! said, "Error    encodedNumber is not defined".

To try to restart things, I clicked on dots | Reset Session. It might have appended a new bubble here, not sure. I tried sending a message to restart things, and it just said, "Message not sent. Resend" inside the same bubble as my message. I clicked on "Resend" but it did nothing.

I tried to send something else, but same thing.

I then clicked on dots | Reset Session again. Not sure what happened here.

I believe I restarted the Signal extension somewhere in there too. It had no effect.

My friend eventually sent a message. It arrived on the desktop but I replied through the phone, since it appeared the desktop was hosed. This worked. After this, everything seemed fine.
### Steps to reproduce

See above.

**Actual result:**
Was not able to acknowledge a session reset through the desktop, nor initiate a session reset through desktop, but was able to reset it through phone.
**Expected result:**
Should be able to respond to or reset session through desktop.
### Device info

Using desktop app v0.7.0 on Chrome 49 on Ubuntu Trusty.
**Device:** Nexus 5X
**Android version:** M
**Signal version:** 3.15.2
### Link to debug log

This was captured the next day, but appears to still have the failed exchange.
https://gist.github.com/ad2d6005e7fbdc63d16d985947ec7d3f

**Comment by keraba** [comment]
And another disconnection, and can't re-establish from either device.

https://gist.github.com/c14143d397532ada4552dbaf43e929e9

**Comment by 2-4601** [comment]
Did you mean to open an issue at Signal Desktop's tracker? This is the tracker for the Android client. Both of your debug logs are only from Signal Desktop and the issue seems to be about Desktop.

**Comment by keraba** [comment]
No, I didn't - thanks - but at this point, I can't reset this connection on any device, so there seems to be a wider issue present.

**Comment by keraba** [comment]
Here's the log from Android. If it missed the event, I can try again.

https://gist.github.com/b28b8d1aaf26775945449fd8ec2d4dab

**Comment by 2-4601** [comment]
Unfortunately it looks like you missed the errors in the Android log you posted.
Please try to capture it again immediately after your issue occurs.

- - - - - - - - - -
@liliakai if you have time, please have a look at the logs @keraba posted
Copy-pasted here:
https://gist.github.com/anonymous/ad2d6005e7fbdc63d16d985947ec7d3f
```
2016-04-12T17:45:21.253Z extension launched
2016-04-12T17:45:21.283Z opening websocket
2016-04-12T17:45:21.290Z open inbox
2016-04-12T17:45:21.606Z websocket open
2016-04-12T17:45:21.629Z envelope from +[REDACTED]953.2 1460483065275
2016-04-12T17:45:21.631Z prekey whisper message
2016-04-12T17:45:21.778Z IncomingIdentityKeyError: The identity of +[REDACTED]953 has changed.
2016-04-12T17:45:21.779Z Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:45:21.781Z  Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:45:21.781Z IncomingIdentityKeyError: The identity of +[REDACTED]953 has changed.
2016-04-12T17:45:21.810Z sorting conversation +[REDACTED]953
2016-04-12T17:45:21.815Z draw attention
2016-04-12T17:45:27.899Z Sending 1 read receipts
2016-04-12T17:45:28.127Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T17:45:28.471Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-12T17:45:29.999Z envelope from +[REDACTED]378.1 1460483127907
2016-04-12T17:45:30.003Z delivery receipt from +[REDACTED]378.1 1460483127907
2016-04-12T17:45:45.193Z prekey whisper message
2016-04-12T17:45:45.674Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys
2016-04-12T17:45:45.689Z ReferenceError: encodedNumber is not defined
2016-04-12T17:45:45.692Z  ReferenceError: encodedNumber is not defined
    at MessageReceiver.<anonymous> (chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:37213:66)
2016-04-12T17:45:45.834Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys 200 Success
2016-04-12T17:45:45.841Z prekey count 98
2016-04-12T17:48:13.578Z pre-main prep time: 4 ms
2016-04-12T17:48:13.642Z background page reloaded
2016-04-12T17:48:13.667Z extension launched
2016-04-12T17:48:13.701Z opening websocket
2016-04-12T17:48:13.705Z open inbox
2016-04-12T17:48:14.019Z websocket open
2016-04-12T17:48:22.325Z sending end session
2016-04-12T17:48:22.377Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953
2016-04-12T17:48:22.719Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953 409 Error
2016-04-12T17:48:22.725Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1
2016-04-12T17:48:22.881Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 200 Success
2016-04-12T17:48:22.888Z OutgoingIdentityKeyError: The identity of +[REDACTED]953 has changed.
2016-04-12T17:48:22.890Z Identity key changed Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:48:55.448Z sorting conversation +[REDACTED]953
2016-04-12T17:48:55.499Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953
2016-04-12T17:48:55.707Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953 409 Error
2016-04-12T17:48:55.711Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1
2016-04-12T17:48:55.794Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 200 Success
2016-04-12T17:48:55.802Z OutgoingIdentityKeyError: The identity of +[REDACTED]953 has changed.
2016-04-12T17:48:55.804Z Identity key changed Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:49:03.814Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1
2016-04-12T17:49:03.900Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 200 Success
2016-04-12T17:49:04.188Z Error: Invalid signature
2016-04-12T17:49:04.191Z Failed to create or send message Error: Invalid signature
    at Curve25519Worker.<anonymous> (chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:25419:25)
2016-04-12T17:49:04.203Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1
2016-04-12T17:49:04.276Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 413 Error
2016-04-12T17:49:04.278Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 413 Error
2016-04-12T17:49:04.281Z OutgoingMessageError: Rate limit exceeded, please try again later.
2016-04-12T17:49:04.285Z Failed to retreive new device keys for number +[REDACTED]953 Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:49:43.753Z websocket closed 1006 
2016-04-12T17:49:43.755Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T17:49:44.082Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T17:49:44.086Z opening websocket
2016-04-12T17:49:44.289Z websocket open
2016-04-12T17:51:03.123Z sorting conversation +[REDACTED]953
2016-04-12T17:51:03.132Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1
2016-04-12T17:51:03.458Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 413 Error
2016-04-12T17:51:03.461Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 413 Error
2016-04-12T17:51:03.465Z OutgoingMessageError: Rate limit exceeded, please try again later.
2016-04-12T17:51:03.467Z Failed to retreive new device keys for number +[REDACTED]953 Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:51:09.980Z pre-main prep time: 4 ms
2016-04-12T17:51:10.039Z background page reloaded
2016-04-12T17:51:10.059Z extension launched
2016-04-12T17:51:10.087Z opening websocket
2016-04-12T17:51:10.091Z open inbox
2016-04-12T17:51:10.354Z websocket open
2016-04-12T17:51:16.401Z sending end session
2016-04-12T17:51:16.413Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1
2016-04-12T17:51:16.486Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 413 Error
2016-04-12T17:51:16.489Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys/+[REDACTED]953/1 413 Error
2016-04-12T17:51:16.496Z OutgoingMessageError: Rate limit exceeded, please try again later.
2016-04-12T17:51:16.497Z Failed to retreive new device keys for number +[REDACTED]953 Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T17:52:40.325Z websocket closed 1006 
2016-04-12T17:52:40.334Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T17:52:40.589Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T17:52:40.593Z opening websocket
2016-04-12T17:52:40.797Z websocket open
2016-04-12T17:54:10.319Z websocket closed 1006 
2016-04-12T17:54:10.325Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T17:54:10.652Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T17:54:10.656Z opening websocket
2016-04-12T17:54:10.929Z websocket open
2016-04-12T17:55:40.752Z websocket closed 1006 
2016-04-12T17:55:40.759Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T17:55:41.012Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T17:55:41.016Z opening websocket
2016-04-12T17:55:41.338Z websocket open
2016-04-12T17:57:11.327Z websocket closed 1006 
2016-04-12T17:57:11.331Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T17:57:11.657Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T17:57:11.660Z opening websocket
2016-04-12T17:57:11.863Z websocket open
2016-04-12T17:58:41.320Z websocket closed 1006 
2016-04-12T17:58:41.322Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T17:58:41.673Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T17:58:41.675Z opening websocket
2016-04-12T17:58:41.949Z websocket open
2016-04-12T18:00:11.759Z websocket closed 1006 
2016-04-12T18:00:11.763Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:00:12.086Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:00:12.088Z opening websocket
2016-04-12T18:00:12.311Z websocket open
2016-04-12T18:01:41.752Z websocket closed 1006 
2016-04-12T18:01:41.756Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:01:42.012Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:01:42.014Z opening websocket
2016-04-12T18:01:42.218Z websocket open
2016-04-12T18:03:11.752Z websocket closed 1006 
2016-04-12T18:03:11.756Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:03:12.081Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:03:12.083Z opening websocket
2016-04-12T18:03:12.352Z websocket open
2016-04-12T18:04:42.326Z websocket closed 1006 
2016-04-12T18:04:42.330Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:04:42.591Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:04:42.593Z opening websocket
2016-04-12T18:04:42.800Z websocket open
2016-04-12T18:06:12.319Z websocket closed 1006 
2016-04-12T18:06:12.326Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:06:12.650Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:06:12.654Z opening websocket
2016-04-12T18:06:12.952Z websocket open
2016-04-12T18:07:42.749Z websocket closed 1006 
2016-04-12T18:07:42.754Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:07:43.003Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:07:43.005Z opening websocket
2016-04-12T18:07:43.210Z websocket open
2016-04-12T18:09:12.750Z websocket closed 1006 
2016-04-12T18:09:12.754Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:09:13.078Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:09:13.080Z opening websocket
2016-04-12T18:09:13.351Z websocket open
2016-04-12T18:10:43.321Z websocket closed 1006 
2016-04-12T18:10:43.323Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:10:43.659Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:10:43.662Z opening websocket
2016-04-12T18:10:43.863Z websocket open
2016-04-12T18:12:13.332Z websocket closed 1006 
2016-04-12T18:12:13.336Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:12:13.661Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:12:13.663Z opening websocket
2016-04-12T18:12:13.938Z websocket open
2016-04-12T18:13:43.749Z websocket closed 1006 
2016-04-12T18:13:43.753Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:13:44.026Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:13:44.028Z opening websocket
2016-04-12T18:13:44.239Z websocket open
2016-04-12T18:15:13.751Z websocket closed 1006 
2016-04-12T18:15:13.755Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:15:14.008Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:15:14.010Z opening websocket
2016-04-12T18:15:14.215Z websocket open
2016-04-12T18:16:43.752Z websocket closed 1006 
2016-04-12T18:16:43.756Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices
2016-04-12T18:16:44.081Z GET https://textsecure-service-ca.whispersystems.org:4433/v1/devices 200 Success
2016-04-12T18:16:44.083Z opening websocket
2016-04-12T18:16:44.354Z websocket open
2016-04-12T18:17:35.033Z envelope from +[REDACTED]953.1 1460485051051
2016-04-12T18:17:35.036Z prekey whisper message
2016-04-12T18:17:35.050Z IncomingIdentityKeyError: The identity of +[REDACTED]953 has changed.
2016-04-12T18:17:35.051Z Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T18:17:35.053Z IncomingIdentityKeyError: The identity of +[REDACTED]953 has changed.
2016-04-12T18:17:35.054Z  Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:29:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:113:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:38109:3
2016-04-12T18:17:35.067Z sorting conversation +[REDACTED]953
2016-04-12T18:17:35.081Z draw attention
2016-04-12T18:17:44.071Z envelope from +[REDACTED]378.1 1460485063084
2016-04-12T18:17:44.435Z read messages from +[REDACTED]378.1
2016-04-12T18:17:44.437Z read receipt  +[REDACTED]953 1460485051051
2016-04-12T18:17:44.439Z envelope from +[REDACTED]378.3 1460485063084
2016-04-12T18:17:44.440Z delivery receipt from +[REDACTED]378.3 1460485063084
2016-04-12T18:18:19.095Z envelope from +[REDACTED]953.1 1460485083689
2016-04-12T18:18:19.097Z delivery receipt from +[REDACTED]953.1 1460485083689
2016-04-12T18:18:19.101Z envelope from +[REDACTED]953.2 1460485083689
2016-04-12T18:18:19.102Z delivery receipt from +[REDACTED]953.2 1460485083689
2016-04-12T18:18:19.288Z envelope from +[REDACTED]378.1 1460485083689
2016-04-12T18:18:19.306Z sent message to +[REDACTED]953 1460485083689 from +[REDACTED]378.1
2016-04-12T18:18:19.314Z sorting conversation +[REDACTED]953
2016-04-12T18:18:19.358Z envelope from +[REDACTED]378.3 1460485083689
2016-04-12T18:18:19.361Z delivery receipt from +[REDACTED]378.3 1460485083689
2016-04-12T18:18:33.897Z clear attention
2016-04-12T18:18:35.801Z Sending 1 read receipts
2016-04-12T18:18:35.859Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T18:18:36.182Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-12T18:18:36.404Z envelope from +[REDACTED]378.1 1460485115806
2016-04-12T18:18:36.407Z delivery receipt from +[REDACTED]378.1 1460485115806
2016-04-12T18:19:58.142Z prekey whisper message
2016-04-12T18:19:58.328Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys
2016-04-12T18:19:58.377Z Sending 1 read receipts
2016-04-12T18:19:58.412Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T18:19:58.618Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-12T18:19:58.654Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys 200 Success
2016-04-12T18:19:58.658Z prekey count 97
2016-04-12T18:19:58.784Z envelope from +[REDACTED]378.1 1460485198378
2016-04-12T18:19:58.787Z delivery receipt from +[REDACTED]378.1 1460485198378
2016-04-12T18:22:54.851Z envelope from +[REDACTED]953.2 1460485365859
2016-04-12T18:22:54.855Z prekey whisper message
2016-04-12T18:22:55.040Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys
2016-04-12T18:22:55.050Z data message from +[REDACTED]953.2 1460485365859
2016-04-12T18:22:55.061Z sorting conversation +[REDACTED]953
2016-04-12T18:22:55.107Z draw attention
2016-04-12T18:22:55.362Z GET https://textsecure-service-ca.whispersystems.org:4433/v2/keys 200 Success
2016-04-12T18:22:55.365Z prekey count 96
2016-04-12T18:23:04.924Z clear attention
2016-04-12T18:23:04.949Z Sending 1 read receipts
2016-04-12T18:23:04.988Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T18:23:05.060Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-12T18:23:05.948Z envelope from +[REDACTED]378.1 1460485384953
2016-04-12T18:23:05.951Z delivery receipt from +[REDACTED]378.1 1460485384953
2016-04-12T18:23:13.189Z sorting conversation +[REDACTED]953
2016-04-12T18:23:13.238Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953
2016-04-12T18:23:13.379Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953 200 Success
2016-04-12T18:23:13.423Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T18:23:13.475Z envelope from +[REDACTED]953.2 1460485393180
2016-04-12T18:23:13.480Z delivery receipt from +[REDACTED]953.2 1460485393180
2016-04-12T18:23:13.495Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-12T18:23:13.617Z envelope from +[REDACTED]953.1 1460485393180
2016-04-12T18:23:13.619Z delivery receipt from +[REDACTED]953.1 1460485393180
2016-04-12T18:23:15.031Z envelope from +[REDACTED]378.1 1460485393382
2016-04-12T18:23:15.033Z delivery receipt from +[REDACTED]378.1 1460485393382
2016-04-12T18:24:33.276Z envelope from +[REDACTED]953.2 1460485466681
2016-04-12T18:24:33.360Z data message from +[REDACTED]953.2 1460485466681
2016-04-12T18:24:33.369Z sorting conversation +[REDACTED]953
2016-04-12T18:24:33.419Z draw attention
2016-04-12T18:24:43.458Z clear attention
2016-04-12T18:24:43.485Z Sending 1 read receipts
2016-04-12T18:24:43.529Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T18:24:43.850Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-12T18:24:44.775Z envelope from +[REDACTED]378.1 1460485483486
2016-04-12T18:24:44.778Z delivery receipt from +[REDACTED]378.1 1460485483486
2016-04-12T18:26:47.593Z sorting conversation +[REDACTED]953
2016-04-12T18:26:47.644Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953
2016-04-12T18:26:47.903Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]953 200 Success
2016-04-12T18:26:47.947Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-12T18:26:48.007Z envelope from +[REDACTED]953.2 1460485607584
2016-04-12T18:26:48.009Z delivery receipt from +[REDACTED]953.2 1460485607584
2016-04-12T18:26:48.022Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
```

https://gist.github.com/anonymous/c14143d397532ada4552dbaf43e929e9
```
2016-04-15T14:40:20.201Z envelope from +[REDACTED]953.1 1460731219056
2016-04-15T14:40:20.221Z data message from +[REDACTED]953.1 1460731219056
2016-04-15T14:40:20.224Z got end session
2016-04-15T14:40:20.242Z closing session for +[REDACTED]953.1
2016-04-15T14:40:20.247Z closing session for +[REDACTED]953.2
2016-04-15T14:40:20.255Z Not deleting closed session which has not yet timed out
2016-04-15T14:40:20.258Z Not deleting closed session which has not yet timed out
2016-04-15T14:40:20.292Z sorting conversation +[REDACTED]953
2016-04-15T14:40:20.342Z Sending 1 read receipts
2016-04-15T14:40:20.381Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378
2016-04-15T14:40:20.454Z PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]378 200 Success
2016-04-15T14:40:21.604Z envelope from +[REDACTED]378.1 1460731220344
2016-04-15T14:40:21.608Z delivery receipt from +[REDACTED]378.1 1460731220344
2016-04-15T15:47:25.487Z envelope from +[REDACTED]953.2 1460735234237
2016-04-15T15:47:25.497Z Error: No session found to decrypt message from +[REDACTED]953.2
2016-04-15T15:47:25.500Z Error: No session found to decrypt message from +[REDACTED]953.2
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:34823:23
2016-04-15T15:47:25.503Z Error: No session found to decrypt message from +[REDACTED]953.2
2016-04-15T15:47:25.505Z  Error: No session found to decrypt message from +[REDACTED]953.2
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:34823:23
```

**Comment by keraba** [comment]
Ok, here's another, also from the phone:

https://gist.github.com/2a0bb3f1a8bab1b4812b2199dc33f476

**Comment by keraba** [comment]
I guess my friend tried re-registering. Something popped up on the existing Signal "conversation" with him. It said, "Message encrypted to non-existent conversation.". Then, on the next line, "So and so is on Signal! Say 'hi'!" So it would *appear* that I have the correct phone number.

I entered a message and got the usual, "Not delivered." No reason why.

I reset the conversation and tried sending something again. Again, it said, "Not delivered" but this time, clicking on the message brought up a dialog which said that it wasn't sent because I needed to verify him. It had a little 'verify' button. I clicked it and tried re-sending. No dice.

I nuked the conversation, went into the contact list, refreshed it, started a new conversation and tried sending a message. Same error.

I would submit a(nother) debug log but this one was empty, about 10 lines of some kind of poll message.

Guys, what is going on? I've never had this problem before and, even if there was a hiccup, it's not re-syncing.

**Comment by riyapenn** [comment]
Contact support@whispersystems.org

**Comment by liliakai** [comment]
So, according to the first log in this thread, one of your contacts most likely re-installed Signal on their phone, causing an identity key change. This is not required in order to install the desktop client, unless perhaps they were switching from iPhone to Android?

For some reason, they then used their desktop client to reset their session with you. Again, this should not be necessary.

Because of the identity key change, there was a key conflict error on the end session message, which you resolved, thereby discovering a desktop bug that will be fixed in the next release (https://github.com/WhisperSystems/Signal-Desktop/commit/6a928e3377245b32c743e601b734db77b8cd387b). It's a pretty rare edge case. Thanks for finding it.

Then for some reason, you decided to also reset the session? Again, not necessary. What's strange is that you then continued to see indentity key errors after accepting the new key. And eventually both your Desktop and Android clients found invalid signatures on prekeys for your contact's android device, and finally both of your clients hit the rate limit on key requests from the the server.

I think we might need to see logs from the other person's devices to really understand what's going on here, but in general you can both be a little less trigger happy with the reset session operation. It is not helping you in this situation, and should almost never be necessary.

**Comment by keraba** [comment]
Hi liliakai, and thanks a million for replying. I really want to see this work.

I don't know why my friend did whatever he did when he got Desktop. He didn't change phones, afaik. Perhaps the install confused him and he didn't tie it back to his phone and just made a new account? I asked him in email and haven't heard back, so maybe I can reply back with a suggestion for a better work-flow.

But for me, after failing to re-sync on the desktop, I simply tried going back to the phone. I only tried to reset the connection whenever I tried to send something and it failed and didn't give me a reason. (A *few* of the times, it said "Verify your contact" with a little red button that never did anything.)

(From one of Moxie's talks, it was claimed that there were 100 session keys of my friend waiting for me on the Signal server. Thus I didn't think it was a big deal to just reset it. I doubt I've done it more than a dozen times over 4 days.)

So ... I'm curious where we go from here. He has re-registered, and can apparently send to me (albeit to a stale session key), but I can't send to him. Am I still locked out from resetting the connection? What's the rate limit there? (We didn't send anything all weekend.)

What intrigues me is that, as you say, "What's strange is that you then continued to see [identity] key errors after accepting the new key." That seems to be fundamental problem here. The rest is symptom.

The truncated log made me think, maybe my phone is out of space, but no, it has 26GB free.

I can send another log in a day or so, unless you have something you'd prefer we try.

**Comment by liliakai** [comment]
There's no harm in resetting, but there's also no benefit under normal circumstances.

The rate limit on prekeys is a leaky bucket that resets if you wait about 10 minutes.

On Android:
When sending a message, do you continue to see the "New identity" / "Verify"?
What fingerprint is displayed when you tap the three dots -> "Conversation settings" -> "Verify Identity"?
What fingerprint is displayed when you tap through the red "Verify" button then -> "You may wish to verify this contact"?

Is the other person able to communicate normally with other Signal contacts besides you?

**Comment by keraba** [comment]
When sending a message, do you continue to see the "New identity" / "Verify"?

I don't often see this, only sometimes. I *think* it's only on reception after a reset?

What fingerprint is displayed when you tap the three dots -> "Conversation settings" -> "Verify Identity"?

Their identity
05 92 55 bf db 56 51 9c 84
7c 00 9b 29 3b 5a 1b 85 87
99 01 12 43 f8 70 13 aa e4
5e 25 9b 19 18 39

What fingerprint is displayed when you tap through the red "Verify" button then -> "You may wish to verify this contact"?

Assuming we're talking about the same "Verify" button, nothing happens when I press it.

Is the other person able to communicate normally with other Signal contacts besides you?

I believe so. I'm able to communicate with people who did not install desktop.

btw, my friend replied. He cleared the app data because the app was crashing on start-up (possible disk corruption.)

**Comment by liliakai** [comment]
This "Verify" button?
![screenshot from 2016-04-18 20 09 11](https://cloud.githubusercontent.com/assets/1039940/14626567/78f192ce-05a1-11e6-8058-9b85b77b6ab2.png)

**Comment by keraba** [comment]
The only time I've seen something like that is, I *think* it was when I received a message, and the app didn't want to show it to me for some reason. I clicked on the message and, on the next screen, it said I should verify the sender. I clicked on the red button but it just took me back to the previous screen.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
