### ISSUE TITLE
Signal crashes upon start with "Attempt to invoke virtual method 'byte[] ws.com.google.android.mms.pdu.EncodedStringValue.getTextString()' on a null object reference"

### ISSUE THREAD

**Issue by afunix** [signalapp/Signal-Android#5944]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes upon start.
I've seen a number of MMS arrived when it start to crash.

I've tried a workaround with airplane mode and the one with sending SMS to myself to check all SMS as read.
Signal still crashes.

### Steps to reproduce
- Start Signal

**Actual result:** Signal crashes right after execution (tries to show password screen)
**Expected result:** Signal does not crash.

### Device info
**Device:** LG Nexus 4
**Android version:** 5.1.1
**Signal version:** 3.23.0

### Link to debug log
NOTE: I cannot capture debug log via Signal as it crashes.
Here is a copy-paste of adb logcat:
```
I/ActivityManager( 1790): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=org.thoughtcrime.securesms cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[188,1040][316,1168] (has extras)} from uid 10014 on display 0
V/WindowManager( 1790): addAppToken: AppWindowToken{6e2ab38 token=Token{12899b9b ActivityRecord{2b9c53aa u0 org.thoughtcrime.securesms/.RoutingActivity t83}}} to stack=1 task=83 at 0
I/ActivityManager( 1790): Start proc 23486:org.thoughtcrime.securesms/u0a91 for activity org.thoughtcrime.securesms/.RoutingActivity
V/WindowManager( 1790): Adding window Window{3935e313 u0 Starting org.thoughtcrime.securesms} at 12 of 18 (after Window{1e4cd224 u0 com.android.settings/com.android.settings.SubSettings})
W/PartProvider(23486): onCreate()
W/PduParser(23486): parse() called...
W/PduParser(23486): Message Type: 130
W/PassphraseRequiredActionBarActivity(23486): onCreate(null)
W/ExperienceUpgradeActivity(23486): getExperienceUpgrade(202)
W/PassphraseRequiredActionBarActivity(23486): routeApplicationState(), state: 2
I/ActivityManager( 1790): START u0 {cmp=org.thoughtcrime.securesms/.PassphrasePromptActivity (has extras)} from uid 10091 on display 0
V/WindowManager( 1790): addAppToken: AppWindowToken{2e3a79bd token=Token{16df2d14 ActivityRecord{c59cb67 u0 org.thoughtcrime.securesms/.PassphrasePromptActivity t83}}} to stack=1 task=83 at 1
V/WindowManager( 1790): Based on layer: Adding window Window{3935e313 u0 Starting org.thoughtcrime.securesms} at 12 of 18
W/CanonicalAddressDatabase(23486): Hitting DB on query [ID].
I/ActivityManager( 1790): Start proc 23525:android.process.acore/u0a4 for content provider com.android.providers.contacts/.ContactsProvider2
D/OpenGLRenderer(23486): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   (23486): Validating map...
V/WindowManager( 1790): Adding window Window{3dcac05f u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity} at 12 of 19 (before Window{3935e313 u0 Starting org.thoughtcrime.securesms})
I/ContactLocale(23525): AddressBook Labels [ru-RU]: [, А, Б, В, Г, Д, Ђ, Е, Є, Ж, З, И, І, Й, Ј, К, Л, Љ, М, Н, Њ, О, П, Р, С, Т, Ћ, У, Ф, Х, Ц, Ч, Џ, Ш, Щ, Ы, Э, Ю, Я, , A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, Α, Β, Γ, Δ, Ε, Ζ, Η, Θ, Ι, Κ, Λ, Μ, Ν, Ξ, Ο, Π, Ρ, Σ, Τ, Υ, Φ, Χ, Ψ, Ω, , א, ב, ג, ד, ה, ו, ז, ח, ט, י, כ, ל, מ, נ, ס, ע, פ, צ, ק, ר, ש, ת, , ا, ب, ت, ث, ج, ح, خ, د, ذ, ر, ز, س, ش, ص, ض, ط, ظ, ع, غ, ف, ق, ك, ل, م, ن, ه, و, ي, , ก, ข, ฃ, ค, ฅ, ฆ, ง, จ, ฉ, ช, ซ, ฌ, ญ, ฎ, ฏ, ฐ, ฑ, ฒ, ณ, ด, ต, ถ, ท, ธ, น, บ, ป, ผ, ฝ, พ, ฟ, ภ, ม, ย, ร, ฤ, ล, ฦ, ว, ศ, ษ, ส, ห, ฬ, อ, ฮ, , ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅅ, ㅇ, ㅈ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ, , あ, か, さ, た, な, は, ま, や, ら, わ, #, ]
I/Adreno-EGL(23486): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/15/15, ab0075f, Id3510ff6dc
I/OpenGLRenderer(23486): Initialized EGL, version 1.4
D/OpenGLRenderer(23486): Enabling debug mode 0
D/CountryDetector( 1790): The first listener is added
W/MmsDatabase(23486): Message received type: 130
I/ActivityManager( 1790): Displayed org.thoughtcrime.securesms/.PassphrasePromptActivity: +404ms (total +1s336ms)
I/ClearcutLoggerManager( 2117): onStartInput()
W/ResourcesManager(23486): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/PassphraseRequiredActionBarActivity(23486): onDestroy()
I/ClearcutLoggerManager( 2117): onFinishInput()
I/ClearcutLoggerManager( 2117): onStartInput()
W/JobConsumer(23486): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] ws.com.google.android.mms.pdu.EncodedStringValue.getTextString()' on a null object reference
W/JobConsumer(23486): 	at org.thoughtcrime.securesms.database.MmsDatabase.insertMessageInbox(MmsDatabase.java:827)
W/JobConsumer(23486): 	at org.thoughtcrime.securesms.jobs.MmsReceiveJob.onRun(MmsReceiveJob.java:61)
W/JobConsumer(23486): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer(23486): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
E/AndroidRuntime(23486): FATAL EXCEPTION: JobConsumer-2
E/AndroidRuntime(23486): Process: org.thoughtcrime.securesms, PID: 23486
E/AndroidRuntime(23486): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] ws.com.google.android.mms.pdu.EncodedStringValue.getTextString()' on a null object reference
E/AndroidRuntime(23486): 	at org.thoughtcrime.securesms.database.MmsDatabase.insertMessageInbox(MmsDatabase.java:827)
E/AndroidRuntime(23486): 	at org.thoughtcrime.securesms.jobs.MmsReceiveJob.onRun(MmsReceiveJob.java:61)
E/AndroidRuntime(23486): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime(23486): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/ActivityManager( 1790):   Force finishing activity 1 org.thoughtcrime.securesms/.PassphrasePromptActivity
W/SurfaceFlinger(  169): FB is protected: PERMISSION_DENIED
W/WindowManager( 1790): Screenshot failure taking screenshot for (768x1280) to layer 21060
I/OpenGLRenderer( 1790): Initialized EGL, version 1.4
I/ClearcutLoggerManager( 2117): onConnected()
W/OpenGLRenderer( 2241): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
W/OpenGLRenderer( 2241): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
W/ResourceType( 1937): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 1937): Failure retrieving resources for org.thoughtcrime.securesms: Resource ID #0x0
D/TaskPersister( 1790): removeObsoleteFile: deleting file=80_task.xml
```

**Comment by afunix** [comment]
Crashes in `org.thoughtcrime.securesms.database.MmsDatabase.insertMessageInbox` at this line:
`addressDatabase.insertAddressesForId(messageId, MmsAddresses.forFrom(Util.toIsoString(notification.getFrom().getTextString())));`

For me it seems I received a bunch of malware MMS-es, probably with `null` From.
Is it enough add a null check and use an empty string as a "From" ?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
