### ISSUE TITLE
RuntimeException: Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by mlsxlist** [signalapp/Signal-Android#5990]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashed suddenly

### Steps to reproduce
I send a signal message and returned to conversation list as far as I remember. I could not recreate it again.

**Actual result:** Signal crashed
**Expected result:** Signal should not crash

### Device info
**Device:** Samsung Note 4 SM-N910F
**Android version:** 5.1.1 CM
**Signal version:** 3.25.3

### Link to debug log
https://gist.github.com/136985126340460e4be4a1f7cabef596

**Comment by 2-4601** [comment]
```
E/AndroidRuntime( 5707): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@39d083b0
E/AndroidRuntime( 5707): 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
E/AndroidRuntime( 5707): 	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
E/AndroidRuntime( 5707): 	at org.thoughtcrime.securesms.components.emoji.EmojiProvider$EmojiDrawable.draw(EmojiProvider.java:149)
E/AndroidRuntime( 5707): 	at android.text.style.DynamicDrawableSpan.draw(DynamicDrawableSpan.java:104)
E/AndroidRuntime( 5707): 	at android.text.TextLine.handleReplacement(TextLine.java:856)
E/AndroidRuntime( 5707): 	at android.text.TextLine.handleRun(TextLine.java:939)
E/AndroidRuntime( 5707): 	at android.text.TextLine.drawRun(TextLine.java:398)
E/AndroidRuntime( 5707): 	at android.text.TextLine.draw(TextLine.java:196)
E/AndroidRuntime( 5707): 	at android.text.Layout.drawText(Layout.java:355)
E/AndroidRuntime( 5707): 	at android.text.Layout.draw(Layout.java:206)
E/AndroidRuntime( 5707): 	at android.widget.TextView.onDraw(TextView.java:5441)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:15247)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:15250)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3558)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:15250)
E/AndroidRuntime( 5707): 	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3037)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1049)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime( 5707): 	at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime( 5707): 	at android.view.View.draw(View.java:14975)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime( 5707): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime( 5707): 	at android.view.View.dr
```
Related #2345?

**Comment by mlsxlist** [comment]
Did not see the crash again. Closing ticket.
