### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by IndianaJ** [signalapp/Signal-Android#5991]
W/TextSecurePreferences: Setting push registered: false
W/PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
W/PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+37258534366
W/RegistrationService: org.thoughtcrime.securesms.service.AccountVerificationTimeoutException
                           at org.thoughtcrime.securesms.service.RegistrationService.waitForChallenge(RegistrationService.java:278)
                           at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:205)
                           at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:63)
                           at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:95)
                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                           at java.lang.Thread.run(Thread.java:818)

**Comment by riyapenn** [comment]
Some users from Estonia have received the SMS and call almost 9 hours after the initial registration request.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
