### ISSUE TITLE
Signal crashes when changing from vertical to horizontal view with keyboard open.

### ISSUE THREAD

**Issue by lazlolazlolazlo** [signalapp/Signal-Android#6045]
I have:
- [X ] searched open and closed issues for duplicates
- [X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal hangs and then crashes if I switch from vertical to horizontal view with the keyboard open.

### Steps to reproduce
- focus in message input to open keyboard
- rotate phone 90 degrees to right
- now signal appears only on the left half of the screen
- rotate phone 90 degrees to the left
- Signal hangs and is not responsive

**Actual result:** 
Signal hangs and crashes.
**Expected result:** 
Signal switches between vertical and horizontal mode.

### Device info

**Device:** motorola XT1021
**Android version:** 4.4.4
**Signal version:** 3.26.2

### Link to debug log
adb logcat: https://gist.github.com/anonymous/55f564648f0fe510c718fa11d6d0b202

**Comment by 2-4601** [comment]
```
E/ActivityManager( 1970): ANR in org.thoughtcrime.securesms (org.thoughtcrime.securesms/.ConversationActivity)
E/ActivityManager( 1970): PID: 15520
E/ActivityManager( 1970): Reason: Input dispatching timed out (Waiting because the focused window has not finished processing the input events that were previously delivered to it.)
E/ActivityManager( 1970): Load: 9.78 / 10.68 / 15.04
E/ActivityManager( 1970): CPU usage from 6575ms to 0ms ago:
E/ActivityManager( 1970):   101% 15520/org.thoughtcrime.securesms: 98% user + 2.1% kernel / faults: 5575 minor
E/ActivityManager( 1970):   3.1% 1970/system_server: 1.3% user + 1.8% kernel / faults: 211 minor 2 major
E/ActivityManager( 1970):   2.8% 2053/com.android.systemui: 1.8% user + 1% kernel / faults: 3 minor
E/ActivityManager( 1970):   2.2% 1429/surfaceflinger: 2.1% user + 0.1% kernel
E/ActivityManager( 1970):   0.7% 2155/com.android.inputmethod.latin: 0.7% user + 0% kernel / faults: 25 minor
E/ActivityManager( 1970):   0.4% 130/irq/334-kxtj9-i: 0% user + 0.4% kernel
E/ActivityManager( 1970):   0.4% 1019/mpdecision: 0% user + 0.4% kernel / faults: 2 minor
E/ActivityManager( 1970):   0% 88/kswapd0: 0% user + 0% kernel
E/ActivityManager( 1970):   0.3% 2848/kworker/u:3: 0% user + 0.3% kernel
E/ActivityManager( 1970):   0.1% 8866/kworker/0:3: 0% user + 0.1% kernel
E/ActivityManager( 1970):   0.3% 13705/kworker/u:6: 0% user + 0.3% kernel
E/ActivityManager( 1970):   0% 3/ksoftirqd/0: 0% user + 0% kernel
E/ActivityManager( 1970):   0% 6/kworker/u:0: 0% user + 0% kernel
E/ActivityManager( 1970):   0% 151/mmcqd/0: 0% user + 0% kernel
E/ActivityManager( 1970):   0.1% 1730/mdss_fb0: 0% user + 0.1% kernel
E/ActivityManager( 1970):   0.1% 2199/com.android.phone: 0.1% user + 0% kernel
E/ActivityManager( 1970):   0.1% 7079/kworker/u:2: 0% user + 0.1% kernel
E/ActivityManager( 1970):   0% 12574/com.duckduckgo.mobile.android: 0% user + 0% kernel
E/ActivityManager( 1970):   0.1% 20425/kworker/1:0: 0% user + 0.1% kernel
E/ActivityManager( 1970): 56% TOTAL: 53% user + 3.2% kernel + 0.1% iowait
E/ActivityManager( 1970): CPU usage from 2920ms to 3445ms later:
E/ActivityManager( 1970):   98% 15520/org.thoughtcrime.securesms: 96% user + 1.8% kernel / faults: 513 minor
E/ActivityManager( 1970):     96% 15520/crime.securesms: 94% user + 1.8% kernel
E/ActivityManager( 1970):     1.8% 20411/pool-10-thread-: 0% user + 1.8% kernel
E/ActivityManager( 1970):   5.6% 1970/system_server: 0% user + 5.6% kernel
E/ActivityManager( 1970):     3.7% 1987/ActivityManager: 0% user + 3.7% kernel
E/ActivityManager( 1970):     1.8% 1991/android.ui: 1.8% user + 0% kernel
E/ActivityManager( 1970):   1% 130/irq/334-kxtj9-i: 0% user + 1% kernel
E/ActivityManager( 1970): 51% TOTAL: 48% user + 3.8% kernel
```

**Comment by 2-4601** [comment]
I can **NOT** reproduce this with:
Motorola Moto G4 Play
Signal 3.26.2
Android 6.0.1

**Comment by sbaum** [comment]
A friend of mine is experiencing the same problem. He's running some older version of CyanogenMod (Android 4.4.x) on his Samsung Galaxy S3. So this problem could be related to Android 4.4...

**Comment by johanw666** [comment]
I can not reproduce this on a Sony Xperia Z1 Compact at stock 4.4.4.

**Comment by moxie0** [comment]
Might have something to do with the recent changes to support image keyboards. I could turn that off for <= 5.0

**Comment by lazlolazlolazlo** [comment]
Unfortunately bbb8ac1 does not fix this issue. When the keyboard is opened and you rotate the phone only half of screen is used. After rotating back, Signal hangs. 

![signal-2017-01-18-092818](https://cloud.githubusercontent.com/assets/601905/22056591/18590f08-dd61-11e6-8b64-f4c6e5b95099.jpeg)

Could be something with the emoji drawer. After recent changes sometimes some of the emoji are missing. They reappear after restart.

**Comment by moxie0** [comment]
oh, yeah looking at the log it's just an OOM. seems as if your device doesn't have enough memory to load the emoji pages, crazy

**Comment by johanw666** [comment]
So we can reverse https://github.com/WhisperSystems/Signal-Android/commit/bbb8ac113ba0a516668b1166e2e0641af348e821 ?

**Comment by nrizzio** [comment]
I have the same problem, same steps to reproduce, but [different exception and crash](https://gist.github.com/anonymous/fb8cc26aa221c494b2e9e58b7e85f1e3) (not an OOM):

```D/AndroidRuntime(20890): Shutting down VM
E/AndroidRuntime(20890): FATAL EXCEPTION: main
E/AndroidRuntime(20890): Process: org.thoughtcrime.securesms, PID: 20890
E/AndroidRuntime(20890): java.lang.IllegalStateException: couldn't move cursor to position -1
E/AndroidRuntime(20890): 	at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.getCursorAtPositionOrThrow(CursorRecyclerViewAdapter.java:181)
E/AndroidRuntime(20890): 	at org.thoughtcrime.securesms.ConversationAdapter.getHeaderId(ConversationAdapter.java:296)
E/AndroidRuntime(20890): 	at org.thoughtcrime.securesms.ConversationFragment$ConversationScrollListener.bindScrollHeader(ConversationFragment.java:491)
E/AndroidRuntime(20890): 	at org.thoughtcrime.securesms.ConversationFragment$ConversationScrollListener.onScrolled(ConversationFragment.java:455)
E/AndroidRuntime(20890): 	at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4541)
E/AndroidRuntime(20890): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3602)
E/AndroidRuntime(20890): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3265)
E/AndroidRuntime(20890): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
E/AndroidRuntime(20890): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
E/AndroidRuntime(20890): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at org.thoughtcrime.securesms.components.camera.QuickAttachmentDrawer.onLayout(QuickAttachmentDrawer.java:189)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1645)
E/AndroidRuntime(20890): 	at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1634)
E/AndroidRuntime(20890): 	at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1409)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
E/AndroidRuntime(20890): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
E/AndroidRuntime(20890): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(20890): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(20890): 	at android.view.View.layout(View.java:16916)
E/AndroidRuntime(20890): 	at android.view.ViewGroup.layout(ViewGroup.java:5405)
E/AndroidRuntime(20890): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2413)
E/AndroidRuntime(20890): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2122)
E/AndroidRuntime(20890): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
E/AndroidRuntime(20890): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6942)
E/AndroidRuntime(20890): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
E/AndroidRuntime(20890): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime(20890): 	at android.view.Choreographer.doFrame(
```
Let me know if this should go in a separate issue.

**Comment by KarolTrzeszczkowski** [comment]
The same bug, meizu m2 note with fleksy keyboard. My debug log: 
https://gist.github.com/751ad221d5e1cde237b22a2c30be1de5

**Comment by haffenloher** [comment]
@nrizzio @KarolTrzeszczkowski that's a different crash, looks like it's related to the new date headers.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
