### ISSUE TITLE
Tried to add stickers in Signal: The picture is gray and then it crashes

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#6072]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I took a picture in Signal with the front camera on my Moto G4 and when I tried to edit it the picture was completely gray. 
Okay, I thought, so I tried to upload a debug log. "Gathering" the log or whatever took several seconds longer than it usually does (I'm a log uploading veteran at this point) and then... Crash! 

### Steps to reproduce
1. Take a picture in Signal using the camera app from the attachments drawer
2. Try to edit it
3. At this point everything was gray
4. Back out of the editing and press the picture to show what it's going to look like
5. Notice it's black ( https://github.com/WhisperSystems/Signal-Android/issues/4732 )
6. Back out and try to send a debug log to GitHub
7. Fear the arrival of Crash Bandicoot!
8. Enter the chat again and notice that adding stickers now works
9. Send the picture
10. Everything now works like it should

**Actual result:** The picture is gray/black and the app crashes
**Expected result:** Pretty obvious isn't it?

### Screenshots
![signal](https://cloud.githubusercontent.com/assets/12563436/22069166/bfb64ee2-dd97-11e6-8627-b4c6fd813090.png)
(The tint is because of Twilight, a really good app for late nights)

### Device info
Device  : motorola Moto G (4) (athene)
Android : 6.0.1 (64, MPJ24.139-63)
Memory  : 33M (6.83% free, 192M max)
Memclass: 192
OS Host : ilclbld87
App     : Signal 3.27.1

### Link to debug log
After the crash:
https://gist.github.com/anonymous/cf78b20151a0f61ed4fd0ccfa45992aa
After successfully sending the picture, in case that helps
https://gist.github.com/anonymous/ac4d20c517930395a8fb89bffb12b80d

### Related 
https://github.com/WhisperSystems/Signal-Android/issues/4732

**Comment by 2-4601** [comment]
```
...
W art     : Throwing OutOfMemoryError "Failed to allocate a 10077708 byte allocation with 316712 free bytes and 309KB until OOM"
D skia    : --- decoder->decode returned false
E PriorityExecutor: Request threw uncaught throwable
E PriorityExecutor: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Failed to allocate a 10077708 byte allocation with 316712 free bytes and 309KB until OOM
E PriorityExecutor: 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E PriorityExecutor: 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor.afterExecute(FifoPriorityThreadPoolExecutor.java:96)
E PriorityExecutor: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
E PriorityExecutor: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E PriorityExecutor: 	at java.lang.Thread.run(Thread.java:818)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(FifoPriorityThreadPoolExecutor.java:118)
E PriorityExecutor: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 10077708 byte allocation with 316712 free bytes and 309KB until OOM
E PriorityExecutor: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E PriorityExecutor: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E PriorityExecutor: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
E PriorityExecutor: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeStream(Downsampler.java:329)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(Downsampler.java:220)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:153)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:50)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:19)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:39)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(ImageVideoBitmapDecoder.java:20)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(GifBitmapWrapperResourceDecoder.java:121)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(GifBitmapWrapperResourceDecoder.java:94)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:71)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:61)
E PriorityExecutor: 	at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(GifBitmapWrapperResourceDecoder.java:22)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(DecodeJob.java:190)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.DecodeJob.decodeSource(DecodeJob.java:177)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(DecodeJob.java:128)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(EngineRunnable.java:122)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.EngineRunnable.decode(EngineRunnable.java:101)
E PriorityExecutor: 	at com.bumptech.glide.load.engine.EngineRunnable.run(EngineRunnable.java:58)
E PriorityExecutor: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
E PriorityExecutor: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E PriorityExecutor: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E PriorityExecutor: 	... 3 more
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
