### ISSUE TITLE
Couldn't load jingle_peerconnection_so: findLibrary returned null

### ISSUE THREAD

**Issue by nomeata** [signalapp/Signal-Android#6213]
After upgrading from 3.28 to 3.29.2 (distributed by the Aptoide app store), Signal will not start here. I find this in the logs:

```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: java.lang.ExceptionInInitializerError
AndroidRuntime:         at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:90)
AndroidRuntime:         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
AndroidRuntime:         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4187)
AndroidRuntime:         at android.app.ActivityThread.access$1300(ActivityThread.java:137)
AndroidRuntime:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
AndroidRuntime:         at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime:         at android.os.Looper.loop(Looper.java:137)
AndroidRuntime:         at android.app.ActivityThread.main(ActivityThread.java:4781)
AndroidRuntime:         at java.lang.reflect.Method.invokeNative(Native Method)
AndroidRuntime:         at java.lang.reflect.Method.invoke(Method.java:511)
AndroidRuntime:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
AndroidRuntime:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
AndroidRuntime:         at dalvik.system.NativeStart.main(Native Method)
AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: Couldn't load jingle_peerconnection_so: findLibrary returned null
AndroidRuntime:         at java.lang.Runtime.loadLibrary(Runtime.java:365)
AndroidRuntime:         at java.lang.System.loadLibrary(System.java:542)
AndroidRuntime:         at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:21)
AndroidRuntime:         ... 13 more
```

This is on an unsupported platform (Alien Dalvik on Sailfish OS, now with the official Google Play Services installed), but maybe someone from the community can help me out here.

Downgrading to 3.28 fixed the problem.

**Comment by johanw666** [comment]
When I unzip the apk file I see a libjingle_peerconnection_so.so in the armeabi-v7a directory but none in the armeabi directory. None in the mips dir either but I doubt that is an ussie here. I'm not sure which cpu architecture Sailfish OS reports, but perhaps this could be the issue?

**Comment by nomeata** [comment]
```
~ $ cat /proc/cpuinfo 
Processor	: ARMv7 Processor rev 4 (v7l)
processor	: 0
BogoMIPS	: 13.53
```

**Comment by minomoto** [comment]
> Downgrading to 3.28 fixed the problem.
not for me. 
The same issue on x86.

**Comment by minomoto** [comment]
Probably some ROMs has rejection to lib with name lib* and  /lib/armeabi-v7a/libjingle_peerconnection_so.so  should be renamed to jingle_peerconnection_so.so  in future to avoid similar cases? 8)

**Comment by moxie0** [comment]
hmm doubt it, dunno what the rationale for that would be, and the same ROM didn't seem to have any problem with libredphone-audio.so

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
