### ISSUE TITLE
Gif not sending in conversation 

### ISSUE THREAD

**Issue by Epopplew** [signalapp/Signal-Android#6230]
```
Device  : samsung SCH-I545 (jfltevzw)
Android : 5.0.1 (I545VRUGOF1, LRX22C.I545VRUGOF1)
Memory  : 122M (11.64% free, 512M max)
Memclass: 128
OS Host : SWDD6122
App     : Signal 3.29.6

--------- beginning of system
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
V/ActivityThread(  715): updateVisibility : ActivityRecord{2f195a75 token=android.os.BinderProxy@d9e6da9 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}} show : true
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
V/ActivityThread(  715): updateVisibility : ActivityRecord{2f195a75 token=android.os.BinderProxy@d9e6da9 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}} show : false
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
W/ResourcesManager(  715): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
W/ResourcesManager(  715): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
V/ActivityThread(  715): updateVisibility : ActivityRecord{199c98e5 token=android.os.BinderProxy@d9e6da9 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}} show : true
V/ActivityThread(  715): updateVisibility : ActivityRecord{199c98e5 token=android.os.BinderProxy@d9e6da9 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}} show : false
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
V/ActivityThread(  715): updateVisibility : ActivityRecord{1f2e3227 token=android.os.BinderProxy@fc02b0a {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationListActivity}} show : false
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
V/ActivityThread(  715): updateVisibility : ActivityRecord{2553ffa8 token=android.os.BinderProxy@32cd3850 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ApplicationPreferencesActivity}} show : false
--------- beginning of main
I/System.out(  715): AsyncTask #4 calls detatch()
E/ViewRootImpl(  715): sendUserActionEvent() mView == null
D/ViewRootImpl(  715): ViewPostImeInputStage ACTION_DOWN
W/IInputConnectionWrapper(  715): showStatusIcon on inactive InputConnection
W/WebSocketConnection(  715): Sending keep alive...
W/WebSocketConnection(  715): WSC onMessage()
W/WebSocketConnection(  715): Message Type: 2
V/ActivityThread(  715): updateVisibility : ActivityRecord{20c58d7b token=android.os.BinderProxy@1c550219 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.LogSubmitActivity}} show : false
E/WindowManager(  715): 
E/WindowManager(  715): android.view.WindowLeaked: Activity org.thoughtcrime.securesms.LogSubmitActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{89a7567 V.E..... R....... 0,0-1002,762} that was originally added here
E/WindowManager(  715): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:465)
E/WindowManager(  715): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
E/WindowManager(  715): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(  715): 	at android.app.Dialog.show(Dialog.java:312)
E/WindowManager(  715): 	at org.whispersystems.libpastelog.SubmitLogFragment.handleShowSuccessDialog(SubmitLogFragment.java:298)
E/WindowManager(  715): 	at org.whispersystems.libpastelog.SubmitLogFragment.access$300(SubmitLogFragment.java:81)
E/WindowManager(  715): 	at org.whispersystems.libpastelog.SubmitLogFragment$SubmitToPastebinAsyncTask.onPostExecute(SubmitLogFragment.java:396)
E/WindowManager(  715): 	at org.whispersystems.libpastelog.SubmitLogFragment$SubmitToPastebinAsyncTask.onPostExecute(SubmitLogFragment.java:336)
E/WindowManager(  715): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
E/WindowManager(  715): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/WindowManager(  715): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/WindowManager(  715): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/WindowManager(  715): 	at android.os.Looper.loop(Looper.java:145)
E/WindowManager(  715): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
E/WindowManager(  715): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager(  715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/WindowManager(  715): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/WindowManager(  715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
W/MessageRetrievalService(  715): Application level read timeout...
W/MessageRetrievalService(  715): Network requirement: true, active activities: 0, push pending: 0
W/MessageRetrievalService(  715): Shutting down pipe...
W/WebSocketConnection(  715): WSC disconnect()...
W/MessageRetrievalService(  715): Looping...
W/MessageRetrievalService(  715): Waiting for websocket state change....
W/MessageRetrievalService(  715): Network requirement: true, active activities: 0, push pending: 0
W/WebSocketConnection(  715): onClosing()!...
W/WebSocketConnection(  715): onClose()...
W/WebSocketConnection(  715): Sending keep alive...
D/MultiPhoneWindow(  715): updateMultiWindowStyle style:MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1},newStyle=MultiWindowStyle{type=0, zone=ZONE_UNKNOWN, option=0x01000002, bounds=null, isNull=false, isolatedCenterPoint=Point(0, 0), scale=0.0, specificTaskId=-1}
D/MultiPhoneWindow(  715): MultiPhoneWindow : mMinStackBoundForPortRect(0, 0 - 626, 1113), mMinStackBoundForPort=Rect(0, 0 - 1113, 626)
V/MediaPlayer(  715): decode(47, 11490428, 5795)
D/Activity(  715): performCreate Call secproduct feature valuefalse
D/Activity(  715): performCreate Call debug elastic valuetrue
D/Scrubber(  715): scrubbing input
```

**Comment by jeremymasters** [comment]
You'll probably want a little better steps to reproduce, even if somewhat basic.

**Comment by Epopplew** [comment]
I opened up a conversation with a signal contact 
Tapped the attachment icon 
Selected gifs 
Chose a gif 
And received an error message saying "Attachments exceed size limits for this type of conversation."

**Comment by jeremymasters** [comment]
I think this is the whole thing where the gif is not re-sized enough...or we need to raise the mms size limit a little.

**Comment by 2-4601** [comment]
related #5958, #6187

**Comment by Epopplew** [comment]
I get the error with a fellow signal contact. Not an unsecured contact

**Comment by jeremymasters** [comment]
Does it do it with ALL gifs or just particular ones?

**Comment by Epopplew** [comment]
Every gif,  but works fine in group chat

**Comment by Epopplew** [comment]
I've duplicated it almost 40x now

**Comment by jeremymasters** [comment]
Looks like a stock verizon S4 then?  I should try this on my S5 since it's the same memory class.  Unfortunately, it's at home. :cry:

**Comment by Epopplew** [comment]
Yes stock vzw s4

**Comment by Epopplew** [comment]
I believe that I may have found the issue. Testing the fix now

**Comment by Epopplew** [comment]
![20170217_105841](https://cloud.githubusercontent.com/assets/25801062/23072557/1b4159f8-f500-11e6-8663-67f33a9e7140.png)

**Comment by Epopplew** [comment]
I had to turn off the setting in developer options 
"Do not keep activities" needs to be unchecked

**Comment by moxie0** [comment]
That sounds like an unsupported configuration to me, unless you have ideas as to why it would be important to support

**Comment by Epopplew** [comment]
I found a fix for it

**Comment by Epopplew** [comment]
With the box checked I'm not able to send gifs, but with it unchecked I am.
It fixed my friend's issue as well. He has a stock vzw s4 too

**Comment by dalanmiller** [comment]
Any idea why this is the case @Epopplew?

**Comment by michaeljensen** [comment]
Mine is unchecked on my LG G4 and I'm unable to send any gifs.  It works fine for messages to other signal users, but not over SMS.

**Comment by michaeljensen** [comment]
I take that back.  It works with some gifs but not others...  It seems to be pickier about file size than my normal SMS app.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
