### ISSUE TITLE
java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by Trolldemorted** [signalapp/Signal-Android#6283]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Out of the blue, signal crashed.

```
02-21 12:26:42.279  2235  3222 E AndroidRuntime: java.lang.OutOfMemoryError: Could not allocate JNI Env
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at java.lang.Thread.nativeCreate(Native Method)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at java.lang.Thread.start(Thread.java:1063)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.ConnectionPool.put(ConnectionPool.java:134)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.OkHttpClient$1.put(OkHttpClient.java:152)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:191)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:132)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:101)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at okhttp3.RealCall.execute(RealCall.java:63)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getConnection(PushServiceSocket.java:655)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:529)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:223)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:143)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.onRun(PushNotificationReceiveJob.java:36)
02-21 12:26:42.279  2235  3222 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-21 12:26:42.279 2235 3222 E AndroidRuntime: at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Pretty sure this is not related to my build, and the device had (after the crash) ~1.5GB free ram. [An issue on so](http://stackoverflow.com/questions/40451877/java-lang-outofmemoryerror-could-not-allocate-jni-env-always-android-java) linked this error messages to leaked file descriptors, which is [apparently intended](https://github.com/WhisperSystems/libsignal-service-java/pull/26) in libsignal. The libsignal version i use has fixed that issue, but maybe there are other leaked FDs?

### Steps to reproduce
- cannot (yet) reproduce, happened only once

### Device info

**Device:** Xiaomi Redmi Note 3 Pro
**Android version:** 6.0.1
**Signal version:** 3.29.6 + https://github.com/Trolldemorted/Signal-Android/commit/cdb8ac203636aa9600445f09cfcd9b91863342cd

### Link to debug log

https://gist.github.com/anonymous/51447caee0494fef9bb45994cd4fada3

**Comment by Trolldemorted** [comment]
It has happened again, but on a different device and with a different user and with an unmodified signal:

https://gist.github.com/anonymous/b4bf8bb05611b0c42a75aaac8ae130d6

Nothing extraordinary happened, except that the device received a lot of receipts before it crashed.

**Comment by Trolldemorted** [comment]
i think i found the culprit!

https://github.com/WhisperSystems/libsignal-service-java/pull/40

**Comment by Trolldemorted** [comment]
was this fixed by https://github.com/WhisperSystems/libsignal-service-java/commit/05571223933d929b091a254c1f1557cf08b25ea4?

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
