### ISSUE TITLE
Strange crash at startup

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#6923]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I started Signal 4.9.9 it crashed after I entered my password.

### Steps to reproduce
- Difficult, this was a one-off.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/anonymous/f2943404c52c75ae28e5044f55203c41

The relevant part seems to me this:
```
09-06 21:34:11.132  9867 22423 W WebSocketConnection: onConnected()
09-06 21:34:11.137  9867 22423 W WebSocketConnection: WSC onMessage()
09-06 21:34:11.141  9867 22423 W WebSocketConnection: Message Type: 1
09-06 21:34:11.155  9867  9887 W CleanPreKeysJob: Cleaning prekeys...
09-06 21:34:11.164  9867  9887 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-4
09-06 21:34:11.164  9867  9887 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9867
09-06 21:34:11.164  9867  9887 E AndroidRuntime: java.lang.AssertionError: Migration didn't happen!
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSerializedRecord(TextSecurePreKeyStore.java:187)
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSignedPreKeys(TextSecurePreKeyStore.java:83)
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSignedPreKeys(SignalProtocolStoreImpl.java:111)
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.CleanPreKeysJob.onRun(CleanPreKeysJob.java:62)
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
09-06 21:34:11.164  9867  9887 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
09-06 21:34:11.172  3436  4608 D ActivityManager: New dropbox entry: org.thoughtcrime.securesms, data_app_crash, c3e86631-d62b-4c3a-97e2-1b398c54279b
09-06 21:34:11.186  9867 22428 W RecipientPreferenceDatabase: Muted until: 0
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
