### ISSUE TITLE
Conversation view crashes without phone permission

### ISSUE THREAD

**Issue by daradib** [signalapp/Signal-Android#7101]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I deny the phone permission (`READ_PHONE_STATE`), the app crashes when opening a conversation thread.

### Steps to reproduce
- deny phone permission
- click on a conversation in the main view (or a notification that opens a conversation)

**Actual result:** App crashes and appears blank
**Expected result:** App should display conversation

### Device info

**Device:** Nexus 6P
**Android version:** 8.0.0 (CopperheadOS)
**Signal version:** 4.10.12 ([CopperheadOS build](https://github.com/copperhead/Noise))

Was not reproducible with Signal 4.9.9.

### Link to debug log

Here is an excerpt from `adb logcat`

    FATAL EXCEPTION: main
    Caused by: android.view.InflateException: Binary XML file line #57: Binary XML file line #167: Error inflating class org.thoughtcrime.securesms.components.SendButton
    at org.thoughtcrime.securesms.ConversationActivity.onCreate(ConversationActivity.java:261)
    at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:50)
    Caused by: java.lang.SecurityException: getActiveSubscriptionInfoList: Neither user [redacted] nor current process has android.permission.READ_PHONE_STATE.
    at org.thoughtcrime.securesms.util.dualsim.SubscriptionManagerCompat.getActiveSubscriptionInfoList(SubscriptionManagerCompat.java:50)
    at org.thoughtcrime.securesms.TransportOptions.getTransportOptionsForSimCards(TransportOptions.java:149)
    at org.thoughtcrime.securesms.TransportOptions.initializeAvailableTransports(TransportOptions.java:129)
    at org.thoughtcrime.securesms.TransportOptions.<init>(TransportOptions.java:34)
    at org.thoughtcrime.securesms.components.SendButton.initializeTransportOptions(SendButton.java:47)
    at org.thoughtcrime.securesms.components.SendButton.<init>(SendButton.java:35)
    ... 38 more

**Comment by Lesik** [comment]
When I choose to deny the phone permission, the settings warn me that "Signal is designed for an earlier version of Android" and might not be able to cope with permissions suddenly being denied. That's also why when installing Signal you see it requiring a whole bunch of permissions before you hit "install", unlike WhatsApp or Telegram, who require no permissions during installation but gradually ask the user to grant those.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
