### ISSUE TITLE
[4.13.6] Unable to complete registration

### ISSUE THREAD

**Issue by artemalexpetrov** [signalapp/Signal-Android#7230]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unable to complete registration if user is not authenticated in GooglePlayServices.

### Steps to reproduce
- you need a device where user is not authenticated in GoogleAccount
- install Signal v4.13.6
- type your phone number and tap on "Registration" button

**Actual result:** I got a message "Unable to connect to service. Please check network connection and try again."
**Expected result:** You should catch GCM IOException [here](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/RegistrationActivity.java#L288) when you try to obtain gcmToken.

```
Optional<String> gcmToken = Optional.absent();
if (gcmSupported) {
  try {
    // obtain gcmToken here 
  } catch (IOException e) {
    // ....
  }
}
```
### Device info

**Device:** Xiaomi Redmi Note3
**Android version:** 7.0
**Signal version:** 4.13.6

### Logs
```
11-29 13:02:27.292 4696-4763/org.thoughtcrime.securesms W/TextSecurePreferences: Setting push registered: false
11-29 13:02:27.312 4696-4763/org.thoughtcrime.securesms W/RegistrationActivity: java.io.IOException: AUTHENTICATION_FAILED
                                                                              at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
                                                                              at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
                                                                              at org.thoughtcrime.securesms.RegistrationActivity$1.doInBackground(RegistrationActivity.java:287)
                                                                              at org.thoughtcrime.securesms.RegistrationActivity$1.doInBackground(RegistrationActivity.java:274)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
```

**Comment by johanw666** [comment]
Maybe related to https://github.com/WhisperSystems/Signal-Android/issues/7229 ?

**Comment by artemalexpetrov** [comment]
No. I can't complete registration at all without authentication in GooglePlayServices on my device.

**Comment by moxie0** [comment]
Please (always) include a full debug log

**Comment by tbruckmaier** [comment]
Same problem here on CAT S30, stock Android 5.1, no google account (but google play services active 11.9.51)

I also tried installing the older versions 4.10.12 and 4.12.3, with these i receive the signal verification code sms, but it then fails with a "connection error". I installed signal the last time without any problems on November 7th, so i guess the version back then must have been 4.12.3

I cannot attach a debug log, as i cannot access the settings dialog from the registration screen as described in https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
adb fails to recongnize my attached device.

**Comment by guidovw** [comment]
Same problem on my Mi6 with China ROM running MIUI 9.2, and Google Play installed from backup as described here: https://www.youtube.com/watch?v=XWATDQm1nLQ
Google Play Store does not recognize the device, Find my device doesn't work, and Signal behaves as described here by artemalexpetrov.

**Comment by bjanssen** [comment]
For me the same as @guidovw (Mi6 + backup method + phone not showing up in Google Play Store settings).

The error I get (both via wifi and 4G) reads: "Signal: Unable to connect to service error. Please check network connection and try again."

I have a Xiaomi Mi 6 phone which runs Xiaomi's android flavour `MIUI 9.2.4.0 | Stable`, Signal version `4.16.9` and Google Play Store version: `Version: 9.2.11-all [0] [PR] 188192317`.

The messages that were captured using `adb logcat` after the "REGISTER" button was pressed (with verified working internet via 4G, wifi disabled, "PHONE NUMBER" field filled in) are listed at the bottom of this request.
This line specifically stands out:
`03-18 14:18:33.880  3441  5434 E ExecutionCriteria: Package unavailable for task: com.facebook.katana/com.facebook.api.feedcache.resync.NewsFeedCacheInvalidationGCMService{u=0 tag="NewsFeedCacheInvalidationGCMService" trigger=window{start=43200s,end=43230s,earliest=-39865325s,latest=-39865295s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=-39908525s last_run=N/A jid=N/A status=PENDING retries=0 client_lib=SOURCE_UNKNOWN-0}`
It is surprising to me that something related to Facebook seems to be requested. Since I don't have a Facebook account this obviously is not available on my phone.

```
03-18 14:18:33.431  6550  6550 W PlayServicesUtil: Play Services: 0
03-18 14:18:33.438  6550  7492 W TextSecurePreferences: Setting push registered: false
03-18 14:18:33.471  1819  6184 D CompatibilityInfo: mCompatibilityFlags - 0
03-18 14:18:33.471  1819  6184 D CompatibilityInfo: applicationDensity - 480
03-18 14:18:33.471  1819  6184 D CompatibilityInfo: applicationScale - 1.0
03-18 14:18:33.486  1819  6188 D CompatibilityInfo: mCompatibilityFlags - 0
03-18 14:18:33.486  1819  6188 D CompatibilityInfo: applicationDensity - 480
03-18 14:18:33.486  1819  6188 D CompatibilityInfo: applicationScale - 1.0
03-18 14:18:33.698  3441  5823 W Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
03-18 14:18:33.699  3441  5823 W Conscrypt: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 14:18:33.699  3441  5823 W Conscrypt: 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(com.google.android.gms@12221448@12.2.21 (448-188803320):13)
03-18 14:18:33.699  3441  5823 W Conscrypt: Caused by: android.system.ErrnoException: setsockopt failed: EBADF (Bad file descriptor)
03-18 14:18:33.699  3441  5823 W Conscrypt: 	at libcore.io.Posix.setsockoptTimeval(Native Method)
03-18 14:18:33.699  3441  5823 W Conscrypt: 	at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:157)
03-18 14:18:33.781  3441  5823 W Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
03-18 14:18:33.781  3441  5823 W Conscrypt: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 14:18:33.782  3441  5823 W Conscrypt: 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(com.google.android.gms@12221448@12.2.21 (448-188803320):13)
03-18 14:18:33.782  3441  5823 W Conscrypt: Caused by: android.system.ErrnoException: setsockopt failed: EBADF (Bad file descriptor)
03-18 14:18:33.782  3441  5823 W Conscrypt: 	at libcore.io.Posix.setsockoptTimeval(Native Method)
03-18 14:18:33.782  3441  5823 W Conscrypt: 	at libcore.io.ForwardingOs.setsockoptTimeval(ForwardingOs.java:157)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 
03-18 14:18:33.863  6550  7492 W RegistrationActivity: java.io.IOException: TOO_MANY_REGISTRATIONS
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$1.doInBackground(RegistrationActivity.java:341)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$1.doInBackground(RegistrationActivity.java:330)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-18 14:18:33.863  6550  7492 W RegistrationActivity: 	at java.lang.Thread.run(Thread.java:760)
03-18 14:18:33.880  3441  5434 E ExecutionCriteria: Package unavailable for task: com.facebook.katana/com.facebook.api.feedcache.resync.NewsFeedCacheInvalidationGCMService{u=0 tag="NewsFeedCacheInvalidationGCMService" trigger=window{start=43200s,end=43230s,earliest=-39865325s,latest=-39865295s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=-39908525s last_run=N/A jid=N/A status=PENDING retries=0 client_lib=SOURCE_UNKNOWN-0}
03-18 14:18:33.882  6550  6550 I Toast   : Show toast from OpPackageName:org.thoughtcrime.securesms, PackageName:org.thoughtcrime.securesms
03-18 14:18:37.381  1819  1819 W WindowManager: Attempted to remove non-existing token: android.os.Binder@bd75642
03-18 14:18:40.678   719   719 I rmt_storage: rmt_storage_connect_cb: clnt_h=0xd conn_h=0x7f8c62a000
03-18 14:18:40.678   719   719 I rmt_storage: rmt_storage_rw_iovec_cb: /boot/modem_fs1: req_h=0xd msg_id=3: R/W request received
03-18 14:18:40.678   719   719 I rmt_storage: wakelock acquired: 1, error no: 42
03-18 14:18:40.679   719  1339 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: Unblock worker thread (th_id: 547813717072)
03-18 14:18:40.755   719  1339 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: req_h=0xd msg_id=3: Bytes written = 2097152
03-18 14:18:40.755   719  1339 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: req_h=0xd msg_id=3: Send response: res=0 err=0
03-18 14:18:40.755   719  1339 I rmt_storage: rmt_storage_client_thread: /boot/modem_fs1: About to block rmt_storage client thread (th_id: 547813717072) wakelock released: 1, error no: 0
03-18 14:18:40.755   719  1339 I rmt_storage: 
03-18 14:18:40.756   719   719 I rmt_storage: rmt_storage_disconnect_cb: clnt_h=0xd conn_h=0x7f8c62a000
03-18 14:18:46.597  3441  6247 V NativeCrypto: SSL shutdown failed: ssl=0x7f706d25c8: I/O error during system call, Software caused connection abort
03-18 14:18:46.734  3751  6298 V NativeCrypto: SSL shutdown failed: ssl=0x7f91c42248: I/O error during system call, Software caused connection abort
03-18 14:18:48.551  3441  6247 V NativeCrypto: SSL shutdown failed: ssl=0x7f91c53d88: I/O error during system call, Software caused connection abort
```

**Comment by bjanssen** [comment]
Similar behaviour for Xiaomi Mi 6 with `MIUI 9.5.3.0 | Stable`.

**Comment by bobcov** [comment]
Same problem today with Xiaomi Redmi Note 3 MIUI Global 8.1.3   Had to load Play Services despite this being specifically removed as a requirement by Moxie

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
