### ISSUE TITLE
4.14.7: messaging from desktop client and receiving SMS and Android crashes

### ISSUE THREAD

**Issue by jeremymasters** [signalapp/Signal-Android#7280]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Was chatting on the desktop client and received an SMS on Android and at some point in there, the Android app crashed

### Steps to reproduce
- chatting on Signal desktop
- receive SMS
- chat on desktop app some more

**Actual result:** app requires password to open
**Expected result:** Still opens and does not require password

### Device info
**Device:** Galaxy S8
**Android version:** 7.0 Verizon stock
**Signal version:** 4.14.7

### Link to debug log
https://gist.github.com/46da0948e77c8b5e2bc0d8114a89899f

**Comment by jeremymasters** [comment]
```12-15 10:32:50.924  8897  8897 E AndroidRuntime: FATAL EXCEPTION: main
12-15 10:32:50.924  8897  8897 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8897
12-15 10:32:50.924  8897  8897 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1229544 bytes
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4209)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1229544 bytes
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:628)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4183)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4201)
12-15 10:32:50.924  8897  8897 E AndroidRuntime: 	... 7 more
12-15 10:32:50.962  8897  8897 I Process : Sending signal. PID: 8897 SIG: 9
12-15 10:32:51.051 23668 23668 I SELinux : SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=org.thoughtcrime.securesms 
12-15 10:32:51.082 23668 23668 D TimaKeyStoreProvider: TimaKeyStore is enabled: try add TimaSignature Service and generateKeyPair Service
12-15 10:32:51.226 23668 23668 I ResourcesManager: updateResourcesForOpenThemeChange for Desktop mode 
12-15 10:32:51.240 23668 23668 I art     : Starting a blocking GC AddRemoveAppImageSpace
12-15 10:32:51.254 23668 23668 I MultiDex: VM with version 2.1.0 has multidex support
12-15 10:32:51.254 23668 23668 I MultiDex: Installing application
12-15 10:32:51.254 23668 23668 I MultiDex: VM has multidex support, MultiDex support library is disabled.
12-15 10:32:51.270 23668 23668 W PartProvider: onCreate()

**Comment by moxie0** [comment]
Is this a debug log? That stack trace doesn't look like it belongs to Signal, and there's a bunch of other non-Signal looking stuff in there.

**Comment by jeremymasters** [comment]
Just grabbed this to check https://gist.github.com/d496706d8f635e4f2afe5d1294bfec10

**Comment by jeremymasters** [comment]
If you open the debug log from my initial post though that one has all the bad junk.

**Comment by jeremymasters** [comment]
```InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@b44890c nm : org.thoughtcrime.securesms ic=com.android.internal.widget.EditableInputConnection@9383255
12-15 10:31:58.686  8897  8897 I InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
12-15 10:31:58.690  8897  8897 D InputTransport: Input channel constructed: fd=74
12-15 10:31:58.690  8897  8897 D InputTransport: Input channel destroyed: fd=71
12-15 10:31:59.185  8897  8897 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1227592)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: Got RemoteException calling setExtractedText
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: android.os.TransactionTooLargeException: data parcel size 1227592 bytes
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at android.os.BinderProxy.transactNative(Native Method)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at android.os.BinderProxy.transact(Binder.java:628)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at com.android.internal.view.IInputContextCallback$Stub$Proxy.setExtractedText(IInputContextCallback.java:210)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:332)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at android.os.Looper.loop(Looper.java:154)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at java.lang.reflect.Method.invoke(Native Method)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
12-15 10:31:59.197  8897  8897 W IInputConnectionWrapper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
