### ISSUE TITLE
Signal calls get stuck "connecting" when received in a Google Pixel 2

### ISSUE THREAD

**Issue by cegg1** [signalapp/Signal-Android#7375]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Incoming Signal calls sometimes get stuck "connecting" and do not fully connect. This happens when calling a Pixel 2 from a Nexus 5 but does not happen when calling the Nexus 5 from the Pixel 2. I suspect the issue is related to the Pixel 2. The issue is persistent, it keeps happening over time on different 4G and wifi networks. No problems with the network are suspected. Signal text messages remain unaffected even though the call is not established. 

### Steps to reproduce
- make a Signal call to a Pixel 2 from another phone
- the call gets established around 50% of the time. The other 50% of the time it happens as follows:

**Actual result:** The phone does not ring. A Signal notification appears that says "Connecting...", together with a phone icon on the notification bar. The phone never rings and never gives up "connecting", even if the caller hangs up. If the notification is tapped, a blank "Signal Call" screen appears, but does now show the caller's number. This screen does not allow the receiver to pick up the call, but it has a red button to hang up. If the receiver hangs up, the call stops immediately on the caller's end, therefore there is some kind of communication between devices.  

**Expected result:** The phone rings as usual and the call is established as usual. 

### Screenshots
Notification of call "connecting..."
![failed-call](https://user-images.githubusercontent.com/28192843/35644589-3b35c2c0-06c1-11e8-9524-52af7762ca63.jpg)

Blank call screen
![failed-call-2](https://user-images.githubusercontent.com/28192843/35644602-4b9a7f34-06c1-11e8-9f5b-932b66bc984f.png)

### Device info
**Receiver's device:** Google Pixel 2
**Android version:** Stock Android 8.1.0
**Signal version:** 4.5.15

**Caller's device:** Google Nexus 5
**Android version:** official LineageOS 7.1 (no root)
**Signal version:** 4.5.15

### Link to debug log
Pixel 2 (receiver):
https://gist.github.com/cbf3df455621b341e9de9e4e4dab75b0

**Comment by moxie0** [comment]
This log doesn't include the period of time that covers the incoming call

**Comment by moxie0** [comment]
The 3G receiving log does show an ICE handshake failure, which would indicate a network problem of some kind. I'd need a full log that covers the call to see more.

**Comment by cegg1** [comment]
Thanks for having a look. Here are some more logs:

1) Incoming call never gets established: https://gist.github.com/320b4964a7026bc21ab1a11cebfff41f
2) Incoming call establishes and then the call drops: https://gist.github.com/cae362e3dc777d6306166950df24709f
3) Successful (normal) call: https://gist.github.com/776109763e6863bad63c03a76fd91d99
4) Signal crashed with one of the incoming calls. I submitted the crash report through the Google mechanism as "Pixel 2 crashed with incoming call".  

May I highlight the following bits from the logs above? Apologies if they are not relevant. 
```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 22213
AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.AnimatorSet.cancel()' on a null object reference
AndroidRuntime: at org.thoughtcrime.securesms.components.webrtc.WebRtcAnswerDeclineButton.resetElements (WebRtcAnswerDeclineButton.java:300)
```
```
RetrieveProfileJob: java.io.IOException: No connection!
RetrieveProfileJob: at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:134)
RetrieveProfileJob: at org.whispersystems.signalservice.api.SignalServiceMessagePipe.getProfile(SignalServiceMessagePipe.java:142)
```
```
JobConsumer: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Unable to parse entity
JobConsumer: at org.whispersystems.signalservice.internal.push.PushServiceSocket.retrieveProfile(PushServiceSocket.java:372)
```
```
WebSocketConnection: WSC connect()...
SignalCommunicationModule: onConnecting()
WebSocketConnection: onFailure()
WebSocketConnection: 
WebSocketConnection: onClose()...
SignalCommunicationModule: onDisconnected()
```
```
EventBus: No subscribers registered for event class org.thoughtcrime.securesms.events.WebRtcViewModel
EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
```
```
MessageRetrievalService: Application level read timeout...
MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: false
MessageRetrievalService: Shutting down pipe...
WebSocketConnection: WSC disconnect()...
MessageRetrievalService: Looping...
MessageRetrievalService: Waiting for websocket state change....
MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: false
WebSocketConnection: onClosing()!...
WebSocketConnection: onClose()...
SignalCommunicationModule: onDisconnected()
```

**Comment by cegg1** [comment]
Regading the possibility of network issues, I have run the WebRTC connectivity tests in case they can throw some light. 

**WebRTC Troubleshooter (test.webrtc.org)**
![screenshot_20180204-155900](https://user-images.githubusercontent.com/28192843/35779461-5fab3a8e-09c5-11e8-8271-d7571e2ccc5a.png)
![screenshot_20180204-160153](https://user-images.githubusercontent.com/28192843/35779462-65ac7c4a-09c5-11e8-9c0b-0522a22604f1.png)

Full log from test.webrtc.org: https://test.webrtc.org/report/AMIfv94pymjpSV8BPZNF106UsYDetTFvs5T_pRowRd6DkzYbna1fZ3AXb09hh9x7pbiWQrgZ0Vyj997Ljhkuy7X9DPXOkvH6dXuhSQegwF7hPkKWbMQ8XfiDOoxMqh1CJmzkHsWURqBgjpDxRw7t0SWf1wV94pFXJA

**Netscan WebRTC test**
![screenshot_20180204-160932](https://user-images.githubusercontent.com/28192843/35779548-92723c5a-09c6-11e8-8586-4b1cd50f9f29.png)
![screenshot_20180204-160943](https://user-images.githubusercontent.com/28192843/35779550-9554ca3c-09c6-11e8-996c-7f4079be8a25.png)

Full log: https://www.netscan.co/r/GMtAP

Pixel 2
EE UK network

**Comment by cegg1** [comment]
Here is a log from a different phone, a Nexus 4, after (unsuccessfully) trying to call the Pixel 2 several times:
https://gist.github.com/anonymous/e1282318e17fbe7150459918d0b10a9d
```
W WebRtcCallService: Got answer for recipient and call id we're not currently dialing: -4086587742473579072, org.thoughtcrime.securesms.recipients.Recipient@12edd212
```

Here the Pixel 2 does not receive the calls:
https://gist.github.com/anonymous/b3d2e0e6f8a24ec0ffe2f7a8bce52fcb
```
W WebRtcCallService: onStartCommand...
W WebRtcCallService: Can only answer from ringing!
```

And here the Pixel 2 receives 3 lost call notifications in a row but still does not ring!
https://gist.github.com/anonymous/b98353ddf6c277eccb3438f40cfbc0d6
```
W SignalServiceMessageSender: Transmitting over pipe...
W SignalServiceMessageSender: java.io.IOException: No connection!
W SignalServiceMessageSender: at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:134)
W SignalServiceMessageSender: at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:119)
W SignalServiceMessageSender: at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:532)
W SignalServiceMessageSender: at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendCallMessage(SignalServiceMessageSender.java:149)
W SignalServiceMessageSender: at org.thoughtcrime.securesms.service.WebRtcCallService$7.call(WebRtcCallService.java:944)
W SignalServiceMessageSender: at org.thoughtcrime.securesms.service.WebRtcCallService$7.call(WebRtcCallService.java:941)
W SignalServiceMessageSender: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W SignalServiceMessageSender: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W SignalServiceMessageSender: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W SignalServiceMessageSender: 	at java.lang.Thread.run(Thread.java:764)
W SignalServiceMessageSender: Falling back to new connection...
W SignalServiceMessageSender: Not transmitting over pipe...
```

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
