### ISSUE TITLE
crash when changing contact color

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#7393]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Tried to change contact color and signal crashed. Could not reproduce. I've attached the log below (this is from a week ago)

```
01-30 18:35:40.558 10390 10390 E AndroidRuntime: FATAL EXCEPTION: main
01-30 18:35:40.558 10390 10390 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10390
01-30 18:35:40.558 10390 10390 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at org.thoughtcrime.securesms.color.MaterialColor.represents(MaterialColor.java:88)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at org.thoughtcrime.securesms.color.MaterialColors$MaterialColorList.getByColor(MaterialColors.java:56)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$ColorChangeListener.onPreferenceChange(RecipientPreferenceActivity.java:443)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at org.thoughtcrime.securesms.preferences.widgets.ColorPickerPreference.setInternalColor(ColorPickerPreference.java:236)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at org.thoughtcrime.securesms.preferences.widgets.ColorPickerPreference.setColor(ColorPickerPreference.java:111)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at org.thoughtcrime.securesms.preferences.widgets.ColorPickerPreferenceDialogFragmentCompat.onDialogClosed(ColorPickerPreferenceDialogFragmentCompat.java:50)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at android.support.v7.preference.PreferenceDialogFragmentCompat.onDismiss(PreferenceDialogFragmentCompat.java:264)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1337)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
01-30 18:35:40.558 10390 10390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

### Device info

**Device:** Moto G4 Plus
**Android version:** 7.0
**Signal version:** 4.15.5

### Link to debug log
https://gist.github.com/anonymous/888ddd1df6d1ea77b5e1b87c7305ea96

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
