### ISSUE TITLE
Signal crashes on startup (Migration didn't happen! )

### ISSUE THREAD

**Issue by pawelpaszczak** [signalapp/Signal-Android#7412]
**Device info**
Device: Samsung Galaxy S4
Android version: 7.1.2 (LineageOS)
Signal version: the newest one

Welcome!
Signal crashes on startup... :(
on adb logcat I got:
`````
02-14 20:52:45.852  3857  3884 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-3
02-14 20:52:45.852  3857  3884 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3857
02-14 20:52:45.852  3857  3884 E AndroidRuntime: java.lang.AssertionError: Migration didn't happen! /data/user/0/org.thoughtcrime.securesms/files/signed_prekeys/6089548, 0
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSerializedRecord(TextSecurePreKeyStore.java:187)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSignedPreKey(TextSecurePreKeyStore.java:66)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSignedPreKey(SignalProtocolStoreImpl.java:106)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionBuilder.processV3(SessionBuilder.java:123)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionBuilder.process(SessionBuilder.java:107)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:180)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:150)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:159)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:129)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:166)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:145)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-14 20:52:45.852  3857  3884 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-14 20:52:45.856  3857  3884 I Process : Sending signal. PID: 3857 SIG: 9
02-14 20:52:45.885   616  1536 I ActivityManager: Process org.thoughtcrime.securesms (pid 3857) has died
02-14 20:52:45.886   616  1536 D ActivityManager: cleanUpApplicationRecord -- 3857
02-14 20:52:45.886   616  1536 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{3f1819c u0 org.thoughtcrime.securesms/.service.MessageRetrievalService}
`````
I tried upgrade to a beta version... on startup it makes Database update but it crashes... and it crashes all the time... same error on adb logcat ...

**Comment by johanw666** [comment]
What is "newest one"? The occurence of TextSecurePreKeyStore in the log suggests a 4.16.x version.

**Comment by moxie0** [comment]
A file you have on disk is corrupted. One or two other people running LineageOS have posted something similar, not sure what the root cause is though.

**Comment by pawelpaszczak** [comment]
I had version 4.15.5 when the crash occurred. Then I upgraded to beta 4.16.5 - after first run database update crashed..
I lost all my conversations because Signal was my default sms app...

Is there any way to fix database?

**Comment by johanw666** [comment]
@pawelpaszczak you could try some of the tools used in https://github.com/signalapp/Signal-Android/issues/7386

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
