### ISSUE TITLE
Signal crash during usage

### ISSUE THREAD

**Issue by dcherian** [signalapp/Signal-Android#7413]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashed during usage; might've been when I tapped a notification.

```
02-14 11:39:59.728 16852 19727 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #16
02-14 11:39:59.728 16852 19727 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16852
02-14 11:39:59.728 16852 19727 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.thoughtcrime.securesms.database.Address org.thoughtcrime.securesms.database.documents.NetworkFailure.getAddress()' on a null object reference
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at org.thoughtcrime.securesms.MessageRecipientListItem$ResendAsyncTask.doInBackground(MessageRecipientListItem.java:205)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at org.thoughtcrime.securesms.MessageRecipientListItem$ResendAsyncTask.doInBackground(MessageRecipientListItem.java:187)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-14 11:39:59.728 16852 19727 E AndroidRuntime: ... 3 more
```

### Device info

**Device:** Moto G4 Plus
**Android version:** 7.0
**Signal version:** 4.16.5

### Link to debug log
https://gist.github.com/anonymous/2a39edab66fd842baaea1b0ae0d38bc1

**Comment by Dyras** [comment]
Moto G4 user here. Crashed when I received an attachment and a message while it was loading.

https://gist.github.com/anonymous/3ffb7e5df36b0c0e8006b2b4b72b5396

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
