### ISSUE TITLE
Crash when swiping: ConversationListItemInboxZero

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#7423]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Swiping if the conversation list is empty crashes Signal

### Steps to reproduce
- have conversations archived
- have an empty conversation list
- swipe right

**Actual result:** Signal crashes
**Expected result:** Signal should not crash

### Device info
**Android version:** 7.1
**Signal version:** 4.16.4

### Debug-Log

```
02-18 20:56:54.092 16317 16317 D AndroidRuntime: Shutting down VM
02-18 20:56:54.093 16317 16317 E AndroidRuntime: FATAL EXCEPTION: main
02-18 20:56:54.093 16317 16317 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16317
02-18 20:56:54.093 16317 16317 E AndroidRuntime: java.lang.ClassCastException: org.thoughtcrime.securesms.ConversationListItemInboxZero cannot be cast to org.thoughtcrime.securesms.ConversationListItem
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at org.thoughtcrime.securesms.ConversationListFragment$ArchiveListenerCallback.onSwiped(ConversationListFragment.java:487)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at android.support.v7.widget.helper.ItemTouchHelper$4.run(ItemTouchHelper.java:692)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-18 20:56:54.093 16317 16317 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-18 20:56:54.097  4112 14190 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-18 20:56:54.172  4112 13045 I OpenGLRenderer: Initialized EGL, version 1.4
02-18 20:56:54.172  4112 13045 D OpenGLRenderer: Swap behavior 1
02-18 20:56:54.612  4112  4510 W ActivityManager: Activity pause timeout for ActivityRecord{9172337 u0 org.thoughtcrime.securesms/.RoutingActivity t12632 f}
02-18 20:56:54.625  4112  4510 W SchedPolicy: add_tid_to_cgroup failed to write '16317' (No space left on device); fd=3
02-18 20:56:54.626  4112  4510 W ActivityManager: Failed setting process group of 16317 to 1
02-18 20:56:54.626  4112  4510 W System.err: java.lang.IllegalArgumentException: Invalid argument: 16317
02-18 20:56:54.626  4112  4510 W System.err: 	at android.os.Process.setProcessGroup(Native Method)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20704)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21307)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2472)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2137)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1834)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1339)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:1219)
02-18 20:56:54.626  4112  4510 W System.err: 	at com.android.server.am.ActivityStack$ActivityStackHandler.handleMessage(ActivityStack.java:384)
02-18 20:56:54.626  4112  4510 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 20:56:54.627  4112  4510 W System.err: 	at android.os.Looper.loop(Looper.java:154)
02-18 20:56:54.627  4112  4510 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-18 20:56:54.627  4112  4510 W System.err: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-18 20:56:54.639   251   251 W SurfaceFlinger: FB is protected: PERMISSION_DENIED
02-18 20:56:54.640  4112  4510 W WindowManager: Screenshot failure taking screenshot for (720x1280) to layer 21050
02-18 20:56:55.184  5957  5997 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

**Comment by junitas** [comment]
Was able to reproduce this on Android 7.0 and 6.0.
