### ISSUE TITLE
Signal Crashes while Startup on Beta-Channel (probably 4.16.7)

### ISSUE THREAD

**Issue by mawed** [signalapp/Signal-Android#7445]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm on the beta channel and got an update today for Signal (I think I got 4.16.7). Also I made an update of LineageOS to 14.1-20180220-nigthly-bacon.

I'm not sure if I opened Signal on the phone afte Signal-update and before OS-Update, but now Signal crashes on start-up every time. Even if I want to share something and Android tries to show the recent contacts, Signal crashes.

### Steps to reproduce
- Start Signal
- experience crash

### Device info
OnePlus One Bacon
**Android version:** 7.1.2
**Signal version:** I think 4.16.7 (Updated today on beta channel)

### debug log
```
02-28 00:16:16.107 W/InputMethodManagerService(5848): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2306c3b attribute=null, token = android.os.BinderProxy@372ac58
02-28 00:16:16.417 D/OpenGLRenderer(13293): endAllActiveAnimators on 0x79425e80 (ap$a) with handle 0xb28ffb80
02-28 00:16:17.888 D/AbstractMetricsFactoryImpl(9969): Setting non-anonymous customer ID and session ID to null, and anonymous tag to true as the metric entry was not recorded in non-anonymous queue.
02-28 00:16:18.452 I/ActivityManager(5848): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher (has extras)} from uid 1000 on display 0
02-28 00:16:18.597 I/art     (5848): Background partial concurrent mark sweep GC freed 30895(1750KB) AllocSpace objects, 7(164KB) LOS objects, 33% free, 23MB/34MB, paused 1.484ms total 117.321ms
02-28 00:16:19.070 W/OpenGLRenderer(7625): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
02-28 00:16:19.071 W/OpenGLRenderer(7625): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
02-28 00:16:21.901 I/ActivityManager(5848): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[225,1228][435,1466] (has extras)} from uid 10028 on display 0
02-28 00:16:21.919 W/BroadcastQueue(5848): Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=7625, uid=10028) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
02-28 00:16:21.919 W/BroadcastQueue(5848): Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10028)
02-28 00:16:21.961 I/ActivityManager(5848): Start proc 13847:org.thoughtcrime.securesms/u0a90 for activity org.thoughtcrime.securesms/.RoutingActivity
02-28 00:16:21.995 I/art     (13847): Starting a blocking GC AddRemoveAppImageSpace
02-28 00:16:22.016 I/MultiDex(13847): VM with version 2.1.0 has multidex support
02-28 00:16:22.016 I/MultiDex(13847): Installing application
02-28 00:16:22.016 I/MultiDex(13847): VM has multidex support, MultiDex support library is disabled.
02-28 00:16:22.034 W/PartProvider(13847): onCreate()
02-28 00:16:22.282 D/AndroidRuntime(13847): Shutting down VM
02-28 00:16:22.283 E/AndroidRuntime(13847): FATAL EXCEPTION: main
02-28 00:16:22.283 E/AndroidRuntime(13847): Process: org.thoughtcrime.securesms, PID: 13847
02-28 00:16:22.283 E/AndroidRuntime(13847): java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.os.Looper.loop(Looper.java:154)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at java.lang.reflect.Method.invoke(Native Method)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-28 00:16:22.283 E/AndroidRuntime(13847): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:121)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:60)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:75)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:153)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:87)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
02-28 00:16:22.283 E/AndroidRuntime(13847): 	... 8 more
02-28 00:16:22.287 W/ActivityManager(5848):   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-28 00:16:22.333 I/OpenGLRenderer(5848): Initialized EGL, version 1.4
02-28 00:16:22.333 D/OpenGLRenderer(5848): Swap behavior 1
02-28 00:16:22.792 W/ActivityManager(5848): Activity pause timeout for ActivityRecord{deda122 u0 org.thoughtcrime.securesms/.RoutingActivity t27992 f}
02-28 00:16:22.796 I/WindowManager(5848): Failed to capture screenshot of Token{79227b3 ActivityRecord{deda122 u0 org.thoughtcrime.securesms/.RoutingActivity t27992 f}} appWin=Window{3e82e88 u0 Starting org.thoughtcrime.securesms} drawState=4
02-28 00:16:23.241 W/WindowManager(5848): Failed looking up window
02-28 00:16:23.241 W/WindowManager(5848): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@a10da2b does not exist
02-28 00:16:23.241 W/WindowManager(5848): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9469)
02-28 00:16:23.241 W/WindowManager(5848): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9460)
02-28 00:16:23.241 W/WindowManager(5848): 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2401)
02-28 00:16:23.241 W/WindowManager(5848): 	at com.android.server.wm.Session.remove(Session.java:202)
02-28 00:16:23.241 W/WindowManager(5848): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
02-28 00:16:23.241 W/WindowManager(5848): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5923)
02-28 00:16:23.241 W/WindowManager(5848): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3629)
02-28 00:16:23.241 W/WindowManager(5848): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-28 00:16:23.241 W/WindowManager(5848): 	at android.os.Looper.loop(Looper.java:154)
02-28 00:16:23.241 W/WindowManager(5848): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-28 00:16:23.241 W/WindowManager(5848): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-28 00:16:23.346 W/OpenGLRenderer(7625): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
02-28 00:16:23.346 W/OpenGLRenderer(7625): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
02-28 00:16:23.440 W/ActivityManager(5848):   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-28 00:16:23.440 I/ActivityManager(5848): Killing 13847:org.thoughtcrime.securesms/u0a90 (adj 900): crash
02-28 00:16:23.441 D/ActivityManager(5848): cleanUpApplicationRecord -- 13847
02-28 00:16:23.461 W/InputMethodManagerService(5848): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2a55fcf attribute=null, token = android.os.BinderProxy@28526e6
02-28 00:16:23.654 W/AppOps  (5848): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
02-28 00:16:24.618 I/ActivityManager(5848): START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10033 on display 0
02-28 00:16:25.526 E/ActivityManager(5848): applyOptionsLocked: Unknown animationType=0
```

As the backup function is not working now and TItanium Backup isn't working anymore I would be really thankfull if my data could be saved instead of a new clean installation.
THanks for looking into this.

__________________________________________________________________________
EDIT:

As I observed I had to login into other apps after OS-Upgrade. Could it be, that the encrypting key to the new database was lost when updating?

**Comment by hennjo** [comment]
I'm expieriencing the same issue. Although in a slightly different scenario. I upgraded from LOS 14.1 to 15.2 the other night and tried to restore signal 4.16.8 from a titanium backup.
So I installed the Version from signal.org (4.15.5) and restored just the data of an older backup. This worked up until I updated signal from the PlayStore a few Minutes ago.

**Comment by moxie0** [comment]
Looks like LineageOS blew away your entire keystore. This is unrecoverable, I don't think there's anything you can do but a fresh install. Might want to report this to the lineageos people.

**Comment by mawed** [comment]
@moxie0 Thanks for the feedback, I just have two questions regarding this.

Is the key for the keystore generated randomly or could it be extraced from an old backup?

Wasn't the old database kept after migrating or was it already deleted with some of the prior versions?
Could this one get extraced?

**Comment by moxie0** [comment]
The keys never leave the hardware. If the hardware has lost them, they're gone. The old database is probably in your tibackup, but you're on your own trying to get anything out of there.
