### ISSUE TITLE
TimeoutException in SQLiteCompiledSql.finalize when importing large backup

### ISSUE THREAD

**Issue by karyon** [signalapp/Signal-Android#7477]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Steps to reproduce
- I imported a plaintext backup with 8k messages (2.5MB) on an old (aka slow) phone (Galaxy nexus)

**Actual result:**

After about 20 seconds, Signal crashed:
```
03-08 22:40:00.334 13608 13617 E AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
03-08 22:40:00.334 13608 13617 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 13608
03-08 22:40:00.334 13608 13617 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
03-08 22:40:00.334 13608 13617 E AndroidRuntime: java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.lang.Object.wait(Native Method)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.lang.Thread.parkFor$(Thread.java:1220)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at sun.misc.Unsafe.park(Unsafe.java:299)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:844)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1173)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:196)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:257)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:553)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.releaseSqlStatement(SQLiteCompiledSql.java:106)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.finalize(SQLiteCompiledSql.java:152)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
03-08 22:40:00.334 13608 13617 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-08 22:40:00.337   636  1257 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.ImportExportActivity
```

I tried smaller XMLs. 2k messages imported fine, but the second 2k crashed again. Then I started over with 1k batches, and was able to import all of the batches with only one crash, which i tried again and then it worked.

### Device info

**Device:** Samsung Galaxy Nexus
**Android version:** 6.0.1
**Signal version:** 4.16.9

### Link to debug log
https://hastebin.com/dociburake

**Comment by bungabunga** [comment]
The same just happened to me when importing a large backup.

[Debug Log](https://debuglogs.org/e290eaaa2be57672c74eca83eea1cfc1225de27b5fc9202731bd656bfc527175)

Device: Sony Xperia XZ
Android version: 8.0
Signal version: 4.17

**Comment by kmark** [comment]
I was not able to replicate this on a restore from a >100k message backup test on latest master. Admittedly it was on a far greater spec device.
