### ISSUE TITLE
Unable to restore new encrypted backup - net.sqlcipher.database.SQLiteException

### ISSUE THREAD

**Issue by cholin** [signalapp/Signal-Android#7488]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to restore an encrypted backup with Signal's new backup feature (since 4.17 - got it through Google Play Beta program), it crashes after entering the correct passphrase during importing messages with a SQLiteException (syntax error). It seems messages are not escaped and therefor any apostrophe in a message should end up in a crash.

This issue seems unrelated to #7446 (different exception).

### Steps to reproduce
- send a message with apostrophe to a contact
- create an encrypted backup
- delete signal app data
- start signal and try to import previously created backup

**Actual result:** Signals crashes during message import
**Expected result:** Signal should import the whole backup

### Screenshots

![screen](https://user-images.githubusercontent.com/140243/37228349-940cde7e-23e0-11e8-993f-bbd187ef4618.png)

### Device info

**Device:** Moto G5
**Android version:** 7.0.0
**Signal version:** 4.17.0

### Link to debug log
Not possible to access Signal Settings therefor only snippet taken through `adb logcat`

```03-09 21:11:42.468 10253 10319 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10253
03-09 21:11:42.468 10253 10319 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: near "s": syntax error: INSERT INTO sms VALUES (182,24,'+49157XXXXXXXXX',1,NULL,14XX69XX47XXX,14XX67XX5XXX,3XXXX,1,-1,10XX5XXX,1,0,NULL,'Hey, [redacted] gibt's [redacted]?',NULL,'GCM',-1,0,0,0,0)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:85)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:367)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:359)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-09 21:11:42.468 10253 10319 E AndroidRuntime: 	... 4 more
```

through adb logcat)

**Comment by junitas** [comment]
Fixed in https://github.com/signalapp/Signal-Android/commit/a2d04f48061719bd40332101e23483c0057683e3 ?

**Comment by cholin** [comment]
Looks good. Will reopen if it's not the case.
