### ISSUE TITLE
[4.17.2] Crash on restoring backup, choking on binary data

### ISSUE THREAD

**Issue by sesse** [signalapp/Signal-Android#7507]
It seems backup restore still isn't entirely where it should be. I took a backup on 4.17.2, restored on 4.17.2, and after ~4800 messages it died. adb logcat says

```
03-12 11:16:45.312 17848 17882 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
03-12 11:16:45.312 17848 17882 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 17848
03-12 11:16:45.312 17848 17882 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: unrecognized token: "'1ÿÿ": INSERT INTO sms VALUES (4SæèÚírá''H¦ëÃï¥ 2408',1,NULL,1461844441867,1461844441867,0,1,-1,23,NULL,0,NULL,'1ÿÿÀÀ062S~ÀðÄÀ~À¤3''ÀÀÀÀÀÀÀÀÀÀÀÀØÍÀbÀÀF@©Bq­Ò[éÚ''ÄÀÀ''ÀÀ',NULL,NULL,-1,0,0,0,0)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:85)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:360)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-12 11:16:45.312 17848 17882 E AndroidRuntime: 	... 4 more
03-12 11:16:45.398  3560  3588 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
03-12 11:16:45.412  3560  3596 I ActivityManager: Showing crash dialog for package org.thoughtcrime.securesms u0
```

I don't know where this binary data comes from.

**Comment by AlfonsoMuskedunder** [comment]
In a similar vein, I get
```
03-12 21:15:02.493 30696 30788 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
...
03-12 21:15:02.493 30696 30788 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: near "s": syntax error: INSERT INTO sms VALUES (51,10,'+49REDACTED',1,NULL,1421084231948,1421084231948,0,1,1,23,NULL,0,NULL,'Falls du\'s mal brauchst',NULL,NULL,-1,0,0,0,0)
```

**Comment by sesse** [comment]
@AlfonsoMuskedunder: That one is fixed in 4.17.2 (you need to take a new backup, though).

**Comment by moxie0** [comment]
Can you try exporting a new backup and importing again with this APK using the same data set? https://mega.nz/#!Rh8F2CQJ!6kjHiYJb-P5it_43PeHbwwFHnnCMAobXB8Z9z0GUI2w

**Comment by sesse** [comment]
@moxie0 Just to confirm: You want the new APK on both devices?

**Comment by moxie0** [comment]
@sesse This APK would need to be the thing that both creates and restores the backup. It's release signed, so you should be able to install it over your existing 4.17 install without any problems

**Comment by sesse** [comment]
It appears to have restored a complete backup without any issues.

**Comment by mmirg** [comment]
I'm not sure if this is the same issue that I'm seeing (I've obfuscated the contact number and message content) when trying to restore a backup taken on 4.17.2 on 4.17.2 and 4.17.3.  Should I re-create the backup with 4.17.3 (or the apk in this issue) and try again?

[signal import.log](https://github.com/signalapp/Signal-Android/files/1808424/signal.import.log)

**Comment by moxie0** [comment]
@mmirg Yeah you'll need to recreate on 4.17.3. 13.5 hours seems a bit long!
