### ISSUE TITLE
Signal crashes on startup - NullPointerException

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#7532]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes on startup. Now i don't have access to my messages anymore. :/

### Steps to reproduce
- start signal
- crash

**Actual result:** Signal crashes right away
**Expected result:** Signal should start like it is supposed to do

### Device info
**Android version:** 7.1.2
**Signal version:** 4.17.3

### Debug log
`````03-17 02:32:24.728  3675  5912 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[162,1035][296,1187] (has extras)} from uid 10032 on display 0
03-17 02:32:24.730  3675  5912 E QCOM PowerHAL: Failed to acquire lock.
03-17 02:32:24.774  3675  3707 I ActivityManager: Start proc 9134:org.thoughtcrime.securesms/u0a83 for activity org.thoughtcrime.securesms/.RoutingActivity
03-17 02:32:24.878  9134  9134 I MultiDex: VM with version 2.1.0 has multidex support
03-17 02:32:24.879  9134  9134 I MultiDex: Installing application
03-17 02:32:24.879  9134  9134 I MultiDex: VM has multidex support, MultiDex support library is disabled.
03-17 02:32:24.900  9134  9134 W PartProvider: onCreate()
03-17 02:32:25.000  9134  9134 D AndroidRuntime: Shutting down VM
03-17 02:32:25.001  9134  9134 E AndroidRuntime: FATAL EXCEPTION: main
03-17 02:32:25.001  9134  9134 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9134
03-17 02:32:25.001  9134  9134 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:144)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:63)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:78)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:154)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:88)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
03-17 02:32:25.001  9134  9134 E AndroidRuntime: 	... 8 more
03-17 02:32:25.004  3675  5906 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
03-17 02:32:25.014  9134  9134 I Process : Sending signal. PID: 9134 SIG: 9
03-17 02:32:25.056  3675  5922 I ActivityManager: Process org.thoughtcrime.securesms (pid 9134) has died
03-17 02:32:25.056  3675  5922 D ActivityManager: cleanUpApplicationRecord -- 9134
`````

**Comment by moxie0** [comment]
Please always include a full debug log. Your keystore has been reset, this usually means that you've restored using something like TiBackup, or are running a broken aftermarket ROM like LineageOS which destroys the keystore on upgrade. Please reopen if neither of those are true, thanks!

**Comment by rmueller83** [comment]
I get the same exception on startup, here is my logcat:

``03-17 09:33:36.204 710-1582/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[540,1245][804,1630] (has extras)} from uid 10028 on display 0
03-17 09:33:36.213 710-741/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1671, uid=10028) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
03-17 09:33:36.213 710-741/? W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10028)
03-17 09:33:36.268 710-923/? I/ActivityManager: Start proc 6369:org.thoughtcrime.securesms/u0a82 for activity org.thoughtcrime.securesms/.RoutingActivity
03-17 09:33:36.306 6369-6369/? I/art: Starting a blocking GC AddRemoveAppImageSpace
03-17 09:33:36.327 6369-6369/? I/MultiDex: VM with version 2.1.0 has multidex support
03-17 09:33:36.327 6369-6369/? I/MultiDex: Installing application
03-17 09:33:36.327 6369-6369/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
03-17 09:33:36.337 6369-6369/? W/PartProvider: onCreate()
03-17 09:33:36.380 6369-6369/? D/AndroidRuntime: Shutting down VM
03-17 09:33:36.381 6369-6369/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.thoughtcrime.securesms, PID: 6369
                                                 java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
                                                     at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)
                                                     at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)
                                                     at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)
                                                     at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)
                                                     at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:144)
                                                     at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:63)
                                                     at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:78)
                                                     at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)
                                                     at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:154)
                                                     at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:88)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
03-17 09:33:36.383 710-1668/? W/ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
03-17 09:33:36.437 710-3787/? I/OpenGLRenderer: Initialized EGL, version 1.4
03-17 09:33:36.437 710-3787/? D/OpenGLRenderer: Swap behavior 1
03-17 09:33:36.887 710-741/? W/ActivityManager: Activity pause timeout for ActivityRecord{c7f450d u0 org.thoughtcrime.securesms/.RoutingActivity t22599 f}
03-17 09:33:36.889 710-741/? I/WindowManager: Failed to capture screenshot of Token{e488cc2 ActivityRecord{c7f450d u0 org.thoughtcrime.securesms/.RoutingActivity t22599 f}} appWin=Window{cbd314b u0 Starting org.thoughtcrime.securesms} drawState=4
03-17 09:33:37.339 710-771/? W/WindowManager: Failed looking up window
                                              java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@88ef21a does not exist
                                                  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9469)
                                                  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9460)
                                                  at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2401)
                                                  at com.android.server.wm.Session.remove(Session.java:202)
                                                  at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
                                                  at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5923)
                                                  at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3629)
                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                  at android.os.Looper.loop(Looper.java:154)
                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-17 09:33:37.433 1671-1765/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
03-17 09:33:37.433 1671-1765/? W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
``

This happens since updating my LineageOS from 20180309 to 20180316: https://www.cmxlog.com/14.1/klte/
I do not have any backup tools.

**Comment by rmueller83** [comment]
I just found a bug ticket on the LineageOS bug tracker (with no response yet), so the problem seems to hit a wider audience: https://jira.lineageos.org/browse/REGRESSION-1782

**Comment by eMPee584** [comment]
It would be much nicer if it wouldn't crash and instead explain what happened (keystore reset = forget about recovering your previous messages)... isn't it?
And that state by itself is really not cool (how is one supposed to move the message store from one phone to another?) ... ; telegram shines with its multi-device-support... Now if it just had proper encryption.... :rofl:
