### ISSUE TITLE
Crash restoring backup - SQLiteException on groupchat [Signal 4.17.3]

### ISSUE THREAD

**Issue by motatuc** [signalapp/Signal-Android#7533]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Tried to restore a backup with Signal after my keystore was cleared during an ROM-update. Signal crashes right away when restore is starting.

### Steps to reproduce
- Start fresh instance of Signal
- It automatically finds the backup and asks to restore it - do so
- Signal crashes when starting to restore the backup

**Actual result:** Signal crashes during the first second of the restore
**Expected result:** Signal should restore the backup

### Device info
**Android version:** 7.1.2
**Signal version:** 4.17.3

### I have modified the log cause Signal leaks phone numbers with this crash!
`````03-17 08:55:12.734 15569 15649 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
03-17 08:55:12.734 15569 15649 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 15569
03-17 08:55:12.734 15569 15649 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: near "Groupchatname": syntax error: INSERT INTO sms VALUES (15,4,'+Phonenumber1',1,NULL,Phonenumber2,Phonenumber2,0,1,-1,20,NULL,0,NULL,'+Phonenumber1 updated the group.
03-17 08:55:12.734 15569 15649 E AndroidRuntime: +Phonenumber1, Name1, +Phonenumber3, +Phonenumber4 joined the group. Group name is now 'Groupchatname'.',NULL,NULL,-1,0,0,0,0)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.processStatement(FullBackupImporter.java:97)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:68)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:372)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:364)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-17 08:55:12.734 15569 15649 E AndroidRuntime: 	... 4 more
03-17 08:55:12.741 10432 10695 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
03-17 08:55:12.762 15569 15574 I art     : Do partial code cache collection, code=41KB, data=62KB
03-17 08:55:12.762 15569 15574 I art     : After code cache collection, code=41KB, data=62KB
03-17 08:55:12.762 15569 15574 I art     : Increasing code cache capacity to 256KB
03-17 08:55:12.876 10432 12728 I OpenGLRenderer: Initialized EGL, version 1.4
03-17 08:55:12.876 10432 12728 D OpenGLRenderer: Swap behavior 1
03-17 08:55:12.945 10432 10443 I art     : Background partial concurrent mark sweep GC freed 49152(2MB) AllocSpace objects, 12(276KB) LOS objects, 33% free, 11MB/17MB, paused 2.284ms total 130.287ms
`````

**Comment by moxie0** [comment]
Looks like this is a backup created with 4.17.2? Those have this problem, which is fixed for backups created with 4.17.3+.  Please reopen if this was created with 4.17.3+ thanks

**Comment by motatuc** [comment]
@moxie0 

You are right this was made with 4.17.2. Is there any way I can get these messages back?

**Comment by moxie0** [comment]
@motatuc You'd have to make changes to the source to try to work around these exceptions. Easiest thing would be to swallow them and continue, which would mean you'd only lose the problematic messages.

**Comment by motatuc** [comment]
@moxie0 I see. I am afraid I am not capable of doing that - I am no coder. I guess its pretty sure to say that you are really busy and that you have quite more important things to solve. But if it wouldn't be too much effort and if you would find some time I really would appreciate your help with that case.

**Comment by motatuc** [comment]
@moxie0 I found a solution. No need for any more help in this case. Thanks for your great work by the way!
