### ISSUE TITLE
[4.17.5] Out Of Memory Error when restoring backup

### ISSUE THREAD

**Issue by BobSilent** [signalapp/Signal-Android#7572]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Trying to restore a backup on an Samsung Galaxy S3 (Android 4.3) - 1GB Ram
Backup File is ~90MB
~13000 Messages

### Steps to reproduce
- start restore after installation

**Actual result:** Signal App crashes
**Expected result:** restore data successfuly done

### Device info
**Device:** Samsung Galaxy S3 GT-I9300
**Android version:** 4.3
**Signal version:** 4.17.5

### Link to debug log
https://gist.github.com/BobSilent/8efdac9436fcdf48532f0ba034fb5c10

**Comment by lambdaupb** [comment]
Possibly related to #7560 - that issue is also assumed to be a wrong frame length field.
While its possible that phones just have sub-par nand, it is also possible that it might be a bug.

**Comment by floesche** [comment]
In case it helps, here is another logcat output for the OutOfMemory problem in readFrame https://gist.github.com/floesche/317de446ad9c60d214b08c615cfb0557

In this case the backup file is ~530MB, the device is a Moto G5S (3GB RAM), and the import crashes around message 20,000.

**Comment by moxie0** [comment]
Yes this is the same as #7560, the erroneous 4-bytes read here just happen to be a super large number instead of a negative number. @BobSilent and @floesche can you comment there to confirm whether the database you're backing up/restoring there is very old?

**Comment by miqid** [comment]
I ran into a similar-looking out of memory error while trying to restore a backup on a new phone running Signal 4.17.5 (LineageOS 14.1, Xperia Z5 Compact).

Relevant `adb logcat` trace:

```
04-03 18:20:41.884  5425  5464 W art     : Throwing OutOfMemoryError "Failed to allocate a 1327528141 byte allocation with 3159456 free bytes and 507MB until OOM"
04-03 18:20:41.892  5425  5464 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
04-03 18:20:41.892  5425  5464 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5425
04-03 18:20:41.892  5425  5464 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
04-03 18:20:41.892  5425  5464 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1327528141 byte allocation with 3159456 free bytes and 507MB until OOM
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:238)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:189)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:372)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:364)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-03 18:20:41.892  5425  5464 E AndroidRuntime:        ... 4 more
```

Like @floesche, my messages go back to circa 2012 or so and I've done some of those plain-text backups and imports successfully before, which was also a while back. However, unlike everyone else here so far, my backup is only 6MB (obviously not much of a TXT person), which makes it seems strange I'm running into an out of memory problem.

Since this issue is closed, am I to assume we're on our own?

I'd really like to preserve my messaging history. Even if going forward I can't have them in Signal, is there a means of decrypting the backup on a computer?

**Comment by floesche** [comment]
I believe the problem is fixed in #7560 and commit b9f99f99410562516ae17dbe6e58a0b94127a904. It seemed less of a problem with how the data was stored.

**Comment by BobSilent** [comment]
I am also a user of Signal (TextSecure) since ages.
what does it mean exactly. Do I need to create a new Backup or do I just need a new Version for Restore.

**Comment by floesche** [comment]
@BobSilent If b9f99f99410562516ae17dbe6e58a0b94127a904 fixes the problem, it would require you to make another backup.

**Comment by miqid** [comment]
I just updated to `4.18.3` today on both my devices. Retried exporting a backup from my old device and was able to successfully import it onto my other one.

Thank you very much for the fix! 🙌

**Comment by jhc-at-home** [comment]
On Singnal 4.23.4, I just tried to migrate my 4.1GB backup and receive an "OutOfMemoryError".

### Debug Log
```
08-01 14:46:28.542 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.542 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.575 18824 18994 I art     : Alloc sticky concurrent mark sweep GC freed 1021(2MB) AllocSpace objects, 0(0B) LOS objects, 36% free, 8MB/13MB, paused 1.703ms total 19.203ms
08-01 14:46:28.576 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.620 18824 18994 I art     : Alloc partial concurrent mark sweep GC freed 1149(494KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 7MB/12MB, paused 499us total 43.033ms
08-01 14:46:28.620 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.655 18824 18994 I art     : Alloc concurrent mark sweep GC freed 104(15KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 7MB/12MB, paused 401us total 33.851ms
08-01 14:46:28.655 18824 18994 I art     : Forcing collection of SoftReferences for 982MB allocation
08-01 14:46:28.655 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.726 18824 18994 I art     : Alloc concurrent mark sweep GC freed 27(728B) AllocSpace objects, 0(0B) LOS objects, 40% free, 7MB/12MB, paused 1.739ms total 71.040ms
08-01 14:46:28.727 18824 18994 W art     : Throwing OutOfMemoryError "Failed to allocate a 1030038681 byte allocation with 5397626 free bytes and 504MB until OOM"
08-01 14:46:28.731 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.731 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.739 18824 18994 I art     : Alloc sticky concurrent mark sweep GC freed 6(416B) AllocSpace objects, 0(0B) LOS objects, 40% free, 7MB/12MB, paused 632us total 7.945ms
08-01 14:46:28.740 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.793 18824 18994 I art     : Alloc partial concurrent mark sweep GC freed 19(512B) AllocSpace objects, 0(0B) LOS objects, 40% free, 7MB/12MB, paused 905us total 52.231ms
08-01 14:46:28.793 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.830 18824 18994 I art     : Alloc concurrent mark sweep GC freed 11(304B) AllocSpace objects, 0(0B) LOS objects, 40% free, 7MB/12MB, paused 503us total 36.423ms
08-01 14:46:28.830 18824 18994 I art     : Forcing collection of SoftReferences for 982MB allocation
08-01 14:46:28.830 18824 18994 I art     : Starting a blocking GC Alloc
08-01 14:46:28.863 18824 18994 I art     : Alloc concurrent mark sweep GC freed 11(272B) AllocSpace objects, 0(0B) LOS objects, 39% free, 7MB/12MB, paused 398us total 31.937ms
08-01 14:46:28.863 18824 18994 I art     : Starting a blocking GC HomogeneousSpaceCompact
08-01 14:46:28.988 18824 18994 I art     : HomogeneousSpaceCompact marksweep + semispace GC freed 4(128B) AllocSpace objects, 0(0B) LOS objects, 39% free, 7MB/12MB, paused 123.289ms total 123.289ms
08-01 14:46:28.988 18824 18994 W art     : Throwing OutOfMemoryError "Failed to allocate a 1030038681 byte allocation with 5401572 free bytes and 504MB until OOM"
08-01 14:46:29.124 18824 18994 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
08-01 14:46:29.124 18824 18994 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18824
08-01 14:46:29.124 18824 18994 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
08-01 14:46:29.124 18824 18994 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1030038681 byte allocation with 5401572 free bytes and 504MB until OOM
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:303)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:245)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:376)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:368)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-01 14:46:29.124 18824 18994 E AndroidRuntime:        ... 4 more
08-01 14:46:29.127  2189  7573 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
08-01 14:46:29.136 18824 18994 I Process : Sending signal. PID: 18824 SIG: 9
08-01 14:46:29.179  2189  4054 I WindowState: WIN DEATH: Window{1619da5 u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RegistrationActivity}
08-01 14:46:29.179  2189  4110 D GraphicsStats: Buffer count: 5
08-01 14:46:29.211  2189  4086 I ActivityManager: Process org.thoughtcrime.securesms (pid 18824) has died
08-01 14:46:29.211  2189  4086 D ActivityManager: cleanUpApplicationRecord -- 18824
08-01 14:46:29.212  2189  4086 W ActivityManager: Scheduling restart of crashed service org.thoughtcrime.securesms/.service.KeyCachingService in 1000ms
08-01 14:46:29.565  2189  2203 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 18824 uid 10121
08-01 14:46:29.610  2189  2189 I ActivityManager: Start proc 20474:com.nextcloud.client/u0a91 for service com.nextcloud.client/com.evernote.android.job.v21.PlatformJobService
08-01 14:46:29.684 20474 20480 I art     : Debugger is no longer active
08-01 14:46:29.725 20474 20474 I MultiDex: VM with version 2.1.0 has multidex support
08-01 14:46:29.725 20474 20474 I MultiDex: Installing application
08-01 14:46:29.725 20474 20474 I MultiDex: VM has multidex support, MultiDex support library is disabled.
```

### Device info
**Device:** Fairphone FP2
**Android version:** 6.0.1
**Signal version (Restoring backup):** 4.23.4 (from: https://signal.org/android/apk/)
**Signal version (Creating backup):** 4.23.4

**Comment by willnix** [comment]
I ran in to, what seems to be the same issue:
```
11-05 16:20:17.718  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.718  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.743  6472  6515 D OpenGLRenderer: endAllActiveAnimators on 0xc9377b80 (RippleDrawable) with handle 0xc98dcf50
11-05 16:20:17.744  6472  6539 I crime.securesm: Alloc concurrent copying GC freed 88860(3MB) AllocSpace objects, 12(2MB) LOS objects, 49% free, 4MB/9MB, paused 42us total 25.949ms
11-05 16:20:17.744  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.744   613   613 D SurfaceFlinger: duplicate layer name: changing Surface(name=bea23a6 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RegistrationActivity)/@0xc7136df - animation-leash to Surface(name=bea23a6 org.thoughtcrime.securesms/org.thoughtcrime.securesms.RegistrationActivity)/@0xc7136df - animation-leash#1
11-05 16:20:17.762  6472  6539 I crime.securesm: Alloc concurrent copying GC freed 11982(525KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4MB/8MB, paused 26us total 18.438ms
11-05 16:20:17.762  6472  6539 I crime.securesm: Forcing collection of SoftReferences for 1GB allocation
11-05 16:20:17.762  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.785  6472  6539 I crime.securesm: Alloc concurrent copying GC freed 11553(590KB) AllocSpace objects, 1(68KB) LOS objects, 50% free, 3MB/7MB, paused 36us total 22.310ms
11-05 16:20:17.785  6472  6539 W crime.securesm: Throwing OutOfMemoryError "Failed to allocate a 1347093264 byte allocation with 3893472 free bytes and 508MB until OOM, max allowed footprint 7786944, growth limit 536870912"
11-05 16:20:17.785  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.785  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.801  6472  6539 I crime.securesm: Alloc concurrent copying GC freed 31(62KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/7MB, paused 75us total 15.726ms
11-05 16:20:17.801  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.817  6472  6539 I crime.securesm: Alloc concurrent copying GC freed 29(32KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/7MB, paused 33us total 15.968ms
11-05 16:20:17.817  6472  6539 I crime.securesm: Forcing collection of SoftReferences for 1GB allocation
11-05 16:20:17.817  6472  6539 I crime.securesm: Starting a blocking GC Alloc
11-05 16:20:17.839  6472  6539 I crime.securesm: Alloc concurrent copying GC freed 625(54KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/7MB, paused 31us total 21.620ms
11-05 16:20:17.839  6472  6539 W crime.securesm: Throwing OutOfMemoryError "Failed to allocate a 1347093264 byte allocation with 3854735 free bytes and 508MB until OOM, max allowed footprint 7742239, growth limit 536870912"
--------- beginning of crash
11-05 16:20:17.840  6472  6539 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
11-05 16:20:17.840  6472  6539 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6472
11-05 16:20:17.840  6472  6539 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1347093264 byte allocation with 3854735 free bytes and 508MB until OOM, max allowed footprint 7742239, growth limit 536870912
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.<init>(FullBackupImporter.java:217)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.<init>(FullBackupImporter.java:197)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:394)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:386)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-05 16:20:17.840  6472  6539 E AndroidRuntime: 	... 4 more
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:764)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1347093264 byte allocation with 3854735 free bytes and 508MB until OOM, max allowed footprint 7742239, growth limit 536870912
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.<init>(FullBackupImporter.java:217)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.<init>(FullBackupImporter.java:197)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:394)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.RegistrationActivity$2.doInBackground(RegistrationActivity.java:386)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-05 16:20:17.840  6472  6539 E UncaughtExceptionLogger: 	... 4 more
11-05 16:20:17.844  1165  4841 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RegistrationActivity
11-05 16:20:17.879  6472  6539 I Process : Sending signal. PID: 6472 SIG: 9
 ```

### Device info
**Device:** Pixel 2 XL
**Android version:** 9.0
**Signal version (Restoring backup):** 4.29.7(PlayStore)
**Signal version (Creating backup):** Unknown (whatever was in the PlayStore on 25.06.2018)

**Comment by maltaisn** [comment]
This is still occurring for me with the latest version.
