### ISSUE TITLE
Immediate crash after launch after update from 4.15.5 to 4.16.9, 4.17.5 or 4.18.3

### ISSUE THREAD

**Issue by yepyepyep4711** [signalapp/Signal-Android#7695]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Immediate crash after launch after update from 4.15.5 to 4.16.9, 4.17.5 or 4.18.3

### Steps to reproduce
- update Signal from Yalp
- start Signal

**Actual result:** immediate crash and close of Signal
**Expected result:** happy Signal start

### Device info

**Device:** OnePlus 5
**Android version:** 7.1.1
**Signal version:** 4.15.5

### Debug log
I have tried to log from the update to the first start. Not sure I have it all, I may have ran out of buffer.
Also, this is kind of a last ditch effort for me. I see other similar issues here, but can't tell if they are the same or not and what I can do. And my signal tells me it's going to stop working in six days. The log if from the last try, from 4.15.5 to 4.18.3
```
[ 04-17 22:51:36.969  1400: 3234 E/ActivityTrigger ]
activityStartTrigger: not whiteListedcom.google.android.packageinstaller/com.and
roid.packageinstaller.PackageInstallerActivity/25

[ 04-17 22:51:36.972  1400: 3234 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.an
droid.packageinstaller.PackageInstallerActivity/25

[ 04-17 22:51:36.980  1400: 9602 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.an
droid.packageinstaller.PackageInstallerActivity/25

[ 04-17 22:51:37.972   680: 2995 E/ANDR-PERF-OPTSHANDLER ]
perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with
1
 return value 2

[ 04-17 22:51:37.975   680: 2995 E/ANDR-PERF-RESOURCEQS ]
Failed to reset optimization [3, 0]

[ 04-17 22:51:43.006 10024:10033 E/System   ]
Uncaught exception thrown by finalizer

[ 04-17 22:51:43.007 10024:10033 E/System   ]
java.lang.IllegalStateException
        at com.syntomo.email.provider.ContentCache$CounterMap.subtract(ContentCa
che.java:135)
        at com.syntomo.email.provider.ContentCache$CachedCursor.close(ContentCac
he.java:311)
        at android.database.CursorWrapper.close(CursorWrapper.java:50)
        at android.content.ContentResolver$CursorWrapperInner.close(ContentResol
ver.java:2763)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentRe
solver.java:2774)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
        at java.lang.Thread.run(Thread.java:761)


[ 04-17 22:51:43.008 10024:10033 E/System   ]
Uncaught exception thrown by finalizer

[ 04-17 22:51:43.009 10024:10033 E/System   ]
java.lang.IllegalStateException
        at com.syntomo.email.provider.ContentCache$CounterMap.subtract(ContentCa
che.java:135)
        at com.syntomo.email.provider.ContentCache$CachedCursor.close(ContentCac
he.java:311)
        at android.database.CursorWrapper.close(CursorWrapper.java:50)
        at android.content.ContentResolver$CursorWrapperInner.close(ContentResol
ver.java:2763)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentRe
solver.java:2774)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
        at java.lang.Thread.run(Thread.java:761)


[ 04-17 22:51:43.011 10024:10033 E/System   ]
Uncaught exception thrown by finalizer

[ 04-17 22:51:43.011 10024:10033 E/System   ]
java.lang.IllegalStateException
        at com.syntomo.email.provider.ContentCache$CounterMap.subtract(ContentCa
che.java:135)
        at com.syntomo.email.provider.ContentCache$CachedCursor.close(ContentCac
he.java:311)
        at android.database.CursorWrapper.close(CursorWrapper.java:50)
        at android.content.ContentResolver$CursorWrapperInner.close(ContentResol
ver.java:2763)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentRe
solver.java:2774)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
        at java.lang.Thread.run(Thread.java:761)


[ 04-17 22:51:43.020 10024:10033 E/System   ]
Uncaught exception thrown by finalizer

[ 04-17 22:51:43.020 10024:10033 E/System   ]
java.lang.IllegalStateException
        at com.syntomo.email.provider.ContentCache$CounterMap.subtract(ContentCa
che.java:135)
        at com.syntomo.email.provider.ContentCache$CachedCursor.close(ContentCac
he.java:311)
        at android.database.CursorWrapper.close(CursorWrapper.java:50)
        at android.content.ContentResolver$CursorWrapperInner.close(ContentResol
ver.java:2763)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentRe
solver.java:2774)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
        at java.lang.Thread.run(Thread.java:761)


[ 04-17 22:51:43.022 10024:10033 E/System   ]
Uncaught exception thrown by finalizer

[ 04-17 22:51:43.022 10024:10033 E/System   ]
java.lang.IllegalStateException
        at com.syntomo.email.provider.ContentCache$CounterMap.subtract(ContentCa
che.java:135)
        at com.syntomo.email.provider.ContentCache$CachedCursor.close(ContentCac
he.java:311)
        at android.database.CursorWrapper.close(CursorWrapper.java:50)
        at android.content.ContentResolver$CursorWrapperInner.close(ContentResol
ver.java:2763)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentRe
solver.java:2774)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
        at java.lang.Thread.run(Thread.java:761)


[ 04-17 22:51:43.024 10024:10033 E/System   ]
Uncaught exception thrown by finalizer

[ 04-17 22:51:43.024 10024:10033 E/System   ]
java.lang.IllegalStateException
        at com.syntomo.email.provider.ContentCache$CounterMap.subtract(ContentCa
che.java:135)
        at com.syntomo.email.provider.ContentCache$CachedCursor.close(ContentCac
he.java:311)
        at android.database.CursorWrapper.close(CursorWrapper.java:50)
        at android.content.ContentResolver$CursorWrapperInner.close(ContentResol
ver.java:2763)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentRe
solver.java:2774)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:230)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:217)
        at java.lang.Thread.run(Thread.java:761)


[ 04-17 22:51:44.745  1400: 9602 E/ActivityTrigger ]
activityStartTrigger: not whiteListedcom.google.android.packageinstaller/com.and
roid.packageinstaller.InstallAppProgress/25

[ 04-17 22:51:44.752  1400: 9602 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.an
droid.packageinstaller.InstallAppProgress/25

[ 04-17 22:51:44.771  1400: 2765 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedcom.google.android.packageinstaller/com.an
droid.packageinstaller.InstallAppProgress/25

[ 04-17 22:51:44.991   680: 2995 E/ANDR-PERF-OPTSHANDLER ]
perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with
1
 return value 2

[ 04-17 22:51:44.993   680: 2995 E/ANDR-PERF-RESOURCEQS ]
Failed to reset optimization [3, 0]

[ 04-17 22:51:48.064  1400: 2085 E/ConnectivityService ]
RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN
 id=385, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]

[ 04-17 22:51:48.138   847:  847 E/         ]
Couldn't opendir /data/app/vmdl57669724.tmp: No such file or directory


[ 04-17 22:51:48.291 22331:22331 E/Embryo   ]
org.thoughtcrime.securesms preload layout failed. decor

[ 04-17 22:51:48.342  3122: 3122 E/RegisteredServicesCache ]
Next Tag=services

[ 04-17 22:51:48.342  3122: 3122 E/RegisteredServicesCache ]
1invalidateCache:WriteServiceStateToFile

[ 04-17 22:51:48.342  3122: 3122 E/RegisteredServicesCache ]
 Writing service state Data Always

[ 04-17 22:51:48.426  3031:21645 E/NetworkScheduler ]
Unrecognised action provided: android.intent.action.PACKAGE_REMOVED

[ 04-17 22:51:48.601 22392:22409 E/SEEMP_JSERVICE ]
onHandleIntent:  Unable to get Seemp instance!

[ 04-17 22:51:48.812 22740:22740 E/Finsky   ]
[1] com.google.android.finsky.wear.au.a(3): onConnectionFailed: ConnectionResult
{statusCode=API_UNAVAILABLE, resolution=null, message=null}

[ 04-17 22:51:49.106  9653:22438 E/HollywoodAppstore.NotificationService ]
Unhandled notification type: Intent { act=android.intent.action.PACKAGE_ADDED da
t=package:org.thoughtcrime.securesms flg=0x4000010 cmp=com.amazon.venezia/.notif
ication.NotificationService (has extras) }

[ 04-17 22:51:49.232  3031: 6162 E/NetworkScheduler ]
Unrecognised action provided: android.intent.action.PACKAGE_REPLACED

[ 04-17 22:51:53.578  1400: 3234 E/ActivityTrigger ]
activityStartTrigger: not whiteListedorg.thoughtcrime.securesms/org.thoughtcrime
.securesms.RoutingActivity/354

[ 04-17 22:51:53.581  1400: 3234 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedorg.thoughtcrime.securesms/org.thoughtcrim
e.securesms.RoutingActivity/354

[ 04-17 22:51:53.588  1400: 1415 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedorg.thoughtcrime.securesms/org.thoughtcrim
e.securesms.RoutingActivity/354

[ 04-17 22:51:53.715 22459:22459 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: org.thoughtcrime.securesms, PID: 22459
java.lang.RuntimeException: Unable to create application org.thoughtcrime.secure
sms.ApplicationContext: java.lang.NullPointerException: Attempt to invoke virtua
l method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecret
Key()' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:
5621)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6334)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit
.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'jav
ax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a n
ull object reference
        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(Key
StoreHelper.java:106)
        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelpe
r.java:65)
        at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncrypted
DatabaseSecret(DatabaseSecretProvider.java:58)
        at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateD
atabaseSecret(DatabaseSecretProvider.java:29)
        at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFa
ctory.java:145)
        at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(Datab
aseFactory.java:63)
        at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(Da
tabaseFactory.java:78)
        at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(Expi
ringMessageManager.java:29)
        at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessa
geManager(ApplicationContext.java:154)
        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationCon
text.java:88)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.j
ava:1036)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:
5618)
        ... 8 more


[ 04-17 22:51:53.744  1400: 2395 E/ActivityTrigger ]
activityResumeTrigger: not whiteListedcom.github.yeriomin.yalpstore/com.github.y
eriomin.yalpstore.DetailsActivity/37

[ 04-17 22:51:53.943 22485:22499 E/libEGL   ]
validate_display:99 error 3008 (EGL_BAD_DISPLAY)
```

**Comment by johanw666** [comment]
Looks like a broken keystore implementation: `Attempt to invoke virtua
l method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecret
Key()' on a null object reference`.

**Comment by yepyepyep4711** [comment]
nope, the os that came with the OnePlus. Rooted, in my case

**Comment by moxie0** [comment]
Hey sorry but it looks like your OS has wiped your keystore. There's no real way for us to recover at that point, the key material necessary for opening the application database has been destroyed by the OS. There are definite lineageos issues around this, and it's possible that the rooting procedure might have interfered here as well. Please keep us posted if you learn anything, but unfortunately there's no action we can take.

**Comment by yepyepyep4711** [comment]
Wait, what?
@moxie0, please elaborate.
First, my OS is *NOT* LineageOS.
Second, what do you mean, my keystore is wiped? My Signal works! Well, for another three days, or until I try the update, whichever comes first. So it's the update that breaks it, not the OS.
Or what am I missing?

**Comment by pgerber** [comment]
>  … So it's the update that breaks it, not the OS.

@yepyepyep4711, Signal has [migrated to SQLCipher + Keystore](https://github.com/signalapp/Signal-Android/commit/f36b296e2ed211893835372513da57bb135c52c1) in 4.16. So, likely your keystore has been broken all along but it didn't affect Signal since it hadn't migrated to the keystore yet.

**Comment by tuxayo** [comment]
> Second, what do you mean, my keystore is wiped? My Signal works! Well, for another three days,

So you still have your messages + working conversations?  (without the recipient warned that you key changed) with the 4.15.5 ?

**Comment by moxie0** [comment]
@yepyepyep4711 It's hard to diagnose what's happening with your install since you're on a rooted device and anything is possible. For instance, it sounds like you're going forwards and backwards in time. That should not be possible in a stock environment, and is not supported by Android at all. You have a 4.15.5 install, which you've upgraded to 4.18.x, and then gone back in time to 4.15.5. If you did that with TiBackup or something, then that will completely break Signal:

1. The upgrade creates keys in the Android keystore.
2. The act of forcing a downgrade (not supported by Android) will wipe the keystore, but the Signal state hasn't changed, so it still thinks it has keys there.
3. You upgrade again, and the keys Signal is expecting are gone.

**Comment by yepyepyep4711** [comment]
thanks @moxie0. It's starting to clear up.
I don't know of any other way to backup all my conversations, including media attachments, so yes I use TiBackup.
If I didn't, I'd have lost everything after the first crash (I did lose two weeks worth of messages).
So in theory if I delete Signal and install the new version, instead of updating, it should work?

**Comment by tuxayo** [comment]
> So in theory if I delete Signal and install the new version, instead of updating, it should work?

No don't! That's how your keys will be lost.
You can use apps like oandbackup or TiBackup to restore data to rollback a migration. But don't uninstall the apo or try to restore in another device. The non externally backupable data will be lost.

**Comment by bungabunga** [comment]
@yepyepyep4711

1. uninstall Signal
2. install v4.15.5. 
3. recover your messages via TiBk
4. upgrade to v4.16.x and see if everything is groovy
5. if everything ok, upgrade to the latest version of Signal and say farewell to TiBk on Signal forever
6. profit :innocent:

(maybe you can even skip nr.4, i don't know, i did this when 4.16 was the latest update)

**Comment by yepyepyep4711** [comment]
@bungabunga nope. That didn't work. Never mind. I give up on keeping those old conversations. I'm going to keep a copy of 4.15.5 together with the backup if I want to open it again sometime.
Now, I'm on 4.18.3. I see we have a backup function. Does it store media messages as well?

**Comment by tuxayo** [comment]
@bungabunga 
> 1. uninstall Signal

Aren't you guarantied to lose the key material (thus never being able to again access the message) that is stored in the hardware keystore of **newer phones**?
Well actually I tried with a test install on a Galaxy S5 on Lineage OS 14.1 and the result match what's written upwards.

>  Now, I'm on 4.18.3. I see we have a backup function. Does it store media messages as well?

Yes, considering the size of the backup, the media messages are definitely there.

**Comment by yepyepyep4711** [comment]
> @tuxayo i was talking about trying to restore OLD Signal TiBk backup on an OLD version of Signal and THEN upgrading everything to the latest version of Signal (hoping that he knows how to do it without fucking up the keys).
@tuxayo well, no, I don't. It's exactly what I've been doing without success, so if there is a how-to somewhere I'll really appreciate if you could post a link to it

**Comment by yepyepyep4711** [comment]
@bungabunga there's no login in Signal that I know of. You mean unregister the phone?

**Comment by bungabunga** [comment]
yep. same thing.

**Comment by yepyepyep4711** [comment]
@bungabunga just so I get this right, you're telling me I should: 
- go back to 4.15.5
- restore my backup of the data that still works with 4.15.5
- whatever happens after the install, reach a point where the conversations are there, but the phone is not registered in signal (how that fixes the keys on the phone is beyond me, as you can unregister from the web page without the app knowing about it, care to explain?)
- when I have reached that state, make a new backup while unregistered
- uninstall signal
- reinstall 4.15.5. If the install routine forces me to register, unregister again
- restore my new backup from unregistered state before
- register phone
- update to 4.16.9
- update to 4.18.3 (why not directly to this one?)

**Comment by bungabunga** [comment]
if the old backup that you have was made while unregistered to Signal service, that should be it. no need for more backups. just install it (while unregistered) to 4.15.5 and upgrade. if not i think you're doomed.

also, please, if u'd like to talk more let's move to forum. this is not a place to chat.
