### ISSUE TITLE
Android client in crashing loop

### ISSUE THREAD

**Issue by improvethings** [signalapp/Signal-Android#7731]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Android client in a crash loop 

### Steps to reproduce
- Click "Signal" icon on phone desktop
- Get popup modal, "Signal has stopped" and then click "Open app again"
- 20 GO TO 10

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Nexus 5 (hammerhead)
**Android version:** 7.1.2 (LineageOS 14.1)
**Signal version:** 4.18.3

### Link to debug log

I can't get into the app to do this. This is from adb logcat: 

`````
04-24 15:57:00.176   790   900 D AudioService: Stream muted, skip playback
04-24 15:57:00.178   790   803 I ActivityManager: Killing 10286:org.thoughtcrime.securesms/u0a82 (adj 0): crash
04-24 15:57:00.182   790   803 D ActivityManager: cleanUpApplicationRecord -- 10286
04-24 15:57:00.188   790   803 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.ConversationListActivity (has extras)} from uid 10029 on display 0
04-24 15:57:00.198   790  1801 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@ba8525b attribute=null, token = android.os.BinderProxy@b9af12d
04-24 15:57:00.203   790   802 E ActivityManager: applyOptionsLocked: Unknown animationType=0
04-24 15:57:00.248   790   802 I ActivityManager: Start proc 10853:org.thoughtcrime.securesms/u0a82 for activity org.thoughtcrime.securesms/.ConversationListActivity
04-24 15:57:00.264   790   790 D ZenLog  : intercepted: 0|android|17039403|null|1000,alarmsOnly
04-24 15:57:00.265   790   790 V NotificationService: pkg=android canInterrupt=false intercept=true
04-24 15:57:00.284 10853 10853 I art     : Starting a blocking GC AddRemoveAppImageSpace
04-24 15:57:00.311 10853 10853 I MultiDex: VM with version 2.1.0 has multidex support
04-24 15:57:00.311 10853 10853 I MultiDex: Installing application
04-24 15:57:00.311 10853 10853 I MultiDex: VM has multidex support, MultiDex support library is disabled.
04-24 15:57:00.320 10853 10853 W PartProvider: onCreate()
04-24 15:57:00.378 10853 10853 D AndroidRuntime: Shutting down VM
04-24 15:57:00.379 10853 10853 E AndroidRuntime: FATAL EXCEPTION: main
04-24 15:57:00.379 10853 10853 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10853
04-24 15:57:00.379 10853 10853 E AndroidRuntime: java.lang.AssertionError: java.security.UnrecoverableKeyException: Failed to obtain information about key
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:108)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:145)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:63)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:78)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:154)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:88)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: Caused by: java.security.UnrecoverableKeyException: Failed to obtain information about key
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreSecretKeyFromKeystore(AndroidKeyStoreProvider.java:282)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:98)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:474)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at java.security.KeyStore.getEntry(KeyStore.java:1323)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)
04-24 15:57:00.379 10853 10853 E AndroidRuntime: 	... 19 more
04-24 15:57:00.379 10853 10853 E AndroidRuntime: Caused by: android.security.KeyStoreException: Invalid key blob
`````

**Comment by moxie0** [comment]
Sadly, this looks like yet another LineageOS keystore bug. I'd recommend filing this with them, I don't think there's any action we can take.
