### ISSUE TITLE
Backup don't work

### ISSUE THREAD

**Issue by Kauler** [signalapp/Signal-Android#7802]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Recently, I tried to create a backup - it didn't work. Two friends tried the same (same Android version, same Signal version) and they hadn't this issue, strange. Maybe my DB crashed a long time ago, I don't know. 

### Steps to reproduce

- I  typed "Chat backups" and then "Create backup".
- After that the TextView under the "Create Backup" displayed "Last backup: Never".
- I tried that several times - didn't wor.

### Device info
**Device:** BQ Aquaris X
**Android version:** 8.1.0
**Signal version:** 4.19.3

### Link to debug log
I already searched the log for some information and I think I found the mistake:
JobConsumer: java.io.IOException: Renaming temporary backup file failed!
https://debuglogs.org/15b904733be34573555eda2ab10410d7ef909c470467cb1a01227fe7c0786d8b

**Comment by Hellmark** [comment]
Sounds like the issue from 7691, which they've supposedly fixed and should be in 4.20, but no clue when that will be out.

**Comment by Kauler** [comment]
I don't think that this is the same issue, you're right sounds similar but in the other issue the problem is caused by renaming backup files including a SD card. In my issue, I wasn't using a SD card.

**Comment by SingerGuy** [comment]
I emailed a debug log to support@signal.org yesterday, but had time at work to do additional debugging. I believe I have the relevant portion of the logs below. What I did was run a debug but not submit (to flush the cache). I immediately turned off backups (not that there were any) and then turned backups on and performed a backup, trying to get as clean of a start as possible. This section of the logs (13:12:26.875 to 13:13:03.239) represent the failed backup.

I have snipped the logs to only show process numbers 18765, 18748, and 18773. The debuglogs.org URL has the full logs from my phone. https://debuglogs.org/4e07a9ba1fa36947c42c64739e4549f756fc8d38c31a26f3c8896282fbfdea4c 

Device : samsung SM-G930V (heroqltevzw) 
Android : 7.0 (G930VVRS4BRC3, NRD90M.G930VVRS4BRC3) 
Memory : 50M (14.85% free, 512M max) 
Memclass: 256 OS Host : SWDG2918 
App : Signal 4.19.3

05-16 13:12:26.875 18748 18748 W ChatsPreferenceFragment: Queing backup... 
05-16 13:12:26.883 18748 18765 W LocalBackupJob: **Executing backup job...** 
05-16 13:12:53.526 18748 18773 W MessageRetrievalService: Application level read timeout... 
05-16 13:12:53.532 18748 18773 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0, gcm disabled: false 
05-16 13:12:53.534 18748 18773 W MessageRetrievalService: Reading message... 
05-16 13:12:58.638 18748 18765 W JobConsumer: 
05-16 13:12:58.638 18748 18765 W JobConsumer: java.io.IOException: **Renaming temporary backup file failed!**
05-16 13:12:58.638 18748 18765 W JobConsumer: at org.thoughtcrime.securesms.jobs.LocalBackupJob.onRun(LocalBackupJob.java:78) 
05-16 13:12:58.638 18748 18765 W JobConsumer: at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76) 
05-16 13:12:58.638 18748 18765 W JobConsumer: at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46) 
05-16 13:13:03.142 18748 18748 D ViewRootImpl@8dc20e7[ApplicationPreferencesActivity]: ViewPostImeInputStage processKey 0 
05-16 13:13:03.239 18748 18748 D ViewRootImpl@8dc20e7[ApplicationPreferencesActivity]: ViewPostImeInputStage processKey 1

By the way, in neither internal nor external storage do I see a path for Android/data/org.whispersystems. I see one for org.thoughtcrime.securesms though. Don't know if that matters. I seem to remember in my old phone that I had org.whispersystems and had never noticed the thoughtcrime domain name until this debug issue.
