### ISSUE TITLE
Crash when searching on Android 4

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#7830]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description
When I type something in the search bar, Signal crashes after a few seconds. This ony happens on my Android 4.4.4 device, on 6.0.1 it works as expected.

### Steps to reproduce
- Start Signal
- Click on the magnifying glass and type something
- crash

**Actual result:** Signal crashes
**Expected result:** Signal should show search results

### Device info
**Device:** Sony Z1 Compact
**Android version:** 4.4.4
**Signal version:** 4.20.4

### Link to debug log
This is the crash as I captured it with catlog. I can send the entire log if it is helpfull:
```
05-23 18:54:08.544 E/AndroidRuntime(31284): FATAL EXCEPTION: main
05-23 18:54:08.544 E/AndroidRuntime(31284): Process: org.thoughtcrime.securesms, PID: 31284
05-23 18:54:08.544 E/AndroidRuntime(31284): android.view.InflateException: Binary XML file line #2: Error inflating class TextView
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.LayoutInflater.inflate(Native Method)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at org.thoughtcrime.securesms.search.SearchListAdapter.onCreateHeaderViewHolder(SearchListAdapter.java:100)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at org.thoughtcrime.securesms.search.SearchListAdapter.onCreateHeaderViewHolder(SearchListAdapter.java:23)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at org.thoughtcrime.securesms.util.StickyHeaderDecoration.getHeader(StickyHeaderDecoration.java:83)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at org.thoughtcrime.securesms.util.StickyHeaderDecoration.getItemOffsets(StickyHeaderDecoration.java:53)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:4696)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8778)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1584)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.View.layout(View.java:14948)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5622)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
05-23 18:54:08.544 E/AndroidRuntime(31284): 	at android.vi

```

**Comment by greyson-signal** [comment]
I haven't been able to repro on my [Galaxy S3 Mini, Android 4.2.2. API 17](https://www.gsmarena.com/samsung_i8200_galaxy_s_iii_mini_ve-6190.php) on Signal 4.20.4. However, given that this crash occurs during the inflation of the header view, I'm assuming our change in 92a64f to switch to using a pre-existing header layout should solve this problem in the upcoming 4.20.5 release.

In the meantime, I'm going to try to get an emulator running 4.4 up to see if this an an API-specific issue I can reproduce.

Thank you!

**Comment by greyson-signal** [comment]
Yep, was just able to repro the crash on a 4.4 emulator on 4.20.4, but 92a64f59a4e126dd5d0cb6b5ec591d0176132121 fixes it.
