### ISSUE TITLE
ConversationAdapterTest.testGetItemIdEquals fails

### ISSUE THREAD

**Issue by patrikhuber** [signalapp/Signal-Android#7860]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Building from the latest master branch (as of today), the following test fails with a NullPointerException: `ConversationAdapterTest. testGetItemIdEquals`

```
java.lang.NullPointerException
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:203)
	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:148)
	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:64)
	at org.thoughtcrime.securesms.database.DatabaseFactory.getAttachmentDatabase(DatabaseFactory.java:87)
	at org.thoughtcrime.securesms.ConversationAdapter.getItemId(ConversationAdapter.java:272)
	at org.thoughtcrime.securesms.ConversationAdapterTest.testGetItemIdEquals(ConversationAdapterTest.java:29)
[... many more lines ...]
```

There are several issues open already about this, the latest one being for example #7742, and according to these closed tickets, the issue is supposed to be solved. Of course it can be "circumvented" by skipping the tests (e.g. doing `gradle assemblerelease`) but that's besides the point of tests, is it not?

### Steps to reproduce
- Build according to the Wiki instructions (https://github.com/signalapp/Signal-Android/wiki/How-to-build-Signal-from-the-sources), the test fails as one of the steps of `gradle build`.
Building on Manjaro with latest Android SDK (from Android Studio) for Linux.

Expected results: All tests should pass successfully.

**Comment by moxie0** [comment]
It's an open wiki; everything on there is "community contributed" and not official.  You could update the wiki to replace "build" with "assembleDebug" or "assembleRelease" if you'd like. Thanks!
