### ISSUE TITLE
backup stopped working

### ISSUE THREAD

**Issue by MarcSN311** [signalapp/Signal-Android#7912]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
1) Signal did backups as expected
2) I moved the backups to the external SD card, because my internal memory was full
3) Signal seems to create backups but no files are created (running about 2h, last message count I saw was 87k messages)

I already disabled and reenabled backups. I tried manual backups, which also fail.

### Steps to reproduce
- Enable backups

**Actual result:** Backup runs but no backup is created
**Expected result:** Backup file should be created.

### Screenshots
![screenshot_20180619-203005](https://user-images.githubusercontent.com/12860202/41617161-0ba2f3dc-7400-11e8-8bd6-41abf95da91c.png)
![screenshot_20180619-203050](https://user-images.githubusercontent.com/12860202/41617162-0bcfd87a-7400-11e8-9b37-f4e45aaf949f.png)

### Device info
**Device:**  Sony E5823 (suzuran)
**Android version:** 7.1.2 (a28b9b6c88, lineage_suzuran-userdebug 7.1.2 NJH47F a28b9b6c88)
**Signal version:** Signal 4.19.3, Signal 4.20.9

### debug log
```
Signal Log
Device  : Sony E5823 (suzuran)
Android : 7.1.2 (a28b9b6c88, lineage_suzuran-userdebug 7.1.2 NJH47F a28b9b6c88)
Memory  : 47M (19.45% free, 512M max)
Memclass: 192
OS Host : iktinos.acc.umu.se
App     : Signal 4.20.9
--------- beginning of main
06-19 19:40:51.959 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:52.242 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:52.242 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:52.271 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:52.271 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:53.021 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:53.021 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:53.175 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:53.175 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:53.284 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:53.284 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:53.915 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:53.915 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:54.751 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:54.751 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:55.355 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:55.355 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:55.533 15593  2953 W WebSocketConnection: Sending keep alive...
06-19 19:40:55.783 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:55.783 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:56.296 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:56.296 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:56.654 15593 15593 W PassphraseRequiredActionBarActivity: onPause()
06-19 19:40:56.663 15593 15593 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
06-19 19:40:56.663 15593 15593 W KeyCachingService: Decrementing activity count...
06-19 19:40:56.666 15593 15593 W MessageRetrievalService: Active Count: 0
06-19 19:40:56.671 15593 15593 W PassphraseRequiredActionBarActivity: onCreate(null)
06-19 19:40:56.677 15593 15593 W ExperienceUpgradeActivity: getExperienceUpgrade(354)
06-19 19:40:56.677 15593 15593 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
06-19 19:40:56.681 15593 15593 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
06-19 19:40:56.718 15593 15593 W PassphraseRequiredActionBarActivity: onResume()
06-19 19:40:56.805 15593 15593 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
06-19 19:40:56.805 15593 15593 W KeyCachingService: Incrementing activity count...
06-19 19:40:56.806 15593 15593 W MessageRetrievalService: Active Count: 1
06-19 19:40:56.846 15593 15691 D OpenGLRenderer: endAllActiveAnimators on 0xd2f1fa00 (MenuPopupWindow$MenuDropDownListView) with handle 0xd51fc390
06-19 19:40:58.093 15593 15620 D EventBus: No subscribers registered for event class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent
06-19 19:40:58.093 15593 15620 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
06-19 19:40:58.361 15593 15593 E EventBus: Could not dispatch event: class org.thoughtcrime.securesms.backup.FullBackupBase$BackupEvent to subscribing class class org.thoughtcrime.securesms.preferences.ChatsPreferenceFragment
06-19 19:40:58.361 15593 15593 E EventBus: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
06-19 19:40:58.361 15593 15593 E EventBus: 	at org.thoughtcrime.securesms.preferences.widgets.ProgressPreference.setProgress(ProgressPreference.java:53)
06-19 19:40:58.361 15593 15593 E EventBus: 	at org.thoughtcrime.securesms.preferences.ChatsPreferenceFragment.onEvent(ChatsPreferenceFragment.java:101)
06-19 19:40:58.361 15593 15593 E EventBus: 	at java.lang.reflect.Method.invoke(Native Method)
06-19 19:40:58.361 15593 15593 E EventBus: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
06-19 19:40:58.361 15593 15593 E EventBus: 	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
06-19 19:40:58.361 15593 15593 E EventBus: 	at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
06-19 19:40:58.361 15593 15593 E EventBus: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-19 19:40:58.361 15593 15593 E EventBus: 	at android.os.Looper.loop(Looper.java:154)
06-19 19:40:58.361 15593 15593 E EventBus: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-19 19:40:58.361 15593 15593 E EventBus: 	at java.lang.reflect.Method.invoke(Native Method)
06-19 19:40:58.361 15593 15593 E EventBus: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-19 19:40:58.361 15593 15593 E EventBus: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-19 19:40:58.361 15593 15593 D EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent
```

**Comment by haffenloher** [comment]
> I tried manual backups, which also fail.

How do you determine that they failed? According to your first screen shot, the last successful backup happened today at 5.43 pm. Can you check if it's stored on your SD card under `Android/data/org.thoughtcrime.securesms/files/Signal/Backups`?

**Comment by MarcSN311** [comment]
so the backup location changed? 
First backups were located under:
[Internal SD]/Signal/Backups
now they are located in:
[External SD]/Android/data/org.thoughtcrime.securesms/files/Signal/Backups
In that case everything is working since my upgrade to Signal 4.20.9
