### ISSUE TITLE
Signal Crashes when opening conversation or 2 seconds into submitting debug log

### ISSUE THREAD

**Issue by CarlSmithson** [signalapp/Signal-Android#7924]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Crashes when opening conversation or 2 seconds into submitting debug log.

### Steps to reproduce
- Install and open signal
- Open conversation > leads into instant crash
- Go to Settings>Advanced>Submit debug log>Submit
- Pop-up says 'Submitting logos' for 2 seconds and crashes

**Actual result:** App crashes
**Expected result:** Conversations opened and debug logs submitted

### Screenshots
Screenshot of the log where the first error line appears.

![signal debug log](https://user-images.githubusercontent.com/40474382/41742753-fb3fa184-756c-11e8-8167-2cb4fda8a2fd.png)

### Device info
**Device:** Google Pixel 2
**Android version:** 8.0.0
**Signal version:** 4.19.3

### Link to debug log
Cannot upload debug log.

**Comment by CarlSmithson** [comment]
This is similar to the bug report found here: https://github.com/signalapp/Signal-Android/issues/6852

The solution was to 'Enable Chromium'. However I am unsure as to how to proceed and my research turned up nothing.

Thank you in advance for your help!

**Comment by CarlSmithson** [comment]
Interestingly, I can send a single text to a contact if no conversation history exists, and the text gets received. However, the app instantly crashes after sending and the contact cannot be texted again without erasing the conversation history (which can be done without crashing).

**Comment by moxie0** [comment]
Hey @CarlSmithson, unfortunately we can't really do anything without a debug log. If you're unable to submit a debug log, we'd need output from "adb logcat."

**Comment by moxie0** [comment]
`````
06-22 00:21:40.419 22698 22698 E AndroidRuntime: java.lang.IllegalArgumentException: Unsupported ABI: null
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at dalvik.system.VMRuntime.getInstructionSet(VMRuntime.java:384)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at dalvik.system.VMRuntime.is64BitAbi(VMRuntime.java:397)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:584)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:710)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:417)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:214)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.webkit.WebView.getFactory(WebView.java:2486)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.webkit.WebView.findAddress(WebView.java:1757)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.text.util.Linkify.gatherMapLinks(Linkify.java:550)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.text.util.Linkify.addLinks(Linkify.java:253)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationItem.linkifyMessageBody(ConversationItem.java:472)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationItem.setBodyText(ConversationItem.java:401)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationItem.bind(ConversationItem.java:212)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationAdapter.onBindItemViewHolder(ConversationAdapter.java:194)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.ConversationAdapter.onBindItemViewHolder(ConversationAdapter.java:72)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.database.FastCursorRecyclerViewAdapter.onBindItemViewHolder(FastCursorRecyclerViewAdapter.java:72)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.onBindViewHolder(CursorRecyclerViewAdapter.java:149)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at org.thoughtcrime.securesms.components.camera.QuickAttachmentDrawer.onLayout(QuickAttachmentDrawer.java:189)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1642)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1631)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.View.layout(View.java:19594)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6054)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2492)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2208)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6748)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:658)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6600)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-22 00:21:40.419 22698 22698 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
`````

This crash is in the Android code. Are you running a custom ROM, rooted device, xposed, or anything like that?

**Comment by CarlSmithson** [comment]
No to all of the above. I also have 'Android web view' and 'Chrome' installed and enabled.

If this is an Android code issue is there a more suitable place for me to ask about this?

Thank you again for your help.

**Comment by greyson-signal** [comment]
@CarlSmithson If you want to file a bug against the platform, you can check out: https://source.android.com/setup/contribute/report-bugs

**Comment by haffenloher** [comment]
Related WebView bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=559720

@CarlSmithson according to someone on the Chromium team, "uninstalling WebView updates in Settings and then re-updating WebView in the Play Store" is a known workaround.
