### ISSUE TITLE
"Signal has stopped" after rooting phone

### ISSUE THREAD

**Issue by LeoSum8** [signalapp/Signal-Android#7959]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Upon launching Signal, I get an error message "Signal has stopped". Signal won't start.
This happened after I installed TWRP 3.2.1 recovery and rooted SuperSU 2.82 on my Samsung Galaxy S5 (SM G900F), running latest Android 6 based stock rom.

### Steps to reproduce
- Have working version (latest play store release) of signal installed
- flash TWRP via Odin
- flash SuperSU to root via recovery
- reboot phone
- tap signal icon

**Actual result:** Signal does not start, I only receive the system message "Signal has stopped".
**Expected result:** Signal should start as before the rooting process.

### What I have tried so far:
According to the log I posted below, I take that Signal seems to be unable to get write access to the folder  `/data/user/0/org.thoughtcrime.securesms/`.
I double checked that Signal has all permissions that can be granted via system settings.
Also I modified the permissions of the folder `/data/user/0/org.thoughtcrime.securesms/` to 777, but this doesn't help.

### Device info

**Device:** Samsung Galaxy S5 (SM G900F)
**Android version:** 6.0.1
**Signal version:** 4.21.6

### Debug log

```
07-01 21:46:54.943   978  1103 I ActivityManager: Start proc 16577:org.thoughtcrime.securesms/u0a217 for broadcast-2 org.thoughtcrime.securesms/.gcm.GcmBroadcastReceiver

07-01 21:46:54.953 16577 16577 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.thoughtcrime.securesms 

07-01 21:46:55.013 16577 16577 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null

07-01 21:46:55.023 16577 16577 W ContextImpl: Unable to create files subdir /data/user/0/org.thoughtcrime.securesms/cache

07-01 21:46:55.023 16577 16577 W ContextImpl: Unable to create files subdir /data/user/0/org.thoughtcrime.securesms/code_cache

07-01 21:46:55.023  2162  2162 E audit   : type=1400 msg=audit(1530474415.023:354): avc:  denied  { write } for  pid=16577 comm="crime.securesms" name="org.thoughtcrime.securesms" dev="mmcblk0p26" ino=310409 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0

07-01 21:46:55.023  2162  2162 E audit   : type=1302 msg=audit(1530474415.023:354): item=0 name="/data/user/0/org.thoughtcrime.securesms/cache" inode=310409 dev=b3:1a mode=040751 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:46:55.023  2162  2162 E audit   : type=1327 msg=audit(1530474415.023:354): proctitle="org.thoughtcrime.securesms"

07-01 21:46:55.023  2162  2162 E audit   : type=1400 msg=audit(1530474415.023:355): avc:  denied  { write } for  pid=16577 comm="crime.securesms" name="org.thoughtcrime.securesms" dev="mmcblk0p26" ino=310409 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0

07-01 21:46:55.023  2162  2162 E audit   : type=1302 msg=audit(1530474415.023:355): item=0 name="/data/user/0/org.thoughtcrime.securesms/code_cache" inode=310409 dev=b3:1a mode=040751 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:46:55.033  2162  2162 E audit   : type=1327 msg=audit(1530474415.023:355): proctitle="org.thoughtcrime.securesms"

07-01 21:46:55.063 16577 16577 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null

07-01 21:46:55.133  2162  2162 E audit   : type=1302 msg=audit(1530474415.133:356): item=0 name="/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs" inode=268640 dev=b3:1a mode=0100660 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:46:55.133 16577 16610 W SQLiteLog: (28) failed to open "/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs" with flag (131138) and mode_t (0) due to error (13)

07-01 21:46:55.133  2162  2162 E audit   : type=1327 msg=audit(1530474415.133:356): proctitle="org.thoughtcrime.securesms"

07-01 21:46:55.143 16577 16610 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs'.

07-01 21:46:55.143 16577 16610 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getJobs(PersistentStorage.java:80)

07-01 21:46:55.143 16577 16610 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getAllUnencrypted(PersistentStorage.java:71)

07-01 21:46:55.143 16577 16610 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.JobManager$LoadTask.run(JobManager.java:153)

07-01 21:46:55.143 16577 16610 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getJobs(PersistentStorage.java:80)

07-01 21:46:55.143 16577 16610 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getAllUnencrypted(PersistentStorage.java:71)

07-01 21:46:55.143 16577 16610 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.JobManager$LoadTask.run(JobManager.java:153)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16577

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:108)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:150)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:64)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:79)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:154)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:88)

07-01 21:46:55.273 16577 16577 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)

07-01 21:46:55.283   978  2077 W ActivityManager: Process org.thoughtcrime.securesms has crashed too many times: killing!

07-01 21:46:55.283   978  2077 I ActivityManager: Killing 16577:org.thoughtcrime.securesms/u0a217 (adj 0): crash

07-01 21:46:55.293  1996  1996 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=org.thoughtcrime.securesms (has extras) }

07-01 21:46:55.633   978  1103 W BroadcastQueue: Unable to launch app org.thoughtcrime.securesms/10217 for broadcast Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 pkg=org.thoughtcrime.securesms (has extras) }: process is bad

07-01 21:46:55.633  1996  1996 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=org.thoughtcrime.securesms (has extras) }

07-01 21:47:15.223   978  1103 W BroadcastQueue: Unable to launch app org.thoughtcrime.securesms/10217 for broadcast Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 pkg=org.thoughtcrime.securesms (has extras) }: process is bad

07-01 21:47:15.223  1996  1996 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=org.thoughtcrime.securesms (has extras) }

07-01 21:47:15.703   978  1103 W BroadcastQueue: Unable to launch app org.thoughtcrime.securesms/10217 for broadcast Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 pkg=org.thoughtcrime.securesms (has extras) }: process is bad

07-01 21:47:15.703  1996  1996 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=org.thoughtcrime.securesms (has extras) }

07-01 21:47:35.173 16740 16740 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in android rsrc of package null

07-01 21:47:35.413   978  2521 I ActivityManager: Start proc 16759:org.thoughtcrime.securesms/u0a217 for service org.thoughtcrime.securesms/.service.DirectShareService

07-01 21:47:35.423 16759 16759 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.thoughtcrime.securesms 

07-01 21:47:35.473 16759 16759 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null

07-01 21:47:35.483 16759 16759 W ContextImpl: Unable to create files subdir /data/user/0/org.thoughtcrime.securesms/cache

07-01 21:47:35.483 16759 16759 W ContextImpl: Unable to create files subdir /data/user/0/org.thoughtcrime.securesms/code_cache

07-01 21:47:35.483  2162  2162 E audit   : type=1400 msg=audit(1530474455.483:357): avc:  denied  { write } for  pid=16759 comm="crime.securesms" name="org.thoughtcrime.securesms" dev="mmcblk0p26" ino=310409 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0

07-01 21:47:35.493  2162  2162 E audit   : type=1302 msg=audit(1530474455.483:357): item=0 name="/data/user/0/org.thoughtcrime.securesms/cache" inode=310409 dev=b3:1a mode=040751 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:47:35.493  2162  2162 E audit   : type=1327 msg=audit(1530474455.483:357): proctitle="org.thoughtcrime.securesms"

07-01 21:47:35.493  2162  2162 E audit   : type=1400 msg=audit(1530474455.483:358): avc:  denied  { write } for  pid=16759 comm="crime.securesms" name="org.thoughtcrime.securesms" dev="mmcblk0p26" ino=310409 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0

07-01 21:47:35.493  2162  2162 E audit   : type=1302 msg=audit(1530474455.483:358): item=0 name="/data/user/0/org.thoughtcrime.securesms/code_cache" inode=310409 dev=b3:1a mode=040751 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:47:35.493  2162  2162 E audit   : type=1327 msg=audit(1530474455.483:358): proctitle="org.thoughtcrime.securesms"

07-01 21:47:35.513 16759 16759 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null

07-01 21:47:35.573 16759 16783 W SQLiteLog: (28) failed to open "/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs" with flag (131138) and mode_t (0) due to error (13)

07-01 21:47:35.573  2162  2162 E audit   : type=1302 msg=audit(1530474455.573:359): item=0 name="/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs" inode=268640 dev=b3:1a mode=0100660 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:47:35.573  2162  2162 E audit   : type=1327 msg=audit(1530474455.573:359): proctitle="org.thoughtcrime.securesms"

07-01 21:47:35.583 16759 16783 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs'.

07-01 21:47:35.583 16759 16783 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getJobs(PersistentStorage.java:80)

07-01 21:47:35.583 16759 16783 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getAllUnencrypted(PersistentStorage.java:71)

07-01 21:47:35.583 16759 16783 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.JobManager$LoadTask.run(JobManager.java:153)

07-01 21:47:35.583 16759 16783 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getJobs(PersistentStorage.java:80)

07-01 21:47:35.583 16759 16783 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getAllUnencrypted(PersistentStorage.java:71)

07-01 21:47:35.583 16759 16783 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.JobManager$LoadTask.run(JobManager.java:153)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16759

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:108)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:150)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:64)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:79)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:154)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:88)

07-01 21:47:35.723 16759 16759 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)

07-01 21:47:35.813 16771 16771 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in com.samsung.android.coreapps rsrc of package null

07-01 21:47:36.013 16740 16813 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in android rsrc of package null

07-01 21:47:36.133 16740 16816 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in android rsrc of package null

07-01 21:47:36.133 16740 16815 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in android rsrc of package null

07-01 21:47:37.243   978  1692 I ActivityManager: Process org.thoughtcrime.securesms (pid 16759)(adj 0) has died(44,464)

07-01 21:47:37.243   978  1692 I ActivityManager: isWidgetUsingPkg : org.thoughtcrime.securesms no widget is using.

07-01 21:47:37.243   978  1692 W ActivityManager: Scheduling restart of crashed service org.thoughtcrime.securesms/.service.DirectShareService in 1000ms

07-01 21:47:38.273   978  1103 I ActivityManager: Start proc 16834:org.thoughtcrime.securesms/u0a217 for service org.thoughtcrime.securesms/.service.DirectShareService

07-01 21:47:38.273 16834 16834 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.thoughtcrime.securesms 

07-01 21:47:38.393 16834 16834 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null

07-01 21:47:38.443  2162  2162 E audit   : type=1400 msg=audit(1530474458.443:360): avc:  denied  { write } for  pid=16834 comm="crime.securesms" name="org.thoughtcrime.securesms" dev="mmcblk0p26" ino=310409 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0

07-01 21:47:38.443 16834 16834 W ContextImpl: Unable to create files subdir /data/user/0/org.thoughtcrime.securesms/cache

07-01 21:47:38.443  2162  2162 E audit   : type=1302 msg=audit(1530474458.443:360): item=0 name="/data/user/0/org.thoughtcrime.securesms/cache" inode=310409 dev=b3:1a mode=040751 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:47:38.443  2162  2162 E audit   : type=1327 msg=audit(1530474458.443:360): proctitle="org.thoughtcrime.securesms"

07-01 21:47:38.443 16834 16834 W ContextImpl: Unable to create files subdir /data/user/0/org.thoughtcrime.securesms/code_cache

07-01 21:47:38.443  2162  2162 E audit   : type=1400 msg=audit(1530474458.443:361): avc:  denied  { write } for  pid=16834 comm="crime.securesms" name="org.thoughtcrime.securesms" dev="mmcblk0p26" ino=310409 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0

07-01 21:47:38.443  2162  2162 E audit   : type=1302 msg=audit(1530474458.443:361): item=0 name="/data/user/0/org.thoughtcrime.securesms/code_cache" inode=310409 dev=b3:1a mode=040751 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:47:38.443  2162  2162 E audit   : type=1327 msg=audit(1530474458.443:361): proctitle="org.thoughtcrime.securesms"

07-01 21:47:38.493 16834 16834 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null

07-01 21:47:38.583  2162  2162 E audit   : type=1302 msg=audit(1530474458.573:362): item=0 name="/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs" inode=268640 dev=b3:1a mode=0100660 ouid=10217 ogid=10217 rdev=00:00 obj=u:object_r:system_data_file:s0

07-01 21:47:38.583  2162  2162 E audit   : type=1327 msg=audit(1530474458.573:362): proctitle="org.thoughtcrime.securesms"

07-01 21:47:38.583 16834 16857 W SQLiteLog: (28) failed to open "/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs" with flag (131138) and mode_t (0) due to error (13)

07-01 21:47:38.603 16834 16857 E SQLiteDatabase: Failed to open database '/data/user/0/org.thoughtcrime.securesms/databases/_jobqueue-TextSecureJobs'.

07-01 21:47:38.603 16834 16857 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getJobs(PersistentStorage.java:80)

07-01 21:47:38.603 16834 16857 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getAllUnencrypted(PersistentStorage.java:71)

07-01 21:47:38.603 16834 16857 E SQLiteDatabase: 	at org.thoughtcrime.securesms.jobmanager.JobManager$LoadTask.run(JobManager.java:153)

07-01 21:47:38.603 16834 16857 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getJobs(PersistentStorage.java:80)

07-01 21:47:38.603 16834 16857 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.persistence.PersistentStorage.getAllUnencrypted(PersistentStorage.java:71)

07-01 21:47:38.603 16834 16857 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.jobmanager.JobManager$LoadTask.run(JobManager.java:153)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16834

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:108)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getEncryptedDatabaseSecret(DatabaseSecretProvider.java:58)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.DatabaseSecretProvider.getOrCreateDatabaseSecret(DatabaseSecretProvider.java:29)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.<init>(DatabaseFactory.java:150)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getInstance(DatabaseFactory.java:64)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory.getSmsDatabase(DatabaseFactory.java:79)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager.<init>(ExpiringMessageManager.java:29)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeExpiringMessageManager(ApplicationContext.java:154)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:88)

07-01 21:47:38.753 16834 16834 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)

07-01 21:47:40.693   978  2075 I ActivityManager: Process org.thoughtcrime.securesms (pid 16834)(adj 0) has died(62,456)

07-01 21:47:44.743   978  1103 I ActivityManager: Start proc 16949:org.thoughtcrime.securesms/u0a217 for broadcast-2 org.thoughtcrime.securesms/.gcm.GcmBroadcastReceiver

07-01 21:47:44.753 16949 16949 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.thoughtcrime.securesms 

07-01 21:47:44.813 16949 16949 W ResourcesManager: getTopLevelResources: /data/app/org.thoughtcrime.securesms-2/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null
```

**Comment by greyson-signal** [comment]
Yeah, unfortunately judging by your logs it seems your file permissions have been screwed up. Unfortunately we can't support these use cases. You can always try backing up your `Android/data/org.thoughtcrime.securesms` folder, reinstalling your ROM, and then trying to go back to it. But honestly you're in uncharted territory. Sorry!
