### ISSUE TITLE
App crashes on number registration

### ISSUE THREAD

**Issue by thisIsMeHello** [signalapp/Signal-Android#8034]
- [x ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When attempting to verify my number, the app crashes when I press the REGISTER button. (I'm aware that I've probably done something moronic and apologise in advance... )

### Steps to reproduce
- Install latest version of Lineage OS for microG on Nexus 6p
- install Signal from web page
- attempt to register phone number

**Actual result:** 
App crashes, get msg "Signal has stopped"
**Expected result:**
App doesn't crash and everything is awesome

### Device info
**Device:** Nexus 6p
**Android version:** 8.1.0
**Lineage for microG build** 15.1-20180723-microG-angler with Google device registration disabled 
**Signal version:** 4.23.4

### Link to debug log
FATAL EXCEPTION: AsyncTask #4
Process: org.thoughtcrime.securesms, PID: 10596
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) }: app is in background uid UidRecord{8bd03bb u0a21 TRNB bg:+5m40s297ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
	at android.app.ContextImpl.startService(ContextImpl.java:1477)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at com.google.android.gms.gcm.GoogleCloudMessaging.zzai(Unknown Source:81)
	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:61)
	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:479)
	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:468)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

**Comment by greyson-signal** [comment]
Do you have Google Play Services installed?

**Comment by thisIsMeHello** [comment]
I think the ROM has an open source replacement for that (which is the main reason for this particular ROM's existence):

"Service Core (GmsCore) is a library app, providing the functionality required to run apps that use Google Play Services or Google Maps Android API (v2)."

**Comment by haffenloher** [comment]
> Lineage for microG build 15.1-20180723-microG-angler with Google device registration disabled

I'm not sure what "Google device registration" means, but if it's the setting that determines whether Signal can register with Google Cloud Messaging, you'll need to enable that.

**Comment by thisIsMeHello** [comment]
The only app I have that isn't f-droid/open source, and I'd imagine relies on Google Play Services, is whatsApp and that seems to be working fine

**Comment by thisIsMeHello** [comment]
"For a full-working microG setup, you may consider to install...the Services Framework Proxy (GsfProxy) module to provide Google's push messaging service."

I tried installing GsfProxy and unfortunately the app still crashes. Also uninstalled then reinstalled Signal, no change. 

@haffenloher For me the point of using a custom ROM is to reduce the use of Google services and tracking so I'd rather not register the device with them (if I can get Signal working, I can also ditch whatsApp). I understand that this might be a niche/minority desire and maybe not justify dev attention, but I thought it was worth a try!

**Comment by thisIsMeHello** [comment]
Found these:

https://github.com/signalapp/Signal-Android/issues/6895 and also a discussion here https://www.reddit.com/r/fossdroid/comments/7i3tbc/what_am_i_giving_up_by_usingnot_using_microg/

Temporarily disabling "MicroG Services Core" in "settings/Apps & notifications" allows registration!
