### ISSUE TITLE
android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0

### ISSUE THREAD

**Issue by kiplingw** [signalapp/Signal-Android#8088]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Every time I open Signal it crashes immediately. This looks similar to  #6852, but there was no debugging log provided so it is hard to tell if I am experiencing the same problem.

I can't reinstall from a backup because the backups are now old and to generate a new one automatically Signal needs to still be able launch in the background which it cannot do anymore.

### Steps to reproduce
Open signal and it crashes immediately.

### Device info
**Device:** Samsung Galaxy S4
**Android version:** 7.1.2
**Signal version:** 4.23.4

### Link to debug log
This was captured via adb logcat.

```
...
08-07 20:03:39.917  1919  2890 I ActivityManager: Killing 21529:org.thoughtcrime.securesms/u0a96 (adj 200): crash
08-07 20:03:39.918  1919  2890 D ActivityManager: cleanUpApplicationRecord -- 21529
08-07 20:03:39.921  1919  2890 W ActivityManager: Scheduling restart of crashed service org.thoughtcrime.securesms/.service.MessageRetrievalService in 1000ms
08-07 20:03:39.921  1919  2890 W ActivityManager: Scheduling restart of crashed service org.thoughtcrime.securesms/.service.KeyCachingService in 11000ms
08-07 20:03:39.941  1919  2890 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=org.thoughtcrime.securesms/.ConversationListActivity (has extras)} from uid 10029 on display 0
08-07 20:03:40.003  1919  6358 E ActivityManager: applyOptionsLocked: Unknown animationType=0
08-07 20:03:40.039  1919  5926 D OpenGLRenderer: endAllActiveAnimators on 0x93ef0500 (RippleDrawable) with handle 0x94069700
08-07 20:03:40.051  1919  6358 I ActivityManager: Start proc 22016:org.thoughtcrime.securesms/u0a96 for activity org.thoughtcrime.securesms/.ConversationListActivity
08-07 20:03:40.104  1919  2892 D GraphicsStats: Buffer count: 6
08-07 20:03:40.221 22016 22016 I art     : Starting a blocking GC AddRemoveAppImageSpace
08-07 20:03:40.248 22016 22016 I MultiDex: VM with version 2.1.0 has multidex support
08-07 20:03:40.248 22016 22016 I MultiDex: Installing application
08-07 20:03:40.248 22016 22016 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-07 20:03:40.263  1919  1984 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
08-07 20:03:40.269 22016 22016 W PartProvider: onCreate()
08-07 20:03:40.394 22016 22016 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1533783689033
08-07 20:03:40.399 22016 22016 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1533726967907
08-07 20:03:40.404 22016 22016 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.LocalBackupListener scheduling for: 1533716820595
08-07 20:03:40.411 22016 22016 I org.webrtc.Logging: NativeLibrary: Loading native library.
08-07 20:03:40.411 22016 22016 I org.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
08-07 20:03:40.438 22016 22016 W PassphraseRequiredActionBarActivity: onCreate(null)
08-07 20:03:40.452 22016 22053 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:40.463 22016 22053 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:40.573 22016 22016 W ExperienceUpgradeActivity: getExperienceUpgrade(384)
08-07 20:03:40.577 22016 22016 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
08-07 20:03:40.595 22016 22016 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
08-07 20:03:40.770 22016 22016 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-07 20:03:40.786 22016 22016 W PassphraseRequiredActionBarActivity: onResume()
08-07 20:03:40.943 22016 22068 W MessageRetrievalService: Waiting for websocket state change....
08-07 20:03:40.945 22016 22068 W MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: true
08-07 20:03:40.947 22016 22068 W MessageRetrievalService: Making websocket connection....
08-07 20:03:40.954 22016 22016 W KeyCachingService: onCreate()
08-07 20:03:40.981 22016 22068 W WebSocketConnection: WSC connect()...
08-07 20:03:41.023 22016 22068 W SignalCommunicationModule: onConnecting()
08-07 20:03:41.026 22016 22068 W MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: true
08-07 20:03:41.028 22016 22068 W MessageRetrievalService: Reading message...
08-07 20:03:41.035 22016 22016 W service : Broadcasting new secret...
08-07 20:03:41.037 22016 22016 W KeyCachingService: onStartCommand, null
08-07 20:03:41.037 22016 22016 W KeyCachingService: onStartCommand, null
08-07 20:03:41.038 22016 22016 W KeyCachingService: onStartCommand, null
08-07 20:03:41.039 22016 22016 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
08-07 20:03:41.039 22016 22056 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_json, quote_id, quote_author, quote_body, quote_attachment, shared_contacts FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_json, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS quote_id, NULL AS quote_author, NULL AS quote_body, NULL AS quote_attachment, NULL AS shared_contacts FROM sms WHERE (read = 0 AND notified = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, json_group_array(json_object('_id', part._id, 'unique_id', part.unique_id, 'mid', part.mid,'data_size', part.data_size, 'file_name', part.file_name, '_data', part._data, 'thumbnail', part.thumbnail, 'ct', part.ct, 'cl', part.cl, 'fast_preflight_id', part.fast_preflight_id, 'voice_note', part.voice_note, 'width', part.width, 'height', part.height, 'quote', part.quote, 'cd', part.cd, 'name', part.name, 'pending_push', part.pending_push)) AS attachment_json, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, read_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, quote_id, quote_author, quote_body, quote_attachment, shared_contacts FROM mms LEFT OUTER JOIN part ON part.mid = mms._id WHERE (read = 0 AND notified = 0) GROUP BY mms._id ORDER BY date_received ASC)
08-07 20:03:41.039 22016 22016 W KeyCachingService: Incrementing activity count...
08-07 20:03:41.040 22016 22016 W MessageRetrievalService: Active Count: 1
08-07 20:03:41.060 22016 22066 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
08-07 20:03:41.054 22066 22066 W RenderThread: type=1400 audit(0.0:551): avc: denied { read } for name="gpuclk" dev="sysfs" ino=11273 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-07 20:03:41.054 22066 22066 W RenderThread: type=1300 audit(0.0:551): arch=40000028 syscall=322 per=800008 success=no exit=-13 a0=ffffff9c a1=a715807a a2=20000 a3=0 items=1 ppid=1599 auid=4294967295 uid=10096 gid=10096 euid=10096 suid=10096 fsuid=10096 egid=10096 sgid=10096 fsgid=10096 tty=(none) ses=4294967295 exe="/system/bin/app_process32" subj=u:r:untrusted_app:s0:c512,c768 key=(null)
08-07 20:03:41.054   215   215 W auditd  : type=1307 audit(0.0:551): cwd="/"
08-07 20:03:41.054   215   215 W auditd  : type=1302 audit(0.0:551): item=0 name="/sys/class/kgsl/kgsl-3d0/gpuclk" inode=11273 dev=00:0d mode=0100644 ouid=0 ogid=0 rdev=00:00 obj=u:object_r:sysfs:s0
08-07 20:03:41.054   215   215 W auditd  : type=1320 audit(0.0:551): 
08-07 20:03:41.065 22016 22066 I OpenGLRenderer: Initialized EGL, version 1.4
08-07 20:03:41.065 22016 22066 D OpenGLRenderer: Swap behavior 1
08-07 20:03:41.070 22016 22066 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
08-07 20:03:41.167  1919  1984 I ActivityManager: Displayed org.thoughtcrime.securesms/.ConversationListActivity: +1s164ms (total +2m43s350ms)
08-07 20:03:41.212 22016 22053 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.218 22016 22048 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.262 22016 22056 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.263 22016 22048 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.263 22016 22065 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.265 22016 22056 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.279 22016 22065 V Cursor  : Filling cursor window with start position:0 required position:0
08-07 20:03:41.394  8203  8389 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
08-07 20:03:41.394  8203  8389 E JavaBinder: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at com.android.providers.contacts.ContactsProvider2.openAssetFileInner(ContactsProvider2.java:9103)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at com.android.providers.contacts.ContactsProvider2.openAssetFileLocal(ContactsProvider2.java:8988)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at com.android.providers.contacts.ContactsProvider2.openAssetFile(ContactsProvider2.java:8964)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1557)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1623)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:422)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
08-07 20:03:41.394  8203  8389 E JavaBinder: 	at android.os.Binder.execTransact(Binder.java:565)
08-07 20:03:41.397 22016 22048 W JobConsumer: 
08-07 20:03:41.397 22016 22048 W JobConsumer: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileInputStream android.content.res.AssetFileDescriptor.createInputStream()' on a null object reference
08-07 20:03:41.397 22016 22048 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.getAvatar(MultiDeviceContactUpdateJob.java:214)
08-07 20:03:41.397 22016 22048 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.generateSingleContactUpdate(MultiDeviceContactUpdateJob.java:103)
08-07 20:03:41.397 22016 22048 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.onRun(MultiDeviceContactUpdateJob.java:87)
08-07 20:03:41.397 22016 22048 W JobConsumer: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
08-07 20:03:41.397 22016 22048 W JobConsumer: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.runJob(JobConsumer.java:74)
08-07 20:03:41.397 22016 22048 W JobConsumer: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.run(JobConsumer.java:47)
08-07 20:03:41.397 22016 22048 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-3
08-07 20:03:41.397 22016 22048 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 22016
08-07 20:03:41.397 22016 22048 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileInputStream android.content.res.AssetFileDescriptor.createInputStream()' on a null object reference
08-07 20:03:41.397 22016 22048 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.getAvatar(MultiDeviceContactUpdateJob.java:214)
08-07 20:03:41.397 22016 22048 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.generateSingleContactUpdate(MultiDeviceContactUpdateJob.java:103)
08-07 20:03:41.397 22016 22048 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MultiDeviceContactUpdateJob.onRun(MultiDeviceContactUpdateJob.java:87)
08-07 20:03:41.397 22016 22048 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
08-07 20:03:41.397 22016 22048 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.runJob(JobConsumer.java:74)
08-07 20:03:41.397 22016 22048 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.run(JobConsumer.java:47)
08-07 20:03:41.401  1919  2868 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.ConversationListActivity
08-07 20:03:41.509  1919  5926 I OpenGLRenderer: Initialized EGL, version 1.4
08-07 20:03:41.509  1919  5926 D OpenGLRenderer: Swap behavior 1
08-07 20:03:41.678 22016 22075 W EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/4cd2166d6934e20229b9eb4c80abc86b75953316632adbbaebe7dcca0e2e2199.0
08-07 20:03:41.683 22016 22075 W EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/4cd2166d6934e20229b9eb4c80abc86b75953316632adbbaebe7dcca0e2e2199.0
08-07 20:03:41.684 22016 22075 W EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/4cd2166d6934e20229b9eb4c80abc86b75953316632adbbaebe7dcca0e2e2199.0
08-07 20:03:41.703 22016 22075 W EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/f6c5698316717863227ba4d4ed999e983ed25442f076e8e8b4827c40816c8d60.0
08-07 20:03:41.717 22016 22075 W EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/f6c5698316717863227ba4d4ed999e983ed25442f076e8e8b4827c40816c8d60.0
08-07 20:03:41.717 22016 22016 W PassphraseRequiredActionBarActivity: onPause()
08-07 20:03:41.719 22016 22075 W EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/f6c5698316717863227ba4d4ed999e983ed25442f076e8e8b4827c40816c8d60.0
08-07 20:03:41.776 22016 22069 W WebSocketConnection: onConnected()
08-07 20:03:41.778 22016 22069 W SignalCommunicationModule: onConnected()
08-07 20:03:41.785 22016 22069 W WebSocketConnection: WSC onMessage()
08-07 20:03:41.799 22016 22069 W WebSocketConnection: Message Type: 1
08-07 20:03:41.800 22016 22075 W EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/d61c1ea3e56b560aeff45b55a0ee144b8216d8d8fec0537497feefa1099e6d32.0
08-07 20:03:41.807 22016 22075 W EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/d61c1ea3e56b560aeff45b55a0ee144b8216d8d8fec0537497feefa1099e6d32.0
08-07 20:03:41.809 22016 22075 W EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/d61c1ea3e56b560aeff45b55a0ee144b8216d8d8fec0537497feefa1099e6d32.0
08-07 20:03:41.835 22016 22016 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
08-07 20:03:41.836 22016 22016 W KeyCachingService: Decrementing activity count...
08-07 20:03:41.837 22016 22016 W MessageRetrievalService: Active Count: 0
08-07 20:03:41.983  1919  1930 I art     : Background partial concurrent mark sweep GC freed 66994(3MB) AllocSpace objects, 11(252KB) LOS objects, 33% free, 15MB/23MB, paused 2.441ms total 194.854ms
08-07 20:03:42.168 22016 22016 W PassphraseRequiredActionBarActivity: onDestroy()
08-07 20:03:42.425  2910  3023 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
08-07 20:03:43.114  1600  1694 D audio_hw_primary: out_standby: enter: stream (0xb6244240) usecase(1: low-latency-playback)
08-07 20:04:05.032  4944  6617 D BatchingTimer: Client timer is done.
08-07 20:04:05.032  4944  6617 D BatchingTimer: Client batch timer is started.
08-07 20:04:05.083  4944 22102 D BatchingTimer: Client timer time: 60
08-07 20:04:14.535  1919  2029 D WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
08-07 20:04:14.553  1919  1962 E BatteryStatsService: no controller energy info supplied
08-07 20:04:14.553  1919  1962 E BatteryStatsService: no controller energy info supplied
08-07 20:04:14.579  1919  1962 E BatteryStatsService: power: Missing API
08-07 20:04:14.592  1919  1962 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
08-07 20:04:22.916  4944  5187 D BatchingTimer: Device timer is done.
08-07 20:04:22.916  4944  5187 D BatchingTimer: Device batch timer is started.
08-07 20:04:23.012  4944 22108 D BatchingTimer: Device timer time: 60
08-07 20:04:36.779 22016 22079 W WebSocketConnection: Sending keep alive...
08-07 20:04:37.031 22016 22069 W WebSocketConnection: WSC onMessage()
08-07 20:04:37.032 22016 22069 W WebSocketConnection: Message Type: 2
08-07 20:04:39.821  1919  1986 I PowerManagerService: Going to sleep due to screen timeout (uid 1000)...
08-07 20:04:39.877  2084  2084 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
08-07 20:04:39.887  1919  1986 W Adreno-EGL: <qeglDrvAPI_eglQueryContext:4373>: EGL_BAD_ATTRIBUTE
08-07 20:04:40.445  1919  1959 I VrManagerService: VR mode is disallowed
08-07 20:04:40.519  1919  1986 V KeyguardServiceDelegate: onScreenTurnedOff()
08-07 20:04:40.527  1919  1984 I DisplayManagerService: Display device changed state: "Built-in Screen", OFF
08-07 20:04:40.531   230   230 D SurfaceFlinger: Set power mode=0, type=0 flinger=0xb68a8000
08-07 20:04:40.538  1919  2053 E LightSensor: Light old sensor_state 129, new sensor_state : 1 en : 0
08-07 20:04:40.540   230   230 D qdhwcomposer: hwc_setPowerMode: Setting mode 0 on display: 0
08-07 20:04:40.816   230   230 D qdhwcomposer: hwc_setPowerMode: Done setting mode 0 on display 0
08-07 20:04:40.819  1919  2066 D SurfaceControl: Excessive delay in setPowerMode(): 291ms
08-07 20:04:40.827  1919  1986 I QCOM PowerHAL: Got set_interactive hint
08-07 20:04:40.835  1919  1986 I PowerManagerService: Sleeping (uid 1000)...
08-07 20:04:40.850  2084  2084 W FingerprintManager: isFingerprintHardwareDetected(): Service not connected!
08-07 20:04:40.930  1600  1600 D audio_hw_primary: adev_set_parameters: enter: screen_state=off
08-07 20:04:41.042  1919  1960 I WindowManager: OverscanTimeout run
08-07 20:04:41.818 22016 22068 W MessageRetrievalService: Application level read timeout...
08-07 20:04:41.822 22016 22068 W MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: true
08-07 20:04:41.825 22016 22068 W MessageRetrievalService: Reading message...
08-07 20:04:44.928  1919  2869 I ActivityManager: Setting hasTopUi=true for pid=2084
...
```

**Comment by kiplingw** [comment]
So for those experiencing this problem, here is a workaround.

If you reinstall Signal the problem goes away. Of course, you're then stuck with the problem of having lost all your data. To work around this set your phone into airplane mode and try re-opening Signal. For whatever reason it opens without crashing, but you obviously can't send or receive messages. From in this state you can initiate the creation of a new backup. After that disable airplane mode, re-install Signal, and restore from your backup.

**Comment by greyson-signal** [comment]
Haven't seen any new reports, and it doesn't show up in the Play Store crash reports.
