### ISSUE TITLE
Backup does not complete

### ISSUE THREAD

**Issue by siccovansas** [signalapp/Signal-Android#8101]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't get Signal to complete a backup on a Fairphone 1. I've tried it dozens of times across the last couple of versions of Signal. The backup starts normally, it shows the notification and the backed up messages counter in the settings increases very fast initially and then slows down but steadily continues (I think when it starts backing up photos and videos) until the notification is suddenly gone after which I find no backup file in the Signal folder.

This is an old installation of Signal, it was probably installed in the second half of 2014 (when it was still called TextSecure). Signal is listed as being around 4GB big, but there is enough space on the device for the backup. Sometimes the backup stops before the Signal backup tmp file reaches 1GB, but I've seen the tmp file reach 3GB+ as well when it stopped. Sometimes the failed backup tmp file is automatically removed by Signal and sometimes it lingers around till I delete it.

Issue #8024 looks related, but in my case the counter doesn't continue.

Please let me know if I can clear anything up or try something. I really want the backup to work as it currently blocks me from moving to another phone :).

### Steps to reproduce
- Start a backup
- Wait till the backup notification is gone

**Actual result:** There is no backup file in the Signal folder
**Expected result:** There should be a backup file in the Signal folder

### Device info
**Device:** Fairphone 1
**Android version:** 4.2.2
**Signal version:** 4.24.8

### Link to debug log
- debug log for 4.23.4: https://debuglogs.org/e8772891bdc08c09f6f4ec74e5908753529a0ebb7427502b20f6707a2ea34133 
- debug log for 4.24.8: https://debuglogs.org/707eb8cea4a2255693e464a273d15fadf1ed09e281abccad7b450535b7adc9c1

**Comment by greyson-signal** [comment]
@siccovansas FWIW the new logger that'll be in the 4.25 release should help with collecting debug logs :)

**Comment by greyson-signal** [comment]
Can you update this with new logs from 4.25.x?

**Comment by siccovansas** [comment]
Somehow, after having this problem for months, the backups now run successfully (even before updating to 4.25.x). I haven't been able to reproduce the issue since 4.25.x, so I'll close this issue :)

**Comment by siccovansas** [comment]
Hmm, so the backup has failed again and I know have a Signal 4.25.x log, so I reopen this issue. It failed after 3.7GB while a full backup should've been 3.9GB. Another backup was started by Signal itself and failed much sooner. Here is the log: https://debuglogs.org/93b8d3f85cb5992361e1ebb8939ec17f07bbf5434f2cae25ccacc9bc6b7012de

I tried another backup and it failed within minutes, see this log which I made soon after it failed: https://debuglogs.org/521cbc200142b5b4b682eeb22295f8103cf4d7bfb7399d6dedd7f350b9395822

**Comment by greyson-signal** [comment]
Both logs contain the following:

```java
2018-09-26 01:27:05.530 CEST W FullBackupExporter: java.io.IOException: write failed: ENOSPC (No space left on device)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at libcore.io.IoBridge.write(IoBridge.java:506)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at java.io.FileOutputStream.write(FileOutputStream.java:187)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at java.io.OutputStream.write(OutputStream.java:82)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter$BackupFrameOutputStream.writeStream(FullBackupExporter.java:346)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter$BackupFrameOutputStream.write(FullBackupExporter.java:320)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportAttachment(FullBackupExporter.java:211)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.lambda$export$3$FullBackupExporter(FullBackupExporter.java:82)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter$$Lambda$3.accept(Unknown Source)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.exportTable(FullBackupExporter.java:184)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.backup.FullBackupExporter.export(FullBackupExporter.java:82)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.jobs.LocalBackupJob.onRun(LocalBackupJob.java:72)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.runJob(JobConsumer.java:74)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.run(JobConsumer.java:47)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: Caused by: libcore.io.ErrnoException: write failed: ENOSPC (No space left on device)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at libcore.io.Posix.writeBytes(Native Method)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at libcore.io.Posix.write(Posix.java:189)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	at libcore.io.IoBridge.write(IoBridge.java:501)
2018-09-26 01:27:05.530 CEST W FullBackupExporter: 	... 12 more
```

Meaning you ran out of disk space. We should be surfacing this information better, but the remedy would be to free up more space. Thank you!
