### ISSUE TITLE
Crash after upgrade to 4.25.0

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#8107]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After a first start that runs fine, Signal crashes at startup. A downgrade to 4.24.8 didn't help, I had to remove all data and restore a backup.

### Steps to reproduce
- Upgrade Signal 4.24.8 to 4.25.0
- Start Signal
- Close and lock Signal
- Start Signal
- Crash

**Actual result:** A crash (OS screen "Signal has stopped).
**Expected result:** Signal starts

### Device info

**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.25.0

### Link to debug log
I got catlog output. I don't understand how this error could occur since I'm running Android 6.0.1.
```
08-14 17:07:35.448 D/AndroidRuntime(15994): Shutting down VM
08-14 17:07:35.448 E/AndroidRuntime(15994): FATAL EXCEPTION: main
08-14 17:07:35.448 E/AndroidRuntime(15994): Process: org.thoughtcrime.securesms, PID: 15994
08-14 17:07:35.448 E/AndroidRuntime(15994): java.lang.AssertionError: OS downgrade not supported. KeyStore sealed data exists on platform < M!
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:38)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:155)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:100)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4806)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.os.Looper.loop(Looper.java:234)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at java.lang.reflect.Method.invoke(Native Method)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-14 17:07:35.448 E/AndroidRuntime(15994): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by greyson-signal** [comment]
https://github.com/signalapp/Signal-Android/blob/acb40c6133e9a8ebccd84494c2a23c63f83afd7a/src/org/thoughtcrime/securesms/logging/LogSecretProvider.java#L34

:man_facepalming: 

Thank you very much for finding this before we launched to beta :)

**Comment by johanw666** [comment]
I was looking at the wrong file, `DatabaseSecretProvider.java` which has the same error message. That will teach me not to do 5 complicated things at the same time.

**Comment by johanw666** [comment]
I just built https://github.com/signalapp/Signal-Android/commit/d581525a6179e645c36ed313a29a9996c2306ecd and that works fine on my device. I only had to reset a few secure sessions afterwards.
