### ISSUE TITLE
"Empty message" snackbar appears when clicking twice at the send button

### ISSUE THREAD

**Issue by mueller-ma** [signalapp/Signal-Android#8126]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I write a message and double tab on the send button twice, I get a snackbar with "ConversationActivity_message_is_empty_exclamation".

### Steps to reproduce
- Write a text
- Click on send twice very fast

**Actual result:** Message is sent and I get a snackbar with "ConversationActivity_message_is_empty_exclamation".
**Expected result:** Message is sent and the attachment menu is opend

### Device info

**Device:** Oneplus X
**Android version:** 7.1.2
**Signal version:** 4.24.8

### Link to debug log
````
08-19 10:12:39.515 7723-7723/org.thoughtcrime.securesms W/ConversationActivity: org.whispersystems.libsignal.InvalidMessageException: Message is empty!
        at org.thoughtcrime.securesms.ConversationActivity.getMessage(ConversationActivity.java:1655)
        at org.thoughtcrime.securesms.ConversationActivity.sendTextMessage(ConversationActivity.java:1807)
        at org.thoughtcrime.securesms.ConversationActivity.sendMessage(ConversationActivity.java:1735)
        at org.thoughtcrime.securesms.ConversationActivity.access$3200(ConversationActivity.java:200)
        at org.thoughtcrime.securesms.ConversationActivity$SendButtonListener.onClick(ConversationActivity.java:2057)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22433)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
````

Legacy issue: #6076

**Comment by greyson-signal** [comment]
I think this is to be expected. You sent a message, which clears the text area. Then you click send again, but the input area is empty, so you get this pop up.

**Comment by mueller-ma** [comment]
IMO the button action should change to "open attachment drawer" instantly after sending the message.
