### ISSUE TITLE
new "Add to home screen" has Signal crash/restart on Huawei P10 Lite

### ISSUE THREAD

**Issue by steko** [signalapp/Signal-Android#8139]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The new "Add to home screen" feature added in Signal 4.25 causes the app to crash and restart, just for some conversations (i.e. not all, but not just one). Nothing is added to home screen, with the stock Huawei launcher. Other conversations can be added without problems. 

### Steps to reproduce
- open Signal
- enter the specific conversation
- tap on menu icon in the upper right
- tap "Add to home screen" from the menu

**Actual result:** the app gets immediately closed and restarts with the lock screen
**Expected result:** a quick link should be added to the home screen

### Device info

**Device:** Huawei P10 Lite (WAS-LX1)
**Android version:** 7.0
**Signal version:** 4.25.5

### Link to debug log

https://debuglogs.org/32f3ffb8f4dc0bac0eeb967056dad3b1db3996d1b20ee4f1642ed8a72b261bfe

**Comment by greyson-signal** [comment]
Huh, looks like Android passes the icon bitmap bytes right into the intent, and as a result we're hitting the transaction limit size. I'll have to update it so we scale it down beforehand.

```java
2018-08-21 17:07:02.143 CEST I ConversationActivity: Creating home screen shortcut for recipient +**********16
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1639480 bytes
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:994)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:421)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.support.v4.content.pm.ShortcutManagerCompat.requestPinShortcut(ShortcutManagerCompat.java:102)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.ConversationActivity$8.onPostExecute(ConversationActivity.java:824)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.ConversationActivity$8.onPostExecute(ConversationActivity.java:788)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.AsyncTask.finish(AsyncTask.java:692)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:709)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:105)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:156)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:6577)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: Caused by: android.os.TransactionTooLargeException: data parcel size 1639480 bytes
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.BinderProxy.transactNative(Native Method)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.os.BinderProxy.transact(Binder.java:617)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3532)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:989)
2018-08-21 17:07:02.299 CEST E UncaughtExceptionLogger: 	... 13 more
```

**Comment by steko** [comment]
Right, the contacts that worked well have no associated image 👻

Thanks!
