### ISSUE TITLE
Unable-to-connect error when re-registering after factory reset

### ISSUE THREAD

**Issue by five-c-d** [signalapp/Signal-Android#8148]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Having difficulty re-registering signalapp with a phone that was recently factory-reset.  

### Steps to reproduce
- begin using signalapp circa ~2016 with +32 XXX XXX XXX (Belgium) 
- ditch whatsApp and move to signal as the primary messenger 
- factory reset the handset a few days ago on 2018-08-23
- attempt to install and then re-register signal 

**Actual result:** Mixture of "unable to connect" errors, or simply failing to receive the SMS-or-robocall with the confirmation code.  Sometimes get prompted to input the six-digit-code by signalapp, sometimes do not get that far in signalapp UI/UX.  
* To eliminate possibility it was the network being flaky, attempted from multiple locations (in two countries even).  
*  To eliminate the possibility of rate-limiting being the problem, waited a few hours and then tried again Friday 2018-08-24, then waited a few days before trying again Wednesday 2018-08-29 between 8:20pm and 8:23pm localtime in Belgium, with latest attempt resulting in the generic "unable to connect to service" error message.  
*  To eliminate the possibility that it was Something Else, tried registering a different telephone number (from burner phone) which DID succeed correctly.  So it seems to be a problem specific to this +32.xxx.xxx.xxx telephone number, albeit it was working before.  
*  Did not setup the registration-lock-PIN feature (previously when signal functioned).  
*  Fresh install of signal with no attempt to retain past conversation-history.
*  Handset is linked to the associated google-account.  
*  Was not using signalapp-beta (previously nor currently) on this handset. 

**Expected result:** Should not get "unable to connect" error message, should receive SMS conf-code, should make it all the way through the steps, registration should succeed properly.  

### Screenshots

n/a... might be able to provide them if really necessary 

### Device info

**Device:** Samsung S9+ (Model SM-965F) 
**Android version:** 8.0 stock ROM with Samsung Experience v9.0 and Android security patch level 1st August 2018 (latest available for handset) 
**Signal version:** 4.24.8

### Link to debug log

n/a because the handset cannot register with signal-server ... MIGHT be able to try the adb logcat thing if REALLY necessary?

### Additional potentially-relevant info

* Forum thread with all the gory details:   https://whispersystems.discoursehosting.net/t/blacklist-of-signal/3915 

*  There should also be some email(s) which was/were sent to support@signal.org 

From searching, these issue-reports might be relevant:  
*  https://github.com/signalapp/Signal-Android/issues/7980 == Unable to register: verification code not received, however sms&robocall arrived 90 minutes later for india OP, commenter#2 never received sms&robocall, commenter#3 gets unable-to-connect, commenter#4 in Tanzania has mixture of unable-to-connect plus never getting sms&robocall on 4.24.8 latest-stable 
* https://github.com/signalapp/Signal-Android/issues/7819 == App doesn't report 413 [you-are-rate-limited] errors correctly ... can somebody review the pull request over there please?  
*  https://github.com/signalapp/Signal-Android/issues/6237#issuecomment-301343886  ==  "unable to connect" after factory reset && playSvcs update, workaround was to uninstall playSvcs, register signal, reinstall playSvcs... but that left the playSvcs in a broken state 
*  https://github.com/signalapp/Signal-Android/issues/5864 == Signal was "unable to connect" to the server.  Failing at last step of verification [i.e. after sms received], tried factory reset.  Various commenters also had issues, in ONE case it helped to open play store, wait a few minutes, and then retry the signal registration, but others never achieved success.  

These issue-reports are NOT likely to be relevant to this specific case:  
*  https://github.com/signalapp/Signal-Android/issues/7994 == Unable to register after a restore, getting "unable to connect", issue closed after problem went away by itself (probably rate-limited).  
*  https://github.com/signalapp/Signal-Android/issues/7230 == Unable to complete registration [when phone has PlaySvcs but is not linked to gmail acct], closed-by-bot without getting resolved  
*  https://github.com/signalapp/Signal-Android/issues/7220 == Connectivity error - Signal was "unable to connect" to the server [when using microG], closed after tweaking microG settings 
*  https://github.com/signalapp/Signal-Android/issues/6237 == Connectivity error. Signal was "unable to connect" to the server AFTER sms conf-code was received.  "solved" by hard-rebooting phone to joggle GCM's elbow. 
* https://github.com/signalapp/Signal-Android/issues/5155 == Unable to register, closed as custom-ROM-related errmsg 
* https://github.com/signalapp/Signal-Android/issues/2621 == push registration failure over 3g, closed as WONTFIX, carrier Republic Wireless is not supported by signalapp 
*  https://github.com/signalapp/Signal-Android/issues/7680 == Can't verify number on version 4.17.5 for android without google play services , "Unable to connect" , closed because user was in country with censorship and google disabled domain-fronting [upgrade to aws-based domain fronting may have solve the problem while that lasted]

**Comment by greyson-signal** [comment]
Unfortunately this is a case where a log would be super helpful (I feel like we should make log submission available somehow during registration...). If you could get the `adb logcat` logs after a registration failure, we should be able to diagnose what kind of error is happening here. Thanks!

**Comment by five-c-d** [comment]
@greyson-signal , thanks for your reply... and yes, it is pretty silly not to be able to submit debug-logs from the portion of the process where signalapp is relying heavily upon third party providers (GCM and Twilio or whatever it is now) without going through the effort to get USB debugging configured and capture the info with a programmer's tool from a laptop.  Special software required, non-phone hardware required, painfully difficult steps required, no helpdocs oriented towards the masses?  

Most endusers are going to simply abandon the registration process when they hit a registration-bug like this... and there is no way to distinguish *actual bugs* from people that just *changed their mind* once they found out signalapp was demanding their phone number so it could robocall them.  

Can you provide me a pointer to a super-straightforward step-by-step tutorial, aimed at the masses of everyday users out there, which would walk them through how to install adb and capture a logcat?  Maybe on the signal wiki somewhere?  This is the best I could find... 

* no official helpdocs for endusers whatsoever == https://www.google.com/search?q=%22logcat%22+site%3Asignal.org

* github-based quasi-official helpdocs give no detailed instructions whatsoever == https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports#advanced-capturing

* 2017 tacitly-official comment by moxie0 says to try googling(tm) to learn how == https://github.com/signalapp/Signal-Android/issues/2436#issuecomment-301278644 

* 2018 unofficial-comment with SOMEWHAT detailed instructions == https://github.com/signalapp/Signal-Android/issues/7813#issuecomment-393722041  ("open a command prompt" is not really aimed at the everyday enduser from the whatsapp crowd however!)

* 2014 unofficial-commentTwo with significantly different instructions == https://github.com/signalapp/Signal-Android/issues/2024#issuecomment-60066876 

Even taking the advice of Moxie0, there was not much helpful to the Typical WhatsApp Convert that signal.org sees as their target market, out there on the interwebz:  

* 2018 **reasonably** enduser-oriented helpdoc from Citrix which is close to what is needed, but assumes windows-PC-plus-android-phone in a few places, which is not suitable for signal.org endusers that might be linux-plus-iOS or whatnot == https://support.citrix.com/article/CTX232375 

* 2018 reddit thread for people with adb already installed == https://www.reddit.com/r/signal/comments/8twtld/took_signal_android_update_now_signal_fcs/e1b4mz5/

* 2017 installation-guide which explains how to download and then set the path == https://lifehacker.com/the-easiest-way-to-install-androids-adb-and-fastboot-to-1586992378

* 2016 installation-guide which briefly mentions logcat without any details == https://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/

* 2011 stackOverflow thread suggests there used to be an app for that... but now android security prevents it unless you have rooted your phone, if I understand correctly == https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log 

* goog's developer-oriented manpage for installing adb == https://developer.android.com/studio/command-line/adb 

* goog's developer-oriented manpage for using logcat == https://developer.android.com/studio/command-line/logcat 

Outside the question of the tutorial-helpdoc, can you give me an idea how long it is necessary to wait between re-registration-attempts?  There was an attempt Friday, and another attempt today, if a third attempt is made eight hours later (with adb logcat supposedly active) will that be rate-limited?  If the attempted logcat capture was unsuccessful for whatever reason, and a fourth re-registration attempt is made thirty minutes after the third, will THAT be rate-limited?

**Comment by greyson-signal** [comment]
Yeah, often times we're simply fortunate enough that may of the bug reporters have a technical background, but I agree that we need something more user-friendly for this case. I'll look into what it would take to get the debug log submission accessible during registration, as this isn't the first time it's caused problems.

Regarding a tutorial, I think if you follow the lifehacker article, then type "adb logcat" into a command prompt / terminal, you should be good. You can just copy-paste the output here. **However**, be sure to check those logs and make sure they don't reveal any personal information. If the idea of following the tutorial or cleaning your logs makes you nervous, don't worry about getting the logs. Better safe than sorry.

> can you give me an idea how long it is necessary to wait between re-registration-attempts

You should be able to make several registration requests (some number less than 10, but I'm not confident enough to give an exact number) back-to-back without getting limited. I often have to do this when testing things that involve fresh install. If you do get rate limited, you usually have to wait around 24 hours.

Given your description, it's unlikely that you're experiencing rate-limiting, unless there's some other bug.

**Comment by five-c-d** [comment]
This is likely one of those times you are going to be fortunate  ;-)  

My point was mostly to encourage you, or someone you know, to write the code that will allow us to click a button to generate debug-logs from the registration screen.  There is already a button once registered, so I don't expect cloning THAT button and making it visible during the registration process, is going to be especially hard.  (But have not written a pull request sorry)    

That said, long-term there might **also** need to be a nice here-is-your-adb-logcat-tutorial, since installation itself does not always go smoothly, as opposed to just registration when the signalapp is already up and functional on the device.  

Will let you know in the next couple of days if logcat acquisition is successful, appreciate your assistance

**Comment by five-c-d** [comment]
Forgot to specify that the carrier is Orange (Belgium / EU), so I wouldn't expect this to be a carrier-specific issue, as they are widely utilized.  Perhaps the problem is somehow phone-model-specific or SIM-specific, in addition to having some possible carrier-related idiosyncrasy?  

Tried putting the SIM-card from another handset into the problematic phone-device, which worked... tried putting the SIM-card from the problematic phone into another handset, which did NOT work.  So the mixture of unable-to-connect and never-receiving-sms-nor-robocall-with-conf-code, does seem to be specific to this number+plan+carrier+something combination.  

p.s.  No debug-logs yet via adb logcat, need to "borrow" admin-permissions from IT folks to be able to install the tools on target laptop, but with luck that will get us over the hump.

**Comment by five-c-d** [comment]
Okay, adb logcat was a success.  There is nothing jumping out that seems to be the root cause of the trouble... captured three unsuccessful registration-attempts... 

<pre>
09-04 12:54:11.587  7547 29455 W Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
09-04 12:54:11.739 20998 14917 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+32XXXXXXXXX
09-04 12:55:18.134 20998 15281 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/voice/code/+32XXXXXXXXX

09-04 12:56:35.240 20998 15548 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+32XXXXXXXXX

09-04 12:57:45.760 20998 17161 W RegistrationActivity: java.io.IOException: SERVICE_NOT_AVAILABLE
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source:6)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:67)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:479)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:468)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at java.lang.Thread.run(Thread.java:764)
09-04 12:57:53.564  7547 29649 W Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
09-04 12:57:53.707  7547 29649 W Conscrypt: Could not set socket write timeout: java.lang.reflect.InvocationTargetException
09-04 12:57:53.792 20998 17923 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+32XXXXXXXXX
09-04 12:58:17.167 20998 18158 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+32XXXXXXXXX
</pre>

Re:  "If the idea of following the tutorial or cleaning your logs makes you nervous" ... well, not so much nervous, as TIRED.   In capturing those 3 registration-attempts, the logcat textfile ended up with 50k lines aka 7 megabytes.  There are a lot of things in there which probably should be scrubbed/redacted, e.g. "facebook video id" and similar, which are presumably unrelated to signalapp.  To avoid the worry that I missed something...  since I believe I already have your direct contact-info, is it permissible to send this to you @greyson-signal rather than post it here on world-visible github?  I understand this is not the usual approach, and will not be offended, *in the slightest*, if you prefer to politely decline  :-) 

p.s.  I've changed my mind, and now believe this **might** be related:  #7230 == "Unable to complete registration [when phone has PlaySvcs but is not linked to gmail acct], closed-by-bot without getting resolved."   Similar behavior with unable-to-connect error, similar logcat with conscrypt-unable-to-set-timeout and java.lang.IOException (albeit not identical), and there ARE some gmail-related-error-messages in the 7MB logcat.  What does one do, to verify that one has 'authenticated in Google Play Services' properly?  Maybe try installing Push Notifications Fixer from the Google Play Store, https://play.google.com/store/apps/details?id=com.andqlimax.pushfixer.noroot , which supposedly tests whether GCM is functional?  Or is that not the same thing?

**Comment by five-c-d** [comment]
Relatively early on, there were also several of this kind of error-message in the logcat: 
<pre> 
09-04 12:52:44.056  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:44.581  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:44.753  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:45.081  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:45.302  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:45.302  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:45.561  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:45.902  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
09-04 12:52:46.273  6319  6517 E InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
</pre>

As shown in the previous comment, the first call to the whispersystems signal-servers happened under 2 seconds later in the sequence:  

<pre>
09-04 12:54:11.739 20998 14917 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+32XXXXXXXXX
</pre>

However, logcat doesn't show any unrecoverably-broken-and-will-be-disposed errors prior to re-registration attempt#2 at 12:56:35, nor prior to re-registration attempt#3 at 12:57:45 either.  Conceivably this is because the same broken channel was used during all three attempts... but that would contradict the will-be-disposed-[of] statement in the error-message.  There are a couple of places where unrecoverably-broken appears in the Signal-Android issues list, both of them signalapp crashes rather than just signalapp silently getting stuck, or throwing an unable-to-connect error however:  

* https://github.com/signalapp/Signal-Android/issues/7219 , where the channel was owned by org.thoughtcrime.securesms.PassphrasePromptActivity 
* https://github.com/signalapp/Signal-Android/issues/7866 , where the channel was owned by org.thoughtcrime.securesms.RoutingActivity 

Perhaps-interestingly, adb logcat is showing just a tilde in the textfile dump from windows 10 connected to the samsung s9+ handset, instead of the channel-owner that was visible in the 7866 and 7219 issues linked to above.  Is that because the adb logcat behavior has changed, or because the channel in this scenario was unowned, or possibly because there is a setting needed to get adb logcat to display more-verbose output that includes the channel-owner?

**Comment by greyson-signal** [comment]
Thank you very much for the in-depth information!

This bit of the log stands out to me:

```java
09-04 12:57:45.760 20998 17161 W RegistrationActivity: java.io.IOException: SERVICE_NOT_AVAILABLE
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source:6)
09-04 12:57:45.760 20998 17161 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:67)
```

Some research implies that these could be potential causes:

- Missing or out-of-date Google Play Services
- Being on a network with some sort of strict firewall
- Having a wrong system clock

That being said, given your description, none of those seem to match. Unfortunately GCM registration can be a bit of a black box :/

If you still want to send me the full log, you can DM me on the forum. Could be useful to look it over for other leads.

**Comment by five-c-d** [comment]
(Direct message sent, let me know what you need me to do on this end.) 

Yes, that IOException happened just prior to the third re-registration attempt... but it did NOT get thrown in the prior two re-registration attempts... thus, very unclear to me that this can be **the** root cause of the overall unable-to-re-register difficulty.  

Like yourself though, I am suspicious some kind of GCM-or-google-related difficulty might be happening here... maybe versioning-related thanks to the factory-reset.  Although prior to posting this bug-report we *tried* to rule out whether the device had a properly-connected-and-confirmed-goog-account, now I'm no longer sure that was fully verified.  If the play store allows one to install google-drive app, and one can login to it from the samsung phone, does that guarantee googAcct/googPlay/GCM are 100% okay?  Or is there more to it? 

Can pretty well rule out the network-and-firewall thing, there were attempts from a lot of different locations/networks prior to the logcat-session (which I believe WAS at a location where the firewall was especially strict... but again only one IOException appeared during the three sequential re-registration attempts from behind that same firewall the whole time).  

I don't **think** it was the clock-settings, but if it was, wouldn't we see something to that effect inside adb logcat that would indicate the difficulty...  java.lang.IOException: YOU_HAVE_VIOLATED_PHYSICS_AND_TRAVELLED_THROUGH_TIME or somesuch?  

But yeah, this is a pretty maddening issue.  My most likely culprit would be some kind of carrier-specific difficulty... but Orange Belgium/EU subscribers with samsungs, that is a pretty large number of people!  We should be seeing more complaints than just one, if it were true that nobody with that carrier was able to register signalapp anymore with their +32.xxx.xxx.xxx telephone number, I would think.

**Comment by five-c-d** [comment]
Latest troubleshooting attempts:  

1.  purchased new SIM-card to eliminate possibility it was some kind of low-level electrical difficulty, did not help 
2.  when visiting a friend physically, borrowed their handset temporarily (different model samsung), inserted new SIM-card into their handset, tried re-registering, did not help 
3.  visited phone-repair store to complain that carrier was not supporting signalapp properly, convinced two different phone-store employees to install & register signalapp on their devices as a test-case, one of them was unable to register but the other one WAS able to install&register successfully 

So almost certainly the problem is carrier-related (since phone-store employee#1 was also unable to register), but just as certainly the problem is intermittent or somehow handset-configuration-dependent, since phone-store employee#2 **was** able to get it to work.  

Is there some kind of super-verbose-tracelog-APK-version of signalapp that can be sideloaded via adb, or whatever, that will help track down this annoying failure more fully?  Doubtful that the phone-store employees will be willing to do that, of course, so we probably cannot capture a tracefile of the successful registration, but mayhap a more detailed tracefile of the unsuccessful re-registration attempt will lead to some progress narrowing down the root cause.

**Comment by greyson-signal** [comment]
@five-c-d Thank you for spending so much time digging into this! I really appreciate the effort, and we can hopefully use this as a jumping-off point for an investigation towards a long-term fix.

**Comment by manasb** [comment]
My cousin in India is on Airtel and has not received either OTP or call when trying to register for Signal.
