### ISSUE TITLE
Signal doesn't work at local hospital - Allo works flawlessly

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#8162]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
So I had the joy of being at a hospital today. I connect my phone to the WiFi and Chrome works flawlessly, everything works flawlessly really. Same thing on my grandmother's phone.

Well, everything except one thing; Signal. Signal just doesn't work and I have no idea why. The messages just keep spinning. I downloaded Allo to check if that works... and it works flawlessly. Both regular messages and incognito messages work 100%.

### Steps to reproduce
I dunno. Going to my hospital in Sweden and trying it out most likely isn't going to be an option. Maybe the logs can help?

**Actual result:** Signal doesn't work, but Allo does
**Expected result:** Signal works just like Allo

### Device info
Moto G4 on Nougat (My grandmother's phone. Couldn't get a log because of reasons)
Pixel XL on Pie, all updates installed.

Both phones have the latest beta

### Link to debug log
https://debuglogs.org/12f210999235f731da136c77c22c9aa6c0ed4e977768dda1d8af8c1eda6f265e
https://debuglogs.org/56b72d291b0b0e219df58d835db2ad5eaf6d04ab0ffb3e0640814b868787c84e
https://debuglogs.org/a9d2f1318e30966b7599169222fa78856030dbb77fe3b74ea6ce80d4669c1964
^ Hopefully at least one of them helps.

**Comment by zynexiz** [comment]
Can be that the hospital has a firewall that blocks the content. If it works on mobile network, I think that's the case.

**Comment by greyson-signal** [comment]
The log is filled with errors like this:

```java
2018-09-01 14:53:01.830 CEST W PushTextSendJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xe56e6488: I/O error during system call, Connection reset by peer
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:800)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:668)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:188)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:664)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:167)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onPushSend(PushTextSendJob.java:58)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:74)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.runJob(JobConsumer.java:74)
2018-09-01 14:53:01.830 CEST W PushTextSendJob: 	at org.thoughtcrime.securesms.jobmanager.JobConsumer.run(JobConsumer.java:47)
```

Sounds like a bad interaction between our SSL requirements and how the wifi at the hospital is configured. Sometimes you have to login to a portal or something, and sometimes public wifi is just weird/bad. Unfortunately, it's not really possible to debug this further without having the details of the hospital's network setup. If somehow you're able to obtain those, please reopen this. Thanks!

**Comment by Dyras** [comment]
@greyson-signal I have no idea how the WiFi was configured, but I know for a 100% fact that there was no login portal.

Maybe they just fucked up the Wifi, I dunno.
