### ISSUE TITLE
Signal Crash on Startup - NullPointerException

### ISSUE THREAD

**Issue by daemonkeeper** [signalapp/Signal-Android#8219]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Starting Signal no longer works, it crashes right away. By searching for similar issues, the issue seems to be, that my keystore got reset. logcat stacktrace

```java
09-23 14:05:28.336 16877 16877 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 16877
09-23 14:05:28.336 16877 16877 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6059)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6938)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
09-23 14:05:28.336 16877 16877 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey java.security.KeyStore$SecretKeyEntry.getSecretKey()' on a null object reference
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getKeyStoreEntry(KeyStoreHelper.java:106)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:65)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:155)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:100)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
09-23 14:05:28.336 16877 16877 E AndroidRuntime:        ... 8 more
09-23 14:05:28.338  5052  6468 D Debug   : !@DumpState : SHIP
09-23 14:05:28.338  5052  6468 D Debug   : !@DumpState : debug level:0x4f4c
09-23 14:05:28.338  5052  6468 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
```

However,

- I do not run any after market Android ROM (Lineage)
- I did not use any backup/restore app
- I did not change any system setting or run any upgrade

The only thing I got in the morning is a warning from Samsung, wherever it came from, that my "Samsung Pass" session expired and I had to log-in to my Samsung account again.

### Device info

**Device:**  Samsung Galaxy S8 (G950F)
**Android version:** 8.0
**Signal version:** 4.25.10

related issue: https://github.com/signalapp/Signal-Android/issues/7532 (but not related to Lineage as said)

**Comment by johanw666** [comment]
Odd. The exception suggests that the Signal key is missing or incorrect in the Android keystore. If you have root, can you check if there is a file `(UID)_USERKEY_SignalSecret`  in ` /data/misc/keystore/user_0` where (UID) is a secuence of (usually 5) numbers?

**Comment by gringoantikapitalist** [comment]
If you use a custom rom, try the .../outputs/apk/website folder

**Comment by sorianog** [comment]
@daemonkeeper is this still happening?

**Comment by daemonkeeper** [comment]
I would say yes. 

However, at the same time I have to admit I cannot provider further input on the root cause, as I am heavily depending on the ability to use Signal and could not wait until this is further addressed. Thus, I had to clear all data and start over from scratch - and therefore losing all chats. 

Since the conditions did not change since, I am awaiting this to happen again.

**Comment by cyrill62** [comment]
I got the same issue with a fresh new custom ROM.

https://forum.xda-developers.com/galaxy-s9/samsung-galaxy-s9--s9-cross-device-development/9-0pie-pixel-experience-9-0-t3853351

**Comment by cyrill62** [comment]
I get this crash even with the `Signal-website-debug-xxx.apk`

```
11-02 07:05:52.904 21378 21378 I PartProvider: onCreate()
11-02 07:05:52.912 21378 21378 I ApplicationContext: onCreate()
11-02 07:05:52.930 21378 21378 W KeyStore: KeyStore exception
11-02 07:05:52.930 21378 21378 W KeyStore: android.os.ServiceSpecificException:  (code 7)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.os.Parcel.createException(Parcel.java:1956)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:1910)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:1860)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:195)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:144)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:118)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:79)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:48)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.createAndStoreSecret(LogSecretProvider.java:48)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:22)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:161)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:101)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.os.Looper.loop(Looper.java:193)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-02 07:05:52.930 21378 21378 W KeyStore: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-02 07:05:52.933 21378 21378 W KeyStore: KeyStore exception
11-02 07:05:52.933 21378 21378 W KeyStore: android.os.ServiceSpecificException:  (code 7)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.os.Parcel.createException(Parcel.java:1956)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:1910)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.os.Parcel.readException(Parcel.java:1860)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.security.KeyStore.get(KeyStore.java:195)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:149)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:118)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:79)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:48)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.createAndStoreSecret(LogSecretProvider.java:48)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:22)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:161)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:101)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.os.Looper.loop(Looper.java:193)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-02 07:05:52.933 21378 21378 W KeyStore: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-02 07:05:52.935  4225  4225 W keymaster2_mdfpp: entered get_key_characteristics function.
11-02 07:05:52.937  4225  4225 W keymaster2_mdfpp: exit get_key_characteristics function, returned 0
11-02 07:05:52.942  4225  4225 W keymaster2_mdfpp: entered get_key_characteristics function.
11-02 07:05:52.944  4225  4225 W keymaster2_mdfpp: exit get_key_characteristics function, returned 0
11-02 07:05:52.944  4225  4225 W keymaster2_mdfpp: entered add_rng_entropy function.
11-02 07:05:52.945  4225  4225 W keymaster2_mdfpp: exit add_rng_entropy function, returned 0
11-02 07:05:52.946  4225  4225 W keymaster2_mdfpp: entered begin function.
11-02 07:05:52.949  4225  4225 W keymaster_tee: [WRN]Returning with error: -30
11-02 07:05:52.949  4225  4225 W keymaster2_mdfpp: exit begin function, returned -30
11-02 07:05:52.959  4225  4225 W keymaster2_mdfpp: entered abort function.
11-02 07:05:52.960  4225  4225 W keymaster_tee: [WRN]Returning with error: -28
11-02 07:05:52.960  4225  4225 W keymaster2_mdfpp: exit abort function, returns -28
11-02 07:05:52.965 21378 21378 D AndroidRuntime: Shutting down VM
11-02 07:05:52.969 21378 21378 E AndroidRuntime: FATAL EXCEPTION: main
11-02 07:05:52.969 21378 21378 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 21378
11-02 07:05:52.969 21378 21378 E AndroidRuntime: java.lang.AssertionError: java.security.InvalidKeyException: Keystore operation failed
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:59)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.createAndStoreSecret(LogSecretProvider.java:48)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:22)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:161)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:101)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: Caused by: java.security.InvalidKeyException: Keystore operation failed
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:901)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.KeyStore.getInvalidKeyException(KeyStore.java:926)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1143)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at javax.crypto.Cipher.init(Cipher.java:1084)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:52)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	... 15 more
11-02 07:05:52.969 21378 21378 E AndroidRuntime: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
11-02 07:05:52.969 21378 21378 E AndroidRuntime: 	... 27 more
11-02 07:05:52.981  4605  7679 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
```

**Comment by cyrill62** [comment]
I think my issue is related on #7731

**Comment by johanw666** [comment]
To let an app crash with an exception - or even worse, an assertion, or to handle it gracefully seems to be a matter of taste among some programmers. I will never use assertions in my code, for no reason. Especially not here, where the reason for the error is usually quite obvious (invalid keystore keys, that could be handled with a neat popup and a closude instead of a deliberate crash). But OWS seems to disagree.

**Comment by jamasi** [comment]
Seems like a really bad practice. the app should at least in form the user of the problem at hand. It would even be better if it would offer some kind of account recovery via that new pin functionality.

**Comment by blueyed** [comment]
I am seeing this issue in v5.30.6 (and 5.31.5), after reinstalling Android, and restoring via backup of the data partition (TWRP).

I've found https://community.signalusers.org/t/wiki-howto-manual-backup-restore-if-full-backup-does-not-work/2462 (by @johanw666), but unfortunately there is no `/data/misc/keystore` in the backup, and no occurrence of "USERKEY_SignalSecret" in the backup's tar files.
I can see the (new?) keystore when using `adb shell` while in TWRP, but for some reason it was not included in the backup.

I will use Signal's backup functionality in the future, but it is unfortunate that there is no better error message, and especially that you have to reset/remove all of its data, and cannot even reconnect it to signal-desktop, can you?

**Comment by alex-signal** [comment]
@blueyed You can totally reconnect to Signal desktop, and you shouldn't lose anything you had on Signal desktop, so long as you're using the same account. I've blown up my install more than once (yay dogfooding) but was able to keep my message history on desktop and relink.
