### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by Radog78** [signalapp/Signal-Android#8250]
Не приходит Смс и звонок с кодом. Республика Беларусь. Опертор МТС, номер перенесён с оператора life +375 25

https://debuglogs.org/1dd8079a8aa9395a8f43b9852419bf9d614debba92352087ba4f335826a4fd56

**Comment by greyson-signal** [comment]
Translated with Google Translate:

> Do not come SMS and call with code. Republic of Belarus. MTS operator, the number was transferred from the life +375 25 operator

Sounds like you may want to check out #8148

**Comment by five-c-d** [comment]
From looking at the debuglog, all I can see is HTTP 413 RateLimitException, I do not think the initial problem was captured.  

```
2018-10-04 15:20:57.072 GMT+03:00 W CreateSignedPreKeyJob: Not yet registered...
2018-10-04 15:20:57.075 GMT+03:00 I Job: [df4f1f1f-7ad0-4c8e-91ed-7fbd7ef1b8c6] CreateSignedPreKeyJob :: Successfully completed. (Time since submission: 5114 ms, Run attempt: 1)
2018-10-04 15:21:09.915 GMT+03:00 I PlayServicesUtil: Play Services: 0
2018-10-04 15:21:09.919 GMT+03:00 I TextSecurePreferences: Setting push registered: false
2018-10-04 15:21:10.655 GMT+03:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2018-10-04 15:21:10.656 GMT+03:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+**********21
2018-10-04 15:21:11.622 GMT+03:00 W RegistrationActivity: Error during account registration 
2018-10-04 15:21:11.622 GMT+03:00 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.RateLimitException: Rate limit exceeded: 413
```

There was this towards the end however, about four hours after the first-listed HTTP 413:  

```
10-04 19:40:26.158 22709 22709 I PlayServicesUtil: Play Services: 0
10-04 19:40:26.168 22709 22760 I TextSecurePreferences: Setting push registered: false
10-04 19:40:26.174 22709 22760 W InstanceID/Rpc: Found 10016
10-04 19:40:26.792 22709 22760 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
10-04 19:40:26.792 22709 22760 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+**********21
10-04 19:40:36.903 22709 22714 I art     : Do partial code cache collection, code=36KB, data=62KB
10-04 19:40:36.904 22709 22714 I art     : After code cache collection, code=36KB, data=62KB
10-04 19:40:36.904 22709 22714 I art     : Increasing code cache capacity to 256KB
10-04 19:41:25.672 22709 22709 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
10-04 19:41:25.672 22709 22709 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
10-04 19:41:25.674 22709 22709 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
10-04 19:41:26.765 22709 22709 I ApplicationContext: App is no longer visible.
10-04 19:41:26.838 22709 22709 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
10-04 19:41:26.839 22709 22709 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
10-04 19:41:36.721 22709 22709 I ApplicationContext: App is now visible.
10-04 19:41:36.895 22709 22709 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
10-04 19:41:39.858 22709 22900 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
10-04 19:41:39.859 22709 22900 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/voice/code/+**********21
10-04 19:42:43.425 22709 22709 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
10-04 19:42:43.426 22709 22709 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
10-04 19:42:45.356 22709 22709 I ApplicationContext: App is no longer visible.
10-04 19:42:46.507 22709 22709 I ApplicationContext: App is now visible.
10-04 19:43:35.905 22709 22994 V Cursor  : Filling cursor window with start position:0 required position:0
10-04 19:43:35.968 22709 22994 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
10-04 19:43:35.968 22709 22994 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/code/528888
10-04 19:43:37.892 22709 22994 W RegistrationActivity: null
10-04 19:43:37.892 22709 22994 W RegistrationActivity: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:757)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:147)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccountWithCode(SignalServiceAccountManager.java:164)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity.verifyAccount(RegistrationActivity.java:697)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity.access$1100(RegistrationActivity.java:108)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$4.doInBackground(RegistrationActivity.java:563)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$4.doInBackground(RegistrationActivity.java:559)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-04 19:43:37.892 22709 22994 W RegistrationActivity: 	at java.lang.Thread.run(Thread.java:760)
10-04 19:43:40.159 22709 22709 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
10-04 19:43:40.774 22709 22709 I ApplicationContext: App is no longer visible.
10-04 19:45:04.695 22709 22709 I PassphraseRequiredActionBarActivity: onCreate(null)
10-04 19:45:04.710 22709 22709 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 4
10-04 19:45:04.713 22709 22709 I Timeline: Timeline: Activity_launch_request time:31312653 intent:Intent { cmp=org.thoughtcrime.securesms/.RegistrationActivity (has extras) }
```

That `AuthorizationFailedException` is HTTP 401 or HTTP 403, <a href="https://github.com/signalapp/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java#L755">per libsignal-service-java code here</a>, and only shows up a couple of times in github recently, one is https://github.com/signalapp/Signal-Android/issues/5363#issuecomment-200461558 where the problem was number-format-related in Argentina, the other was something related to keystore corruption, https://github.com/signalapp/Signal-Android/issues/5551#issuecomment-281120785 , fix was to 

* completely clear app and cache 
* re-register the phone number with signalapp 

However, problems receiving the SMS-or-robocall are known to happen in Belarus, with MTS specifically, and these number-skeletons:    

* +375 29 xxx xxxx
* +375 33 xxx xxxx
* +375 44 xxx xxxx

Probably +375 25 xxx xxxx can be added to the list at #6027 ... generic delays in #7980 is possibly related, but seemingly-Benelux-specific #8148 is probably unrelated.  Is there any <a href="https://en.wikipedia.org/wiki/Censorship_in_Belarus#Internet_censorship">reason to suspect overt censorship</a> of signalapp is happening inside Belarus, at the telco level and/or at the internet level?

**Comment by Notatechdud3** [comment]
Hello, 

I made a topic Signalusers. Maybe it is best to drop all information there as well, so we can have a look at it. 

https://community.signalusers.org/t/registering-in-belarus-all-providers/4827
