### ISSUE TITLE
Signal fails to load after data is corrupted by Android context menu from another app

### ISSUE THREAD

**Issue by twig** [signalapp/Signal-Android#8313]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sharing a link from another app causes Signal's data to corrupt and fail to start.

This is something I have experienced with Signal over many years but have failed to reliably reproduce. It seems to happen at random, but always noticeable during the process of sharing links between apps. Finally got off my ass to get the crash stack trace via Android Studio.

### Steps to reproduce

- (by chance) turn on phone
- using [Reddit Sync](https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync), share a link to a reddit post
- when the [Android share context menu](https://www.androidpolice.com/wp-content/uploads/2016/03/nexus2cee_2016-03-12-15.20.29.png) appears, Signal crashes in the background (but bringing up a report/dismiss dialog in the foreground)

I feel these steps may be a way to reproduce the symptom, not the problem.

I have a strong suspicion that it has something to do with a race condition on boot. Maybe Signal is trying to do something during `android.intent.action.BOOT_COMPLETED` before the Android file system has completely loaded?

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- be able to share links without it affecting Signal
- try to run Signal. it will crash.

uncaught exception is `java.security.InvalidKeyException: Keystore operation failed`

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- can share links between other apps without Signal crashing
- Signal still works

### Screenshots

the initial actions
![screenrecord_2018-10-28-07-08-03 mp4_snapshot_00 02_ 2018 10 28_08 39 49](https://user-images.githubusercontent.com/59689/47609632-51f4a980-da8e-11e8-95b4-f12cd7e2af0a.jpg)

![screenrecord_2018-10-28-07-08-03 mp4_snapshot_00 03_ 2018 10 28_08 40 20](https://user-images.githubusercontent.com/59689/47609633-54ef9a00-da8e-11e8-9b9b-bf5a43a4288d.jpg)

crash as the menu appears, before anything is even shared
![screenrecord_2018-10-28-07-08-03 mp4_snapshot_00 04_ 2018 10 28_08 40 29](https://user-images.githubusercontent.com/59689/47609634-56b95d80-da8e-11e8-9ed3-b3783e9a3499.jpg)

clicking back
![screenrecord_2018-10-28-07-08-03 mp4_snapshot_00 07_ 2018 10 28_08 40 56](https://user-images.githubusercontent.com/59689/47609635-58832100-da8e-11e8-94c5-fc5ad866d2ed.jpg)

another crash
![screenrecord_2018-10-28-07-08-03 mp4_snapshot_00 08_ 2018 10 28_08 41 04](https://user-images.githubusercontent.com/59689/47609637-5c16a800-da8e-11e8-88f4-71b7dc9621ee.jpg)

Signal data is now corrupt and fails to load
![screenrecord_2018-10-28-07-08-03 mp4_snapshot_00 17_ 2018 10 28_08 41 29](https://user-images.githubusercontent.com/59689/47609638-5e790200-da8e-11e8-9be9-6692e82abd20.jpg)

### Device info

**Device:** Sony Z5 Compact
**Android version:** 6.0
**Signal version:** 4.29.7

### Link to debug log

```
? E/AndroidRuntime: FATAL EXCEPTION: main
                    Process: org.thoughtcrime.securesms, PID: 9259
                    java.lang.AssertionError: java.security.InvalidKeyException: Keystore operation failed
                        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:73)
                        at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36)
                        at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
                        at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
                        at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:158)
                        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:99)
                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4804)
                        at android.app.ActivityThread.access$1600(ActivityThread.java:154)
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1450)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:224)
                        at android.app.ActivityThread.main(ActivityThread.java:5514)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                     Caused by: java.security.InvalidKeyException: Keystore operation failed
                        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:696)
                        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:716)
                        at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:53)
                        at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
                        at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:263)
                        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:147)
                        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:608)
                        at javax.crypto.Cipher.tryCombinations(Cipher.java:532)
                        at javax.crypto.Cipher.getSpi(Cipher.java:437)
                        at javax.crypto.Cipher.init(Cipher.java:909)
                        at javax.crypto.Cipher.init(Cipher.java:859)
                        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:69)
                        at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36) 
                        at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21) 
                        at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48) 
                        at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:158) 
                        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:99) 
                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4804) 
                        at android.app.ActivityThread.access$1600(ActivityThread.java:154) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1450) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:224) 
                        at android.app.ActivityThread.main(ActivityThread.java:5514) 
                        at java.lang.reflect.Method.invoke(Native Method) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                     Caused by: android.security.KeyStoreException: Signature/MAC verification failed
                        at android.security.KeyStore.getKeyStoreException(KeyStore.java:636)
                        at android.security.KeyStore.getInvalidKeyException(KeyStore.java:716) 
                        at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:53) 
                        at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89) 
                        at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:263) 
                        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:147) 
                        at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:608) 
                        at javax.crypto.Cipher.tryCombinations(Cipher.java:532) 
                        at javax.crypto.Cipher.getSpi(Cipher.java:437) 
                        at javax.crypto.Cipher.init(Cipher.java:909) 
                        at javax.crypto.Cipher.init(Cipher.java:859) 
                        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:69) 
                        at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36) 
                        at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21) 
                        at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48) 
                        at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:158) 
                        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:99) 
                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014) 
                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4804) 
                        at android.app.ActivityThread.access$1600(ActivityThread.java:154) 
                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1450) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:224) 
                        at android.app.ActivityThread.main(ActivityThread.java:5514) 
                        at java.lang.reflect.Method.invoke(Native Method) 
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by johanw666** [comment]
Keystore error? That is very strange - it means that the encryption key for the Signal database is not in the Android keystore, or the key is invalid. I have really no idea how that can be caused by a link sharing.

**Comment by twig** [comment]
Yeah me neither. It's been plaguing me periodically over the years and finally decided to log a bug about it. Never happens on a fresh install.

As I mentioned, I feel like the sharing thing is a symptom more than the cause as the context menu needs some information from Signal in order to know which contacts to share to.

I'll try to keep this updated as I find more details, but for now it feels very random.

**Comment by johanw666** [comment]
> It's been plaguing me periodically over the years

Years is not possible, Signal uses the Android keystore since the release of 4.16 in spring 2018. That must have been another bug then.

**Comment by greyson-signal** [comment]
Using #8589 as the tracker for this.
