### ISSUE TITLE
Android P Signal Registration GCM issues

### ISSUE THREAD

**Issue by bkerler** [signalapp/Signal-Android#8363]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal Registration fails due to outdated GCM libraries in Android P

### Steps to reproduce
- Install Signal on a new Android P device
- Registration of a new or existing number fails with "No Connection to Services possible" message

**Actual result:**
Device fails to start Connection with Google Play Services: Copied from Debug Log:

RegistrationActivity Java.io.Exception: Authentification Failed com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source:27)

**Expected result:** 
Registration works as expected.

**Recommendation / Solution**
Upgrade to GCM 11 or higher. (The latest is 15.0.1: com.google.android.gms:play-services-gcm:15.0.1), or even better, migrate to FCM. (GCM is now deprecated) (Taken as recommendation from StackOverflow)

### Device info
**Device:** Oneplus 6t
**Android version:** 9.0.0
**Signal version:** 4.29.7

**Comment by bkerler** [comment]
Debug Log:
`11-13 09:52:26.696 16780 28702 I TextSecurePreferences: Setting push registered: false
11-13 09:52:26.709  2370 28385 E GCM     : Missing checkin config file
11-13 09:52:26.709  2370 28385 W GCM     : GCM FAILED TO INITIALIZE - missing checkin
11-13 09:52:26.709 16780 28346 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
11-13 09:52:26.711 16780 28702 W RegistrationActivity: Error during account registration
11-13 09:52:26.711 16780 28702 W RegistrationActivity: java.io.IOException: AUTHENTICATION_FAILED
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source:27)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source:67)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:509)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:498)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-13 09:52:26.711 16780 28702 W RegistrationActivity: 	at java.lang.Thread.run(Thread.java:764)
`
Google play works as expected and is linked to an google account. Also no issues with activation via sms with other apps like whatsapp.

**Comment by bkerler** [comment]
Update: Looks like it's an Oneplus internal bug. If you copy over the files from another phone in the setup process, it doesn't generate a gcm config. So factory wiping the device via recovery and then just use the sim card to setup worked fine.
