### ISSUE TITLE
Crash after some time

### ISSUE THREAD

**Issue by ajudator** [signalapp/Signal-Android#8364]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Signal crashes randomly, after a brief period of time.

### Steps to reproduce
- Click Signal icon
- Type passphrase and unlock the app
- Use it normally (write messages, open conversation, or just let it open in the main screen)

**Actual result:** When using the app as usual - writing messages, reading conversations, waiting for a someone to reply - Signal suddenly crashes and the app is closed, prompting a generic system message: 'Signal has stopped', and the options to open the app again or mute until restart.
**Expected result:** A normal use, as in no random crashing?

### Device info

**Device:** Motorola Moto G (falcon; XT1032)
**Android version:** 7.1.2 (Lineage without google services)
**Signal version:** 4.29.7

### Link to debug log

https://debuglogs.org/2b74e9f6f2970ad20eb7009df308e1e4ae4416c9aa6aa9256e807632e808bdd4

**Comment by greyson-signal** [comment]
Somehow your device got into a situation where it's trying to send a a group message using PushMediaSendJob, which assumes you're sending to a phone number.

```
2018-11-13 12:33:45.911 GMT-02:00 I PushMediaSendJob: Sending message: 12295
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: java.lang.AssertionError: Not e164: __textsecure_group__!16207a5ad2c6a0d7b81c82249858dadb
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:132)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.PushSendJob.getPushAddress(PushSendJob.java:97)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:129)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:83)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:71)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:49)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:75)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at androidx.work.Worker$1.run(Worker.java:95)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2018-11-13 12:33:45.924 GMT-02:00 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:761)
2018-11-13 12:33:45.962 GMT-02:00 I PassphraseRequiredActionBarActivity: onPause()
```

To mitigate this in the meantime, I suggest looking through your recently sent messages and deleting any pending messages (likely a group message). Apparently one of them got into a bad state somehow.

**Comment by ajudator** [comment]
Solved. I believe that really was a pending message, as you said. 

I trimmed all my conversations to ease searching, and then found a group message that wasn't sent successfully. It was chronologically consistent, also, with the beginning of the crashes, and after I deleted it, the app returned to its normal behavior. Thanks!

**Comment by d5xtgr** [comment]
Rather than open a new essentially-duplicate bug report, I'm adding this here:

It is possible to send unencrypted messages to email addresses using Signal.  If you do that, you can then trigger the same failed assertion about e164 from the search bar.  I did this by sending an email to an address beginning with "hani" and then searching for "hang".

The problem in this case appears to be calling `contact.getAddress().toPhoneString()` in `ConversationListItem.bind()`.

**Comment by haffenloher** [comment]
[A forum user reported another occurrence of this today:](https://community.signalusers.org/t/signal-keeps-crashing-while-using-it/8320/5?u=haffenloher)

```
07-06 15:34:46.575  4257  4424 E AndroidRuntime: java.lang.AssertionError: Not e164, is group
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:136)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushSendJob.getPushAddress(PushSendJob.java:109)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:203)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:136)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:85)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:43)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
07-06 15:34:46.575  4257  4424 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
```

**Comment by alan-signal** [comment]
This issue was never really solved. There was just a successful work around.
