### ISSUE TITLE
Unable to send any media over WiFi but I can over mobile data

### ISSUE THREAD

**Issue by rajshrimohanks** [signalapp/Signal-Android#8374]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I'm unable to send any kind of media messages over WiFi. They get stuck with a spinning circle indicating that it's being sent. All subsequent messages get stuck as well. I'm able to receive messages during this ordeal. If I turn off WiFi and switch to mobile data, the queue hers sent and everything goes back to normal.

### Steps to reproduce

- Nokia 6.1 with Android 9.0
- Use the + button to add any media. 
- send message while on WiFi

**Actual result:** 

It should fail to send the message. The status circle keeps spinning endlessly.

**Expected result:**

The message should be sent. The status circle should change to one with a check mark.

### Device info

**Device:** Nokia 6.1
**Android version:** 9.0
**Signal version:** 4.29.7

### Link to debug log
https://debuglogs.org/59f5a0f3eb73ac7f581c4b5a080667010323236b1a94f3ddaf2fbc90fa15960d

**Comment by greyson-signal** [comment]
So I'm seeing these logs, which are a form of generic network error:

```java
2018-11-16 08:42:18.594 IST I Job: [3b492d07-646e-4aee-aa34-0427210eedab] PushMediaSendJob :: Retrying after a retryable exception. (Time since submission: 32017 ms, Run attempt: 0)
2018-11-16 08:42:18.594 IST I Job: org.thoughtcrime.securesms.transport.RetryLaterException: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@ba51a948
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:156)
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.onPushSend(PushMediaSendJob.java:83)
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:71)
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:49)
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:75)
2018-11-16 08:42:18.594 IST I Job: 	at androidx.work.Worker$1.run(Worker.java:95)
2018-11-16 08:42:18.594 IST I Job: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2018-11-16 08:42:18.594 IST I Job: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2018-11-16 08:42:18.594 IST I Job: 	at java.lang.Thread.run(Thread.java:764)
2018-11-16 08:42:18.594 IST I Job: Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@ba51a948
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
2018-11-16 08:42:18.594 IST I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:610)
2018-11-16 08:42:18.594 IST I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:357)
2018-11-16 08:42:18.594 IST I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointer(SignalServiceMessageSender.java:711)
2018-11-16 08:42:18.594 IST I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createAttachmentPointers(SignalServiceMessageSender.java:692)
2018-11-16 08:42:18.594 IST I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.createMessageContent(SignalServiceMessageSender.java:290)
2018-11-16 08:42:18.594 IST I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:164)
2018-11-16 08:42:18.594 IST I Job: 	at org.thoughtcrime.securesms.jobs.PushMediaSendJob.deliver(PushMediaSendJob.java:147)
2018-11-16 08:42:18.594 IST I Job: 	... 9 more
2018-11-16 08:42:18.594 IST I Job: Caused by: java.io.EOFException: \n not found: size=0 content=...
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
2018-11-16 08:42:18.594 IST I Job: 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
2018-11-16 08:42:18.594 IST I Job: 	... 24 more
```

This actually looks very similar to #8365. Similar enough that I'm going to consider this the same issue close this as a dupe. 

I wonder if this is a device-specific problem? #8365 is also a Nokia 6.1 running Android 9.0. Did you also just recently get the 9.0 upgrade? I wonder if there's something funny in their software update...
