### ISSUE TITLE
Can't Update My Profile Photo "problem setting profile"

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [signalapp/Signal-Android#8378]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
every time i try to change my profile photo i get "problem setting profile .

### Steps to reproduce
- open "Your Profile Info" menu
- upload your photo
- click on ""FINISH"

**Actual result:** i get problem setting profile 
**Expected result:** the photo upload & change

### Screenshots
![screenshot_20181116-235447](https://user-images.githubusercontent.com/28893833/48649425-76d3a100-e9ea-11e8-8929-bbe9e76e84cf.png)

### Device info
**Device:** VFD 301
**Android version:** 6.0.0
**Signal version:** 4.29.7

### Link to debug log
https://debuglogs.org/f95423f5c39cdcb2f70dbc6dd89bd1526198277115c7c9d51b39b2e1aa1b720f

**Comment by Pratiwir** [comment]
I had the same problem. I found that rebooting the phone enabled signal to upload the profile image. I am using Signal 4.31.6, Android 4.1.2 on a GT-I9082 phone.
I suspected that the reboot would work as voice notes often won't play on signal. After the reboot the same file will play. 
The history is this. I was running low on available free memory and then decided to limit chats to 500 messages. This cleared a lot of space and now I have about 398 MB free. Unfortunately that didn't stop the problem though, as after exchanging a few voice notes and photos I still get the same problem with audio not playing and have to reboot. I don't know if this is an Android problem or one with Signal, however, another new Android 8 phone also suffers the same problem with audio not playing in Signal, and then requires a reboot.
Another problem is that I can't upload the debug log, I get a 'server error' each time.
I think that there needs to be more focus on problems when something fails to play or fails to upload, better on screen diagnostics and somewhere to report it.
- This is literally the third attempt at uploading the comment using Firefox on the same phone.

**Comment by EsmailELBoBDev2** [comment]
well, i tried restart my phone but everything is same & i tried to call the support team but no one replied so i stopped using this app

**Comment by Pingmin** [comment]
I had this problem too sometimes. It's maybe by the network.

**Comment by alan-signal** [comment]
@Pingmin can we have the logs please, Settings->Advanced->Submit Debug logs

**Comment by Pingmin** [comment]
@alan-signal https://debuglogs.org/0c15196f88d39b9d38faac0bda04cc8f8d0a32b986bdcc1ee133779ed3e93eb2

**Comment by alan-signal** [comment]
Thanks @Pingmin 

Just copying the relevant parts here:

```
========== SYSINFO ========

Time    : 1562474827322
Device  : Xiaomi MI 2SC (aries)
Android : 5.0.2 (V9.2.3.0.LXACNEK, LRX22G)
ABIs    : armeabi-v7a, armeabi
Memory  : 34M (2.98% free, 256M max)
Memclass: 96
OS Host : c3-miui-ota-bd46.bj
App     : Signal 4.41.6 (4945)
```

```
/UncaughtExceptionLogger(32598): Caused by: java.lang.AssertionError: java.security.InvalidAlgorithmParameterException: Required GCMParameterSpec
E/UncaughtExceptionLogger(32598): 	at org.whispersystems.signalservice.api.crypto.ProfileCipherOutputStream.(ProfileCipherOutputStream.java:31)
E/UncaughtExceptionLogger(32598): 	at org.whispersystems.signalservice.internal.push.http.ProfileCipherOutputStreamFactory.createFor(ProfileCipherOutputStreamFactory.java:20)
E/UncaughtExceptionLogger(32598): 	at org.whispersystems.signalservice.internal.push.http.DigestingRequestBody.writeTo(DigestingRequestBody.java:43)
E/UncaughtExceptionLogger(32598): 	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
E/UncaughtExceptionLogger(32598): 	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/UncaughtExceptionLogger(32598): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/UncaughtExceptionLogger(32598): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
E/UncaughtExceptionLogger(32598): 	at okhttp3.RealCall.execute(RealCall.java:92)
```

**Comment by Pingmin** [comment]
Yes, that's it!

**Comment by Pingmin** [comment]
This is also for Signal 4.43.8 (5075):

https://debuglogs.org/0791210835bd58d2e81d47c8e1f703f6a5ffa9ce8c136ba78e18bcda64f5cdaa

```
2019-07-10 22:38:51.760 GMT+08:00 I ApplicationContext: App is no longer visible.
2019-07-10 22:38:51.761 GMT+08:00 I KeyCachingService: Starting timeout: 300000
2019-07-10 22:38:58.873 GMT+08:00 I ApplicationContext: App is now visible.
2019-07-10 22:39:09.350 GMT+08:00 I BitmapUtil: Initial scaled bitmap has size of 1638400 bytes.
2019-07-10 22:39:09.351 GMT+08:00 I BitmapUtil: Max dimensions 640 x 640, 5242880 bytes
2019-07-10 22:39:09.353 GMT+08:00 I KeyboardAwareLinearLayout: onKeyboardClose()
2019-07-10 22:39:09.382 GMT+08:00 D BitmapUtil: iteration with quality 90 size 44492 bytes.
2019-07-10 22:39:09.383 GMT+08:00 I BitmapUtil: createScaledBytes(android.net.Uri$HierarchicalUri) -> quality 85, 1 attempt(s) over 1 sizes.
2019-07-10 22:39:11.009 GMT+08:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-07-10 22:39:11.009 GMT+08:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/profile/name/GBR3nQjX0VzDG9rUuHEK8ZOozqPzFiwatlv6LMEwfrdZsNcs8afEhPUJy5O%2F7zSbNIbIuNag
2019-07-10 22:39:11.406 GMT+08:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-07-10 22:39:11.407 GMT+08:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/profile/form/avatar
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: java.lang.RuntimeException: An error occured while executing doInBackground()
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:818)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: Caused by: java.lang.AssertionError: java.security.InvalidAlgorithmParameterException: Required GCMParameterSpec
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherOutputStream.<init>(ProfileCipherOutputStream.java:31)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.internal.push.http.ProfileCipherOutputStreamFactory.createFor(ProfileCipherOutputStreamFactory.java:20)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.internal.push.http.DigestingRequestBody.writeTo(DigestingRequestBody.java:43)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at okhttp3.RealCall.execute(RealCall.java:92)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:744)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.setProfileAvatar(PushServiceSocket.java:497)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.setProfileAvatar(SignalServiceAccountManager.java:413)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.CreateProfileActivity$7.doInBackground(CreateProfileActivity.java:376)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.CreateProfileActivity$7.doInBackground(CreateProfileActivity.java:361)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	... 3 more
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: Caused by: java.security.InvalidAlgorithmParameterException: Required GCMParameterSpec
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.signal.aesgcmprovider.AesGcmCipher.engineInit(AesGcmCipher.java:112)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at javax.crypto.Cipher.init(Cipher.java:751)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at javax.crypto.Cipher.init(Cipher.java:701)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	at org.whispersystems.signalservice.api.crypto.ProfileCipherOutputStream.<init>(ProfileCipherOutputStream.java:27)
2019-07-10 22:39:15.096 GMT+08:00 E UncaughtExceptionLogger: 	... 29 more
2019-07-10 22:39:16.457 GMT+08:00 I IncomingMessageObserver: Waiting for websocket state change....
2019-07-10 22:39:16.706 GMT+08:00 D IncomingMessageObserver: Network requirement: true, app visible: false, gcm disabled: true
2019-07-10 22:39:16.707 GMT+08:00 I IncomingMessageObserver: Making websocket connection....
2019-07-10 22:39:16.708 GMT+08:00 W WebSocketConnection: WSC connect()...
```

**Comment by alan-signal** [comment]
Thanks @Pingmin we have a solution now, we just have to wait for 4.44 to be released.

**Comment by Pingmin** [comment]
OK. Thank you too and hope soon!

**Comment by Pingmin** [comment]
@alan-signal The latest Signal v4.44.7 works well for profile image on my phone now.

**Comment by EsmailELBoBDev2** [comment]
Wow this kinda late to report, but it seems working fine now

Thanks

**Comment by ashbk37** [comment]
The problem has appeared again now.[](https://debuglogs.org/705e6efb9b0804055fbb66ef34dd4bcaa44a3d91d4838fa9b523f31adb82f7d9)

**Comment by IamMarcIvanov** [comment]
I am also having the same problem. Although it failed only while uploading an image for the profile of a group. I tried it for my own image and it worked just fine. Restarting the phone did not make a difference. I am using Signal 5.2.3 and am on Android 10.

**Comment by Angelluc** [comment]
Yes same here on my iPhone. Try to upload a profile photo (haven't one yet) but when I click a photo in my photo library it just returns to the settings page and nothing happens or has happened. Tried .jpg and .png. Also rebooted my phone but no luck. And on my Mac I am not able to change my profile picture so no way to put one.

**Comment by spagy** [comment]
Just had the same issue, also with a group on version 5.29.7. Trying for the third time (with the same image) it worked.

**Comment by cody-signal** [comment]
If you're still encountering the issue, an updated debuglog would be helpful in figuring out what's up.

**Comment by EsmailELBoBDev2** [comment]
I can't believe this issue is still alive 😂

Good luck to whomever is facing this issue! because I use xmpp after signal added crypto support :stuck_out_tongue:

**Comment by spagy** [comment]
@cody-signal here's a log from fairly soon after the issue https://debuglogs.org/21000cad7cdb0120135271fe272dbe9fe703bafbb06b2fda680fdf8315188f78 although i don't know whether it's helpful as it's giving me an internal server error.

here's one from a bit later that isn't giving an internal server error: https://debuglogs.org/34e43321ee6e959333162501f0a80c9b7f3964f1339ae000492a189bd938a7fe.
