### ISSUE TITLE
Non-Google Play device experiences broadcast receiver exception.

### ISSUE THREAD

**Issue by greyson-signal** [signalapp/Signal-Android#8402]
Creating on behalf of @scytho via #8365.

### Bug description
Device fails to send messages, likely due to an issue with `RealtimeSleepTimer$AlarmReceiver` not being registered.

```java
2018-11-27 11:12:45.322 MEZ W WebSocketConnection: java.lang.IllegalArgumentException: Receiver not registered: org.whispersystems.signalservice.api.util.RealtimeSleepTimer$AlarmReceiver@b334c6e
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1193)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1449)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:645)
	at org.whispersystems.signalservice.api.util.RealtimeSleepTimer.sleep(RealtimeSleepTimer.java:51)
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection$KeepAliveSender.run(WebSocketConnection.java:320)
```

### Device info
Device: Sony Xperia Z1 Compact (D5503)
Android: 8.1.0 (3485e188fa, aicp_amami-userdebug 8.1.0 OPM2.171026.006.H1 3485e188fa test-keys)
App: Signal 4.30.7

### Link to debug log
https://debuglogs.org/f9d5b29e5e3ffaec5d28ddf354f21f5d0b4a1d4896dcc61eb71cd42830d4cf64

**Comment by scytho** [comment]
I just disabled AFWall+, now sending a message worked right away. See this post, too:
https://github.com/signalapp/Signal-Android/issues/8365#issuecomment-442573759

**Comment by greyson-signal** [comment]
Same root bug, but here it looks to be possibly causing battery issues:
https://github.com/signalapp/Signal-Android/issues/8217#issuecomment-443442441

**Comment by floogit** [comment]
Just a short notice to confirm that the battery drainage continues to be a problem on the latest 4.34.8 version of signal (Lineageos 14.1, Android 7.1.2, no GAPPS, still throwing a WebSocketConnection exception).

**Comment by five-c-d** [comment]
Forum thread, if people that are running LineageOS or other non-GApps builds are interested in trying to test and correct the "Receiver not registered" error-message that is linked to heavy battery drain:  https://community.signalusers.org/t/very-high-battery-drain-on-4-34-8-without-google-play-services/6536
