### ISSUE TITLE
Error playing audio

### ISSUE THREAD

**Issue by Edu4rdSHL** [signalapp/Signal-Android#8487]
- [x] I have searched open and closed issues for duplicates - there are a lot of "Error playing audio" but my issue is for the latest Signal beta version.
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal says "Error playing audio" when playing a audio.

### Steps to reproduce
- Receive an audio.
- Try to listen it.

**Actual result:** Signal says "Error playing audio"
**Expected result:** Signal play audio.

### Screenshots

Not needed.

### Device info

**Device:** Samsung SM-G610M
**Android version:** 8.1.0
**Signal version:** 4.31.6 

### Link to debug log

https://debuglogs.org/d13d763ba1d21af27be1dda7609f81c0d5245eb3e99c53cc624be9cbaebb8561

**Comment by greyson-signal** [comment]
Interesting, looks like there was an interesting media-specific error.

```java
12-25 00:06:01.307 11969 32563 E LoadTask: Unexpected exception handling load completed
12-25 00:06:01.307 11969 32563 E LoadTask: java.lang.NullPointerException
12-25 00:06:01.307 11969 32563 E LoadTask: 	at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:111)
12-25 00:06:01.307 11969 32563 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod.onLoadCompleted(ExtractorMediaPeriod.java:504)
12-25 00:06:01.307 11969 32563 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod.onLoadCompleted(ExtractorMediaPeriod.java:57)
12-25 00:06:01.307 11969 32563 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:450)
12-25 00:06:01.307 11969 32563 E LoadTask: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-25 00:06:01.307 11969 32563 E LoadTask: 	at android.os.Looper.loop(Looper.java:164)
12-25 00:06:01.307 11969 32563 E LoadTask: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: Source error.
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: null
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:454)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:164)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: Caused by: java.lang.NullPointerException
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:111)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod.onLoadCompleted(ExtractorMediaPeriod.java:504)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod.onLoadCompleted(ExtractorMediaPeriod.java:57)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:450)
12-25 00:06:01.313 11969 32563 E ExoPlayerImplInternal: 	... 3 more
```

Does this happen for all media, or only a specific item(s)? If it's easily reproducible, can you upload a sample?

**Comment by greyson-signal** [comment]
(Sorry, the close was accidental)

**Comment by davidak** [comment]
I get this error after playing some audio messages. Then i can't play any until i kill the app and restart it.

This is really annoying and happens every day when i use Signal. It's a reason not to use and recommend Signal!
