### ISSUE TITLE
crash on startup after Android upate to 8.1 java.security.InvalidKeyException

### ISSUE THREAD

**Issue by derMart** [signalapp/Signal-Android#8490]
Hi, Signal always crashes on startup for a user, after the phone updated to Android 8.1
Here is the interesting part of the logcat output:

```
12-25 11:30:38.315   479   479 D keystore: Unable to read cached characteristics for key
12-25 11:30:38.325   310   310 D tkcore-teec: Function returns with [-53135]
12-25 11:30:38.326   310   310 E KeymasterHAL: module.cpp:266: Invoke command failed with 0xffff3071, orig 0x00000004
12-25 11:30:38.326   310   310 E KeymasterHAL: module.cpp:1642: Return -49
12-25 11:30:38.331   310   310 E KeymasterHAL: module.cpp:1960: Abort return -28
12-25 11:30:38.331   310   310 E KeymasterHAL: module.cpp:1954: Return -28
12-25 11:30:38.338 14616 14616 D AndroidRuntime: Shutting down VM
12-25 11:30:38.340 14616 14616 E AndroidRuntime: FATAL EXCEPTION: main
12-25 11:30:38.340 14616 14616 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 14616
12-25 11:30:38.340 14616 14616 E AndroidRuntime: java.lang.AssertionError: java.security.InvalidKeyException: Keystore operation failed
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:73)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:175)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:105)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5767)
12-25 11:30:38.340 14616 14616 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
```
What could be the cause of this corruption?
Possible related to https://github.com/signalapp/Signal-Android/issues/8313 ?
Is there any possibility to extract (/ save / transfer to new installation) the message history and attachments in this case (no backup present)?

Thanks alot

### Device info

**Device:** Siemens Gigaset
**Android version:** 8.1
**Signal version:** 4.31.6

**Comment by johanw666** [comment]
It seems that update trashed the Android keystore. Is it LineageOS, which is known to have done that in the past? I'm affraid that without a backup your messages are lost.

**Comment by greyson-signal** [comment]
Hi there, I'm sorry this happened. @johanw666 is correct.

**Comment by 1u** [comment]
same here, but I have an old signal and adb backup. does this help re-accessing the signal-db?

**Comment by johanw666** [comment]
I never tried adb backup (no need, I don't buy devices I can't root) but if you can access the keystore files in that backup you could try thisprocedure (no guarantees): https://community.signalusers.org/t/howto-manual-backup-restore-if-full-backup-does-not-work/2462

**Comment by 1u** [comment]
@johanw666 :ok_hand: thx, I'll give it a try. I even still have the old phone I migrated from so I should be able to get the key from there, right?
