### ISSUE TITLE
Not Detecting Newly Joined Contact

### ISSUE THREAD

**Issue by Xashyar** [signalapp/Signal-Android#8496]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can only send Secure Signal Messages to a newly joined contact from Desktop. Android detects it as Non-Signal Contact. Although it shows chat history.

### Steps to reproduce
- Ask one of your existing contacts to join signal
- see you can only send Secure Signal Messages from Desktop

### Screenshots
![signal-attachment-2018-12-29-192947](https://user-images.githubusercontent.com/34171942/50540138-6a259980-0ba1-11e9-8e37-d6b93b3063a8.png)

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 4.31.6

### Link to debug log

https://debuglogs.org/2b2f28bda8aa1edd862ef9c519a031ff247c4b49c9ebb2cce9419426e252bacb

**Comment by Xashyar** [comment]
**Calls Ring When The Contact is offline:**
after a while the contact ([Redacted]457) is shown as a regular contact. but Calls to this contact always get Ringing even if the contact is Offline.

**Comment by greyson-signal** [comment]
Interesting, fwiw I saw a bunch of interesting errors saying that you were unable to resolve Signal's hostname:

```java
2018-12-29 18:20:19.718 GMT+03:30 I Job: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.UnknownHostException: Unable to resolve host "textsecure-service.whispersystems.org": No address associated with hostname
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getServiceConnection(PushServiceSocket.java:897)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:762)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:756)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:222)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:172)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.pullAndProcessMessages(PushNotificationReceiveJob.java:60)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobs.PushNotificationReceiveJob.onRun(PushNotificationReceiveJob.java:55)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWorkInternal(Job.java:99)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:65)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at androidx.work.Worker$1.run(Worker.java:57)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
2018-12-29 18:20:19.718 GMT+03:30 I Job: 	at java.lang.Thread.run(Thread.java:818)
```

Do you have a firewall either on your device or on your local network?

Also, when you say:

> after a while the contact ([Redacted]457) is shown as a regular contact. 

Are you saying that your contact is now recognized as having Signal? Did you recall if this happened after you were on a different network?

> Calls to this contact always get Ringing even if the contact is Offline.

Can you elaborate here? There's two types of ringing -- one is a type of sonar beep that means we're trying to connect to the other user. If we establish a connection, we move to a more traditional phone ring noise that means the user is now being notified of the call.

**Comment by Xashyar** [comment]
> Do you have a firewall either on your device or on your local network?

No firewall whatsoever, it could be a ISP/Carrier thing.

Are you saying that your contact is now recognized as having Signal? 

Yes.

Did you recall if this happened after you were on a different network?

I think I was on the same network Both before and after the contact was recognized.

> Can you elaborate here? There's two types of ringing -- one is a type of sonar beep that means we're trying to connect to the other user. If we establish a connection, we move to a more traditional phone ring noise that means the user is now being notified of the call.

The traditional ring noise, indeed, and I was surprised after I found out that the contact didn't even have a network connection while ringing, although I will try to reproduce and post logs if successful.

(feels like an FBI kind of Q&A :D)

**Comment by Xashyar** [comment]
Re-Experiencing the issue on **4.45.2**, with Corresponding contact's no. ending with 112

https://debuglogs.org/4a1450724cff15c348752385c1b8382fbc1f3459bc944fca7d569f33a2e8dbd2

![signal-attachment-2019-08-09-173502](https://user-images.githubusercontent.com/34171942/62781010-3d891700-bacc-11e9-9a7f-fe377fd6d1df.jpeg)

**Comment by Xashyar** [comment]
> Do you have a firewall either on your device or on your local network?

@greyson-signal, I also tried using VPN to bypass any potential blocks, but the problem persists.

**Comment by Xashyar** [comment]
> Do you have a firewall either on your device or on your local network?

@greyson-signal, I also tried using VPNs to bypass any potential blocks and Marked as Verified the corresponding contact, but the problem persists.
