### ISSUE TITLE
Unable to Connect to service during registeration

### ISSUE THREAD

**Issue by gppixelworks** [signalapp/Signal-Android#8502]
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After entered my mobile number and tapping to register Signal immediately returned the ‘Unable to Connect to service…’ error. There were no firewall log entries indicating Signal attempted to access the 'Net.

Signal had been installed without difficulty months ago. Updated ROM required reinstall of Signal.

### Steps to reproduce
1) Uninstalled & reinstalled.
2) Uninstalled, stopped & disabled Google Play Services
     a) Installed Signal & registered mobile number
     b) Re-enabled Google Play Services

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

1) Upon registering mobile number Signal returned: ‘Unable to Connect to service…’
2) Mobile number registered, Signal continues to function in fallback mode.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Expected Signal to connect and register mobile number.

### Device info

**Device:** Motorola XT1524 (Moto E LTE (2nd gen))
**Android version:** 7.1.2
**Signal version:** 4.31.6
Lineage (surnia) 14.1 (Am aware it's not officially supported but noticed others with this problem)

### Link to debug log

https://debuglogs.org/7b957156888c70a971c7f1e499155b4616f0e3942f2291617708bb9d6e9d25c1

**Comment by greyson-signal** [comment]
I'm assuming this has something to do with your configuration of Google Play Services. It looks like we're trying and failing to register a GCM token. 

```java
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: java.io.IOException: AUTHENTICATION_FAILED
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:509)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at org.thoughtcrime.securesms.RegistrationActivity$3.doInBackground(RegistrationActivity.java:498)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-01-03 14:17:56.833 GMT+00:00 W RegistrationActivity: 	at java.lang.Thread.run(Thread.java:761)
```

We'd only do this if we detect you have Google Play Services available. So I'm assuming you're in some weird intermediate state where the system thinks you have Google Play Services, but it's not fully working.

Given the number of possible configurations in this scenario, I can't give you specific advice. I'd suggest heading over to the [forum](https://community.signalusers.org/) where people might be able to give you more specific advice. Thanks!

**Comment by varkhan** [comment]
Simple method to solve this bug: uninstall Signal, use Telegram.
