### ISSUE TITLE
Signal can't cope with some group messages

### ISSUE THREAD

**Issue by poetnerd** [signalapp/Signal-Android#8535]
I saw this description of the problem and it exactly matches mine.

With version 4.31.8 on a Samsung Galaxy S4. I have exactly this same problem.

As soon as I quit using signal, and switched to the default messaging App, I got the group message just fine.

FOLLOW-UP:

After growing tired of the endless automatic attempts to resend the failed MMS messages to my phone's Signal app, I switched my default messaging app back to the OEM messenger application. This cleared the queue of the residual messages, which were part of a group text a contact of mine initiated. They were not media messages, but apparently group texts are sent as MMS messages, and Signal was unable to process slightly more than half of them, setting up the endless cycle of repeat-send-attempts.

I am a caveman mechanical engineer who can't code his way out of a paper bag regardless of its moisture content, but perhaps a future release of Signal could address this, please?

_Originally posted by @autojim in https://github.com/signalapp/Signal-Android/issues/6234#issuecomment-281145831_

**Comment by poetnerd** [comment]
Here is the debug log from the group text message that would not download.  Hope it helps getting this particular manifestation of the broad MMS download failures fixed.
https://debuglogs.org/a810601e11e501b339fee238d1f25f38c870bf36ff4fe40af81d3baaa68a83fb

**Comment by five-c-d** [comment]
Starting-point in the code which is hitting the timeout is here == https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/mms/IncomingLollipopMmsConnection.java#L89 if anyone wishes to have a look 

```
18:08:10.713 D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
18:08:10.721 D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
```

However, even before that point, I have a more fundamental question, though, which is why the mcc=311 mnc=480 lookup is returning the mcc=310 mnc=000 result, is that the right URL even?  I could not figure out where signalapp is getting their APN info from, but here is an online listing which seems related from the android codebase == https://android.googlesource.com/device/sample/+/master/etc/apns-full-conf.xml 

```
<apn carrier="Verizon CDMA HRPD" 
mcc="310" mnc="000" 
mmsc="http://mms.vzwreseller.com/servlets/mms" 
type="default,mms,hipri,dun,supl" mvno_type="spn" 
mvno_match_data="Tracfone" authtype="3" />

<apn carrier="Verizon" carrier_id = "1839"
mcc="311" mnc="480"
apn="internet" authtype="3"
type="default,mms,supl,fota,cbs"
mmsc="http://mms.vtext.com/servlets/mms"
protocol="IPV4V6" bearer_bitmask="4|5|6|7|8|12"
user_visible="false" />
```

First of those URLs is what signalapp *seems* to be using with mcc311 mnc480, second URL is what it ought to be using, methinks.  Does signal4android need to update the APN list it is using, or is the problem with the lookup-function somehow messing up?  https://github.com/signalapp/Signal-Android/blob/master/src/org/thoughtcrime/securesms/database/ApnDatabase.java#L135  Or am I just looking at the wrong android file, for the data above? 

Debuglog shows Android 5.0.1 on Samsung SCH-I545 (jfltevzw).  All lines are 2019-01-17 EST, excerpts only.  Main problem is HTTP 500 error from mms.vzwreseller.com (i.e. some Verizon MVNO methinks?) leading to java.io.IOException ... causes attempted fallback to Lollipop API, but this also fails with java.util.concurrent.TimeoutException  

```
18:08:08.296 I MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
18:08:09.808 I MmsDatabase: Message received type: 130
18:08:10.683 I MmsDownloadJob: Downloading mms at 69.78.88.6, subscription ID: -1
18:08:10.687 I CompatMmsConnection: Receiving via legacy API
18:08:10.713 D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
18:08:10.721 D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }

18:08:10.885 I MmsRadio: Connected: [type: MOBILE[LTE] - MOBILE_MMS, state: CONNECTED/CONNECTED, reason: connected, extra: VZWAPP, roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
18:08:10.900 I IncomingLegacyMmsConnection: got successful route to host 69.78.88.6
18:08:12.904 I LegacyMmsConnection: * response code: HTTP/1.1 200 OK
18:08:13.058 I OutgoingLegacyMmsConnection: Sending MMS of length: 34, using mms radio

18:08:53.851 I MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
18:08:54.742 I MmsDownloadJob: Downloading mms at 69.78.88.6, subscription ID: -1
18:08:54.743 I CompatMmsConnection: Receiving via legacy API
18:08:54.873 D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
18:08:54.901 D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
18:08:55.018 I IncomingLegacyMmsConnection: got successful route to host 69.78.88.6
18:08:55.630 I MmsDatabase: Message received type: 130
18:09:11.240 EST I LegacyMmsConnection: * response code: HTTP/1.1 500 Internal Server Error
18:09:11.251 EST W IncomingLegacyMmsConnection: null
18:09:11.251 EST W IncomingLegacyMmsConnection: java.io.IOException: unhandled response code
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.execute(LegacyMmsConnection.java:208)
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLegacyMmsConnection.retrieve(IncomingLegacyMmsConnection.java:121)
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLegacyMmsConnection.retrieve(IncomingLegacyMmsConnection.java:96)
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:87)
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:140)
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.Job.doWorkInternal(Job.java:99)
18:09:11.251 W IncomingLegacyMmsConnection: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:65)
18:09:11.251 W IncomingLegacyMmsConnection: 	at androidx.work.Worker$1.run(Worker.java:57)
18:09:11.251 W IncomingLegacyMmsConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
18:09:11.251 W IncomingLegacyMmsConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
18:09:11.251 W IncomingLegacyMmsConnection: 	at java.lang.Thread.run(Thread.java:818)

18:09:17.291 EST I MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
18:09:17.452 EST I MmsDatabase: Message received type: 130
18:09:27.614 EST I LegacyMmsConnection: * response code: HTTP/1.1 500 Internal Server Error
18:09:27.818 EST I MmsRadio: MMS Radio Disconnect Called...
18:09:27.823 EST W CompatMmsConnection: null
18:09:27.823 EST W CompatMmsConnection: java.io.IOException: unhandled response code
18:09:27.840 EST I CompatMmsConnection: Falling back to receiving via Lollipop API
18:09:28.147 EST I IncomingLollipopMmsConnection: downloading multimedia from http://69.78.88.6/servlets/mms?message-id=03A5E2EC1BD500000750000403 to content://org.thoughtcrime.provider.securesms.mms/mms/1547766568143

18:10:28.129 EST I MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
18:10:28.454 EST I MmsDatabase: Message received type: 130
18:10:29.724 EST W IncomingLollipopMmsConnection: null
18:10:29.724 EST W IncomingLollipopMmsConnection: java.util.concurrent.TimeoutException: timeout when waiting for MMS
18:10:29.724 EST W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
18:10:29.724 EST W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:89)
18:10:29.724 EST W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:95)
18:10:29.724 EST W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:140)
18:10:29.795 EST W MmsDownloadJob: org.thoughtcrime.securesms.mms.MmsException: java.util.concurrent.TimeoutException: timeout when waiting for MMS

18:11:08.454 EST I MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
18:11:09.489 EST I MmsDownloadJob: Downloading mms at 69.78.88.6, subscription ID: -1
18:11:09.497 EST I CompatMmsConnection: Receiving via legacy API
18:11:09.593 EST D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
18:11:09.594 EST D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
18:11:09.602 EST I IncomingLegacyMmsConnection: got successful route to host 69.78.88.6
18:11:10.146 EST I MmsDatabase: Message received type: 130
18:11:10.993 EST I LegacyMmsConnection: * response code: HTTP/1.1 200 OK
18:11:11.054 EST D ApnDatabase: Querying table for MCC+MNC 311480 and APN name VZWAPP
18:11:11.072 EST D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
18:11:11.074 EST I OutgoingLegacyMmsConnection: Sending MMS of length: 34, using mms radio
18:11:11.307 EST I OutgoingLegacyMmsConnection: got successful route to host mms.vzwreseller.com
18:11:11.923 EST I LegacyMmsConnection: * response code: HTTP/1.1 200 OK
18:11:11.964 EST I MmsRadio: MMS Radio Disconnect Called...
18:11:12.011 EST D AttachmentDatabase: insertParts(0)

18:11:14.152 EST I MmsDownloadJob: Downloading mms at 69.78.64.23, subscription ID: -1
18:11:14.158 EST I CompatMmsConnection: Receiving via legacy API
18:11:14.160 EST D ApnDatabase: Querying table for MCC+MNC 311480 without APN name
18:11:14.162 EST D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
18:11:14.212 EST I IncomingLegacyMmsConnection: got successful route to host 69.78.64.23
18:11:14.556 EST I LegacyMmsConnection: * response code: HTTP/1.1 200 OK
18:11:14.572 EST D ApnDatabase: Querying table for MCC+MNC 311480 and APN name VZWAPP
18:11:14.573 EST D ApnDatabase: Returning preferred APN Apn{ mmsc: "http://mms.vzwreseller.com/servlets/mms", proxy: none, port: (none), user: none, pass: none }
18:11:14.574 EST I OutgoingLegacyMmsConnection: Sending MMS of length: 34, using mms radio
18:11:14.688 EST I LegacyMmsConnection: requestRouteToHostAddress(mms.vzwreseller.com/198.224.174.182) -> true
18:11:15.103 EST I LegacyMmsConnection: * response code: HTTP/1.1 200 OK
18:11:15.127 EST I LegacyMmsConnection: Received full server response, 0 bytes
18:11:15.145 EST D AttachmentDatabase: insertParts(0)


18:25:44.588 EST I LegacyMmsConnection: * response code: HTTP/1.1 500 Internal Server Error

18:26:01.214 EST I LegacyMmsConnection: * response code: HTTP/1.1 500 Internal Server Error

18:26:01.474 EST I CompatMmsConnection: Falling back to receiving via Lollipop API
18:27:01.517 EST W IncomingLollipopMmsConnection: java.util.concurrent.TimeoutException: timeout when waiting for MMS
```

**Possibly** related == 

* https://github.com/signalapp/Signal-Android/issues/4131#issuecomment-195611961 "IOException is a checked exception, so it can't be thrown from LegacyMmsConnection.send() unless it is declared, which it is not."  [but eventually problem was patched] 
* https://github.com/signalapp/Signal-Android/issues/4131 "can send MSS / picture messages fine using the default android messaging application. I cannot send them using TextSecure 2.27.2, Device : motorola Nexus 6 (shamu).  Android : 5.1.1 (2168849, LVY48F).  LegacyMmsConnection... connecting to http://mms.sprintpcs.com ... response code: HTTP/1.1 401 Authorization Required ... OutgoingLegacyMmsConnection ... java.io.IOException: unhandled response code" <br /><br />
* https://github.com/signalapp/Signal-Android/issues/6234#issuecomment-304178716 and https://gist.github.com/anonymous/934cc665053bbe90ac05b288e9cae210 , Android 7.1.2 on Huawei Nexus 6P (angler) Signal 4.6.1 == 
2017-05-25 19:55:58.977 17021 17043 W IncomingLollipopMmsConnection: java.util.concurrent.TimeoutException 
2017-05-25 19:55:58.978 17021 17043 W CompatMmsConnection: mms.MmsException: timeout when waiting for MMS 
2017-05-25 19:55:58.979 17021 17043 W MmsDownloadJob: IOException: lollipop and fallback APIs failed... <br /><br />

**Unclear** if related == 

* https://github.com/signalapp/Signal-Android/issues/5134  , Verizon MMS Retrieval Extremely Slow ... fixed by changing the APN database and tweaking the MMS-related codebase  [sounds similar but not directly related] <br /><br />

*  https://github.com/signalapp/Signal-Android/issues/6234#issuecomment-280353912 and https://gist.github.com/c55f15162cc077efc73e166fc761cb12 , Android 6.0.1 on Samsung SM-G900P (kltespr) Signal 3.29.6 == 
```
02-16 08:36:45.870 14479 14479 W MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_DELIVER
02-16 08:36:45.870 14479 14479 W ResourcesManager: getTopLevelResources: /system/priv-app/SecMms_Candy_M/SecMms_Candy_M.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null
02-16 08:36:45.880 14479 14479 W ResourcesManager: getTopLevelResources: /data/app/com.google.android.talk-1/base.apk / 1.0 running in org.thoughtcrime.securesms rsrc of package null
02-16 08:36:45.900 14479 14479 W MmsListener: Relevant!
02-16 08:36:45.930 14479 14598 W PduParser: parse() called...
02-16 08:36:45.930 14479 14598 W PduParser: Message Type: 130
02-16 08:36:45.930 14479 14598 W MmsDatabase: Message received type: 130
02-16 08:36:45.940 14479 14479 W MmsListener: Got MMS broadcast...android.provider.Telephony.WAP_PUSH_RECEIVED
02-16 08:36:45.970 14479 14598 W MmsReceiveJob: Inserted received MMS notification...
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: java.util.concurrent.TimeoutException: timeout when waiting for MMS
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:86)
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:74)
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:98)
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-16 08:37:25.242 14479 14596 W IncomingLollipopMmsConnection: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: ws.com.google.android.mms.MmsException: java.util.concurrent.TimeoutException: timeout when waiting for MMS
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:97)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.thoughtcrime.securesms.mms.CompatMmsConnection.retrieve(CompatMmsConnection.java:74)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.thoughtcrime.securesms.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:98)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: Caused by: java.util.concurrent.TimeoutException: timeout when waiting for MMS
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.thoughtcrime.securesms.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	at org.thoughtcrime.securesms.mms.IncomingLollipopMmsConnection.retrieve(IncomingLollipopMmsConnection.java:86)
02-16 08:37:25.242 14479 14596 W MmsDownloadJob: 	... 5 more
02-16 08:37:25.272 14479 14596 W MmsSmsDatabase: ...thread_id = 68
02-16 08:37:25.652 14479 14596 W MmsDownloadJob: Downloading mms at rstnmms.sprintpcs.com
02-16 08:37:25.652 14479 14596 W CompatMmsConnection: Falling back to try receiving via Lollipop API
02-16 08:37:25.682 14479 14596 W IncomingLollipopMmsConnection: downloading multimedia from http://rstnmms.sprintpcs.com/ammsc/?ABKrWWJUDpzsZcd4g12489818961 to content://org.thoughtcrime.provider.securesms.mms/mms/1487255845692
02-16 08:37:53.182 14479 14479 W LollipopMmsConnection: onReceive()
02-16 08:37:53.182 14479 14479 W IncomingLollipopMmsConnection: HTTP status: -1
02-16 08:37:53.182 14479 14479 W IncomingLollipopMmsConnection: code: 3, result string: null
02-16 08:37:53.182 14479 14596 W MmsBodyProvider: openFile(content://org.thoughtcrime.provider.securesms.mms/mms/1487255845692, r)
02-16 08:37:53.182 14479 14596 W MmsBodyProvider: Fetching message body for a single row...
02-16 08:37:53.182 14479 14596 W MmsBodyProvider: returning file /data/user/0/org.thoughtcrime.securesms/cache/1487255845692.mmsbody
02-16 08:37:53.242 14479 14596 W IncomingLollipopMmsConnection: java.io.FileNotFoundException: No such file or directory
```
*  https://github.com/signalapp/Signal-Android/issues/6234#issuecomment-362841518 and 
https://gist.github.com/anonymous/e6852ec5887e4e02cd9a2734608d6bd3
```
Device  : Motorola Moto G4 (tesla_athene)
Android : 7.1.2 (90f683d62b, tesla_athene-userdebug 7.1.2 NZH54D 90f683d62b release-keys)
App : Signal 4.16.3
02-03 12:39:22.938  6891  6911 W MmsDownloadJob: Downloading mms at 166.216.198.5, subscription ID: 1
02-03 12:39:22.941  6891  6911 W CompatMmsConnection: Receiving via Lollipop API
02-03 12:39:22.944  6891  6911 W IncomingLollipopMmsConnection: downloading multimedia from http://166.216.198.5:8014/Y/0203163640500034000050000 to content://org.thoughtcrime.provider.securesms.mms/mms/1517679562944
02-03 12:39:22.946  6891  7015 W MmsSmsDatabase: thread_id = 1
02-03 12:39:40.719  6891  6891 W LollipopMmsConnection: onReceive()
02-03 12:39:40.719  6891  6891 W IncomingLollipopMmsConnection: HTTP status: -1
02-03 12:39:40.719  6891  6891 W IncomingLollipopMmsConnection: code: 4, result string: null
02-03 12:39:40.720  6891  6911 W MmsBodyProvider: openFile(content://org.thoughtcrime.provider.securesms.mms/mms/1517679562944, r)
02-03 12:39:40.720  6891  6911 W MmsBodyProvider: Fetching message body for a single row...
02-03 12:39:40.721  6891  6911 W MmsBodyProvider: returning file /data/user/0/org.thoughtcrime.securesms/cache/1517679562944.mmsbody
02-03 12:39:40.723  6891  6911 W IncomingLollipopMmsConnection: 
02-03 12:39:40.723  6891  6911 W IncomingLollipopMmsConnection: java.io.FileNotFoundException: No such file or directory
```

**Not** related == 

* https://github.com/signalapp/Signal-Android/issues/6234#issuecomment-353800537  and https://gist.github.com/anonymous/ae63f328d5e113ac19349a3e7f49d1e0  , Android 4.4.2 on Samsung GT-I9515 (jfveltexx) Signal 4.14.10, "MmsDownloadJob: org.thoughtcrime.securesms.mms.MmsException: Not registered" ...solved by re-enabling home > signal > threeDotMenu > advanced > enable Signal messages and calls (i.e. registering with signal server is "required" to handle SMS/MMS via telco) 

@poetnerd ... I do not suppose you have any interest in trying to use some tricks, such as installing a copy of tcpdump onto your android device perhaps (e.g. https://github.com/chatch/tcpdump-android ... likely requires root permissions), and try to capture the packets which your broken and working MMS apps are exchanging with the mms.vzwreseller.com telco backend?  https://github.com/signalapp/Signal-Android/issues/6663#issuecomment-303584379 seems to encourage that direction of exploration.  In addition to having smartphone-permissions allowing you to install a hand-compiled version of tcpdump onto your android device, you would need a laptop with a usb cable to connect to that smartphone, the android SDK installed (for adb), and probably also wireshark installed (to see the capture-effort).  However, before we go to any such lengths, I would rather see if anybody has the answer to why the APN query seems to be returning the "wrong" result ... though I am not positive the google-sample-file I double checked with is the "right" result either.

**Comment by five-c-d** [comment]
Tracking a different problem, and ran across this MCC+MNC combo, which is "unrelated" to what poetnerd was experiencing ... but also seems to indicate that the ApnDatabase is *not* getting updated properly, at least for some MMS providers:  

```
2019-01-11 20:49:53.482 CET D ApnDatabase: Querying table for MCC+MNC 29364 and APN name internet.t-2.net
2019-01-11 20:49:53.587 CET D ApnDatabase: Returning preferred APN Apn{ mmsc: "", proxy: none, port: (none), user: "", pass: none }
2019-01-11 20:49:53.604 CET I ThumbnailView: Not re-loading slide content://org.thoughtcrime.securesms/part/1547235956826/106
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: null
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: org.thoughtcrime.securesms.mms.ApnUnavailableException: No parameters available from ApnDefaults.
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.LegacyMmsConnection.getApn(LegacyMmsConnection.java:82)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.mms.OutgoingLegacyMmsConnection.isConnectionPossible(OutgoingLegacyMmsConnection.java:155)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.util.Util.isMmsCapable(Util.java:379)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.ConversationActivity$15.doInBackground(ConversationActivity.java:1296)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at org.thoughtcrime.securesms.ConversationActivity$15.doInBackground(ConversationActivity.java:1293)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
2019-01-11 20:49:53.626 CET W OutgoingLegacyMmsConnection: 	at java.lang.Thread.run(Thread.java:841)
```

That exists and should be found, per this == https://android.googlesource.com/device/sample/+/master/etc/apns-full-conf.xml#7310

```
<apn carrier="T2"
carrier_id = "1711"
mcc="293"
mnc="64"
apn="internet.t-2.net"
mmsc="http://www.mms.t-2.net:8002"
mmsproxy="172.20.18.137"
mmsport="8080"
type="default,supl,mms"
/>
```

**Comment by DLFontenot** [comment]
I'm here for this issue too, but I use Verizon and do have SMS and MMS, so there is no reason that I know of that these group messages shouldn't be sending. 

I just made a group text of 15-20 mixed users and had multiple failures. I've had these issues while roaming occasionally as well, and it always ends with Signal spamming the recipients. Unfortunately, I've endured this issue to much and am no longer using Signal for my SMS/MMS, but I'm happy to try and help debug the issue which is why I hunted down this git issue.

**Comment by DLFontenot** [comment]
Switching to my original messaging app resulted in me getting an error for having more than 20 participants in the group chat. [Here is Verizon answering a question on the group limit](https://community.verizonwireless.com/t5/Moto-Z-Droid/Limiting-the-number-of-contacts-on-a-group-text-message/td-p/1067800)

I now see how my error is in line with OPs, in both cases Signal fails to properly handle errors when there is a reason that the MMS group chat cannot be sent.
