### ISSUE TITLE
Group messages alert with user's notification sound

### ISSUE THREAD

**Issue by 2-4601** [signalapp/Signal-Android#8539]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Sometimes when a user sends a message to a group I hear the user's notification sound instead of the group's notification sound. Does not always happen. Don't know how to reproduce. I think this started occurring in the past month or so. Maybe due to the notification channel update? I have the default device encryption on. Signal's screen lock is off.

### Steps that sometimes make it happen
- make sure you have set a custom sound for user U
- make sure you have set a custom sound for group G
- user U sends a message to group G

**Actual result:** I hear the custom sound of user U
**Expected result:** I hear the custom sound of group G

This occurs in the following log at the 2019-01-18 17:38 mark for contact `+**********86` and group `424c896d24a45895bdf9478a1e3f33a9`
```
2019-01-18 17:38:24.179 GMT+02:00 I GcmBroadcastReceiver: GCM message...
2019-01-18 17:38:24.189 GMT+02:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-01-18 17:38:24.190 GMT+02:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/
2019-01-18 17:38:24.704 GMT+02:00 I GcmBroadcastReceiver: Retrieved an envelope. (524 ms elapsed)
2019-01-18 17:38:24.749 GMT+02:00 D PushDecryptJob: Typing stopped on thread 9 due to an incoming message.
2019-01-18 17:38:24.843 GMT+02:00 I Job: [a769bb1a-f24f-4326-af72-ba4a83394817] TrimThreadJob :: onSubmit() network: true
2019-01-18 17:38:24.907 GMT+02:00 I Job: [a769bb1a-f24f-4326-af72-ba4a83394817] TrimThreadJob :: doWork() (Time since submission: 51 ms, Run attempt: 0, isStopped: false)
2019-01-18 17:38:24.968 GMT+02:00 I Job: [a769bb1a-f24f-4326-af72-ba4a83394817] TrimThreadJob :: doWorkInternal() (Time since submission: 52 ms, Run attempt: 0, isStopped: false)
2019-01-18 17:38:24.981 GMT+02:00 I Job: [a769bb1a-f24f-4326-af72-ba4a83394817] TrimThreadJob :: Successfully completed. (Time since submission: 52 ms, Run attempt: 0, isStopped: false)
2019-01-18 17:38:25.315 GMT+02:00 I MessageNotifier: sendSingleThreadNotification()  signal: false  bundled: true
2019-01-18 17:38:25.318 GMT+02:00 I EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/76352083596e69e9f5635c7f4cc45812180b4d5d16a368018e425c53dea24b8c.0
2019-01-18 17:38:25.328 GMT+02:00 I EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/76352083596e69e9f5635c7f4cc45812180b4d5d16a368018e425c53dea24b8c.0
2019-01-18 17:38:25.338 GMT+02:00 I EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/76352083596e69e9f5635c7f4cc45812180b4d5d16a368018e425c53dea24b8c.0
2019-01-18 17:38:25.347 GMT+02:00 I NotificationState: Added thread: 13
2019-01-18 17:38:25.357 GMT+02:00 I NotificationState: getAndroidAutoHeardIntent Added thread: 13
2019-01-18 17:38:25.374 GMT+02:00 I MessageNotifier: Posted notification. Notification(channel=contact___textsecure_group__!336faf7eebdf7f5c85bd98f15b4674b9_1547587969018 pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x9 color=0xff2090ea category=msg groupKey=messages actions=2 vis=PRIVATE)
2019-01-18 17:38:25.378 GMT+02:00 I MessageNotifier: sendSingleThreadNotification()  signal: false  bundled: true
2019-01-18 17:38:25.378 GMT+02:00 I EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/c04b15d243f7485cd0458bf2e17674ca8dab7f64a59862a45b82ef14d76a2df1.0
2019-01-18 17:38:25.393 GMT+02:00 I EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/c04b15d243f7485cd0458bf2e17674ca8dab7f64a59862a45b82ef14d76a2df1.0
2019-01-18 17:38:25.395 GMT+02:00 I EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/c04b15d243f7485cd0458bf2e17674ca8dab7f64a59862a45b82ef14d76a2df1.0
2019-01-18 17:38:25.407 GMT+02:00 I NotificationState: Added thread: 4
2019-01-18 17:38:25.412 GMT+02:00 I NotificationState: getAndroidAutoHeardIntent Added thread: 4
2019-01-18 17:38:25.424 GMT+02:00 I MessageNotifier: Posted notification. Notification(channel=messages_2 pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x9 color=0xff2090ea category=msg groupKey=messages actions=2 vis=PRIVATE)
2019-01-18 17:38:25.434 GMT+02:00 I MessageNotifier: sendSingleThreadNotification()  signal: false  bundled: true
2019-01-18 17:38:25.439 GMT+02:00 I EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/9f7f0306f289b6b090b7157c19f99ea185c9a47922e14bc571aed73e0bfd32c9.0
2019-01-18 17:38:25.441 GMT+02:00 I EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/9f7f0306f289b6b090b7157c19f99ea185c9a47922e14bc571aed73e0bfd32c9.0
2019-01-18 17:38:25.442 GMT+02:00 I EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/9f7f0306f289b6b090b7157c19f99ea185c9a47922e14bc571aed73e0bfd32c9.0
2019-01-18 17:38:25.454 GMT+02:00 I NotificationState: Added thread: 9
2019-01-18 17:38:25.459 GMT+02:00 I NotificationState: getAndroidAutoHeardIntent Added thread: 9
2019-01-18 17:38:25.490 GMT+02:00 I MessageNotifier: Posted notification. Notification(channel=contact___textsecure_group__!424c896d24a45895bdf9478a1e3f33a9_1547461476153 pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x9 color=0xff2090ea category=msg groupKey=messages actions=2 vis=PRIVATE)
2019-01-18 17:38:25.519 GMT+02:00 I MessageNotifier: sendMultiThreadNotification()  signal: true
2019-01-18 17:38:25.520 GMT+02:00 I NotificationState: Added thread: 13
2019-01-18 17:38:25.529 GMT+02:00 I NotificationState: Added thread: 4
2019-01-18 17:38:25.529 GMT+02:00 I NotificationState: Added thread: 9
2019-01-18 17:38:25.530 GMT+02:00 I MessageNotifier: Posted notification. Notification(channel=contact_+**********86_1547641982646 pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x201 color=0xff2090ea category=msg groupKey=messages actions=1 vis=PRIVATE)
2019-01-18 17:38:25.821 GMT+02:00 I GcmBroadcastReceiver: Successfully processed an envelope. (1374 ms elapsed)
2019-01-18 17:38:25.904 GMT+02:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-01-18 17:38:25.972 GMT+02:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/uuid/c0b242ca-d87a-42e2-9624-33e6cb5cf961
2019-01-18 17:38:25.973 GMT+02:00 I Job: [96b95b01-d1dc-42c2-b7a8-efd4d43eddf0] SendDeliveryReceiptJob :: onSubmit() network: true
2019-01-18 17:38:25.973 GMT+02:00 I Job: [96b95b01-d1dc-42c2-b7a8-efd4d43eddf0] SendDeliveryReceiptJob :: doWork() (Time since submission: 120 ms, Run attempt: 0, isStopped: false)
2019-01-18 17:38:25.974 GMT+02:00 I Job: [96b95b01-d1dc-42c2-b7a8-efd4d43eddf0] SendDeliveryReceiptJob :: doWorkInternal() (Time since submission: 121 ms, Run attempt: 0, isStopped: false)
2019-01-18 17:38:25.975 GMT+02:00 I UnidentifiedAccessUtil: Their access key present? true | Our access key present? true | Our certificate present? true
2019-01-18 17:38:25.975 GMT+02:00 I GcmBroadcastReceiver: Processing complete.
2019-01-18 17:38:25.976 GMT+02:00 W SignalServiceMessageSender: Transmitting over unidentified pipe...
2019-01-18 17:38:25.977 GMT+02:00 W SignalServiceMessageSender: java.io.IOException: No connection!
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:154)
	at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:138)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:815)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:156)
	at org.thoughtcrime.securesms.jobs.SendDeliveryReceiptJob.onRun(SendDeliveryReceiptJob.java:85)
	at org.thoughtcrime.securesms.jobmanager.Job.doWorkInternal(Job.java:111)
	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:64)
	at androidx.work.Worker$1.run(Worker.java:84)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

2019-01-18 17:38:25.984 GMT+02:00 W SignalServiceMessageSender: Falling back to new connection...
2019-01-18 17:38:25.987 GMT+02:00 W SignalServiceMessageSender: Not transmitting over pipe...
2019-01-18 17:38:25.988 GMT+02:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-01-18 17:38:25.989 GMT+02:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+**********86
2019-01-18 17:38:26.282 GMT+02:00 I Job: [96b95b01-d1dc-42c2-b7a8-efd4d43eddf0] SendDeliveryReceiptJob :: Successfully completed. (Time since submission: 726 ms, Run attempt: 0, isStopped: false)
2019-01-18 17:38:53.715 GMT+02:00 I ApplicationContext: App is now visible.
2019-01-18 17:38:53.720 GMT+02:00 I PassphraseRequiredActionBarActivity: onResume()
2019-01-18 17:38:53.724 GMT+02:00 D IncomingMessageObserver: Network requirement: true, app visible: true, gcm disabled: false
2019-01-18 17:38:53.725 GMT+02:00 I IncomingMessageObserver: Making websocket connection....
2019-01-18 17:38:53.725 GMT+02:00 W WebSocketConnection: WSC connect()...
2019-01-18 17:38:53.731 GMT+02:00 I SignalCommunicationModule: onConnecting()
2019-01-18 17:38:53.732 GMT+02:00 W WebSocketConnection: WSC connect()...
2019-01-18 17:38:53.738 GMT+02:00 I SignalCommunicationModule: onConnecting()
2019-01-18 17:38:53.762 GMT+02:00 D IncomingMessageObserver: Network requirement: true, app visible: true, gcm disabled: false
2019-01-18 17:38:53.762 GMT+02:00 I IncomingMessageObserver: Reading message...
2019-01-18 17:38:54.616 GMT+02:00 W WebSocketConnection: onConnected()
2019-01-18 17:38:54.617 GMT+02:00 I SignalCommunicationModule: onConnected()
2019-01-18 17:38:54.623 GMT+02:00 W WebSocketConnection: WSC onMessage()
2019-01-18 17:38:54.625 GMT+02:00 W WebSocketConnection: Message Type: 1
2019-01-18 17:38:55.052 GMT+02:00 W WebSocketConnection: onConnected()
2019-01-18 17:38:55.053 GMT+02:00 I SignalCommunicationModule: onConnected()
2019-01-18 17:39:00.472 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
2019-01-18 17:39:00.483 GMT+02:00 I PassphraseRequiredActionBarActivity: onCreate(null)
2019-01-18 17:39:00.532 GMT+02:00 I ExperienceUpgradeActivity: getExperienceUpgrade(437)
2019-01-18 17:39:00.532 GMT+02:00 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
2019-01-18 17:39:00.533 GMT+02:00 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
2019-01-18 17:39:00.559 GMT+02:00 I PassphraseRequiredActionBarActivity: onResume()
2019-01-18 17:39:00.592 GMT+02:00 I EncryptedGifCacheDecoder: Checking item for encrypted GIF cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/3ec33122b5b1c654aedc1dbeb11508e979fa15cf157a96b11ac05428bb6c8e77.0
2019-01-18 17:39:00.594 GMT+02:00 I EncryptedBitmapCacheDecoder: Checking item for encrypted Bitmap cache decoder: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/3ec33122b5b1c654aedc1dbeb11508e979fa15cf157a96b11ac05428bb6c8e77.0
2019-01-18 17:39:00.595 GMT+02:00 I EncryptedBitmapCacheDecoder: Encrypted Bitmap cache decoder running: /data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/3ec33122b5b1c654aedc1dbeb11508e979fa15cf157a96b11ac05428bb6c8e77.0
2019-01-18 17:39:03.826 GMT+02:00 I PassphraseRequiredActionBarActivity: onPause()
```

### Full debug log
https://debuglogs.org/cff7287dddcee287cf542d7c9658cc77eb43a5900031fd5a10f705894b7f6d2c

### Device info

**Device:** Pixel XL
**Android version:** 9
**Signal version:** 4.32.4

**Comment by 2-4601** [comment]
#### Another occurrence:
The last received message in this log
https://debuglogs.org/64a9ff6548057a34fecc899dd5acec46fe79ed131a9ee5ea810c655e6fc3980c
alerted with the custom sound of contact `+**********66`.

It should have alerted with the custom sound of the group `380f8bf4f3115ec05412f16b5fc38761`.

**Signal version:** 4.32.7

**Comment by 2-4601** [comment]
I am able to reproduce this now:

- user sends a message to your group: you will hear the group sound (as expected)
- user sends a message directly to you: you will hear the user's sound (as expected)
- user sends a message to your group: **you will hear the user's sound** (this is abomination)

Signal 4.33.5, Android Pie

**Comment by TheShanMan** [comment]
I've experienced this too for quite some time. The one thing missing from the steps to reproduce is that it only happens when I've got one or more notifications from other conversations. Multiple Signal notifications is when I start experiencing the user sounds rather than the group sounds.
