### ISSUE TITLE
Unhandled Promise Rejecion Error in desktop app, when waking from sleep

### ISSUE THREAD

**Issue by greggirwin** [signalapp/Signal-Android#8596]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Since updating to v1.21.0 I get the following error from Signal desktop every time I wake my system (WIndows 10) from overnight sleep. It never happened in previous versions. It appears that the system needs to be asleep for some time. Just putting it to sleep and waking it right back up doesn't reproduce the issue. Based on `NsisUpdater.getUpdateInfoAndProvider` and the use of `electron-updater`, my guess is that Signal tries to look for updates on waking, and the net connection isn't established yet.

```
Unhandled Promise Rejection
Error: net::ERR_NAME_NOT_RESOLVED
    at GenericProvider.getLatestVersion (C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at Timeout.checkForUpdates [as _onTimeout] (C:\Users\Gregg\AppData\Local\Programs\signal-desktop\resources\app.asar\app\auto_update.js:22:15)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

### Steps to reproduce

- Run signal
- Leave Signal running and put the system to sleep for some extended period
- Wake the system

When the system wakes up, a dialog with the above error message is displayed, and the Signal window is gone.

### Device info

- Desktop system
- WIndows 10

**Comment by greggirwin** [comment]
Crap. Just noticed the repo this is in. Sorry about that. Needs to be in Desktop repo. Need coffee.
