### ISSUE TITLE
Crashed on opening in Android 8.0.0

### ISSUE THREAD

**Issue by mikicat** [signalapp/Signal-Android#8607]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic
### Bug description
Signal won't start after updating Android to 8.0.0
It crashes right after clicking on signal app icon.

### Device info
**Device:** Blackview BV9000Pro-F
**Android version:** 8.0.0
**Signal version:** 4.32.8

### Link to debug log
[signal_crash.log](https://github.com/signalapp/Signal-Android/files/2852242/signal_crash.log)

#### Edit
I think it's a similiar issue to [#8589](https://github.com/signalapp/Signal-Android/issues/8589)

**Comment by greyson-signal** [comment]
Yeah, similar keystore exception. 

```java
02-11 18:24:31.604 30663 30663 E AndroidRuntime: FATAL EXCEPTION: main
02-11 18:24:31.604 30663 30663 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 30663
02-11 18:24:31.604 30663 30663 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.thoughtcrime.securesms.ApplicationContext: java.security.ProviderException: Keystore operation failed
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5955)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:206)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6735)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: Caused by: java.security.ProviderException: Keystore operation failed
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:321)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.createKeyStoreEntry(KeyStoreHelper.java:94)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:80)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:48)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.createAndStoreSecret(LogSecretProvider.java:48)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:22)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:48)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:175)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:105)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5952)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	... 8 more
02-11 18:24:31.604 30663 30663 E AndroidRuntime: Caused by: android.security.KeyStoreException: Unknown error
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:695)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:322)
02-11 18:24:31.604 30663 30663 E AndroidRuntime: 	... 19 more
02-11 18:24:31.610   918  2442 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-11 18:24:31.614   360   396 I vendor.mediatek.hardware.power@1.1-impl: mtkPowerHint hint:11, data:2000
02-11 18:24:31.617   918  1070 I ActivityManager: Showing crash dialog for package org.thoughtcrime.securesms u0
```

Let's use #8589 as the primary issue. Closing this as a dupe.
