### ISSUE TITLE
Two problems sending text messages

### ISSUE THREAD

**Issue by davetamasi** [signalapp/Signal-Android#8718]
I'm experiencing two problems sending text messages using Signal 4.36.2 on Android 8.0.0 on a Samsung Galaxy S8+:

I text my friend Megs and immediately get a red circle-bang. Have reset the session, attempted to resend the message, does not fix. Been this way for months.

Debug log: https://debuglogs.org/dd4a514e961f6343dbecdaccfbc49e6ba1fecf60ae9e4945eb1462361f07407c

I text my friend Larissa and the message apparently sends; the message bubble is annotated with a small circle with a checkbox. But she does not receive the message. Have reset the session, did not fix the problem. Been this way for months.

Debug log: https://debuglogs.org/92f508e61b263c2457ba27cc34ca212866b89eef61ef7738f637e8d3d2db9784

**Comment by greyson-signal** [comment]
For reference:

Message failure
```java
2019-03-25 16:46:26.465 PDT W Job: [2c2357de-7195-4d6a-bb2a-36a0b30eb60f] PushTextSendJob :: Failing due to an exception. (Time since submission: 542 ms, Run attempt: 0, isStopped: false)
2019-03-25 16:46:26.465 PDT W Job: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.whispersystems.libsignal.IdentityKey.equals(java.lang.Object)' on a null object reference
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.crypto.storage.TextSecureIdentityKeyStore.isTrustedForSending(TextSecureIdentityKeyStore.java:128)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.crypto.storage.TextSecureIdentityKeyStore.isTrustedIdentity(TextSecureIdentityKeyStore.java:104)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.isTrustedIdentity(SignalProtocolStoreImpl.java:51)
2019-03-25 16:46:26.465 PDT W Job: 	at org.whispersystems.libsignal.SessionBuilder.process(SessionBuilder.java:167)
2019-03-25 16:46:26.465 PDT W Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:981)
2019-03-25 16:46:26.465 PDT W Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:951)
2019-03-25 16:46:26.465 PDT W Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:826)
2019-03-25 16:46:26.465 PDT W Job: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:218)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:184)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.jobs.PushTextSendJob.onPushSend(PushTextSendJob.java:94)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.jobs.PushSendJob.onSend(PushSendJob.java:89)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:56)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWorkInternal(Job.java:111)
2019-03-25 16:46:26.465 PDT W Job: 	at org.thoughtcrime.securesms.jobmanager.Job.doWork(Job.java:64)
2019-03-25 16:46:26.465 PDT W Job: 	at androidx.work.Worker$1.run(Worker.java:84)
2019-03-25 16:46:26.465 PDT W Job: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-03-25 16:46:26.465 PDT W Job: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-03-25 16:46:26.465 PDT W Job: 	at java.lang.Thread.run(Thread.java:764)
```

For the second log, the issue is likely on the receiving side. If you got a single checkmark, your job is done. The message is sent. (This is a signal message, yes? Not an SMS?)

Also, fwiw these logs are from 4.35.3, not 4.36.2.

**Comment by davetamasi** [comment]
Thanks a million Greyson!

Re: first issue.  Gotta love null derefs.   Would it fix the problem to delete the contact and recreate it?

Re: second issue.  It’s a signal message on my end; I believe Larissa had Signal and then deleted it, or may have it installed but not have it set as the messaging handler.  Would that cause this problem?

Re:  Signal rev.   I had originally mistakenly filed this bug with the desktop app folks, took a bit to figure that out and file it with you.  The app apparently updated in the interim.

**Comment by greyson-signal** [comment]
> Would it fix the problem to delete the contact and recreate it?

I've honestly never see that happen. Something bad is happening with the session. I'd have to investigate.

> I believe Larissa had Signal and then deleted it

That's likely the problem. There can be a pretty big delay between when a user uninstalls an app and when we're notified by the relevant system (e.g. Apple/Google's notification systems).

**Comment by Facemelter222** [comment]
Yea having same issue. Friend is former signal user (from several months ago) and does not receive SMS from my signal. Sent checkmark visible on my side.

Switched to default android messages app to test, worked first try.  Let me know if I can help provide additional info

**Comment by davetamasi** [comment]
Correct – I am able to send messages to her through the Android Messages app no problem.

It’s a pain to have to change the default SMS app each time I want to write this one person, however. :)

Because of that, I do think this is a Signal problem.

**Comment by jeremymasters** [comment]
If they uninstalled signal, have them go to https://signal.org/textsecure/unregister/
Temporarily, you can long press the send button and choose sms
Alternatively, you can have them re-install signal 😁
