### ISSUE TITLE
Crash on attempts to use GIF feature since mandated upgrade to 4.33.5

### ISSUE THREAD

**Issue by BugScribe** [signalapp/Signal-Android#8774]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since a forced upgrade to 4.33.5 recently (the Signal app announced it would no longer work otherwise), any attempt to use the GIF feature whilst composing text messages with the Signal app results in a crash. This issues persists after an upgrade to 4.34.8 too.

The Signal app has been used on the device for years prior. Same device no changes.

#### For crash while scrolling GIFs
- Open Signal
- Select a contact from conversation list
- Press the (+) icon next to message input box
- Press the GIF icon
- Scroll the list of GIFs really fast (scrolling slowly will eventually result in same outcome after 3-4 pages)

**Actual result:**
  - The list of GIFs begins to scroll rapidly as expected then, Signal crashes and the "Unfortunately, Signal has stopped." message is displayed
  - NOTE: Signal does not always crash with the message, sometimes the GIF Activity and keyboard simply disappears and we are dumped back to the conversation screen

**Expected result:** 
  - The list of GIFs scroll rapidly then slows down and stops scrolling
 
#### For crash while searching GIFs
- Open Signal
- Select a contact from conversation list
- Press the (+) icon next to message input box
- Press the GIF icon
- Touch the GIF search box to bring up the keyboard
- Try typing "hello world" or just try entering a (lengthy?) search string 

**Actual result:**
  - At some point Signal crashes and the "Unfortunately, Signal has stopped." message is displayed
  - NOTE: Signal does not always crash with the message, sometimes the GIF Activity and keyboard simply disappears and we are dumped back to the conversation screen

**Expected result:**
  - The list of GIFs are filtered to match the entered search term(s)

### Device info

**Device:** Motorola Moto G xt1033
**Android version:** 4.4.4
**Signal version:** 4.34.8, 4.33.5

### Link to debug log
[For crash while SCROLLING](https://debuglogs.org/0f2573b2b1b8f21534ae9ad240cce230a5250e74613e573c4c87334a8f8ae78f)

**Comment by greyson-signal** [comment]
Your debug log is > 30 days old and therefore is no longer available. It seems like it's easy to repro -- can you do it again and submit a new debug log?

**Comment by BugScribe** [comment]
[For crash while SCROLLING](https://debuglogs.org/37d7d143c6a3dcb3cae018994819574435ffcba9b5d26a30538e07fdcfb70cce)

[For crash while SEARCHING](https://debuglogs.org/4c4ec397d0234c98765381da4f3bb3fa797ad30e3a22050d8cbfdd94ef573e03)

**Comment by alan-signal** [comment]
Both seem to be this:

```
W/EncryptedCacheEncoder( 9340): null
W/EncryptedCacheEncoder( 9340): java.net.SocketException: Socket is closed
W/EncryptedCacheEncoder( 9340): 	at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:238)
W/EncryptedCacheEncoder( 9340): 	at com.android.org.conscrypt.OpenSSLSocketImpl.access$100(OpenSSLSocketImpl.java:63)
W/EncryptedCacheEncoder( 9340): 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:685)
W/EncryptedCacheEncoder( 9340): 	at okio.Okio$2.read(Okio.java:139)
W/EncryptedCacheEncoder( 9340): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
W/EncryptedCacheEncoder( 9340): 	at okio.RealBufferedSource.read(RealBufferedSource.java:46)
W/EncryptedCacheEncoder( 9340): 	at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:352)
W/EncryptedCacheEncoder( 9340): 	at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:396)
W/EncryptedCacheEncoder( 9340): 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
W/EncryptedCacheEncoder( 9340): 	at java.io.FilterInputStream.read(FilterInputStream.java:118)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.util.ContentLengthInputStream.read(ContentLengthInputStream.java:72)
W/EncryptedCacheEncoder( 9340): 	at java.io.FilterInputStream.read(FilterInputStream.java:118)
W/EncryptedCacheEncoder( 9340): 	at org.thoughtcrime.securesms.net.ChunkedDataFetcher$SkippingInputStream.read(ChunkedDataFetcher.java:262)
W/EncryptedCacheEncoder( 9340): 	at org.thoughtcrime.securesms.net.ChunkedDataFetcher$InputStreamList.read(ChunkedDataFetcher.java:307)
W/EncryptedCacheEncoder( 9340): 	at org.thoughtcrime.securesms.net.ChunkedDataFetcher$InputStreamList.read(ChunkedDataFetcher.java:318)
W/EncryptedCacheEncoder( 9340): 	at org.thoughtcrime.securesms.glide.cache.EncryptedCacheEncoder.encode(EncryptedCacheEncoder.java:39)
W/EncryptedCacheEncoder( 9340): 	at org.thoughtcrime.securesms.glide.cache.EncryptedCacheEncoder.encode(EncryptedCacheEncoder.java:17)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.DataCacheWriter.write(DataCacheWriter.java:31)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.cache.DiskLruCacheWrapper.put(DiskLruCacheWrapper.java:134)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:79)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
W/EncryptedCacheEncoder( 9340): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/EncryptedCacheEncoder( 9340): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/EncryptedCacheEncoder( 9340): 	at java.lang.Thread.run(Thread.java:841)
W/EncryptedCacheEncoder( 9340): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
D/ChunkedImageUrlFetcher( 9340): Canceled.
E/UncaughtExceptionLogger( 9340): 
E/UncaughtExceptionLogger( 9340): java.lang.IllegalStateException: Unbalanced enter/exit
E/UncaughtExceptionLogger( 9340): 	at okio.AsyncTimeout.enter(AsyncTimeout.java:73)
E/UncaughtExceptionLogger( 9340): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:235)
E/UncaughtExceptionLogger( 9340): 	at okio.RealBufferedSource.read(RealBufferedSource.java:46)
E/UncaughtExceptionLogger( 9340): 	at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:352)
E/UncaughtExceptionLogger( 9340): 	at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:396)
E/UncaughtExceptionLogger( 9340): 	at okhttp3.internal.Util.skipAll(Util.java:175)
E/UncaughtExceptionLogger( 9340): 	at okhttp3.internal.Util.discard(Util.java:157)
E/UncaughtExceptionLogger( 9340): 	at okhttp3.internal.http1.Http1Codec$FixedLengthSource.close(Http1Codec.java:413)
E/UncaughtExceptionLogger( 9340): 	at okio.RealBufferedSource.close(RealBufferedSource.java:455)
E/UncaughtExceptionLogger( 9340): 	at okio.RealBufferedSource$1.close(RealBufferedSource.java:443)
E/UncaughtExceptionLogger( 9340): 	at java.io.FilterInputStream.close(FilterInputStream.java:64)
E/UncaughtExceptionLogger( 9340): 	at java.io.FilterInputStream.close(FilterInputStream.java:64)
E/UncaughtExceptionLogger( 9340): 	at org.thoughtcrime.securesms.util.Util.close(Util.java:208)
E/UncaughtExceptionLogger( 9340): 	at org.thoughtcrime.securesms.net.CallRequestController.lambda$cancel$0(CallRequestController.java:34)
E/UncaughtExceptionLogger( 9340): 	at org.thoughtcrime.securesms.net.-$$Lambda$CallRequestController$dSCLut3_7ld6pvj1xm-KwuW6aug.run(lambda)
E/UncaughtExceptionLogger( 9340): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/UncaughtExceptionLogger( 9340): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/UncaughtExceptionLogger( 9340): 	at java.lang.Thread.run(Thread.java:841)
```
