### ISSUE TITLE
Signal crashes when opening app

### ISSUE THREAD

**Issue by joneshf** [signalapp/Signal-Android#8781]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal immediately crashes when trying to open.

It was working normally earlier today. Looking at the messages from the desktop app, I sent a message to someone at 12:59 PDT from my phone, they sent a message to me at 13:02 PDT that I received on my phone. They then sent another message to me at 13:02 PDT that I didn't receive on my phone (and a few more after that). Around 17:00 PDT, I noticed the app on my phone wouldn't open anymore.

### Steps to reproduce
- Press the Signal app

**Actual result:** Signal crashes, flashes a report dialog, then dismisses it.
**Expected result:** Signal opens, and I can use it.

### Screenshots

![signal_crash_2](https://user-images.githubusercontent.com/1356417/56707586-5660ee80-66ce-11e9-9b46-3a6e4c30d156.gif)

### Device info

**Device:** Moto G5 plus
**Android version:** 8.1.0
**Signal version:** 4.37.2

### Link to debug log

Cannot capture a debug log from the phone as the app doesn't open.

Connecting through `adb` and using `logcat` gives this:
```
04-24 19:39:02.212 10252 10276 E Database: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.212 10252 10276 E Database: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
04-24 19:39:02.212 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.212 10252 10276 E Database: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.212 10252 10276 E Database: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:684)
04-24 19:39:02.212 10252 10276 E Database: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-24 19:39:02.212 10252 10276 E Database: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.212 10252 10276 E Database: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.212 10252 10276 E Database: 	at java.lang.Thread.run(Thread.java:764)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: Couldn't open signal.db for writing (will try read-only):
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:684)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.212 10252 10276 E SQLiteOpenHelper: 	at java.lang.Thread.run(Thread.java:764)
04-24 19:39:02.215 10252 10252 I org.webrtc.Logging: PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
04-24 19:39:02.222 10252 10276 E Database: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.222 10252 10276 E Database: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
04-24 19:39:02.222 10252 10276 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.222 10252 10276 E Database: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.222 10252 10276 E Database: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:684)
04-24 19:39:02.222 10252 10276 E Database: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-24 19:39:02.222 10252 10276 E Database: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.222 10252 10276 E Database: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.222 10252 10276 E Database: 	at java.lang.Thread.run(Thread.java:764)
--------- switch to crash
04-24 19:39:02.223 10252 10276 E AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
04-24 19:39:02.223 10252 10276 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10252
04-24 19:39:02.223 10252 10276 E AndroidRuntime: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:684)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.223 10252 10276 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
--------- switch to main
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:684)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.223 10252 10276 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:764)
--------- switch to system
04-24 19:39:02.226  1599  9745 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
--------- switch to main
04-24 19:39:02.232 10252 10282 E Database: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.232 10252 10282 E Database: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
04-24 19:39:02.232 10252 10282 E Database: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.232 10252 10282 E Database: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.232 10252 10282 E Database: 	at org.thoughtcrime.securesms.database.RecipientDatabase.getRecipientsWithNotificationChannels(RecipientDatabase.java:168)
04-24 19:39:02.232 10252 10282 E Database: 	at org.thoughtcrime.securesms.notifications.NotificationChannels.ensureCustomChannelConsistency(NotificationChannels.java:399)
04-24 19:39:02.232 10252 10282 E Database: 	at org.thoughtcrime.securesms.notifications.NotificationChannels.lambda$create$0(NotificationChannels.java:79)
04-24 19:39:02.232 10252 10282 E Database: 	at org.thoughtcrime.securesms.notifications.-$$Lambda$NotificationChannels$Sd7VJNywHEsb0voxMXFHyQiVB-I.run(Unknown Source:2)
04-24 19:39:02.232 10252 10282 E Database: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
04-24 19:39:02.232 10252 10282 E Database: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.232 10252 10282 E Database: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.232 10252 10282 E Database: 	at java.lang.Thread.run(Thread.java:764)
--------- switch to system
04-24 19:39:02.232  1599  1777 I ActivityManager: Showing crash dialog for package org.thoughtcrime.securesms u0
--------- switch to main
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: Couldn't open signal.db for writing (will try read-only):
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:416)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.database.RecipientDatabase.getRecipientsWithNotificationChannels(RecipientDatabase.java:168)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.notifications.NotificationChannels.ensureCustomChannelConsistency(NotificationChannels.java:399)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.notifications.NotificationChannels.lambda$create$0(NotificationChannels.java:79)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at org.thoughtcrime.securesms.notifications.-$$Lambda$NotificationChannels$Sd7VJNywHEsb0voxMXFHyQiVB-I.run(Unknown Source:2)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-24 19:39:02.232 10252 10282 E SQLiteOpenHelper: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by greyson-signal** [comment]
It looks like your database has become corrupted or otherwise unreadable. Is your device rooted or have you otherwise altered the file system at all? I've seen situations where different xposed mods and whatnot can mess with files and permissions in such a way where things like this happen.

Otherwise, this could relate to https://github.com/sqlcipher/android-database-sqlcipher/issues/390. However, that ticket appears to describe a situation that'd consistently happen on the same kinds of devices, not something that sporadically happens to a functioning device.

**Comment by joneshf** [comment]
@greyson-signal Thanks for taking a look at this!

My device is not rooted, and I've not altered the file system. Any ideas on what I should do? Are my messages all gone?

**Comment by greyson-signal** [comment]
To the best of my knowledge there isn't anything you can do. Your database has become unreadable. If you've made a backup you can restore from that, and if not I recommend turning backups on in the future (Settings > Chats and media > Chat backups). I'm sorry, I can imagine this is frustrating. I'll follow up with SqlCipher to see if there's a bug on their end.

**Comment by joneshf** [comment]
No worries. Thanks for looking into it.
