### ISSUE TITLE
Unable to send images on Pixel 2 to the receiver

### ISSUE THREAD

**Issue by asdhammu** [signalapp/Signal-Android#8810]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I am not able to send image to the receiver. 

### Steps to reproduce
- Open signal app.
- Click on the camera and take a picture.
- Hit send. 

**Actual result:** 
Image is stuck with loader showing approximately 75% 

**Expected result:** 
Image should be sent to the receiver.

### Device info

**Device:** Google Pixel 2 xl
**Android version:** Android 9
**Signal version:** 4.39.4

### Link to debug log
https://debuglogs.org/7d643c49a78fc128f9494c07419b684031d5b729032aaf16ab1c9cc1fb1319b8

**Comment by greyson-signal** [comment]
Looks like, for whatever reason, you're hitting a socket timeout during upload pretty consistently. How often is this happening. Is your network connection stable?

```java
2019-05-13 11:49:53.779 CDT I BaseJob: [413e1dde-941d-481e-9dc6-15fe57c1d97f][AttachmentUploadJob] Encountered a retryable exception. (Time Since Submission: 124847 ms, Lifespan: 86400000 ms, Run Attempt: 6/Unlimited)
2019-05-13 11:49:53.779 CDT I BaseJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: java.net.SocketTimeoutException: timeout
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:683)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendAttachment(PushServiceSocket.java:424)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachment(SignalServiceMessageSender.java:323)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:88)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
2019-05-13 11:49:53.779 CDT I BaseJob: Caused by: java.net.SocketTimeoutException: timeout
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.Okio$4.newTimeoutException(Okio.java:232)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.RealBufferedSink.write(RealBufferedSink.java:42)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.ForwardingSink.write(ForwardingSink.java:35)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.RealBufferedSink$1.write(RealBufferedSink.java:201)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.api.crypto.DigestingOutputStream.write(DigestingOutputStream.java:29)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherOutputStream.write(AttachmentCipherOutputStream.java:59)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.internal.push.http.DigestingRequestBody.writeTo(DigestingRequestBody.java:50)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okhttp3.RealCall.execute(RealCall.java:92)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:681)
2019-05-13 11:49:53.779 CDT I BaseJob: 	... 6 more
2019-05-13 11:49:53.779 CDT I BaseJob: Caused by: java.net.SocketException: socket is closed
2019-05-13 11:49:53.779 CDT I BaseJob: 	at org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:630)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.Okio$1.write(Okio.java:79)
2019-05-13 11:49:53.779 CDT I BaseJob: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
```

**Comment by asdhammu** [comment]
This was happening while I reported the issue for an hour. Connection was stable. I was able to send the text messages but not the images. 
I sent an image followed with a text message. Both were stuck, but when I deleted the image text message was sent. 

I just tried now on LTE the image is still stuck at about 75 %. But I am able to send the text message. I have checked the connection, everything works. 

But on WIFI I am able to send images.

here are latest logs.
https://debuglogs.org/63c2c5f3931e03eb66d145c8bcfc8037411d9d0bb0577824c5caa46836866230

**Comment by greyson-signal** [comment]
> I sent an image followed with a text message. Both were stuck, but when I deleted the image text message was sent.

Yeah, so message sending in Signal is done in order, so if a message was stuck sending (because of an attachment upload), then later messages would also be stuck.

> I just tried now on LTE the image is still stuck at about 75 % [...] But on WIFI I am able to send images.

That's interesting. Do you mind sharing your country + carrier?

**Comment by asdhammu** [comment]
Country : USA
Carrier : Cricket
