### ISSUE TITLE
Contacts don't appear in Signal

### ISSUE THREAD

**Issue by amccarter** [signalapp/Signal-Android#8823]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I go to create a new message, and select a recipient, only two of my phone contacts are available.

### Steps to reproduce
- Install Signal
- Open Signal and complete setup steps
- Tap button to create new message

**Actual result:** List of contacts has only two people; one is a Signal user, one is not.

I've had this issue since I first installed Signal, in Android 7 or 8. I have tried everything in every other but report related to issue that I can find. Even after a fresh install it behaves this way.
**Expected result:** All of my phone contacts (or at least the ones with valid phone numbers) should show up in the list.

### Device info

**Device:** Google Pixel 2 XL
**Android version:** 10 QPP3.190404.015
**Signal version:** 4.40.4

### Link to debug log

https://debuglogs.org/9a8e8a2e95534582ea6a545f276e28b3c5af48243c231a3fc90bede017e36af2

**Comment by piratenpanda** [comment]
What happens when you pull down the contact list to refresh in Signal?

**Comment by amccarter** [comment]
I get the spinning arrow progress indicator for a few seconds, and then nothing. The debug log I attached was taken right after attempting to refresh the contact list.

I see this error on line 90 of the debug log (and a number of other times); I'm not sure if it's related or not:
`2019-05-20 16:43:02.394 CDT W Address$ExternalAddressFormatter: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number. `

**Comment by alan-signal** [comment]
```
2019-05-20 16:44:05.803 CDT W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-05-20 16:44:05.803 CDT W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2019-05-20 16:44:05.804 CDT W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/directory/tokens
2019-05-20 16:44:05.804 CDT W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/directory/auth
2019-05-20 16:44:07.881 CDT W DirectoryHelper: Failed due to poor network.
2019-05-20 16:44:07.881 CDT W DirectoryHelper: java.util.concurrent.ExecutionException: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: Handshake failed
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.executeAndMergeContactDiscoveryRequests(DirectoryHelper.java:405)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:113)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:80)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.ContactSelectionActivity$RefreshDirectoryTask.doInBackground(ContactSelectionActivity.java:132)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.ContactSelectionActivity$RefreshDirectoryTask.doInBackground(ContactSelectionActivity.java:120)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at java.lang.Thread.run(Thread.java:919)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: Caused by: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: Handshake failed
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeContactDiscoveryRequest(PushServiceSocket.java:1027)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getContactDiscoveryRemoteAttestation(PushServiceSocket.java:517)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getRegisteredUsers(SignalServiceAccountManager.java:286)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.lambda$getContactServiceDirectoryResult$3(DirectoryHelper.java:372)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.thoughtcrime.securesms.util.-$$Lambda$DirectoryHelper$F6S_wzBrGC-wFCfc6ja_gJll9k8.call(Unknown Source:6)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	... 4 more
2019-05-20 16:44:07.881 CDT W DirectoryHelper: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:287)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at okhttp3.RealCall.execute(RealCall.java:92)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeContactDiscoveryRequest(PushServiceSocket.java:1021)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	... 8 more
2019-05-20 16:44:07.881 CDT W DirectoryHelper: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xcc73dbf8: Failure in SSL library, usually a protocol error
2019-05-20 16:44:07.881 CDT W DirectoryHelper: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (/usr/local/google/home/flooey/code/boringssl/ssl/tls_record.cc:587 0xccb94548:0x00000001)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (/usr/local/google/home/flooey/code/boringssl/ssl/handshake.cc:580 0xcec3754f:0x00000000)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:385)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:225)
2019-05-20 16:44:07.881 CDT W DirectoryHelper: 	... 28 more
2019-05-20 16:44:07.889 CDT I DirectoryHelper: [Batch] New contact discovery service failed, so we're skipping the comparison.
```

**Comment by amccarter** [comment]
I just tried again, while on my home WiFi, just to try and rule out the "poor network" error. It didn't sound my contacts still.

https://debuglogs.org/3fab1a94ab5c66c6d9bc1f9367f730a0da6ac045e21430d8efec535d8c36e189

**Comment by BigSweetPotato** [comment]
I'm seeing the same issue.

**Comment by jeremymasters** [comment]
I get this in my logs as well:
```SignalServiceAccountManager: Request to indicate a contact discovery result match failed. Ignoring.```

**Comment by monkeyborg** [comment]
Ditto. I have 217 contacts, all from a linked Google account. Only 28 show up in Signal.

**Comment by dazurn** [comment]
I have the same issue with a Google Pixel 3a XL. No contacts from the Google account appear in Signal.

**Comment by alan-signal** [comment]
Are you all using the app as your SMS app?

Either way, is there any patterns to the missing/present contacts. Are they all one or the other.

**Comment by jeremymasters** [comment]
All 85+ of my contacts are in a google account and sync well, so it's probably not just to do with the google account.  Using a Samsung s10+ verizon stock rom.

**Comment by dazurn** [comment]
Only two of my contacts where appearing in my Signal contacts list. What I noticed is that, those two contacts where the only ones that had +1 in the phone number field. So I edited one of the contacts that didn't appear in my Signal contacts list and added +1 in front of the number and BOOM, it then appeared in Signal!

Any logic behind that?

**Comment by alan-signal** [comment]
Is your registered number also `+1` or a different country?

Is your device's SIM the same or different to the registered number's country?

**Comment by dazurn** [comment]
> 
> 
> Is your registered number also `+1` or a different country?
> 
> Is your device's SIM the same or different to the registered number's country?
> 
> And there maybe further clues in your debug log if you wouldn't mind supplying.

Yes my registered number has +1 but i'm not sure about my SIM. I'll post my log soon.

**Comment by amccarter** [comment]
Interestingly, sometime in the past few weeks, all of my contacts are appearing in Signal.

I'm running the Q betas, too. I'm not sure if that has anything to do with it.
