### ISSUE TITLE
Startup crash in 4.40.4 with SMS with email address.

### ISSUE THREAD

**Issue by nathanjw** [signalapp/Signal-Android#8855]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on startup, since I selected a particular SMS message to view. The stacktrace, extracted from the log, is as follows:

java.lang.AssertionError: Not e164: notifications@learnedleague.com
	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:134)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.handleIndividualRecipient(RetrieveProfileJob.java:99)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.onRun(RetrieveProfileJob.java:82)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)

This looks similar to:
#6841: Startup crash under 4.9.0 beta with email-to-SMS gateway message
#6844: Crash on startup due to "invalid" email
#8813: Signal crashes when email address entered intophone number

but the stacktrace is a bit different from those. In particular the recent in-flight fix for #8813,
https://github.com/signalapp/Signal-Android/commit/7db15885781e20d9adeaaecf22e9e700ff399020,
doesn't look like it will cover this case.

### Steps to reproduce
- Receive SMS messages that are "from" an email address
- Pick that sender/message in conversation view
- See app crash; attempt to reopen

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Instant crash, from database.Address.toPhoneString()

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Viewing the conversation

### Device info

**Device:** Google Pixel
**Android version:** 0.0.0
**Signal version:** 4.40.4

### Link to debug log

From logcat, since I can't get to the app's settings:
06-04 13:13:52.976   919   970 I ActivityManager: Start proc 6764:org.thoughtcrime.securesms/u0a248 for activity org.thoughtcrime.securesms/.RoutingActivity
06-04 13:13:53.054  6764  6764 E crime.securesm: Not starting debugger since process cannot load the jdwp agent.
06-04 13:13:53.179  6764  6764 I crime.securesm: The ClassLoaderContext is a special shared library.
06-04 13:13:53.552  6764  6764 I MultiDex: VM with version 2.1.0 has multidex support
06-04 13:13:53.553  6764  6764 I MultiDex: Installing application
06-04 13:13:53.553  6764  6764 I MultiDex: VM has multidex support, MultiDex support library is disabled.
06-04 13:13:53.633  6764  6764 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
06-04 13:13:53.634  6764  6764 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
06-04 13:13:53.634  6764  6764 D FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
06-04 13:13:53.634  6764  6764 I FirebaseInitProvider: FirebaseApp initialization successful
06-04 13:13:53.660  6764  6764 I PartProvider: onCreate()
06-04 13:13:53.665  6764  6764 I ApplicationContext: onCreate()
06-04 13:13:53.672  6764  6764 I ApplicationContext: Installed AesGcmProvider: 1
06-04 13:13:53.831  6764  6764 V NativeCrypto: Registering org/conscrypt/NativeCrypto's 284 native methods...
06-04 13:13:53.857  6764  6764 I ApplicationContext: Installed Conscrypt provider: 2
06-04 13:13:53.909  6764  6764 W Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
06-04 13:13:54.299  6764  6764 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-04 13:13:54.302  6764  6885 I IncomingMessageObserver: Waiting for websocket state change....
06-04 13:13:54.303  6764  6885 D IncomingMessageObserver: Network requirement: true, app visible: false, gcm disabled: false
06-04 13:13:54.307  6764  6764 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1559736152222
06-04 13:13:54.312  6764  6764 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1559669468006
06-04 13:13:54.317  6764  6764 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSenderCertificateListener scheduling for: 1559752888311
06-04 13:13:54.319  6764  6764 I org.webrtc.Logging: NativeLibrary: Loading native library: jingle_peerconnection_so
06-04 13:13:54.319  6764  6764 I org.webrtc.Logging: NativeLibrary: Loading library: jingle_peerconnection_so
06-04 13:13:54.338  6764  6882 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.361  6764  6882 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.363  6764  6764 I org.webrtc.Logging: PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
06-04 13:13:54.364  6764  6886 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.407  6764  6764 I PassphraseRequiredActionBarActivity: onCreate(null)
06-04 13:13:54.495  6764  6764 I ExperienceUpgradeActivity: getExperienceUpgrade(449)
06-04 13:13:54.496  6764  6764 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
06-04 13:13:54.505  6764  6764 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
06-04 13:13:54.624  6764  6764 I ApplicationContext: App is now visible.
06-04 13:13:54.626  6764  6885 D IncomingMessageObserver: Network requirement: true, app visible: true, gcm disabled: false
06-04 13:13:54.626  6764  6764 I PassphraseRequiredActionBarActivity: onResume()
06-04 13:13:54.627  6764  6885 I IncomingMessageObserver: Making websocket connection....
06-04 13:13:54.627  6764  6885 W WebSocketConnection: WSC connect()...
06-04 13:13:54.628  6764  6764 D OpenGLRenderer: Skia GL Pipeline
06-04 13:13:54.636  6764  6885 I SignalCommunicationModule: onConnecting()
06-04 13:13:54.638  6764  6885 W WebSocketConnection: WSC connect()...
06-04 13:13:54.650  6764  6885 I SignalCommunicationModule: onConnecting()
06-04 13:13:54.653  6764  6885 D IncomingMessageObserver: Network requirement: true, app visible: true, gcm disabled: false
06-04 13:13:54.654  6764  6885 I IncomingMessageObserver: Reading message...
06-04 13:13:54.677  6764  6899 I Adreno  : QUALCOMM build                   : d7977ce, Ife855c4895
06-04 13:13:54.677  6764  6899 I Adreno  : Build Date                       : 08/21/18
06-04 13:13:54.677  6764  6899 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.00.00
06-04 13:13:54.677  6764  6899 I Adreno  : Local Branch                     : master
06-04 13:13:54.677  6764  6899 I Adreno  : Remote Branch                    : 
06-04 13:13:54.677  6764  6899 I Adreno  : Remote Branch                    : 
06-04 13:13:54.677  6764  6899 I Adreno  : Reconstruct Branch               : 
06-04 13:13:54.677  6764  6899 I Adreno  : Build Config                     : S L 4.0.10 AArch32
06-04 13:13:54.683  6764  6899 I Adreno  : PFP: 0x005ff110, ME: 0x005ff066
06-04 13:13:54.688  6764  6899 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
06-04 13:13:54.688  6764  6899 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
06-04 13:13:54.689  6764  6899 I OpenGLRenderer: Initialized EGL, version 1.4
06-04 13:13:54.689  6764  6899 D OpenGLRenderer: Swap behavior 1
06-04 13:13:54.734  6764  6886 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.763  6764  6889 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.766  6764  6887 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.766  6764  6882 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.798  6764  6889 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.800  6764  6897 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.801  6764  6882 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.809  6764  6897 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.924  6764  6764 I JobManager: onConstraintMet(NetworkConstraintObserver)
06-04 13:13:54.967  6764  6912 I JobRunner: [98fdd9e0-ca34-428e-a9c1-03b85cc9b320][RetrieveProfileJob][1] Running job. (Time Since Submission: 2494953 ms, Lifespan: Immortal, Run Attempt: 1/3)
06-04 13:13:54.968  6764  6912 D WakeLockUtil: Acquired wakelock with tag: 98fdd9e0-ca34-428e-a9c1-03b85cc9b320
06-04 13:13:54.968  6764  6901 V Cursor  : Filling cursor window with start position:0 required position:0
06-04 13:13:54.984  6764  6912 D WakeLockUtil: Released wakelock with tag: 98fdd9e0-ca34-428e-a9c1-03b85cc9b320
06-04 13:13:54.987  6764  6912 E AndroidRuntime: FATAL EXCEPTION: JobRunner-1
06-04 13:13:54.987  6764  6912 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6764
06-04 13:13:54.987  6764  6912 E AndroidRuntime: java.lang.AssertionError: Not e164: notifications@learnedleague.com
06-04 13:13:54.987  6764  6912 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:134)
06-04 13:13:54.987  6764  6912 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.handleIndividualRecipient(RetrieveProfileJob.java:99)
06-04 13:13:54.987  6764  6912 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.onRun(RetrieveProfileJob.java:82)
06-04 13:13:54.987  6764  6912 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-04 13:13:54.987  6764  6912 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-04 13:13:54.987  6764  6912 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: java.lang.AssertionError: Not e164: notifications@learnedleague.com
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:134)
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.handleIndividualRecipient(RetrieveProfileJob.java:99)
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.onRun(RetrieveProfileJob.java:82)
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-04 13:13:54.987  6764  6912 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-04 13:13:55.021  6764  6912 I Process : Sending signal. PID: 6764 SIG: 9
06-04 13:13:55.035   682   682 E lowmemorykiller: Error writing /proc/6764/oom_score_adj; errno=22
06-04 13:13:55.123   919  4421 I ActivityManager: Process org.thoughtcrime.securesms (pid 6764) has died: vis  +99TOP 
06-04 13:13:55.137   615   615 I Zygote  : Process 6764 exited due to signal (9)
06-04 13:13:55.155   919  1034 W ActivityManager: setHasOverlayUi called on unknown pid: 6764
06-04 13:13:55.302   919   971 W libprocessgroup: kill(-6764, 9) failed: No such process
06-04 13:13:55.302   919   971 I libprocessgroup: Successfully killed process cgroup uid 10248 pid 6764 in 0ms
06-04 13:32:38.093 24236 24271 I ConversationActivity: Loading identity for: +16177676488
06-04 13:33:06.030 24445 24484 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/profile/+16177676488
06-04 13:33:06.052 24445 24484 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/profile/+16177676488
06-04 13:38:31.772 26733 26764 D NetworkSecurityConfig: No Network Security Config specified, using platform default

**Comment by nathanjw** [comment]
Updated to beta channel in Play store. Crashes almost the same way, with the fix for #8813 included:

FATAL EXCEPTION: JobRunner-1
Process: org.thoughtcrime.securesms, PID: 17576
java.lang.AssertionError: Not e164, is email
	at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:135)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.handleIndividualRecipient(RetrieveProfileJob.java:99)
	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob.onRun(RetrieveProfileJob.java:82)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
