### ISSUE TITLE
Trying to select text in long message view results in a crash

### ISSUE THREAD

**Issue by inthewaves** [signalapp/Signal-Android#8872]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The app crashes when attempting to select text in long message view

### Steps to reproduce
- Send or receive a long message
- Go into the long message
- Try to select and deselect text

**Actual result:** Crashes when trying to select text
**Expected result:** No crash

### Screenshots

<img src="https://user-images.githubusercontent.com/26474149/59394404-197cb400-8d6f-11e9-8150-9fef6b5a8941.gif" width="50%"/>

This is the text being used:

>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
>
>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

### Device info

**Device:** Samsung S6
**Android version:** 7.0
**Signal version:** 4.41.6

### Link to debug log

This debug log is from shortly after the GIF was recorded

https://debuglogs.org/c4990e9c8192a3f80d3c3019d89b1e6894219a7ed02b178194503b4539877ce2

These seem to be the relevant lines. I've reproduced the bug multiple times on the S6 and similar lines appear throughout the log.

```
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:434)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:155)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.text.SpannableString.setSpan(SpannableString.java:46)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.text.Selection.setSelection(Selection.java:76)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.widget.Editor$HandleView$4.onAnimationEnd(Editor.java:5228)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.view.Choreographer.doFrame(Choreographer.java:635)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:751)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:95)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:154)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
2019-06-12 16:53:11.736 PDT E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by westonal** [comment]
It's an Android bug https://issuetracker.google.com/issues/37068143

I expect you can produce it in other apps on that device.

There's a hacky fix here https://stackoverflow.com/a/36740247/360211 

I doubt we want to go through the whole app finding and replacing every instance of text view that might get copied but we will consider it.

**Comment by alan-signal** [comment]
> I expect you can reproduce it in other apps on that device.

Out of interest, were you able to cause on any other apps?

**Comment by inthewaves** [comment]
No, I've tried doing the same steps in Conversations and the long message view in the default Samsung Messenger app but I haven't ran into any crashes
