### ISSUE TITLE
Signal crashes on startup with contacts-related NPE

### ISSUE THREAD

**Issue by praus** [signalapp/Signal-Android#8877]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
A couple weeks ago, Signal started to *always* crash on my phone. I don't remember doing anything in particular. I noticed when one day I got a message, wanted to open it, and the app crashed. Whenever I tried to start it from the menu it would crash almost immediately. I remember this was a problem at least on 4.41.5 a now on 4.41.6.

Signal crashed both when I tried recovering from an existing backup and when I tried to go to a fresh slate. Today I got around to looking at logcat. The app was crashing with an NPE when it tried to do something with contacts. It turns out the app won't crash if I deny contacts permission on Android level. But if I denied access to contacts during setup, it wouldn't let me restore from backup. So I allowed access to contacts during the backup restoration process (after fresh install from app store) and let the app crash afterwards. Then I disabled contacts permission, started the app, and it worked!

Later on I was reading the debug log and I saw that Signal wrote log messages like these "Adding: +1206xxxxxxx". I looked at the last phone number just before the crash. It was a contact that had nothing special about it. Just a phone number and a name. I also didn't really care about preserving it. I thought maybe something in the contact record itself caused the crash so I deleted the contact. I then re-enabled contacts permission and Signal now works. Unfortunately, I haven't tried re-enabling the permission and starting the app before deleting the contact so I'm not sure whether temporarily removing the contacts permission was the thing that got it working or whether it was the contact I deleted. My bad.

### Steps to reproduce
Unfortunately, I'm not able to reproduce this issue once I fixed it as described above.

### Screenshots
None, app crashed immediately.

### Device info
**Device:** OnePlus 5. build A5000_23_190610
**Android version:** Android 9, OP5_O2_BETA_34
**Signal version:** 4.41.6

### Crash stack trace
```plain
06-17 21:40:09.678 30912 30957 E DirectoryHelper: [Batch] Experienced an unexpected exception.
06-17 21:40:09.678 30912 30957 E DirectoryHelper: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:112)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:80)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:71)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:208)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.util.DirectoryHelper.lambda$getLegacyDirectoryResult$1(DirectoryHelper.java:312)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at org.thoughtcrime.securesms.util.-$$Lambda$DirectoryHelper$LX0BDH9uvGu4L9C6BQ7CR3rVnes.call(Unknown Source:8)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-17 21:40:09.678 30912 30957 E DirectoryHelper: 	at java.lang.Thread.run(Thread.java:764)
06-17 21:40:09.679 30912 30957 D WakeLockUtil: Released wakelock with tag: signal:a99faa5e-796a-47c0-bcc0-2f319fd61404
06-17 21:29:43.817 29096 29133 E AndroidRuntime: FATAL EXCEPTION: JobRunner-1
06-17 21:29:43.817 29096 29133 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 29096
06-17 21:29:43.817 29096 29133 E AndroidRuntime: java.lang.AssertionError: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:137)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:80)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:71)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:112)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	... 5 more
06-17 21:29:43.817 29096 29133 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:208)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.lambda$getLegacyDirectoryResult$1(DirectoryHelper.java:312)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.-$$Lambda$DirectoryHelper$LX0BDH9uvGu4L9C6BQ7CR3rVnes.call(Unknown Source:8)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-17 21:29:43.817 29096 29133 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: FATAL EXCEPTION: JobRunner-4
06-17 21:40:09.679 30912 30957 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 30912
06-17 21:40:09.679 30912 30957 E AndroidRuntime: java.lang.AssertionError: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:137)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:80)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:71)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:112)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	... 5 more
06-17 21:40:09.679 30912 30957 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:208)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.DirectoryHelper.lambda$getLegacyDirectoryResult$1(DirectoryHelper.java:312)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.-$$Lambda$DirectoryHelper$LX0BDH9uvGu4L9C6BQ7CR3rVnes.call(Unknown Source:8)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-17 21:40:09.679 30912 30957 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: java.lang.AssertionError: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:137)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:80)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.DirectoryRefreshJob.onRun(DirectoryRefreshJob.java:71)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:20)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:71)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:37)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectory(DirectoryHelper.java:112)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	... 5 more
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.DirectoryHelper.updateContactsDatabase(DirectoryHelper.java:208)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.DirectoryHelper.lambda$getLegacyDirectoryResult$1(DirectoryHelper.java:312)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.-$$Lambda$DirectoryHelper$LX0BDH9uvGu4L9C6BQ7CR3rVnes.call(Unknown Source:8)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-17 21:40:09.679 30912 30957 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:764)
```

### Link to debug log
https://www.dropbox.com/s/n0rm2ycqcd2xksq/setup-signal.log?dl=0

**Comment by greyson-signal** [comment]
The code where this crash happened has changed, and since there's no repro, I'll close this until we see it again.
