### ISSUE TITLE
Sending multiple images fails

### ISSUE THREAD

**Issue by jost-s** [signalapp/Signal-Android#8929]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------
### Bug description
Sending multiple images to someone doesn't work

### Steps to reproduce
- Select a chat with someone
- Click `+` -> `Gallery`
- Select 2 or more images
- Click on the number with arrow in the right bottom corner
- (Enter a comment)
- Click on the send button

**Actual result:** The screen is white for a moment and then the chat reappears without the images being sent, with only the content it had before trying to send the images.

**Expected result:** The previously selected images should appear in the chat and should be sent.

### Device info

**Device:** Huawei P8
**Android version:** 6.0
**Signal version:** 4.43.8

### Link to debug log

https://debuglogs.org/b2bfcea58ebe8753e19c10e57344949026a8e5e062ce521f2af7974a81697482

#8929 This is a similar issue

**Comment by greyson-signal** [comment]
Looks like an OOM.

```java
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: There was 1 cause:
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: java.lang.OutOfMemoryError(Failed to allocate a 50331660 byte allocation with 4194304 free bytes and 39MB until OOM)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger:  call GlideException#logRootCauses(String) for more detail
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.scribbles.UriGlideRenderer.render(UriGlideRenderer.java:63)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorElement.drawSelf(EditorElement.java:119)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorElement.draw(EditorElement.java:104)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorElement.drawChildren(EditorElement.java:124)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorElement.draw(EditorElement.java:110)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorElement.drawChildren(EditorElement.java:124)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorElement.draw(EditorElement.java:110)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.imageeditor.model.EditorModel.render(EditorModel.java:552)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.mediasend.MediaSendFragment.lambda$render$10(MediaSendFragment.java:509)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.mediasend.-$$Lambda$MediaSendFragment$IzWa5YnqvNsdVZ3uSj1c0i1T980.run(lambda)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:833)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: Caused by: java.util.concurrent.ExecutionException: com.bumptech.glide.load.engine.GlideException: Failed to load resource
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: There was 1 cause:
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: java.lang.OutOfMemoryError(Failed to allocate a 50331660 byte allocation with 4194304 free bytes and 39MB until OOM)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger:  call GlideException#logRootCauses(String) for more detail
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:205)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:108)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.scribbles.UriGlideRenderer.render(UriGlideRenderer.java:60)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: 	... 12 more
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: Caused by: com.bumptech.glide.load.engine.GlideException: Failed to load resource
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: There was 1 cause:
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger: java.lang.OutOfMemoryError(Failed to allocate a 50331660 byte allocation with 4194304 free bytes and 39MB until OOM)
07-13 15:27:26.286 31211 31269 E UncaughtExceptionLogger:  call GlideException#logRootCauses(String) for more detail
```

**Comment by jost-s** [comment]
Right, I see it. That's odd, I have almost 2 GB of memory available and wanted to send 5 images of 5 MB each. But it explains why it sometimes works.

Is there something wrong with memory allocation then?

**Comment by jost-s** [comment]
@greyson-signal @alan-signal Thank you guys for addressing this! Look forward to the release
