### ISSUE TITLE
crash on photo opening

### ISSUE THREAD

**Issue by unInstance** [signalapp/Signal-Android#8940]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
the app crashes each time i open with a tap a sent/received picture

### Steps to reproduce
open any sent/received picture

Actual result: crash
Expected result: i wish it didn't crash

### Screenshots
it just crashes

### Device info

Device: xiaomi mi mix 2 (aka chiron)
Android version: 9 (aka pie)
Signal version: 4.44.0

### Link to debug log

https://debuglogs.org/f2ed0d246af2fbc636ab6e2133d03e5d92a4c7d30e8ce644a4999d98dc32cc08

**Comment by u32i64** [comment]
Also reproducible on:

**Device**: Pixel 3 XL
**Android version**: Q Beta 5
**Signal version**: 4.44.0

Here is an excerpt from my debug log:
```
XX:XX:16.898 I MediaPreviewActivity: Loading Part URI: content://org.thoughtcrime.securesms/part/1563884955709/85
XX:XX:16.925 E UncaughtExceptionLogger: 
XX:XX:16.925 E UncaughtExceptionLogger: java.lang.IllegalStateException: Fragment org.thoughtcrime.securesms.mediapreview.ImageMediaPreviewFragment must be a public static class to be  properly recreated from instance state.
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:165)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:179)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:134)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.fragment.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:195)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
XX:XX:16.925 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:403)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
XX:XX:16.925 E UncaughtExceptionLogger: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:737)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.View.measure(View.java:24530)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2997)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1826)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2115)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1714)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7587)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:883)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:100)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:214)
XX:XX:16.925 E UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:7343)
XX:XX:16.925 E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
XX:XX:16.925 E UncaughtExceptionLogger: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
XX:XX:16.925 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
XX:XX:17.173 I IncomingMessageObserver: Waiting for websocket state change....
XX:XX:17.175 D IncomingMessageObserver: Network requirement: true, app visible: false, gcm disabled: false
XX:XX:17.175 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1563945774809
XX:XX:17.176 I RevealableMessageManage: No messages to schedule.
XX:XX:17.176 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1563903918935
XX:XX:17.176 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.LocalBackupListener scheduling for: 1563953525467
XX:XX:17.177 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSenderCertificateListener scheduling for: 1563946419918
XX:XX:17.202 I PassphraseRequiredActionBarActivity: onCreate(Bundle[{android:viewHierarchyState=Bundle[mParcelledData.dataSize=832], a**************************************************************************c, androidx.lifecycle.BundlableSavedStateRegistry.key=Bundle[EMPTY_PARCEL], android:lastAutofillId=1073741823, a**********************************************************])
XX:XX:17.281 I ExperienceUpgradeActivity: getExperienceUpgrade(494)
XX:XX:17.282 I PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
XX:XX:17.287 I PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
XX:XX:17.321 I ApplicationContext: App is now visible.
```

**Comment by user45876** [comment]
Same here:
(same description)

### **Device info**
Device: Samsung Galaxy S10+
Android version: 9 (aka pie)
Signal version: 4.44.0

### **Link to debug log**
https://debuglogs.org/ef09a3f702e83f395f33853fce5d92de75613975acc6f7d3f3ac2ac7bd7c5620

**Comment by user45876** [comment]
Great, thanks. Just saw it, sorry for bringing it up. Bad timing on my side.

Greyson Parrelli <notifications@github.com> schrieb am Di., 23. Juli 2019,
15:51:
