### ISSUE TITLE
New media flow not working on pixel 3. Can take a pic but no button for contacts

### ISSUE THREAD

**Issue by nutts0** [signalapp/Signal-Android#8950]
https://debuglogs.org/459f4749cc5627b7c33b8c41e7bd925767ca1858fed56a2b8e704ffd280f0604

**Comment by greyson-signal** [comment]
Looks like I forgot to put a permissions check in for the contact selection screen.

```java
07-25 08:46:34.540  7602  7684 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{2c8f2d3 7602:org.thoughtcrime.securesms/u0a170} (pid=7602, uid=10170) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1950)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4185)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6019)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2592)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1829)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:787)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:753)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:711)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactsDatabase.queryTextSecureContacts(ContactsDatabase.java:216)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.CameraContactsRepository.getContacts(CameraContactsRepository.java:80)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.CameraContactsRepository.lambda$getCameraContacts$0(CameraContactsRepository.java:50)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.-$$Lambda$CameraContactsRepository$c2j0bJnpfm3CODBWKEAkCfPO2YE.run(Unknown Source:6)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12359)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:12651)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3297)
07-25 08:46:34.540  7602  7684 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:731)
```

In the short term, if you'd like to use this feature, enable the contact permission in the system permission settings for Signal.

Thanks!
