### ISSUE TITLE
Crash with 64 bit version

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#8969]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I install the 64 bit version (build nr 5162) on my phone (Sony M4 Aqua), it crashes as soon as I open a conversation. When I install the 32 bit version  (build nr 5161) over it, it works without problem.

### Steps to reproduce
- Install 64-bit Signal
- Open Signal
- Open an existing conversation
- Crash

**Actual result:** Crash
**Expected result:** Show the conversation contents

### Device info
**Device:** Sony M4 Auqa, rooted, no Xposed
**Android version:** 5.0
**Signal version:** 4.45.0

### Link to debug log
I had to get the debuglog after I installed the 32 bit version because submitting the debuglog also resulted in a crash. Seems like an issue with an incorrect library being called:
```
 Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
```
It might be an issue with the device though, because Sygic (a navigation app) has also problems when I install the 64 bit version.

https://debuglogs.org/aa50e2984fa17f4b43a448672c66220b54e42878e202642c32aea957f7d85091

**Comment by alan-signal** [comment]
Would you try the universal build out of interest? 516**5**

Pasting full crash:

```
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: android.view.InflateException: Binary XML file line #51: Error inflating class TextView
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.util.ViewUtil.inflate(ViewUtil.java:176)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.ConversationAdapter.onCreateItemViewHolder(ConversationAdapter.java:219)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.ConversationAdapter.onCreateItemViewHolder(ConversationAdapter.java:75)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.onCreateViewHolder(CursorRecyclerViewAdapter.java:146)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1649)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1638)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1413)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.View.layout(View.java:15691)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewGroup.layout(ViewGroup.java:4967)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2093)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1850)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5807)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.Choreographer.doFrame(Choreographer.java:550)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:739)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:95)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:135)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:5319)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Method.java:372)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: Caused by: android.util.AndroidRuntimeException: java.lang.RuntimeException: Cannot load WebView
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:117)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.webkit.WebView.getFactory(WebView.java:2185)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.webkit.WebView.findAddress(WebView.java:1622)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.text.util.Linkify.gatherMapLinks(Linkify.java:469)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.text.util.Linkify.addLinks(Linkify.java:234)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.TextView.setText(TextView.java:4019)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.TextView.setText(TextView.java:3941)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.TextView.<init>(TextView.java:1322)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.widget.TextView.<init>(TextView.java:639)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:98)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:94)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1389)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1439)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	... 80 more
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: Caused by: java.lang.RuntimeException: Cannot load WebView
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.chromium.android_webview.AwBrowserProcess.a(PG:14)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:117)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(PG:22)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at java.lang.reflect.Constructor.newInstance(Native Method)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at java.lang.Class.newInstance(Class.java:1572)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:112)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	... 95 more
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: Caused by: BZ
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.chromium.base.library_loader.LibraryLoader.g(PG:80)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.chromium.base.library_loader.LibraryLoader.a(PG:21)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.chromium.android_webview.AwBrowserProcess.a(PG:8)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	... 100 more
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at java.lang.System.loadLibrary(System.java:989)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	at org.chromium.base.library_loader.LibraryLoader.g(PG:62)
2019-08-02 01:16:54.907 GMT+02:00 E UncaughtExceptionLogger: 	... 102 more
```

**Comment by johanw666** [comment]
The universal build crashes with the same error: https://debuglogs.org/0144b6be20c0b470c4ef1a3dbf041e185e7647331cf86aab5d4b6756b960b045

**Comment by johanw666** [comment]
I solved the issue. I manually installed the Webview component on that device and installed only the 32-bit version (https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-76-0-3809-89-release/android-system-webview-76-0-3809-89-7-android-apk-download/) where I should have installed https://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-76-0-3809-89-release/android-system-webview-76-0-3809-89-5-android-apk-download/ . After I installed the last one the crash did not happen with the 64-bit version.
