### ISSUE TITLE
Signal crashes always when entering any conversation

### ISSUE THREAD

**Issue by Glasses8448** [signalapp/Signal-Android#8977]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Since the latest Singal update I cant open my conversations anymore. Signal crashes when I enter any chat. Signal also crashes when I tap on the seach icon. 

### Steps to reproduce
- entering a conversation
- entering the search

**Actual result:** Signal chrashes :" Signal keeps stopping"

**Expected result:** Conversations opens.

### Device info
**Device:** Samsung J5 SM-J500FN
**Android version:** 7.1.2
**Signal version:** 4.44.7

### Link to debug log
https://debuglogs.org/3f7d19592ced62a1f06e17844d0f8fc03babb97d8d88b5c24b0e8f4595f28835

**Comment by greyson-signal** [comment]
```java
08-07 15:52:14.592  2062  3869 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: vtable constructor failed: sms_fts: , while compiling: UPDATE sms SET read=? WHERE thread_id = ? AND read = 0
```

```java
2019-08-10 13:07:48.345 MESZ E UncaughtExceptionLogger: net.sqlcipher.database.SQLiteException: vtable constructor failed: sms_fts: , while compiling: SELECT thread.recipient_ids AS conversation_address, address AS message_address, snippet(sms_fts, -1, '', '', '...', 7) AS snippet, sms.date AS date_received, sms_fts.thread_id FROM sms INNER JOIN sms_fts ON sms_fts.rowid = sms._id INNER JOIN thread ON sms_fts.thread_id = thread._id WHERE sms_fts MATCH ? UNION ALL SELECT thread.recipient_ids AS conversation_address, address AS message_address, snippet(mms_fts, -1, '', '', '...', 7) AS snippet, mms.date_received AS date_received, mms_fts.thread_id FROM mms INNER JOIN mms_fts ON mms_fts.rowid = mms._id INNER JOIN thread ON mms_fts.thread_id = thread._id WHERE mms_fts MATCH ? ORDER BY date_received DESC LIMIT 500
```

Looks like there's some native SQL crash here that we're not seeing anywhere else.

1. Did you recently update? Do you know which version you updated from?
2. I see you're running Lineage. Do you have any xposed plugins running? Have you been using a third-party backup tool? Have you edited internal storage at all?

**Comment by Glasses8448** [comment]
Yesterday, I reinstalled signal without restoring thee backup. Now it works just fine.

**Comment by mossroy** [comment]
I just had a very similar issue.
I was using Signal 4.58.5 (installed from the Signal provided apk 4.57.2, and upgraded OTA through WiFi), on LineageOS for MicroG 16.0 on Samsung S5 (klte). Without any xposed plugin. No third-party backup tool, no manual edition of internal storage.

Signal crashed with the following adb log on every attempt to open any conversation. Rebooting the device did not help.
Trying to use the built-in feature to send debug logs was crashing the app too.

But I could export the conversations with the built-in feature (it did not crash), uninstalled Signal, reinstalled it (from a freshly downloaded 4.58.5 apk), re-imported the conversations. The crash disappeared, it's now working fine.

```
04-17 20:36:08.227 10277 10421 V Cursor  : Filling cursor window with start position:0 required position:0
04-17 20:36:08.234 10277 10421 E Database: Error updating <redacted values> using <redacted sql> for sms
04-17 20:36:08.240 10277 10421 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
04-17 20:36:08.240 10277 10421 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 10277
04-17 20:36:08.240 10277 10421 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: vtable constructor failed: sms_fts: , while compiling: UPDATE sms SET read=? WHERE thread_id = ? AND read = 0
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1647)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2306)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.update(SQLiteDatabase.java:2253)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.setMessagesRead(SmsDatabase.java:501)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.setMessagesRead(SmsDatabase.java:467)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.ThreadDatabase.setRead(ThreadDatabase.java:322)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity$21.doInBackground(ConversationActivity.java:2174)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity$21.doInBackground(ConversationActivity.java:2170)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-17 20:36:08.240 10277 10421 E AndroidRuntime: 	... 3 more
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:764)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: Caused by: net.sqlcipher.database.SQLiteException: vtable constructor failed: sms_fts: , while compiling: UPDATE sms SET read=? WHERE thread_id = ? AND read = 0
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1647)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2306)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at net.sqlcipher.database.SQLiteDatabase.update(SQLiteDatabase.java:2253)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.database.SmsDatabase.setMessagesRead(SmsDatabase.java:501)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.database.SmsDatabase.setMessagesRead(SmsDatabase.java:467)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.database.ThreadDatabase.setRead(ThreadDatabase.java:322)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity$21.doInBackground(ConversationActivity.java:2174)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity$21.doInBackground(ConversationActivity.java:2170)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-17 20:36:08.240 10277 10421 E SignalUncaughtExceptionHandler: 	... 3 more
04-17 20:36:08.244 10277 10434 I ConversationActivity: Resolving registered state...
04-17 20:36:08.244 10277 10434 I ConversationActivity: Checking through resolved recipient
04-17 20:36:08.244 10277 10434 I ConversationActivity: Resolved registered state: REGISTERED
04-17 20:36:08.244 10277 10434 I ConversationActivity: Returning registered state...
04-17 20:36:08.251 10277 10277 I ConversationActivity: onSecurityUpdated()
04-17 20:36:08.252 10277 10277 I ConversationActivity: updateDefaultSubscriptionId(null)

```

**Comment by mossroy** [comment]
For the record, I suspect that my issue above was due to some faulty hardware, that was corrupting the filesystem.
