### ISSUE TITLE
Can't get push notification with old signal

### ISSUE THREAD

**Issue by akworld111** [signalapp/Signal-Android#9040]
I'm using old signal-android and I'm trying to update GCM to FCM in that code.
But can't get push notification with this AuthorizationFailedException: 
Not sure what is the reason.

W/PushNotificationReceiveJob: null
    org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:757)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:207)
        at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:162)
        at PushNotificationReceiveJob.pullAndProcessMessages(PushNotificationReceiveJob.java:62)
        at PushNotificationReceiveJob.onRun(PushNotificationReceiveJob.java:57)
        at jobmanager.Job.doWork(Job.java:75)
        at androidx.work.Worker$1.run(Worker.java:95)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-20 10:36:25.970 27635-27700 W/Job: [4c54d032-7c68-44bb-8089-d2a29893cfff] PushNotificationReceiveJob :: Failing due to an exception. (Time since submission: 21161 ms, Run attempt: 0)
    org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:757)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.getMessages(PushServiceSocket.java:207)
        at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveMessages(SignalServiceMessageReceiver.java:162)
        at PushNotificationReceiveJob.pullAndProcessMessages(PushNotificationReceiveJob.java:62)
        at PushNotificationReceiveJob.onRun(PushNotificationReceiveJob.java:57)
        at zone.blackcap.vpn.jobmanager.Job.doWork(Job.java:75)
        at androidx.work.Worker$1.run(Worker.java:95)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-20 10:36:25.970 27635-27700 W/PushNotificationReceiveJob: ***** Failed to download pending message!

**Comment by greyson-signal** [comment]
Hi there, we don't use Github for this type of support. We only use it for bug reports on our own releases. You might be able to find more assistance on [the forum](https://community.signalusers.org/). Thank you!
