### ISSUE TITLE
Signal crashes entering a number in the contact view

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#9084]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- Go to the "contact view" (see screenshots):
- Enter a few digits and Signal crashes. Simply entering *000* is enough on my phone.

**Actual result:** Crash
**Expected result:** No crash

### Screenshots

![a](https://user-images.githubusercontent.com/11895833/66433900-e42c5e00-ea10-11e9-8fe3-409fc9746ddb.png)
![b](https://user-images.githubusercontent.com/11895833/66433901-e4c4f480-ea10-11e9-9e82-3c73bb533da8.png)

### Device info

**Device:** Motorola one vision
**Android version:** 9
**Signal version:** 4.48.14

### Link to debug log
[full log](https://debuglogs.org/2fa257e2e01b8d262b0f5c7c1dfc6f62283f2db066834c0045fc890ec6cbf773)

relevant section:

```
10-08 22:48:52.078 22351 22351 E AndroidRuntime: FATAL EXCEPTION: main
10-08 22:48:52.078 22351 22351 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 22351
10-08 22:48:52.078 22351 22351 E AndroidRuntime: org.thoughtcrime.securesms.database.RecipientDatabase$MissingRecipientError: Failed to find recipient with ID: RecipientId::-1
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.RecipientDatabase.getRecipientSettings(RecipientDatabase.java:234)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipient.fetchRecipientFromDisk(LiveRecipient.java:173)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.LiveRecipient.resolve(LiveRecipient.java:132)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.Recipient.resolve(Recipient.java:374)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.Recipient.requireAddress(Recipient.java:238)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.Recipient.isGroup(Recipient.java:265)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.Recipient.getContactPhoto(Recipient.java:299)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.AvatarImageView$RecipientContactPhoto.<init>(AvatarImageView.java:151)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.AvatarImageView.setAvatar(AvatarImageView.java:99)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactSelectionListItem.set(ContactSelectionListItem.java:76)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter$ContactViewHolder.bind(ContactSelectionListAdapter.java:101)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.onBindItemViewHolder(ContactSelectionListAdapter.java:191)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.contacts.ContactSelectionListAdapter.onBindItemViewHolder(ContactSelectionListAdapter.java:54)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.CursorRecyclerViewAdapter.onBindViewHolder(CursorRecyclerViewAdapter.java:157)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.adapter.RecyclerViewConcatenateAdapter.onBindViewHolder(RecyclerViewConcatenateAdapter.java:252)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:792)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.View.layout(View.java:20685)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6197)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2834)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2361)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1497)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7306)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:220)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6929)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-08 22:48:52.078 22351 22351 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by greyson-signal** [comment]
Fixed in 4.48.15. Thanks!
