### ISSUE TITLE
crash when filesystem is read-only when attempting to share some content

### ISSUE THREAD

**Issue by muelli** [signalapp/Signal-Android#9087]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal is crashing as soon as I share, say, an image from the Gallery App with the share button. I see the list of apps to share with popping up and I suppose Android is waiting for the apps, among them Signal, to offer contacts so that I can directly share to the contact rather than the app.

### Steps to reproduce
- open image in gallery app
- press share button
- see the list of apps to share with popping up
- wait another second or so to see it crash.

**Actual result:**

Then it says "Signal has closed...". This is interestingly followed by "The Android system has closed..."

**Expected result:** 
I expected it to not crash. And I expected Android to not crash...

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 7.1.1
**Signal version:** 4.47.7

### Link to debug log
```
E/PersistentLogger(24964): java.io.FileNotFoundException: /mnt/expand/89ea3d3a-c1b8-4172-ace2-d59f83128f4e/user/0/org.thoughtcrime.securesms/cache/log/log-1570637503639 (Read-only file system)
E/PersistentLogger(24964): 	at java.io.FileOutputStream.open(Native Method)
E/PersistentLogger(24964): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
E/PersistentLogger(24964): 	at org.thoughtcrime.securesms.logging.LogFile$Writer.<init>(LogFile.java:43)
E/PersistentLogger(24964): 	at org.thoughtcrime.securesms.logging.PersistentLogger.initializeWriter(PersistentLogger.java:133)
E/PersistentLogger(24964): 	at org.thoughtcrime.securesms.logging.PersistentLogger.lambda$LIQJDWTfkGAT-_rlmrMYuO5Bba8(PersistentLogger.java)
E/PersistentLogger(24964): 	at org.thoughtcrime.securesms.logging.-$$Lambda$PersistentLogger$LIQJDWTfkGAT-_rlmrMYuO5Bba8.run(lambda)
E/PersistentLogger(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/PersistentLogger(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/PersistentLogger(24964): 	at java.lang.Thread.run(Thread.java:761)
D/SoftKeymaster(  609): system/keymaster/soft_keymaster_device.cpp, Line 691: Not performing software digesting for algorithm 32
D/SoftKeymaster(  609): system/keymaster/soft_keymaster_device.cpp, Line 1202: Operation supported by Keymaster QTI HAL, passing through to keymaster1 module
D/SoftKeymaster(  609): system/keymaster/soft_keymaster_device.cpp, Line 691: Not performing software digesting for algorithm 32
D/SoftKeymaster(  609): system/keymaster/soft_keymaster_device.cpp, Line 1202: Operation supported by Keymaster QTI HAL, passing through to keymaster1 module
D/ApplicationMigrations(24964): Not an update. Skipping.
I/IncomingMessageObserver(24964): Waiting for websocket state change....
D/IncomingMessageObserver(24964): Network requirement: true, app visible: false, gcm disabled: false
I/PersistentAlarmManagerListener(24964): class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1570785604062
E/SQLiteOpenHelper(24964): Couldn't open signal.db for writing (will try read-only):
E/SQLiteOpenHelper(24964): net.sqlcipher.database.SQLiteException: not an error: Could not open the database in read/write mode.
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2510)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:47)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:64)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
E/SQLiteOpenHelper(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/SQLiteOpenHelper(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/SQLiteOpenHelper(24964): 	at java.lang.Thread.run(Thread.java:761)
I/PersistentAlarmManagerListener(24964): class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1570746934737
E/SharedPreferencesImpl(24964): Couldn't rename file /mnt/expand/89ea3d3a-c1b8-4172-ace2-d59f83128f4e/user/0/org.thoughtcrime.securesms/shared_prefs/org.thoughtcrime.securesms_preferences.xml to backup file /mnt/expand/89ea3d3a-c1b8-4172-ace2-d59f83128f4e/user/0/org.thoughtcrime.securesms/shared_prefs/org.thoughtcrime.securesms_preferences.xml.bak
I/PersistentAlarmManagerListener(24964): class org.thoughtcrime.securesms.service.RotateSenderCertificateListener scheduling for: 1570715820703
I/UpdateApkRefreshListener(24964): onAlarm...
I/UpdateApkRefreshListener(24964): Queueing APK update job...
I/PersistentAlarmManagerListener(24964): class org.thoughtcrime.securesms.service.UpdateApkRefreshListener scheduling for: 1570725334747
E/SharedPreferencesImpl(24964): Couldn't rename file /mnt/expand/89ea3d3a-c1b8-4172-ace2-d59f83128f4e/user/0/org.thoughtcrime.securesms/shared_prefs/org.thoughtcrime.securesms_preferences.xml to backup file /mnt/expand/89ea3d3a-c1b8-4172-ace2-d59f83128f4e/user/0/org.thoughtcrime.securesms/shared_prefs/org.thoughtcrime.securesms_preferences.xml.bak
I/org.webrtc.Logging(24964): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(24964): NativeLibrary: Loading library: jingle_peerconnection_so
I/org.webrtc.Logging(24964): PeerConnectionFactory: PeerConnectionFactory was initialized without an injected Loggable. Any existing Loggable will be deleted.
I/CameraManagerGlobal(24964): Connecting to camera service
D/CameraRepository(24964): Added camera: 0
D/CameraRepository(24964): Added camera: 1
D/UseCaseAttachState(24964): Active and online use case: [] for camera: 0
D/UseCaseAttachState(24964): Active and online use case: [] for camera: 1
D/IncomingMessageObserver(24964): Network requirement: true, app visible: false, gcm disabled: false
E/Database(24964): file is not a database: , while compiling: select count(*) from sqlite_master;
E/Database(24964): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
E/Database(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
E/Database(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
E/Database(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
E/Database(24964): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
E/Database(24964): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
E/Database(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
E/Database(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/Database(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/Database(24964): 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
E/Database(24964): 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:47)
E/Database(24964): 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:64)
E/Database(24964): 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
E/Database(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/Database(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/Database(24964): 	at java.lang.Thread.run(Thread.java:761)
E/UncaughtExceptionLogger(24964): 
E/UncaughtExceptionLogger(24964): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:47)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:64)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
E/UncaughtExceptionLogger(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/UncaughtExceptionLogger(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/UncaughtExceptionLogger(24964): 	at java.lang.Thread.run(Thread.java:761)
--------- beginning of crash
E/AndroidRuntime(24964): FATAL EXCEPTION: signal-JobManager
E/AndroidRuntime(24964): Process: org.thoughtcrime.securesms, PID: 24964
E/AndroidRuntime(24964): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
E/AndroidRuntime(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/AndroidRuntime(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/AndroidRuntime(24964): 	at org.thoughtcrime.securesms.database.JobDatabase.getAllJobSpecs(JobDatabase.java:106)
E/AndroidRuntime(24964): 	at org.thoughtcrime.securesms.jobs.FastJobStorage.init(FastJobStorage.java:47)
E/AndroidRuntime(24964): 	at org.thoughtcrime.securesms.jobmanager.JobManager.lambda$new$0(JobManager.java:64)
E/AndroidRuntime(24964): 	at org.thoughtcrime.securesms.jobmanager.-$$Lambda$JobManager$9Zi9v05tPAq4MHHBB1w6g8_lni0.run(lambda)
E/AndroidRuntime(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(24964): 	at java.lang.Thread.run(Thread.java:761)
E/SQLiteOpenHelper(24964): Couldn't open signal.db for writing (will try read-only):
E/SQLiteOpenHelper(24964): net.sqlcipher.database.SQLiteException: not an error: Could not open the database in read/write mode.
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2510)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:688)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
E/SQLiteOpenHelper(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/SQLiteOpenHelper(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/SQLiteOpenHelper(24964): 	at java.lang.Thread.run(Thread.java:761)
I/OpenGLRenderer( 2721): Initialized EGL, version 1.4
D/OpenGLRenderer( 2721): Swap behavior 1
E/Database(24964): file is not a database: , while compiling: select count(*) from sqlite_master;
E/Database(24964): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
E/Database(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
E/Database(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
E/Database(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
E/Database(24964): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
E/Database(24964): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/Database(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
E/Database(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
E/Database(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/Database(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/Database(24964): 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:688)
E/Database(24964): 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
E/Database(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/Database(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/Database(24964): 	at java.lang.Thread.run(Thread.java:761)
E/UncaughtExceptionLogger(24964): 
E/UncaughtExceptionLogger(24964): net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1965)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1843)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2584)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2513)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1099)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:255)
E/UncaughtExceptionLogger(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:688)
E/UncaughtExceptionLogger(24964): 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
E/UncaughtExceptionLogger(24964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/UncaughtExceptionLogger(24964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/UncaughtExceptionLogger(24964): 	at java.lang.Thread.run(Thread.java:761)
E/SQLiteOpenHelper(24964): Couldn't open signal.db for writing (will try read-only):
E/SQLiteOpenHelper(24964): net.sqlcipher.database.SQLiteException: not an error: Could not open the database in read/write mode.
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2510)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1207)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1270)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:233)
E/SQLiteOpenHelper(24964): 	at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:220)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.database.helpers.SQLCipherOpenHelper.getReadableDatabase(SQLCipherOpenHelper.java:492)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.database.MmsDatabase.getNearestExpiringViewOnceMessage(MmsDatabase.java:1257)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.revealable.ViewOnceMessageManager.getNextClosestEvent(ViewOnceMessageManager.java:42)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.revealable.ViewOnceMessageManager.getNextClosestEvent(ViewOnceMessageManager.java:23)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.service.TimedEventManager.lambda$scheduleIfNecessary$1(TimedEventManager.java:42)
E/SQLiteOpenHelper(24964): 	at org.thoughtcrime.securesms.service.-$$Lambda$TimedEventManager$kZDO3F2WBQVtGx-SkAgEDt8jCeU.run(lambda)
E/SQLiteOpenHelper(24964): 	at android.os.Handler.handleCallback(Handler.java:751)
E/SQLiteOpenHelper(24964): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/SQLiteOpenHelper(24964): 	at android.os.Looper.loop(Looper.java:154)
E/SQLiteOpenHelper(24964): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/Process (24964): Sending signal. PID: 24964 SIG: 9
D/AndroidRuntime(24949): Shutting down VM
E/AndroidRuntime(24949): FATAL EXCEPTION: main
E/AndroidRuntime(24949): Process: android:ui, PID: 24949
E/AndroidRuntime(24949): java.lang.NullPointerException: Attempt to read from field 'java.util.List com.android.internal.app.ChooserActivity.mServiceConnections' on a null object reference
E/AndroidRuntime(24949): 	at com.android.internal.app.ChooserActivity.-get5(ChooserActivity.java)
E/AndroidRuntime(24949): 	at com.android.internal.app.ChooserActivity$ChooserTargetServiceConnection.onServiceDisconnected(ChooserActivity.java:1425)
E/AndroidRuntime(24949): 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1469)
E/AndroidRuntime(24949): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1483)
E/AndroidRuntime(24949): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(24949): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(24949): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(24949): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime(24949): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24949): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(24949): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Note that it seems that the filesystem is mounted read-only. I guess Android had a hiccup of some sorts and requires to be rebooted... I appreciate that this is a tough environment to work in. But it'd still be nice to cope with that problem some way or the better. I hope that there's a better way than crashing (and taking Android down).

**Comment by greyson-signal** [comment]
I'm not sure what your OS situation is, but if we can't open our own database, there's nothing reasonable for us to do besides crash.

**Comment by muelli** [comment]
that's interesting. It's the only app that complains so loudly. And takes the system down.

Besides, it seems to complain about a log in the cache folder. That sounds like a bad reason to crash for.
