### ISSUE TITLE
Crash pressing "Submit debug log"

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#9116]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes clicking *Submit debug log* in the settings.

### Device info

**Device:** Motorola One Vision
**Android version:** 9
**Signal version:** 4.49.4

### Link to debug log
```
--------- beginning of crash
10-21 11:21:00.880  8451  8469 E AndroidRuntime: FATAL EXCEPTION: signal-PersistentLogger
10-21 11:21:00.880  8451  8469 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8451
10-21 11:21:00.880  8451  8469 E AndroidRuntime: java.lang.AssertionError: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogFile$Reader.readEntry(LogFile.java:9)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogFile$Reader.readAll(LogFile.java:2)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.PersistentLogger.a(PersistentLogger.java:7)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.b.run(Unknown Source:4)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: Caused by: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:3)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:5)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at javax.crypto.Cipher.doFinal(Cipher.java:2113)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	at org.thoughtcrime.securesms.logging.LogFile$Reader.readEntry(LogFile.java:7)
10-21 11:21:00.880  8451  8469 E AndroidRuntime: 	... 6 more
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: java.lang.AssertionError: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.logging.LogFile$Reader.readEntry(LogFile.java:9)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.logging.LogFile$Reader.readAll(LogFile.java:2)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.logging.PersistentLogger.a(PersistentLogger.java:7)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.logging.b.run(Unknown Source:4)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at java.lang.Thread.run(Thread.java:764)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: Caused by: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:3)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:5)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at javax.crypto.Cipher.doFinal(Cipher.java:2113)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.logging.LogFile$Reader.readEntry(LogFile.java:7)
10-21 11:21:00.881  8451  8469 E UncaughtExceptionLogger: 	... 6 more
10-21 11:21:00.885  3953  5275 E BufferQueueProducer: [org.thoughtcrime.securesms/org.thoughtcrime.securesms.ApplicationPreferencesActivity#0] disconnect: not connected (req=1)
10-21 11:21:00.885  8451  8501 W libEGL  : EGLNativeWindowType 0x7a49898010 disconnect failed
10-21 11:21:00.893  4442  7567 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.LogSubmitActivity
10-21 11:21:00.900  8451  8469 I Process : Sending signal. PID: 8451 SIG: 9
10-21 11:21:00.903  4442  4457 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-21 11:21:00.903  4442  4457 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-21 11:21:00.959  4442  4552 W InputDispatcher: channel '2467d91 org.thoughtcrime.securesms/org.thoughtcrime.securesms.Appl
```

**Comment by greyson-signal** [comment]
Hmm, maybe there was a bad log write? Have you cleared Signal's cache recently?

**Comment by pgerber** [comment]
No, I can't remember clearing Signal's cache recently.

**Comment by greyson-signal** [comment]
I can only imagine this is some sort of disk corruption. The logfile on disk is bad. I don't think much can be done on our end. Given it's a log though, we should avoid crashing, so I've made it no-op in this instance instead.
