### ISSUE TITLE
Video gets stuck, chews up 2 gigs of mobile data and prevents me from writing messages

### ISSUE THREAD

**Issue by Dyras** [signalapp/Signal-Android#9119]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I chatted with a friend when I was using public WiFi. Then I try to send a video I recorded at the karaoke bar I was visiting. All of a sudden, my messages are refusing to send. They still won't send, even on mobile data or on my WiFi at home.

**Actual result:** Messages refuse to send after using public WiFi and sending a video
**Expected result:** Messages should never get stuck and should definitely not chew up 2 gigs of mobile data

### How to reproduce
1. Send a video on a public WiFi, presumably one with a poor connection
2. The video gets stuck and disappears from your phone
3. Go about your day, with mobile data enabled
4. Get a warning from Android that the app has eaten 2 gigabytes of mobile data and an additional 2 gigabytes of data on your home network in the span of 16 hours

### Device info
Device       : Google Pixel 3a XL (bonito)
Android      : 10 (5878874, QP1A.191005.007)
ABIs         : arm64-v8a, armeabi-v7a, armeabi
Memory       : 29M (26.81% free, 512M max)
Memclass     : 192
OS Host      : abfarm788
First Version: 532
App          : Signal 4.49.4 (5512)

### Link to debug log
https://debuglogs.org/27704cad7a3d80fc6cfeb3f464816d5dca62e6d5591660965fc281c17593864d
Tried copying the message IDs but it seems I can't if they haven't been sent yet :|
The contact I'm having problems with has a mobile number that ends with 23.

**Comment by Dyras** [comment]
By forcing the app to close and then deleting the cache, I managed to get rid of the video so Signal is no longer attempting to send a video repeatedly. However, now the issue is that I still can't send messages to that contact.

**Comment by greyson-signal** [comment]
Looks like you're unable to upload the entire video. I don't know the reliability of the various networks you were on throughout the day, but it looks like we repeatedly tried to upload but couldn't do it.

```java
2019-10-22 12:20:33.849 CEST I BaseJob: [62922c73-5d5a-466f-aae1-7b3021f8fc3e][AttachmentUploadJob] Encountered a retryable exception. (Time Since Submission: 50015320 ms, Lifespan: 86400000 ms, Run Attempt: 322/Unlimited)
2019-10-22 12:20:33.849 CEST I BaseJob: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:35)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadAttachment(PushServiceSocket.java:8)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.uploadAttachment(SignalServiceMessageSender.java:13)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.thoughtcrime.securesms.jobs.AttachmentUploadJob.onRun(AttachmentUploadJob.java:6)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:1)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:21)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:2)
2019-10-22 12:20:33.849 CEST I BaseJob: Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:7)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:1)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:28)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:7)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at okhttp3.RealCall.execute(RealCall.java:9)
2019-10-22 12:20:33.849 CEST I BaseJob: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.uploadToCdn(PushServiceSocket.java:29)
2019-10-22 12:20:33.849 CEST I BaseJob: 	... 6 more
```

The way our message sending system works is that we will only send things in order within a specific conversation. In this case, your video message send can't complete, so future messages in that conversation can't be sent.

The easiest solution would be to delete the message from the conversation. The next time signal tries to upload the attachment, it'll see that the attachment/message no longer exists and it'll be skipped.

> By forcing the app to close and then deleting the cache, I managed to get rid of the video so Signal is no longer attempting to send a video repeatedly.

Clearing the cache shouldn't affect a video send. We copy attachments that are being sent to internal storage, which is separate from the cache. However, force-stopping Signal would stop it from retrying sends in the background.

> However, now the issue is that I still can't send messages to that contact.

Another debuglog would be helpful. I'd recommend deleting the video message in question, waiting 30 seconds, and seeing if the rest of your messages go through. If they're still stuck, post another debuglog here. Thanks!

**Comment by Dyras** [comment]
I deleted the video and it's still happening.
Two logs uploaded before deleting the video:
https://debuglogs.org/08a8b0cb082ce798dc71bde8e6130dfba5180e3c31a04f2c044bec1a66f67898
https://debuglogs.org/0dbbad4d504f89eb8d79961e115c777647e9aa8722d3876e5d002c51d013d12a

Two logs uploaded after deleting the video:
https://debuglogs.org/0dbbad4d504f89eb8d79961e115c777647e9aa8722d3876e5d002c51d013d12a
https://debuglogs.org/66f1d059d02974e34375d776c550b4428976c0de2031ae2d5cc2478c16194bc5

The second one was uploaded after deleting the picture I sent immediately after the video

And here's a log I uploaded after deleting every message that could not be delivered and then sending a new message:
https://debuglogs.org/558c422b600b5e5a956745b27671e2c5ac100164a341eaaa96fbbd39657cefda

I don't think it's an issue with my connection at this point. It's not sending at home, and I can send messages to everyone else including myself just fine.

**Comment by greyson-signal** [comment]
I just want to double check we're talking about the same thing: when I say "delete the video", I mean long pressing the message with the video and then pressing the delete button in the toolbar. *Not* deleting the video from your external photos app. The only reason I'm clarifying that is because your logs indicate that the video attachment still exists, and it's still trying to send it. Regardless, I'm putting some additional logging in the next beta release around this.

**Comment by Dyras** [comment]
@greyson-signal I definitely deleted it in the chat and not on my device. I might be dumb, but I'm not _that_ dumb. 😉 I've done the exact same thing when it's gotten stuck in the past and it always worked. This time, it didn't.

I managed to get rid of the issue by deleting the entire chat and then killing Signal, waiting a while and then opening it again.

Will report back again if it happens again.

**Comment by greyson-signal** [comment]
Yeah, I'm particularly interested if somehow the message for an attachment was deleted, but not the attachment row itself... I know this is a stretch, but could there have been a separate attachment that was getting stuck earlier that wasn't deleted? It sounds like deleting the chat eventually cleaned up whatever bad attachment row was there, so maybe something else was stuck that you didn't realize? Sorry, basically trying to explain my own confusion :)

The 4.49.6 release adds more logging to find the problem if it happens again. Thanks!
