### ISSUE TITLE
Signal crash on Pixel 3XL - Android 10

### ISSUE THREAD

**Issue by lft-d** [signalapp/Signal-Android#9185]
-   [x ] I have searched open and closed issues for duplicates
 -   [ x] I am submitting a bug report for existing functionality that does not work as intended
 -   [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
    [ x] This isn't a feature request or a discussion topic

------------------------------------------------------------------------------

### Bug description
Signal app is crashing after importing a backup on  Pixel 3 XL with Android version 10 and security patch 5 November 2019.
I can use the app for a while after importing, then it crashes and I am unable to open it (crash on open).

### Steps to reproduce
I can't figure the exact steps that makes the app crash. I  imported a backup from an old phone (Signal version 4.47.6 on LineageOS 14.1-20190125-suzuran), the app works for a while and then it crashes on opening.

### Device info

**Device:**  Pixel 3 XL
**Android version:** 10.0.0
**Signal version:** 4.49.18

### Link to debug log
Since the app was crashing on open, I've got the logs with adb.
```java
--------- beginning of crash
11-12 16:57:51.360 12029 12090 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
11-12 16:57:51.360 12029 12090 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12029
11-12 16:57:51.360 12029 12090 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:57:51.360 12029 12090 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-4
11-12 16:57:51.360 12029 12092 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12029
11-12 16:57:51.360 12029 12092 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:57:51.360 12029 12092 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:57:51.362  1356 12093 I chatty  : uid=1000 system_server expire 1 line
11-12 16:58:01.280 12119 12119 I SuspendedAppActivity: Started more details activity
11-12 16:58:01.386  1356  6889 I chatty  : uid=1000(system) Binder:1356_19 expire 2 lines
11-12 16:58:01.652 12151 12211 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
11-12 16:58:01.652 12151 12211 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12151
11-12 16:58:01.652 12151 12211 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:58:01.652 12151 12211 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
11-12 16:58:01.653 12151 12212 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12151
11-12 16:58:01.653 12151 12212 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:58:01.653 12151 12212 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-4
11-12 16:58:01.654 12151 12214 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12151
11-12 16:58:01.654 12151 12214 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:58:01.654 12151 12214 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:58:01.656  1356 12215 I chatty  : uid=1000 system_server expire 1 line
11-12 16:58:01.661  1356  1437 I chatty  : uid=1000(system) ActivityManager expire 10 lines
11-12 16:58:01.663  1356  1423 I chatty  : uid=1000(system) android.ui expire 14 lines
11-12 16:58:01.705  1356 10769 I chatty  : uid=1000(system) Binder:1356_20 expire 5 lines
11-12 16:58:02.902  1356  6289 I chatty  : uid=1000(system) Binder:1356_17 expire 10 lines
11-12 16:58:03.143 12222 12282 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
11-12 16:58:03.143 12222 12282 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12222
11-12 16:58:03.143 12222 12282 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:58:03.143 12222 12282 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
11-12 16:58:03.144 12222 12280 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12222
11-12 16:58:03.144 12222 12280 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:58:03.144 12222 12280 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-4
11-12 16:58:03.145 12222 12283 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12222
11-12 16:58:03.145 12222 12283 E AndroidRuntime: java.lang.IllegalStateException: Tried to retrieve a value with key 'recipient', but it wasn't present.
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.throwIfAbsent(Data.java:207)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.Data.getString(Data.java:60)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:242)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.RetrieveProfileJob$Factory.create(RetrieveProfileJob.java:238)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobInstantiator.instantiate(JobInstantiator.java:18)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.createJob(JobController.java:325)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.getNextEligibleJobForExecution(JobController.java:315)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobController.pullNextEligibleJobForExecution(JobController.java:170)
11-12 16:58:03.145 12222 12283 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:45)
11-12 16:58:03.148  1356 12285 I chatty  : uid=1000 system_server expire 1 line
```

**Comment by lft-d** [comment]
The backup was created with Signal version 4.47.6 on LineageOS 14.1-20190125-suzuran

**Comment by greyson-signal** [comment]
Looks like you had an old Job in your database, which we imported, but didn't run through the job migration process. There's an argument to be made that we shouldn't be backing up/restoring the jobs database at all.

Unfortunately your device is in a bad state where it's going to keep failing to create the job. I can see if we can work in something where we fail jobs in this case before crashing, which should allow you to get through.

**Comment by lft-d** [comment]
Thanks greyson, in the meantime does it makes sense to retry a backup and import it?
Maybe the old job wouldn't be imported.

**Comment by greyson-signal** [comment]
Unfortunately it probably would fail again. If you reach out to me at greyson@signal.org, I'll get you a build to get yourself back up and running.

**Comment by greyson-signal** [comment]
I've made changes to prevent this type of problem from happening in the future. Notably:

- Don't restore the jobs database during backup restore.
- If a job fails to be created at the instantiation phase, fail+crash, but don't get into a loop.

**Comment by lft-d** [comment]
Awesome, thanks! 
I'll test it as soon as I can.
