### ISSUE TITLE
Signal crashes repeatedly if a blocked recipient object is invalid

### ISSUE THREAD

**Issue by mwleeds** [signalapp/Signal-Android#9218]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After I blocked a group MMS message, Signal crashes on startup repeatedly.

### Steps to reproduce
I'm not sure, the spam message I blocked appears to come from "+19415312053". Maybe the problem is the `+` in the phone number?

**Actual result:** The app crashes every time it opens, and Android seems to open it on its own, so there are frequent notifications from Android that it crashed.
**Expected result:** The group is blocked and the app continues to work.

### Device info

**Device:** Pixel 3a
**Android version:** 10
**Signal version:** 4.50.5 (might have been one release previous to that when the bug happened?)

### Link to debug log
from `adb logcat`:
```
--------- beginning of crash
11-22 09:35:12.137  4969  5591 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
11-22 09:35:12.137  4969  5591 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 4969
11-22 09:35:12.137  4969  5591 E AndroidRuntime: java.lang.AssertionError: RecipientId::848 - No UUID or phone number!
11-22 09:35:12.137  4969  5591 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientUtil.toSignalServiceAddress(RecipientUtil.java:35)
11-22 09:35:12.137  4969  5591 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MultiDeviceBlockedUpdateJob.onRun(MultiDeviceBlockedUpdateJob.java:81)
11-22 09:35:12.137  4969  5591 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
11-22 09:35:12.137  4969  5591 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
11-22 09:35:12.137  4969  5591 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
11-22 09:35:12.156  1346  2000 I chatty  : uid=1000(system) Binder:1346_6 expire 1 line
11-22 09:35:12.168  1346  5619 I chatty  : uid=1000 system_server expire 1 line
11-22 09:35:12.409  1346  1363 I chatty  : uid=1000(system) Binder:1346_1 expire 4 lines
11-22 09:35:13.263  1346  3996 I chatty  : uid=1000(system) Binder:1346_18 expire 2 lines
11-22 09:35:14.682  2267  5708 E ActivityThread: Failed to find provider info for instantapp-dev-manager
11-22 09:35:15.604  5756  5955 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
11-22 09:35:15.604  5756  5955 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5756
11-22 09:35:15.604  5756  5955 E AndroidRuntime: java.lang.AssertionError: RecipientId::848 - No UUID or phone number!
11-22 09:35:15.604  5756  5955 E AndroidRuntime: 	at org.thoughtcrime.securesms.recipients.RecipientUtil.toSignalServiceAddress(RecipientUtil.java:35)
11-22 09:35:15.604  5756  5955 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.MultiDeviceBlockedUpdateJob.onRun(MultiDeviceBlockedUpdateJob.java:81)
11-22 09:35:15.604  5756  5955 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
11-22 09:35:15.604  5756  5955 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
11-22 09:35:15.604  5756  5955 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```

**Comment by mwleeds** [comment]
I wrote this patch to get my phone working, but not in a state where it could be merged: https://github.com/mwleeds/Signal-Android/commit/bf74ca1cd98caca58b7ba57616ab1e2713e58fd8

**Comment by mwleeds** [comment]
I guess numbers normally show up with a leading `+` so that's not the issue. And now that I've deleted the recipient from the database I guess there's no way to tell what it looked like, other than that it was missing a UUID and a phone number.
