### ISSUE TITLE
AvatarImageView: unhandled ActivityNotFoundException when Contacts app is disabled

### ISSUE THREAD

**Issue by theshoals** [signalapp/Signal-Android#9236]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal 4.50.5 crashes with an ActivityNotFoundException when I tap on an avatar in the conversation-list view.  The crash goes away when I enable the Contacts application on my phone.

### Steps to reproduce
- Disable your Contacts application in the Android settings
- Open Signal
- Tap on an avatar in the conversations-list view

**Actual result:** Signal crashes
**Expected result:** An error message is displayed about a disabled/missing Contacts application

### Device info

**Android version:** 7.1.2 (LineageOS)
**Signal version:** 4.50.5

### Debug log
```
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSERT_OR_EDIT typ=vnd.android.cursor.item/contact (has extras) }
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1818)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.Activity.startActivityForResult(Activity.java:4229)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.Activity.startActivityForResult(Activity.java:4187)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.Activity.startActivity(Activity.java:4526)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.Activity.startActivity(Activity.java:4494)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.components.AvatarImageView.lambda$setAvatarClickHandler$0$AvatarImageView(AvatarImageView.java:144)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.components.-$$Lambda$AvatarImageView$XESJUbW2ImudJWqZc9R4kvBLTNA.onClick(lambda)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.view.View.performClick(View.java:5637)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.view.View$PerformClick.run(View.java:22433)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:751)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.os.Looper.loop(Looper.java:154)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-01 23:11:25.629 23752 23752 E UncaughtExceptionLogger: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: FATAL EXCEPTION: main
12-01 23:11:25.652 23752 23752 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 23752
12-01 23:11:25.652 23752 23752 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSERT_OR_EDIT typ=vnd.android.cursor.item/contact (has extras) }
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1818)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4229)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4187)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4526)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4494)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.AvatarImageView.lambda$setAvatarClickHandler$0$AvatarImageView(AvatarImageView.java:144)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.-$$Lambda$AvatarImageView$XESJUbW2ImudJWqZc9R4kvBLTNA.onClick(lambda)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-01 23:11:25.652 23752 23752 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by theshoals** [comment]
I'm no longer able to reproduce this crash with 4.60.9.
