### ISSUE TITLE
Incompatible Signal Client and Signal Server

### ISSUE THREAD

**Issue by danherascu** [signalapp/Signal-Android#9263]
### Bug description
The current version of the client 4.51.6 is incompatible with the current version of the server 2.5.5.

1. The first error is when the client tries to register it get's the following error:

`2019-12-09 15:24:20.208 14248-14292/org.whispersystems W/PushServiceSocket: Push service URL: https://domain.com
2019-12-09 15:24:20.209 14248-14292/org.whispersystems W/PushServiceSocket: Opening URL: https://domain.com/v1/accounts/fcm/preauth/cZSes_XFRys:APA91bEI7LVzZ7O-_ypTOVX6f7YgalXmI9eEEA_8S4Vkf6jx1lPqlIRoNlMBHEJEE23OAmqcOcG-RuwWiHHst9OFB77jeuWHMIqL9w7bWOI6J7KC3zceyh5W7HQnwhrqxCGkh2ogWoom/+000000000
2019-12-09 15:24:20.254 14248-14292/org.whispersystems D/NetworkManagementSocketTagger: tagSocket(91) with statsTag=0xffffffff, statsUid=-1
2019-12-09 15:24:20.272 14248-14292/org.whispersystems W/org.whispersystems: Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
2019-12-09 15:24:20.299 14248-14292/org.whispersystems W/org.whispersystems: Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
2019-12-09 15:24:20.397 14248-14292/org.whispersystems W/PushChallengeRequest: Error getting push challenge
    org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:951)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:904)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestPushChallenge(PushServiceSocket.java:297)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestPushChallenge(SignalServiceAccountManager.java:174)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest$Request.requestAndReceiveChallengeBlocking(PushChallengeRequest.java:94)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest$Request.access$100(PushChallengeRequest.java:66)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest.getPushChallengeBlocking(PushChallengeRequest.java:50)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:55)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:38)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

So the issue is that the server does not implement the endpoint "v1/accounts/fcm/preauth"

2. The second issues is 

`2019-12-09 15:25:27.875 14248-14295/? W/CodeVerificationRequest: null
    com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
     at [Source: (String)""; line: 1, column: 0]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4146)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
        at org.whispersystems.signalservice.internal.util.JsonUtil.fromJson(JsonUtil.java:51)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:244)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccountWithCode(SignalServiceAccountManager.java:225)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest.verifyAccount(CodeVerificationRequest.java:166)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest.access$000(CodeVerificationRequest.java:49)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest$1.doInBackground(CodeVerificationRequest.java:94)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest$1.doInBackground(CodeVerificationRequest.java:86)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

Which comes from the fact that the server code for verifyAccount does not return a UUID for the app, so when the client tries to build the class VerifyAccountResponse, it gets an exception.

### Steps to reproduce

1. Used a local setup for the server;
2. Build the client on Android Studio and connected to the local server.

**Expected result:** I have added the issue here because the server does not have the issues tab active. 

Please fix the issue or point to a version of the client which is compatible with the current version of the Signal Server.

**Comment by trojanoffline** [comment]
I am also presenting the same problem and have tried the versions, from 4.47.7 to the last, with the same result.

```
I/PlayServicesUtil: Play Services: 0
I/EnterPhoneNumberFragmen: Successfully registered SMS listener.
D/RegistrationCodeRequest: SMS Verification requested for +1XXX4676925 captcha null
I/TextSecurePreferences: Setting push registered: false
I/crime.securesm: Background concurrent copying GC freed 54153(2MB) AllocSpace objects, 3(68KB) LOS objects, 50% free, 3MB/6MB, paused 67us total 2.484s
I/PushChallengeRequest: Requesting a push challenge
W/PushServiceSocket: Push service URL: https://signalin.net
    Opening URL: https://signalin.net/v1/accounts/fcm/preauth/fBfY4lrDg04:APA91bEz6zRva7gCEJl9u3m-Ue4phcKvDYJoEjAu6vkOAaLZ75Wgad7kXkTMMG2u7uGmUCEP59dxvVQNX9RxJzNmzmnalYx7gq7oorjcidV0l-lxGwJNNubjiR6mrr9ETA0Y7X_rltMO/+1XXX4676925
W/PushChallengeRequest: Error getting push challenge
    org.whispersystems.signalservice.api.push.exceptions.NotFoundException: Not found
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:838)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:791)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestPushChallenge(PushServiceSocket.java:272)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestPushChallenge(SignalServiceAccountManager.java:155)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest$Request.requestAndReceiveChallengeBlocking(PushChallengeRequest.java:94)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest$Request.access$100(PushChallengeRequest.java:66)
        at org.thoughtcrime.securesms.registration.PushChallengeRequest.getPushChallengeBlocking(PushChallengeRequest.java:50)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:55)
        at org.thoughtcrime.securesms.registration.service.RegistrationCodeRequest$1.doInBackground(RegistrationCodeRequest.java:38)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    Did not received a push challenge in 3346 ms
W/PushServiceSocket: Push service URL: https://signalin.net
    Opening URL: https://signalin.net/v1/accounts/sms/code/+1XXX4676925?client=android-ng
I/crime.securesm: NativeAlloc concurrent copying GC freed 7261(452KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/6MB, paused 47us total 482.562ms
V/Cursor: Filling cursor window with start position:0 required position:0
W/PushServiceSocket: Push service URL: https://signalin.net
    Opening URL: https://signalin.net/v1/accounts/code/197914
W/CodeVerificationRequest: null
    com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
     at [Source: (String)""; line: 1, column: 0]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4146)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
        at org.whispersystems.signalservice.internal.util.JsonUtil.fromJson(JsonUtil.java:49)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.verifyAccountCode(PushServiceSocket.java:224)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.verifyAccountWithCode(SignalServiceAccountManager.java:203)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest.verifyAccount(CodeVerificationRequest.java:137)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest.access$000(CodeVerificationRequest.java:42)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest$1.doInBackground(CodeVerificationRequest.java:75)
        at org.thoughtcrime.securesms.registration.service.CodeVerificationRequest$1.doInBackground(CodeVerificationRequest.java:68)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/EGL_emulation: eglMakeCurrent: 0xeb3c6200: ver 2 0 (tinfo 0xe399e130)
D/EGL_emulation: eglMakeCurrent: 0xeb3c6200: ver 2 0 (tinfo 0xe399e130)
```

**Comment by greyson-signal** [comment]
You should be able to use 4.43.x or earlier.

**Comment by trojanoffline** [comment]
I tried all versions 4.43.x with the same result.

Have any of you had a different result? Did the Signal-Andriod App on Signal-Server 2.55 work?

**Comment by trojanoffline** [comment]
> You should be able to use 4.43.x or earlier.

I tried all versions 4.43.x with the same result.

Have any of you had a different result? Did the Signal-Andriod App on Signal-Server 2.55 work?

**Comment by danherascu** [comment]
No results. I hope that they have not abandoned the Signal Server.
