### ISSUE TITLE
Crash when trying to take picture (since Signal 4.53.0)

### ISSUE THREAD

**Issue by pgerber** [signalapp/Signal-Android#9322]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Starting with Signal 4.53.0 the app crashes when attempting to take a picture.

### Steps to reproduce
- open any conversation
- click camera icon
- crash

### Device info

**Device:** Motorola One Vision
**Android version:** 9
**Signal version:** 4.53.0

### Link to debug log
[full log](https://debuglogs.org/8f25dcf4850678d65655e8a925e6b89189626fbc7590d4a7a4a1b583067c7adc)
```
01-06 23:18:36.557  8985  8985 E AndroidRuntime: FATAL EXCEPTION: main
01-06 23:18:36.557  8985  8985 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 8985
01-06 23:18:36.557  8985  8985 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.thoughtcrime.securesms-3JPtd4RuwiS324Assa7x0A==/base.apk"],nativeLibraryDirectories=[/data/app/org.thoughtcrime.securesms-3JPtd4RuwiS324Assa7x0A==/lib/arm64, /data/app/org.thoughtcrime.securesms-3JPtd4RuwiS324Assa7x0A==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libnative-utils.so"
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.FileUtils.<clinit>(FileUtils.java:15)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.FileUtils.createMemoryFileDescriptor(Native Method)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.MemoryFileDescriptor.supported(MemoryFileDescriptor.java:36)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.mms.MediaConstraints.isVideoTranscodeAvailable(MediaConstraints.java:79)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.CameraXFragment.isVideoRecordingSupported(CameraXFragment.java:286)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.CameraXFragment.initControls(CameraXFragment.java:231)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.CameraXFragment.onOrientationChanged(CameraXFragment.java:141)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.mediasend.CameraXFragment.onViewCreated(CameraXFragment.java:108)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onStart(PassphraseRequiredActionBarActivity.java:75)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7169)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3146)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:220)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6929)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 23:18:36.557  8985  8985 E AndroidRuntime: 	at 
```

**Comment by greyson-signal** [comment]
This is fixed in 4.53.1, which is rolling out now. Thanks!
