### ISSUE TITLE
Crash on create new message

### ISSUE THREAD

**Issue by morelazers** [signalapp/Signal-Android#9349]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Crashes when I hit the new message button. Loads for a short while then crashes. I have given the app all the available permissions in settings.

### Device info

**Device:** OnePlus 7 Pro
**Android version:** 10
**Signal version:** 4.53.6

### Link to debug log
https://debuglogs.org/fe48c87b17fdf5a6c5b754fbea3c32c89e5c5995c14c026cbd67c38a90c64ddc

**Comment by greyson-signal** [comment]
Seeing lots of stuff like this.

```java
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: [Batch] Experienced an unexpected exception.
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: java.util.concurrent.ExecutionException: java.lang.SecurityException: uid 10417 cannot explicitly add accounts of type: org.thoughtcrime.securesms
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.refreshDirectory(DirectoryHelperV1.java:99)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.refreshDirectory(DirectoryHelperV1.java:73)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelper.refreshDirectory(DirectoryHelper.java:24)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$1.doInBackground(ContactSelectionListFragment.java:311)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.ContactSelectionListFragment$1.doInBackground(ContactSelectionListFragment.java:297)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.lang.Thread.run(Thread.java:919)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: Caused by: java.lang.SecurityException: uid 10417 cannot explicitly add accounts of type: org.thoughtcrime.securesms
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.os.Parcel.createException(Parcel.java:2071)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.os.Parcel.readException(Parcel.java:2039)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.os.Parcel.readException(Parcel.java:1987)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:1660)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:889)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.createAccount(DirectoryHelperV1.java:237)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.getOrCreateAccount(DirectoryHelperV1.java:223)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.updateContactsDatabase(DirectoryHelperV1.java:147)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.DirectoryHelperV1.lambda$getLegacyDirectoryResult$1(DirectoryHelperV1.java:278)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at org.thoughtcrime.securesms.contacts.sync.-$$Lambda$DirectoryHelperV1$RZ1CMqxA0ZQn1s3GN0G_F5dp8CI.call(Unknown Source:8)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	... 3 more
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: Caused by: android.os.RemoteException: Remote stack trace:
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at com.android.server.accounts.AccountManagerService.addAccountExplicitlyWithVisibility(AccountManagerService.java:470)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at com.android.server.accounts.AccountManagerService.addAccountExplicitly(AccountManagerService.java:1617)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:630)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1072)
2020-01-17 13:54:05.539 GMT+11:00 E DirectoryHelperV1: 	at android.os.Binder.execTransactInternal(Binder.java:1032)
```

I saw this crash on github before, but I can't find the issue. I think they also had a OnePlus phone? It eventually just started working again for that user. Maybe try doing the normal "restart your phone" type stuff? None of this code has changed in Signal in a looong time, and it seems to be isolated to specific phones.

**Comment by morelazers** [comment]
Hasn't worked for about 2 months, multiple reboots, reinstalls, etc.

I really like Signal too :(

**Comment by morelazers** [comment]
Hasn't worked for about 2 months, multiple reboots, reinstalls, etc.

I really like Signal too :(

**Comment by apederson94** [comment]
Not sure if this helps, but I had Session installed as well as Signal and after uninstalling Session this same crash was fixed for me. Maybe another application is causing your crash as well?

**Comment by morelazers** [comment]
Ah this might have been it - I had Loki Messenger installed and since uninstalling it Signal has started working again. Session and Signal seem to work even though I have them both installed.

**Comment by apederson94** [comment]
Yeah just reading the log it looks like the Signal application was denied rights to adding a specific type of account. Potentially by another application forked from Signal.

**Comment by Haafingar** [comment]
Yes don't have Loki Messenger Installed, its redundant. We haven't noticed any compatibility issues with running Session and Signal side by side.
