### ISSUE TITLE
Strange crash when receiving message

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9389]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I received messages Signal suddenly crashed. After a restart it seemed to work normal again.

### Steps to reproduce
- I don't know.

**Actual result:** Signal crashes.
**Expected result:** Signal does not crash.

### Device info
**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.55.6

### Link to debug log
https://debuglogs.org/1f62fdba0f56509122b79539268818d6694ddeb1caff2e96d9745e542c92c1da

**Comment by Sgn-32** [comment]
Crash is triggered by key.length == 0 (2020-02-09 22:57:48.819) when trying to send a delivery receipt.
Probably triggered by TextSecureSessionStore: No existing session information found. (2020-02-09 22:57:48.798)


----
2020-02-09 22:57:48.098 GMT+01:00 W WebSocketConnection: WSC onMessage()
2020-02-09 22:57:48.099 GMT+01:00 W WebSocketConnection: Message Type: 2
**2020-02-09 22:57:48.099 GMT+01:00 W SignalServiceMessageSender: java.io.IOException: Non-successful response: 409
	at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:142)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1060)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:163)
	at org.thoughtcrime.securesms.jobs.SendDeliveryReceiptJob.onRun(SendDeliveryReceiptJob.java:84)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)**

2020-02-09 22:57:48.099 GMT+01:00 W SignalServiceMessageSender: Falling back to new connection...
2020-02-09 22:57:48.102 GMT+01:00 W SignalServiceMessageSender: Not transmitting over pipe...
2020-02-09 22:57:48.103 GMT+01:00 W PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
2020-02-09 22:57:48.104 GMT+01:00 W PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/messages/********-****-****-****-**********c0
2020-02-09 22:57:48.104 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********c2`
2020-02-09 22:57:48.230 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********c2`
2020-02-09 22:57:48.231 GMT+01:00 I JobRunner: [JOB::f4b1c752-e98b-4a65-8b8b-a02c870427c2][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 19576 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.242 GMT+01:00 I Job: [JOB::1ffbcb13-cb42-41d4-9026-c09f497e80ee][PushProcessMessageJob] onSubmit() (Time Since Submission: 32 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.295 GMT+01:00 I JobRunner: [JOB::ae735853-3117-4de6-9891-bf2208bbd8e9][PushDecryptMessageJob][3] Running job. (Time Since Submission: 19594 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.297 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********e9`
2020-02-09 22:57:48.425 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********e9`
2020-02-09 22:57:48.426 GMT+01:00 I JobRunner: [JOB::ae735853-3117-4de6-9891-bf2208bbd8e9][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 19724 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.439 GMT+01:00 I Job: [JOB::9620b4c8-0691-4bcf-a4c0-d5002755925f][PushProcessMessageJob] onSubmit() (Time Since Submission: 36 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.500 GMT+01:00 I JobRunner: [JOB::53be4a48-1515-4970-a7f6-8542ab7e6612][PushDecryptMessageJob][3] Running job. (Time Since Submission: 19359 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.507 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********12`
**2020-02-09 22:57:48.666 GMT+01:00 W SignalServiceMessageSender: org.whispersystems.signalservice.internal.push.exceptions.MismatchedDevicesException
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:976)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:934)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:328)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1069)
	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:163)
	at org.thoughtcrime.securesms.jobs.SendDeliveryReceiptJob.onRun(SendDeliveryReceiptJob.java:84)
	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)**

2020-02-09 22:57:48.678 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********12`
2020-02-09 22:57:48.681 GMT+01:00 I JobRunner: [JOB::53be4a48-1515-4970-a7f6-8542ab7e6612][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 19538 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.696 GMT+01:00 I Job: [JOB::1a874904-db25-4db0-842b-0399c5e43816][PushProcessMessageJob] onSubmit() (Time Since Submission: 68 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:48.797 GMT+01:00 I JobRunner: [JOB::864f1a8c-2dbc-4e23-beac-d3f6db46a95d][PushDecryptMessageJob][3] Running job. (Time Since Submission: 19378 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
**2020-02-09 22:57:48.798 GMT+01:00 W TextSecureSessionStore: No existing session information found.**
2020-02-09 22:57:48.818 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********5d`
**2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: Encountered a fatal exception. Crash imminent.
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: java.lang.IllegalArgumentException: key.length == 0
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:62)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.signal.libsignal.metadata.SealedSessionCipher.encrypt(SealedSessionCipher.java:70)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:86)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1218)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1178)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1044)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:163)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.thoughtcrime.securesms.jobs.SendDeliveryReceiptJob.onRun(SendDeliveryReceiptJob.java:84)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
2020-02-09 22:57:48.819 GMT+01:00 E BaseJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)**
2020-02-09 22:57:48.834 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:********-****-****-****-**********13
**2020-02-09 22:57:48.835 GMT+01:00 E JobRunner: [JOB::07aeb266-1016-43a5-8e61-747168961713][SendDeliveryReceiptJob][1] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 3229 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)**
**2020-02-09 22:57:48.835 GMT+01:00 W SendReadReceiptJob: Failed to send delivery receipt to: RecipientId::777**
**2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: java.lang.IllegalArgumentException: key.length == 0
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:62)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.libsignal.ratchet.ChainKey.getBaseMaterial(ChainKey.java:57)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.libsignal.ratchet.ChainKey.getMessageKeys(ChainKey.java:47)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.libsignal.SessionCipher.encrypt(SessionCipher.java:97)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.signal.libsignal.metadata.SealedSessionCipher.encrypt(SealedSessionCipher.java:70)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.encrypt(SignalServiceCipher.java:86)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessage(SignalServiceMessageSender.java:1218)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.getEncryptedMessages(SignalServiceMessageSender.java:1178)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1044)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendReceipt(SignalServiceMessageSender.java:163)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobs.SendDeliveryReceiptJob.onRun(SendDeliveryReceiptJob.java:84)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
2020-02-09 22:57:48.836 GMT+01:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)**
2020-02-09 22:57:48.945 GMT+01:00 D PassphraseRequiredActionBarActivity: [MainActivity] onPause()
2020-02-09 22:57:49.049 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********5d`
2020-02-09 22:57:49.050 GMT+01:00 I JobRunner: [JOB::864f1a8c-2dbc-4e23-beac-d3f6db46a95d][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 19631 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.067 GMT+01:00 I Job: [JOB::641129ce-38c3-42f5-bf2f-3ddb8657cd5b][PushProcessMessageJob] onSubmit() (Time Since Submission: 48 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.230 GMT+01:00 I JobRunner: [JOB::4abe9003-93ec-4b8d-84e9-413a39ce4a19][PushDecryptMessageJob][3] Running job. (Time Since Submission: 19748 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.249 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********19`
2020-02-09 22:57:49.313 GMT+01:00 D PassphraseRequiredActionBarActivity: [MainActivity] onStop()
2020-02-09 22:57:49.328 GMT+01:00 D PassphraseRequiredActionBarActivity: [MainActivity] onDestroy()
2020-02-09 22:57:49.505 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********19`
2020-02-09 22:57:49.506 GMT+01:00 I JobRunner: [JOB::4abe9003-93ec-4b8d-84e9-413a39ce4a19][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 20023 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.522 GMT+01:00 I Job: [JOB::1b5e9cbc-c371-49af-87ef-7f0c77bc76ea][PushProcessMessageJob] onSubmit() (Time Since Submission: 58 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.561 GMT+01:00 I JobRunner: [JOB::3367b10d-96e1-48db-a9c6-f62f068040e3][PushDecryptMessageJob][3] Running job. (Time Since Submission: 20004 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.563 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********e3`
2020-02-09 22:57:49.645 GMT+01:00 I ApplicationContext: App is no longer visible.
2020-02-09 22:57:49.648 GMT+01:00 I KeyCachingService: Starting timeout: 14400000
2020-02-09 22:57:49.712 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********e3`
2020-02-09 22:57:49.714 GMT+01:00 I JobRunner: [JOB::3367b10d-96e1-48db-a9c6-f62f068040e3][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 20155 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.732 GMT+01:00 I Job: [JOB::90a5f248-5704-426e-881e-11cbf4ef7d99][PushProcessMessageJob] onSubmit() (Time Since Submission: 46 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.840 GMT+01:00 I JobRunner: [JOB::0bc58e5e-a70d-4920-a8b3-a5ae8d01c58b][PushDecryptMessageJob][3] Running job. (Time Since Submission: 20197 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.864 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********8b`
2020-02-09 22:57:49.864 GMT+01:00 W SignalServiceMessageSender: Transmitting over unidentified pipe...
2020-02-09 22:57:49.926 GMT+01:00 I Job: [JOB::a0c740fc-b8d2-4e8d-ba26-cfaeec2ef39b][PushProcessMessageJob] onSubmit() (Time Since Submission: 16 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.951 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********8b`
2020-02-09 22:57:49.953 GMT+01:00 I JobRunner: [JOB::0bc58e5e-a70d-4920-a8b3-a5ae8d01c58b][PushDecryptMessageJob][3] Job finished with result: SUCCESS (Time Since Submission: 20329 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.978 GMT+01:00 W WebSocketConnection: WSC onMessage()
2020-02-09 22:57:49.982 GMT+01:00 W WebSocketConnection: Message Type: 2
2020-02-09 22:57:49.983 GMT+01:00 D WakeLockUtil: Released wakelock with tag: signal:`********-****-****-****-**********6a`
2020-02-09 22:57:49.984 GMT+01:00 I JobRunner: [JOB::d813c478-075e-4096-b537-0593a1deaf6a][SendDeliveryReceiptJob][2] Job finished with result: SUCCESS (Time Since Submission: 5117 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.998 GMT+01:00 I JobRunner: [JOB::3bbdd2ff-02c1-4e04-8f30-8f7f7a6577d5][PushDecryptMessageJob][3] Running job. (Time Since Submission: 20170 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
2020-02-09 22:57:49.999 GMT+01:00 D WakeLockUtil: Acquired wakelock with tag: signal:`********-****-****-****-**********d5`
2020-02-09 22:57:50.074 GMT+01:00 I JobRunner: [JOB::c9a9d712-91eb-47d7-b9bf-6b5aa54a8ecb][PushProcessMessageJob][2] Running job. (Time Since Submission: 4423 ms, Lifespan: Immortal, Run Attempt: 1/Unlimited)
