### ISSUE TITLE
Building on JDK 9+ results in MethodNotFoundError

### ISSUE THREAD

**Issue by smarek** [signalapp/Signal-Android#9462]
Logcat provided error
```
03-10 17:07:47.065  6533  6731 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-1
03-10 17:07:47.065  6533  6731 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 6533
03-10 17:07:47.065  6533  6731 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.contacts.crypto.Quote.read(Quote.java:105)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.contacts.crypto.Quote.readZero(Quote.java:111)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.contacts.crypto.Quote.<init>(Quote.java:62)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.internal.push.RemoteAttestationUtil.getAndVerifyRemoteAttestation(RemoteAttestationUtil.java:47)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.api.KeyBackupService$Session.getAndVerifyRemoteAttestation(KeyBackupService.java:195)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.api.KeyBackupService$Session.putKbsData(KeyBackupService.java:226)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.whispersystems.signalservice.api.KeyBackupService$Session.setPin(KeyBackupService.java:205)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.thoughtcrime.securesms.migrations.RegistrationPinV2MigrationJob.onRun(RegistrationPinV2MigrationJob.java:80)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
03-10 17:07:47.065  6533  6731 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```

This is result of source compatibility issue, where building with JDK 9 or higher (default for debian in my case is JDK 11)

This issue is documented accross the internet, for example:
- https://stackoverflow.com/a/58435689/492624
- https://github.com/sannies/mp4parser/issues/323#issuecomment-491498060
- https://www.reddit.com/r/androiddev/comments/ah194v/javaniobytebuffer_java_9_compiler_and_android/

And relevant info about implementing workarounds:
- https://issuetracker.google.com/issues/123015428
- https://github.com/gradle/gradle/issues/2510

This can be fixed two ways, using JRE safe implementation of ByteBuffer, handling all those corner-cases (or using implementation using explicit casts), or setting the compiler flag `--release 8` to handle this on JDK/JRE level (for example like this https://github.com/dkimitsa/robovm/commit/846535d54459a7c086c1339bbee800532133ec37 )

I've not attempted to do the necessary changes and tests, for me, trying to build and run current HEAD (da59ed019ff2f4946f326b6dc0e2a36efb400d51) i've applied changes, as seen in diff below:
```diff
git diff libsignal/service/src/main/java/org/whispersystems/signalservice/internal/contacts/crypto/Quote.java
diff --git a/libsignal/service/src/main/java/org/whispersystems/signalservice/internal/contacts/crypto/Quote.java b/libsignal/service/src/main/java/org/whispersystems/signalservice/internal/contacts/crypto/Quote.java
index 7337ff2fc..7c35bb4ee 100644
--- a/libsignal/service/src/main/java/org/whispersystems/signalservice/internal/contacts/crypto/Quote.java
+++ b/libsignal/service/src/main/java/org/whispersystems/signalservice/internal/contacts/crypto/Quote.java
@@ -1,5 +1,6 @@
 package org.whispersystems.signalservice.internal.contacts.crypto;
 
+import java.nio.Buffer;
 import java.nio.ByteBuffer;
 import java.nio.ByteOrder;
 
@@ -102,7 +103,8 @@ public class Quote {
   }
 
   private void read(ByteBuffer quoteBuf, int pos, byte[] buf) {
-    quoteBuf.position(pos);
+    Buffer b = (Buffer)quoteBuf;
+    b.position(pos);
     quoteBuf.get(buf);
   }

```

This fixed the single startup issue for me, but I acknowledge, there are more not-patched usages, such as VideoThumbnailsExtractor.java, VideoCapture.java, AudioTrackConverter.java, AudioCodec.java, etc..

**Comment by smarek** [comment]
Just to be useful, I've just tried reverting all changes to repository, and applying this on top of current HEAD (https://github.com/signalapp/Signal-Android/commit/da59ed019ff2f4946f326b6dc0e2a36efb400d51) and it seems to be working just fine currently

```diff
git diff main.gradle
diff --git a/main.gradle b/main.gradle
index d87ae1001..5d176cf94 100644
--- a/main.gradle
+++ b/main.gradle
@@ -2,6 +2,27 @@ wrapper {
     distributionType = Wrapper.DistributionType.ALL
 }
 
+allprojects {
+    afterEvaluate { Project p ->
+        List<String> androidPlugins = ["android", "com.android.application", "android-library", "com.android.library",
+        "com.android.test", "com.android.feature", "com.android.dynamic-feature", "com.android.instantapp"]
+
+        boolean isAndroidProject = false
+        for(String s: androidPlugins) {
+            if (p.plugins.findPlugin(s)) {
+                isAndroidProject = true
+                break;
+            }
+        }
+
+        if (!isAndroidProject) {
+            p.tasks.withType(JavaCompile).all {
+                it.options.compilerArgs += ['--release', '8']
+            }
+        }
+    }
+}
+
 subprojects {
     ext.lib_signal_service_version_number   = "2.15.3"
     ext.lib_signal_service_group_info       = "org.whispersystems"
```

**Comment by eht16** [comment]
I had the very same problem with OpenJDK 11.
@smarek's workaround helped me, thanks!

Though I also think a proper solution would be to replace the `ByteBuffer` usage.

**Comment by DonovanDiamond** [comment]
Update 2021:

I had to add this modification to the build.gradle file located in the root of the Signal-Android project:

```
allprojects {
    repositories {
        google()
        jcenter()
    }

+    afterEvaluate { Project p ->
+        List<String> androidPlugins = ["android", "com.android.application", "android-library", "com.android.library",
+                                       "com.android.test", "com.android.feature", "com.android.dynamic-feature", "com.android.instantapp"]
+
+        boolean isAndroidProject = false
+        for(String s: androidPlugins) {
+            if (p.plugins.findPlugin(s)) {
+                isAndroidProject = true
+                break;
+            }
+        }
+
+        if (!isAndroidProject) {
+            p.tasks.withType(JavaCompile).all {
+                it.options.compilerArgs += ['--release', '8']
+            }
+        }
+    }
}
```
