### ISSUE TITLE
Opening notification settings menu crashes the app instantly

### ISSUE THREAD

**Issue by dominikheinz** [signalapp/Signal-Android#9494]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening the notification settings in the app results in a crash of the signal app. 

### Steps to reproduce
- Open the Signal App
- Click on three dots in the top right corner
- Click on "Settings"
- Click on "Notifications"
- Observe the app crashing

**Actual result:** The app crashes immediately after pressing "Notifications"
**Expected result:** The notification settings should show up.

### Device info
**Device:** Xiaomi Mi9T Pro
**Android version:** 10 (_LineageOS 17.1-20200117-UNOFFICIAL-raphael_)
**Signal version:** 4.55.8

### Link to debug log
```
java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10206 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
 at android.os.Parcel.createException(Parcel.java:2071)
 at android.os.Parcel.readException(Parcel.java:2039)
 at android.os.Parcel.readException(Parcel.java:1987)
 at com.android.internal.telecom.ITelecomService$Stub$Proxy.getUserSelectedOutgoingPhoneAccount(ITelecomService.java:1468)
 at android.telecom.TelecomManager.getUserSelectedOutgoingPhoneAccount(TelecomManager.java:825)
 at android.media.RingtoneManager.getDefaultPhoneAccountHandle(RingtoneManager.java:891)
 at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:785)
 at android.media.Ringtone.getTitle(Ringtone.java:242)
 at android.media.Ringtone.getTitle(Ringtone.java:225)
 at org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment$RingtoneSummaryListener.onPreferenceChange(NotificationsPreferenceFragment.java:170)
 at org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment.initializeRingtoneSummary(NotificationsPreferenceFragment.java:182)
 at org.thoughtcrime.securesms.preferences.NotificationsPreferenceFragment.onCreate(NotificationsPreferenceFragment.java:114)
 at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
 at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
 at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
 at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
 at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
 at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
 at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
 at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by alan-signal** [comment]
Is this a recent problem? Has it ever worked on this device/ROM?

Please provide full log, here or email alan@signal.org

**Comment by dominikheinz** [comment]
@alan-signal Here is the full log, as requested: https://debuglogs.org/932f60db0f393bcde98a10cfb76f78d6ae00cbc05b74404607a93ceaeae52755

It has worked before with this ROM, - however, I can't pinpoint when this problem was first introduced.

**Comment by hendricjabs** [comment]
Maybe this is an Android 10 Issue: https://developer.android.com/about/versions/10/privacy/changes

> Starting in Android 10, apps must have the READ_PRIVILEGED_PHONE_STATE privileged permission in order to access the device's non-resettable identifiers, which include both IMEI and serial number.

**Comment by dominikheinz** [comment]
> Maybe this is an Android 10 Issue: https://developer.android.com/about/versions/10/privacy/changes
> 
> > Starting in Android 10, apps must have the READ_PRIVILEGED_PHONE_STATE privileged permission in order to access the device's non-resettable identifiers, which include both IMEI and serial number.

That seems to be the case. Signal should at least prompt for that permission or give a popup explaining this, rather than just crashing without further information.

**Comment by greyson-signal** [comment]
@dominikheinz As noted in the documentation you linked to, third-party apps cannot request that permission. And no other OS is crashing when reading the active ringtone. Which makes sense, because there is no reason reading the ringtone should require that permission. I'm closing this as a LineageOS bug.

**Comment by dmitrmax** [comment]
Seems that it is a bug in AOSP. Stock firmwares have  TelecomService replaced by vendors without this bug. But AOSP-based firmwares (LineageOS, crDroid etc.) suffer from that. I created an issue in AOSP bug tracker. Feel free to look at it and vote for it if you suffer from this: https://issuetracker.google.com/issues/312227037
