### ISSUE TITLE
Signal crashes when taking a picture (camerax)

### ISSUE THREAD

**Issue by guimspace** [signalapp/Signal-Android#9513]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes when taking a picture. Filming works ok.

### Steps to reproduce
- Select a chat or the camera icon
- Click on the camera
- Click the shoot button

**Actual result:** Signal crashes
**Expected result:** Takes a picture and goes to image editor

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 8.0.0
**Signal version:** 4.58.2

### Link to debug log
https://debuglogs.org/3f6a29074d4cbb526b66ead20c8689641fe35821e82b1f95d130c6bcf4db8763
```
2020-03-31 12:12:34.366 GMT-03:00 W CameraXUtil: Decoded image dimensions differed from stated dimensions! Stated: 1920 x 1080, Decoded: 1080 x 1920
2020-03-31 12:12:34.367 GMT-03:00 W CameraXUtil: Ignoring the stated rotation and rotating the crop rect 90 degrees (stated rotation is 90 degrees).
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Rect.top' on a null object reference
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.camerax.CameraXUtil.toJpeg(CameraXUtil.java:81)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.CameraXFragment$3.lambda$onCaptureSuccess$0$CameraXFragment$3(CameraXFragment.java:375)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.mediasend.-$$Lambda$CameraXFragment$3$i8GXbBNGHl6L1pMfko7tjxKCv5k.run(Unknown Source:6)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.concurrent.SimpleTask.lambda$run$1(SimpleTask.java:24)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.concurrent.-$$Lambda$SimpleTask$W3hwqgjBrQ_4y_Y0MHEF08-is-w.run(Unknown Source:6)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-03-31 12:12:34.369 GMT-03:00 E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by stefanovazzocell** [comment]
It might help the devs if you share the Manufacturer Model so they can [blacklist it](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/mediasend/camerax/CameraXModelBlacklist.java)

**Comment by guimspace** [comment]
Thanks for the detail: it is ASUS ZenFone 3 ZE520KL
