### ISSUE TITLE
Signal shows aiff as audio file but is not able to play it

### ISSUE THREAD

**Issue by strackeflavia16** [signalapp/Signal-Android#9545]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug Description

A friend sent me an aiff audio file from his IPhone to my Android phone. Signal recognizes the file as being audio but is not able to play it. Downloading the file and playing it with the phones music app works meaning the file is not corrupted.

### Steps to Reproduce

1) Sent an aiff audio file from Iphone to Android phone
2) Try to play it

Actual Result:

Signal shows toast message: Error playing audio file if I press the play button.

Expected Result:

Signal should be able to play that audio file.

### Platform Info

Signal Version:

4.58.5

Operating System:

Android 10

### Log
```04-16 10:13:37.347  7402  7402 I ExoPlayerImpl: Init 59ce6d4 [ExoPlayerLib/2.9.1] [beyond0, SM-G970F, samsung, 29]
04-16 10:13:37.352  7402 23778 V Cursor  : Filling cursor window with start position:0 required position:0
04-16 10:13:37.354  7402 23778 V Cursor  : Filling cursor window with start position:0 required position:0
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: Source error.
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-16 10:13:37.369  7402 23776 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:919)
04-16 10:13:37.369  7402  7402 W AudioSlidePlayer: MediaPlayer Error: com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
04-16 10:13:37.375  8443  8621 W IncomingMessageObserver: Application level read timeout...
04-16 10:13:37.375  7402  7402 D AudioSlidePlayer: onPlayerStateChanged(true, 1)
04-16 10:13:37.377  8443  8621 D IncomingMessageObserver: Network requirement: true, app visible: false, gcm disabled: true
04-16 10:13:37.377  8443  8621 I IncomingMessageObserver: Reading message...
04-16 10:13:37.397  7402 10955 I mali_winsys: new_window_surface() [503x147] return: 0x3000
04-16 10:13:39.382  7402 10955 I mali_egl: eglDestroySurface() in
04-16 10:13:39.383  7402 10955 I mali_winsys: delete_surface() [503x147] return
04-16 10:13:39.383  7402 10955 I mali_egl: eglDestroySurface() out
04-16 10:13:39.385  5272  6832 E BufferQueueProducer: [Toast#0] disconnect: not connected (req=1)
04-16 10:13:39.385  7402 10955 W libEGL  : EGLNativeWindowType 0x791fae8b50 disconnect failed
04-16 10:13:39.390  5654  6641 W NotificationService: Toast already killed. pkg=org.thoughtcrime.securesms callback=android.app.ITransientNotification$Stub$Proxy@cdf086c
```

**Comment by strackeflavia16** [comment]
Hm, seems Lineageos 17 has issues with playing aiff files. Closing.
