### ISSUE TITLE
Crash on conversation open or new message

### ISSUE THREAD

**Issue by rannbaron** [signalapp/Signal-Android#9572]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes on opening a conversation or a new message. 

### Steps to reproduce
- open conversation or start new message

**Actual result:** Crash

**Expected result:** no crash

### Device info

**Device:** OnePlus 5T
**Android version:** 10.0.0
**Signal version:** 4.59.5

### Link to debug log
https://debuglogs.org/76fbb405b6bdaee2ef29c51ef384d7e25d0e8abc62d10f563a5e1833f4baa21e

**Comment by CalvinNor** [comment]
Can confirm, same issue, same device.

**Comment by greyson-signal** [comment]
This is an Android bug on OnePlus's behalf, unnecessarily requiring a permission. You can grant "read phone state" in your system app settings for signal to resolve this. I fear we may have to put some manufacturer-specific condition in here to prevent this in the long run.

```java
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: Caused by: java.lang.SecurityException: com.android.phone from uid 10366 not allowed to perform READ_PHONE_STATE
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.os.Parcel.createException(Parcel.java:2071)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.os.Parcel.readException(Parcel.java:2039)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.os.Parcel.readException(Parcel.java:1987)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at com.android.internal.telephony.ISms$Stub$Proxy.isImsSmsSupportedForSubscriber(ISms.java:2292)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.telephony.SmsManager.isImsSmsSupported(SmsManager.java:2011)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.telephony.SmsMessage.useCdmaFormatForMoSms(SmsMessage.java:905)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:374)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:353)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:511)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.util.SmsCharacterCalculator.calculateCharacters(SmsCharacterCalculator.java:34)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.TransportOption.calculateCharacters(TransportOption.java:83)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.calculateCharactersRemaining(ConversationActivity.java:2065)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.lambda$initializeViews$10$ConversationActivity(ConversationActivity.java:1655)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.-$$Lambda$ConversationActivity$e_n2rSHEQmm_lWfQCU1F1QyT8k0.onChange(Unknown Source:2)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:208)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.TransportOptions.reset(TransportOptions.java:57)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.components.SendButton.resetAvailableTransports(SendButton.java:78)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.handleSecurityChange(ConversationActivity.java:1292)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.initializeSecurity(ConversationActivity.java:1438)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.onCreate(ConversationActivity.java:400)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:64)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.app.Activity.performCreate(Activity.java:7815)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.app.Activity.performCreate(Activity.java:7804)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
2020-04-30 15:28:57.785 EDT E SignalUncaughtExceptionHandler: 	... 11 more
```

**Comment by swordfischer** [comment]
I also receive this error (and same debug output more or less) (OnePlus 5)
However I'm unsure how to grant this permission, and for what? All required permissions by Signal are granted.

**Comment by rannbaron** [comment]
I posted this on OnePlus forums, was asked for logs, and was told they're working on it. I hope it'll be fixed by the time their Android 10 is finalized in a few weeks. 

I also granted all permissions, so that isn't quite the issue, @greyson-signal.

**Comment by rannbaron** [comment]
This issue is fixed in the latest beta of Oxygen OS for the OnePlus 5T, so we're good.

**Comment by greyson-signal** [comment]
Oh thank goodness, thanks for reporting it to them :)

**Comment by swordfischer** [comment]
I can confirm that it works on OnePlus 5 as well with Open Beta 3


-------- Original Message --------

**Comment by supersat** [comment]
This is back on Android 11 on the OnePlus 7T Pro 5G running OS build 11.0.1.3.HD61CB, but only rarely occurs:

07-21 13:45:20.362  1696  1823 I ActivityManager: Start proc 23646:org.thoughtcrime.securesms/u0a248 for pre-top-activity {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}
07-21 13:45:20.911 23646 23646 D ViewRootImpl: support adaptive color gamut feature!
07-21 13:45:21.598 23646  4070 I 110     :  OptJank - total:275 frameGap:577 delta#0#254#0#253#0#20
07-21 13:45:22.472  1696  2943 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW cmp=org.thoughtcrime.securesms/.conversation.ConversationActivity (has extras)} from uid 10248 pid 23646
07-21 13:45:22.484  1696  2601 I ActivityTaskManager: The Process org.thoughtcrime.securesms Already Exists in BG. So sending its PID: 23646
07-21 13:45:22.581 23646 23646 E AndroidRuntime: FATAL EXCEPTION: main
07-21 13:45:22.581 23646 23646 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 23646
07-21 13:45:22.581 23646 23646 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}: java.lang.SecurityException: com.android.phone from uid 10248 not allowed to perform READ_PHONE_STATE
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3611)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: Caused by: java.lang.SecurityException: com.android.phone from uid 10248 not allowed to perform READ_PHONE_STATE
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at com.android.internal.telephony.ISms$Stub$Proxy.isImsSmsSupportedForSubscriber(ISms.java:2146)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.telephony.SmsManager.isImsSmsSupported(SmsManager.java:2095)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.telephony.SmsMessage.useCdmaFormatForMoSms(SmsMessage.java:1065)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:407)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:384)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.telephony.SmsMessage.calculateLength(SmsMessage.java:546)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.SmsCharacterCalculator.calculateCharacters(SmsCharacterCalculator.java:35)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOption.calculateCharacters(TransportOption.java:84)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.calculateCharactersRemaining(ConversationActivity.java:2612)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.lambda$initializeViews$21(ConversationActivity.java:1998)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.lambda$initializeViews$21$ConversationActivity(Unknown Source:0)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.-$$Lambda$ConversationActivity$GU52L2w8V_mYmDwFu73vVpDktlk.onChange(Unknown Source:2)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.notifyTransportChangeListeners(TransportOptions.java:210)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.TransportOptions.reset(TransportOptions.java:59)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.SendButton.resetAvailableTransports(SendButton.java:79)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.handleSecurityChange(ConversationActivity.java:1507)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.initializeSecurity(ConversationActivity.java:1750)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.onCreate(ConversationActivity.java:463)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at org.thoughtcrime.securesms.PassphraseRequiredActivity.onCreate(PassphraseRequiredActivity.java:71)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8006)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7990)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
07-21 13:45:22.581 23646 23646 E AndroidRuntime: 	... 11 more
07-21 13:45:26.548  1696  2943 I ActivityManager: Killing 23646:org.thoughtcrime.securesms/u0a248 (adj 900): crash
07-21 13:45:27.124  1696  1813 W ActivityManager: setHasOverlayUi called on unknown pid: 23646
