### ISSUE TITLE
Out of Memory when restoring backup

### ISSUE THREAD

**Issue by fdietze** [signalapp/Signal-Android#9612]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Trying to restore from a backup crashes the app. The backup file has a size of ~1G.

### Steps to reproduce
- Open app
- Press restore button

### Device info

**Device:** Sony Xperia XA2 Dual (H4113)
**Android version:** 9
**Signal version:** 4.59.9

### Link to debug log

Signal crashes before I can open settings, so here is a logcat:

```
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:764)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1246232592 byte allocation with 3982287 free bytes and 508MB until OOM, max allowed footprint 7964575, growth limit 536870912
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.<init>(FullBackupImporter.java:234)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.<init>(FullBackupImporter.java:214)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:67)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:201)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:193)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-10 23:12:50.212 24448 25763 E SignalUncaughtExceptionHandler: 	... 4 more
```

**Comment by alan-signal** [comment]
What version was the backup made with?

**Comment by fdietze** [comment]
Sadly no... But my apps were up-to-date. I guess it was the latest version from play store at 2020-05-09.

**Comment by fdietze** [comment]
Is it worth waiting for this to be fixed, or should I live with deleting all my messages? Currently I'm waiting without using signal on my phone...

**Comment by Anti-ctrl** [comment]
Seems like i have the same Problem. Trying to Restore a Backupfile with ~8GB in Size. It crashes after restoring ~4600 Messages.
Cant do anything about it as it seems. Backup and Restore are both done on an Up to Date App (4.73.4).
