### ISSUE TITLE
Signal crashes while starting

### ISSUE THREAD

**Issue by hype11** [signalapp/Signal-Android#9663]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes while starting

### Steps to reproduce
- start Signal App

**Actual result:** Signal crashes
**Expected result:** Signal don't crash

### Device info
**Device:** Fairphone FP3
**Android version:** 9 (04060919, 8901.2.A.0118.20200406)
**Signal version:** 4.59.11

### Link to debug log
https://debuglogs.org/16d79a061f2c2272b80d9c677d75b43794b1a0878227e64099f0394c8892808a

**Comment by greyson-signal** [comment]
```java
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at android.content.ContentResolver.insert(ContentResolver.java:1586)
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at android.app.DownloadManager.enqueue(DownloadManager.java:1024)
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.handleDownloadStart(UpdateApkJob.java:171)
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobs.UpdateApkJob.onRun(UpdateApkJob.java:97)
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
2020-05-23 15:08:55.378 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```
Your app is crashing when we try to download the latest web APK.

It looks like something funny is happening with your phone's resolution of the downloads directory. This isn't something Signal does itself, but rather something the Android DownloadManager does.

This feels like a system configuration issue. If you have the Play Store, you could try using the version from there.

**Comment by hype11** [comment]
Can't you surround this with a try catch and give the user a useful message?

**Comment by hype11** [comment]
I found out, that this error occur when Download Manager is deactivated.
In my phone the internet access for Download Manager is blocked. I think this is the reason.
It would be nice, if Signal don't crash when something unexpected happen while downloading.

**Comment by greyson-signal** [comment]
Sounds like this is out of scope for us to fix then. Very much sounds like an OS/system configuration issue. Throwing wide try-catches around blocks of code is often a recipe for disaster and can hide real problems.

**Comment by hype11** [comment]
Signal has ca. 1000 code parts with try catch surroundings, so you have more than 1000 parts with real problems which you hide before the user?
No, I don't think so. try catch with exception logging is common programming standard.
In this case, everytime Signal has found an update at signal servers, signal crashes completely with the chance of corrupt database, corrupt backup and everything that is possible while a program crashes out of control.
If you have no time to add some lines of code with a try catch and a user message to output, add a help label to this issue, but don't close it like "I won't fix it".
