### ISSUE TITLE
v4.59.6 crashes repeatedly with `Recipient$UuidRecipientError`.  Fixed by updating to 4.61.5.

### ISSUE THREAD

**Issue by sure-fire** [signalapp/Signal-Android#9689]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

Personally, this issue is resolved, but I did not find mention of it anywhere.  Feel free to close this issue if it's not actionable, but I wanted to raise awareness.

### Bug description
Signal (v4.59.6) crashes repeatedly with `Recipient$UuidRecipientError` exception.  Update to 4.61.5 resolves the crashes.

### Steps to reproduce
- Opt-in to the Signal Beta in the Android Play store `(*)`
- Enable fingerprint-based authentication `(*)`
- Android silently updates to 4.59.6.
- An unknown time later, Signal begins crashing ("app not responding" error) in the background every few minutes
- Attempting to open Signal in the foreground generates the same error, prior to fingerprint authentication
- Force closing and rebooting the device do not help
- Manually update to Signal 4.61.5 via the Google Play store.
- Signal now functions normally.

`(*)` Not sure if these are necessary repro steps, but I'm including them just in case.

**Actual result:** Signal crashes with a Android OS "not responding" error.
**Expected result:** Signal should open normally.

### Device info

**Device:** Google Pixel 3a
**Android version:** 10 (May 2020 update)
**Signal version:** 4.59.6 -> 4.61.5

### Link to debug log
(Unable to open Signal to generate a debug log, but I did gather this using logcat via USB:

```
06-03 20:08:03.334  1394  3118 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[648,1850][864,2040]} from uid 10375
06-03 20:08:03.398  1394  1488 I ActivityManager: Start proc 18867:org.thoughtcrime.securesms/u0a217 for activity {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}
06-03 20:08:03.604 18867 18867 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
06-03 20:08:03.874 18867 18867 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1591359626968
06-03 20:08:03.877 18867 18867 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1591274056372
06-03 20:08:03.879 18867 18867 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.LocalBackupListener scheduling for: 1591243174946
06-03 20:08:03.881 18867 18867 I PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSenderCertificateListener scheduling for: 1591290707325
06-03 20:08:04.034  1394  3118 I ActivityTaskManager: START u0 {cmp=org.thoughtcrime.securesms/.PassphrasePromptActivity (has extras)} from uid 10217
06-03 20:08:04.202  1394  1394 V FingerprintService: startAuthentication(org.thoughtcrime.securesms)
06-03 20:08:04.202  1394  1394 V FingerprintService: starting client AuthenticationClientImpl(org.thoughtcrime.securesms) targetUserId: 0 currentUserId: 0 cookie: 0/0
06-03 20:08:04.219  1394  1394 W FingerprintService: client org.thoughtcrime.securesms is authenticating...
06-03 20:08:04.313  1394  1485 I ActivityTaskManager: Displayed org.thoughtcrime.securesms/.PassphrasePromptActivity: +963ms
06-03 20:08:04.343 18867 18931 D WakeLockUtil: Acquired wakelock with tag: signal:6bbc034f-dabf-4b36-8f88-0f60459e3275
06-03 20:08:04.401 18867 18931 D WakeLockUtil: Released wakelock with tag: signal:6bbc034f-dabf-4b36-8f88-0f60459e3275
06-03 20:08:04.407 18867 18931 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
06-03 20:08:04.407 18867 18931 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18867
06-03 20:08:04.407 18867 18931 E AndroidRuntime: org.thoughtcrime.securesms.recipients.Recipient$UuidRecipientError
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:271)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:38)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSession(SignalProtocolStoreImpl.java:81)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:179)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:150)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:190)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:131)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:190)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:138)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:159)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:113)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
06-03 20:08:04.407 18867 18931 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler: org.thoughtcrime.securesms.recipients.Recipient$UuidRecipientError
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:271)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.crypto.storage.TextSecureSessionStore.loadSession(TextSecureSessionStore.java:38)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSession(SignalProtocolStoreImpl.java:81)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:179)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:150)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:190)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.signal.libsignal.metadata.SealedSessionCipher.decrypt(SealedSessionCipher.java:131)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:190)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:138)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.handleMessage(PushDecryptMessageJob.java:159)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.PushDecryptMessageJob.onRun(PushDecryptMessageJob.java:113)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
06-03 20:08:04.407 18867 18931 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
06-03 20:08:04.420  1394 18937 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-03 20:08:04.420  1394  1421 W ActivityTaskManager:   Force finishing activity org.thoughtcrime.securesms/.PassphrasePromptActivity
06-03 20:08:04.427  1394 18937 W DropBoxManagerService: Dropping: data_app_crash (1565 > 0 bytes)
06-03 20:08:04.439  1394  1394 E FingerprintService: Stopping background authentication, top: com.teslacoilsw.launcher currentClient: org.thoughtcrime.securesms
06-03 20:08:04.453 18867 18931 I Process : Sending signal. PID: 18867 SIG: 9
06-03 20:08:04.491  1394  1394 W FingerprintService: client org.thoughtcrime.securesms is no longer authenticating
06-03 20:08:04.493  1394  1394 V FingerprintService: handleError(client=org.thoughtcrime.securesms, error = 5)
06-03 20:08:04.494  1394  1394 V FingerprintService: Done with client: org.thoughtcrime.securesms
06-03 20:08:04.509  1394  1720 W InputDispatcher: channel 'c2c08c org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-03 20:08:04.509  1394  1720 E InputDispatcher: channel 'c2c08c org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-03 20:08:04.510  1394  4001 I WindowManager: WIN DEATH: Window{c2c08c u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity}
06-03 20:08:04.510  1394  4001 W InputDispatcher: Attempted to unregister already unregistered input channel 'c2c08c org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity (server)'
06-03 20:08:04.510  1394  3097 I ActivityManager: Process org.thoughtcrime.securesms (pid 18867) has died: vis+99 TOP
06-03 20:08:04.512   820   820 I Zygote  : Process 18867 exited due to signal 9 (Killed)
```

**Comment by sure-fire** [comment]
Potentially related commits:
28bd245b96cadf0e855c9078c6052edf8e12ef4b - "While testing GV2 without UUID, fail jobs that hit UuidRecipientError." - @greyson-signal 
f270a6b8c49cf2e2eb7c7e76588d15778b3a2fb3 - "Fix potential crash by removing an unnecessary column." - @alan-signal
