### ISSUE TITLE
Reproducible crash when deleting many messages in a conversation

### ISSUE THREAD

**Issue by equaeghe** [signalapp/Signal-Android#9690]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When I delete a large number of messages in a conversation (40, say) by selecting them and then pressing the trashcan icon, Signal starts deleting them, but crashes after a while. After restarting, I see that no messages have actually been deleted.

Deleting works when selecting fewer messages (12 tested and worked).

### Steps to reproduce
- select conversation (so a contact)
- select multiple messages
    - by long-pressing one and tapping the selection icon
    - by short pressing the others
- tap the trashcan icon to delete the selected messages

**Actual result:**
Signal crashes and messages are not deleted.

**Expected result:**
Signal deletes the messages without crashing.

### Device info
**Device:** Samsung GT-I9192 (Galaxy S4 Mini Duos)
**Android version:** 8.1.0
**Signal version:** 4.60.9 (6401)

### Link to debug log
https://debuglogs.org/3f5b3661979db5b8cd8b517963d58dbae7d7031afaecad22b4c74432347cfc47

**Comment by mileskrell** [comment]
Experiencing this as well. Wanted to add that it doesn't seem to happen reliably - I've experienced it when deleting as few as 14 messages, but I've also been able to delete more than that without it crashing.

**Comment by greyson-signal** [comment]
I'm very sorry, but the debuglog has expired. Can someone who's experiencing this post a new debuglog after they hit the crash?

**Comment by equaeghe** [comment]
> I'm very sorry, but the debuglog has expired. Can someone who's experiencing this post a new debuglog after they hit the crash?

I have not yet been able to reproduce this with 4.65.2.

**Comment by pgerber** [comment]
@greyson-signal, as requested, a new debug log. I assume this is the same crash. If I remember correctly this happened after removing two successive messages at once. Both messages containing a picture and text.

https://debuglogs.org/d4ded1b489e6e61f14dda172eac960dba7fa2cc6e0f990a3cd28cafd7094d83c

```
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at java.util.ArrayList.get(ArrayList.java:437)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedStorage.get(PagedStorage.java:174)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedList.get(PagedList.java:410)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.AsyncPagedListDiffer.getItem(AsyncPagedListDiffer.java:217)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedListAdapter.getItem(PagedListAdapter.java:176)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationAdapter.getItem(ConversationAdapter.java:261)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationAdapter.getItemViewType(ConversationAdapter.java:133)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6186)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1649)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1638)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1413)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.View.layout(View.java:21973)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewGroup.layout(ViewGroup.java:6263)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3159)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2669)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1794)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7745)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:883)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:100)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:241)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7617)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
2020-07-26 22:23:46.142 GMT+02:00 E SignalUncaughtExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
```

**Comment by sivaraam** [comment]
I also experienced a very similar crash when using 4.70.4 when trying to delete multiple messages which were just links with previews to the conversation when using 4.69 & 4.70.

Relevant part of log:
```
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: java.lang.IndexOutOfBoundsException: Invalid index 9, size is 9
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at java.util.ArrayList.get(ArrayList.java:308)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedStorage.get(PagedStorage.java:174)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedStorageDiffHelper$1.areItemsTheSame(PagedStorageDiffHelper.java:77)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.DiffUtil.diffPartial(DiffUtil.java:268)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:145)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedStorageDiffHelper.computeDiff(PagedStorageDiffHelper.java:53)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at androidx.paging.AsyncPagedListDiffer$2.run(AsyncPagedListDiffer.java:336)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
2020-09-01 14:17:21.124 IST E SignalUncaughtExceptionHandler: 	at java.lang.Thread.run(Thread.java:818)
```

Debug log: https://debuglogs.org/57e824cb7904cf869ca24d52ae9ab7ba7f1d163d636421254289b8ed579ed294
