### ISSUE TITLE
Signal crashes in the context of choosing all messages via "Select all"

### ISSUE THREAD

**Issue by fommio** [signalapp/Signal-Android#9790]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal crashes without visible error message as soon as a conversation is selected in the main view, and more/all are selected via the "3-point menu" using the "Select all" command.

### Steps to reproduce
- Select one or more conversations in the main view
- Click on the "3-point menu"
- Click on "Select all"

**Actual result:** Signal crashes
**Expected result:** All conversations in the main view should be selected (e.g. for archiving afterwards)

### Screenshots
![20200626_130856](https://user-images.githubusercontent.com/67462955/85857618-80261180-b7ba-11ea-95ab-0d1afec8b828.gif)

### Device info

**Device:** OnePlus 7 (GM1900)
**Android version:** 10 (Security patch level 2020-05-01) / Oxygen OS 10.0.6.GM57BA
**Signal version:** 4.64.7

### App state

Signal messages and calls registered, SMS enabled.

### Link to debug log

https://debuglogs.org/f84b1343a234ad1d9cd45144378087c2f77cf9f8713fb30a14715d375a0b0c18

### Relevant part from the debug log

```
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedList.loadAround(PagedList.java:424)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.AsyncPagedListDiffer.getItem(AsyncPagedListDiffer.java:216)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.paging.PagedListAdapter.getItem(PagedListAdapter.java:176)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversationlist.ConversationListAdapter.selectAllThreads(ConversationListAdapter.java:217)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversationlist.ConversationListFragment.handleSelectAllThreads(ConversationListFragment.java:754)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversationlist.ConversationListFragment.onActionItemClicked(ConversationListFragment.java:841)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2413)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:141)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3265)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:883)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:100)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:214)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
2020-06-26 14:58:51.366 GMT+02:00 E SignalUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by grandchild** [comment]
Can confirm: https://debuglogs.org/433f64609d70a0bab773dbb08483a2a3ddaec6db83ef52b93699813a1c81711b

**Comment by grandchild** [comment]
Works if you don't have any archived conversations, so I guess directly using `getItem()` [here](https://github.com/signalapp/Signal-Android/blob/dac6b5c992c05cf302906c34d65f8913b386ffb7/app/src/main/java/org/thoughtcrime/securesms/conversationlist/ConversationListAdapter.java#L216) returns the "Archived Conversations" item as well.
