### ISSUE TITLE
Crash after registration

### ISSUE THREAD

**Issue by johanw666** [signalapp/Signal-Android#9837]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Immediately after registration and database restore Signal crashes. When I restart it, it runs normally.

### Steps to reproduce
- Install  Signal or wipe its data
- Restore backup
- Register Signal

**Actual result:** Signal crashes
**Expected result:** Signal does not crash

I think this is the relevant part of the log. Maybe a race condition?
```
07-10 02:15:13.209 20723 20763 E AndroidRuntime: FATAL EXCEPTION: signal-serial-0
07-10 02:15:13.209 20723 20763 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 20723
07-10 02:15:13.209 20723 20763 E AndroidRuntime: net.sqlcipher.database.SQLiteException: database is locked: BEGIN EXCLUSIVE;
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2363)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListenerInternal(SQLiteDatabase.java:2852)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:765)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:736)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.MegaphoneDatabase.getAllAndDeleteMissing(MegaphoneDatabase.java:71)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at org.thoughtcrime.securesms.megaphone.MegaphoneRepository.init(MegaphoneRepository.java:110)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at org.thoughtcrime.securesms.megaphone.MegaphoneRepository.lambda$getNextMegaphone$2$MegaphoneRepository(MegaphoneRepository.java:68)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at org.thoughtcrime.securesms.megaphone.-$$Lambda$MegaphoneRepository$q9Ph2NWga4K9VBzFhswMpm7EJ5M.run(lambda)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-10 02:15:13.209 20723 20763 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

### Device info

**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.66.0

### Link to debug log
https://debuglogs.org/f4d87cb41a8167edc7e5fe8af7f651d6c1f984458b601774b5195a8531a6849e

**Comment by sivaraam** [comment]
> - Register Signal
> - Restore backup

That's interesting. From my experience, I've been able to register only _after_ I restore the backup. How do you register before restoring the backup? 🤔

**Comment by johanw666** [comment]
Yes, I should have reversed the order of those.
