### ISSUE TITLE
when I changed the package name of the project I got many errors, here are they

### ISSUE THREAD

**Issue by zubairmahdihatef** [signalapp/Signal-Android#9842]
- [x] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
after many tries for renaming package name of this project I got the app installed fine ,
but when I press the camera icon the app crashes 
Actually it work very well before renaming the package name but after that it does'nt
So the problem exists in the way of renaming the package name 
How to do it in a perfect way because I am newbie in this field and it seems to be hard 
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** E/ubair.securesm: No implementation found for int org.zubair.securesms.util.FileUtils.createMemoryFileDescriptor(java.lang.String) (tried Java_org_zubair_securesms_util_FileUtils_createMemoryFileDescriptor and Java_org_zubair_securesms_util_FileUtils_createMemoryFileDescriptor__Ljava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.zubair.securesms, PID: 8842
    java.lang.UnsatisfiedLinkError: No implementation found for int org.zubair.securesms.util.FileUtils.createMemoryFileDescriptor(java.lang.String) (tried Java_org_zubair_securesms_util_FileUtils_createMemoryFileDescriptor and Java_org_zubair_securesms_util_FileUtils_createMemoryFileDescriptor__Ljava_lang_String_2)
        at org.zubair.securesms.util.FileUtils.createMemoryFileDescriptor(Native Method)
        at org.zubair.securesms.util.MemoryFileDescriptor.supported(MemoryFileDescriptor.java:36)
        at org.zubair.securesms.mms.MediaConstraints.isVideoTranscodeAvailable(MediaConstraints.java:79)
        at org.zubair.securesms.mediasend.CameraXFragment.isVideoRecordingSupported(CameraXFragment.java:303)
        at org.zubair.securesms.mediasend.CameraXFragment.initControls(CameraXFragment.java:247)
        at org.zubair.securesms.mediasend.CameraXFragment.onOrientationChanged(CameraXFragment.java:155)
        at org.zubair.securesms.mediasend.CameraXFragment.onViewCreated(CameraXFragment.java:122)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at org.zubair.securesms.BaseActivity.onStart(BaseActivity.java:46)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7978)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3472)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/SignalUncaughtExceptionHandler: java.lang.UnsatisfiedLinkError: No implementation found for int org.zubair.securesms.util.FileUtils.createMemoryFileDescriptor(java.lang.String) (tried Java_org_zubair_securesms_util_FileUtils_createMemoryFileDescriptor and Java_org_zubair_securesms_util_FileUtils_createMemoryFileDescriptor__Ljava_lang_String_2)
        at org.zubair.securesms.util.FileUtils.createMemoryFileDescriptor(Native Method)
        at org.zubair.securesms.util.MemoryFileDescriptor.supported(MemoryFileDescriptor.java:36)
        at org.zubair.securesms.mms.MediaConstraints.isVideoTranscodeAvailable(MediaConstraints.java:79)
        at org.zubair.securesms.mediasend.CameraXFragment.isVideoRecordingSupported(CameraXFragment.java:303)
        at org.zubair.securesms.mediasend.CameraXFragment.initControls(CameraXFragment.java:247)
        at org.zubair.securesms.mediasend.CameraXFragment.onOrientationChanged(CameraXFragment.java:155)
        at org.zubair.securesms.mediasend.CameraXFragment.onViewCreated(CameraXFragment.java:122) (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by alan-signal** [comment]
Please use the community forum for development help https://community.signalusers.org/
