### ISSUE TITLE
Registering leads to signal crash

### ISSUE THREAD

**Issue by bepaald** [signalapp/Signal-Android#9876]
Yesterday i tried to restore a backup and register, but after I entered my phone number to get the sms code, signal crashed. When re-opening signal, the app did recognize I was mid-registration and skipped basically to the 'enter your phone number' screen. After entering the phone number, signal crashed again. This attempt, I had adb logcat running, here is the relevant info (full llogcat available):

```
07-25 14:09:16.726 12022 12022 D RegistrationCodeRequest: SMS Verification requested
07-25 14:09:16.728 12022 12220 I TextSecurePreferences: Setting push registered: false
07-25 14:09:16.987 12022 12220 I PushChallengeRequest: Requesting a push challenge
07-25 14:09:16.989 12022 12220 D PushServiceSocket: Opening URL: <REDACTED>
07-25 14:09:17.629 12022 12231 I FcmReceiveService: FCM message... Delay: -614
07-25 14:09:17.629 12022 12231 D FcmReceiveService: Got a push challenge "3e1653902824247924cbc304832fe04e"
07-25 14:09:17.632 12022 12220 I PushChallengeRequest: Received a push challenge "3e1653902824247924cbc304832fe04e" in 644 ms
07-25 14:09:17.633 12022 12220 D PushServiceSocket: Opening URL: <REDACTED>
07-25 14:09:17.811 12022 12022 D LoggingFragment: [EnterCodeFragment] onCreate()
07-25 14:09:17.884 12022 12022 D LoggingFragment: [EnterCodeFragment] onStart()
07-25 14:09:17.893 12022 12022 D LoggingFragment: [EnterPhoneNumberFragmen] onStop()
07-25 14:09:19.766 12022 12022 I SmsListener: Got SMS broadcast...
07-25 14:09:19.766 12022 12022 I SmsListener: Constructing SmsReceiveJob...
07-25 14:09:19.775 12022 12054 I Job     : [JOB::0fa64717-02d6-4810-a721-c3a8bc0a0047][SmsReceiveJob] onSubmit() (Time Since Submission: 6 ms, Lifespan: Immortal, Run Attempt: 1/25)
07-25 14:09:19.779 12022 12065 I JobRunner: [JOB::0fa64717-02d6-4810-a721-c3a8bc0a0047][SmsReceiveJob][3] Running job. (Time Since Submission: 9 ms, Lifespan: Immortal, Run Attempt: 1/25)
07-25 14:09:19.781 12022 12065 D WakeLockUtil: Acquired wakelock with tag: signal:0fa64717-02d6-4810-a721-c3a8bc0a0047
07-25 14:09:19.781 12022 12022 I SmsListener: Got SMS broadcast...
07-25 14:09:19.782 12022 12065 E BaseJob : Encountered a fatal exception. Crash imminent.
07-25 14:09:19.782 12022 12065 E BaseJob : org.thoughtcrime.securesms.jobs.SmsReceiveJob$NotReadyException
07-25 14:09:19.782 12022 12065 E BaseJob :      at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:75)
07-25 14:09:19.782 12022 12065 E BaseJob :      at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
07-25 14:09:19.782 12022 12065 E BaseJob :      at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
07-25 14:09:19.782 12022 12065 E BaseJob :      at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
07-25 14:09:19.783 12022 12065 D WakeLockUtil: Released wakelock with tag: signal:0fa64717-02d6-4810-a721-c3a8bc0a0047
07-25 14:09:19.783 12022 12065 E JobRunner: [JOB::0fa64717-02d6-4810-a721-c3a8bc0a0047][SmsReceiveJob][3] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 13 ms, Lifespan: Immortal, Run Attempt: 1/25)
07-25 14:09:19.786 12022 12065 E SignalUncaughtExceptionHandler: 
07-25 14:09:19.786 12022 12065 E SignalUncaughtExceptionHandler: org.thoughtcrime.securesms.jobs.SmsReceiveJob$NotReadyException
07-25 14:09:19.786 12022 12065 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:75)
07-25 14:09:19.786 12022 12065 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
07-25 14:09:19.786 12022 12065 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
07-25 14:09:19.786 12022 12065 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
07-25 14:09:19.813 12022 12022 I RegistrationNavigationA: SmsRetrieverReceiver received a broadcast...
07-25 14:09:19.814 12022 12022 I RegistrationNavigationA: Received verification code.
07-25 14:09:19.834 12022 12065 I JobManager: Successfully flushed.
07-25 14:09:19.835 12022 12065 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-3
07-25 14:09:19.835 12022 12065 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12022
07-25 14:09:19.835 12022 12065 E AndroidRuntime: org.thoughtcrime.securesms.jobs.SmsReceiveJob$NotReadyException
07-25 14:09:19.835 12022 12065 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:75)
07-25 14:09:19.835 12022 12065 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
07-25 14:09:19.835 12022 12065 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
07-25 14:09:19.835 12022 12065 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
07-25 14:09:20.154 12022 12022 D LoggingFragment: [EnterCodeFragment] onStop()
07-25 14:09:20.157 12022 12022 D LoggingFragment: [EnterCodeFragment] onDestroy()
07-25 14:09:20.158 12022 12022 D LoggingFragment: [EnterPhoneNumberFragmen] onDestroy()
07-25 14:09:20.159 12022 12022 D LoggingFragment: [WelcomeFragment] onDestroy()
07-25 14:09:20.566 12022 12022 I ApplicationContext: App is no longer visible.
07-25 14:09:20.574 12022 12048 D IncomingMessageObserver: Network: true, Foreground: false, FCM: true, Censored: false, Registered: false, Websocket Registered: false
07-25 14:09:20.840 12022 12022 D AndroidRuntime: Shutting down VM
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler: 
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler: java.lang.IllegalStateException: Fragment EnterCodeFragment{b2320dd (507fbfd5-7122-4ad7-8287-3466ed4eb888)} not attached to an activity.
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at androidx.fragment.app.Fragment.requireActivity(Fragment.java:802)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.EnterCodeFragment.lambda$setOnCodeFullyEnteredListener$6$EnterCodeFragment(EnterCodeFragment.java:107)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.-$$Lambda$EnterCodeFragment$5FBxIpLknvOw0hsN2Wh9oOZAGv8.onCodeComplete(lambda)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.components.registration.VerificationCodeView.append(VerificationCodeView.java:107)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.EnterCodeFragment.lambda$onVerificationCodeReceived$7$EnterCodeFragment(EnterCodeFragment.java:224)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at org.thoughtcrime.securesms.registration.fragments.-$$Lambda$EnterCodeFragment$TCMWcTFd728b1QMPLrDThQrjhmc.run(lambda)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at android.os.Handler.handleCallback(Handler.java:751)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at android.os.Looper.loop(Looper.java:241)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at android.app.ActivityThread.main(ActivityThread.java:6274)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at java.lang.reflect.Method.invoke(Native Method)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-25 14:09:20.845 12022 12022 E SignalUncaughtExceptionHandler:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-25 14:09:20.889 12022 12022 I JobManager: Successfully flushed.
07-25 14:09:20.889 12022 12022 I Process : Sending signal. PID: 12022 SIG: 9
```

[logcat_grepped.txt](https://github.com/signalapp/Signal-Android/files/4977933/logcat_grepped.txt)

I do not think it has anything to do with the backup restore, as I - just about an hour ago - cleared all signal data and restarted the registration, this time skipping the backup restore. The same thing happened, this time I told android to send the info so there is probably a crash report from google.

I am not at home at the moment so I have to do the device info from memory, let me know if you need more details and I'll provide them at a later time. The device is a Sony Xperia Z5C, running unrooted, android 7(dot-something) and whatever the beta version of signal was yesterday (but I do not know if the problem only happens in the current beta).

Thanks!

**Comment by bepaald** [comment]
So, I think what was happening is that signal was still the default sms handler (because it wasn't a fresh install, I just cleared all data to start clean), but it wasn't able to handle the incoming (registration) sms because the setup was not complete. After I set a different default sms handler, I just manually entered the code that arrived in the other messaging app and signal completed registration successfully.

Not 100% sure that was the problem, but maybe you could confirm from the logcat. Also not sure if this is a situation you want to gracefully handle in the app. If not, this bug report could be closed.

Thanks!

**Comment by rgilton** [comment]
I encountered a similar problem with the app crashing after backup restoration and upon receiving the confirmation SMS.  The workaround @bepaald described of setting a different default SMS handler during setup worked here too -- thanks!
