### ISSUE TITLE
opening existing chat crashes Signal since 4.69.0

### ISSUE THREAD

**Issue by Trombonista** [signalapp/Signal-Android#9933]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Opening any (existing) chat from main screen always crashes Signal.

### Steps to reproduce
- open signal
- have existing chats or get a notification
- open chat via main screen or use notification to jump into chat

**Actual result:** Signal crashes always
**Expected result:** Chat gets opened

### Device info
**Device:** Samsung S4mini GT-I9195
**Android version:** 4.4.2
**Signal version:** 4.69.0 and 4.69.1

2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.conversation.ConversationActivity}: android.view.InflateException: Binary XML file line #53: Error inflating class org.thoughtcrime.securesms.components.ConversationScrollToView
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.access$900(ActivityThread.java:174)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:102)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.os.Looper.loop(Looper.java:146)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:5593)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Method.invokeNative(Native Method)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Method.invoke(Method.java:515)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at dalvik.system.NativeStart.main(Native Method)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: Caused by: android.view.InflateException: Binary XML file line #53: Error inflating class org.thoughtcrime.securesms.components.ConversationScrollToView
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.conversation.ConversationFragment.onCreateView(ConversationFragment.java:202)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.BaseActivity.onStart(BaseActivity.java:46)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.Activity.performStart(Activity.java:5468)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	... 11 more
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: Caused by: java.lang.reflect.InvocationTargetException
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Constructor.constructNative(Native Method)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.view.LayoutInflater.createView(LayoutInflater.java:600)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	... 34 more
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_at_24.xml from drawable resource ID #0x7f080104
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.content.res.Resources.loadDrawable(Resources.java:3443)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.components.ConversationScrollToView.<init>(ConversationScrollToView.java:39)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at org.thoughtcrime.securesms.components.ConversationScrollToView.<init>(ConversationScrollToView.java:26)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	... 37 more
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	at android.content.res.Resources.loadDrawable(Resources.java:3439)
2020-08-18 14:50:45.494 MESZ E SignalUncaughtExceptionHandler: 	... 40 more

Feedback via Google Play Beta program feedback does not seem to be used?!?!?

**Comment by Trombonista** [comment]
Thank you, 4.69.3 works for me.
