### ISSUE TITLE
Crash on startup in crypto.KeyStoreHelper.unseal()

### ISSUE THREAD

**Issue by Svintooo** [signalapp/Signal-Android#9943]
_Title:_ | Crash on startup: javax.crypto.AEADBadTagException
----------|--------------------------------------------

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

- - - - - - - - - -

#### Bug description

Signal Android app Suddenly started crashing one morning when I try to start it.

Installed Signal year 2017 on Android 7 (LineAgeOS 14.1). Signal was still working after upgrading to Android 9, which I did 1-2 months ago (during summer 2020).
Then suddenly Signal worked perfectly one evening but stopped working next morning. No updates was made during that time.

I have installed updates to Signal app after this but it still crashes.

Signal seems to work fine after clearing app data (backed up with Titanium Backup first and restored data after testing).

#### Device info

**Device:** Samsung Galaxy S5

**Android version:** LineAgeOS 16.0 (Android 9)

**Signal version:** 4.69.4.69410

#### Debug log

```
08-20 22:03:22.085 18762 18762 E AndroidRuntime: FATAL EXCEPTION: main
08-20 22:03:22.085 18762 18762 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 18762
08-20 22:03:22.085 18762 18762 E AndroidRuntime: java.lang.AssertionError: javax.crypto.AEADBadTagException
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:75)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.logging.LogSecretProvider.parseEncryptedSecret(LogSecretProvider.java:36)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.logging.LogSecretProvider.getOrCreateAttachmentSecret(LogSecretProvider.java:21)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.logging.PersistentLogger.<init>(PersistentLogger.java:51)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.initializeLogging(ApplicationContext.java:217)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:111)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-20 22:03:22.085 18762 18762 E AndroidRuntime: Caused by: javax.crypto.AEADBadTagException
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.KeyStoreHelper.unseal(KeyStoreHelper.java:73)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        ... 16 more
08-20 22:03:22.085 18762 18762 E AndroidRuntime: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.security.KeyStore.getKeyStoreException(KeyStore.java:850)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
08-20 22:03:22.085 18762 18762 E AndroidRuntime:        ... 18 more
```

#### Question

Is there any chance of me restoring my data? Or must I delete app data and start anew?
I am willing to get my hands dirty if there is anything I can do on my end.

**Comment by Svintooo** [comment]
Right after posting I found closed issue #8130. If I understand it correctly I broke Signal further when I restored app data from TitaniumBackup.

The debug log is after restoring from TitaniumBackup. I didn't fetch a debug log before that.

So I guess you can close this issue.
