### ISSUE TITLE
Signal crashes when you pull down a conversation past the beginning with a new contact

### ISSUE THREAD

**Issue by szotsaki** [signalapp/Signal-Android#9954]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
1. Have a new contact. The essence is that you should have only half-screen height conversation so far. In my case it was 2-2 small sentences. You cannot pull up or down the conversation.
2. Open the keyboard which now allows you to pull the conversation vertically.
3. Pull in downwards direction (so the conversation goes up).

Even without releasing it, Signal crashes.

### Device info

**Device:** Sony XPERIA X (F1521)
**Android version:** 8.0.0
**Signal version:** 4.68.8

### Link to debug log
https://debuglogs.org/7a0745b03df80bc1aba086a0abea81edadf4344cea290b35ee6bf151c839a5eb

**Comment by szotsaki** [comment]
Can be reproduced with the latest version, 4.69.4. The backtrace is quite similar there:
```
08-24 11:20:03.918 15672 15672 E AndroidRuntime: FATAL EXCEPTION: main
08-24 11:20:03.918 15672 15672 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 15672
08-24 11:20:03.918 15672 15672 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.paging.PagedList.loadAround(PagedList.java:424)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.paging.AsyncPagedListDiffer.getItem(AsyncPagedListDiffer.java:216)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.paging.PagedListAdapter.getItem(PagedListAdapter.java:176)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationAdapter.getItem(ConversationAdapter.java:262)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationScrollListener.postMarkAsReadRequest(ConversationFragment.java:1090)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationFragment$ConversationScrollListener.onScrolled(ConversationFragment.java:1071)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:1971)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3391)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:11731)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2955)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:453)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationActivity.dispatchTouchEvent(ConversationActivity.java:578)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:415)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:11970)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4790)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4604)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4142)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4195)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4161)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4288)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4169)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4345)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4142)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4195)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4161)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4169)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4142)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6663)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6637)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6598)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6766)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6737)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6789)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:707)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6589)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-24 11:20:03.918 15672 15672 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
