### ISSUE TITLE
Zombie messages never fully load and reappear after being deleted

### ISSUE THREAD

**Issue by reglos** [signalapp/Signal-Android#9976]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

The Signal system fails to fully load and delete some old received images. 

These zombie messages, several month old images, start to load but are never displayed. 
They can be deleted but reappear after about 24 hours.
It happens on all linked devices, Android and Desktop. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

I don't know how to create new Zombies.
The old ones just re-appear every day automatically.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

As it happens both on the Android and the Desktop client (multiple versions since April), 
I assume it is rather a server side problem, probably a data base corruption?

**Comment by Nisc3d** [comment]
A debug log that was captured immediately after the issue  occured would be helpful to the developers. Here is how to capture a debug log: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports

**Comment by Nisc3d** [comment]
Ironically I had the same issue today. Someone sent me 10 pictures in a group but 2 of them keep downloading, but it doesn't finish. Not on Android and not on the desktop App. And I don't want to delete them, because I think that could cause more problems.

Screenshot:
![signal-2020-08-30-223901](https://user-images.githubusercontent.com/7361310/91669031-02f87f00-eb12-11ea-9ae0-ffc21b4a8e84.png)
 
At first I thought my phone had a problem, but after a restart it still didn't download. Other members of the group confirmed, that they had the same problem. The person who sent the images also sent all of them again to me in a private chat and there was no issue with these specific images there.

So here is the debug log for Android:
Device: Asus Zenfone 6
Android version: 10
Signal version: 4.70.3
https://debuglogs.org/7a925130665178bba8ac68714b1d79fd50adbb784dd691876f5bb43cf21b0189

It happens at around 22:17 and I think this could be the relevant Exception:

> 2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: Experienced exception while trying to download an attachment.
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: org.whispersystems.libsignal.InvalidMessageException: org.whispersystems.libsignal.InvalidMacException: MAC doesn't match!
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherInputStream.createForAttachment(AttachmentCipherInputStream.java:84)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveAttachment(SignalServiceMessageReceiver.java:190)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrieveAttachment(AttachmentDownloadJob.java:168)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.doWork(AttachmentDownloadJob.java:140)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(AttachmentDownloadJob.java:110)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:25)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:85)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:48)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: Caused by: org.whispersystems.libsignal.InvalidMacException: MAC doesn't match!
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherInputStream.verifyMac(AttachmentCipherInputStream.java:245)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	at org.whispersystems.signalservice.api.crypto.AttachmentCipherInputStream.createForAttachment(AttachmentCipherInputStream.java:71)
2020-08-30 22:17:21.760 MESZ W AttachmentDownloadJob: 	... 7 more

Also I see, that it still trys to download it after that.

Here is the debug log for the Desktop App running on Arch Linux, it happens at 20:17 there:
https://debuglogs.org/eb6a7c40eee97ba8cf093a0aef466cb0c6d2d731c6ea96f81df62e5856f96591

And the same Error, that was on Android:

> ERROR 2020-08-30T20:17:21.655Z _runJob: Failed to download attachment type attachment for message +[REDACTED]279.1 1598818629602, attempt 1: Error: Bad MAC
    at file://[REDACTED]/app.asar/js/libtextsecure.js:35312:23
    at async MessageReceiverInner.downloadAttachment ([REDACTED]/app.asar/ts/textsecure/MessageReceiver.js:1120:28)
    at async downloadAttachment ([REDACTED]/app.asar/ts/util/downloadAttachment.js:10:22)
    at async _runJob ([REDACTED]/app.asar/js/modules/attachment_downloads.js:193:24)

**Comment by alan-signal** [comment]
@reglos 

- Do the messages come from just one sender?
  - If so do you know what OS they are using?
- Have these messages started recently or has this been happening for months, ever since the message was first sent?

@Nisc3d I think you have the same symptom, but not the same issue as your message was a new one, not months old like the OP. Can you tell me what OS the sender was using to send these pictures?

**Comment by Nisc3d** [comment]
The sender was using Android 9 on a Nokia 6.

**Comment by reglos** [comment]
This is the debug log right after three "zombie" messages reappeared
https://debuglogs.org/9d62407bcefd04fab797c33150d556c89ca67e04291b857d109a14fd9ab304d1

>> Do the messages come from just one sender?
yes - three images sent in a short interval back in April

>>    If so do you know what OS they are using?
IOS or Signal Desktop on Linux

>> Have these messages started recently or has this been happening for months, ever since the message was first sent?
It happened for month
